import type { Kanji } from './types'

// N4: 207 kanji

export const kanjiN4: Kanji[] = [
  { rank:3, k:'国', level:'N4', meanings:['país','nación'], on:['コク'], kun:['くに'],
    words:[{w:'外国',f:'がいこく',m:'extranjero (país)',l:'N5'},{w:'国語',f:'こくご',m:'lengua nacional',l:'N5'},{w:'中国',f:'ちゅうごく',m:'China',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'}]},
  { rank:4, k:'会', level:'N4', meanings:['reunión','encontrar'], on:['カイ','エ'], kun:['あ.う'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},{w:'会話',f:'かいわ',m:'conversación',l:'N4'},{w:'社会',f:'しゃかい',m:'sociedad',l:'N4'},{w:'会議',f:'かいぎ',m:'reunión',l:'N4'}]},
  { rank:15, k:'同', level:'N4', meanings:['igual','mismo'], on:['ドウ'], kun:['おな.じ'],
    words:[{w:'同時',f:'どうじ',m:'al mismo tiempo',l:'N4'},{w:'同意',f:'どうい',m:'acuerdo',l:'N3'},{w:'共同',f:'きょうどう',m:'conjunto / común',l:'N3'}]},
  { rank:19, k:'自', level:'N4', meanings:['uno mismo'], on:['ジ','シ'], kun:['みずか.ら'],
    words:[{w:'自分',f:'じぶん',m:'uno mismo',l:'N5'},{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},{w:'自然',f:'しぜん',m:'naturaleza',l:'N4'},{w:'自由',f:'じゆう',m:'libertad',l:'N4'}]},
  { rank:21, k:'社', level:'N4', meanings:['empresa','sociedad','santuario'], on:['シャ'], kun:['やしろ'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},{w:'神社',f:'じんじゃ',m:'santuario sintoísta',l:'N4'},{w:'社会',f:'しゃかい',m:'sociedad',l:'N4'}]},
  { rank:26, k:'後', level:'N4', meanings:['después','detrás'], on:['ゴ','コウ'], kun:['あと','うし.ろ'],
    words:[{w:'午後',f:'ごご',m:'tarde (PM)',l:'N5'},{w:'最後',f:'さいご',m:'último / final',l:'N4'},{w:'後輩',f:'こうはい',m:'júnior / novato',l:'N3'}]},
  { rank:27, k:'前', level:'N4', meanings:['delante','antes'], on:['ゼン'], kun:['まえ'],
    words:[{w:'名前',f:'なまえ',m:'nombre',l:'N5'},{w:'午前',f:'ごぜん',m:'de la mañana (AM)',l:'N5'},{w:'駅前',f:'えきまえ',m:'frente a la estación',l:'N5'}]},
  { rank:32, k:'発', level:'N4', meanings:['partir','emitir','publicar'], on:['ハツ','ホツ'], kun:[],
    words:[{w:'出発',f:'しゅっぱつ',m:'partida / salida',l:'N5'},{w:'発表',f:'はっぴょう',m:'presentación / anuncio',l:'N4'},{w:'発音',f:'はつおん',m:'pronunciación',l:'N4'}]},
  { rank:40, k:'地', level:'N4', meanings:['tierra','terreno'], on:['チ','ジ'], kun:[],
    words:[{w:'地図',f:'ちず',m:'mapa',l:'N5'},{w:'地下',f:'ちか',m:'subterráneo',l:'N4'},{w:'土地',f:'とち',m:'terreno',l:'N4'}]},
  { rank:52, k:'場', level:'N4', meanings:['lugar','sitio'], on:['ジョウ'], kun:['ば'],
    words:[{w:'場所',f:'ばしょ',m:'lugar',l:'N5'},{w:'工場',f:'こうじょう',m:'fábrica',l:'N4'},{w:'広場',f:'ひろば',m:'plaza',l:'N4'},{w:'駐車場',f:'ちゅうしゃじょう',m:'aparcamiento',l:'N4'}]},
  { rank:59, k:'開', level:'N4', meanings:['abrir','inaugurar'], on:['カイ'], kun:['ひら.く','あ.ける'],
    words:[{w:'開始',f:'かいし',m:'comienzo',l:'N4'},{w:'開店',f:'かいてん',m:'apertura de tienda',l:'N3'}]},
  { rank:64, k:'問', level:'N4', meanings:['pregunta','problema'], on:['モン'], kun:['と.う'],
    words:[{w:'質問',f:'しつもん',m:'pregunta',l:'N5'},{w:'問題',f:'もんだい',m:'problema / pregunta',l:'N5'},{w:'訪問',f:'ほうもん',m:'visita',l:'N4'}]},
  { rank:73, k:'動', level:'N4', meanings:['mover','moverse'], on:['ドウ'], kun:['うご.く'],
    words:[{w:'動物',f:'どうぶつ',m:'animal',l:'N5'},{w:'運動',f:'うんどう',m:'ejercicio / movimiento',l:'N4'},{w:'活動',f:'かつどう',m:'actividad',l:'N4'},{w:'自動',f:'じどう',m:'automático',l:'N4'},{w:'感動',f:'かんどう',m:'emoción / conmoción',l:'N4'}]},
  { rank:74, k:'京', level:'N4', meanings:['capital'], on:['キョウ','ケイ'], kun:[],
    words:[{w:'東京',f:'とうきょう',m:'Tokio',l:'N5'},{w:'京都',f:'きょうと',m:'Kioto',l:'N5'}]},
  { rank:80, k:'通', level:'N4', meanings:['pasar','circular','comunicar'], on:['ツウ'], kun:['とお.る','かよ.う'],
    words:[{w:'交通',f:'こうつう',m:'tráfico',l:'N4'},{w:'通勤',f:'つうきん',m:'desplazamiento al trabajo',l:'N4'},{w:'普通',f:'ふつう',m:'normal / corriente',l:'N4'}]},
  { rank:86, k:'理', level:'N4', meanings:['razón','principio'], on:['リ'], kun:[],
    words:[{w:'料理',f:'りょうり',m:'cocina / plato',l:'N5'},{w:'理由',f:'りゆう',m:'razón / motivo',l:'N4'},{w:'理解',f:'りかい',m:'comprensión',l:'N4'},{w:'管理',f:'かんり',m:'gestión / administración',l:'N4'}]},
  { rank:95, k:'主', level:'N4', meanings:['dueño','principal','señor'], on:['シュ'], kun:['ぬし','おも'],
    words:[{w:'主人',f:'しゅじん',m:'marido / dueño',l:'N5'},{w:'主語',f:'しゅご',m:'sujeto (gramática)',l:'N4'},{w:'主婦',f:'しゅふ',m:'ama de casa',l:'N4'},{w:'主役',f:'しゅやく',m:'protagonista',l:'N3'}]},
  { rank:96, k:'題', level:'N4', meanings:['tema','título','problema'], on:['ダイ'], kun:[],
    words:[{w:'問題',f:'もんだい',m:'problema',l:'N5'},{w:'宿題',f:'しゅくだい',m:'tarea / deberes',l:'N5'},{w:'題名',f:'だいめい',m:'título',l:'N4'},{w:'話題',f:'わだい',m:'tema de conversación',l:'N4'}]},
  { rank:101, k:'不', level:'N4', meanings:['no-','in-','negación'], on:['フ','ブ'], kun:[],
    words:[{w:'不便',f:'ふべん',m:'inconveniente',l:'N4'},{w:'不安',f:'ふあん',m:'ansiedad / inquietud',l:'N4'},{w:'不満',f:'ふまん',m:'insatisfacción',l:'N4'},{w:'不思議',f:'ふしぎ',m:'misterioso',l:'N4'}]},
  { rank:103, k:'作', level:'N4', meanings:['hacer','crear','fabricar'], on:['サク','サ'], kun:['つく.る'],
    words:[{w:'作品',f:'さくひん',m:'obra',l:'N4'},{w:'作文',f:'さくぶん',m:'composición escrita',l:'N4'},{w:'工作',f:'こうさく',m:'manualidades',l:'N4'}]},
  { rank:112, k:'強', level:'N4', meanings:['fuerte'], on:['キョウ','ゴウ'], kun:['つよ.い'],
    words:[{w:'勉強',f:'べんきょう',m:'estudio',l:'N5'},{w:'強力',f:'きょうりょく',m:'potente',l:'N3'},{w:'強調',f:'きょうちょう',m:'énfasis',l:'N3'}]},
  { rank:118, k:'公', level:'N4', meanings:['público','oficial'], on:['コウ','ク'], kun:[],
    words:[{w:'公園',f:'こうえん',m:'parque público',l:'N5'},{w:'公務員',f:'こうむいん',m:'funcionario público',l:'N4'}]},
  { rank:119, k:'持', level:'N4', meanings:['sostener','tener'], on:['ジ'], kun:['も.つ'],
    words:[{w:'気持ち',f:'きもち',m:'sentimiento',l:'N5'},{w:'持参',f:'じさん',m:'traer consigo',l:'N4'},{w:'支持',f:'しじ',m:'apoyo',l:'N3'},{w:'所持',f:'しょじ',m:'posesión',l:'N3'}]},
  { rank:120, k:'野', level:'N4', meanings:['campo','llanura'], on:['ヤ'], kun:['の'],
    words:[{w:'野菜',f:'やさい',m:'verdura',l:'N5'},{w:'野球',f:'やきゅう',m:'béisbol',l:'N4'},{w:'野外',f:'やがい',m:'al aire libre',l:'N4'}]},
  { rank:132, k:'思', level:'N4', meanings:['pensar','sentir'], on:['シ'], kun:['おも.う'],
    words:[{w:'思い出',f:'おもいで',m:'recuerdo',l:'N4'},{w:'不思議',f:'ふしぎ',m:'misterioso / extraño',l:'N4'},{w:'思考',f:'しこう',m:'pensamiento',l:'N3'},{w:'思想',f:'しそう',m:'ideología',l:'N3'}]},
  { rank:133, k:'家', level:'N4', meanings:['casa','hogar','familia'], on:['カ','ケ'], kun:['いえ','や'],
    words:[{w:'家族',f:'かぞく',m:'familia',l:'N5'},{w:'家庭',f:'かてい',m:'hogar',l:'N4'},{w:'家具',f:'かぐ',m:'muebles',l:'N4'},{w:'家賃',f:'やちん',m:'alquiler',l:'N4'}]},
  { rank:135, k:'世', level:'N4', meanings:['generación','mundo','era'], on:['セイ','セ'], kun:['よ'],
    words:[{w:'世界',f:'せかい',m:'mundo',l:'N5'},{w:'世話',f:'せわ',m:'cuidado / ayuda',l:'N4'},{w:'世代',f:'せだい',m:'generación',l:'N4'}]},
  { rank:143, k:'正', level:'N4', meanings:['correcto','justo','recto'], on:['セイ','ショウ'], kun:['ただ.しい','まさ'],
    words:[{w:'正月',f:'しょうがつ',m:'año nuevo',l:'N5'},{w:'正直',f:'しょうじき',m:'honesto',l:'N4'},{w:'正確',f:'せいかく',m:'exacto / preciso',l:'N4'}]},
  { rank:150, k:'院', level:'N4', meanings:['institución','templo','hospital'], on:['イン'], kun:[],
    words:[{w:'病院',f:'びょういん',m:'hospital',l:'N5'},{w:'美容院',f:'びよういん',m:'peluquería',l:'N4'},{w:'大学院',f:'だいがくいん',m:'posgrado',l:'N4'},{w:'入院',f:'にゅういん',m:'hospitalización',l:'N4'}]},
  { rank:154, k:'午', level:'N4', meanings:['mediodía'], on:['ゴ'], kun:[],
    words:[{w:'午前',f:'ごぜん',m:'de la mañana (AM)',l:'N5'},{w:'午後',f:'ごご',m:'tarde (PM)',l:'N5'},{w:'正午',f:'しょうご',m:'mediodía',l:'N4'}]},
  { rank:157, k:'心', level:'N4', meanings:['corazón','mente'], on:['シン'], kun:['こころ'],
    words:[{w:'安心',f:'あんしん',m:'tranquilidad',l:'N4'},{w:'心配',f:'しんぱい',m:'preocupación',l:'N4'},{w:'中心',f:'ちゅうしん',m:'centro',l:'N4'},{w:'関心',f:'かんしん',m:'interés / inquietud',l:'N4'},{w:'熱心',f:'ねっしん',m:'entusiasta / dedicado',l:'N4'}]},
  { rank:158, k:'界', level:'N4', meanings:['mundo','frontera','ámbito'], on:['カイ'], kun:[],
    words:[{w:'世界',f:'せかい',m:'mundo',l:'N5'},{w:'限界',f:'げんかい',m:'límite',l:'N3'},{w:'業界',f:'ぎょうかい',m:'sector industrial',l:'N3'}]},
  { rank:166, k:'教', level:'N4', meanings:['enseñar'], on:['キョウ'], kun:['おし.える'],
    words:[{w:'教室',f:'きょうしつ',m:'aula',l:'N5'},{w:'教育',f:'きょういく',m:'educación',l:'N4'},{w:'教科書',f:'きょうかしょ',m:'libro de texto',l:'N4'}]},
  { rank:190, k:'文', level:'N4', meanings:['texto','escritura'], on:['ブン','モン'], kun:['ふみ'],
    words:[{w:'文化',f:'ぶんか',m:'cultura',l:'N4'},{w:'作文',f:'さくぶん',m:'redacción',l:'N4'},{w:'文法',f:'ぶんぽう',m:'gramática',l:'N4'}]},
  { rank:193, k:'重', level:'N4', meanings:['pesado','importante'], on:['ジュウ','チョウ'], kun:['おも.い','かさ.なる'],
    words:[{w:'重要',f:'じゅうよう',m:'importante',l:'N4'},{w:'体重',f:'たいじゅう',m:'peso corporal',l:'N4'},{w:'貴重',f:'きちょう',m:'valioso',l:'N3'}]},
  { rank:194, k:'近', level:'N4', meanings:['cerca'], on:['キン'], kun:['ちか.い'],
    words:[{w:'近所',f:'きんじょ',m:'vecindario',l:'N4'},{w:'最近',f:'さいきん',m:'recientemente',l:'N4'}]},
  { rank:196, k:'考', level:'N4', meanings:['considerar','pensar'], on:['コウ'], kun:['かんが.える'],
    words:[{w:'参考',f:'さんこう',m:'referencia',l:'N4'},{w:'思考',f:'しこう',m:'pensamiento',l:'N3'}]},
  { rank:199, k:'画', level:'N4', meanings:['imagen','trazar','planificar'], on:['ガ','カク'], kun:['かく','えが.く'],
    words:[{w:'映画',f:'えいが',m:'película',l:'N5'},{w:'計画',f:'けいかく',m:'plan',l:'N4'},{w:'画家',f:'がか',m:'pintor / artista',l:'N4'},{w:'漫画',f:'まんが',m:'manga / cómic',l:'N4'}]},
  { rank:200, k:'海', level:'N4', meanings:['mar'], on:['カイ'], kun:['うみ'],
    words:[{w:'海外',f:'かいがい',m:'extranjero / ultramar',l:'N4'},{w:'日本海',f:'にほんかい',m:'Mar de Japón',l:'N4'},{w:'海岸',f:'かいがん',m:'costa / playa',l:'N4'},{w:'海水',f:'かいすい',m:'agua de mar',l:'N4'}]},
  { rank:202, k:'売', level:'N4', meanings:['vender'], on:['バイ'], kun:['う.る'],
    words:[{w:'売り場',f:'うりば',m:'mostrador de ventas',l:'N4'},{w:'売買',f:'ばいばい',m:'compraventa',l:'N4'},{w:'販売',f:'はんばい',m:'venta',l:'N4'}]},
  { rank:205, k:'知', level:'N4', meanings:['saber','conocer'], on:['チ'], kun:['し.る'],
    words:[{w:'知識',f:'ちしき',m:'conocimiento',l:'N4'},{w:'知人',f:'ちじん',m:'conocido',l:'N4'},{w:'通知',f:'つうち',m:'notificación / aviso',l:'N4'}]},
  { rank:207, k:'道', level:'N4', meanings:['camino','vía','arte'], on:['ドウ','トウ'], kun:['みち'],
    words:[{w:'道路',f:'どうろ',m:'carretera',l:'N4'},{w:'茶道',f:'ちゃどう',m:'ceremonia del té',l:'N4'}]},
  { rank:210, k:'集', level:'N4', meanings:['reunir','congregar'], on:['シュウ'], kun:['あつ.める'],
    words:[{w:'集合',f:'しゅうごう',m:'reunión / punto de encuentro',l:'N4'},{w:'集中',f:'しゅうちゅう',m:'concentración',l:'N4'}]},
  { rank:219, k:'使', level:'N4', meanings:['usar'], on:['シ'], kun:['つか.う'],
    words:[{w:'使い方',f:'つかいかた',m:'forma de usar',l:'N5'},{w:'使用',f:'しよう',m:'uso / utilización',l:'N4'}]},
  { rank:225, k:'品', level:'N4', meanings:['artículo','producto','calidad'], on:['ヒン','ピン'], kun:['しな'],
    words:[{w:'品物',f:'しなもの',m:'artículo / mercancía',l:'N4'},{w:'作品',f:'さくひん',m:'obra',l:'N4'},{w:'食品',f:'しょくひん',m:'alimento / producto alimenticio',l:'N4'}]},
  { rank:228, k:'計', level:'N4', meanings:['medir','calcular','plan'], on:['ケイ'], kun:['はか.る'],
    words:[{w:'時計',f:'とけい',m:'reloj',l:'N5'},{w:'計画',f:'けいかく',m:'plan',l:'N4'},{w:'合計',f:'ごうけい',m:'total',l:'N4'},{w:'計算',f:'けいさん',m:'cálculo',l:'N4'}]},
  { rank:234, k:'特', level:'N4', meanings:['especial','particular'], on:['トク'], kun:[],
    words:[{w:'特別',f:'とくべつ',m:'especial',l:'N4'},{w:'特急',f:'とっきゅう',m:'tren expreso',l:'N4'}]},
  { rank:242, k:'私', level:'N4', meanings:['yo','privado'], on:['シ'], kun:['わたし','わたくし'],
    words:[{w:'私立',f:'しりつ',m:'privado',l:'N4'}]},
  { rank:244, k:'始', level:'N4', meanings:['comenzar'], on:['シ'], kun:['はじ.める','はじ.まる'],
    words:[{w:'開始',f:'かいし',m:'inicio',l:'N4'},{w:'始発',f:'しはつ',m:'primer tren / primera salida',l:'N4'},{w:'年始',f:'ねんし',m:'comienzo del año',l:'N4'}]},
  { rank:248, k:'朝', level:'N4', meanings:['mañana'], on:['チョウ'], kun:['あさ'],
    words:[{w:'毎朝',f:'まいあさ',m:'cada mañana',l:'N5'},{w:'今朝',f:'けさ',m:'esta mañana',l:'N5'},{w:'朝食',f:'ちょうしょく',m:'desayuno',l:'N4'}]},
  { rank:255, k:'運', level:'N4', meanings:['transportar','suerte','destino'], on:['ウン'], kun:['はこ.ぶ'],
    words:[{w:'運転',f:'うんてん',m:'conducción',l:'N5'},{w:'運動',f:'うんどう',m:'ejercicio / movimiento',l:'N4'},{w:'幸運',f:'こううん',m:'buena suerte',l:'N4'}]},
  { rank:256, k:'終', level:'N4', meanings:['terminar','fin'], on:['シュウ'], kun:['お.わる'],
    words:[{w:'終電',f:'しゅうでん',m:'último tren',l:'N4'},{w:'最終',f:'さいしゅう',m:'último / final',l:'N4'},{w:'終点',f:'しゅうてん',m:'terminal / última parada',l:'N4'}]},
  { rank:262, k:'台', level:'N4', meanings:['plataforma','pedestal','contador de vehículos'], on:['ダイ','タイ'], kun:['うてな'],
    words:[{w:'台所',f:'だいどころ',m:'cocina',l:'N5'},{w:'台風',f:'たいふう',m:'tifón',l:'N4'},{w:'舞台',f:'ぶたい',m:'escenario',l:'N4'}]},
  { rank:263, k:'広', level:'N4', meanings:['amplio'], on:['コウ'], kun:['ひろ.い'],
    words:[{w:'広告',f:'こうこく',m:'publicidad',l:'N4'},{w:'広場',f:'ひろば',m:'plaza',l:'N4'}]},
  { rank:270, k:'住', level:'N4', meanings:['residir','vivir en'], on:['ジュウ'], kun:['す.む'],
    words:[{w:'住所',f:'じゅうしょ',m:'dirección',l:'N4'},{w:'住民',f:'じゅうみん',m:'residente',l:'N4'},{w:'住宅',f:'じゅうたく',m:'vivienda',l:'N4'}]},
  { rank:270, k:'様', level:'N4', meanings:['manera','señor/señora'], on:['ヨウ'], kun:['さま'],
    words:[{w:'様子',f:'ようす',m:'estado / apariencia',l:'N4'},{w:'同様',f:'どうよう',m:'de la misma manera',l:'N3'},{w:'お客様',f:'おきゃくさま',m:'cliente / huésped',l:'N3'}]},
  { rank:279, k:'真', level:'N4', meanings:['verdad','realidad','auténtico'], on:['シン'], kun:['ま','まこと'],
    words:[{w:'写真',f:'しゃしん',m:'fotografía',l:'N5'},{w:'真剣',f:'しんけん',m:'serio / en serio',l:'N4'},{w:'真っ直ぐ',f:'まっすぐ',m:'recto / directo',l:'N4'}]},
  { rank:282, k:'有', level:'N4', meanings:['tener','existir','poseer'], on:['ユウ','ウ'], kun:['あ.る'],
    words:[{w:'有名',f:'ゆうめい',m:'famoso',l:'N5'},{w:'有料',f:'ゆうりょう',m:'de pago',l:'N4'}]},
  { rank:287, k:'合', level:'N4', meanings:['combinar','concordar'], on:['ゴウ','ガッ'], kun:['あ.う'],
    words:[{w:'場合',f:'ばあい',m:'caso / situación',l:'N4'},{w:'合格',f:'ごうかく',m:'aprobado',l:'N3'},{w:'都合',f:'つごう',m:'conveniencia',l:'N3'}]},
  { rank:295, k:'料', level:'N4', meanings:['tarifa','ingrediente'], on:['リョウ'], kun:[],
    words:[{w:'料理',f:'りょうり',m:'cocina / plato',l:'N5'},{w:'料金',f:'りょうきん',m:'tarifa / precio',l:'N4'},{w:'材料',f:'ざいりょう',m:'ingredientes / materiales',l:'N4'},{w:'無料',f:'むりょう',m:'gratis',l:'N4'},{w:'有料',f:'ゆうりょう',m:'de pago',l:'N4'}]},
  { rank:299, k:'工', level:'N4', meanings:['artesanía','construcción','trabajo'], on:['コウ','ク'], kun:[],
    words:[{w:'工場',f:'こうじょう',m:'fábrica',l:'N4'},{w:'工事',f:'こうじ',m:'obra / construcción',l:'N4'}]},
  { rank:301, k:'語', level:'N4', meanings:['idioma','palabra'], on:['ゴ'], kun:['かた.る'],
    words:[{w:'日本語',f:'にほんご',m:'japonés',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},{w:'言語',f:'げんご',m:'idioma',l:'N4'}]},
  { rank:302, k:'部', level:'N4', meanings:['sección','departamento','parte'], on:['ブ'], kun:[],
    words:[{w:'全部',f:'ぜんぶ',m:'todo',l:'N4'},{w:'部分',f:'ぶぶん',m:'parte',l:'N4'},{w:'部長',f:'ぶちょう',m:'jefe de departamento',l:'N3'}]},
  { rank:303, k:'市', level:'N4', meanings:['ciudad','mercado'], on:['シ'], kun:['いち'],
    words:[{w:'市民',f:'しみん',m:'ciudadano',l:'N3'},{w:'市場',f:'いちば',m:'mercado',l:'N3'},{w:'都市',f:'とし',m:'ciudad',l:'N3'}]},
  { rank:304, k:'空', level:'N4', meanings:['cielo','vacío'], on:['クウ'], kun:['そら','から','す.く'],
    words:[{w:'空気',f:'くうき',m:'aire',l:'N5'},{w:'空港',f:'くうこう',m:'aeropuerto',l:'N5'}]},
  { rank:309, k:'急', level:'N4', meanings:['urgente','rápido'], on:['キュウ'], kun:['いそ.ぐ'],
    words:[{w:'急行',f:'きゅうこう',m:'tren expreso',l:'N4'},{w:'急用',f:'きゅうよう',m:'asunto urgente',l:'N3'}]},
  { rank:310, k:'止', level:'N4', meanings:['parar','detener'], on:['シ'], kun:['と.まる','や.める'],
    words:[{w:'禁止',f:'きんし',m:'prohibición',l:'N4'},{w:'中止',f:'ちゅうし',m:'cancelación',l:'N4'}]},
  { rank:311, k:'送', level:'N4', meanings:['enviar','mandar'], on:['ソウ'], kun:['おく.る'],
    words:[{w:'放送',f:'ほうそう',m:'emisión / transmisión',l:'N4'},{w:'送料',f:'そうりょう',m:'gastos de envío',l:'N4'},{w:'郵送',f:'ゆうそう',m:'envío postal',l:'N4'}]},
  { rank:312, k:'化', level:'N4', meanings:['transformar','cambiar','química'], on:['カ','ケ'], kun:['ば.ける'],
    words:[{w:'文化',f:'ぶんか',m:'cultura',l:'N4'},{w:'変化',f:'へんか',m:'cambio',l:'N3'},{w:'化学',f:'かがく',m:'química',l:'N3'}]},
  { rank:313, k:'当', level:'N4', meanings:['acertar','aplicar','este'], on:['トウ'], kun:['あ.たる'],
    words:[{w:'本当',f:'ほんとう',m:'verdad',l:'N5'},{w:'当然',f:'とうぜん',m:'por supuesto / natural',l:'N3'},{w:'担当',f:'たんとう',m:'encargado',l:'N3'}]},
  { rank:324, k:'切', level:'N4', meanings:['cortar','importante'], on:['セツ','サイ'], kun:['き.る'],
    words:[{w:'大切',f:'たいせつ',m:'importante',l:'N5'},{w:'切符',f:'きっぷ',m:'billete',l:'N5'}]},
  { rank:325, k:'都', level:'N4', meanings:['metrópoli','capital','ciudad'], on:['ト','ツ'], kun:['みやこ'],
    words:[{w:'都市',f:'とし',m:'ciudad',l:'N3'},{w:'首都',f:'しゅと',m:'capital',l:'N3'},{w:'都合',f:'つごう',m:'conveniencia',l:'N3'}]},
  { rank:330, k:'数', level:'N4', meanings:['número','contar'], on:['スウ'], kun:['かず','かぞ.える'],
    words:[{w:'数学',f:'すうがく',m:'matemáticas',l:'N4'},{w:'数字',f:'すうじ',m:'dígito / cifra',l:'N4'},{w:'多数',f:'たすう',m:'gran cantidad',l:'N3'}]},
  { rank:336, k:'研', level:'N4', meanings:['pulir','estudiar'], on:['ケン'], kun:['と.ぐ'],
    words:[{w:'研究',f:'けんきゅう',m:'investigación',l:'N4'},{w:'研修',f:'けんしゅう',m:'formación / prácticas',l:'N3'}]},
  { rank:338, k:'原', level:'N4', meanings:['campo','origen','llanura'], on:['ゲン'], kun:['はら'],
    words:[{w:'原因',f:'げんいん',m:'causa',l:'N3'},{w:'原則',f:'げんそく',m:'principio',l:'N3'},{w:'原料',f:'げんりょう',m:'materia prima',l:'N3'}]},
  { rank:341, k:'交', level:'N4', meanings:['cruzar','intercambiar','mezclarse'], on:['コウ'], kun:['まじ.わる','か.わす'],
    words:[{w:'交通',f:'こうつう',m:'tráfico',l:'N4'},{w:'交換',f:'こうかん',m:'intercambio',l:'N3'},{w:'外交',f:'がいこう',m:'diplomacia',l:'N3'}]},
  { rank:352, k:'利', level:'N4', meanings:['provecho','ventaja','beneficio'], on:['リ'], kun:[],
    words:[{w:'便利',f:'べんり',m:'conveniente',l:'N5'},{w:'利用',f:'りよう',m:'uso / utilización',l:'N3'},{w:'権利',f:'けんり',m:'derecho',l:'N3'}]},
  { rank:361, k:'所', level:'N4', meanings:['lugar','punto','sitio'], on:['ショ'], kun:['ところ'],
    words:[{w:'場所',f:'ばしょ',m:'lugar',l:'N5'},{w:'住所',f:'じゅうしょ',m:'dirección (postal)',l:'N4'},{w:'研究所',f:'けんきゅうじょ',m:'instituto de investigación',l:'N3'}]},
  { rank:368, k:'究', level:'N4', meanings:['investigar','estudiar a fondo'], on:['キュウ'], kun:['きわ.める'],
    words:[{w:'研究',f:'けんきゅう',m:'investigación',l:'N4'}]},
  { rank:373, k:'楽', level:'N4', meanings:['música','placer','fácil'], on:['ガク','ラク'], kun:['たの.しい'],
    words:[{w:'音楽',f:'おんがく',m:'música',l:'N5'},{w:'気楽',f:'きらく',m:'relajado / despreocupado',l:'N4'},{w:'楽器',f:'がっき',m:'instrumento musical',l:'N4'}]},
  { rank:376, k:'着', level:'N4', meanings:['llegar','ponerse ropa'], on:['チャク','ジャク'], kun:['き.る','つ.く'],
    words:[{w:'到着',f:'とうちゃく',m:'llegada',l:'N4'},{w:'着替え',f:'きがえ',m:'cambiarse de ropa',l:'N4'},{w:'下着',f:'したぎ',m:'ropa interior',l:'N4'},{w:'着陸',f:'ちゃくりく',m:'aterrizaje',l:'N3'}]},
  { rank:377, k:'乗', level:'N4', meanings:['montar','subir a'], on:['ジョウ'], kun:['の.る'],
    words:[{w:'乗り換え',f:'のりかえ',m:'transbordo',l:'N4'},{w:'乗客',f:'じょうきゃく',m:'pasajero',l:'N4'},{w:'乗車',f:'じょうしゃ',m:'subir al vehículo',l:'N4'}]},
  { rank:378, k:'店', level:'N4', meanings:['tienda','mostrador'], on:['テン'], kun:['みせ'],
    words:[{w:'書店',f:'しょてん',m:'librería',l:'N5'},{w:'駅前店',f:'えきまえてん',m:'tienda frente a estación',l:'N4'},{w:'店員',f:'てんいん',m:'dependiente',l:'N4'},{w:'売店',f:'ばいてん',m:'quiosco',l:'N3'}]},
  { rank:384, k:'病', level:'N4', meanings:['enfermedad'], on:['ビョウ','ヘイ'], kun:['や.む'],
    words:[{w:'病院',f:'びょういん',m:'hospital',l:'N5'},{w:'病気',f:'びょうき',m:'enfermedad',l:'N5'},{w:'病室',f:'びょうしつ',m:'habitación de hospital',l:'N4'}]},
  { rank:388, k:'声', level:'N4', meanings:['voz'], on:['セイ','ショウ'], kun:['こえ'],
    words:[{w:'大声',f:'おおごえ',m:'voz alta',l:'N4'},{w:'音声',f:'おんせい',m:'sonido / voz',l:'N3'},{w:'歓声',f:'かんせい',m:'ovación',l:'N3'}]},
  { rank:389, k:'質', level:'N4', meanings:['calidad','sustancia','pregunta'], on:['シツ','シチ'], kun:['たち'],
    words:[{w:'質問',f:'しつもん',m:'pregunta',l:'N5'},{w:'品質',f:'ひんしつ',m:'calidad',l:'N3'},{w:'性質',f:'せいしつ',m:'naturaleza / carácter',l:'N3'}]},
  { rank:391, k:'待', level:'N4', meanings:['esperar'], on:['タイ'], kun:['ま.つ'],
    words:[{w:'期待',f:'きたい',m:'expectativa',l:'N4'},{w:'招待',f:'しょうたい',m:'invitación',l:'N4'}]},
  { rank:392, k:'試', level:'N4', meanings:['probar','experimentar'], on:['シ'], kun:['こころ.みる','ため.す'],
    words:[{w:'試験',f:'しけん',m:'examen',l:'N5'},{w:'試合',f:'しあい',m:'partido / encuentro',l:'N4'},{w:'入試',f:'にゅうし',m:'examen de ingreso',l:'N4'}]},
  { rank:393, k:'族', level:'N4', meanings:['tribu','familia','grupo'], on:['ゾク'], kun:[],
    words:[{w:'家族',f:'かぞく',m:'familia',l:'N5'},{w:'水族館',f:'すいぞくかん',m:'acuario',l:'N4'}]},
  { rank:395, k:'銀', level:'N4', meanings:['plata','banco'], on:['ギン'], kun:[],
    words:[{w:'銀行',f:'ぎんこう',m:'banco',l:'N5'},{w:'銀色',f:'ぎんいろ',m:'color plata',l:'N4'}]},
  { rank:402, k:'早', level:'N4', meanings:['temprano','rápido'], on:['ソウ','サッ'], kun:['はや.い'],
    words:[{w:'早速',f:'さっそく',m:'de inmediato',l:'N4'},{w:'早朝',f:'そうちょう',m:'madrugada',l:'N3'},{w:'早期',f:'そうき',m:'etapa temprana',l:'N3'}]},
  { rank:404, k:'映', level:'N4', meanings:['proyectar','reflejar'], on:['エイ'], kun:['うつ.る'],
    words:[{w:'映画',f:'えいが',m:'película',l:'N5'},{w:'映画館',f:'えいがかん',m:'cine',l:'N5'}]},
  { rank:405, k:'夫', level:'N4', meanings:['marido','esposo'], on:['フ','フウ'], kun:['おっと'],
    words:[{w:'夫婦',f:'ふうふ',m:'matrimonio / pareja',l:'N3'},{w:'夫人',f:'ふじん',m:'señora / esposa',l:'N3'}]},
  { rank:406, k:'親', level:'N4', meanings:['padre/madre','pariente','íntimo'], on:['シン'], kun:['おや','した.しい'],
    words:[{w:'親切',f:'しんせつ',m:'amabilidad',l:'N5'},{w:'両親',f:'りょうしん',m:'ambos padres',l:'N4'},{w:'親友',f:'しんゆう',m:'amigo íntimo',l:'N4'}]},
  { rank:410, k:'験', level:'N4', meanings:['examen','experiencia','efecto'], on:['ケン'], kun:[],
    words:[{w:'試験',f:'しけん',m:'examen',l:'N5'},{w:'経験',f:'けいけん',m:'experiencia',l:'N4'},{w:'受験',f:'じゅけん',m:'presentarse a un examen',l:'N4'}]},
  { rank:412, k:'番', level:'N4', meanings:['turno','número de serie','guardia'], on:['バン'], kun:['つが'],
    words:[{w:'番号',f:'ばんごう',m:'número',l:'N5'},{w:'交番',f:'こうばん',m:'comisaría de barrio',l:'N4'},{w:'番組',f:'ばんぐみ',m:'programa (TV/radio)',l:'N3'}]},
  { rank:415, k:'宅', level:'N4', meanings:['hogar','residencia','domicilio'], on:['タク'], kun:[],
    words:[{w:'帰宅',f:'きたく',m:'regreso a casa',l:'N4'},{w:'自宅',f:'じたく',m:'casa propia / domicilio',l:'N3'},{w:'宅配',f:'たくはい',m:'entrega a domicilio',l:'N3'}]},
  { rank:417, k:'働', level:'N4', meanings:['trabajar'], on:['ドウ'], kun:['はたら.く'],
    words:[{w:'労働',f:'ろうどう',m:'trabajo / labor',l:'N4'},{w:'労働者',f:'ろうどうしゃ',m:'trabajador',l:'N3'}]},
  { rank:418, k:'育', level:'N4', meanings:['criar','educar','crecer'], on:['イク'], kun:['そだ.てる','はぐく.む'],
    words:[{w:'教育',f:'きょういく',m:'educación',l:'N4'},{w:'保育',f:'ほいく',m:'cuidado de niños',l:'N3'}]},
  { rank:426, k:'然', level:'N4', meanings:['naturaleza','así','por supuesto'], on:['ゼン','ネン'], kun:[],
    words:[{w:'自然',f:'しぜん',m:'naturaleza',l:'N4'},{w:'当然',f:'とうぜん',m:'por supuesto',l:'N3'},{w:'突然',f:'とつぜん',m:'de repente',l:'N3'}]},
  { rank:430, k:'英', level:'N4', meanings:['inglés','Gran Bretaña','brillante'], on:['エイ'], kun:[],
    words:[{w:'英語',f:'えいご',m:'inglés',l:'N5'},{w:'英国',f:'えいこく',m:'Reino Unido',l:'N4'},{w:'英会話',f:'えいかいわ',m:'conversación en inglés',l:'N4'}]},
  { rank:436, k:'毎', level:'N4', meanings:['cada','todos'], on:['マイ'], kun:['ごと'],
    words:[{w:'毎日',f:'まいにち',m:'cada día',l:'N5'},{w:'毎年',f:'まいとし',m:'cada año',l:'N5'},{w:'毎週',f:'まいしゅう',m:'cada semana',l:'N5'}]},
  { rank:437, k:'医', level:'N4', meanings:['medicina','médico'], on:['イ'], kun:[],
    words:[{w:'医者',f:'いしゃ',m:'médico',l:'N5'},{w:'医学',f:'いがく',m:'medicina (ciencia)',l:'N4'},{w:'医療',f:'いりょう',m:'atención médica',l:'N4'},{w:'医院',f:'いいん',m:'clínica',l:'N4'}]},
  { rank:440, k:'去', level:'N4', meanings:['irse','pasado'], on:['キョ','コ'], kun:['さ.る'],
    words:[{w:'去年',f:'きょねん',m:'el año pasado',l:'N5'},{w:'過去',f:'かこ',m:'pasado',l:'N4'}]},
  { rank:442, k:'若', level:'N4', meanings:['joven','juvenil'], on:['ジャク','ニャク'], kun:['わか.い','も'],
    words:[{w:'若者',f:'わかもの',m:'joven / juventud',l:'N4'},{w:'若手',f:'わかて',m:'persona joven (en trabajo)',l:'N3'}]},
  { rank:442, k:'味', level:'N4', meanings:['sabor','gusto','interés'], on:['ミ'], kun:['あじ'],
    words:[{w:'意味',f:'いみ',m:'significado',l:'N5'},{w:'趣味',f:'しゅみ',m:'afición / pasatiempo',l:'N5'}]},
  { rank:453, k:'写', level:'N4', meanings:['copiar','fotografiar'], on:['シャ'], kun:['うつ.す'],
    words:[{w:'写真',f:'しゃしん',m:'fotografía',l:'N5'},{w:'写真館',f:'しゃしんかん',m:'estudio fotográfico',l:'N4'},{w:'複写',f:'ふくしゃ',m:'copia',l:'N4'}]},
  { rank:467, k:'科', level:'N4', meanings:['departamento','asignatura','ciencia'], on:['カ'], kun:[],
    words:[{w:'科学',f:'かがく',m:'ciencia',l:'N4'},{w:'外科',f:'げか',m:'cirugía',l:'N3'},{w:'内科',f:'ないか',m:'medicina interna',l:'N3'}]},
  { rank:471, k:'太', level:'N4', meanings:['gordo','grueso'], on:['タイ','タ'], kun:['ふと.い','ふと.る'],
    words:[{w:'太陽',f:'たいよう',m:'sol',l:'N4'},{w:'太平洋',f:'たいへいよう',m:'océano Pacífico',l:'N3'}]},
  { rank:472, k:'客', level:'N4', meanings:['cliente','visitante','invitado'], on:['キャク','カク'], kun:[],
    words:[{w:'観客',f:'かんきゃく',m:'audiencia / espectadores',l:'N3'}]},
  { rank:477, k:'速', level:'N4', meanings:['rápido','veloz'], on:['ソク'], kun:['はや.い'],
    words:[{w:'高速',f:'こうそく',m:'alta velocidad / autopista',l:'N4'},{w:'速度',f:'そくど',m:'velocidad',l:'N3'}]},
  { rank:480, k:'号', level:'N4', meanings:['número','nombre especial','señal'], on:['ゴウ'], kun:[],
    words:[{w:'番号',f:'ばんごう',m:'número',l:'N5'},{w:'信号',f:'しんごう',m:'semáforo / señal',l:'N4'},{w:'記号',f:'きごう',m:'símbolo',l:'N3'}]},
  { rank:483, k:'白', level:'N4', meanings:['blanco'], on:['ハク','ビャク'], kun:['しろ','しら'],
    words:[{w:'白人',f:'はくじん',m:'persona blanca',l:'N5'},{w:'白米',f:'はくまい',m:'arroz blanco',l:'N4'}]},
  { rank:486, k:'答', level:'N4', meanings:['respuesta','contestar'], on:['トウ'], kun:['こた.える'],
    words:[{w:'回答',f:'かいとう',m:'respuesta / contestación',l:'N4'},{w:'解答',f:'かいとう',m:'solución',l:'N4'}]},
  { rank:486, k:'降', level:'N4', meanings:['descender','caer','rendirse'], on:['コウ'], kun:['ふ.る','お.りる'],
    words:[{w:'以降',f:'いこう',m:'desde entonces / a partir de',l:'N3'},{w:'下降',f:'かこう',m:'descenso',l:'N3'},{w:'降水',f:'こうすい',m:'precipitación',l:'N3'}]},
  { rank:487, k:'夜', level:'N4', meanings:['noche'], on:['ヤ'], kun:['よる','よ'],
    words:[{w:'今夜',f:'こんや',m:'esta noche',l:'N5'},{w:'夜中',f:'よなか',m:'medianoche',l:'N4'},{w:'夜景',f:'やけい',m:'vista nocturna',l:'N4'}]},
  { rank:493, k:'園', level:'N4', meanings:['parque','jardín'], on:['エン'], kun:['その'],
    words:[{w:'公園',f:'こうえん',m:'parque público',l:'N5'},{w:'幼稚園',f:'ようちえん',m:'jardín de infancia',l:'N4'},{w:'動物園',f:'どうぶつえん',m:'zoológico',l:'N4'}]},
  { rank:497, k:'馬', level:'N4', meanings:['caballo'], on:['バ'], kun:['うま','ま'],
    words:[{w:'競馬',f:'けいば',m:'carreras de caballos',l:'N3'}]},
  { rank:512, k:'天', level:'N4', meanings:['cielo','naturaleza'], on:['テン'], kun:['あま','あめ'],
    words:[{w:'天気',f:'てんき',m:'clima / tiempo',l:'N5'},{w:'天下',f:'てんか',m:'imperio / el mundo',l:'N4'},{w:'天皇',f:'てんのう',m:'emperador',l:'N4'}]},
  { rank:512, k:'返', level:'N4', meanings:['devolver','responder'], on:['ヘン'], kun:['かえ.す','かえ.る'],
    words:[{w:'返事',f:'へんじ',m:'respuesta',l:'N5'},{w:'返却',f:'へんきゃく',m:'devolución',l:'N3'}]},
  { rank:513, k:'妻', level:'N4', meanings:['esposa','mujer'], on:['サイ'], kun:['つま'],
    words:[{w:'夫妻',f:'ふさい',m:'matrimonio / esposos',l:'N3'}]},
  { rank:516, k:'宿', level:'N4', meanings:['alojamiento','posada','tarea'], on:['シュク'], kun:['やど'],
    words:[{w:'宿題',f:'しゅくだい',m:'tarea / deberes',l:'N5'},{w:'宿泊',f:'しゅくはく',m:'alojamiento / estancia',l:'N3'}]},
  { rank:519, k:'歌', level:'N4', meanings:['cantar','canción'], on:['カ'], kun:['うた.う','うた'],
    words:[{w:'歌手',f:'かしゅ',m:'cantante',l:'N4'}]},
  { rank:520, k:'船', level:'N4', meanings:['barco','nave'], on:['セン'], kun:['ふね','ふな'],
    words:[{w:'客船',f:'きゃくせん',m:'barco de pasajeros',l:'N3'}]},
  { rank:524, k:'便', level:'N4', meanings:['conveniente','servicio','correo'], on:['ベン','ビン'], kun:['たよ'],
    words:[{w:'便利',f:'べんり',m:'conveniente',l:'N5'},{w:'郵便',f:'ゆうびん',m:'correo postal',l:'N4'},{w:'不便',f:'ふべん',m:'inconveniente',l:'N4'}]},
  { rank:527, k:'光', level:'N4', meanings:['luz','brillar'], on:['コウ'], kun:['ひかり'],
    words:[{w:'観光',f:'かんこう',m:'turismo',l:'N4'}]},
  { rank:530, k:'静', level:'N4', meanings:['quieto','tranquilo','silencioso'], on:['セイ','ジョウ'], kun:['しず.まる'],
    words:[{w:'冷静',f:'れいせい',m:'calmado',l:'N3'}]},
  { rank:539, k:'図', level:'N4', meanings:['mapa','diagrama'], on:['ズ','ト'], kun:['はか.る'],
    words:[{w:'地図',f:'ちず',m:'mapa',l:'N5'},{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'図形',f:'ずけい',m:'figura geométrica',l:'N4'}]},
  { rank:540, k:'週', level:'N4', meanings:['semana'], on:['シュウ'], kun:[],
    words:[{w:'週末',f:'しゅうまつ',m:'fin de semana',l:'N5'},{w:'毎週',f:'まいしゅう',m:'cada semana',l:'N5'},{w:'今週',f:'こんしゅう',m:'esta semana',l:'N5'}]},
  { rank:542, k:'丸', level:'N4', meanings:['círculo','redondo'], on:['ガン'], kun:['まる.い'],
    words:[{w:'丸太',f:'まるた',m:'tronco / leño',l:'N4'},{w:'弾丸',f:'だんがん',m:'bala',l:'N3'}]},
  { rank:550, k:'室', level:'N4', meanings:['habitación','sala'], on:['シツ'], kun:['むろ'],
    words:[{w:'教室',f:'きょうしつ',m:'aula',l:'N5'},{w:'洋室',f:'ようしつ',m:'habitación al estilo occidental',l:'N4'},{w:'和室',f:'わしつ',m:'habitación al estilo japonés',l:'N4'},{w:'個室',f:'こしつ',m:'habitación individual / privada',l:'N4'}]},
  { rank:554, k:'歩', level:'N4', meanings:['caminar','paso'], on:['ホ','ブ'], kun:['ある.く','あゆ.む'],
    words:[{w:'散歩',f:'さんぽ',m:'paseo',l:'N5'},{w:'進歩',f:'しんぽ',m:'progreso',l:'N4'},{w:'一歩',f:'いっぽ',m:'un paso',l:'N4'}]},
  { rank:558, k:'風', level:'N4', meanings:['viento'], on:['フウ','フ'], kun:['かぜ'],
    words:[{w:'台風',f:'たいふう',m:'tifón',l:'N4'},{w:'風景',f:'ふうけい',m:'paisaje',l:'N4'}]},
  { rank:559, k:'紙', level:'N4', meanings:['papel'], on:['シ'], kun:['かみ'],
    words:[{w:'手紙',f:'てがみ',m:'carta',l:'N5'},{w:'新聞紙',f:'しんぶんし',m:'papel de periódico',l:'N4'},{w:'折り紙',f:'おりがみ',m:'origami',l:'N4'}]},
  { rank:572, k:'閉', level:'N4', meanings:['cerrar','clausurar'], on:['ヘイ'], kun:['し.める','と.じる'],
    words:[{w:'閉店',f:'へいてん',m:'cierre de tienda',l:'N3'},{w:'閉鎖',f:'へいさ',m:'clausura',l:'N3'}]},
  { rank:573, k:'黒', level:'N4', meanings:['negro'], on:['コク'], kun:['くろ'],
    words:[{w:'黒板',f:'こくばん',m:'pizarra',l:'N5'},{w:'黒字',f:'くろじ',m:'superávit',l:'N3'},{w:'白黒',f:'しろくろ',m:'blanco y negro',l:'N3'}]},
  { rank:575, k:'草', level:'N4', meanings:['hierba','maleza'], on:['ソウ'], kun:['くさ'],
    words:[{w:'雑草',f:'ざっそう',m:'maleza',l:'N3'},{w:'草原',f:'そうげん',m:'pradera',l:'N3'}]},
  { rank:577, k:'酒', level:'N4', meanings:['alcohol','sake'], on:['シュ'], kun:['さけ','さか'],
    words:[{w:'日本酒',f:'にほんしゅ',m:'sake japonés',l:'N3'},{w:'飲酒',f:'いんしゅ',m:'beber alcohol',l:'N3'},{w:'居酒屋',f:'いざかや',m:'izakaya / taberna',l:'N3'}]},
  { rank:579, k:'春', level:'N4', meanings:['primavera'], on:['シュン'], kun:['はる'],
    words:[{w:'春休み',f:'はるやすみ',m:'vacaciones de primavera',l:'N4'},{w:'青春',f:'せいしゅん',m:'juventud',l:'N3'}]},
  { rank:579, k:'晴', level:'N4', meanings:['despejado','buen tiempo'], on:['セイ'], kun:['は.れる'],
    words:[{w:'快晴',f:'かいせい',m:'cielo despejado',l:'N3'},{w:'晴天',f:'せいてん',m:'cielo despejado',l:'N3'}]},
  { rank:584, k:'赤', level:'N4', meanings:['rojo'], on:['セキ','シャク'], kun:['あか'],
    words:[{w:'赤信号',f:'あかしんごう',m:'semáforo en rojo',l:'N4'},{w:'赤字',f:'あかじ',m:'déficit / números rojos',l:'N3'},{w:'赤道',f:'せきどう',m:'ecuador',l:'N3'}]},
  { rank:589, k:'青', level:'N4', meanings:['azul','verde'], on:['セイ','ショウ'], kun:['あお'],
    words:[{w:'青空',f:'あおぞら',m:'cielo azul',l:'N4'},{w:'青信号',f:'あおしんごう',m:'semáforo en verde',l:'N4'}]},
  { rank:602, k:'鳴', level:'N4', meanings:['sonar','cantar (pájaros)','llamar (animales)'], on:['メイ'], kun:['な.る','な.く'],
    words:[{w:'鳴き声',f:'なきごえ',m:'canto (animal) / llanto',l:'N3'},{w:'悲鳴',f:'ひめい',m:'grito / chillido',l:'N3'}]},
  { rank:609, k:'晩', level:'N4', meanings:['noche','tarde'], on:['バン'], kun:[],
    words:[{w:'今晩',f:'こんばん',m:'esta noche',l:'N5'},{w:'晩ご飯',f:'ばんごはん',m:'cena',l:'N5'},{w:'毎晩',f:'まいばん',m:'cada noche',l:'N4'}]},
  { rank:610, k:'寒', level:'N4', meanings:['frío (clima)'], on:['カン'], kun:['さむ.い'],
    words:[{w:'寒波',f:'かんぱ',m:'ola de frío',l:'N3'},{w:'寒気',f:'さむけ',m:'escalofrío',l:'N3'}]},
  { rank:613, k:'才', level:'N4', meanings:['talento','años de edad'], on:['サイ'], kun:[],
    words:[{w:'天才',f:'てんさい',m:'genio',l:'N4'},{w:'才能',f:'さいのう',m:'talento',l:'N3'}]},
  { rank:613, k:'館', level:'N4', meanings:['edificio','sala'], on:['カン'], kun:['やかた'],
    words:[{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'映画館',f:'えいがかん',m:'cine',l:'N5'},{w:'水族館',f:'すいぞくかん',m:'acuario',l:'N4'},{w:'旅館',f:'りょかん',m:'posada japonesa',l:'N4'}]},
  { rank:616, k:'屋', level:'N4', meanings:['tienda','casa','techo'], on:['オク'], kun:['や'],
    words:[{w:'本屋',f:'ほんや',m:'librería',l:'N5'},{w:'部屋',f:'へや',m:'habitación',l:'N5'},{w:'八百屋',f:'やおや',m:'frutería / verdulería',l:'N4'},{w:'肉屋',f:'にくや',m:'carnicería',l:'N4'}]},
  { rank:621, k:'色', level:'N4', meanings:['color'], on:['ショク','シキ'], kun:['いろ'],
    words:[{w:'茶色',f:'ちゃいろ',m:'marrón',l:'N5'},{w:'景色',f:'けしき',m:'paisaje',l:'N4'}]},
  { rank:626, k:'走', level:'N4', meanings:['correr'], on:['ソウ'], kun:['はし.る'],
    words:[{w:'競走',f:'きょうそう',m:'carrera',l:'N4'},{w:'走者',f:'そうしゃ',m:'corredor',l:'N4'}]},
  { rank:635, k:'秋', level:'N4', meanings:['otoño'], on:['シュウ'], kun:['あき'],
    words:[{w:'秋分',f:'しゅうぶん',m:'equinoccio de otoño',l:'N3'}]},
  { rank:636, k:'低', level:'N4', meanings:['bajo','inferior'], on:['テイ'], kun:['ひく.い'],
    words:[{w:'最低',f:'さいてい',m:'mínimo / lo peor',l:'N3'},{w:'低下',f:'ていか',m:'disminución / descenso',l:'N3'}]},
  { rank:648, k:'冊', level:'N4', meanings:['contador de libros'], on:['サツ'], kun:[],
    words:[{w:'一冊',f:'いっさつ',m:'un libro',l:'N4'}]},
  { rank:659, k:'夏', level:'N4', meanings:['verano'], on:['カ','ゲ'], kun:['なつ'],
    words:[{w:'夏休み',f:'なつやすみ',m:'vacaciones de verano',l:'N5'}]},
  { rank:663, k:'区', level:'N4', meanings:['distrito','sección'], on:['ク'], kun:[],
    words:[{w:'地区',f:'ちく',m:'zona / distrito',l:'N3'},{w:'区別',f:'くべつ',m:'distinción / diferencia',l:'N3'}]},
  { rank:673, k:'史', level:'N4', meanings:['historia'], on:['シ'], kun:[],
    words:[{w:'歴史',f:'れきし',m:'historia',l:'N3'},{w:'史上',f:'しじょう',m:'en la historia',l:'N3'}]},
  { rank:702, k:'薬', level:'N4', meanings:['medicina','fármaco'], on:['ヤク'], kun:['くすり'],
    words:[{w:'薬局',f:'やっきょく',m:'farmacia',l:'N4'},{w:'目薬',f:'めぐすり',m:'colirio',l:'N4'}]},
  { rank:706, k:'習', level:'N4', meanings:['aprender','practicar'], on:['シュウ'], kun:['なら.う'],
    words:[{w:'練習',f:'れんしゅう',m:'práctica',l:'N5'},{w:'学習',f:'がくしゅう',m:'aprendizaje',l:'N4'},{w:'習慣',f:'しゅうかん',m:'costumbre / hábito',l:'N4'}]},
  { rank:724, k:'駅', level:'N4', meanings:['estación'], on:['エキ'], kun:[],
    words:[{w:'駅前',f:'えきまえ',m:'frente a la estación',l:'N5'},{w:'駅員',f:'えきいん',m:'empleado de estación',l:'N4'}]},
  { rank:726, k:'府', level:'N4', meanings:['prefectura','sede'], on:['フ'], kun:[],
    words:[{w:'政府',f:'せいふ',m:'gobierno',l:'N3'}]},
  { rank:755, k:'星', level:'N4', meanings:['estrella'], on:['セイ'], kun:['ほし'],
    words:[{w:'星座',f:'せいざ',m:'constelación',l:'N3'},{w:'星空',f:'ほしぞら',m:'cielo estrellado',l:'N3'}]},
  { rank:758, k:'曇', level:'N4', meanings:['nublado'], on:['ドン'], kun:['くも.る'],
    words:[{w:'曇天',f:'どんてん',m:'cielo nublado',l:'N3'}]},
  { rank:763, k:'村', level:'N4', meanings:['pueblo','aldea'], on:['ソン'], kun:['むら'],
    words:[{w:'農村',f:'のうそん',m:'aldea agrícola / pueblo rural',l:'N3'},{w:'村人',f:'むらびと',m:'aldeano',l:'N3'},{w:'漁村',f:'ぎょそん',m:'pueblo pesquero',l:'N3'}]},
  { rank:763, k:'洋', level:'N4', meanings:['océano','occidental'], on:['ヨウ'], kun:[],
    words:[{w:'洋服',f:'ようふく',m:'ropa occidental',l:'N5'},{w:'西洋',f:'せいよう',m:'occidente',l:'N4'},{w:'東洋',f:'とうよう',m:'oriente',l:'N4'},{w:'洋食',f:'ようしょく',m:'comida occidental',l:'N4'}]},
  { rank:782, k:'歴', level:'N4', meanings:['historia','trayectoria'], on:['レキ'], kun:[],
    words:[{w:'歴史',f:'れきし',m:'historia',l:'N3'},{w:'経歴',f:'けいれき',m:'trayectoria',l:'N3'},{w:'学歴',f:'がくれき',m:'nivel educativo',l:'N3'}]},
  { rank:783, k:'旅', level:'N4', meanings:['viaje','viajar'], on:['リョ'], kun:['たび'],
    words:[{w:'旅行',f:'りょこう',m:'viaje',l:'N5'},{w:'旅館',f:'りょかん',m:'posada japonesa',l:'N4'},{w:'旅人',f:'たびびと',m:'viajero',l:'N4'},{w:'旅費',f:'りょひ',m:'gastos de viaje',l:'N4'}]},
  { rank:786, k:'毛', level:'N4', meanings:['pelo','vello'], on:['モウ'], kun:['け'],
    words:[{w:'毛布',f:'もうふ',m:'manta',l:'N3'},{w:'毛糸',f:'けいと',m:'lana',l:'N4'},{w:'羽毛',f:'うもう',m:'plumón',l:'N3'}]},
  { rank:788, k:'練', level:'N4', meanings:['practicar','entrenar'], on:['レン'], kun:['ね.る'],
    words:[{w:'練習',f:'れんしゅう',m:'práctica',l:'N5'},{w:'訓練',f:'くんれん',m:'entrenamiento',l:'N4'}]},
  { rank:790, k:'軽', level:'N4', meanings:['ligero','leve'], on:['ケイ'], kun:['かる.い'],
    words:[{w:'気軽',f:'きがる',m:'despreocupado',l:'N4'},{w:'軽食',f:'けいしょく',m:'comida ligera',l:'N3'},{w:'軽量',f:'けいりょう',m:'ligero / liviano',l:'N3'}]},
  { rank:791, k:'池', level:'N4', meanings:['estanque'], on:['チ'], kun:['いけ'],
    words:[{w:'電池',f:'でんち',m:'batería / pila',l:'N4'}]},
  { rank:795, k:'油', level:'N4', meanings:['aceite','petróleo'], on:['ユ'], kun:['あぶら'],
    words:[{w:'石油',f:'せきゆ',m:'petróleo',l:'N3'},{w:'醤油',f:'しょうゆ',m:'salsa de soja',l:'N4'},{w:'油断',f:'ゆだん',m:'descuido',l:'N3'}]},
  { rank:811, k:'湖', level:'N4', meanings:['lago'], on:['コ'], kun:['みずうみ'],
    words:[{w:'湖畔',f:'こはん',m:'orilla del lago',l:'N3'}]},
  { rank:832, k:'玉', level:'N4', meanings:['bola','joya'], on:['ギョク'], kun:['たま'],
    words:[{w:'玉子',f:'たまご',m:'huevo',l:'N4'},{w:'目玉',f:'めだま',m:'globo ocular',l:'N3'},{w:'水玉',f:'みずたま',m:'lunares',l:'N3'}]},
  { rank:833, k:'遅', level:'N4', meanings:['tarde','lento'], on:['チ'], kun:['おそ.い','おく.れる'],
    words:[{w:'遅刻',f:'ちこく',m:'llegar tarde',l:'N4'}]},
  { rank:841, k:'皿', level:'N4', meanings:['plato','bandeja'], on:[], kun:['さら'],
    words:[{w:'皿洗い',f:'さらあらい',m:'lavar platos',l:'N3'},{w:'小皿',f:'こざら',m:'platito',l:'N3'}]},
  { rank:843, k:'県', level:'N4', meanings:['prefectura'], on:['ケン'], kun:[],
    words:[{w:'県庁',f:'けんちょう',m:'gobierno prefectural',l:'N3'},{w:'県立',f:'けんりつ',m:'prefectural',l:'N3'}]},
  { rank:844, k:'短', level:'N4', meanings:['corto','breve'], on:['タン'], kun:['みじか.い'],
    words:[{w:'短所',f:'たんしょ',m:'defecto / punto débil',l:'N3'},{w:'短期',f:'たんき',m:'corto plazo',l:'N3'},{w:'最短',f:'さいたん',m:'lo más corto',l:'N3'}]},
  { rank:869, k:'糸', level:'N4', meanings:['hilo'], on:['シ'], kun:['いと'],
    words:[{w:'毛糸',f:'けいと',m:'hilo de lana',l:'N3'}]},
  { rank:872, k:'細', level:'N4', meanings:['fino','delgado','detalle'], on:['サイ'], kun:['こま.かい'],
    words:[{w:'明細',f:'めいさい',m:'detalle / estado de cuenta',l:'N3'},{w:'詳細',f:'しょうさい',m:'detalle',l:'N3'},{w:'細胞',f:'さいぼう',m:'célula',l:'N3'}]},
  { rank:873, k:'服', level:'N4', meanings:['ropa','prenda'], on:['フク'], kun:[],
    words:[{w:'洋服',f:'ようふく',m:'ropa occidental',l:'N5'},{w:'制服',f:'せいふく',m:'uniforme',l:'N4'},{w:'和服',f:'わふく',m:'ropa japonesa',l:'N4'}]},
  { rank:877, k:'緑', level:'N4', meanings:['verde'], on:['リョク'], kun:['みどり'],
    words:[{w:'緑茶',f:'りょくちゃ',m:'té verde',l:'N4'},{w:'緑色',f:'みどりいろ',m:'verde',l:'N4'}]},
  { rank:884, k:'羽', level:'N4', meanings:['pluma','ala'], on:['ウ'], kun:['はね'],
    words:[{w:'羽根',f:'はね',m:'pluma / paleta',l:'N3'},{w:'羽毛',f:'うもう',m:'plumón',l:'N3'}]},
  { rank:887, k:'遠', level:'N4', meanings:['lejos'], on:['エン','オン'], kun:['とお.い'],
    words:[{w:'遠足',f:'えんそく',m:'excursión',l:'N4'},{w:'遠慮',f:'えんりょ',m:'reserva / abstención',l:'N3'},{w:'永遠',f:'えいえん',m:'eternidad',l:'N3'}]},
  { rank:904, k:'荷', level:'N4', meanings:['carga','equipaje'], on:['カ'], kun:['に'],
    words:[{w:'荷物',f:'にもつ',m:'equipaje / carga',l:'N4'},{w:'出荷',f:'しゅっか',m:'envío de mercancía',l:'N3'},{w:'入荷',f:'にゅうか',m:'llegada de mercancía',l:'N3'}]},
  { rank:913, k:'衣', level:'N4', meanings:['ropa','vestimenta'], on:['イ'], kun:['ころも'],
    words:[{w:'浴衣',f:'ゆかた',m:'yukata (kimono de verano)',l:'N4'},{w:'衣服',f:'いふく',m:'ropa',l:'N3'},{w:'衣類',f:'いるい',m:'prendas',l:'N3'}]},
  { rank:930, k:'谷', level:'N4', meanings:['valle'], on:['コク'], kun:['たに'],
    words:[{w:'谷川',f:'たにがわ',m:'arroyo de montaña',l:'N4'}]},
  { rank:932, k:'借', level:'N4', meanings:['pedir prestado','alquilar'], on:['シャク'], kun:['か.りる'],
    words:[{w:'借金',f:'しゃっきん',m:'deuda',l:'N4'},{w:'借家',f:'しゃくや',m:'casa de alquiler',l:'N4'}]},
  { rank:951, k:'辺', level:'N4', meanings:['alrededor','zona'], on:['ヘン'], kun:['あた.り'],
    words:[{w:'周辺',f:'しゅうへん',m:'alrededores / vecindad',l:'N3'},{w:'海辺',f:'うみべ',m:'playa / costa',l:'N3'},{w:'近辺',f:'きんぺん',m:'cercanías',l:'N3'}]},
  { rank:958, k:'弱', level:'N4', meanings:['débil'], on:['ジャク'], kun:['よわ.い'],
    words:[{w:'弱点',f:'じゃくてん',m:'punto débil',l:'N4'},{w:'弱気',f:'よわき',m:'timidez',l:'N3'},{w:'強弱',f:'きょうじゃく',m:'intensidad',l:'N3'}]},
  { rank:960, k:'鉄', level:'N4', meanings:['hierro','férreo'], on:['テツ'], kun:[],
    words:[{w:'地下鉄',f:'ちかてつ',m:'metro',l:'N4'},{w:'鉄道',f:'てつどう',m:'ferrocarril',l:'N3'}]},
  { rank:983, k:'麦', level:'N4', meanings:['trigo','cebada'], on:['バク'], kun:['むぎ'],
    words:[{w:'麦茶',f:'むぎちゃ',m:'té de cebada',l:'N3'},{w:'小麦',f:'こむぎ',m:'trigo',l:'N3'}]},
  { rank:984, k:'黄', level:'N4', meanings:['amarillo'], on:['オウ'], kun:['き'],
    words:[{w:'黄色',f:'きいろ',m:'amarillo',l:'N5'},{w:'黄金',f:'おうごん',m:'oro',l:'N3'}]},
  { rank:995, k:'貸', level:'N4', meanings:['prestar','alquilar (a otro)'], on:['タイ'], kun:['か.す'],
    words:[{w:'貸し出し',f:'かしだし',m:'préstamo',l:'N4'},{w:'貸家',f:'かしや',m:'casa en alquiler',l:'N4'}]},
  { rank:1043, k:'鳥', level:'N4', meanings:['pájaro','ave'], on:['チョウ'], kun:['とり'],
    words:[{w:'小鳥',f:'ことり',m:'pajarito',l:'N4'},{w:'渡り鳥',f:'わたりどり',m:'ave migratoria',l:'N4'},{w:'鳥居',f:'とりい',m:'torii (puerta de santuario)',l:'N4'}]},
  { rank:1046, k:'飯', level:'N4', meanings:['arroz cocido','comida'], on:['ハン'], kun:['めし'],
    words:[{w:'朝ご飯',f:'あさごはん',m:'desayuno',l:'N5'},{w:'夕飯',f:'ゆうはん',m:'cena',l:'N4'}]},
  { rank:1066, k:'勉', level:'N4', meanings:['estudiar','esforzarse'], on:['ベン'], kun:[],
    words:[{w:'勉強',f:'べんきょう',m:'estudio',l:'N5'}]},
  { rank:1090, k:'冬', level:'N4', meanings:['invierno'], on:['トウ'], kun:['ふゆ'],
    words:[{w:'冬休み',f:'ふゆやすみ',m:'vacaciones de invierno',l:'N5'},{w:'真冬',f:'まふゆ',m:'pleno invierno',l:'N3'},{w:'冬季',f:'とうき',m:'temporada de invierno',l:'N3'}]},
  { rank:1096, k:'里', level:'N4', meanings:['aldea','milla japonesa'], on:['リ'], kun:['さと'],
    words:[{w:'里帰り',f:'さとがえり',m:'regreso al pueblo natal',l:'N3'}]},
  { rank:1115, k:'昼', level:'N4', meanings:['mediodía'], on:['チュウ'], kun:['ひる'],
    words:[{w:'昼食',f:'ちゅうしょく',m:'almuerzo',l:'N4'},{w:'昼間',f:'ひるま',m:'durante el día',l:'N4'},{w:'昼休み',f:'ひるやすみ',m:'descanso del mediodía',l:'N4'}]},
  { rank:1131, k:'雪', level:'N4', meanings:['nieve'], on:['セツ'], kun:['ゆき'],
    words:[{w:'大雪',f:'おおゆき',m:'nevada intensa',l:'N4'},{w:'雪国',f:'ゆきぐに',m:'tierra de nieve',l:'N3'},{w:'積雪',f:'せきせつ',m:'acumulación de nieve',l:'N3'}]},
  { rank:1161, k:'弟', level:'N4', meanings:['hermano menor'], on:['テイ','ダイ'], kun:['おとうと'],
    words:[{w:'弟子',f:'でし',m:'discípulo / aprendiz',l:'N4'},{w:'兄弟',f:'きょうだい',m:'hermanos',l:'N4'}]},
  { rank:1219, k:'兄', level:'N4', meanings:['hermano mayor'], on:['ケイ','キョウ'], kun:['あに'],
    words:[{w:'兄弟',f:'きょうだい',m:'hermanos',l:'N4'}]},
  { rank:1223, k:'泳', level:'N4', meanings:['nadar'], on:['エイ'], kun:['およ.ぐ'],
    words:[{w:'水泳',f:'すいえい',m:'natación',l:'N4'}]},
  { rank:1442, k:'暑', level:'N4', meanings:['caluroso (tiempo)'], on:['ショ'], kun:['あつ.い'],
    words:[{w:'猛暑',f:'もうしょ',m:'calor intenso / ola de calor',l:'N2'}]},
  { rank:1446, k:'妹', level:'N4', meanings:['hermana menor'], on:['マイ'], kun:['いもうと'],
    words:[{w:'姉妹',f:'しまい',m:'hermanas',l:'N4'}]},
  { rank:1473, k:'姉', level:'N4', meanings:['hermana mayor'], on:['シ'], kun:['あね'],
    words:[{w:'姉妹',f:'しまい',m:'hermanas',l:'N4'}]},
  { rank:1487, k:'漢', level:'N4', meanings:['China','carácter chino','hombre'], on:['カン'], kun:[],
    words:[{w:'漢字',f:'かんじ',m:'kanji / carácter chino',l:'N5'},{w:'漢語',f:'かんご',m:'palabra de origen chino',l:'N4'},{w:'漢文',f:'かんぶん',m:'texto clásico chino',l:'N4'}]},
]
