import type { Kanji } from './types'

// N3: 349 kanji

export const kanjiN3: Kanji[] = [
  { rank:38, k:'者', level:'N3', meanings:['persona','individuo'], on:['シャ'], kun:['もの'],
    words:[{w:'医者',f:'いしゃ',m:'médico',l:'N5'},{w:'若者',f:'わかもの',m:'joven',l:'N3'},{w:'読者',f:'どくしゃ',m:'lector',l:'N3'},]},
  { rank:43, k:'業', level:'N3', meanings:['negocio','trabajo','industria'], on:['ギョウ','ゴウ'], kun:['わざ'],
    words:[{w:'授業',f:'じゅぎょう',m:'clase / lección',l:'N5'},{w:'卒業',f:'そつぎょう',m:'graduación',l:'N3'},{w:'職業',f:'しょくぎょう',m:'profesión',l:'N3'},]},
  { rank:54, k:'員', level:'N3', meanings:['miembro','empleado'], on:['イン'], kun:[],
    words:[{w:'店員',f:'てんいん',m:'dependiente',l:'N4'},{w:'会員',f:'かいいん',m:'miembro',l:'N4'},{w:'社員',f:'しゃいん',m:'empleado',l:'N4'},]},
  { rank:66, k:'代', level:'N3', meanings:['generación','época','tarifa'], on:['ダイ','タイ'], kun:['かわ.る','よ'],
    words:[{w:'時代',f:'じだい',m:'época / era',l:'N4'},{w:'電話代',f:'でんわだい',m:'tarifa telefónica',l:'N4'}]},
  { rank:99, k:'意', level:'N3', meanings:['idea','mente','intención'], on:['イ'], kun:[],
    words:[{w:'意味',f:'いみ',m:'significado',l:'N5'},{w:'注意',f:'ちゅうい',m:'atención / cuidado',l:'N4'},{w:'意見',f:'いけん',m:'opinión',l:'N4'},{w:'用意',f:'ようい',m:'preparación',l:'N4'}]},
  { rank:107, k:'用', level:'N3', meanings:['uso','negocio','emplear'], on:['ヨウ'], kun:['もち.いる'],
    words:[{w:'使用',f:'しよう',m:'uso / utilización',l:'N4'},{w:'用意',f:'ようい',m:'preparación',l:'N4'},{w:'費用',f:'ひよう',m:'gasto / coste',l:'N4'},{w:'用事',f:'ようじ',m:'asunto / recado',l:'N4'}]},
  { rank:110, k:'度', level:'N3', meanings:['grado','vez','frecuencia'], on:['ド','ト'], kun:['たび'],
    words:[{w:'今度',f:'こんど',m:'esta vez / próxima vez',l:'N5'},{w:'温度',f:'おんど',m:'temperatura',l:'N4'},{w:'程度',f:'ていど',m:'grado / nivel',l:'N4'},{w:'毎度',f:'まいど',m:'cada vez',l:'N4'}]},
  { rank:126, k:'以', level:'N3', meanings:['por medio de','a partir de'], on:['イ'], kun:[],
    words:[{w:'以上',f:'いじょう',m:'más de / en adelante',l:'N4'},{w:'以下',f:'いか',m:'menos de / a continuación',l:'N4'},{w:'以前',f:'いぜん',m:'antes / anteriormente',l:'N4'},{w:'以外',f:'いがい',m:'excepto / aparte de',l:'N4'}]},
  { rank:229, k:'死', level:'N3', meanings:['morir','muerte'], on:['シ'], kun:['し.ぬ'],
    words:[{w:'必死',f:'ひっし',m:'desesperado',l:'N3'},{w:'死亡',f:'しぼう',m:'fallecimiento',l:'N3'},{w:'死者',f:'ししゃ',m:'víctima mortal',l:'N3'}]},
  { rank:233, k:'感', level:'N3', meanings:['sentir','emoción'], on:['カン'], kun:[],
    words:[{w:'感動',f:'かんどう',m:'emoción profunda',l:'N4'},{w:'感想',f:'かんそう',m:'impresión / opinión',l:'N4'},]},
  { rank:236, k:'第', level:'N3', meanings:['número ordinal','ranking'], on:['ダイ'], kun:[],
    words:[{w:'第一',f:'だいいち',m:'primero / número uno',l:'N4'},{w:'次第',f:'しだい',m:'según / dependiendo de',l:'N3'}]},
  { rank:268, k:'達', level:'N3', meanings:['alcanzar','plural (personas)'], on:['タツ'], kun:[],
    words:[{w:'友達',f:'ともだち',m:'amigo',l:'N5'},{w:'達成',f:'たっせい',m:'logro',l:'N3'},{w:'上達',f:'じょうたつ',m:'progreso',l:'N3'}]},
  { rank:271, k:'表', level:'N3', meanings:['tabla','expresar','exterior'], on:['ヒョウ'], kun:['おもて','あらわ.す'],
    words:[{w:'発表',f:'はっぴょう',m:'presentación / anuncio',l:'N4'},{w:'表現',f:'ひょうげん',m:'expresión',l:'N3'},{w:'表面',f:'ひょうめん',m:'superficie',l:'N3'}]},
  { rank:272, k:'記', level:'N3', meanings:['registrar','anotar'], on:['キ'], kun:['しる.す'],
    words:[{w:'日記',f:'にっき',m:'diario',l:'N4'},{w:'記念',f:'きねん',m:'conmemoración',l:'N3'},{w:'記者',f:'きしゃ',m:'periodista',l:'N3'}]},
  { rank:274, k:'全', level:'N3', meanings:['todo','completo'], on:['ゼン'], kun:['すべ.て','まった.く'],
    words:[{w:'全部',f:'ぜんぶ',m:'todo',l:'N4'},{w:'全員',f:'ぜんいん',m:'todos los miembros',l:'N3'},{w:'完全',f:'かんぜん',m:'perfecto / completo',l:'N3'}]},
  { rank:275, k:'的', level:'N3', meanings:['objetivo','(sufijo adjetival)'], on:['テキ'], kun:['まと'],
    words:[{w:'目的',f:'もくてき',m:'propósito',l:'N4'},{w:'具体的',f:'ぐたいてき',m:'concreto',l:'N3'}]},
  { rank:276, k:'次', level:'N3', meanings:['siguiente','próximo'], on:['ジ','シ'], kun:['つぎ'],
    words:[{w:'次第',f:'しだい',m:'según / dependiendo de',l:'N3'},{w:'次回',f:'じかい',m:'próxima vez',l:'N3'}]},
  { rank:277, k:'量', level:'N3', meanings:['cantidad','volumen','medir'], on:['リョウ'], kun:['はか.る'],
    words:[{w:'大量',f:'たいりょう',m:'gran cantidad',l:'N3'},{w:'重量',f:'じゅうりょう',m:'peso / masa',l:'N3'},{w:'少量',f:'しょうりょう',m:'pequeña cantidad',l:'N3'}]},
  { rank:277, k:'最', level:'N3', meanings:['más','el más'], on:['サイ'], kun:['もっと.も'],
    words:[{w:'最初',f:'さいしょ',m:'el primero',l:'N4'},{w:'最近',f:'さいきん',m:'recientemente',l:'N4'},{w:'最終',f:'さいしゅう',m:'último / final',l:'N4'}]},
  { rank:278, k:'続', level:'N3', meanings:['continuar'], on:['ゾク'], kun:['つづ.く','つづ.ける'],
    words:[{w:'接続',f:'せつぞく',m:'conexión',l:'N3'},{w:'継続',f:'けいぞく',m:'continuación',l:'N3'},{w:'手続き',f:'てつづき',m:'procedimiento',l:'N3'}]},
  { rank:279, k:'変', level:'N3', meanings:['cambiar','extraño'], on:['ヘン'], kun:['か.わる'],
    words:[{w:'大変',f:'たいへん',m:'difícil / muy',l:'N5'},{w:'変更',f:'へんこう',m:'cambio / modificación',l:'N3'},{w:'変化',f:'へんか',m:'cambio',l:'N3'}]},
  { rank:280, k:'関', level:'N3', meanings:['relacionar','barrera'], on:['カン'], kun:['せき','かか.わる'],
    words:[{w:'関係',f:'かんけい',m:'relación',l:'N4'},{w:'玄関',f:'げんかん',m:'entrada de casa',l:'N4'},{w:'関心',f:'かんしん',m:'interés',l:'N4'}]},
  { rank:281, k:'現', level:'N3', meanings:['presente','aparecer'], on:['ゲン'], kun:['あらわ.れる'],
    words:[{w:'現在',f:'げんざい',m:'actualmente',l:'N4'},{w:'現実',f:'げんじつ',m:'realidad',l:'N3'},{w:'表現',f:'ひょうげん',m:'expresión',l:'N3'}]},
  { rank:282, k:'進', level:'N3', meanings:['avanzar','progresar'], on:['シン'], kun:['すす.む'],
    words:[{w:'進歩',f:'しんぽ',m:'progreso',l:'N4'},{w:'前進',f:'ぜんしん',m:'avance',l:'N3'},{w:'進学',f:'しんがく',m:'avance académico',l:'N3'}]},
  { rank:284, k:'失', level:'N3', meanings:['perder','fallar'], on:['シツ'], kun:['うしな.う'],
    words:[{w:'失礼',f:'しつれい',m:'descortesía',l:'N4'},{w:'失敗',f:'しっぱい',m:'fracaso',l:'N4'}]},
  { rank:285, k:'望', level:'N3', meanings:['desear','esperanza'], on:['ボウ'], kun:['のぞ.む'],
    words:[{w:'希望',f:'きぼう',m:'esperanza',l:'N4'},{w:'失望',f:'しつぼう',m:'decepción',l:'N3'},{w:'絶望',f:'ぜつぼう',m:'desesperanza',l:'N3'}]},
  { rank:286, k:'決', level:'N3', meanings:['decidir'], on:['ケツ'], kun:['き.める','き.まる'],
    words:[{w:'決心',f:'けっしん',m:'determinación',l:'N3'},{w:'決定',f:'けってい',m:'decisión',l:'N3'},{w:'解決',f:'かいけつ',m:'solución',l:'N3'}]},
  { rank:288, k:'調', level:'N3', meanings:['investigar','ajustar'], on:['チョウ'], kun:['しら.べる','ととの.える'],
    words:[{w:'調子',f:'ちょうし',m:'condición / ritmo',l:'N4'},{w:'調査',f:'ちょうさ',m:'investigación',l:'N3'},{w:'強調',f:'きょうちょう',m:'énfasis',l:'N3'}]},
  { rank:289, k:'確', level:'N3', meanings:['confirmar','seguro'], on:['カク'], kun:['たし.かめる'],
    words:[{w:'正確',f:'せいかく',m:'exacto / preciso',l:'N4'},{w:'確実',f:'かくじつ',m:'seguro / certero',l:'N3'},{w:'確認',f:'かくにん',m:'confirmación',l:'N3'}]},
  { rank:290, k:'能', level:'N3', meanings:['habilidad','capaz'], on:['ノウ'], kun:[],
    words:[{w:'可能',f:'かのう',m:'posible',l:'N3'},{w:'能力',f:'のうりょく',m:'capacidad',l:'N3'},{w:'機能',f:'きのう',m:'función',l:'N3'}]},
  { rank:291, k:'活', level:'N3', meanings:['vivir','activo'], on:['カツ'], kun:['い.きる'],
    words:[{w:'生活',f:'せいかつ',m:'vida cotidiana',l:'N4'},{w:'活動',f:'かつどう',m:'actividad',l:'N4'},{w:'活用',f:'かつよう',m:'uso activo',l:'N3'}]},
  { rank:292, k:'機', level:'N3', meanings:['máquina','oportunidad'], on:['キ'], kun:['はた'],
    words:[{w:'飛行機',f:'ひこうき',m:'avión',l:'N5'},{w:'機会',f:'きかい',m:'oportunidad',l:'N4'},{w:'機能',f:'きのう',m:'función',l:'N3'}]},
  { rank:293, k:'術', level:'N3', meanings:['arte','técnica'], on:['ジュツ'], kun:[],
    words:[{w:'手術',f:'しゅじゅつ',m:'cirugía',l:'N4'},{w:'芸術',f:'げいじゅつ',m:'arte',l:'N3'},{w:'技術',f:'ぎじゅつ',m:'tecnología / técnica',l:'N3'}]},
  { rank:294, k:'査', level:'N3', meanings:['investigar','inspeccionar','examinar'], on:['サ'], kun:[],
    words:[{w:'調査',f:'ちょうさ',m:'investigación / encuesta',l:'N3'},{w:'検査',f:'けんさ',m:'inspección / examen médico',l:'N3'},{w:'審査',f:'しんさ',m:'selección / evaluación',l:'N3'}]},
  { rank:295, k:'困', level:'N3', meanings:['estar en apuros'], on:['コン'], kun:['こま.る'],
    words:[{w:'困難',f:'こんなん',m:'dificultad',l:'N3'},{w:'貧困',f:'ひんこん',m:'pobreza',l:'N3'}]},
  { rank:297, k:'政', level:'N3', meanings:['gobierno','política'], on:['セイ','ショウ'], kun:['まつりごと'],
    words:[{w:'政治',f:'せいじ',m:'política',l:'N3'},{w:'政府',f:'せいふ',m:'gobierno',l:'N3'},{w:'行政',f:'ぎょうせい',m:'administración pública',l:'N3'}]},
  { rank:298, k:'議', level:'N3', meanings:['debatir','asamblea'], on:['ギ'], kun:[],
    words:[{w:'会議',f:'かいぎ',m:'reunión / conferencia',l:'N4'},{w:'議論',f:'ぎろん',m:'debate',l:'N3'},{w:'議員',f:'ぎいん',m:'parlamentario',l:'N3'}]},
  { rank:298, k:'無', level:'N3', meanings:['nada','sin','imposible'], on:['ム','ブ'], kun:['な.い'],
    words:[{w:'無料',f:'むりょう',m:'gratis',l:'N4'},{w:'無理',f:'むり',m:'imposible / forzar',l:'N4'},{w:'無駄',f:'むだ',m:'desperdicio / en vano',l:'N3'}]},
  { rank:300, k:'連', level:'N3', meanings:['unir','conectar','llevar'], on:['レン'], kun:['つら.なる','つ.れる'],
    words:[{w:'連絡',f:'れんらく',m:'contacto / comunicación',l:'N4'},{w:'連続',f:'れんぞく',m:'continuación / serie',l:'N3'}]},
  { rank:300, k:'建', level:'N3', meanings:['construir','edificar'], on:['ケン','コン'], kun:['た.てる'],
    words:[{w:'建物',f:'たてもの',m:'edificio',l:'N5'},{w:'建設',f:'けんせつ',m:'construcción',l:'N3'},]},
  { rank:301, k:'対', level:'N3', meanings:['opuesto','contra'], on:['タイ','ツイ'], kun:[],
    words:[{w:'対話',f:'たいわ',m:'diálogo',l:'N3'},{w:'反対',f:'はんたい',m:'oposición',l:'N3'},{w:'対応',f:'たいおう',m:'respuesta / reacción',l:'N3'}]},
  { rank:303, k:'保', level:'N3', meanings:['preservar','proteger','mantener'], on:['ホ','ホウ'], kun:['たも.つ'],
    words:[{w:'保険',f:'ほけん',m:'seguro',l:'N4'},{w:'保護',f:'ほご',m:'protección',l:'N3'},{w:'保存',f:'ほぞん',m:'conservación / guardar',l:'N3'},{w:'確保',f:'かくほ',m:'asegurar / garantizar',l:'N3'}]},
  { rank:304, k:'各', level:'N3', meanings:['cada','respectivo'], on:['カク'], kun:['おのおの'],
    words:[{w:'各自',f:'かくじ',m:'cada uno / individualmente',l:'N3'},{w:'各地',f:'かくち',m:'cada región / por todo el país',l:'N3'}]},
  { rank:305, k:'相', level:'N3', meanings:['mutuo','ministro','aspecto'], on:['ソウ','ショウ'], kun:['あい'],
    words:[{w:'相談',f:'そうだん',m:'consulta / consejo',l:'N4'},{w:'相互',f:'そうご',m:'mutuo / recíproco',l:'N3'},{w:'相手',f:'あいて',m:'interlocutor / contrario',l:'N3'}]},
  { rank:306, k:'定', level:'N3', meanings:['determinar','fijar','establecer'], on:['テイ','ジョウ'], kun:['さだ.める'],
    words:[{w:'予定',f:'よてい',m:'plan / horario',l:'N4'},{w:'決定',f:'けってい',m:'decisión',l:'N3'},{w:'定期',f:'ていき',m:'periódico / abono',l:'N3'}]},
  { rank:307, k:'回', level:'N3', meanings:['vuelta','vez','girar'], on:['カイ','エ'], kun:['まわ.る'],
    words:[{w:'今回',f:'こんかい',m:'esta vez',l:'N4'},{w:'回答',f:'かいとう',m:'respuesta',l:'N4'},{w:'毎回',f:'まいかい',m:'cada vez',l:'N3'}]},
  { rank:308, k:'選', level:'N3', meanings:['elegir','seleccionar'], on:['セン'], kun:['えら.ぶ'],
    words:[{w:'選手',f:'せんしゅ',m:'atleta / jugador',l:'N3'},{w:'選択',f:'せんたく',m:'selección',l:'N3'},{w:'当選',f:'とうせん',m:'ser elegido / ganar',l:'N3'}]},
  { rank:309, k:'実', level:'N3', meanings:['realidad','fruto','verdad'], on:['ジツ'], kun:['み','みの.る'],
    words:[{w:'実際',f:'じっさい',m:'en la práctica',l:'N3'},{w:'現実',f:'げんじつ',m:'realidad',l:'N3'}]},
  { rank:310, k:'戦', level:'N3', meanings:['guerra','batalla','luchar'], on:['セン'], kun:['いくさ','たたか.う'],
    words:[{w:'戦争',f:'せんそう',m:'guerra',l:'N3'},{w:'挑戦',f:'ちょうせん',m:'desafío',l:'N3'}]},
  { rank:311, k:'経', level:'N3', meanings:['pasar','transcurrir','longitud'], on:['ケイ','キョウ'], kun:['へ.る','た.つ'],
    words:[{w:'経験',f:'けいけん',m:'experiencia',l:'N4'},{w:'経済',f:'けいざい',m:'economía',l:'N3'},{w:'経営',f:'けいえい',m:'gestión / administración',l:'N3'}]},
  { rank:314, k:'約', level:'N3', meanings:['promesa','aproximadamente'], on:['ヤク'], kun:[],
    words:[{w:'約束',f:'やくそく',m:'promesa',l:'N4'},{w:'条約',f:'じょうやく',m:'tratado',l:'N3'},{w:'契約',f:'けいやく',m:'contrato',l:'N3'}]},
  { rank:315, k:'首', level:'N3', meanings:['cuello','cabeza','primero'], on:['シュ'], kun:['くび'],
    words:[{w:'首相',f:'しゅしょう',m:'primer ministro',l:'N3'},{w:'首都',f:'しゅと',m:'capital',l:'N3'},{w:'手首',f:'てくび',m:'muñeca',l:'N3'}]},
  { rank:317, k:'性', level:'N3', meanings:['sexo','género','naturaleza'], on:['セイ','ショウ'], kun:[],
    words:[{w:'男性',f:'だんせい',m:'hombre / masculino',l:'N4'},{w:'性格',f:'せいかく',m:'personalidad / carácter',l:'N3'},{w:'可能性',f:'かのうせい',m:'posibilidad',l:'N3'}]},
  { rank:318, k:'要', level:'N3', meanings:['necesario','esencia','punto principal'], on:['ヨウ'], kun:['い','かなめ'],
    words:[{w:'必要',f:'ひつよう',m:'necesario',l:'N4'},{w:'重要',f:'じゅうよう',m:'importante',l:'N4'},{w:'要求',f:'ようきゅう',m:'demanda / petición',l:'N3'}]},
  { rank:320, k:'治', level:'N3', meanings:['gobernar','curar','sanar'], on:['ジ','チ'], kun:['おさ.める','なお.る'],
    words:[{w:'政治',f:'せいじ',m:'política',l:'N3'},{w:'治療',f:'ちりょう',m:'tratamiento médico',l:'N3'},{w:'治安',f:'ちあん',m:'orden público',l:'N3'}]},
  { rank:322, k:'率', level:'N3', meanings:['tasa','proporción','liderar'], on:['ソツ','リツ'], kun:['ひき.いる'],
    words:[{w:'確率',f:'かくりつ',m:'probabilidad',l:'N3'},{w:'効率',f:'こうりつ',m:'eficiencia',l:'N3'},{w:'比率',f:'ひりつ',m:'tasa / proporción',l:'N3'}]},
  { rank:322, k:'成', level:'N3', meanings:['convertirse','lograr','alcanzar'], on:['セイ','ジョウ'], kun:['な.る'],
    words:[{w:'成長',f:'せいちょう',m:'crecimiento',l:'N4'},{w:'成功',f:'せいこう',m:'éxito',l:'N3'},{w:'達成',f:'たっせい',m:'logro',l:'N3'}]},
  { rank:323, k:'期', level:'N3', meanings:['período','temporada','plazo'], on:['キ','ゴ'], kun:[],
    words:[{w:'時期',f:'じき',m:'momento / período',l:'N4'},{w:'期間',f:'きかん',m:'período de tiempo',l:'N4'},{w:'期待',f:'きたい',m:'expectativa',l:'N4'}]},
  { rank:324, k:'取', level:'N3', meanings:['tomar','coger','obtener'], on:['シュ'], kun:['と.る'],
    words:[{w:'取引',f:'とりひき',m:'transacción',l:'N3'},{w:'取材',f:'しゅざい',m:'cobertura / reportaje',l:'N3'},{w:'取得',f:'しゅとく',m:'adquisición',l:'N3'}]},
  { rank:326, k:'和', level:'N3', meanings:['armonía','paz','estilo japonés'], on:['ワ','オ'], kun:['やわ.らぐ','なご.む'],
    words:[{w:'和食',f:'わしょく',m:'comida japonesa',l:'N4'},{w:'平和',f:'へいわ',m:'paz',l:'N3'},{w:'調和',f:'ちょうわ',m:'armonía',l:'N3'}]},
  { rank:327, k:'平', level:'N3', meanings:['plano','tranquilo','igual'], on:['ヘイ','ビョウ'], kun:['たい','ひら'],
    words:[{w:'平日',f:'へいじつ',m:'día laborable',l:'N4'},{w:'平和',f:'へいわ',m:'paz',l:'N3'},{w:'平均',f:'へいきん',m:'promedio',l:'N3'}]},
  { rank:327, k:'転', level:'N3', meanings:['rodar','girar','cambiar'], on:['テン'], kun:['ころ.ぶ','うつ.る'],
    words:[{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},{w:'運転',f:'うんてん',m:'conducción',l:'N5'},{w:'転校',f:'てんこう',m:'cambio de escuela',l:'N4'}]},
  { rank:329, k:'受', level:'N3', meanings:['recibir','aceptar','sufrir'], on:['ジュ'], kun:['う.ける'],
    words:[{w:'受験',f:'じゅけん',m:'presentarse a examen',l:'N4'},{w:'受付',f:'うけつけ',m:'recepción',l:'N3'},{w:'受信',f:'じゅしん',m:'recepción (mensaje/señal)',l:'N3'}]},
  { rank:331, k:'初', level:'N3', meanings:['primero','principio','primera vez'], on:['ショ'], kun:['はつ','はじ.めて','うい'],
    words:[{w:'最初',f:'さいしょ',m:'el primero / al principio',l:'N4'},{w:'初心者',f:'しょしんしゃ',m:'principiante',l:'N3'},{w:'初級',f:'しょきゅう',m:'nivel básico / principiante',l:'N3'}]},
  { rank:332, k:'指', level:'N3', meanings:['dedo','señalar','indicar'], on:['シ'], kun:['ゆび','さ.す'],
    words:[{w:'指導',f:'しどう',m:'orientación / instrucción',l:'N3'},{w:'指示',f:'しじ',m:'instrucción',l:'N3'},{w:'指輪',f:'ゆびわ',m:'anillo',l:'N3'}]},
  { rank:333, k:'個', level:'N3', meanings:['individuo','pieza','artículo'], on:['コ','カ'], kun:[],
    words:[{w:'個人',f:'こじん',m:'individuo / personal',l:'N3'},{w:'個別',f:'こべつ',m:'individual / separado',l:'N3'},{w:'個性',f:'こせい',m:'personalidad / carácter único',l:'N3'}]},
  { rank:334, k:'支', level:'N3', meanings:['apoyar','rama','sustentar'], on:['シ'], kun:['ささ.える'],
    words:[{w:'支配',f:'しはい',m:'dominio / control',l:'N3'},{w:'支持',f:'しじ',m:'apoyo',l:'N3'},{w:'支払い',f:'しはらい',m:'pago',l:'N3'}]},
  { rank:335, k:'点', level:'N3', meanings:['punto','marca','nota'], on:['テン'], kun:[],
    words:[{w:'点数',f:'てんすう',m:'puntuación',l:'N3'},{w:'観点',f:'かんてん',m:'punto de vista',l:'N3'},{w:'欠点',f:'けってん',m:'defecto / punto débil',l:'N3'}]},
  { rank:336, k:'報', level:'N3', meanings:['informar','noticia','recompensar'], on:['ホウ'], kun:['むく.いる'],
    words:[{w:'情報',f:'じょうほう',m:'información',l:'N3'},{w:'報告',f:'ほうこく',m:'informe',l:'N3'},{w:'報道',f:'ほうどう',m:'noticias / cobertura',l:'N3'}]},
  { rank:337, k:'済', level:'N3', meanings:['concluir','saldar','economía'], on:['サイ'], kun:['す.む'],
    words:[{w:'経済',f:'けいざい',m:'economía',l:'N3'},{w:'返済',f:'へんさい',m:'reembolso',l:'N3'}]},
  { rank:337, k:'結', level:'N3', meanings:['unir','ligar','concluir'], on:['ケツ','ケチ'], kun:['むす.ぶ'],
    words:[{w:'結果',f:'けっか',m:'resultado',l:'N3'},{w:'結婚',f:'けっこん',m:'matrimonio / boda',l:'N4'},{w:'結論',f:'けつろん',m:'conclusión',l:'N3'},{w:'結局',f:'けっきょく',m:'al final / en definitiva',l:'N3'}]},
  { rank:340, k:'解', level:'N3', meanings:['resolver','entender','desatar'], on:['カイ','ゲ'], kun:['と.く'],
    words:[{w:'理解',f:'りかい',m:'comprensión',l:'N4'},{w:'解決',f:'かいけつ',m:'solución',l:'N3'},{w:'解説',f:'かいせつ',m:'explicación / comentario',l:'N3'}]},
  { rank:343, k:'予', level:'N3', meanings:['por anticipado','de antemano'], on:['ヨ','シャ'], kun:['あらかじ.め'],
    words:[{w:'予定',f:'よてい',m:'plan / horario',l:'N4'},{w:'予約',f:'よやく',m:'reserva',l:'N4'},{w:'予算',f:'よさん',m:'presupuesto',l:'N3'}]},
  { rank:344, k:'向', level:'N3', meanings:['orientarse hacia','dirección'], on:['コウ'], kun:['む.く','むか.う'],
    words:[{w:'向上',f:'こうじょう',m:'mejora / progreso',l:'N3'},{w:'方向',f:'ほうこう',m:'dirección',l:'N4'},{w:'傾向',f:'けいこう',m:'tendencia',l:'N3'}]},
  { rank:345, k:'勝', level:'N3', meanings:['victoria','ganar','superar'], on:['ショウ'], kun:['か.つ'],
    words:[{w:'勝利',f:'しょうり',m:'victoria',l:'N3'},{w:'優勝',f:'ゆうしょう',m:'campeonato',l:'N3'},{w:'勝負',f:'しょうぶ',m:'combate / competición',l:'N3'}]},
  { rank:346, k:'面', level:'N3', meanings:['cara','superficie','aspecto'], on:['メン'], kun:['おも','おもて','つら'],
    words:[{w:'場面',f:'ばめん',m:'escena',l:'N3'},{w:'正面',f:'しょうめん',m:'frente / fachada',l:'N3'}]},
  { rank:347, k:'告', level:'N3', meanings:['anunciar','notificar','informar'], on:['コク'], kun:['つ.げる'],
    words:[{w:'広告',f:'こうこく',m:'publicidad',l:'N4'},{w:'報告',f:'ほうこく',m:'informe',l:'N3'},{w:'告白',f:'こくはく',m:'confesión',l:'N3'}]},
  { rank:348, k:'反', level:'N3', meanings:['oponer','anti-','rebelarse'], on:['ホン','ハン','タン'], kun:['そ.る'],
    words:[{w:'反対',f:'はんたい',m:'oposición',l:'N3'},{w:'反省',f:'はんせい',m:'reflexión / arrepentimiento',l:'N3'},{w:'反応',f:'はんのう',m:'reacción',l:'N3'}]},
  { rank:349, k:'判', level:'N3', meanings:['juzgar','sello','tamaño'], on:['ハン','バン'], kun:[],
    words:[{w:'判断',f:'はんだん',m:'juicio / decisión',l:'N3'},{w:'裁判',f:'さいばん',m:'juicio / tribunal',l:'N3'},{w:'批判',f:'ひはん',m:'crítica',l:'N3'}]},
  { rank:350, k:'認', level:'N3', meanings:['reconocer','admitir','aprobar'], on:['ニン'], kun:['みと.める'],
    words:[{w:'公認',f:'こうにん',m:'reconocimiento oficial',l:'N3'},{w:'確認',f:'かくにん',m:'confirmación',l:'N3'},{w:'認識',f:'にんしき',m:'reconocimiento',l:'N3'}]},
  { rank:353, k:'組', level:'N3', meanings:['grupo','equipo','ensamblar'], on:['ソ'], kun:['く.む','くみ'],
    words:[{w:'番組',f:'ばんぐみ',m:'programa (TV/radio)',l:'N3'},{w:'組織',f:'そしき',m:'organización',l:'N3'},{w:'組み合わせ',f:'くみあわせ',m:'combinación',l:'N3'}]},
  { rank:354, k:'信', level:'N3', meanings:['creer','confiar','fe'], on:['シン'], kun:[],
    words:[{w:'自信',f:'じしん',m:'confianza en uno mismo',l:'N3'},{w:'信頼',f:'しんらい',m:'confianza',l:'N3'},{w:'信号',f:'しんごう',m:'semáforo / señal',l:'N4'}]},
  { rank:355, k:'在', level:'N3', meanings:['existir','estar presente'], on:['ザイ'], kun:['あ.る'],
    words:[{w:'現在',f:'げんざい',m:'actualmente',l:'N4'},{w:'存在',f:'そんざい',m:'existencia',l:'N3'},{w:'不在',f:'ふざい',m:'ausencia',l:'N3'}]},
  { rank:357, k:'側', level:'N3', meanings:['lado','flanco'], on:['ソク'], kun:['がわ','そば'],
    words:[{w:'右側',f:'みぎがわ',m:'lado derecho',l:'N5'},{w:'内側',f:'うちがわ',m:'interior',l:'N3'},{w:'外側',f:'そとがわ',m:'exterior',l:'N3'}]},
  { rank:358, k:'任', level:'N3', meanings:['encomendar','responsabilidad','deber'], on:['ニン'], kun:['まか.せる'],
    words:[{w:'責任',f:'せきにん',m:'responsabilidad',l:'N3'},{w:'担任',f:'たんにん',m:'tutor de clase',l:'N3'},{w:'主任',f:'しゅにん',m:'jefe / encargado',l:'N3'}]},
  { rank:359, k:'引', level:'N3', meanings:['tirar','jalar','atraer'], on:['イン'], kun:['ひ.く'],
    words:[{w:'引っ越し',f:'ひっこし',m:'mudanza',l:'N4'},{w:'引用',f:'いんよう',m:'cita / citar',l:'N3'},{w:'値引き',f:'ねびき',m:'descuento',l:'N3'}]},
  { rank:360, k:'求', level:'N3', meanings:['pedir','solicitar','buscar'], on:['キュウ'], kun:['もと.める'],
    words:[{w:'追求',f:'ついきゅう',m:'persecución / búsqueda',l:'N3'},{w:'要求',f:'ようきゅう',m:'demanda / petición',l:'N3'},{w:'求人',f:'きゅうじん',m:'oferta de empleo',l:'N3'}]},
  { rank:362, k:'昨', level:'N3', meanings:['ayer','anterior','pasado'], on:['サク'], kun:[],
    words:[{w:'昨日',f:'きのう',m:'ayer',l:'N5'},{w:'昨年',f:'さくねん',m:'el año pasado',l:'N4'},{w:'昨夜',f:'さくや',m:'anoche',l:'N3'}]},
  { rank:364, k:'官', level:'N3', meanings:['burocracia','funcionario'], on:['カン'], kun:[],
    words:[{w:'官庁',f:'かんちょう',m:'ministerio / agencia',l:'N3'},{w:'警官',f:'けいかん',m:'policía',l:'N3'},{w:'器官',f:'きかん',m:'órgano',l:'N3'}]},
  { rank:366, k:'係', level:'N3', meanings:['encargado','relacionado','vinculado'], on:['ケイ'], kun:['かか','かかり'],
    words:[{w:'関係',f:'かんけい',m:'relación',l:'N4'},{w:'係員',f:'かかりいん',m:'persona encargada',l:'N3'}]},
  { rank:366, k:'線', level:'N3', meanings:['línea','raíl','traza'], on:['セン'], kun:[],
    words:[{w:'新幹線',f:'しんかんせん',m:'tren bala (Shinkansen)',l:'N3'},{w:'路線',f:'ろせん',m:'línea de transporte',l:'N3'},{w:'直線',f:'ちょくせん',m:'línea recta',l:'N3'}]},
  { rank:367, k:'情', level:'N3', meanings:['emoción','sentimiento','compasión'], on:['ジョウ','セイ'], kun:['なさ.け'],
    words:[{w:'感情',f:'かんじょう',m:'emoción',l:'N3'},{w:'事情',f:'じじょう',m:'circunstancias',l:'N3'},{w:'情報',f:'じょうほう',m:'información',l:'N3'}]},
  { rank:368, k:'投', level:'N3', meanings:['lanzar','arrojar','invertir'], on:['トウ'], kun:['な.げる'],
    words:[{w:'投手',f:'とうしゅ',m:'lanzador (béisbol)',l:'N3'},{w:'投票',f:'とうひょう',m:'voto',l:'N3'},{w:'投資',f:'とうし',m:'inversión',l:'N3'}]},
  { rank:369, k:'示', level:'N3', meanings:['mostrar','indicar','exhibir'], on:['ジ','シ'], kun:['しめ.す'],
    words:[{w:'表示',f:'ひょうじ',m:'visualización / indicación',l:'N3'},{w:'指示',f:'しじ',m:'instrucción',l:'N3'},{w:'展示',f:'てんじ',m:'exposición / exhibición',l:'N3'}]},
  { rank:370, k:'打', level:'N3', meanings:['golpear','batear','teclear'], on:['ダ'], kun:['う.つ'],
    words:[{w:'打撃',f:'だげき',m:'golpe / impacto',l:'N3'},{w:'打ち合わせ',f:'うちあわせ',m:'reunión / coordinación',l:'N3'}]},
  { rank:371, k:'直', level:'N3', meanings:['recto','directo','corregir'], on:['チョク'], kun:['ただ.ちに','なお.す'],
    words:[{w:'直接',f:'ちょくせつ',m:'directo / directamente',l:'N4'},{w:'直線',f:'ちょくせん',m:'línea recta',l:'N3'},{w:'直前',f:'ちょくぜん',m:'justo antes',l:'N3'}]},
  { rank:373, k:'式', level:'N3', meanings:['ceremonia','estilo','fórmula'], on:['シキ'], kun:[],
    words:[{w:'卒業式',f:'そつぎょうしき',m:'ceremonia de graduación',l:'N4'},{w:'方式',f:'ほうしき',m:'método / sistema',l:'N3'}]},
  { rank:374, k:'果', level:'N3', meanings:['fruto','resultado','lograr'], on:['カ'], kun:['は.たす'],
    words:[{w:'果物',f:'くだもの',m:'fruta',l:'N5'},{w:'結果',f:'けっか',m:'resultado',l:'N3'},{w:'効果',f:'こうか',m:'efecto',l:'N3'}]},
  { rank:374, k:'起', level:'N3', meanings:['levantarse','ocurrir'], on:['キ'], kun:['お.きる','お.こる'],
    words:[{w:'早起き',f:'はやおき',m:'madrugar',l:'N4'},{w:'起立',f:'きりつ',m:'ponerse de pie',l:'N3'},{w:'起源',f:'きげん',m:'origen',l:'N3'}]},
  { rank:376, k:'必', level:'N3', meanings:['inevitable','sin falta','ciertamente'], on:['ヒツ'], kun:['かなら.ず'],
    words:[{w:'必要',f:'ひつよう',m:'necesario',l:'N4'},{w:'必死',f:'ひっし',m:'desesperado',l:'N3'},{w:'必然',f:'ひつぜん',m:'inevitable / necesario',l:'N3'}]},
  { rank:377, k:'演', level:'N3', meanings:['actuar','representar','realizar'], on:['エン'], kun:[],
    words:[{w:'演技',f:'えんぎ',m:'actuación',l:'N3'},{w:'演奏',f:'えんそう',m:'interpretación musical',l:'N3'},{w:'公演',f:'こうえん',m:'representación / actuación pública',l:'N3'}]},
  { rank:380, k:'談', level:'N3', meanings:['conversación','hablar','charla'], on:['ダン'], kun:[],
    words:[{w:'相談',f:'そうだん',m:'consulta / consejo',l:'N4'},{w:'冗談',f:'じょうだん',m:'broma',l:'N4'},{w:'会談',f:'かいだん',m:'conversación formal',l:'N3'}]},
  { rank:381, k:'位', level:'N3', meanings:['rango','grado','aproximadamente'], on:['イ'], kun:['くらい','ぐらい'],
    words:[{w:'位置',f:'いち',m:'posición',l:'N3'},{w:'地位',f:'ちい',m:'posición / rango',l:'N3'},{w:'単位',f:'たんい',m:'unidad',l:'N3'}]},
  { rank:382, k:'置', level:'N3', meanings:['colocar','poner','depositar'], on:['チ'], kun:['お.く'],
    words:[{w:'設置',f:'せっち',m:'instalación / establecimiento',l:'N3'},{w:'位置',f:'いち',m:'posición',l:'N3'},{w:'装置',f:'そうち',m:'dispositivo / aparato',l:'N3'}]},
  { rank:382, k:'準', level:'N3', meanings:['estándar','nivel','prepararse'], on:['ジュン'], kun:[],
    words:[{w:'準備',f:'じゅんび',m:'preparación',l:'N4'},{w:'基準',f:'きじゅん',m:'estándar / criterio',l:'N3'},{w:'水準',f:'すいじゅん',m:'nivel / estándar',l:'N3'}]},
  { rank:383, k:'流', level:'N3', meanings:['corriente','fluir','estilo'], on:['リュウ'], kun:['なが.れる'],
    words:[{w:'主流',f:'しゅりゅう',m:'corriente principal',l:'N3'},{w:'交流',f:'こうりゅう',m:'intercambio / interacción',l:'N3'},{w:'流行',f:'りゅうこう',m:'moda / tendencia',l:'N3'}]},
  { rank:384, k:'格', level:'N3', meanings:['rango','estatus','norma'], on:['カク','コウ','キャク'], kun:[],
    words:[{w:'資格',f:'しかく',m:'calificación / credencial',l:'N3'},{w:'性格',f:'せいかく',m:'personalidad',l:'N3'},{w:'合格',f:'ごうかく',m:'aprobado',l:'N3'}]},
  { rank:387, k:'局', level:'N3', meanings:['oficina','departamento','emisora'], on:['キョク'], kun:[],
    words:[{w:'郵便局',f:'ゆうびんきょく',m:'oficina de correos',l:'N5'},{w:'放送局',f:'ほうそうきょく',m:'emisora de radio/TV',l:'N3'},{w:'局面',f:'きょくめん',m:'situación / fase',l:'N3'}]},
  { rank:389, k:'管', level:'N3', meanings:['tubo','administrar','gestionar'], on:['カン'], kun:['くだ'],
    words:[{w:'管理',f:'かんり',m:'gestión / administración',l:'N4'},{w:'血管',f:'けっかん',m:'vaso sanguíneo',l:'N3'},{w:'管轄',f:'かんかつ',m:'jurisdicción',l:'N3'}]},
  { rank:389, k:'常', level:'N3', meanings:['normal','habitual','siempre'], on:['ジョウ'], kun:['つね','とこ'],
    words:[{w:'日常',f:'にちじょう',m:'cotidiano',l:'N3'},{w:'非常',f:'ひじょう',m:'emergencia / extremo',l:'N3'},{w:'常識',f:'じょうしき',m:'sentido común',l:'N3'}]},
  { rank:391, k:'球', level:'N3', meanings:['esfera','pelota'], on:['キュウ'], kun:['たま'],
    words:[{w:'野球',f:'やきゅう',m:'béisbol',l:'N4'},{w:'地球',f:'ちきゅう',m:'Tierra',l:'N4'},{w:'電球',f:'でんきゅう',m:'bombilla',l:'N3'}]},
  { rank:392, k:'職', level:'N3', meanings:['ocupación','empleo','trabajo'], on:['ショク'], kun:[],
    words:[{w:'職業',f:'しょくぎょう',m:'profesión',l:'N4'},{w:'職場',f:'しょくば',m:'lugar de trabajo',l:'N3'},{w:'就職',f:'しゅうしょく',m:'conseguir empleo',l:'N3'}]},
  { rank:394, k:'再', level:'N3', meanings:['de nuevo','otra vez','re-'], on:['サイ','サ'], kun:['ふた.たび'],
    words:[{w:'再開',f:'さいかい',m:'reanudación',l:'N3'},{w:'再度',f:'さいど',m:'de nuevo / una vez más',l:'N3'}]},
  { rank:394, k:'供', level:'N3', meanings:['ofrecer','acompañar','niño'], on:['キョウ','ク'], kun:['そな.える','とも'],
    words:[{w:'子供',f:'こども',m:'niño',l:'N5'},{w:'提供',f:'ていきょう',m:'provisión / aportación',l:'N3'},{w:'供給',f:'きょうきゅう',m:'suministro',l:'N3'}]},
  { rank:395, k:'設', level:'N3', meanings:['establecer','instalar','fundar'], on:['セツ'], kun:['もう.ける'],
    words:[{w:'設備',f:'せつび',m:'instalaciones / equipamiento',l:'N3'},{w:'設定',f:'せってい',m:'configuración / ajuste',l:'N3'},{w:'設計',f:'せっけい',m:'diseño / plano',l:'N3'}]},
  { rank:396, k:'構', level:'N3', meanings:['construir','estructura','no importar'], on:['コウ'], kun:['かま.う'],
    words:[{w:'結構',f:'けっこう',m:'bastante / está bien',l:'N4'},{w:'構造',f:'こうぞう',m:'estructura',l:'N3'},{w:'機構',f:'きこう',m:'mecanismo / organismo',l:'N3'}]},
  { rank:397, k:'効', level:'N3', meanings:['efecto','eficaz','efectivo'], on:['コウ'], kun:['き.く'],
    words:[{w:'効果',f:'こうか',m:'efecto',l:'N3'},{w:'効率',f:'こうりつ',m:'eficiencia',l:'N3'},{w:'有効',f:'ゆうこう',m:'válido / eficaz',l:'N3'}]},
  { rank:398, k:'身', level:'N3', meanings:['cuerpo','persona','uno mismo'], on:['シン'], kun:['み'],
    words:[{w:'出身',f:'しゅっしん',m:'origen / procedencia',l:'N4'},{w:'身体',f:'しんたい',m:'cuerpo',l:'N3'},{w:'自身',f:'じしん',m:'uno mismo',l:'N3'}]},
  { rank:399, k:'費', level:'N3', meanings:['gasto','coste','consumir'], on:['ヒ'], kun:['つい.やす'],
    words:[{w:'費用',f:'ひよう',m:'gasto / coste',l:'N4'},{w:'消費',f:'しょうひ',m:'consumo',l:'N3'},{w:'生活費',f:'せいかつひ',m:'gastos de vida',l:'N3'}]},
  { rank:400, k:'付', level:'N3', meanings:['adjuntar','añadir','pegar'], on:['フ'], kun:['つ.く','つ.ける'],
    words:[{w:'付近',f:'ふきん',m:'cercanías',l:'N3'},{w:'日付',f:'ひづけ',m:'fecha',l:'N3'}]},
  { rank:401, k:'型', level:'N3', meanings:['molde','tipo','modelo'], on:['ケイ'], kun:['かた'],
    words:[{w:'大型',f:'おおがた',m:'grande / de gran tamaño',l:'N3'},{w:'血液型',f:'けつえきがた',m:'grupo sanguíneo',l:'N3'},{w:'新型',f:'しんがた',m:'nuevo modelo / tipo nuevo',l:'N3'}]},
  { rank:401, k:'由', level:'N3', meanings:['origen','causa','razón'], on:['ユ','ユウ','ユイ'], kun:['よし'],
    words:[{w:'自由',f:'じゆう',m:'libertad',l:'N4'},{w:'理由',f:'りゆう',m:'razón / motivo',l:'N4'},{w:'由来',f:'ゆらい',m:'origen / procedencia',l:'N3'}]},
  { rank:402, k:'説', level:'N3', meanings:['teoría','explicar','persuadir'], on:['セツ','ゼイ'], kun:['と.く'],
    words:[{w:'説明',f:'せつめい',m:'explicación',l:'N4'},{w:'小説',f:'しょうせつ',m:'novela',l:'N4'},{w:'説得',f:'せっとく',m:'persuasión',l:'N3'}]},
  { rank:403, k:'難', level:'N3', meanings:['difícil','problema','desastre'], on:['ナン'], kun:['かた.い','むずか.しい'],
    words:[{w:'困難',f:'こんなん',m:'dificultad',l:'N3'},{w:'避難',f:'ひなん',m:'evacuación',l:'N3'},{w:'難民',f:'なんみん',m:'refugiado',l:'N3'}]},
  { rank:404, k:'優', level:'N3', meanings:['superior','excelente','gentil'], on:['ユウ'], kun:['やさ.しい','すぐ.れる'],
    words:[{w:'優先',f:'ゆうせん',m:'prioridad',l:'N3'},{w:'優勝',f:'ゆうしょう',m:'campeonato',l:'N3'},{w:'優秀',f:'ゆうしゅう',m:'excelente / destacado',l:'N3'}]},
  { rank:406, k:'収', level:'N3', meanings:['recaudar','recoger','ingreso'], on:['シュウ'], kun:['おさ.める'],
    words:[{w:'収入',f:'しゅうにゅう',m:'ingresos',l:'N4'},{w:'回収',f:'かいしゅう',m:'recogida / recuperación',l:'N3'},{w:'収集',f:'しゅうしゅう',m:'colección',l:'N3'}]},
  { rank:407, k:'断', level:'N3', meanings:['rechazar','cortar','decidir'], on:['ダン'], kun:['た.つ','ことわ.る'],
    words:[{w:'判断',f:'はんだん',m:'juicio / decisión',l:'N3'},{w:'診断',f:'しんだん',m:'diagnóstico',l:'N3'},{w:'中断',f:'ちゅうだん',m:'interrupción',l:'N3'}]},
  { rank:410, k:'消', level:'N3', meanings:['extinguir','borrar','desaparecer'], on:['ショウ'], kun:['き.える','け.す'],
    words:[{w:'消費',f:'しょうひ',m:'consumo',l:'N3'},{w:'消防',f:'しょうぼう',m:'bomberos',l:'N3'}]},
  { rank:411, k:'神', level:'N3', meanings:['dios','deidad','espíritu'], on:['シン','ジン'], kun:['かみ','こう','かん'],
    words:[{w:'神社',f:'じんじゃ',m:'santuario sintoísta',l:'N4'},{w:'精神',f:'せいしん',m:'espíritu / mente',l:'N3'},{w:'神秘',f:'しんぴ',m:'misterio',l:'N3'}]},
  { rank:412, k:'技', level:'N3', meanings:['técnica','habilidad','destreza'], on:['ギ'], kun:['わざ'],
    words:[{w:'技術',f:'ぎじゅつ',m:'tecnología / técnica',l:'N3'},{w:'演技',f:'えんぎ',m:'actuación / interpretación',l:'N3'},{w:'技能',f:'ぎのう',m:'habilidad técnica',l:'N3'}]},
  { rank:412, k:'角', level:'N3', meanings:['ángulo','esquina','cuerno'], on:['カク'], kun:['かど','つの'],
    words:[{w:'角度',f:'かくど',m:'ángulo / grado',l:'N3'},{w:'三角',f:'さんかく',m:'triángulo',l:'N3'},{w:'四角',f:'しかく',m:'cuadrado / rectángulo',l:'N3'}]},
  { rank:414, k:'備', level:'N3', meanings:['preparar','equipar','prever'], on:['ビ'], kun:['そな.える'],
    words:[{w:'準備',f:'じゅんび',m:'preparación',l:'N4'},{w:'設備',f:'せつび',m:'instalaciones',l:'N3'},{w:'装備',f:'そうび',m:'equipo / armamento',l:'N3'}]},
  { rank:418, k:'税', level:'N3', meanings:['impuesto','tributo'], on:['ゼイ'], kun:[],
    words:[{w:'税金',f:'ぜいきん',m:'impuesto',l:'N3'},{w:'消費税',f:'しょうひぜい',m:'impuesto al consumo',l:'N3'},{w:'税率',f:'ぜいりつ',m:'tasa impositiva',l:'N3'}]},
  { rank:419, k:'席', level:'N3', meanings:['asiento','lugar','puesto'], on:['セキ'], kun:[],
    words:[{w:'出席',f:'しゅっせき',m:'asistencia / presencia',l:'N3'},{w:'欠席',f:'けっせき',m:'ausencia',l:'N3'},{w:'座席',f:'ざせき',m:'asiento',l:'N3'}]},
  { rank:420, k:'団', level:'N3', meanings:['grupo','organización','tropa'], on:['ダン','トン'], kun:[],
    words:[{w:'団体',f:'だんたい',m:'grupo / organización',l:'N3'},{w:'集団',f:'しゅうだん',m:'grupo / colectivo',l:'N3'},{w:'布団',f:'ふとん',m:'edredón / futón',l:'N4'}]},
  { rank:421, k:'残', level:'N3', meanings:['quedar','sobrar','resto'], on:['ザン'], kun:['のこ.る'],
    words:[{w:'残念',f:'ざんねん',m:'lástima / decepción',l:'N4'},{w:'残業',f:'ざんぎょう',m:'horas extra',l:'N3'},{w:'残金',f:'ざんきん',m:'saldo restante',l:'N3'}]},
  { rank:422, k:'想', level:'N3', meanings:['idea','pensamiento','imaginar'], on:['ソウ','ソ'], kun:[],
    words:[{w:'感想',f:'かんそう',m:'impresión / opinión',l:'N4'},{w:'想像',f:'そうぞう',m:'imaginación',l:'N3'},{w:'理想',f:'りそう',m:'ideal',l:'N3'}]},
  { rank:422, k:'検', level:'N3', meanings:['examinar','inspeccionar','verificar'], on:['ケン'], kun:[],
    words:[{w:'検査',f:'けんさ',m:'inspección / examen médico',l:'N3'},{w:'検討',f:'けんとう',m:'estudio / deliberación',l:'N3'},{w:'点検',f:'てんけん',m:'inspección / revisión',l:'N3'}]},
  { rank:423, k:'温', level:'N3', meanings:['cálido','tibio','temperatura'], on:['オン'], kun:['あたた.める','あたた.かい'],
    words:[{w:'温度',f:'おんど',m:'temperatura',l:'N4'},{w:'気温',f:'きおん',m:'temperatura del aire',l:'N3'},{w:'温泉',f:'おんせん',m:'aguas termales / onsen',l:'N3'},{w:'体温',f:'たいおん',m:'temperatura corporal',l:'N3'}]},
  { rank:423, k:'助', level:'N3', meanings:['ayudar','rescatar','asistir'], on:['ジョ'], kun:['たす.ける'],
    words:[{w:'援助',f:'えんじょ',m:'ayuda / asistencia',l:'N3'},{w:'助言',f:'じょげん',m:'consejo / asesoramiento',l:'N3'},{w:'救助',f:'きゅうじょ',m:'rescate',l:'N3'}]},
  { rank:424, k:'労', level:'N3', meanings:['trabajo','esfuerzo','fatiga'], on:['ロウ'], kun:['いたわ.る','ねぎら.う'],
    words:[{w:'苦労',f:'くろう',m:'esfuerzo / sufrimiento',l:'N4'},{w:'労働',f:'ろうどう',m:'trabajo / labor',l:'N4'},{w:'過労',f:'かろう',m:'exceso de trabajo',l:'N3'}]},
  { rank:425, k:'例', level:'N3', meanings:['ejemplo','instancia'], on:['レイ'], kun:['たと.える'],
    words:[{w:'例外',f:'れいがい',m:'excepción',l:'N3'},{w:'事例',f:'じれい',m:'caso / ejemplo',l:'N3'},{w:'用例',f:'ようれい',m:'ejemplo de uso',l:'N3'}]},
  { rank:426, k:'複', level:'N3', meanings:['complejo','doble','múltiple'], on:['フク'], kun:[],
    words:[{w:'複雑',f:'ふくざつ',m:'complejo / complicado',l:'N3'},{w:'複数',f:'ふくすう',m:'plural / varios',l:'N3'}]},
  { rank:426, k:'材', level:'N3', meanings:['material','ingrediente','madera'], on:['ザイ'], kun:[],
    words:[{w:'材料',f:'ざいりょう',m:'ingredientes / materiales',l:'N4'},{w:'木材',f:'もくざい',m:'madera',l:'N3'},{w:'教材',f:'きょうざい',m:'material didáctico',l:'N3'}]},
  { rank:428, k:'追', level:'N3', meanings:['perseguir','seguir'], on:['ツイ'], kun:['お.う'],
    words:[{w:'追加',f:'ついか',m:'adición',l:'N3'},{w:'追跡',f:'ついせき',m:'seguimiento / rastreo',l:'N3'}]},
  { rank:429, k:'移', level:'N3', meanings:['trasladarse','transferir','cambiar'], on:['イ'], kun:['うつ.る','うつ.す'],
    words:[{w:'移動',f:'いどう',m:'traslado / desplazamiento',l:'N3'},{w:'転移',f:'てんい',m:'transferencia / metástasis',l:'N3'},{w:'移民',f:'いみん',m:'emigrante / inmigrante',l:'N3'}]},
  { rank:429, k:'商', level:'N3', meanings:['comercio','negocio','mercader'], on:['ショウ'], kun:['あきな.う'],
    words:[{w:'商品',f:'しょうひん',m:'mercancía',l:'N3'},{w:'商業',f:'しょうぎょう',m:'comercio',l:'N3'},{w:'商店',f:'しょうてん',m:'tienda / comercio',l:'N3'}]},
  { rank:430, k:'葉', level:'N3', meanings:['hoja','foliage'], on:['ヨウ'], kun:['は'],
    words:[{w:'言葉',f:'ことば',m:'palabra / lenguaje',l:'N5'},{w:'紅葉',f:'こうよう',m:'follaje otoñal / momiji',l:'N3'},{w:'落葉',f:'らくよう',m:'caída de hojas',l:'N3'}]},
  { rank:431, k:'伝', level:'N3', meanings:['transmitir','comunicar','propagar'], on:['デン'], kun:['つた.える'],
    words:[{w:'伝言',f:'でんごん',m:'mensaje / recado',l:'N3'},{w:'伝統',f:'でんとう',m:'tradición',l:'N3'},{w:'宣伝',f:'せんでん',m:'publicidad / propaganda',l:'N3'}]},
  { rank:432, k:'形', level:'N3', meanings:['forma','figura','apariencia'], on:['ケイ','ギョウ'], kun:['かた','かたち'],
    words:[{w:'人形',f:'にんぎょう',m:'muñeca / marioneta',l:'N4'},{w:'形式',f:'けいしき',m:'formato / formalidad',l:'N3'},{w:'形成',f:'けいせい',m:'formación / constitución',l:'N3'}]},
  { rank:433, k:'頭', level:'N3', meanings:['cabeza'], on:['トウ','ズ'], kun:['あたま','かしら'],
    words:[{w:'頭痛',f:'ずつう',m:'dolor de cabeza',l:'N4'},{w:'先頭',f:'せんとう',m:'frente / encabezado',l:'N3'},{w:'頭脳',f:'ずのう',m:'cerebro / inteligencia',l:'N3'}]},
  { rank:434, k:'落', level:'N3', meanings:['caer','bajar','perder'], on:['ラク'], kun:['お.とす','お.ちる'],
    words:[{w:'落下',f:'らっか',m:'caída',l:'N3'},{w:'落第',f:'らくだい',m:'suspender (examen)',l:'N3'}]},
  { rank:436, k:'退', level:'N3', meanings:['retirarse','retroceder'], on:['タイ'], kun:['しりぞ.く','ひ.く','の.く'],
    words:[{w:'退院',f:'たいいん',m:'alta médica',l:'N3'},{w:'引退',f:'いんたい',m:'retiro',l:'N3'},{w:'退職',f:'たいしょく',m:'jubilación / renuncia',l:'N3'}]},
  { rank:437, k:'負', level:'N3', meanings:['perder','derrota','carga'], on:['フ'], kun:['ま.ける','お.う'],
    words:[{w:'負担',f:'ふたん',m:'carga / responsabilidad',l:'N3'},{w:'勝負',f:'しょうぶ',m:'combate / competición',l:'N3'},{w:'負傷',f:'ふしょう',m:'lesión / herida',l:'N3'}]},
  { rank:439, k:'差', level:'N3', meanings:['diferencia','distinción','discriminación'], on:['サ'], kun:['さ'],
    words:[{w:'差別',f:'さべつ',m:'discriminación',l:'N3'},{w:'時差',f:'じさ',m:'diferencia horaria',l:'N3'},{w:'格差',f:'かくさ',m:'brecha / disparidad',l:'N3'}]},
  { rank:439, k:'仕', level:'N3', meanings:['servir','hacer'], on:['シ'], kun:[],
    words:[{w:'仕事',f:'しごと',m:'trabajo',l:'N5'},{w:'仕方',f:'しかた',m:'manera / forma',l:'N4'},]},
  { rank:440, k:'順', level:'N3', meanings:['orden','turno','favorable'], on:['ジュン'], kun:[],
    words:[{w:'順番',f:'じゅんばん',m:'turno / orden',l:'N3'},{w:'手順',f:'てじゅん',m:'procedimiento / pasos',l:'N3'},{w:'順調',f:'じゅんちょう',m:'sin problemas / favorable',l:'N3'}]},
  { rank:440, k:'末', level:'N3', meanings:['final','extremo','punta'], on:['マツ','バツ'], kun:['すえ'],
    words:[{w:'週末',f:'しゅうまつ',m:'fin de semana',l:'N4'},{w:'年末',f:'ねんまつ',m:'fin de año',l:'N3'},{w:'始末',f:'しまつ',m:'resultado / manejo',l:'N3'}]},
  { rank:441, k:'守', level:'N3', meanings:['guardar','proteger','cumplir'], on:['シュ','ス'], kun:['まも.る','もり'],
    words:[{w:'留守',f:'るす',m:'ausencia del hogar',l:'N4'},{w:'守備',f:'しゅび',m:'defensa',l:'N3'},{w:'保守',f:'ほしゅ',m:'conservadurismo / mantenimiento',l:'N3'}]},
  { rank:443, k:'種', level:'N3', meanings:['tipo','especie','semilla'], on:['シュ'], kun:['たね'],
    words:[{w:'種類',f:'しゅるい',m:'tipo / clase',l:'N3'},{w:'品種',f:'ひんしゅ',m:'variedad',l:'N3'},{w:'種目',f:'しゅもく',m:'categoría / evento',l:'N3'}]},
  { rank:444, k:'級', level:'N3', meanings:['grado','clase','rango'], on:['キュウ'], kun:[],
    words:[{w:'学級',f:'がっきゅう',m:'clase escolar',l:'N3'},{w:'上級',f:'じょうきゅう',m:'nivel avanzado',l:'N3'},{w:'同級生',f:'どうきゅうせい',m:'compañero de clase',l:'N3'}]},
  { rank:446, k:'福', level:'N3', meanings:['fortuna','felicidad','bendición'], on:['フク'], kun:[],
    words:[{w:'幸福',f:'こうふく',m:'felicidad',l:'N3'},{w:'福岡',f:'ふくおか',m:'Fukuoka (ciudad)',l:'N3'}]},
  { rank:447, k:'非', level:'N3', meanings:['no-','no es','incorrecto'], on:['ヒ'], kun:[],
    words:[{w:'非常口',f:'ひじょうぐち',m:'salida de emergencia',l:'N3'},{w:'非公開',f:'ひこうかい',m:'privado / no público',l:'N3'}]},
  { rank:448, k:'観', level:'N3', meanings:['observar','perspectiva','visión'], on:['カン'], kun:[],
    words:[{w:'観光',f:'かんこう',m:'turismo',l:'N4'},{w:'観客',f:'かんきゃく',m:'audiencia / espectadores',l:'N3'},{w:'観察',f:'かんさつ',m:'observación',l:'N3'}]},
  { rank:450, k:'段', level:'N3', meanings:['escalón','grado','etapa'], on:['ダン'], kun:[],
    words:[{w:'階段',f:'かいだん',m:'escaleras',l:'N4'},{w:'段階',f:'だんかい',m:'etapa / fase',l:'N3'},{w:'手段',f:'しゅだん',m:'medio / método',l:'N3'}]},
  { rank:451, k:'横', level:'N3', meanings:['horizontal','lado','lateral'], on:['オウ'], kun:['よこ'],
    words:[{w:'横断歩道',f:'おうだんほどう',m:'paso de peatones',l:'N3'},{w:'横浜',f:'よこはま',m:'Yokohama',l:'N3'},{w:'横断',f:'おうだん',m:'cruce / atravesar',l:'N3'}]},
  { rank:452, k:'深', level:'N3', meanings:['profundo','hondo'], on:['シン'], kun:['ふか.い'],
    words:[{w:'深夜',f:'しんや',m:'medianoche / madrugada',l:'N3'},{w:'深刻',f:'しんこく',m:'grave / serio',l:'N3'},{w:'深呼吸',f:'しんこきゅう',m:'respiración profunda',l:'N3'}]},
  { rank:456, k:'識', level:'N3', meanings:['saber','discernir','conocimiento'], on:['シキ'], kun:[],
    words:[{w:'知識',f:'ちしき',m:'conocimiento',l:'N4'},{w:'意識',f:'いしき',m:'conciencia',l:'N3'},{w:'常識',f:'じょうしき',m:'sentido común',l:'N3'}]},
  { rank:457, k:'呼', level:'N3', meanings:['llamar','nombrar','invitar'], on:['コ'], kun:['よ.ぶ'],
    words:[{w:'呼吸',f:'こきゅう',m:'respiración',l:'N3'},{w:'深呼吸',f:'しんこきゅう',m:'respiración profunda',l:'N3'}]},
  { rank:458, k:'良', level:'N3', meanings:['bueno','fino'], on:['リョウ'], kun:['よ','い'],
    words:[{w:'改良',f:'かいりょう',m:'mejora',l:'N3'},{w:'優良',f:'ゆうりょう',m:'excelente',l:'N3'},{w:'不良',f:'ふりょう',m:'defectuoso / malo',l:'N3'}]},
  { rank:460, k:'候', level:'N3', meanings:['condición','estado','(sufijo epistolar)'], on:['コウ'], kun:['そうろう'],
    words:[{w:'気候',f:'きこう',m:'clima',l:'N3'},{w:'候補',f:'こうほ',m:'candidato',l:'N3'},{w:'天候',f:'てんこう',m:'condición meteorológica',l:'N3'}]},
  { rank:461, k:'程', level:'N3', meanings:['grado','extensión','medida'], on:['テイ'], kun:['ほど'],
    words:[{w:'程度',f:'ていど',m:'grado / nivel',l:'N4'},{w:'過程',f:'かてい',m:'proceso',l:'N3'},{w:'日程',f:'にってい',m:'programa / itinerario',l:'N3'}]},
  { rank:462, k:'満', level:'N3', meanings:['lleno','satisfecho','completo'], on:['マン'], kun:['み.ちる'],
    words:[{w:'不満',f:'ふまん',m:'insatisfacción',l:'N4'},{w:'満足',f:'まんぞく',m:'satisfacción',l:'N3'},{w:'満員',f:'まんいん',m:'lleno / aforo completo',l:'N3'}]},
  { rank:465, k:'突', level:'N3', meanings:['empujar','sobresalir','de repente'], on:['トツ'], kun:['つ.く'],
    words:[{w:'突然',f:'とつぜん',m:'de repente',l:'N3'},{w:'衝突',f:'しょうとつ',m:'choque / colisión',l:'N3'}]},
  { rank:466, k:'路', level:'N3', meanings:['camino','ruta','vía'], on:['ロ'], kun:['じ'],
    words:[{w:'道路',f:'どうろ',m:'carretera',l:'N4'},{w:'線路',f:'せんろ',m:'vía del tren',l:'N3'},{w:'路線',f:'ろせん',m:'línea (transporte)',l:'N3'}]},
  { rank:468, k:'積', level:'N3', meanings:['acumular','amontonar','carga'], on:['セキ'], kun:['つ.む','つ.もる'],
    words:[{w:'面積',f:'めんせき',m:'área / superficie',l:'N3'},{w:'積極的',f:'せっきょくてき',m:'activo / proactivo',l:'N3'},{w:'蓄積',f:'ちくせき',m:'acumulación',l:'N3'}]},
  { rank:469, k:'他', level:'N3', meanings:['otro','diferente','además'], on:['タ'], kun:['ほか'],
    words:[{w:'他人',f:'たにん',m:'otra persona / extraño',l:'N3'},{w:'他国',f:'たこく',m:'otros países',l:'N3'}]},
  { rank:473, k:'否', level:'N3', meanings:['negar','no','rechazar'], on:['ヒ'], kun:['いな','いや'],
    words:[{w:'否定',f:'ひてい',m:'negación',l:'N3'},{w:'拒否',f:'きょひ',m:'rechazo / denegación',l:'N3'}]},
  { rank:474, k:'師', level:'N3', meanings:['maestro','experto','tropas'], on:['シ'], kun:[],
    words:[{w:'教師',f:'きょうし',m:'profesor / maestro',l:'N4'},{w:'医師',f:'いし',m:'médico',l:'N3'}]},
  { rank:475, k:'登', level:'N3', meanings:['subir','ascender'], on:['トウ','ト'], kun:['のぼ.る'],
    words:[{w:'登山',f:'とざん',m:'montañismo',l:'N4'},{w:'登録',f:'とうろく',m:'registro',l:'N3'},{w:'登場',f:'とうじょう',m:'aparición / entrada en escena',l:'N3'}]},
  { rank:476, k:'易', level:'N3', meanings:['fácil','sencillo','comercio'], on:['エキ','イ'], kun:['やさ.しい'],
    words:[{w:'容易',f:'ようい',m:'fácil / sencillo',l:'N3'},{w:'貿易',f:'ぼうえき',m:'comercio exterior',l:'N3'}]},
  { rank:477, k:'録', level:'N3', meanings:['registrar','grabar','anotar'], on:['ロク'], kun:[],
    words:[{w:'録音',f:'ろくおん',m:'grabación de sonido',l:'N3'},{w:'記録',f:'きろく',m:'registro / récord',l:'N3'},{w:'登録',f:'とうろく',m:'registro / inscripción',l:'N3'}]},
  { rank:478, k:'存', level:'N3', meanings:['existir','mantener'], on:['ソン','ゾン'], kun:[],
    words:[{w:'存在',f:'そんざい',m:'existencia',l:'N3'},{w:'保存',f:'ほぞん',m:'conservación / almacenamiento',l:'N3'}]},
  { rank:481, k:'単', level:'N3', meanings:['simple','único','soltero'], on:['タン'], kun:['ひとえ'],
    words:[{w:'簡単',f:'かんたん',m:'fácil / sencillo',l:'N5'},{w:'単語',f:'たんご',m:'vocabulario / palabra',l:'N4'},{w:'単純',f:'たんじゅん',m:'simple / sencillo',l:'N3'}]},
  { rank:482, k:'座', level:'N3', meanings:['sentar','asiento'], on:['ザ'], kun:['すわ.る'],
    words:[{w:'座席',f:'ざせき',m:'asiento',l:'N3'},{w:'銀座',f:'ぎんざ',m:'Ginza (barrio de Tokio)',l:'N3'},{w:'正座',f:'せいざ',m:'sentarse correctamente (seiza)',l:'N3'}]},
  { rank:489, k:'危', level:'N3', meanings:['peligroso','arriesgado'], on:['キ'], kun:['あぶ.ない'],
    words:[{w:'危険',f:'きけん',m:'peligro',l:'N3'},{w:'危機',f:'きき',m:'crisis',l:'N3'}]},
  { rank:490, k:'給', level:'N3', meanings:['suministrar','salario','proveer'], on:['キュウ'], kun:[],
    words:[{w:'給料',f:'きゅうりょう',m:'salario',l:'N4'},{w:'給食',f:'きゅうしょく',m:'comida escolar',l:'N3'}]},
  { rank:491, k:'苦', level:'N3', meanings:['sufrimiento','amargo','dificultad'], on:['ク'], kun:['にが.い','くる.しい'],
    words:[{w:'苦労',f:'くろう',m:'esfuerzo / sufrimiento',l:'N4'},{w:'苦手',f:'にがて',m:'punto débil / no ser bueno en',l:'N4'},{w:'苦情',f:'くじょう',m:'queja / reclamación',l:'N3'}]},
  { rank:492, k:'迎', level:'N3', meanings:['dar la bienvenida','recibir'], on:['ゲイ'], kun:['むか.える'],
    words:[{w:'歓迎',f:'かんげい',m:'bienvenida',l:'N3'},{w:'出迎え',f:'でむかえ',m:'recibir / ir a buscar',l:'N3'}]},
  { rank:494, k:'具', level:'N3', meanings:['herramienta','implemento','ingrediente'], on:['グ'], kun:[],
    words:[{w:'道具',f:'どうぐ',m:'herramienta',l:'N4'},{w:'具体的',f:'ぐたいてき',m:'concreto / específico',l:'N3'},{w:'文具',f:'ぶんぐ',m:'papelería',l:'N3'}]},
  { rank:495, k:'辞', level:'N3', meanings:['renunciar','dimitir','palabras'], on:['ジ'], kun:['や.める'],
    words:[{w:'辞書',f:'じしょ',m:'diccionario',l:'N5'},{w:'辞典',f:'じてん',m:'diccionario',l:'N4'},{w:'辞表',f:'じひょう',m:'carta de dimisión',l:'N3'}]},
  { rank:497, k:'器', level:'N3', meanings:['recipiente','instrumento','órgano'], on:['キ'], kun:['うつわ'],
    words:[{w:'楽器',f:'がっき',m:'instrumento musical',l:'N3'},{w:'食器',f:'しょっき',m:'vajilla / utensilios de cocina',l:'N3'},{w:'機器',f:'きき',m:'aparatos / equipos',l:'N3'}]},
  { rank:497, k:'注', level:'N3', meanings:['verter','anotar','prestar atención'], on:['チュウ'], kun:['そそ.ぐ','さ.す'],
    words:[{w:'注文',f:'ちゅうもん',m:'pedido',l:'N5'},{w:'注意',f:'ちゅうい',m:'atención / cuidado',l:'N4'},{w:'注射',f:'ちゅうしゃ',m:'inyección',l:'N4'},{w:'注目',f:'ちゅうもく',m:'atención / foco',l:'N4'}]},
  { rank:498, k:'算', level:'N3', meanings:['calcular','número','aritmética'], on:['サン'], kun:[],
    words:[{w:'計算',f:'けいさん',m:'cálculo',l:'N4'},{w:'算数',f:'さんすう',m:'aritmética (asignatura)',l:'N3'},{w:'予算',f:'よさん',m:'presupuesto',l:'N3'}]},
  { rank:498, k:'愛', level:'N3', meanings:['amor','afecto'], on:['アイ'], kun:['め'],
    words:[{w:'愛情',f:'あいじょう',m:'afecto / cariño',l:'N3'},{w:'恋愛',f:'れんあい',m:'amor romántico',l:'N3'},{w:'愛国',f:'あいこく',m:'patriotismo',l:'N3'}]},
  { rank:500, k:'彼', level:'N3', meanings:['él','ella','aquél'], on:['ヒ'], kun:['かれ','かの'],
    words:[{w:'彼女',f:'かのじょ',m:'ella / novia',l:'N5'},{w:'彼岸',f:'ひがん',m:'equinoccio / semana de los difuntos',l:'N3'}]},
  { rank:501, k:'未', level:'N3', meanings:['todavía no','aún no','prefijo negativo'], on:['ミ','ビ'], kun:['まだ','いまだ'],
    words:[{w:'未来',f:'みらい',m:'futuro',l:'N4'},{w:'未定',f:'みてい',m:'aún por determinar',l:'N3'},{w:'未満',f:'みまん',m:'menos de',l:'N3'}]},
  { rank:503, k:'亡', level:'N3', meanings:['fallecido','morir','perdido'], on:['ボウ','モウ'], kun:['な'],
    words:[{w:'死亡',f:'しぼう',m:'fallecimiento',l:'N3'},{w:'亡命',f:'ぼうめい',m:'exilio / huida',l:'N3'}]},
  { rank:504, k:'冷', level:'N3', meanings:['frío','enfriar','refrigerar'], on:['レイ'], kun:['つめ.たい','ひ.える','さ.める'],
    words:[{w:'冷蔵庫',f:'れいぞうこ',m:'refrigerador',l:'N4'},{w:'冷静',f:'れいせい',m:'calmado / sereno',l:'N3'},{w:'冷房',f:'れいぼう',m:'aire acondicionado',l:'N3'}]},
  { rank:506, k:'婦', level:'N3', meanings:['mujer casada','señora'], on:['フ'], kun:['よめ'],
    words:[{w:'主婦',f:'しゅふ',m:'ama de casa',l:'N4'},{w:'夫婦',f:'ふうふ',m:'matrimonio / pareja',l:'N3'},{w:'婦人',f:'ふじん',m:'señora',l:'N3'}]},
  { rank:509, k:'類', level:'N3', meanings:['tipo','clase','género'], on:['ルイ'], kun:['たぐ.い'],
    words:[{w:'種類',f:'しゅるい',m:'tipo / clase',l:'N3'},{w:'分類',f:'ぶんるい',m:'clasificación',l:'N3'},{w:'人類',f:'じんるい',m:'humanidad',l:'N3'}]},
  { rank:510, k:'億', level:'N3', meanings:['cien millones'], on:['オク'], kun:[],
    words:[{w:'億円',f:'おくえん',m:'cien millones de yenes',l:'N3'},{w:'一億',f:'いちおく',m:'cien millones',l:'N3'}]},
  { rank:512, k:'卒', level:'N3', meanings:['graduarse','acabar'], on:['ソツ'], kun:[],
    words:[{w:'卒業',f:'そつぎょう',m:'graduación',l:'N3'},{w:'卒業式',f:'そつぎょうしき',m:'ceremonia de graduación',l:'N3'}]},
  { rank:515, k:'熱', level:'N3', meanings:['calor','fiebre','ardor'], on:['ネツ'], kun:['あつ.い'],
    words:[{w:'熱心',f:'ねっしん',m:'entusiasta / diligente',l:'N4'},{w:'情熱',f:'じょうねつ',m:'pasión',l:'N3'},{w:'発熱',f:'はつねつ',m:'fiebre / generar calor',l:'N3'}]},
  { rank:517, k:'険', level:'N3', meanings:['peligroso','escarpado'], on:['ケン'], kun:['けわ.しい'],
    words:[{w:'保険',f:'ほけん',m:'seguro',l:'N4'},{w:'危険',f:'きけん',m:'peligro',l:'N3'},{w:'冒険',f:'ぼうけん',m:'aventura',l:'N3'}]},
  { rank:517, k:'接', level:'N3', meanings:['contactar','conectar','recibir'], on:['セツ'], kun:['つ.ぐ'],
    words:[{w:'接続',f:'せつぞく',m:'conexión',l:'N3'},{w:'直接',f:'ちょくせつ',m:'directo / directamente',l:'N4'},{w:'面接',f:'めんせつ',m:'entrevista de trabajo',l:'N3'}]},
  { rank:519, k:'覚', level:'N3', meanings:['memorizar','recordar','despertar'], on:['カク'], kun:['おぼ.える','さ.める'],
    words:[{w:'感覚',f:'かんかく',m:'sensación',l:'N3'},{w:'自覚',f:'じかく',m:'conciencia propia',l:'N3'},{w:'視覚',f:'しかく',m:'sentido de la vista',l:'N3'}]},
  { rank:522, k:'復', level:'N3', meanings:['recuperar','restaurar','regresar'], on:['フク'], kun:[],
    words:[{w:'回復',f:'かいふく',m:'recuperación',l:'N3'},{w:'復習',f:'ふくしゅう',m:'repasar / repaso',l:'N3'},{w:'復興',f:'ふっこう',m:'reconstrucción / recuperación',l:'N3'}]},
  { rank:522, k:'賞', level:'N3', meanings:['premio','galardón','elogio'], on:['ショウ'], kun:[],
    words:[{w:'受賞',f:'じゅしょう',m:'recibir un premio',l:'N3'},{w:'賞品',f:'しょうひん',m:'premio / trofeo',l:'N3'}]},
  { rank:524, k:'造', level:'N3', meanings:['crear','fabricar','construir'], on:['ゾウ','ソウ'], kun:['つく.る'],
    words:[{w:'製造',f:'せいぞう',m:'fabricación / manufactura',l:'N3'},{w:'構造',f:'こうぞう',m:'estructura',l:'N3'},{w:'改造',f:'かいぞう',m:'modificación / remodelación',l:'N3'}]},
  { rank:525, k:'留', level:'N3', meanings:['detenerse','retener','estudiar en el extranjero'], on:['リュウ','ル'], kun:['と.まる','とど.める'],
    words:[{w:'留学',f:'りゅうがく',m:'estudiar en el extranjero',l:'N4'},{w:'留守',f:'るす',m:'ausencia del hogar',l:'N4'}]},
  { rank:527, k:'努', level:'N3', meanings:['esforzarse','hacer el máximo'], on:['ド'], kun:['つと.める'],
    words:[{w:'努力',f:'どりょく',m:'esfuerzo',l:'N4'}]},
  { rank:530, k:'悪', level:'N3', meanings:['malo','malvado'], on:['アク','オ'], kun:['わる.い'],
    words:[{w:'最悪',f:'さいあく',m:'pésimo',l:'N4'},{w:'悪口',f:'わるくち',m:'hablar mal de alguien',l:'N4'},{w:'悪化',f:'あっか',m:'empeoramiento',l:'N3'}]},
  { rank:531, k:'介', level:'N3', meanings:['intermediar','interponerse','asistir'], on:['カイ'], kun:[],
    words:[{w:'紹介',f:'しょうかい',m:'presentación / introducción',l:'N3'},{w:'介護',f:'かいご',m:'cuidado de ancianos / asistencia',l:'N3'}]},
  { rank:531, k:'婚', level:'N3', meanings:['matrimonio','casarse'], on:['コン'], kun:[],
    words:[{w:'結婚',f:'けっこん',m:'matrimonio / boda',l:'N4'},{w:'離婚',f:'りこん',m:'divorcio',l:'N3'},{w:'婚約',f:'こんやく',m:'compromiso / noviazgo',l:'N3'}]},
  { rank:532, k:'喜', level:'N3', meanings:['regocijarse','alegría'], on:['キ'], kun:['よろこ.ぶ'],
    words:[{w:'歓喜',f:'かんき',m:'gran alegría',l:'N3'},{w:'喜劇',f:'きげき',m:'comedia',l:'N3'}]},
  { rank:534, k:'倍', level:'N3', meanings:['doble','veces','múltiplo'], on:['バイ'], kun:[],
    words:[{w:'何倍',f:'なんばい',m:'¿cuántas veces?',l:'N3'},{w:'倍増',f:'ばいぞう',m:'duplicarse / doblar',l:'N3'}]},
  { rank:534, k:'測', level:'N3', meanings:['medir','calcular','pronosticar'], on:['ソク'], kun:['はか.る'],
    words:[{w:'測定',f:'そくてい',m:'medición',l:'N3'},{w:'観測',f:'かんそく',m:'observación / medición',l:'N3'},{w:'推測',f:'すいそく',m:'suposición / estimación',l:'N3'}]},
  { rank:534, k:'旧', level:'N3', meanings:['antiguo','anterior','ex-'], on:['キュウ'], kun:['ふる.い'],
    words:[{w:'旧式',f:'きゅうしき',m:'anticuado / de modelo antiguo',l:'N3'},{w:'旧友',f:'きゅうゆう',m:'viejo amigo',l:'N3'}]},
  { rank:534, k:'副', level:'N3', meanings:['vice-','auxiliar','secundario'], on:['フク'], kun:[],
    words:[{w:'副作用',f:'ふくさよう',m:'efecto secundario',l:'N3'},{w:'副業',f:'ふくぎょう',m:'trabajo secundario',l:'N3'}]},
  { rank:535, k:'幸', level:'N3', meanings:['felicidad','fortuna','suerte'], on:['コウ'], kun:['しあわ.せ','さち','さいわ.い'],
    words:[{w:'幸福',f:'こうふく',m:'felicidad',l:'N3'},{w:'幸運',f:'こううん',m:'suerte / buena fortuna',l:'N3'}]},
  { rank:536, k:'押', level:'N3', meanings:['empujar','presionar'], on:['オウ'], kun:['お.す'],
    words:[{w:'押し入れ',f:'おしいれ',m:'armario empotrado',l:'N3'}]},
  { rank:537, k:'倒', level:'N3', meanings:['caer','tumbar','derrotar'], on:['トウ'], kun:['たお.れる','たお.す'],
    words:[{w:'圧倒',f:'あっとう',m:'abrumar / aplastar',l:'N3'},{w:'倒産',f:'とうさん',m:'bancarrota',l:'N3'}]},
  { rank:537, k:'独', level:'N3', meanings:['solo','independiente','Alemania'], on:['ドク'], kun:['ひと.り'],
    words:[{w:'独立',f:'どくりつ',m:'independencia',l:'N3'},{w:'独身',f:'どくしん',m:'soltero',l:'N3'},{w:'独自',f:'どくじ',m:'propio / original',l:'N3'}]},
  { rank:539, k:'老', level:'N3', meanings:['envejecer','anciano'], on:['ロウ'], kun:['お.いる','ふ.ける'],
    words:[{w:'老人',f:'ろうじん',m:'anciano',l:'N3'},{w:'老化',f:'ろうか',m:'envejecimiento',l:'N3'},{w:'老後',f:'ろうご',m:'vejez',l:'N3'}]},
  { rank:540, k:'曲', level:'N3', meanings:['curvar','melodía','canción'], on:['キョク'], kun:['ま.がる','ま.げる'],
    words:[{w:'作曲',f:'さっきょく',m:'composición musical',l:'N3'},{w:'名曲',f:'めいきょく',m:'obra musical famosa',l:'N3'},{w:'楽曲',f:'がっきょく',m:'pieza musical',l:'N3'}]},
  { rank:541, k:'島', level:'N3', meanings:['isla'], on:['トウ'], kun:['しま'],
    words:[{w:'半島',f:'はんとう',m:'península',l:'N3'},{w:'孤島',f:'ことう',m:'isla solitaria',l:'N3'},{w:'群島',f:'ぐんとう',m:'archipiélago',l:'N3'}]},
  { rank:543, k:'徒', level:'N3', meanings:['seguidor','a pie','en vano'], on:['ト'], kun:[],
    words:[{w:'生徒',f:'せいと',m:'alumno',l:'N4'},{w:'徒歩',f:'とほ',m:'a pie',l:'N3'}]},
  { rank:545, k:'担', level:'N3', meanings:['cargar','responsabilizarse','encargarse'], on:['タン','ダン'], kun:['かつ.ぐ','にな.う'],
    words:[{w:'担当',f:'たんとう',m:'encargado / responsable',l:'N3'},{w:'担任',f:'たんにん',m:'tutor de clase',l:'N3'},{w:'負担',f:'ふたん',m:'carga / responsabilidad',l:'N3'}]},
  { rank:545, k:'補', level:'N3', meanings:['suplir','complementar','asistir'], on:['ホ'], kun:['おぎな.う'],
    words:[{w:'補充',f:'ほじゅう',m:'reposición',l:'N3'},{w:'補助',f:'ほじょ',m:'asistencia / subsidio',l:'N3'},{w:'候補',f:'こうほ',m:'candidato',l:'N3'}]},
  { rank:545, k:'帯', level:'N3', meanings:['cinturón','zona','llevar puesto'], on:['タイ'], kun:['おび','お.びる'],
    words:[{w:'携帯',f:'けいたい',m:'teléfono móvil',l:'N3'},{w:'地帯',f:'ちたい',m:'zona / región',l:'N3'},{w:'包帯',f:'ほうたい',m:'vendaje',l:'N3'}]},
  { rank:548, k:'欠', level:'N3', meanings:['faltar','defecto','ausente'], on:['ケツ'], kun:['か.ける'],
    words:[{w:'欠席',f:'けっせき',m:'ausencia',l:'N3'},{w:'欠点',f:'けってん',m:'defecto',l:'N3'}]},
  { rank:551, k:'賛', level:'N3', meanings:['aprobar','estar de acuerdo'], on:['サン'], kun:[],
    words:[{w:'賛成',f:'さんせい',m:'acuerdo / aprobación',l:'N3'},{w:'賛同',f:'さんどう',m:'aprobación / apoyo',l:'N3'}]},
  { rank:555, k:'息', level:'N3', meanings:['respiración','hijo','interés'], on:['ソク'], kun:['いき'],
    words:[{w:'息子',f:'むすこ',m:'hijo',l:'N5'},{w:'休息',f:'きゅうそく',m:'descanso',l:'N3'},{w:'溜息',f:'ためいき',m:'suspiro',l:'N3'}]},
  { rank:556, k:'階', level:'N3', meanings:['piso','planta','rango'], on:['カイ'], kun:[],
    words:[{w:'階段',f:'かいだん',m:'escaleras',l:'N4'},{w:'一階',f:'いっかい',m:'planta baja / primer piso',l:'N3'},{w:'段階',f:'だんかい',m:'etapa / fase',l:'N3'}]},
  { rank:557, k:'願', level:'N3', meanings:['deseo','petición','súplica'], on:['ガン'], kun:['ねが.う'],
    words:[{w:'願書',f:'がんしょ',m:'solicitud escrita',l:'N3'},{w:'念願',f:'ねんがん',m:'deseo ferviente',l:'N3'}]},
  { rank:559, k:'欲', level:'N3', meanings:['deseo','codicia','anhelar'], on:['ヨク'], kun:['ほ.しい'],
    words:[{w:'食欲',f:'しょくよく',m:'apetito',l:'N4'},{w:'欲望',f:'よくぼう',m:'deseo / codicia',l:'N3'},{w:'物欲',f:'ぶつよく',m:'codicia material / apego a los bienes',l:'N3'}]},
  { rank:560, k:'痛', level:'N3', meanings:['dolor','doler','agudo'], on:['ツウ'], kun:['いた.い','いた.む'],
    words:[{w:'頭痛',f:'ずつう',m:'dolor de cabeza',l:'N4'},{w:'腹痛',f:'ふくつう',m:'dolor de estómago',l:'N3'},{w:'苦痛',f:'くつう',m:'dolor / sufrimiento',l:'N3'}]},
  { rank:561, k:'笑', level:'N3', meanings:['reír','sonreír'], on:['ショウ'], kun:['わら.う','え.む'],
    words:[{w:'笑顔',f:'えがお',m:'sonrisa',l:'N4'},{w:'微笑',f:'びしょう',m:'sonrisa suave',l:'N3'},{w:'苦笑',f:'くしょう',m:'sonrisa amarga',l:'N3'}]},
  { rank:563, k:'束', level:'N3', meanings:['ramo','atado','manojo'], on:['ソク'], kun:['たば','つか'],
    words:[{w:'花束',f:'はなたば',m:'ramo de flores',l:'N4'},{w:'約束',f:'やくそく',m:'promesa',l:'N4'}]},
  { rank:565, k:'列', level:'N3', meanings:['fila','hilera','columna'], on:['レツ'], kun:[],
    words:[{w:'列車',f:'れっしゃ',m:'tren',l:'N4'},{w:'行列',f:'ぎょうれつ',m:'fila / cola',l:'N3'}]},
  { rank:566, k:'探', level:'N3', meanings:['buscar','explorar','investigar'], on:['タン'], kun:['さぐ.る','さが.す'],
    words:[{w:'探偵',f:'たんてい',m:'detective',l:'N3'},{w:'探検',f:'たんけん',m:'exploración',l:'N3'}]},
  { rank:570, k:'夢', level:'N3', meanings:['sueño','ensoñación'], on:['ム'], kun:['ゆめ'],
    words:[{w:'夢中',f:'むちゅう',m:'absorto / obsesionado',l:'N3'},{w:'悪夢',f:'あくむ',m:'pesadilla',l:'N3'},{w:'初夢',f:'はつゆめ',m:'primer sueño del año nuevo',l:'N3'}]},
  { rank:571, k:'君', level:'N3', meanings:['tú','señor','sufijo masculino'], on:['クン'], kun:['きみ'],
    words:[{w:'君主',f:'くんしゅ',m:'soberano / monarca',l:'N3'}]},
  { rank:574, k:'折', level:'N3', meanings:['doblar','romper','oportunidad'], on:['セツ'], kun:['お.る','おり'],
    words:[{w:'折り紙',f:'おりがみ',m:'origami',l:'N4'},{w:'時折',f:'ときおり',m:'de vez en cuando',l:'N3'},{w:'骨折',f:'こっせつ',m:'fractura ósea',l:'N3'}]},
  { rank:578, k:'悲', level:'N3', meanings:['triste','llorar','lamentar'], on:['ヒ'], kun:['かな.しい'],
    words:[{w:'悲劇',f:'ひげき',m:'tragedia',l:'N3'},{w:'悲鳴',f:'ひめい',m:'grito',l:'N3'},{w:'悲観',f:'ひかん',m:'pesimismo',l:'N3'}]},
  { rank:580, k:'飛', level:'N3', meanings:['volar'], on:['ヒ'], kun:['と.ぶ'],
    words:[{w:'飛行',f:'ひこう',m:'vuelo',l:'N4'},{w:'飛行機',f:'ひこうき',m:'avión',l:'N5'},{w:'飛躍',f:'ひやく',m:'salto / avance espectacular',l:'N3'}]},
  { rank:583, k:'吸', level:'N3', meanings:['inhalar','absorber','chupar'], on:['キュウ'], kun:['す.う'],
    words:[{w:'呼吸',f:'こきゅう',m:'respiración',l:'N3'},{w:'吸収',f:'きゅうしゅう',m:'absorción',l:'N3'}]},
  { rank:584, k:'陽', level:'N3', meanings:['sol','positivo','cálido'], on:['ヨウ'], kun:['ひ'],
    words:[{w:'太陽',f:'たいよう',m:'sol',l:'N4'},{w:'陽気',f:'ようき',m:'alegre / animado',l:'N3'}]},
  { rank:585, k:'州', level:'N3', meanings:['provincia','estado','continente'], on:['シュウ'], kun:['す'],
    words:[{w:'欧州',f:'おうしゅう',m:'Europa',l:'N3'},{w:'本州',f:'ほんしゅう',m:'Honshu (isla principal de Japón)',l:'N3'}]},
  { rank:586, k:'歯', level:'N3', meanings:['diente'], on:['シ'], kun:['は'],
    words:[{w:'歯医者',f:'はいしゃ',m:'dentista',l:'N4'},{w:'虫歯',f:'むしば',m:'caries',l:'N3'},{w:'歯科',f:'しか',m:'odontología / dentística',l:'N3'}]},
  { rank:587, k:'忘', level:'N3', meanings:['olvidar'], on:['ボウ'], kun:['わす.れる'],
    words:[{w:'忘れ物',f:'わすれもの',m:'objeto olvidado',l:'N4'},{w:'忘年会',f:'ぼうねんかい',m:'fiesta de fin de año',l:'N3'}]},
  { rank:589, k:'娘', level:'N3', meanings:['hija','chica'], on:[], kun:['むすめ'],
    words:[{w:'一人娘',f:'ひとりむすめ',m:'hija única',l:'N3'}]},
  { rank:591, k:'芸', level:'N3', meanings:['arte','espectáculo','habilidad artística'], on:['ゲイ'], kun:[],
    words:[{w:'芸術',f:'げいじゅつ',m:'arte',l:'N3'},{w:'芸能',f:'げいのう',m:'espectáculos / entretenimiento',l:'N3'},{w:'芸人',f:'げいにん',m:'artista / cómico',l:'N3'}]},
  { rank:591, k:'洗', level:'N3', meanings:['lavar','limpiar'], on:['セン'], kun:['あら.う'],
    words:[{w:'洗濯',f:'せんたく',m:'lavandería / lavado de ropa',l:'N4'},{w:'洗剤',f:'せんざい',m:'detergente',l:'N3'},{w:'洗面所',f:'せんめんじょ',m:'lavabo / baño',l:'N3'}]},
  { rank:592, k:'績', level:'N3', meanings:['logro','mérito','resultado'], on:['セキ'], kun:[],
    words:[{w:'成績',f:'せいせき',m:'notas / resultados académicos',l:'N3'},{w:'業績',f:'ぎょうせき',m:'rendimiento / logro empresarial',l:'N3'},{w:'実績',f:'じっせき',m:'resultados reales / historial',l:'N3'}]},
  { rank:593, k:'礼', level:'N3', meanings:['etiqueta','gratitud','reverencia'], on:['レイ','ライ'], kun:[],
    words:[{w:'失礼',f:'しつれい',m:'descortesía',l:'N4'},{w:'礼儀',f:'れいぎ',m:'etiqueta / modales',l:'N3'}]},
  { rank:594, k:'窓', level:'N3', meanings:['ventana'], on:['ソウ'], kun:['まど'],
    words:[{w:'窓口',f:'まどぐち',m:'ventanilla / taquilla',l:'N4'},{w:'同窓会',f:'どうそうかい',m:'reunión de exalumnos',l:'N3'}]},
  { rank:595, k:'昔', level:'N3', meanings:['antaño','hace mucho','pasado'], on:['セキ','シャク'], kun:['むかし'],
    words:[{w:'昔話',f:'むかしばなし',m:'cuento antiguo',l:'N3'},{w:'大昔',f:'おおむかし',m:'tiempos remotos',l:'N3'}]},
  { rank:596, k:'授', level:'N3', meanings:['otorgar','enseñar','conferir'], on:['ジュ'], kun:['さず.ける'],
    words:[{w:'授業',f:'じゅぎょう',m:'clase / lección',l:'N5'},{w:'教授',f:'きょうじゅ',m:'profesor universitario',l:'N3'},{w:'授与',f:'じゅよ',m:'conferir / otorgar',l:'N3'}]},
  { rank:597, k:'怒', level:'N3', meanings:['enojarse','airado'], on:['ド'], kun:['おこ.る','いか.る'],
    words:[{w:'激怒',f:'げきど',m:'furia / cólera',l:'N3'}]},
  { rank:599, k:'杯', level:'N3', meanings:['copa','vaso','contadora de tazas'], on:['ハイ'], kun:['さかずき'],
    words:[{w:'一杯',f:'いっぱい',m:'una taza / lleno',l:'N5'},{w:'乾杯',f:'かんぱい',m:'brindis / ¡salud!',l:'N4'}]},
  { rank:608, k:'箱', level:'N3', meanings:['caja','estuche'], on:['ソウ'], kun:['はこ'],
    words:[{w:'郵便箱',f:'ゆうびんばこ',m:'buzón',l:'N3'},{w:'宝箱',f:'たからばこ',m:'cofre del tesoro',l:'N3'}]},
  { rank:621, k:'可', level:'N3', meanings:['posible','permitido'], on:['カ'], kun:[],
    words:[{w:'可能',f:'かのう',m:'posible',l:'N3'},{w:'不可能',f:'ふかのう',m:'imposible',l:'N3'},{w:'許可',f:'きょか',m:'permiso',l:'N3'}]},
  { rank:622, k:'念', level:'N3', meanings:['pensamiento','preocupación','deseo'], on:['ネン'], kun:[],
    words:[{w:'残念',f:'ざんねん',m:'lástima / qué pena',l:'N4'},{w:'記念',f:'きねん',m:'conmemoración',l:'N3'}]},
  { rank:626, k:'央', level:'N3', meanings:['centro','mitad'], on:['オウ'], kun:[],
    words:[{w:'中央',f:'ちゅうおう',m:'centro / central',l:'N3'}]},
  { rank:636, k:'祭', level:'N3', meanings:['festival','ceremonia','celebrar'], on:['サイ'], kun:['まつ.り','まつ.る'],
    words:[{w:'文化祭',f:'ぶんかさい',m:'festival cultural escolar',l:'N3'},{w:'祭日',f:'さいじつ',m:'día festivo',l:'N3'},{w:'祭典',f:'さいてん',m:'ceremonia / festival',l:'N3'}]},
  { rank:636, k:'戸', level:'N3', meanings:['puerta','hogar','unidad familiar'], on:['コ'], kun:['と'],
    words:[{w:'戸口',f:'とぐち',m:'entrada / umbral',l:'N3'},{w:'江戸',f:'えど',m:'Edo (antiguo nombre de Tokio)',l:'N3'},{w:'雨戸',f:'あまど',m:'contraventana',l:'N3'}]},
  { rank:638, k:'逆', level:'N3', meanings:['inverso','al revés','contrario'], on:['ギャク'], kun:['さか.らう','さか'],
    words:[{w:'逆効果',f:'ぎゃくこうか',m:'efecto contrario',l:'N3'},{w:'逆転',f:'ぎゃくてん',m:'reversión / darle la vuelta',l:'N3'}]},
  { rank:639, k:'訳', level:'N3', meanings:['traducir','razón','motivo'], on:['ヤク'], kun:['わけ'],
    words:[{w:'翻訳',f:'ほんやく',m:'traducción',l:'N3'},{w:'言い訳',f:'いいわけ',m:'excusa / pretexto',l:'N3'},{w:'通訳',f:'つうやく',m:'interpretación / intérprete',l:'N3'}]},
  { rank:640, k:'貿', level:'N3', meanings:['comercio','intercambio comercial'], on:['ボウ'], kun:[],
    words:[{w:'貿易',f:'ぼうえき',m:'comercio exterior',l:'N3'}]},
  { rank:647, k:'児', level:'N3', meanings:['niño','infante'], on:['ジ','ニ'], kun:['こ'],
    words:[{w:'児童',f:'じどう',m:'niño / alumno de primaria',l:'N3'},{w:'小児科',f:'しょうにか',m:'pediatría',l:'N3'},{w:'育児',f:'いくじ',m:'cría de niños / crianza',l:'N3'}]},
  { rank:657, k:'根', level:'N3', meanings:['raíz','base','fundamento'], on:['コン'], kun:['ね'],
    words:[{w:'根本',f:'こんぽん',m:'fundamento / raíz',l:'N3'},{w:'大根',f:'だいこん',m:'rábano blanco',l:'N4'},{w:'屋根',f:'やね',m:'techo',l:'N3'}]},
  { rank:668, k:'仏', level:'N3', meanings:['Buda','Francia','budismo'], on:['ブツ','フツ'], kun:['ほとけ'],
    words:[{w:'仏教',f:'ぶっきょう',m:'budismo',l:'N3'},{w:'仏様',f:'ほとけさま',m:'Buda (respetuoso)',l:'N3'}]},
  { rank:672, k:'血', level:'N3', meanings:['sangre'], on:['ケツ'], kun:['ち'],
    words:[{w:'血液',f:'けつえき',m:'sangre',l:'N3'},{w:'献血',f:'けんけつ',m:'donación de sangre',l:'N3'},{w:'血圧',f:'けつあつ',m:'presión arterial',l:'N3'}]},
  { rank:672, k:'板', level:'N3', meanings:['tabla','tablón','plancha'], on:['ハン','バン'], kun:['いた'],
    words:[{w:'黒板',f:'こくばん',m:'pizarra',l:'N5'},{w:'看板',f:'かんばん',m:'letrero',l:'N3'},{w:'鉄板',f:'てっぱん',m:'plancha de hierro',l:'N3'}]},
  { rank:673, k:'植', level:'N3', meanings:['plantar','cultivar','establecer'], on:['ショク'], kun:['う.える'],
    words:[{w:'植物',f:'しょくぶつ',m:'planta / vegetal',l:'N4'},{w:'植民地',f:'しょくみんち',m:'colonia',l:'N3'},{w:'移植',f:'いしょく',m:'trasplante',l:'N3'}]},
  { rank:673, k:'焼', level:'N3', meanings:['asar','hornear','quemar'], on:['ショウ'], kun:['や.く','や.ける'],
    words:[{w:'焼き鳥',f:'やきとり',m:'yakitori (pollo a la parrilla)',l:'N3'},{w:'日焼け',f:'ひやけ',m:'bronceado / quemadura solar',l:'N3'},{w:'焼肉',f:'やきにく',m:'carne asada',l:'N3'}]},
  { rank:674, k:'均', level:'N3', meanings:['uniforme','promedio','nivelado'], on:['キン'], kun:[],
    words:[{w:'平均',f:'へいきん',m:'promedio / media',l:'N3'},{w:'均等',f:'きんとう',m:'igual / equitativo',l:'N3'}]},
  { rank:676, k:'顔', level:'N3', meanings:['cara','rostro'], on:['ガン'], kun:['かお'],
    words:[{w:'笑顔',f:'えがお',m:'sonrisa',l:'N4'},{w:'顔色',f:'かおいろ',m:'color de la cara / expresión',l:'N4'}]},
  { rank:678, k:'河', level:'N3', meanings:['río','corriente'], on:['カ','ガ'], kun:['かわ'],
    words:[{w:'河川',f:'かせん',m:'ríos y arroyos',l:'N3'},{w:'銀河',f:'ぎんが',m:'galaxia / Vía Láctea',l:'N3'},{w:'運河',f:'うんが',m:'canal',l:'N3'}]},
  { rank:681, k:'庫', level:'N3', meanings:['almacén','depósito','bodega'], on:['コ','ク'], kun:[],
    words:[{w:'車庫',f:'しゃこ',m:'garaje / cochera',l:'N3'},{w:'冷蔵庫',f:'れいぞうこ',m:'refrigerador',l:'N4'},{w:'文庫',f:'ぶんこ',m:'libro de bolsillo',l:'N3'}]},
  { rank:687, k:'陸', level:'N3', meanings:['tierra','continente','costa'], on:['リク'], kun:['おか'],
    words:[{w:'陸地',f:'りくち',m:'tierra firme',l:'N3'},{w:'大陸',f:'たいりく',m:'continente',l:'N3'},{w:'着陸',f:'ちゃくりく',m:'aterrizaje',l:'N3'}]},
  { rank:694, k:'季', level:'N3', meanings:['estación del año','temporada'], on:['キ'], kun:[],
    words:[{w:'季節',f:'きせつ',m:'estación del año',l:'N4'},{w:'四季',f:'しき',m:'las cuatro estaciones',l:'N3'}]},
  { rank:697, k:'希', level:'N3', meanings:['esperanza','raro','escaso'], on:['キ'], kun:[],
    words:[{w:'希望',f:'きぼう',m:'esperanza / deseo',l:'N4'},{w:'希少',f:'きしょう',m:'escaso / raro',l:'N3'}]},
  { rank:697, k:'救', level:'N3', meanings:['rescatar','salvar','auxiliar'], on:['キュウ'], kun:['すく.う'],
    words:[{w:'救急',f:'きゅうきゅう',m:'emergencia / urgencia médica',l:'N3'},{w:'救助',f:'きゅうじょ',m:'rescate',l:'N3'},{w:'救済',f:'きゅうさい',m:'socorro / alivio',l:'N3'}]},
  { rank:701, k:'底', level:'N3', meanings:['fondo','base','inferior'], on:['テイ'], kun:['そこ'],
    words:[{w:'徹底',f:'てってい',m:'completo / exhaustivo',l:'N3'},{w:'海底',f:'かいてい',m:'fondo del mar',l:'N3'}]},
  { rank:712, k:'液', level:'N3', meanings:['líquido','fluido'], on:['エキ'], kun:[],
    words:[{w:'液体',f:'えきたい',m:'líquido',l:'N3'},{w:'血液',f:'けつえき',m:'sangre',l:'N3'},{w:'液晶',f:'えきしょう',m:'pantalla LCD / cristal líquido',l:'N3'}]},
  { rank:719, k:'永', level:'N3', meanings:['eterno','permanente','duradero'], on:['エイ'], kun:['なが.い'],
    words:[{w:'永遠',f:'えいえん',m:'eternidad / para siempre',l:'N3'},{w:'永久',f:'えいきゅう',m:'permanente / perpetuo',l:'N3'}]},
  { rank:726, k:'翌', level:'N3', meanings:['el día siguiente','el próximo'], on:['ヨク'], kun:[],
    words:[{w:'翌日',f:'よくじつ',m:'el día siguiente',l:'N3'},{w:'翌朝',f:'よくあさ',m:'la mañana siguiente',l:'N3'},{w:'翌年',f:'よくねん',m:'el año siguiente',l:'N3'}]},
  { rank:728, k:'築', level:'N3', meanings:['construir','edificar','establecer'], on:['チク'], kun:['きず.く'],
    words:[{w:'建築',f:'けんちく',m:'arquitectura / construcción',l:'N3'},{w:'築城',f:'ちくじょう',m:'construcción de castillo / fortaleza',l:'N3'}]},
  { rank:741, k:'枚', level:'N3', meanings:['(contador de cosas planas)'], on:['マイ'], kun:[],
    words:[{w:'一枚',f:'いちまい',m:'una hoja / una lámina',l:'N4'},{w:'何枚',f:'なんまい',m:'¿cuántas hojas?',l:'N4'}]},
  { rank:741, k:'仲', level:'N3', meanings:['relación','entre','intermediario'], on:['チュウ'], kun:['なか'],
    words:[{w:'仲間',f:'なかま',m:'compañero / colega',l:'N3'},{w:'仲良し',f:'なかよし',m:'amigo / buena relación',l:'N3'},{w:'仲直り',f:'なかなおり',m:'reconciliación',l:'N3'}]},
  { rank:742, k:'械', level:'N3', meanings:['máquina','mecanismo'], on:['カイ'], kun:[],
    words:[{w:'機械',f:'きかい',m:'máquina / maquinaria',l:'N3'},{w:'機械的',f:'きかいてき',m:'mecánico / automático',l:'N3'}]},
  { rank:749, k:'欧', level:'N3', meanings:['Europa'], on:['オウ'], kun:[],
    words:[{w:'欧州',f:'おうしゅう',m:'Europa',l:'N3'},{w:'欧米',f:'おうべい',m:'Europa y América',l:'N3'}]},
  { rank:757, k:'橋', level:'N3', meanings:['puente'], on:['キョウ'], kun:['はし'],
    words:[{w:'橋渡し',f:'はしわたし',m:'mediación / tender un puente',l:'N3'},{w:'鉄橋',f:'てっきょう',m:'puente de hierro',l:'N3'},{w:'歩道橋',f:'ほどうきょう',m:'paso elevado peatonal',l:'N3'}]},
  { rank:757, k:'湯', level:'N3', meanings:['agua caliente','baño caliente','infusión'], on:['トウ'], kun:['ゆ'],
    words:[{w:'銭湯',f:'せんとう',m:'baño público',l:'N3'},{w:'熱湯',f:'ねっとう',m:'agua hirviendo',l:'N3'},{w:'湯気',f:'ゆげ',m:'vapor',l:'N3'}]},
  { rank:758, k:'祝', level:'N3', meanings:['celebrar','felicitar','bendecir'], on:['シュク','シュウ'], kun:['いわ.う'],
    words:[{w:'祝日',f:'しゅくじつ',m:'día festivo / fiesta nacional',l:'N3'},{w:'祝福',f:'しゅくふく',m:'bendición',l:'N3'}]},
  { rank:762, k:'兆', level:'N3', meanings:['billón','presagio','señal'], on:['チョウ'], kun:['きざ.す'],
    words:[{w:'兆候',f:'ちょうこう',m:'señal / presagio / síntoma',l:'N3'},{w:'前兆',f:'ぜんちょう',m:'presagio',l:'N3'},{w:'一兆',f:'いっちょう',m:'un billón',l:'N3'}]},
  { rank:763, k:'紹', level:'N3', meanings:['presentar','introducir'], on:['ショウ'], kun:[],
    words:[{w:'紹介',f:'しょうかい',m:'presentación / introducción',l:'N3'}]},
  { rank:771, k:'筆', level:'N3', meanings:['pincel','pluma','escritura'], on:['ヒツ'], kun:['ふで'],
    words:[{w:'鉛筆',f:'えんぴつ',m:'lápiz',l:'N5'},{w:'筆記',f:'ひっき',m:'escritura / tomar notas',l:'N3'},{w:'毛筆',f:'もうひつ',m:'pincel japonés',l:'N3'}]},
  { rank:784, k:'久', level:'N3', meanings:['mucho tiempo','duradero'], on:['キュウ','ク'], kun:['ひさ.しい'],
    words:[{w:'永久',f:'えいきゅう',m:'permanente / perpetuo',l:'N3'}]},
  { rank:793, k:'巨', level:'N3', meanings:['gigante','enorme'], on:['キョ'], kun:[],
    words:[{w:'巨大',f:'きょだい',m:'gigante / enorme',l:'N3'},{w:'巨人',f:'きょじん',m:'gigante / persona enorme',l:'N3'}]},
  { rank:793, k:'秒', level:'N3', meanings:['segundo (unidad de tiempo)'], on:['ビョウ'], kun:[],
    words:[{w:'数秒',f:'すうびょう',m:'unos segundos',l:'N3'},{w:'秒速',f:'びょうそく',m:'velocidad por segundo',l:'N3'},{w:'毎秒',f:'まいびょう',m:'cada segundo',l:'N3'}]},
  { rank:803, k:'岸', level:'N3', meanings:['orilla','ribera','costa'], on:['ガン'], kun:['きし'],
    words:[{w:'海岸',f:'かいがん',m:'costa / playa',l:'N4'},{w:'対岸',f:'たいがん',m:'la orilla opuesta',l:'N3'}]},
  { rank:805, k:'厚', level:'N3', meanings:['grueso','generoso','abundante'], on:['コウ'], kun:['あつ.い'],
    words:[{w:'厚紙',f:'あつがみ',m:'cartulina gruesa',l:'N3'},{w:'温厚',f:'おんこう',m:'amable / de carácter apacible',l:'N3'}]},
  { rank:805, k:'伸', level:'N3', meanings:['extenderse','estirarse','crecer'], on:['シン'], kun:['の.びる','の.ばす'],
    words:[{w:'背伸び',f:'せのび',m:'estirar / ponerse de puntillas',l:'N3'},{w:'追伸',f:'ついしん',m:'posdata',l:'N3'}]},
  { rank:808, k:'菜', level:'N3', meanings:['verdura','vegetal','plato'], on:['サイ'], kun:['な'],
    words:[{w:'野菜',f:'やさい',m:'verdura / vegetal',l:'N5'},{w:'白菜',f:'はくさい',m:'col china',l:'N3'}]},
  { rank:812, k:'浴', level:'N3', meanings:['bañarse','baño'], on:['ヨク'], kun:['あ.びる'],
    words:[{w:'入浴',f:'にゅうよく',m:'tomar un baño',l:'N3'},{w:'浴室',f:'よくしつ',m:'cuarto de baño',l:'N3'},{w:'浴衣',f:'ゆかた',m:'yukata (kimono de verano)',l:'N4'}]},
  { rank:818, k:'燃', level:'N3', meanings:['quemar','arder','combustión'], on:['ネン'], kun:['も.える','も.やす'],
    words:[{w:'燃料',f:'ねんりょう',m:'combustible / carburante',l:'N3'},{w:'可燃',f:'かねん',m:'inflamable / combustible',l:'N3'}]},
  { rank:823, k:'絡', level:'N3', meanings:['conectar','enredar','relacionar'], on:['ラク'], kun:['から.む'],
    words:[{w:'連絡',f:'れんらく',m:'contacto / comunicación',l:'N4'}]},
  { rank:833, k:'乳', level:'N3', meanings:['leche','pecho','mama'], on:['ニュウ'], kun:['ちち','ち'],
    words:[{w:'牛乳',f:'ぎゅうにゅう',m:'leche de vaca',l:'N5'},{w:'乳児',f:'にゅうじ',m:'bebé / lactante',l:'N3'},{w:'母乳',f:'ぼにゅう',m:'leche materna',l:'N3'}]},
  { rank:834, k:'恋', level:'N3', meanings:['amor romántico','enamoramiento'], on:['レン'], kun:['こい','こい.しい'],
    words:[{w:'恋愛',f:'れんあい',m:'amor romántico',l:'N3'},{w:'恋人',f:'こいびと',m:'novio / novia',l:'N3'}]},
  { rank:836, k:'粉', level:'N3', meanings:['harina','polvo'], on:['フン'], kun:['こな','こ'],
    words:[{w:'小麦粉',f:'こむぎこ',m:'harina de trigo',l:'N3'},{w:'粉末',f:'ふんまつ',m:'polvo / en polvo',l:'N3'}]},
  { rank:840, k:'包', level:'N3', meanings:['envolver','empacar','cubrir'], on:['ホウ'], kun:['つつ.む'],
    words:[{w:'小包',f:'こづつみ',m:'paquete / bulto',l:'N3'},{w:'包帯',f:'ほうたい',m:'vendaje',l:'N3'}]},
  { rank:844, k:'悩', level:'N3', meanings:['preocupación','angustia','sufrir'], on:['ノウ'], kun:['なや.む'],
    words:[{w:'苦悩',f:'くのう',m:'sufrimiento / angustia',l:'N3'}]},
  { rank:848, k:'塩', level:'N3', meanings:['sal'], on:['エン'], kun:['しお'],
    words:[{w:'塩分',f:'えんぶん',m:'contenido de sal / salinidad',l:'N3'},{w:'食塩',f:'しょくえん',m:'sal de mesa',l:'N3'}]},
  { rank:867, k:'姓', level:'N3', meanings:['apellido','nombre de familia'], on:['セイ','ショウ'], kun:[],
    words:[{w:'姓名',f:'せいめい',m:'nombre completo / apellido y nombre',l:'N3'},{w:'旧姓',f:'きゅうせい',m:'apellido de soltera',l:'N3'},{w:'同姓',f:'どうせい',m:'mismo apellido',l:'N3'}]},
  { rank:870, k:'柱', level:'N3', meanings:['pilar','poste','columna'], on:['チュウ'], kun:['はしら'],
    words:[{w:'電柱',f:'でんちゅう',m:'poste eléctrico',l:'N3'},{w:'支柱',f:'しちゅう',m:'pilar / soporte',l:'N3'}]},
  { rank:895, k:'絵', level:'N3', meanings:['pintura','cuadro'], on:['カイ','エ'], kun:[],
    words:[{w:'絵本',f:'えほん',m:'libro ilustrado',l:'N5'},{w:'絵画',f:'かいが',m:'pintura / cuadro',l:'N3'}]},
  { rank:906, k:'捨', level:'N3', meanings:['tirar','desechar','abandonar'], on:['シャ'], kun:['す.てる'],
    words:[{w:'四捨五入',f:'ししゃごにゅう',m:'redondeo',l:'N3'}]},
  { rank:910, k:'泣', level:'N3', meanings:['llorar','lloriquear'], on:['キュウ'], kun:['な.く'],
    words:[{w:'泣き声',f:'なきごえ',m:'llanto',l:'N3'}]},
  { rank:913, k:'泊', level:'N3', meanings:['alojarse','pernoctar'], on:['ハク'], kun:['と.まる'],
    words:[{w:'一泊',f:'いっぱく',m:'una noche (de alojamiento)',l:'N3'},{w:'宿泊',f:'しゅくはく',m:'alojamiento',l:'N3'}]},
  { rank:920, k:'干', level:'N3', meanings:['secar','tender','hacer la colada'], on:['カン'], kun:['ほ.す','ひ.る'],
    words:[{w:'梅干し',f:'うめぼし',m:'ciruela en vinagre',l:'N3'},{w:'干物',f:'ひもの',m:'pescado seco',l:'N3'}]},
  { rank:927, k:'棒', level:'N3', meanings:['palo','barra','palillo'], on:['ボウ'], kun:[],
    words:[{w:'鉄棒',f:'てつぼう',m:'barra de hierro / barra fija (gym)',l:'N3'},{w:'木棒',f:'もくぼう',m:'palo de madera',l:'N3'}]},
  { rank:940, k:'曜', level:'N3', meanings:['día de la semana'], on:['ヨウ'], kun:[],
    words:[{w:'月曜日',f:'げつようび',m:'lunes',l:'N5'},{w:'火曜日',f:'かようび',m:'martes',l:'N5'},{w:'水曜日',f:'すいようび',m:'miércoles',l:'N5'},{w:'何曜日',f:'なんようび',m:'¿qué día de la semana?',l:'N5'}]},
  { rank:944, k:'暖', level:'N3', meanings:['cálido','templado','tibio'], on:['ダン','ノン'], kun:['あたた.か','あたた.かい'],
    words:[{w:'暖房',f:'だんぼう',m:'calefacción',l:'N3'},{w:'温暖',f:'おんだん',m:'cálido / templado',l:'N3'}]},
  { rank:951, k:'鼻', level:'N3', meanings:['nariz'], on:['ビ'], kun:['はな'],
    words:[{w:'鼻血',f:'はなぢ',m:'hemorragia nasal',l:'N3'},{w:'耳鼻科',f:'じびか',m:'otorrinolaringología',l:'N3'}]},
  { rank:985, k:'童', level:'N3', meanings:['niño','infante','cuento infantil'], on:['ドウ'], kun:['わらべ'],
    words:[{w:'童話',f:'どうわ',m:'cuento infantil',l:'N3'},{w:'童謡',f:'どうよう',m:'canción infantil',l:'N3'},{w:'児童',f:'じどう',m:'niño / alumno de primaria',l:'N3'}]},
  { rank:986, k:'涙', level:'N3', meanings:['lágrima','llanto'], on:['ルイ'], kun:['なみだ'],
    words:[{w:'涙声',f:'なみだごえ',m:'voz entre lágrimas',l:'N3'}]},
  { rank:998, k:'氷', level:'N3', meanings:['hielo'], on:['ヒョウ'], kun:['こおり','ひ'],
    words:[{w:'氷山',f:'ひょうざん',m:'iceberg',l:'N3'},{w:'氷河',f:'ひょうが',m:'glaciar',l:'N3'}]},
  { rank:1007, k:'幼', level:'N3', meanings:['infantil','pequeño','tierno'], on:['ヨウ'], kun:['おさな.い'],
    words:[{w:'幼稚園',f:'ようちえん',m:'jardín de infancia',l:'N4'},{w:'幼児',f:'ようじ',m:'niño pequeño / infante',l:'N3'},{w:'幼稚',f:'ようち',m:'infantil / pueril',l:'N3'}]},
  { rank:1012, k:'坂', level:'N3', meanings:['cuesta','pendiente','ladera'], on:['ハン'], kun:['さか'],
    words:[{w:'坂道',f:'さかみち',m:'camino en pendiente',l:'N3'},{w:'急坂',f:'きゅうはん',m:'cuesta empinada',l:'N3'}]},
  { rank:1021, k:'貯', level:'N3', meanings:['ahorrar','almacenar'], on:['チョ'], kun:['た.める'],
    words:[{w:'貯金',f:'ちょきん',m:'ahorro / dinero ahorrado',l:'N3'},{w:'貯蓄',f:'ちょちく',m:'ahorros / acumulación',l:'N3'}]},
  { rank:1034, k:'寝', level:'N3', meanings:['dormir'], on:['シン'], kun:['ね.る'],
    words:[{w:'寝室',f:'しんしつ',m:'dormitorio',l:'N4'},{w:'昼寝',f:'ひるね',m:'siesta',l:'N4'}]},
  { rank:1041, k:'袋', level:'N3', meanings:['bolsa','saco','bolsillo'], on:['タイ'], kun:['ふくろ'],
    words:[{w:'手袋',f:'てぶくろ',m:'guantes',l:'N4'},{w:'紙袋',f:'かみぶくろ',m:'bolsa de papel',l:'N3'},{w:'寝袋',f:'ねぶくろ',m:'saco de dormir',l:'N3'}]},
  { rank:1051, k:'豆', level:'N3', meanings:['legumbre','frijol','soja'], on:['ズ','ト'], kun:['まめ'],
    words:[{w:'豆腐',f:'とうふ',m:'tofu',l:'N4'},{w:'大豆',f:'だいず',m:'soja',l:'N3'},{w:'枝豆',f:'えだまめ',m:'edamame / soja verde',l:'N3'}]},
  { rank:1066, k:'汗', level:'N3', meanings:['sudor'], on:['カン'], kun:['あせ'],
    words:[{w:'冷や汗',f:'ひやあせ',m:'sudor frío',l:'N3'}]},
  { rank:1069, k:'浅', level:'N3', meanings:['poco profundo','superficial'], on:['セン'], kun:['あさ.い'],
    words:[{w:'浅草',f:'あさくさ',m:'Asakusa (barrio de Tokio)',l:'N3'}]},
  { rank:1093, k:'卵', level:'N3', meanings:['huevo'], on:['ラン'], kun:['たまご'],
    words:[{w:'卵白',f:'らんぱく',m:'clara de huevo',l:'N3'},{w:'卵黄',f:'らんおう',m:'yema de huevo',l:'N3'}]},
  { rank:1119, k:'肯', level:'N3', meanings:['consentir','asentir','concordar'], on:['コウ'], kun:['うなず.く'],
    words:[{w:'肯定',f:'こうてい',m:'afirmación / consentimiento',l:'N3'}]},
  { rank:1121, k:'酔', level:'N3', meanings:['borracho','intoxicado','mareado'], on:['スイ'], kun:['よ.う'],
    words:[{w:'酔っ払い',f:'よっぱらい',m:'borracho',l:'N3'},{w:'二日酔い',f:'ふつかよい',m:'resaca',l:'N3'}]},
  { rank:1144, k:'机', level:'N3', meanings:['escritorio','mesa de estudio','pupitre'], on:['キ'], kun:['つくえ'],
    words:[{w:'机上',f:'きじょう',m:'teórico / sobre el papel',l:'N3'}]},
  { rank:1199, k:'拾', level:'N3', meanings:['recoger','levantar','encontrar'], on:['シュウ','ジュウ'], kun:['ひろ.う'],
    words:[{w:'拾得物',f:'しゅうとくぶつ',m:'objeto encontrado / hallazgo',l:'N3'}]},
  { rank:1205, k:'缶', level:'N3', meanings:['lata','bote'], on:['カン'], kun:[],
    words:[{w:'缶詰',f:'かんづめ',m:'conserva / comida en lata',l:'N3'}]},
  { rank:1343, k:'舟', level:'N3', meanings:['barca','bote'], on:['シュウ'], kun:['ふね','ふな'],
    words:[{w:'舟遊び',f:'ふなあそび',m:'paseo en barca',l:'N3'},{w:'小舟',f:'こぶね',m:'barquita',l:'N3'}]},
  { rank:1524, k:'匹', level:'N3', meanings:['(contador de animales pequeños)'], on:['ヒキ','ヒツ'], kun:[],
    words:[{w:'一匹',f:'いっぴき',m:'un animal (pequeño)',l:'N4'},{w:'何匹',f:'なんびき',m:'¿cuántos animales?',l:'N4'}]},
  { rank:1567, k:'萌', level:'N3', meanings:['brotar','germinar','tierno'], on:['ホウ'], kun:['も.える','きざ.す'],
    words:[]},
  { rank:1644, k:'濯', level:'N3', meanings:['lavar','enjuagar'], on:['タク'], kun:[],
    words:[{w:'洗濯',f:'せんたく',m:'lavado de ropa',l:'N4'},{w:'洗濯機',f:'せんたくき',m:'lavadora',l:'N4'}]},
]
