import type { Kanji } from './types'

const RAW: Kanji[] = [
  // ── N5 ──────────────────────────────────────────────────────────────────
  { k:'日', level:'N5', meanings:['sol','día'], on:['ニチ','ジツ'], kun:['ひ','か'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'今日',f:'きょう',m:'hoy',l:'N5'},{w:'毎日',f:'まいにち',m:'cada día',l:'N5'},{w:'日曜日',f:'にちようび',m:'domingo',l:'N5'},{w:'誕生日',f:'たんじょうび',m:'cumpleaños',l:'N4'}]},
  { k:'月', level:'N5', meanings:['luna','mes'], on:['ゲツ','ガツ'], kun:['つき'],
    words:[{w:'月曜日',f:'げつようび',m:'lunes',l:'N5'},{w:'今月',f:'こんげつ',m:'este mes',l:'N5'},{w:'毎月',f:'まいつき',m:'cada mes',l:'N4'},{w:'月見',f:'つきみ',m:'contemplación de la luna',l:'N3'}]},
  { k:'火', level:'N5', meanings:['fuego'], on:['カ'], kun:['ひ'],
    words:[{w:'火曜日',f:'かようび',m:'martes',l:'N5'},{w:'火事',f:'かじ',m:'incendio',l:'N4'},{w:'花火',f:'はなび',m:'fuegos artificiales',l:'N4'}]},
  { k:'水', level:'N5', meanings:['agua'], on:['スイ'], kun:['みず'],
    words:[{w:'水曜日',f:'すいようび',m:'miércoles',l:'N5'},{w:'水泳',f:'すいえい',m:'natación',l:'N4'},{w:'お水',f:'おみず',m:'agua (cortés)',l:'N5'}]},
  { k:'木', level:'N5', meanings:['árbol','madera'], on:['モク','ボク'], kun:['き'],
    words:[{w:'木曜日',f:'もくようび',m:'jueves',l:'N5'},{w:'木材',f:'もくざい',m:'madera',l:'N4'},{w:'木の葉',f:'このは',m:'hoja de árbol',l:'N4'}]},
  { k:'金', level:'N5', meanings:['oro','dinero'], on:['キン','コン'], kun:['かね'],
    words:[{w:'金曜日',f:'きんようび',m:'viernes',l:'N5'},{w:'お金',f:'おかね',m:'dinero',l:'N5'},{w:'金色',f:'きんいろ',m:'color dorado',l:'N4'}]},
  { k:'土', level:'N5', meanings:['tierra'], on:['ド','ト'], kun:['つち'],
    words:[{w:'土曜日',f:'どようび',m:'sábado',l:'N5'},{w:'土地',f:'とち',m:'terreno',l:'N4'},{w:'土砂',f:'どしゃ',m:'tierra y arena',l:'N3'}]},
  { k:'山', level:'N5', meanings:['montaña'], on:['サン'], kun:['やま'],
    words:[{w:'富士山',f:'ふじさん',m:'Monte Fuji',l:'N5'},{w:'山登り',f:'やまのぼり',m:'alpinismo',l:'N4'},{w:'山道',f:'やまみち',m:'camino de montaña',l:'N3'}]},
  { k:'川', level:'N5', meanings:['río'], on:['セン'], kun:['かわ'],
    words:[{w:'小川',f:'おがわ',m:'arroyo',l:'N4'},{w:'川辺',f:'かわべ',m:'orilla del río',l:'N3'},{w:'川岸',f:'かわぎし',m:'ribera',l:'N3'}]},
  { k:'人', level:'N5', meanings:['persona'], on:['ジン','ニン'], kun:['ひと'],
    words:[{w:'人々',f:'ひとびと',m:'personas',l:'N5'},{w:'外国人',f:'がいこくじん',m:'extranjero',l:'N5'},{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'人口',f:'じんこう',m:'población',l:'N4'}]},
  { k:'口', level:'N5', meanings:['boca','entrada'], on:['コウ','ク'], kun:['くち'],
    words:[{w:'人口',f:'じんこう',m:'población',l:'N4'},{w:'口座',f:'こうざ',m:'cuenta bancaria',l:'N4'},{w:'入口',f:'いりぐち',m:'entrada',l:'N5'}]},
  { k:'手', level:'N5', meanings:['mano'], on:['シュ'], kun:['て'],
    words:[{w:'手紙',f:'てがみ',m:'carta',l:'N5'},{w:'上手',f:'じょうず',m:'hábil',l:'N5'},{w:'下手',f:'へた',m:'torpe',l:'N5'},{w:'手伝う',f:'てつだう',m:'ayudar',l:'N5'}]},
  { k:'目', level:'N5', meanings:['ojo'], on:['モク','ボク'], kun:['め'],
    words:[{w:'目的',f:'もくてき',m:'propósito',l:'N4'},{w:'目薬',f:'めぐすり',m:'colirio',l:'N4'},{w:'一目',f:'ひとめ',m:'un vistazo',l:'N3'}]},
  { k:'耳', level:'N5', meanings:['oído'], on:['ジ'], kun:['みみ'],
    words:[{w:'耳鼻科',f:'じびか',m:'otorrinolaringología',l:'N3'},{w:'耳鳴り',f:'みみなり',m:'tinnitus',l:'N3'}]},
  { k:'足', level:'N5', meanings:['pie','pierna','suficiente'], on:['ソク'], kun:['あし','た'],
    words:[{w:'足りる',f:'たりる',m:'ser suficiente',l:'N5'},{w:'遠足',f:'えんそく',m:'excursión',l:'N4'},{w:'足音',f:'あしおと',m:'sonido de pasos',l:'N3'}]},
  { k:'上', level:'N5', meanings:['arriba','encima'], on:['ジョウ','ショウ'], kun:['うえ','あ','のぼ'],
    words:[{w:'上手',f:'じょうず',m:'hábil',l:'N5'},{w:'屋上',f:'おくじょう',m:'azotea',l:'N4'},{w:'上着',f:'うわぎ',m:'chaqueta',l:'N4'}]},
  { k:'下', level:'N5', meanings:['abajo','debajo'], on:['カ','ゲ'], kun:['した','さ','くだ'],
    words:[{w:'下手',f:'へた',m:'torpe',l:'N5'},{w:'地下',f:'ちか',m:'subterráneo',l:'N4'},{w:'下着',f:'したぎ',m:'ropa interior',l:'N4'}]},
  { k:'中', level:'N5', meanings:['interior','durante'], on:['チュウ'], kun:['なか'],
    words:[{w:'中学校',f:'ちゅうがっこう',m:'instituto',l:'N5'},{w:'中心',f:'ちゅうしん',m:'centro',l:'N4'},{w:'中級',f:'ちゅうきゅう',m:'nivel intermedio',l:'N3'}]},
  { k:'大', level:'N5', meanings:['grande'], on:['ダイ','タイ'], kun:['おお'],
    words:[{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'大切',f:'たいせつ',m:'importante',l:'N5'},{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'大勢',f:'おおぜい',m:'mucha gente',l:'N4'}]},
  { k:'小', level:'N5', meanings:['pequeño'], on:['ショウ'], kun:['ちい','こ'],
    words:[{w:'小学校',f:'しょうがっこう',m:'escuela primaria',l:'N5'},{w:'小説',f:'しょうせつ',m:'novela',l:'N4'},{w:'小声',f:'こごえ',m:'voz baja',l:'N3'}]},
  { k:'本', level:'N5', meanings:['libro','origen'], on:['ホン'], kun:['もと'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'本当',f:'ほんとう',m:'verdad',l:'N5'},{w:'本屋',f:'ほんや',m:'librería',l:'N5'},{w:'基本',f:'きほん',m:'fundamento',l:'N4'}]},
  { k:'円', level:'N5', meanings:['yen','círculo'], on:['エン'], kun:['まる'],
    words:[{w:'百円',f:'ひゃくえん',m:'100 yenes',l:'N5'},{w:'円高',f:'えんだか',m:'yen fuerte',l:'N3'},{w:'円安',f:'えんやす',m:'yen débil',l:'N3'}]},
  { k:'年', level:'N5', meanings:['año'], on:['ネン'], kun:['とし'],
    words:[{w:'今年',f:'ことし',m:'este año',l:'N5'},{w:'毎年',f:'まいとし',m:'cada año',l:'N5'},{w:'年齢',f:'ねんれい',m:'edad',l:'N4'}]},
  { k:'時', level:'N5', meanings:['tiempo','hora'], on:['ジ'], kun:['とき'],
    words:[{w:'時間',f:'じかん',m:'tiempo',l:'N5'},{w:'時々',f:'ときどき',m:'a veces',l:'N5'},{w:'時代',f:'じだい',m:'era, época',l:'N4'}]},
  { k:'国', level:'N5', meanings:['país','nación'], on:['コク'], kun:['くに'],
    words:[{w:'外国',f:'がいこく',m:'extranjero',l:'N5'},{w:'中国',f:'ちゅうごく',m:'China',l:'N5'},{w:'国際',f:'こくさい',m:'internacional',l:'N4'}]},
  { k:'学', level:'N5', meanings:['estudio','aprendizaje'], on:['ガク'], kun:['まな'],
    words:[{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'学習',f:'がくしゅう',m:'aprendizaje',l:'N4'}]},
  { k:'校', level:'N5', meanings:['escuela'], on:['コウ'], kun:[],
    words:[{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},{w:'校長',f:'こうちょう',m:'director de escuela',l:'N4'}]},
  { k:'先', level:'N5', meanings:['antes','adelante'], on:['セン'], kun:['さき'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'先週',f:'せんしゅう',m:'la semana pasada',l:'N5'},{w:'先輩',f:'せんぱい',m:'superior/veterano',l:'N4'}]},
  { k:'生', level:'N5', meanings:['vida','nacer'], on:['セイ','ショウ'], kun:['い','う','なま'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'学生',f:'がくせい',m:'estudiante',l:'N5'},{w:'生活',f:'せいかつ',m:'vida cotidiana',l:'N4'}]},
  { k:'電', level:'N5', meanings:['electricidad'], on:['デン'], kun:[],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'電気',f:'でんき',m:'electricidad/luz',l:'N5'}]},
  { k:'車', level:'N5', meanings:['coche','vehículo'], on:['シャ'], kun:['くるま'],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},{w:'駐車場',f:'ちゅうしゃじょう',m:'aparcamiento',l:'N4'}]},
  { k:'語', level:'N5', meanings:['idioma','palabra'], on:['ゴ'], kun:['かた'],
    words:[{w:'日本語',f:'にほんご',m:'japonés',l:'N5'},{w:'英語',f:'えいご',m:'inglés',l:'N5'},{w:'語学',f:'ごがく',m:'estudio de idiomas',l:'N4'}]},
  { k:'何', level:'N5', meanings:['qué','cuánto'], on:['カ'], kun:['なに','なん'],
    words:[{w:'何か',f:'なにか',m:'algo',l:'N5'},{w:'何故',f:'なぜ',m:'por qué',l:'N4'},{w:'何度',f:'なんど',m:'cuántas veces',l:'N4'}]},
  { k:'白', level:'N5', meanings:['blanco'], on:['ハク','ビャク'], kun:['しろ'],
    words:[{w:'白い',f:'しろい',m:'blanco',l:'N5'},{w:'白紙',f:'はくし',m:'papel en blanco',l:'N4'},{w:'告白',f:'こくはく',m:'confesión',l:'N3'}]},
  { k:'見', level:'N5', meanings:['ver','mirar'], on:['ケン'], kun:['み'],
    words:[{w:'見る',f:'みる',m:'ver',l:'N5'},{w:'意見',f:'いけん',m:'opinión',l:'N4'},{w:'見学',f:'けんがく',m:'visita de estudio',l:'N4'}]},
  { k:'行', level:'N5', meanings:['ir'], on:['コウ','ギョウ'], kun:['い','おこな'],
    words:[{w:'旅行',f:'りょこう',m:'viaje',l:'N5'},{w:'銀行',f:'ぎんこう',m:'banco',l:'N5'},{w:'行動',f:'こうどう',m:'acción',l:'N4'}]},
  { k:'食', level:'N5', meanings:['comer','comida'], on:['ショク'], kun:['た','く'],
    words:[{w:'食べる',f:'たべる',m:'comer',l:'N5'},{w:'食事',f:'しょくじ',m:'comida',l:'N5'},{w:'食料',f:'しょくりょう',m:'alimentos',l:'N4'}]},
  { k:'飲', level:'N5', meanings:['beber'], on:['イン'], kun:['の'],
    words:[{w:'飲む',f:'のむ',m:'beber',l:'N5'},{w:'飲み物',f:'のみもの',m:'bebida',l:'N5'},{w:'飲食店',f:'いんしょくてん',m:'restaurante',l:'N4'}]},

  // ── N4 ──────────────────────────────────────────────────────────────────
  { k:'会', level:'N4', meanings:['reunión','encontrar'], on:['カイ','エ'], kun:['あ'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},{w:'会議',f:'かいぎ',m:'reunión',l:'N4'},{w:'社会',f:'しゃかい',m:'sociedad',l:'N4'}]},
  { k:'社', level:'N4', meanings:['empresa','sociedad'], on:['シャ'], kun:['やしろ'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},{w:'社会',f:'しゃかい',m:'sociedad',l:'N4'},{w:'神社',f:'じんじゃ',m:'santuario shinto',l:'N4'}]},
  { k:'長', level:'N4', meanings:['largo','jefe'], on:['チョウ'], kun:['なが'],
    words:[{w:'長い',f:'ながい',m:'largo',l:'N5'},{w:'社長',f:'しゃちょう',m:'presidente de empresa',l:'N4'},{w:'校長',f:'こうちょう',m:'director de escuela',l:'N4'}]},
  { k:'高', level:'N4', meanings:['alto','caro'], on:['コウ'], kun:['たか'],
    words:[{w:'高い',f:'たかい',m:'alto/caro',l:'N5'},{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},{w:'最高',f:'さいこう',m:'el mejor/máximo',l:'N4'}]},
  { k:'新', level:'N4', meanings:['nuevo'], on:['シン'], kun:['あたら','にい'],
    words:[{w:'新しい',f:'あたらしい',m:'nuevo',l:'N5'},{w:'新幹線',f:'しんかんせん',m:'tren bala',l:'N4'},{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'}]},
  { k:'古', level:'N4', meanings:['antiguo','viejo'], on:['コ'], kun:['ふる'],
    words:[{w:'古い',f:'ふるい',m:'viejo/antiguo',l:'N5'},{w:'古典',f:'こてん',m:'clásico',l:'N4'},{w:'中古',f:'ちゅうこ',m:'segunda mano',l:'N4'}]},
  { k:'明', level:'N4', meanings:['brillante','claro','mañana'], on:['メイ','ミョウ'], kun:['あか','あき'],
    words:[{w:'明日',f:'あした',m:'mañana',l:'N5'},{w:'説明',f:'せつめい',m:'explicación',l:'N4'},{w:'明るい',f:'あかるい',m:'brillante',l:'N5'}]},
  { k:'暗', level:'N4', meanings:['oscuro'], on:['アン'], kun:['くら'],
    words:[{w:'暗い',f:'くらい',m:'oscuro',l:'N5'},{w:'暗記',f:'あんき',m:'memorización',l:'N4'},{w:'暗示',f:'あんじ',m:'insinuación',l:'N3'}]},
  { k:'多', level:'N4', meanings:['mucho','abundante'], on:['タ'], kun:['おお'],
    words:[{w:'多い',f:'おおい',m:'mucho/muchos',l:'N5'},{w:'多分',f:'たぶん',m:'probablemente',l:'N5'},{w:'多様',f:'たよう',m:'diverso',l:'N3'}]},
  { k:'少', level:'N4', meanings:['poco','joven'], on:['ショウ'], kun:['すく','すこ'],
    words:[{w:'少ない',f:'すくない',m:'poco',l:'N5'},{w:'少し',f:'すこし',m:'un poco',l:'N5'},{w:'少女',f:'しょうじょ',m:'chica joven',l:'N4'}]},
  { k:'近', level:'N4', meanings:['cerca'], on:['キン'], kun:['ちか'],
    words:[{w:'近い',f:'ちかい',m:'cercano',l:'N5'},{w:'近所',f:'きんじょ',m:'vecindario',l:'N4'},{w:'最近',f:'さいきん',m:'recientemente',l:'N4'}]},
  { k:'遠', level:'N4', meanings:['lejos'], on:['エン','オン'], kun:['とお'],
    words:[{w:'遠い',f:'とおい',m:'lejano',l:'N5'},{w:'遠足',f:'えんそく',m:'excursión',l:'N4'},{w:'永遠',f:'えいえん',m:'eternidad',l:'N3'}]},
  { k:'強', level:'N4', meanings:['fuerte'], on:['キョウ','ゴウ'], kun:['つよ'],
    words:[{w:'強い',f:'つよい',m:'fuerte',l:'N5'},{w:'勉強',f:'べんきょう',m:'estudio',l:'N5'},{w:'強調',f:'きょうちょう',m:'énfasis',l:'N3'}]},
  { k:'弱', level:'N4', meanings:['débil'], on:['ジャク'], kun:['よわ'],
    words:[{w:'弱い',f:'よわい',m:'débil',l:'N5'},{w:'弱点',f:'じゃくてん',m:'punto débil',l:'N4'},{w:'弱者',f:'じゃくしゃ',m:'persona débil',l:'N3'}]},
  { k:'早', level:'N4', meanings:['temprano','rápido'], on:['ソウ','サッ'], kun:['はや'],
    words:[{w:'早い',f:'はやい',m:'temprano/rápido',l:'N5'},{w:'早速',f:'さっそく',m:'de inmediato',l:'N4'},{w:'早朝',f:'そうちょう',m:'madrugada',l:'N3'}]},
  { k:'遅', level:'N4', meanings:['tarde','lento'], on:['チ'], kun:['おそ','おく'],
    words:[{w:'遅い',f:'おそい',m:'tarde/lento',l:'N5'},{w:'遅刻',f:'ちこく',m:'llegar tarde',l:'N4'},{w:'遅延',f:'ちえん',m:'retraso',l:'N3'}]},
  { k:'重', level:'N4', meanings:['pesado','importante'], on:['ジュウ','チョウ'], kun:['おも','かさ'],
    words:[{w:'重い',f:'おもい',m:'pesado',l:'N5'},{w:'重要',f:'じゅうよう',m:'importante',l:'N4'},{w:'重大',f:'じゅうだい',m:'grave/importante',l:'N3'}]},
  { k:'軽', level:'N4', meanings:['ligero','leve'], on:['ケイ'], kun:['かる'],
    words:[{w:'軽い',f:'かるい',m:'ligero',l:'N5'},{w:'気軽',f:'きがる',m:'despreocupado',l:'N4'},{w:'軽食',f:'けいしょく',m:'refrigerio',l:'N3'}]},
  { k:'広', level:'N4', meanings:['amplio'], on:['コウ'], kun:['ひろ'],
    words:[{w:'広い',f:'ひろい',m:'amplio',l:'N5'},{w:'広告',f:'こうこく',m:'publicidad',l:'N4'},{w:'広場',f:'ひろば',m:'plaza',l:'N4'}]},
  { k:'動', level:'N4', meanings:['mover','moverse'], on:['ドウ'], kun:['うご'],
    words:[{w:'運動',f:'うんどう',m:'ejercicio',l:'N5'},{w:'動物',f:'どうぶつ',m:'animal',l:'N5'},{w:'活動',f:'かつどう',m:'actividad',l:'N4'}]},
  { k:'使', level:'N4', meanings:['usar'], on:['シ'], kun:['つか'],
    words:[{w:'使う',f:'つかう',m:'usar',l:'N5'},{w:'使い方',f:'つかいかた',m:'forma de usar',l:'N4'},{w:'天使',f:'てんし',m:'ángel',l:'N4'}]},
  { k:'始', level:'N4', meanings:['comenzar'], on:['シ'], kun:['はじ'],
    words:[{w:'始める',f:'はじめる',m:'empezar (trans.)',l:'N5'},{w:'始まる',f:'はじまる',m:'empezar (intrans.)',l:'N5'},{w:'開始',f:'かいし',m:'inicio',l:'N4'}]},
  { k:'終', level:'N4', meanings:['terminar','fin'], on:['シュウ'], kun:['お'],
    words:[{w:'終わる',f:'おわる',m:'terminar',l:'N5'},{w:'終電',f:'しゅうでん',m:'último tren',l:'N4'},{w:'最終',f:'さいしゅう',m:'último/final',l:'N4'}]},
  { k:'働', level:'N4', meanings:['trabajar'], on:['ドウ'], kun:['はたら'],
    words:[{w:'働く',f:'はたらく',m:'trabajar',l:'N5'},{w:'労働',f:'ろうどう',m:'trabajo/labor',l:'N4'},{w:'働き者',f:'はたらきもの',m:'persona trabajadora',l:'N3'}]},
  { k:'住', level:'N4', meanings:['residir','vivir en'], on:['ジュウ'], kun:['す'],
    words:[{w:'住む',f:'すむ',m:'vivir/residir',l:'N5'},{w:'住所',f:'じゅうしょ',m:'dirección',l:'N4'},{w:'住民',f:'じゅうみん',m:'residente',l:'N4'}]},
  { k:'道', level:'N4', meanings:['camino','vía'], on:['ドウ','トウ'], kun:['みち'],
    words:[{w:'道路',f:'どうろ',m:'carretera',l:'N4'},{w:'道具',f:'どうぐ',m:'herramienta',l:'N4'},{w:'北海道',f:'ほっかいどう',m:'Hokkaido',l:'N4'}]},
  { k:'空', level:'N4', meanings:['cielo','vacío'], on:['クウ'], kun:['そら','あ','から'],
    words:[{w:'空港',f:'くうこう',m:'aeropuerto',l:'N5'},{w:'空気',f:'くうき',m:'aire',l:'N5'},{w:'青空',f:'あおぞら',m:'cielo azul',l:'N4'}]},
  { k:'海', level:'N4', meanings:['mar'], on:['カイ'], kun:['うみ'],
    words:[{w:'海外',f:'かいがい',m:'extranjero',l:'N4'},{w:'日本海',f:'にほんかい',m:'Mar de Japón',l:'N4'},{w:'海岸',f:'かいがん',m:'costa',l:'N4'}]},
  { k:'花', level:'N4', meanings:['flor'], on:['カ'], kun:['はな'],
    words:[{w:'花',f:'はな',m:'flor',l:'N5'},{w:'花火',f:'はなび',m:'fuegos artificiales',l:'N4'},{w:'花見',f:'はなみ',m:'contemplación de flores',l:'N4'}]},
  { k:'米', level:'N4', meanings:['arroz','EE.UU.'], on:['マイ','ベイ'], kun:['こめ'],
    words:[{w:'お米',f:'おこめ',m:'arroz',l:'N5'},{w:'米国',f:'べいこく',m:'Estados Unidos',l:'N4'},{w:'玄米',f:'げんまい',m:'arroz integral',l:'N3'}]},
  { k:'肉', level:'N4', meanings:['carne'], on:['ニク'], kun:[],
    words:[{w:'牛肉',f:'ぎゅうにく',m:'carne de vaca',l:'N5'},{w:'肉体',f:'にくたい',m:'cuerpo físico',l:'N4'},{w:'筋肉',f:'きんにく',m:'músculo',l:'N3'}]},
  { k:'魚', level:'N4', meanings:['pez','pescado'], on:['ギョ'], kun:['さかな','うお'],
    words:[{w:'魚',f:'さかな',m:'pescado',l:'N5'},{w:'金魚',f:'きんぎょ',m:'pez dorado',l:'N4'},{w:'魚介類',f:'ぎょかいるい',m:'mariscos',l:'N3'}]},
  { k:'心', level:'N4', meanings:['corazón','mente'], on:['シン'], kun:['こころ'],
    words:[{w:'安心',f:'あんしん',m:'tranquilidad',l:'N4'},{w:'心配',f:'しんぱい',m:'preocupación',l:'N4'},{w:'中心',f:'ちゅうしん',m:'centro',l:'N4'}]},
  { k:'体', level:'N4', meanings:['cuerpo'], on:['タイ','テイ'], kun:['からだ'],
    words:[{w:'体',f:'からだ',m:'cuerpo',l:'N5'},{w:'体育',f:'たいいく',m:'educación física',l:'N4'},{w:'体験',f:'たいけん',m:'experiencia',l:'N4'}]},
  { k:'頭', level:'N4', meanings:['cabeza'], on:['トウ','ズ'], kun:['あたま','かしら'],
    words:[{w:'頭',f:'あたま',m:'cabeza',l:'N5'},{w:'先頭',f:'せんとう',m:'frente/inicio',l:'N4'},{w:'頭痛',f:'ずつう',m:'dolor de cabeza',l:'N4'}]},
  { k:'顔', level:'N4', meanings:['cara','rostro'], on:['ガン'], kun:['かお'],
    words:[{w:'顔',f:'かお',m:'cara',l:'N5'},{w:'笑顔',f:'えがお',m:'sonrisa',l:'N4'},{w:'顔色',f:'かおいろ',m:'color de la cara',l:'N4'}]},
  { k:'声', level:'N4', meanings:['voz'], on:['セイ','ショウ'], kun:['こえ'],
    words:[{w:'声',f:'こえ',m:'voz',l:'N5'},{w:'大声',f:'おおごえ',m:'voz alta',l:'N4'},{w:'声優',f:'せいゆう',m:'actor de voz',l:'N3'}]},
  { k:'色', level:'N4', meanings:['color'], on:['ショク','シキ'], kun:['いろ'],
    words:[{w:'色',f:'いろ',m:'color',l:'N5'},{w:'茶色',f:'ちゃいろ',m:'marrón',l:'N5'},{w:'景色',f:'けしき',m:'paisaje',l:'N4'}]},
  { k:'音', level:'N4', meanings:['sonido'], on:['オン','イン'], kun:['おと','ね'],
    words:[{w:'音楽',f:'おんがく',m:'música',l:'N5'},{w:'発音',f:'はつおん',m:'pronunciación',l:'N4'},{w:'音声',f:'おんせい',m:'voz/sonido',l:'N4'}]},
  { k:'光', level:'N4', meanings:['luz','brillar'], on:['コウ'], kun:['ひかり'],
    words:[{w:'光',f:'ひかり',m:'luz',l:'N5'},{w:'観光',f:'かんこう',m:'turismo',l:'N4'},{w:'光線',f:'こうせん',m:'rayo de luz',l:'N3'}]},
  { k:'風', level:'N4', meanings:['viento'], on:['フウ','フ'], kun:['かぜ'],
    words:[{w:'風',f:'かぜ',m:'viento',l:'N5'},{w:'台風',f:'たいふう',m:'tifón',l:'N4'},{w:'風景',f:'ふうけい',m:'paisaje',l:'N4'}]},
  { k:'雨', level:'N4', meanings:['lluvia'], on:['ウ'], kun:['あめ','あま'],
    words:[{w:'雨',f:'あめ',m:'lluvia',l:'N5'},{w:'大雨',f:'おおあめ',m:'lluvia fuerte',l:'N4'},{w:'梅雨',f:'つゆ',m:'temporada de lluvias',l:'N4'}]},
  { k:'雪', level:'N4', meanings:['nieve'], on:['セツ'], kun:['ゆき'],
    words:[{w:'雪',f:'ゆき',m:'nieve',l:'N5'},{w:'大雪',f:'おおゆき',m:'nevada intensa',l:'N4'},{w:'初雪',f:'はつゆき',m:'primera nieve',l:'N3'}]},
  { k:'春', level:'N4', meanings:['primavera'], on:['シュン'], kun:['はる'],
    words:[{w:'春',f:'はる',m:'primavera',l:'N5'},{w:'春休み',f:'はるやすみ',m:'vacaciones de primavera',l:'N4'},{w:'青春',f:'せいしゅん',m:'juventud',l:'N4'}]},
  { k:'夏', level:'N4', meanings:['verano'], on:['カ','ゲ'], kun:['なつ'],
    words:[{w:'夏',f:'なつ',m:'verano',l:'N5'},{w:'夏休み',f:'なつやすみ',m:'vacaciones de verano',l:'N5'},{w:'初夏',f:'しょか',m:'principios del verano',l:'N3'}]},
  { k:'秋', level:'N4', meanings:['otoño'], on:['シュウ'], kun:['あき'],
    words:[{w:'秋',f:'あき',m:'otoño',l:'N5'},{w:'秋分',f:'しゅうぶん',m:'equinoccio de otoño',l:'N4'},{w:'実りの秋',f:'みのりのあき',m:'otoño de la cosecha',l:'N3'}]},
  { k:'冬', level:'N4', meanings:['invierno'], on:['トウ'], kun:['ふゆ'],
    words:[{w:'冬',f:'ふゆ',m:'invierno',l:'N5'},{w:'冬休み',f:'ふゆやすみ',m:'vacaciones de invierno',l:'N5'},{w:'真冬',f:'まふゆ',m:'pleno invierno',l:'N3'}]},
  { k:'朝', level:'N4', meanings:['mañana'], on:['チョウ'], kun:['あさ'],
    words:[{w:'朝',f:'あさ',m:'mañana',l:'N5'},{w:'毎朝',f:'まいあさ',m:'cada mañana',l:'N5'},{w:'朝食',f:'ちょうしょく',m:'desayuno',l:'N4'}]},
  { k:'昼', level:'N4', meanings:['mediodía'], on:['チュウ'], kun:['ひる'],
    words:[{w:'昼',f:'ひる',m:'mediodía',l:'N5'},{w:'昼食',f:'ちゅうしょく',m:'almuerzo',l:'N4'},{w:'昼間',f:'ひるま',m:'durante el día',l:'N4'}]},
  { k:'夜', level:'N4', meanings:['noche'], on:['ヤ'], kun:['よる','よ'],
    words:[{w:'夜',f:'よる',m:'noche',l:'N5'},{w:'今夜',f:'こんや',m:'esta noche',l:'N5'},{w:'夜中',f:'よなか',m:'medianoche',l:'N4'}]},
  { k:'医', level:'N4', meanings:['medicina','médico'], on:['イ'], kun:[],
    words:[{w:'医者',f:'いしゃ',m:'médico',l:'N5'},{w:'医学',f:'いがく',m:'medicina',l:'N4'},{w:'医療',f:'いりょう',m:'atención médica',l:'N3'}]},
  { k:'病', level:'N4', meanings:['enfermedad'], on:['ビョウ','ヘイ'], kun:['や'],
    words:[{w:'病院',f:'びょういん',m:'hospital',l:'N5'},{w:'病気',f:'びょうき',m:'enfermedad',l:'N5'},{w:'疾病',f:'しっぺい',m:'enfermedad (formal)',l:'N3'}]},
  { k:'薬', level:'N4', meanings:['medicina','fármaco'], on:['ヤク'], kun:['くすり'],
    words:[{w:'薬',f:'くすり',m:'medicina',l:'N5'},{w:'薬局',f:'やっきょく',m:'farmacia',l:'N4'},{w:'薬剤師',f:'やくざいし',m:'farmacéutico',l:'N3'}]},
  { k:'映', level:'N4', meanings:['proyectar','reflejar'], on:['エイ'], kun:['うつ'],
    words:[{w:'映画',f:'えいが',m:'película',l:'N5'},{w:'映像',f:'えいぞう',m:'imagen/video',l:'N4'},{w:'上映',f:'じょうえい',m:'proyección',l:'N3'}]},
  { k:'料', level:'N4', meanings:['tarifa','ingrediente'], on:['リョウ'], kun:[],
    words:[{w:'料理',f:'りょうり',m:'cocina',l:'N5'},{w:'料金',f:'りょうきん',m:'tarifa',l:'N4'},{w:'材料',f:'ざいりょう',m:'ingredientes/materiales',l:'N4'}]},
  { k:'理', level:'N4', meanings:['razón','principio'], on:['リ'], kun:[],
    words:[{w:'料理',f:'りょうり',m:'cocina',l:'N5'},{w:'理由',f:'りゆう',m:'razón',l:'N4'},{w:'理解',f:'りかい',m:'comprensión',l:'N4'}]},
  { k:'地', level:'N4', meanings:['tierra','terreno'], on:['チ','ジ'], kun:[],
    words:[{w:'地下',f:'ちか',m:'subterráneo',l:'N4'},{w:'地図',f:'ちず',m:'mapa',l:'N5'},{w:'土地',f:'とち',m:'terreno',l:'N4'}]},
  { k:'図', level:'N4', meanings:['mapa','diagrama'], on:['ズ','ト'], kun:['はか'],
    words:[{w:'地図',f:'ちず',m:'mapa',l:'N5'},{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'図形',f:'ずけい',m:'figura geométrica',l:'N4'}]},
  { k:'紙', level:'N4', meanings:['papel'], on:['シ'], kun:['かみ'],
    words:[{w:'手紙',f:'てがみ',m:'carta',l:'N5'},{w:'新聞紙',f:'しんぶんし',m:'papel de periódico',l:'N4'},{w:'折り紙',f:'おりがみ',m:'origami',l:'N4'}]},
  { k:'字', level:'N4', meanings:['carácter','letra'], on:['ジ'], kun:['あざ'],
    words:[{w:'漢字',f:'かんじ',m:'kanji',l:'N5'},{w:'文字',f:'もじ',m:'carácter/letra',l:'N4'},{w:'数字',f:'すうじ',m:'número',l:'N4'}]},
  { k:'文', level:'N4', meanings:['texto','escritura'], on:['ブン','モン'], kun:['ふみ'],
    words:[{w:'文化',f:'ぶんか',m:'cultura',l:'N4'},{w:'作文',f:'さくぶん',m:'redacción',l:'N4'},{w:'文法',f:'ぶんぽう',m:'gramática',l:'N4'}]},
  { k:'読', level:'N4', meanings:['leer'], on:['ドク','トク'], kun:['よ'],
    words:[{w:'読む',f:'よむ',m:'leer',l:'N5'},{w:'読書',f:'どくしょ',m:'lectura',l:'N4'},{w:'読者',f:'どくしゃ',m:'lector',l:'N4'}]},
  { k:'書', level:'N4', meanings:['escribir'], on:['ショ'], kun:['か'],
    words:[{w:'書く',f:'かく',m:'escribir',l:'N5'},{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'書類',f:'しょるい',m:'documentos',l:'N4'}]},
  { k:'話', level:'N4', meanings:['hablar','historia'], on:['ワ'], kun:['はな','はなし'],
    words:[{w:'話す',f:'はなす',m:'hablar',l:'N5'},{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'会話',f:'かいわ',m:'conversación',l:'N4'}]},
  { k:'聞', level:'N4', meanings:['escuchar','preguntar'], on:['ブン','モン'], kun:['き'],
    words:[{w:'聞く',f:'きく',m:'escuchar/preguntar',l:'N5'},{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'},{w:'見聞',f:'けんぶん',m:'conocimiento/experiencia',l:'N3'}]},
  { k:'言', level:'N4', meanings:['decir','palabra'], on:['ゲン','ゴン'], kun:['い','こと'],
    words:[{w:'言う',f:'いう',m:'decir',l:'N5'},{w:'言語',f:'げんご',m:'lenguaje',l:'N4'},{w:'言葉',f:'ことば',m:'palabra/idioma',l:'N4'}]},
  { k:'来', level:'N4', meanings:['venir'], on:['ライ'], kun:['く','き','こ'],
    words:[{w:'来る',f:'くる',m:'venir',l:'N5'},{w:'未来',f:'みらい',m:'futuro',l:'N4'},{w:'来週',f:'らいしゅう',m:'la semana próxima',l:'N5'}]},
  { k:'出', level:'N4', meanings:['salir','emitir'], on:['シュツ'], kun:['で','だ'],
    words:[{w:'出る',f:'でる',m:'salir',l:'N5'},{w:'出口',f:'でぐち',m:'salida',l:'N5'},{w:'提出',f:'ていしゅつ',m:'enviar/entregar',l:'N4'}]},
  { k:'入', level:'N4', meanings:['entrar'], on:['ニュウ'], kun:['い','はい'],
    words:[{w:'入る',f:'はいる',m:'entrar',l:'N5'},{w:'入口',f:'いりぐち',m:'entrada',l:'N5'},{w:'入学',f:'にゅうがく',m:'ingreso escolar',l:'N4'}]},
  { k:'帰', level:'N4', meanings:['regresar'], on:['キ'], kun:['かえ'],
    words:[{w:'帰る',f:'かえる',m:'regresar',l:'N5'},{w:'帰国',f:'きこく',m:'regreso al país',l:'N4'},{w:'日帰り',f:'ひがえり',m:'excursión de un día',l:'N4'}]},
  { k:'教', level:'N4', meanings:['enseñar'], on:['キョウ'], kun:['おし'],
    words:[{w:'教える',f:'おしえる',m:'enseñar',l:'N5'},{w:'教室',f:'きょうしつ',m:'aula',l:'N5'},{w:'教育',f:'きょういく',m:'educación',l:'N4'}]},
  { k:'知', level:'N4', meanings:['saber','conocer'], on:['チ'], kun:['し'],
    words:[{w:'知る',f:'しる',m:'saber/conocer',l:'N5'},{w:'知識',f:'ちしき',m:'conocimiento',l:'N4'},{w:'知人',f:'ちじん',m:'conocido',l:'N4'}]},
  { k:'思', level:'N4', meanings:['pensar','sentir'], on:['シ'], kun:['おも'],
    words:[{w:'思う',f:'おもう',m:'pensar/creer',l:'N5'},{w:'思想',f:'しそう',m:'pensamiento/ideología',l:'N4'},{w:'思い出',f:'おもいで',m:'recuerdo',l:'N4'}]},
  { k:'考', level:'N4', meanings:['considerar','pensar'], on:['コウ'], kun:['かんが'],
    words:[{w:'考える',f:'かんがえる',m:'pensar/considerar',l:'N5'},{w:'参考',f:'さんこう',m:'referencia',l:'N4'},{w:'思考',f:'しこう',m:'pensamiento',l:'N3'}]},
  { k:'感', level:'N4', meanings:['sentir','emoción'], on:['カン'], kun:[],
    words:[{w:'感じる',f:'かんじる',m:'sentir',l:'N5'},{w:'感謝',f:'かんしゃ',m:'gratitud',l:'N4'},{w:'感動',f:'かんどう',m:'emoción profunda',l:'N4'}]},
  { k:'急', level:'N4', meanings:['urgente','rápido'], on:['キュウ'], kun:['いそ'],
    words:[{w:'急ぐ',f:'いそぐ',m:'apresurarse',l:'N5'},{w:'急行',f:'きゅうこう',m:'tren expreso',l:'N4'},{w:'緊急',f:'きんきゅう',m:'emergencia',l:'N3'}]},
  { k:'待', level:'N4', meanings:['esperar'], on:['タイ'], kun:['ま'],
    words:[{w:'待つ',f:'まつ',m:'esperar',l:'N5'},{w:'期待',f:'きたい',m:'expectativa',l:'N4'},{w:'招待',f:'しょうたい',m:'invitación',l:'N4'}]},
  { k:'持', level:'N4', meanings:['sostener','tener'], on:['ジ'], kun:['も'],
    words:[{w:'持つ',f:'もつ',m:'tener/sostener',l:'N5'},{w:'気持ち',f:'きもち',m:'sentimiento',l:'N5'},{w:'維持',f:'いじ',m:'mantenimiento',l:'N3'}]},
  { k:'買', level:'N4', meanings:['comprar'], on:['バイ'], kun:['か'],
    words:[{w:'買う',f:'かう',m:'comprar',l:'N5'},{w:'買い物',f:'かいもの',m:'compras',l:'N5'},{w:'購買',f:'こうばい',m:'compra (formal)',l:'N3'}]},
  { k:'売', level:'N4', meanings:['vender'], on:['バイ'], kun:['う'],
    words:[{w:'売る',f:'うる',m:'vender',l:'N5'},{w:'売り場',f:'うりば',m:'mostrador de ventas',l:'N4'},{w:'販売',f:'はんばい',m:'venta',l:'N3'}]},
  { k:'乗', level:'N4', meanings:['montar','subir a'], on:['ジョウ'], kun:['の'],
    words:[{w:'乗る',f:'のる',m:'montar/subir a',l:'N5'},{w:'乗り換え',f:'のりかえ',m:'transbordo',l:'N4'},{w:'乗客',f:'じょうきゃく',m:'pasajero',l:'N4'}]},
  { k:'起', level:'N4', meanings:['levantarse','ocurrir'], on:['キ'], kun:['お'],
    words:[{w:'起きる',f:'おきる',m:'levantarse/despertarse',l:'N5'},{w:'起こる',f:'おこる',m:'ocurrir',l:'N5'},{w:'起業',f:'きぎょう',m:'crear empresa',l:'N3'}]},
  { k:'寝', level:'N4', meanings:['dormir'], on:['シン'], kun:['ね'],
    words:[{w:'寝る',f:'ねる',m:'dormir',l:'N5'},{w:'寝室',f:'しんしつ',m:'dormitorio',l:'N4'},{w:'昼寝',f:'ひるね',m:'siesta',l:'N4'}]},
  { k:'泳', level:'N4', meanings:['nadar'], on:['エイ'], kun:['およ'],
    words:[{w:'泳ぐ',f:'およぐ',m:'nadar',l:'N5'},{w:'水泳',f:'すいえい',m:'natación',l:'N4'},{w:'遠泳',f:'えんえい',m:'natación de largo recorrido',l:'N3'}]},
  { k:'走', level:'N4', meanings:['correr'], on:['ソウ'], kun:['はし'],
    words:[{w:'走る',f:'はしる',m:'correr',l:'N5'},{w:'競走',f:'きょうそう',m:'carrera',l:'N4'},{w:'走者',f:'そうしゃ',m:'corredor',l:'N3'}]},
  { k:'飛', level:'N4', meanings:['volar'], on:['ヒ'], kun:['と'],
    words:[{w:'飛ぶ',f:'とぶ',m:'volar/saltar',l:'N5'},{w:'飛行機',f:'ひこうき',m:'avión',l:'N5'},{w:'飛躍',f:'ひやく',m:'salto/progreso',l:'N3'}]},
  { k:'切', level:'N4', meanings:['cortar','importante'], on:['セツ','サイ'], kun:['き'],
    words:[{w:'切る',f:'きる',m:'cortar',l:'N5'},{w:'大切',f:'たいせつ',m:'importante',l:'N5'},{w:'切符',f:'きっぷ',m:'billete',l:'N5'}]},
  { k:'歌', level:'N4', meanings:['cantar','canción'], on:['カ'], kun:['うた'],
    words:[{w:'歌う',f:'うたう',m:'cantar',l:'N5'},{w:'歌手',f:'かしゅ',m:'cantante',l:'N4'},{w:'国歌',f:'こっか',m:'himno nacional',l:'N3'}]},
  { k:'絵', level:'N4', meanings:['pintura','cuadro'], on:['カイ','エ'], kun:[],
    words:[{w:'絵',f:'え',m:'pintura/dibujo',l:'N5'},{w:'絵本',f:'えほん',m:'libro ilustrado',l:'N4'},{w:'絵画',f:'かいが',m:'pintura (arte)',l:'N3'}]},
  { k:'写', level:'N4', meanings:['copiar','fotografiar'], on:['シャ'], kun:['うつ'],
    words:[{w:'写真',f:'しゃしん',m:'fotografía',l:'N5'},{w:'写す',f:'うつす',m:'copiar',l:'N4'},{w:'複写',f:'ふくしゃ',m:'copia',l:'N3'}]},
  { k:'習', level:'N4', meanings:['aprender','practicar'], on:['シュウ'], kun:['なら'],
    words:[{w:'習う',f:'ならう',m:'aprender',l:'N5'},{w:'学習',f:'がくしゅう',m:'aprendizaje',l:'N4'},{w:'習慣',f:'しゅうかん',m:'costumbre',l:'N4'}]},
  { k:'練', level:'N4', meanings:['practicar','entrenar'], on:['レン'], kun:['ね'],
    words:[{w:'練習',f:'れんしゅう',m:'práctica',l:'N5'},{w:'訓練',f:'くんれん',m:'entrenamiento',l:'N4'},{w:'練り直す',f:'ねりなおす',m:'revisar/refinar',l:'N3'}]},

  // ── N3 ──────────────────────────────────────────────────────────────────
  { k:'達', level:'N3', meanings:['alcanzar','plural (personas)'], on:['タツ'], kun:['た'],
    words:[{w:'友達',f:'ともだち',m:'amigo',l:'N5'},{w:'達成',f:'たっせい',m:'logro',l:'N3'},{w:'上達',f:'じょうたつ',m:'progreso',l:'N3'}]},
  { k:'集', level:'N3', meanings:['reunir','recopilar'], on:['シュウ'], kun:['あつ'],
    words:[{w:'集める',f:'あつめる',m:'recopilar',l:'N4'},{w:'集中',f:'しゅうちゅう',m:'concentración',l:'N3'},{w:'収集',f:'しゅうしゅう',m:'colección',l:'N3'}]},
  { k:'配', level:'N3', meanings:['distribuir','preocupar'], on:['ハイ'], kun:['くば'],
    words:[{w:'心配',f:'しんぱい',m:'preocupación',l:'N4'},{w:'配達',f:'はいたつ',m:'entrega',l:'N3'},{w:'分配',f:'ぶんぱい',m:'distribución',l:'N3'}]},
  { k:'様', level:'N3', meanings:['manera','señor/señora'], on:['ヨウ'], kun:['さま'],
    words:[{w:'様子',f:'ようす',m:'estado/apariencia',l:'N4'},{w:'同様',f:'どうよう',m:'de la misma manera',l:'N3'},{w:'お客様',f:'おきゃくさま',m:'cliente/huésped',l:'N3'}]},
  { k:'表', level:'N3', meanings:['tabla','expresar','exterior'], on:['ヒョウ'], kun:['おもて','あらわ'],
    words:[{w:'発表',f:'はっぴょう',m:'presentación/anuncio',l:'N4'},{w:'表現',f:'ひょうげん',m:'expresión',l:'N3'},{w:'表面',f:'ひょうめん',m:'superficie',l:'N3'}]},
  { k:'記', level:'N3', meanings:['registrar','anotar'], on:['キ'], kun:['しる'],
    words:[{w:'日記',f:'にっき',m:'diario',l:'N4'},{w:'記念',f:'きねん',m:'conmemoración',l:'N3'},{w:'記者',f:'きしゃ',m:'periodista',l:'N3'}]},
  { k:'特', level:'N3', meanings:['especial'], on:['トク'], kun:[],
    words:[{w:'特別',f:'とくべつ',m:'especial',l:'N4'},{w:'特徴',f:'とくちょう',m:'característica',l:'N3'},{w:'独特',f:'どくとく',m:'único/peculiar',l:'N3'}]},
  { k:'別', level:'N3', meanings:['separar','diferente'], on:['ベツ'], kun:['わか'],
    words:[{w:'特別',f:'とくべつ',m:'especial',l:'N4'},{w:'別々',f:'べつべつ',m:'por separado',l:'N3'},{w:'区別',f:'くべつ',m:'distinción',l:'N3'}]},
  { k:'産', level:'N3', meanings:['producir','nacer'], on:['サン'], kun:['う'],
    words:[{w:'生産',f:'せいさん',m:'producción',l:'N3'},{w:'産業',f:'さんぎょう',m:'industria',l:'N3'},{w:'出産',f:'しゅっさん',m:'parto',l:'N3'}]},
  { k:'以', level:'N3', meanings:['por medio de','a partir de'], on:['イ'], kun:[],
    words:[{w:'以上',f:'いじょう',m:'más de / al final',l:'N4'},{w:'以下',f:'いか',m:'menos de / o menos',l:'N4'},{w:'以外',f:'いがい',m:'excepto',l:'N3'}]},
  { k:'全', level:'N3', meanings:['todo','completo'], on:['ゼン'], kun:['すべ','まった'],
    words:[{w:'全部',f:'ぜんぶ',m:'todo',l:'N4'},{w:'全員',f:'ぜんいん',m:'todos los miembros',l:'N3'},{w:'完全',f:'かんぜん',m:'perfecto/completo',l:'N3'}]},
  { k:'的', level:'N3', meanings:['objetivo','(sufijo adjetival)'], on:['テキ'], kun:['まと'],
    words:[{w:'目的',f:'もくてき',m:'propósito',l:'N4'},{w:'具体的',f:'ぐたいてき',m:'concreto',l:'N3'},{w:'的確',f:'てきかく',m:'exacto/preciso',l:'N3'}]},
  { k:'次', level:'N3', meanings:['siguiente','próximo'], on:['ジ','シ'], kun:['つぎ'],
    words:[{w:'次',f:'つぎ',m:'siguiente',l:'N4'},{w:'次第',f:'しだい',m:'según/dependiendo de',l:'N3'},{w:'順次',f:'じゅんじ',m:'sucesivamente',l:'N3'}]},
  { k:'最', level:'N3', meanings:['más','el más'], on:['サイ'], kun:['もっと'],
    words:[{w:'最初',f:'さいしょ',m:'el primero',l:'N4'},{w:'最近',f:'さいきん',m:'recientemente',l:'N4'},{w:'最終',f:'さいしゅう',m:'último/final',l:'N4'}]},
  { k:'続', level:'N3', meanings:['continuar'], on:['ゾク'], kun:['つづ'],
    words:[{w:'続く',f:'つづく',m:'continuar',l:'N4'},{w:'継続',f:'けいぞく',m:'continuación',l:'N3'},{w:'手続き',f:'てつづき',m:'procedimiento',l:'N3'}]},
  { k:'変', level:'N3', meanings:['cambiar','extraño'], on:['ヘン'], kun:['か','かわ'],
    words:[{w:'変わる',f:'かわる',m:'cambiar',l:'N4'},{w:'大変',f:'たいへん',m:'difícil/muy',l:'N5'},{w:'変化',f:'へんか',m:'cambio',l:'N3'}]},
  { k:'関', level:'N3', meanings:['relacionar','barrera'], on:['カン'], kun:['せき','かか'],
    words:[{w:'関係',f:'かんけい',m:'relación',l:'N4'},{w:'関心',f:'かんしん',m:'interés',l:'N3'},{w:'玄関',f:'げんかん',m:'entrada de casa',l:'N4'}]},
  { k:'現', level:'N3', meanings:['presente','aparecer'], on:['ゲン'], kun:['あらわ'],
    words:[{w:'現在',f:'げんざい',m:'actualmente',l:'N4'},{w:'現実',f:'げんじつ',m:'realidad',l:'N3'},{w:'表現',f:'ひょうげん',m:'expresión',l:'N3'}]},
  { k:'進', level:'N3', meanings:['avanzar','progresar'], on:['シン'], kun:['すす'],
    words:[{w:'進む',f:'すすむ',m:'avanzar',l:'N4'},{w:'前進',f:'ぜんしん',m:'avance',l:'N3'},{w:'進歩',f:'しんぽ',m:'progreso',l:'N3'}]},
  { k:'通', level:'N3', meanings:['pasar','comunicar'], on:['ツウ','ツ'], kun:['とお','かよ'],
    words:[{w:'通る',f:'とおる',m:'pasar',l:'N4'},{w:'交通',f:'こうつう',m:'tráfico',l:'N4'},{w:'普通',f:'ふつう',m:'normal/ordinario',l:'N4'}]},
  { k:'得', level:'N3', meanings:['obtener','ganar'], on:['トク'], kun:['え','う'],
    words:[{w:'得る',f:'える',m:'obtener',l:'N4'},{w:'納得',f:'なっとく',m:'comprensión/convicción',l:'N3'},{w:'習得',f:'しゅうとく',m:'adquisición',l:'N3'}]},
  { k:'失', level:'N3', meanings:['perder','fallar'], on:['シツ'], kun:['うしな'],
    words:[{w:'失礼',f:'しつれい',m:'descortesía',l:'N4'},{w:'失敗',f:'しっぱい',m:'fracaso',l:'N4'},{w:'消失',f:'しょうしつ',m:'desaparición',l:'N3'}]},
  { k:'望', level:'N3', meanings:['desear','esperanza'], on:['ボウ','モウ'], kun:['のぞ'],
    words:[{w:'希望',f:'きぼう',m:'esperanza',l:'N4'},{w:'望む',f:'のぞむ',m:'desear',l:'N3'},{w:'展望',f:'てんぼう',m:'perspectiva',l:'N3'}]},
  { k:'決', level:'N3', meanings:['decidir'], on:['ケツ'], kun:['き'],
    words:[{w:'決める',f:'きめる',m:'decidir',l:'N4'},{w:'決定',f:'けってい',m:'decisión',l:'N3'},{w:'解決',f:'かいけつ',m:'solución',l:'N3'}]},
  { k:'合', level:'N3', meanings:['combinar','concordar'], on:['ゴウ','ガッ'], kun:['あ'],
    words:[{w:'場合',f:'ばあい',m:'caso/situación',l:'N4'},{w:'合格',f:'ごうかく',m:'aprobado',l:'N3'},{w:'都合',f:'つごう',m:'conveniencia',l:'N3'}]},
  { k:'問', level:'N3', meanings:['preguntar','problema'], on:['モン'], kun:['と'],
    words:[{w:'問題',f:'もんだい',m:'problema',l:'N4'},{w:'質問',f:'しつもん',m:'pregunta',l:'N4'},{w:'問い合わせ',f:'といあわせ',m:'consulta',l:'N3'}]},
  { k:'調', level:'N3', meanings:['investigar','ajustar'], on:['チョウ'], kun:['しら','ととの'],
    words:[{w:'調べる',f:'しらべる',m:'investigar',l:'N4'},{w:'調子',f:'ちょうし',m:'condición/ritmo',l:'N4'},{w:'調査',f:'ちょうさ',m:'investigación',l:'N3'}]},
  { k:'確', level:'N3', meanings:['confirmar','seguro'], on:['カク'], kun:['たし'],
    words:[{w:'確かめる',f:'たしかめる',m:'confirmar',l:'N4'},{w:'確認',f:'かくにん',m:'confirmación',l:'N3'},{w:'正確',f:'せいかく',m:'exacto/preciso',l:'N3'}]},
  { k:'能', level:'N3', meanings:['habilidad','capaz'], on:['ノウ'], kun:[],
    words:[{w:'可能',f:'かのう',m:'posible',l:'N3'},{w:'能力',f:'のうりょく',m:'capacidad',l:'N3'},{w:'機能',f:'きのう',m:'función',l:'N3'}]},
  { k:'力', level:'N3', meanings:['fuerza','poder'], on:['リョク','リキ'], kun:['ちから'],
    words:[{w:'力',f:'ちから',m:'fuerza',l:'N5'},{w:'努力',f:'どりょく',m:'esfuerzo',l:'N4'},{w:'能力',f:'のうりょく',m:'capacidad',l:'N3'}]},
  { k:'活', level:'N3', meanings:['vivir','activo'], on:['カツ'], kun:['い'],
    words:[{w:'生活',f:'せいかつ',m:'vida cotidiana',l:'N4'},{w:'活動',f:'かつどう',m:'actividad',l:'N4'},{w:'活用',f:'かつよう',m:'uso activo',l:'N3'}]},
  { k:'機', level:'N3', meanings:['máquina','oportunidad'], on:['キ'], kun:['はた'],
    words:[{w:'飛行機',f:'ひこうき',m:'avión',l:'N5'},{w:'機会',f:'きかい',m:'oportunidad',l:'N3'},{w:'機能',f:'きのう',m:'función',l:'N3'}]},
  { k:'術', level:'N3', meanings:['arte','técnica'], on:['ジュツ'], kun:[],
    words:[{w:'手術',f:'しゅじゅつ',m:'cirugía',l:'N3'},{w:'芸術',f:'げいじゅつ',m:'arte',l:'N3'},{w:'技術',f:'ぎじゅつ',m:'tecnología/técnica',l:'N3'}]},
  { k:'場', level:'N3', meanings:['lugar','escena'], on:['ジョウ','バ'], kun:['ば'],
    words:[{w:'場合',f:'ばあい',m:'caso/situación',l:'N4'},{w:'工場',f:'こうじょう',m:'fábrica',l:'N4'},{w:'広場',f:'ひろば',m:'plaza',l:'N4'}]},
  { k:'際', level:'N3', meanings:['cuando','ocasión'], on:['サイ'], kun:['きわ'],
    words:[{w:'国際',f:'こくさい',m:'internacional',l:'N4'},{w:'実際',f:'じっさい',m:'en realidad',l:'N3'},{w:'交際',f:'こうさい',m:'relación/trato',l:'N3'}]},
  { k:'困', level:'N3', meanings:['estar en apuros'], on:['コン'], kun:['こま'],
    words:[{w:'困る',f:'こまる',m:'estar en apuros',l:'N4'},{w:'困難',f:'こんなん',m:'dificultad',l:'N3'},{w:'貧困',f:'ひんこん',m:'pobreza',l:'N3'}]},
  { k:'整', level:'N3', meanings:['ordenar','arreglar'], on:['セイ'], kun:['ととの'],
    words:[{w:'整理',f:'せいり',m:'organización',l:'N3'},{w:'調整',f:'ちょうせい',m:'ajuste',l:'N3'},{w:'整備',f:'せいび',m:'mantenimiento',l:'N3'}]},

  // ── N2 ──────────────────────────────────────────────────────────────────
  { k:'愛', level:'N2', meanings:['amor','querer'], on:['アイ'], kun:['あい'],
    words:[{w:'愛情',f:'あいじょう',m:'afecto',l:'N2'},{w:'恋愛',f:'れんあい',m:'romance',l:'N2'},{w:'愛する',f:'あいする',m:'amar',l:'N2'}]},
  { k:'夢', level:'N2', meanings:['sueño'], on:['ム'], kun:['ゆめ'],
    words:[{w:'夢中',f:'むちゅう',m:'absorto/obsesionado',l:'N2'},{w:'悪夢',f:'あくむ',m:'pesadilla',l:'N2'},{w:'夢見る',f:'ゆめみる',m:'soñar',l:'N2'}]},
  { k:'笑', level:'N2', meanings:['reír','sonreír'], on:['ショウ'], kun:['わら','え'],
    words:[{w:'笑顔',f:'えがお',m:'sonrisa',l:'N2'},{w:'笑い',f:'わらい',m:'risa',l:'N2'},{w:'微笑む',f:'ほほえむ',m:'sonreír suavemente',l:'N2'}]},
  { k:'悲', level:'N2', meanings:['tristeza','lamentar'], on:['ヒ'], kun:['かなし'],
    words:[{w:'悲しみ',f:'かなしみ',m:'tristeza',l:'N2'},{w:'悲劇',f:'ひげき',m:'tragedia',l:'N2'},{w:'悲しい',f:'かなしい',m:'triste',l:'N2'}]},
  { k:'怒', level:'N2', meanings:['enojo','enfadarse'], on:['ド','ヌ'], kun:['おこ','いか'],
    words:[{w:'怒る',f:'おこる',m:'enfadarse',l:'N2'},{w:'怒り',f:'いかり',m:'ira',l:'N2'},{w:'激怒',f:'げきど',m:'furia',l:'N2'}]},

  // ── N1 ──────────────────────────────────────────────────────────────────
  { k:'魂', level:'N1', meanings:['alma','espíritu'], on:['コン'], kun:['たましい'],
    words:[{w:'霊魂',f:'れいこん',m:'espíritu/alma',l:'N1'},{w:'魂胆',f:'こんたん',m:'intención oculta',l:'N1'}]},
  { k:'誇', level:'N1', meanings:['orgullo','enorgullecerse'], on:['コ'], kun:['ほこ'],
    words:[{w:'誇り',f:'ほこり',m:'orgullo',l:'N1'},{w:'誇る',f:'ほこる',m:'enorgullecerse',l:'N1'},{w:'誇示',f:'こじ',m:'ostentación',l:'N1'}]},
  { k:'憂', level:'N1', meanings:['pena','melancolía'], on:['ユウ'], kun:['うれ'],
    words:[{w:'憂鬱',f:'ゆううつ',m:'melancolía',l:'N1'},{w:'憂い',f:'うれい',m:'tristeza profunda',l:'N1'},{w:'憂慮',f:'ゆうりょ',m:'preocupación',l:'N1'}]},
  { k:'勇', level:'N1', meanings:['valentía','coraje'], on:['ユウ'], kun:['いさ'],
    words:[{w:'勇気',f:'ゆうき',m:'valor',l:'N1'},{w:'勇者',f:'ゆうしゃ',m:'héroe valiente',l:'N1'},{w:'勇敢',f:'ゆうかん',m:'valiente',l:'N1'}]},
  { k:'奥', level:'N1', meanings:['interior','profundidad'], on:['オウ'], kun:['おく'],
    words:[{w:'奥さん',f:'おくさん',m:'esposa (respetuoso)',l:'N1'},{w:'奥深い',f:'おくふかい',m:'profundo',l:'N1'},{w:'奥底',f:'おくそこ',m:'el fondo más profundo',l:'N1'}]},
]

// Deduplicate by kanji character
const seen = new Set<string>()
export const KANJI: Kanji[] = RAW.filter(k => {
  if (seen.has(k.k)) return false
  seen.add(k.k)
  return true
})
