import type { Kanji } from './types'

// N5: 119 kanji

export const kanjiN5: Kanji[] = [
  { rank:1, k:'日', level:'N5', meanings:['sol','día'], on:['ニチ','ジツ'], kun:['ひ','か'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'今日',f:'きょう',m:'hoy',l:'N5'},{w:'毎日',f:'まいにち',m:'cada día',l:'N5'},{w:'日曜日',f:'にちようび',m:'domingo',l:'N5'},]},
  { rank:2, k:'一', level:'N5', meanings:['uno'], on:['イチ','イツ'], kun:['ひと'],
    words:[{w:'一人',f:'ひとり',m:'una persona',l:'N5'},{w:'一月',f:'いちがつ',m:'enero',l:'N5'},{w:'一番',f:'いちばん',m:'el más / número uno',l:'N5'},{w:'一度',f:'いちど',m:'una vez',l:'N5'},]},
  { rank:5, k:'人', level:'N5', meanings:['persona'], on:['ジン','ニン'], kun:['ひと'],
    words:[{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'外国人',f:'がいこくじん',m:'extranjero (persona)',l:'N5'},{w:'一人',f:'ひとり',m:'una persona / solo',l:'N5'},]},
  { rank:6, k:'年', level:'N5', meanings:['año'], on:['ネン'], kun:['とし'],
    words:[{w:'今年',f:'ことし',m:'este año',l:'N5'},{w:'来年',f:'らいねん',m:'el año que viene',l:'N5'},{w:'毎年',f:'まいとし',m:'cada año',l:'N5'},{w:'去年',f:'きょねん',m:'el año pasado',l:'N5'},{w:'新年',f:'しんねん',m:'año nuevo',l:'N5'},]},
  { rank:7, k:'大', level:'N5', meanings:['grande'], on:['ダイ','タイ'], kun:['おお'],
    words:[{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'大切',f:'たいせつ',m:'importante',l:'N5'},{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'大事',f:'だいじ',m:'importante / asunto grave',l:'N5'},]},
  { rank:8, k:'十', level:'N5', meanings:['diez'], on:['ジュウ','ジッ'], kun:['とお','と'],
    words:[{w:'十日',f:'とおか',m:'diez días / día 10',l:'N5'},{w:'十分',f:'じゅうぶん',m:'suficiente',l:'N5'},{w:'二十歳',f:'はたち',m:'veinte años',l:'N5'},]},
  { rank:9, k:'二', level:'N5', meanings:['dos'], on:['ニ'], kun:['ふた'],
    words:[{w:'二人',f:'ふたり',m:'dos personas',l:'N5'},{w:'二月',f:'にがつ',m:'febrero',l:'N5'},{w:'二十',f:'にじゅう',m:'veinte',l:'N5'}]},
  { rank:10, k:'本', level:'N5', meanings:['libro','origen'], on:['ホン'], kun:['もと'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'本当',f:'ほんとう',m:'verdad / de verdad',l:'N5'},{w:'本屋',f:'ほんや',m:'librería',l:'N5'},{w:'絵本',f:'えほん',m:'libro ilustrado',l:'N5'},]},
  { rank:11, k:'中', level:'N5', meanings:['dentro','interior','durante'], on:['チュウ'], kun:['なか'],
    words:[{w:'中学校',f:'ちゅうがっこう',m:'instituto',l:'N5'},{w:'中国',f:'ちゅうごく',m:'China',l:'N5'},{w:'中心',f:'ちゅうしん',m:'centro',l:'N4'},{w:'中央',f:'ちゅうおう',m:'centro / central',l:'N3'}]},
  { rank:12, k:'長', level:'N5', meanings:['largo','jefe'], on:['チョウ'], kun:['なが.い'],
    words:[{w:'成長',f:'せいちょう',m:'crecimiento',l:'N4'},{w:'社長',f:'しゃちょう',m:'presidente de empresa',l:'N4'},{w:'長所',f:'ちょうしょ',m:'punto fuerte',l:'N3'}]},
  { rank:13, k:'出', level:'N5', meanings:['salir','sacar'], on:['シュツ','スイ'], kun:['で.る','だ.す'],
    words:[{w:'出口',f:'でぐち',m:'salida',l:'N5'},{w:'出発',f:'しゅっぱつ',m:'partida / salida',l:'N5'},{w:'出席',f:'しゅっせき',m:'asistencia',l:'N4'},{w:'外出',f:'がいしゅつ',m:'salir / salida',l:'N4'}]},
  { rank:14, k:'三', level:'N5', meanings:['tres'], on:['サン'], kun:['み','みっ'],
    words:[{w:'三日',f:'みっか',m:'tres días / día 3',l:'N5'},{w:'三月',f:'さんがつ',m:'marzo',l:'N5'},{w:'三角',f:'さんかく',m:'triángulo',l:'N5'}]},
  { rank:16, k:'時', level:'N5', meanings:['tiempo','hora'], on:['ジ'], kun:['とき'],
    words:[{w:'時間',f:'じかん',m:'tiempo / hora',l:'N5'},{w:'何時',f:'なんじ',m:'qué hora',l:'N5'},{w:'時代',f:'じだい',m:'época / era',l:'N4'},{w:'時計',f:'とけい',m:'reloj',l:'N5'}]},
  { rank:20, k:'行', level:'N5', meanings:['ir'], on:['コウ','ギョウ'], kun:['い.く','おこな.う'],
    words:[{w:'旅行',f:'りょこう',m:'viaje',l:'N5'},{w:'銀行',f:'ぎんこう',m:'banco',l:'N5'},{w:'行動',f:'こうどう',m:'conducta / acción',l:'N3'},{w:'急行',f:'きゅうこう',m:'tren exprés',l:'N4'}]},
  { rank:22, k:'見', level:'N5', meanings:['ver','mirar','mostrar'], on:['ケン'], kun:['み.る','み.える','み.せる'],
    words:[{w:'花見',f:'はなみ',m:'contemplación de cerezos',l:'N5'},{w:'意見',f:'いけん',m:'opinión',l:'N4'},{w:'発見',f:'はっけん',m:'descubrimiento',l:'N3'}]},
  { rank:23, k:'月', level:'N5', meanings:['luna','mes'], on:['ゲツ','ガツ'], kun:['つき'],
    words:[{w:'月曜日',f:'げつようび',m:'lunes',l:'N5'},{w:'今月',f:'こんげつ',m:'este mes',l:'N5'},{w:'来月',f:'らいげつ',m:'el mes que viene',l:'N5'},{w:'一月',f:'いちがつ',m:'enero',l:'N5'},]},
  { rank:24, k:'分', level:'N5', meanings:['minuto','entender','parte'], on:['フン','ブン'], kun:['わか.る'],
    words:[{w:'半分',f:'はんぶん',m:'la mitad',l:'N5'},{w:'自分',f:'じぶん',m:'uno mismo',l:'N5'},{w:'十分',f:'じゅっぷん',m:'diez minutos',l:'N5'},]},
  { rank:29, k:'生', level:'N5', meanings:['vida','nacer'], on:['セイ','ショウ'], kun:['い.きる','う.まれる','なま'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'学生',f:'がくせい',m:'estudiante',l:'N5'},{w:'人生',f:'じんせい',m:'vida (humana)',l:'N4'},]},
  { rank:31, k:'五', level:'N5', meanings:['cinco'], on:['ゴ'], kun:['いつ'],
    words:[{w:'五日',f:'いつか',m:'cinco días / día 5',l:'N5'},{w:'五月',f:'ごがつ',m:'mayo',l:'N5'},{w:'五分',f:'ごふん',m:'cinco minutos',l:'N5'},]},
  { rank:33, k:'間', level:'N5', meanings:['intervalo','entre'], on:['カン','ケン'], kun:['あいだ','ま'],
    words:[{w:'時間',f:'じかん',m:'tiempo / hora',l:'N5'},{w:'人間',f:'にんげん',m:'ser humano',l:'N4'},{w:'期間',f:'きかん',m:'periodo',l:'N3'}]},
  { rank:35, k:'上', level:'N5', meanings:['arriba','encima'], on:['ジョウ','ショウ'], kun:['うえ','あ.がる','のぼ.る'],
    words:[{w:'上手',f:'じょうず',m:'hábil',l:'N5'},{w:'以上',f:'いじょう',m:'más de / lo anterior',l:'N4'},{w:'屋上',f:'おくじょう',m:'azotea',l:'N3'}]},
  { rank:37, k:'東', level:'N5', meanings:['este'], on:['トウ'], kun:['ひがし'],
    words:[{w:'東京',f:'とうきょう',m:'Tokio',l:'N5'},{w:'東口',f:'ひがしぐち',m:'salida este',l:'N5'},{w:'東北',f:'とうほく',m:'noreste',l:'N3'},{w:'関東',f:'かんとう',m:'región de Kanto',l:'N3'}]},
  { rank:46, k:'方', level:'N5', meanings:['dirección','persona','método'], on:['ホウ'], kun:['かた'],
    words:[{w:'使い方',f:'つかいかた',m:'manera de usar',l:'N5'},{w:'方法',f:'ほうほう',m:'método',l:'N4'},{w:'方向',f:'ほうこう',m:'dirección',l:'N4'},{w:'地方',f:'ちほう',m:'región',l:'N4'}]},
  { rank:47, k:'四', level:'N5', meanings:['cuatro'], on:['シ'], kun:['よ','よっ'],
    words:[{w:'四日',f:'よっか',m:'cuatro días / día 4',l:'N5'},{w:'四月',f:'しがつ',m:'abril',l:'N5'},{w:'四角',f:'しかく',m:'cuadrado',l:'N4'},{w:'四季',f:'しき',m:'las cuatro estaciones',l:'N3'}]},
  { rank:49, k:'今', level:'N5', meanings:['ahora'], on:['コン','キン'], kun:['いま'],
    words:[{w:'今日',f:'きょう',m:'hoy',l:'N5'},{w:'今年',f:'ことし',m:'este año',l:'N5'},{w:'今週',f:'こんしゅう',m:'esta semana',l:'N5'},{w:'今月',f:'こんげつ',m:'este mes',l:'N5'},{w:'今夜',f:'こんや',m:'esta noche',l:'N5'},]},
  { rank:51, k:'新', level:'N5', meanings:['nuevo'], on:['シン'], kun:['あたら.しい','にい'],
    words:[{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'},{w:'新年',f:'しんねん',m:'año nuevo',l:'N5'},{w:'新幹線',f:'しんかんせん',m:'tren bala',l:'N4'},{w:'新鮮',f:'しんせん',m:'fresco',l:'N3'}]},
  { rank:53, k:'金', level:'N5', meanings:['oro','dinero'], on:['キン','コン'], kun:['かね'],
    words:[{w:'金曜日',f:'きんようび',m:'viernes',l:'N5'},{w:'料金',f:'りょうきん',m:'tarifa',l:'N4'},{w:'現金',f:'げんきん',m:'efectivo',l:'N3'}]},
  { rank:55, k:'九', level:'N5', meanings:['nueve'], on:['キュウ','ク'], kun:['ここの'],
    words:[{w:'九日',f:'ここのか',m:'nueve días / día 9',l:'N5'},{w:'九月',f:'くがつ',m:'septiembre',l:'N5'},{w:'九時',f:'くじ',m:'las nueve',l:'N5'},]},
  { rank:56, k:'入', level:'N5', meanings:['entrar','meter'], on:['ニュウ'], kun:['はい.る','い.れる'],
    words:[{w:'入口',f:'いりぐち',m:'entrada',l:'N5'},{w:'入学',f:'にゅうがく',m:'ingreso a la escuela',l:'N4'},{w:'入院',f:'にゅういん',m:'hospitalización',l:'N4'},{w:'記入',f:'きにゅう',m:'rellenar / anotar',l:'N3'}]},
  { rank:58, k:'立', level:'N5', meanings:['ponerse de pie','levantarse'], on:['リツ','リュウ'], kun:['た.つ'],
    words:[{w:'国立',f:'こくりつ',m:'nacional / estatal',l:'N4'},{w:'私立',f:'しりつ',m:'privado',l:'N4'},{w:'立派',f:'りっぱ',m:'espléndido',l:'N4'},{w:'独立',f:'どくりつ',m:'independencia',l:'N3'}]},
  { rank:60, k:'手', level:'N5', meanings:['mano'], on:['シュ'], kun:['て'],
    words:[{w:'手紙',f:'てがみ',m:'carta',l:'N5'},{w:'上手',f:'じょうず',m:'hábil',l:'N5'},{w:'下手',f:'へた',m:'torpe',l:'N5'},]},
  { rank:61, k:'米', level:'N5', meanings:['arroz','EE.UU.'], on:['マイ','ベイ'], kun:['こめ'],
    words:[{w:'米国',f:'べいこく',m:'Estados Unidos',l:'N4'},{w:'白米',f:'はくまい',m:'arroz blanco',l:'N3'},{w:'新米',f:'しんまい',m:'arroz nuevo / novato',l:'N3'}]},
  { rank:62, k:'力', level:'N5', meanings:['fuerza','poder'], on:['リョク','リキ'], kun:['ちから'],
    words:[{w:'努力',f:'どりょく',m:'esfuerzo',l:'N4'},{w:'協力',f:'きょうりょく',m:'cooperación',l:'N4'},{w:'体力',f:'たいりょく',m:'fuerza física',l:'N4'},{w:'実力',f:'じつりょく',m:'capacidad real',l:'N3'}]},
  { rank:63, k:'学', level:'N5', meanings:['estudio','aprendizaje'], on:['ガク'], kun:['まな.ぶ'],
    words:[{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'学生',f:'がくせい',m:'estudiante',l:'N5'},{w:'小学校',f:'しょうがっこう',m:'escuela primaria',l:'N5'},]},
  { rank:65, k:'高', level:'N5', meanings:['alto','caro'], on:['コウ'], kun:['たか.い'],
    words:[{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},{w:'高校生',f:'こうこうせい',m:'estudiante de bachillerato',l:'N5'},{w:'最高',f:'さいこう',m:'lo máximo / genial',l:'N4'},{w:'高速',f:'こうそく',m:'alta velocidad',l:'N3'}]},
  { rank:67, k:'明', level:'N5', meanings:['brillante','claro','mañana'], on:['メイ','ミョウ'], kun:['あか.るい','あき.らか'],
    words:[{w:'明日',f:'あした',m:'mañana',l:'N5'},{w:'説明',f:'せつめい',m:'explicación',l:'N4'},{w:'証明',f:'しょうめい',m:'demostración',l:'N3'},{w:'不明',f:'ふめい',m:'desconocido',l:'N3'}]},
  { rank:69, k:'円', level:'N5', meanings:['yen','círculo'], on:['エン'], kun:['まる'],
    words:[{w:'百円',f:'ひゃくえん',m:'100 yenes',l:'N5'},{w:'千円',f:'せんえん',m:'1000 yenes',l:'N5'},{w:'円形',f:'えんけい',m:'forma circular',l:'N3'},{w:'半円',f:'はんえん',m:'semicírculo',l:'N3'}]},
  { rank:72, k:'子', level:'N5', meanings:['niño','hijo'], on:['シ','ス'], kun:['こ'],
    words:[{w:'子供',f:'こども',m:'niño',l:'N5'},{w:'様子',f:'ようす',m:'aspecto / situación',l:'N4'},{w:'男子',f:'だんし',m:'chico',l:'N4'},{w:'女子',f:'じょし',m:'chica',l:'N4'}]},
  { rank:76, k:'目', level:'N5', meanings:['ojo'], on:['モク','ボク'], kun:['め'],
    words:[{w:'目的',f:'もくてき',m:'objetivo / propósito',l:'N3'},{w:'目標',f:'もくひょう',m:'meta',l:'N3'},{w:'注目',f:'ちゅうもく',m:'atención / interés',l:'N3'}]},
  { rank:81, k:'外', level:'N5', meanings:['exterior','fuera'], on:['ガイ','ゲ'], kun:['そと','ほか'],
    words:[{w:'外国',f:'がいこく',m:'extranjero (país)',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},{w:'海外',f:'かいがい',m:'extranjero / ultramar',l:'N4'},{w:'以外',f:'いがい',m:'excepto',l:'N4'}]},
  { rank:83, k:'言', level:'N5', meanings:['decir','palabra'], on:['ゲン','ゴン'], kun:['い.う','こと'],
    words:[{w:'言葉',f:'ことば',m:'palabra / idioma',l:'N5'},{w:'方言',f:'ほうげん',m:'dialecto',l:'N3'},{w:'言語',f:'げんご',m:'lenguaje',l:'N3'}]},
  { rank:88, k:'体', level:'N5', meanings:['cuerpo'], on:['タイ','テイ'], kun:['からだ'],
    words:[{w:'体育',f:'たいいく',m:'educación física',l:'N4'},{w:'体験',f:'たいけん',m:'experiencia',l:'N4'},{w:'全体',f:'ぜんたい',m:'totalidad / conjunto',l:'N4'},]},
  { rank:90, k:'田', level:'N5', meanings:['arrozal','campo'], on:['デン'], kun:['た'],
    words:[{w:'田舎',f:'いなか',m:'campo / zona rural',l:'N4'},{w:'水田',f:'すいでん',m:'arrozal',l:'N3'},{w:'田畑',f:'たはた',m:'campos de cultivo',l:'N3'}]},
  { rank:92, k:'八', level:'N5', meanings:['ocho'], on:['ハチ'], kun:['や','やっ'],
    words:[{w:'八日',f:'ようか',m:'ocho días / día 8',l:'N5'},{w:'八月',f:'はちがつ',m:'agosto',l:'N5'},{w:'八時',f:'はちじ',m:'las ocho',l:'N5'},]},
  { rank:93, k:'六', level:'N5', meanings:['seis'], on:['ロク'], kun:['む','むっ'],
    words:[{w:'六日',f:'むいか',m:'seis días / día 6',l:'N5'},{w:'六月',f:'ろくがつ',m:'junio',l:'N5'},{w:'六時',f:'ろくじ',m:'las seis',l:'N5'},]},
  { rank:97, k:'下', level:'N5', meanings:['abajo','debajo'], on:['カ','ゲ'], kun:['した','さ.がる','くだ.る'],
    words:[{w:'下手',f:'へた',m:'torpe',l:'N5'},{w:'地下',f:'ちか',m:'subterráneo',l:'N4'},{w:'以下',f:'いか',m:'menos de / lo siguiente',l:'N4'}]},
  { rank:102, k:'来', level:'N5', meanings:['venir'], on:['ライ'], kun:['く.る','き','こ'],
    words:[{w:'来年',f:'らいねん',m:'el año que viene',l:'N5'},{w:'来週',f:'らいしゅう',m:'la semana próxima',l:'N5'},{w:'来月',f:'らいげつ',m:'el mes que viene',l:'N5'},]},
  { rank:113, k:'気', level:'N5', meanings:['espíritu','aire','ánimo'], on:['キ','ケ'], kun:[],
    words:[{w:'元気',f:'げんき',m:'saludable / animado',l:'N5'},{w:'天気',f:'てんき',m:'tiempo (meteorológico)',l:'N5'},{w:'気持ち',f:'きもち',m:'sentimiento',l:'N5'},{w:'電気',f:'でんき',m:'electricidad / luz',l:'N5'},{w:'空気',f:'くうき',m:'aire',l:'N5'},]},
  { rank:114, k:'小', level:'N5', meanings:['pequeño'], on:['ショウ'], kun:['ちい.さい','こ'],
    words:[{w:'小学校',f:'しょうがっこう',m:'escuela primaria',l:'N5'},{w:'小学生',f:'しょうがくせい',m:'alumno de primaria',l:'N5'},{w:'小説',f:'しょうせつ',m:'novela',l:'N4'},{w:'小型',f:'こがた',m:'de tamaño pequeño',l:'N3'}]},
  { rank:115, k:'七', level:'N5', meanings:['siete'], on:['シチ'], kun:['なな'],
    words:[{w:'七日',f:'なのか',m:'siete días / día 7',l:'N5'},{w:'七月',f:'しちがつ',m:'julio',l:'N5'},{w:'七時',f:'しちじ',m:'las siete',l:'N5'},]},
  { rank:131, k:'山', level:'N5', meanings:['montaña'], on:['サン'], kun:['やま'],
    words:[{w:'富士山',f:'ふじさん',m:'monte Fuji',l:'N5'},{w:'火山',f:'かざん',m:'volcán',l:'N3'},{w:'登山',f:'とざん',m:'montañismo',l:'N3'}]},
  { rank:134, k:'話', level:'N5', meanings:['hablar','historia'], on:['ワ'], kun:['はな.す','はなし'],
    words:[{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'会話',f:'かいわ',m:'conversación',l:'N4'},{w:'世話',f:'せわ',m:'cuidado / ayuda',l:'N4'},{w:'話題',f:'わだい',m:'tema de conversación',l:'N3'}]},
  { rank:139, k:'多', level:'N5', meanings:['mucho','abundante'], on:['タ'], kun:['おお.い'],
    words:[{w:'多分',f:'たぶん',m:'probablemente',l:'N5'},{w:'多数',f:'たすう',m:'gran número / mayoría',l:'N3'},{w:'多少',f:'たしょう',m:'más o menos',l:'N3'}]},
  { rank:144, k:'安', level:'N5', meanings:['barato','seguro'], on:['アン'], kun:['やす.い'],
    words:[{w:'安全',f:'あんぜん',m:'seguridad / tranquilidad',l:'N4'},{w:'安心',f:'あんしん',m:'tranquilidad',l:'N4'},{w:'安定',f:'あんてい',m:'estabilidad',l:'N3'}]},
  { rank:151, k:'女', level:'N5', meanings:['mujer','hembra'], on:['ジョ','ニョ'], kun:['おんな'],
    words:[{w:'女の人',f:'おんなのひと',m:'mujer',l:'N5'},{w:'女性',f:'じょせい',m:'mujer',l:'N4'},{w:'少女',f:'しょうじょ',m:'niña',l:'N4'}]},
  { rank:153, k:'北', level:'N5', meanings:['norte'], on:['ホク'], kun:['きた'],
    words:[{w:'北口',f:'きたぐち',m:'salida norte',l:'N5'},{w:'東北',f:'とうほく',m:'noreste / Tohoku',l:'N3'},{w:'北部',f:'ほくぶ',m:'región norte',l:'N3'}]},
  { rank:163, k:'百', level:'N5', meanings:['cien'], on:['ヒャク'], kun:[],
    words:[{w:'百円',f:'ひゃくえん',m:'100 yenes',l:'N5'},{w:'百万',f:'ひゃくまん',m:'un millón',l:'N5'},{w:'三百',f:'さんびゃく',m:'trescientos',l:'N5'},]},
  { rank:169, k:'書', level:'N5', meanings:['escribir'], on:['ショ'], kun:['か.く'],
    words:[{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'辞書',f:'じしょ',m:'diccionario',l:'N5'},{w:'書店',f:'しょてん',m:'librería (formal)',l:'N5'},]},
  { rank:173, k:'先', level:'N5', meanings:['antes','adelante','punta'], on:['セン'], kun:['さき'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'先週',f:'せんしゅう',m:'la semana pasada',l:'N5'},{w:'先月',f:'せんげつ',m:'el mes pasado',l:'N5'},]},
  { rank:177, k:'名', level:'N5', meanings:['nombre','famoso'], on:['メイ','ミョウ'], kun:['な'],
    words:[{w:'名前',f:'なまえ',m:'nombre',l:'N5'},{w:'有名',f:'ゆうめい',m:'famoso',l:'N5'},{w:'名人',f:'めいじん',m:'maestro / experto',l:'N3'},{w:'氏名',f:'しめい',m:'nombre completo',l:'N3'}]},
  { rank:181, k:'川', level:'N5', meanings:['río'], on:['セン'], kun:['かわ'],
    words:[{w:'小川',f:'おがわ',m:'arroyo',l:'N4'},{w:'川岸',f:'かわぎし',m:'ribera',l:'N3'}]},
  { rank:192, k:'元', level:'N5', meanings:['origen','comienzo','antes'], on:['ゲン','ガン'], kun:['もと'],
    words:[{w:'元気',f:'げんき',m:'energía / salud',l:'N5'},{w:'元日',f:'がんじつ',m:'día de año nuevo',l:'N4'},{w:'地元',f:'じもと',m:'local / de la zona',l:'N4'}]},
  { rank:195, k:'千', level:'N5', meanings:['mil'], on:['セン'], kun:['ち'],
    words:[{w:'千円',f:'せんえん',m:'1000 yenes',l:'N5'},{w:'三千',f:'さんぜん',m:'tres mil',l:'N5'},{w:'千葉',f:'ちば',m:'Chiba',l:'N5'},]},
  { rank:215, k:'物', level:'N5', meanings:['cosa','objeto','asunto'], on:['ブツ','モツ'], kun:['もの'],
    words:[{w:'食べ物',f:'たべもの',m:'comida',l:'N5'},{w:'飲み物',f:'のみもの',m:'bebida',l:'N5'},{w:'荷物',f:'にもつ',m:'equipaje',l:'N4'},{w:'物語',f:'ものがたり',m:'historia / cuento',l:'N4'}]},
  { rank:223, k:'水', level:'N5', meanings:['agua'], on:['スイ'], kun:['みず'],
    words:[{w:'水曜日',f:'すいようび',m:'miércoles',l:'N5'},{w:'水道',f:'すいどう',m:'agua corriente',l:'N4'},{w:'水泳',f:'すいえい',m:'natación',l:'N4'}]},
  { rank:224, k:'半', level:'N5', meanings:['mitad','medio'], on:['ハン'], kun:['なかば'],
    words:[{w:'半分',f:'はんぶん',m:'la mitad',l:'N5'},{w:'一時半',f:'いちじはん',m:'la una y media',l:'N5'},{w:'後半',f:'こうはん',m:'segunda mitad',l:'N3'},{w:'前半',f:'ぜんはん',m:'primera mitad',l:'N3'}]},
  { rank:240, k:'男', level:'N5', meanings:['hombre','varón'], on:['ダン','ナン'], kun:['おとこ'],
    words:[{w:'男の人',f:'おとこのひと',m:'hombre',l:'N5'},{w:'男性',f:'だんせい',m:'hombre',l:'N4'},{w:'長男',f:'ちょうなん',m:'hijo mayor',l:'N3'}]},
  { rank:259, k:'西', level:'N5', meanings:['oeste'], on:['セイ','サイ'], kun:['にし'],
    words:[{w:'西口',f:'にしぐち',m:'salida oeste',l:'N5'},{w:'西洋',f:'せいよう',m:'Occidente',l:'N3'},{w:'関西',f:'かんさい',m:'región de Kansai',l:'N3'}]},
  { rank:268, k:'電', level:'N5', meanings:['electricidad'], on:['デン'], kun:[],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'電気',f:'でんき',m:'electricidad / luz',l:'N5'},]},
  { rank:284, k:'口', level:'N5', meanings:['boca','entrada'], on:['コウ','ク'], kun:['くち'],
    words:[{w:'入口',f:'いりぐち',m:'entrada',l:'N5'},{w:'出口',f:'でぐち',m:'salida',l:'N5'},{w:'人口',f:'じんこう',m:'población',l:'N4'},{w:'窓口',f:'まどぐち',m:'ventanilla',l:'N3'}]},
  { rank:287, k:'少', level:'N5', meanings:['poco','joven'], on:['ショウ'], kun:['すく.ない','すこ.し'],
    words:[{w:'少年',f:'しょうねん',m:'joven / muchacho',l:'N4'},{w:'少女',f:'しょうじょ',m:'niña',l:'N4'},{w:'少数',f:'しょうすう',m:'minoría',l:'N3'}]},
  { rank:292, k:'町', level:'N5', meanings:['ciudad','barrio','manzana'], on:['チョウ'], kun:['まち'],
    words:[{w:'下町',f:'したまち',m:'barrio antiguo',l:'N4'},{w:'城下町',f:'じょうかまち',m:'ciudad-castillo',l:'N3'},{w:'町民',f:'ちょうみん',m:'vecino del pueblo',l:'N3'}]},
  { rank:294, k:'校', level:'N5', meanings:['escuela'], on:['コウ'], kun:[],
    words:[{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},{w:'校長',f:'こうちょう',m:'director de escuela',l:'N4'},{w:'転校',f:'てんこう',m:'cambio de escuela',l:'N3'}]},
  { rank:304, k:'内', level:'N5', meanings:['interior','dentro'], on:['ナイ','ダイ'], kun:['うち'],
    words:[{w:'案内',f:'あんない',m:'guía / información',l:'N4'},{w:'内容',f:'ないよう',m:'contenido',l:'N3'},{w:'国内',f:'こくない',m:'interior del país',l:'N3'}]},
  { rank:307, k:'土', level:'N5', meanings:['tierra'], on:['ド','ト'], kun:['つち'],
    words:[{w:'土曜日',f:'どようび',m:'sábado',l:'N5'},{w:'土地',f:'とち',m:'terreno',l:'N3'},{w:'国土',f:'こくど',m:'territorio nacional',l:'N3'}]},
  { rank:317, k:'木', level:'N5', meanings:['árbol','madera'], on:['モク','ボク'], kun:['き'],
    words:[{w:'木曜日',f:'もくようび',m:'jueves',l:'N5'},{w:'木材',f:'もくざい',m:'madera',l:'N3'},{w:'木造',f:'もくぞう',m:'de madera',l:'N3'}]},
  { rank:319, k:'聞', level:'N5', meanings:['escuchar','preguntar'], on:['ブン','モン'], kun:['き.く'],
    words:[{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'},{w:'新聞社',f:'しんぶんしゃ',m:'editorial de periódico',l:'N3'}]},
  { rank:328, k:'食', level:'N5', meanings:['comer','comida'], on:['ショク'], kun:['た.べる','く.う'],
    words:[{w:'食事',f:'しょくじ',m:'comida / comer',l:'N5'},{w:'食堂',f:'しょくどう',m:'comedor',l:'N4'},{w:'夕食',f:'ゆうしょく',m:'cena',l:'N4'}]},
  { rank:333, k:'車', level:'N5', meanings:['coche','vehículo'], on:['シャ'], kun:['くるま'],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},{w:'自動車',f:'じどうしゃ',m:'automóvil',l:'N4'},{w:'乗車',f:'じょうしゃ',m:'subir a un vehículo',l:'N3'}]},
  { rank:340, k:'何', level:'N5', meanings:['qué','cuánto'], on:['カ'], kun:['なに','なん'],
    words:[{w:'何時',f:'なんじ',m:'qué hora',l:'N5'},{w:'何回',f:'なんかい',m:'cuántas veces',l:'N4'},{w:'何度',f:'なんど',m:'cuántas veces / grados',l:'N4'}]},
  { rank:341, k:'南', level:'N5', meanings:['sur'], on:['ナン'], kun:['みなみ'],
    words:[{w:'南口',f:'みなみぐち',m:'salida sur',l:'N5'},{w:'南北',f:'なんぼく',m:'norte y sur',l:'N3'},{w:'東南',f:'とうなん',m:'sureste',l:'N3'}]},
  { rank:343, k:'足', level:'N5', meanings:['pie','pierna','suficiente'], on:['ソク'], kun:['あし','た.りる'],
    words:[{w:'遠足',f:'えんそく',m:'excursión',l:'N4'},{w:'不足',f:'ふそく',m:'insuficiencia',l:'N4'},{w:'満足',f:'まんぞく',m:'satisfacción',l:'N3'},{w:'手足',f:'てあし',m:'manos y pies',l:'N3'}]},
  { rank:375, k:'万', level:'N5', meanings:['diez mil'], on:['マン','バン'], kun:[],
    words:[{w:'一万円',f:'いちまんえん',m:'10.000 yenes',l:'N5'},{w:'百万',f:'ひゃくまん',m:'un millón',l:'N5'},{w:'万一',f:'まんいち',m:'por si acaso',l:'N3'}]},
  { rank:408, k:'石', level:'N5', meanings:['piedra','roca'], on:['セキ','シャク','コク'], kun:['いし'],
    words:[{w:'磁石',f:'じしゃく',m:'imán',l:'N3'},{w:'化石',f:'かせき',m:'fósil',l:'N3'},{w:'宝石',f:'ほうせき',m:'joya / gema',l:'N3'}]},
  { rank:435, k:'好', level:'N5', meanings:['gustar','afición','favorable'], on:['コウ'], kun:['この.む','す.き'],
    words:[{w:'友好',f:'ゆうこう',m:'amistad',l:'N4'},{w:'好奇心',f:'こうきしん',m:'curiosidad',l:'N3'},{w:'好物',f:'こうぶつ',m:'comida favorita',l:'N3'},{w:'好調',f:'こうちょう',m:'en buena forma',l:'N3'}]},
  { rank:485, k:'字', level:'N5', meanings:['carácter','letra'], on:['ジ'], kun:['あざ'],
    words:[{w:'漢字',f:'かんじ',m:'kanji',l:'N5'},{w:'文字',f:'もじ',m:'carácter / letra',l:'N4'},{w:'数字',f:'すうじ',m:'número',l:'N4'}]},
  { rank:491, k:'音', level:'N5', meanings:['sonido'], on:['オン','イン'], kun:['おと','ね'],
    words:[{w:'音楽',f:'おんがく',m:'música',l:'N5'},{w:'音読み',f:'おんよみ',m:'lectura on del kanji',l:'N5'},{w:'発音',f:'はつおん',m:'pronunciación',l:'N4'},{w:'音声',f:'おんせい',m:'voz / sonido',l:'N4'},]},
  { rank:504, k:'帰', level:'N5', meanings:['regresar'], on:['キ'], kun:['かえ.る'],
    words:[{w:'帰国',f:'きこく',m:'regreso al país',l:'N4'},{w:'日帰り',f:'ひがえり',m:'excursión de un día',l:'N4'},{w:'帰宅',f:'きたく',m:'volver a casa',l:'N3'}]},
  { rank:509, k:'古', level:'N5', meanings:['antiguo','viejo'], on:['コ'], kun:['ふる.い'],
    words:[{w:'中古',f:'ちゅうこ',m:'de segunda mano / usado',l:'N4'},{w:'古代',f:'こだい',m:'antigüedad',l:'N3'},{w:'古典',f:'こてん',m:'clásico',l:'N3'}]},
  { rank:511, k:'王', level:'N5', meanings:['rey','monarca'], on:['オウ'], kun:[],
    words:[{w:'王様',f:'おうさま',m:'rey',l:'N4'},{w:'王国',f:'おうこく',m:'reino',l:'N3'},{w:'女王',f:'じょおう',m:'reina',l:'N3'}]},
  { rank:520, k:'買', level:'N5', meanings:['comprar'], on:['バイ'], kun:['か.う'],
    words:[{w:'買い物',f:'かいもの',m:'compras',l:'N5'},{w:'売買',f:'ばいばい',m:'compraventa',l:'N3'}]},
  { rank:570, k:'母', level:'N5', meanings:['madre'], on:['ボ'], kun:['はは'],
    words:[{w:'母親',f:'ははおや',m:'madre',l:'N4'},{w:'祖母',f:'そぼ',m:'abuela',l:'N4'},{w:'母国',f:'ぼこく',m:'patria',l:'N3'}]},
  { rank:574, k:'火', level:'N5', meanings:['fuego'], on:['カ'], kun:['ひ'],
    words:[{w:'火曜日',f:'かようび',m:'martes',l:'N5'},{w:'火事',f:'かじ',m:'incendio',l:'N4'},{w:'花火',f:'はなび',m:'fuegos artificiales',l:'N4'}]},
  { rank:578, k:'花', level:'N5', meanings:['flor'], on:['カ'], kun:['はな'],
    words:[{w:'花見',f:'はなみ',m:'contemplación de cerezos',l:'N5'},{w:'花火',f:'はなび',m:'fuegos artificiales',l:'N4'},{w:'開花',f:'かいか',m:'floración',l:'N3'}]},
  { rank:602, k:'右', level:'N5', meanings:['derecha'], on:['ウ','ユウ'], kun:['みぎ'],
    words:[{w:'右側',f:'みぎがわ',m:'lado derecho',l:'N5'},{w:'右手',f:'みぎて',m:'mano derecha',l:'N5'},{w:'左右',f:'さゆう',m:'izquierda y derecha',l:'N3'}]},
  { rank:618, k:'読', level:'N5', meanings:['leer'], on:['ドク','トク'], kun:['よ.む'],
    words:[{w:'音読み',f:'おんよみ',m:'lectura on del kanji',l:'N5'},{w:'読書',f:'どくしょ',m:'lectura',l:'N4'},{w:'音読',f:'おんどく',m:'lectura en voz alta',l:'N3'}]},
  { rank:622, k:'友', level:'N5', meanings:['amigo'], on:['ユウ'], kun:['とも'],
    words:[{w:'友達',f:'ともだち',m:'amigo',l:'N5'},{w:'親友',f:'しんゆう',m:'mejor amigo',l:'N3'},{w:'友情',f:'ゆうじょう',m:'amistad',l:'N3'}]},
  { rank:630, k:'左', level:'N5', meanings:['izquierda'], on:['サ'], kun:['ひだり'],
    words:[{w:'左側',f:'ひだりがわ',m:'lado izquierdo',l:'N5'},{w:'左手',f:'ひだりて',m:'mano izquierda',l:'N5'},{w:'左右',f:'さゆう',m:'izquierda y derecha',l:'N3'}]},
  { rank:642, k:'休', level:'N5', meanings:['descansar','vacaciones'], on:['キュウ'], kun:['やす.む'],
    words:[{w:'夏休み',f:'なつやすみ',m:'vacaciones de verano',l:'N5'},{w:'休日',f:'きゅうじつ',m:'día festivo',l:'N4'},{w:'休憩',f:'きゅうけい',m:'descanso',l:'N3'}]},
  { rank:646, k:'父', level:'N5', meanings:['padre'], on:['フ'], kun:['ちち'],
    words:[{w:'父親',f:'ちちおや',m:'padre',l:'N4'},{w:'祖父',f:'そふ',m:'abuelo',l:'N4'},{w:'父母',f:'ふぼ',m:'padres',l:'N3'}]},
  { rank:702, k:'寺', level:'N5', meanings:['templo budista'], on:['ジ'], kun:['てら'],
    words:[{w:'寺院',f:'じいん',m:'templo budista',l:'N3'},]},
  { rank:710, k:'岩', level:'N5', meanings:['roca'], on:['ガン'], kun:['いわ'],
    words:[{w:'岩石',f:'がんせき',m:'roca / piedra',l:'N3'},]},
  { rank:765, k:'林', level:'N5', meanings:['bosque'], on:['リン'], kun:['はやし'],
    words:[{w:'山林',f:'さんりん',m:'bosque montañoso',l:'N3'},{w:'森林',f:'しんりん',m:'bosque',l:'N3'}]},
  { rank:776, k:'森', level:'N5', meanings:['bosque denso'], on:['シン'], kun:['もり'],
    words:[{w:'森林',f:'しんりん',m:'bosque / floresta',l:'N3'},]},
  { rank:858, k:'竹', level:'N5', meanings:['bambú'], on:['チク'], kun:['たけ'],
    words:[{w:'竹林',f:'ちくりん',m:'bosque de bambú',l:'N3'},]},
  { rank:911, k:'虫', level:'N5', meanings:['insecto / bicho'], on:['チュウ'], kun:['むし'],
    words:[{w:'虫歯',f:'むしば',m:'caries',l:'N3'},{w:'昆虫',f:'こんちゅう',m:'insecto',l:'N3'},{w:'害虫',f:'がいちゅう',m:'plaga / bicho dañino',l:'N3'}]},
  { rank:924, k:'夕', level:'N5', meanings:['tarde','atardecer'], on:['セキ'], kun:['ゆう'],
    words:[{w:'夕方',f:'ゆうがた',m:'tarde / atardecer',l:'N5'},{w:'夕食',f:'ゆうしょく',m:'cena',l:'N5'},{w:'夕日',f:'ゆうひ',m:'sol del atardecer',l:'N4'},{w:'夕暮れ',f:'ゆうぐれ',m:'anochecer',l:'N4'}]},
  { rank:933, k:'貝', level:'N5', meanings:['concha / marisco'], on:['カイ'], kun:['かい'],
    words:[{w:'貝殻',f:'かいがら',m:'concha / caparazón',l:'N3'},]},
  { rank:950, k:'雨', level:'N5', meanings:['lluvia'], on:['ウ'], kun:['あめ','あま'],
    words:[{w:'大雨',f:'おおあめ',m:'lluvia intensa',l:'N4'},{w:'梅雨',f:'つゆ',m:'temporada de lluvias',l:'N3'},{w:'雨天',f:'うてん',m:'día lluvioso',l:'N3'}]},
  { rank:965, k:'門', level:'N5', meanings:['puerta / entrada'], on:['モン'], kun:['かど'],
    words:[{w:'専門',f:'せんもん',m:'especialidad',l:'N3'},{w:'入門',f:'にゅうもん',m:'iniciación',l:'N3'},{w:'校門',f:'こうもん',m:'puerta de la escuela',l:'N3'}]},
  { rank:969, k:'飲', level:'N5', meanings:['beber'], on:['イン'], kun:['の.む'],
    words:[{w:'飲み物',f:'のみもの',m:'bebida',l:'N5'},{w:'飲料',f:'いんりょう',m:'bebida',l:'N3'},{w:'飲食',f:'いんしょく',m:'comida y bebida',l:'N3'}]},
  { rank:986, k:'肉', level:'N5', meanings:['carne'], on:['ニク'], kun:[],
    words:[{w:'牛肉',f:'ぎゅうにく',m:'carne de vaca',l:'N5'},{w:'筋肉',f:'きんにく',m:'músculo',l:'N3'},{w:'豚肉',f:'ぶたにく',m:'carne de cerdo',l:'N4'}]},
  { rank:1040, k:'暗', level:'N5', meanings:['oscuro'], on:['アン'], kun:['くら.い'],
    words:[{w:'暗記',f:'あんき',m:'memorización',l:'N4'},{w:'暗黒',f:'あんこく',m:'oscuridad',l:'N3'}]},
  { rank:1116, k:'茶', level:'N5', meanings:['té'], on:['チャ','サ'], kun:[],
    words:[{w:'茶色',f:'ちゃいろ',m:'color marrón',l:'N5'},{w:'紅茶',f:'こうちゃ',m:'té negro',l:'N4'},{w:'茶道',f:'さどう',m:'ceremonia del té',l:'N4'},{w:'緑茶',f:'りょくちゃ',m:'té verde',l:'N4'},{w:'喫茶店',f:'きっさてん',m:'cafetería',l:'N4'}]},
  { rank:1202, k:'牛', level:'N5', meanings:['vaca','buey'], on:['ギュウ'], kun:['うし'],
    words:[{w:'牛乳',f:'ぎゅうにゅう',m:'leche',l:'N5'},{w:'牛肉',f:'ぎゅうにく',m:'carne de vaca',l:'N5'},{w:'牛丼',f:'ぎゅうどん',m:'cuenco de arroz con carne',l:'N4'}]},
  { rank:1208, k:'魚', level:'N5', meanings:['pez','pescado'], on:['ギョ'], kun:['さかな','うお'],
    words:[{w:'金魚',f:'きんぎょ',m:'pez de colores',l:'N4'},{w:'人魚',f:'にんぎょ',m:'sirena',l:'N3'}]},
  { rank:1326, k:'犬', level:'N5', meanings:['perro'], on:['ケン'], kun:['いぬ'],
    words:[{w:'小犬',f:'こいぬ',m:'perrito / cachorro',l:'N4'},{w:'番犬',f:'ばんけん',m:'perro guardián',l:'N3'},{w:'愛犬',f:'あいけん',m:'perro querido',l:'N3'}]},
  { rank:1328, k:'耳', level:'N5', meanings:['oído / oreja'], on:['ジ'], kun:['みみ'],
    words:[{w:'耳鼻科',f:'じびか',m:'otorrinolaringología',l:'N3'},]},
  { rank:1860, k:'畑', level:'N5', meanings:['campo de cultivo'], on:[], kun:['はたけ','はた'],
    words:[{w:'田畑',f:'たはた',m:'campos de arroz y cultivo',l:'N4'},{w:'花畑',f:'はなばたけ',m:'campo de flores',l:'N3'}]},
]
