import type { Kanji } from './types'

// N2: 364 kanji

export const kanjiN2: Kanji[] = [
  { rank:623, k:'並', level:'N2', meanings:['alinearse / estar en fila'], on:['ヘイ'], kun:['なら'],
    words:[]},
  { rank:624, k:'丸', level:'N2', meanings:['círculo / redondo'], on:['ガン'], kun:['まる'],
    words:[{w:'丸い',f:'まるい',m:'redondo',l:'N4'},]},
  { rank:625, k:'久', level:'N2', meanings:['largo tiempo / duradero'], on:['キュウ'], kun:['ひさ'],
    words:[{w:'久しぶり',f:'ひさしぶり',m:'hace mucho tiempo',l:'N4'},{w:'久しい',f:'ひさしい',m:'hace mucho',l:'N3'}]},
  { rank:626, k:'乱', level:'N2', meanings:['desorden / caos'], on:['ラン'], kun:['みだ'],
    words:[]},
  { rank:627, k:'乳', level:'N2', meanings:['leche / pecho'], on:['ニュウ'], kun:['ちち'],
    words:[{w:'牛乳',f:'ぎゅうにゅう',m:'leche de vaca',l:'N5'},]},
  { rank:628, k:'乾', level:'N2', meanings:['secar / seco'], on:['カン'], kun:['かわ'],
    words:[{w:'乾杯',f:'かんぱい',m:'¡Salud! / brindis',l:'N4'},]},
  { rank:629, k:'了', level:'N2', meanings:['terminar / completar'], on:['リョウ'], kun:[],
    words:[{w:'了解',f:'りょうかい',m:'entendido / comprensión',l:'N3'},{w:'終了',f:'しゅうりょう',m:'finalización',l:'N3'}]},
  { rank:630, k:'介', level:'N2', meanings:['mediar / presentar'], on:['カイ'], kun:[],
    words:[{w:'紹介',f:'しょうかい',m:'presentación / introducción',l:'N4'},]},
  { rank:631, k:'仏', level:'N2', meanings:['Buda / Francia'], on:['ブツ'], kun:['ほとけ'],
    words:[{w:'仏教',f:'ぶっきょう',m:'budismo',l:'N3'},]},
  { rank:632, k:'令', level:'N2', meanings:['orden / mandato'], on:['レイ'], kun:[],
    words:[{w:'命令',f:'めいれい',m:'orden / mandato',l:'N3'},]},
  { rank:633, k:'仲', level:'N2', meanings:['relación / mediación'], on:['チュウ'], kun:['なか'],
    words:[{w:'仲良し',f:'なかよし',m:'amigos íntimos',l:'N4'},{w:'仲間',f:'なかま',m:'compañero / camarada',l:'N3'}]},
  { rank:634, k:'伸', level:'N2', meanings:['estirar / extender'], on:['シン'], kun:['の'],
    words:[]},
  { rank:635, k:'伺', level:'N2', meanings:['visitar / preguntar (humilde)'], on:['シ'], kun:['うかが'],
    words:[]},
  { rank:636, k:'低', level:'N2', meanings:['bajo / inferior'], on:['テイ'], kun:['ひく'],
    words:[{w:'低い',f:'ひくい',m:'bajo',l:'N5'},{w:'最低',f:'さいてい',m:'mínimo / lo peor',l:'N3'},{w:'低下',f:'ていか',m:'disminución / descenso',l:'N3'}]},
  { rank:637, k:'依', level:'N2', meanings:['depender / según'], on:['イ'], kun:['よ'],
    words:[{w:'依頼',f:'いらい',m:'solicitud / encargo',l:'N3'},]},
  { rank:638, k:'個', level:'N2', meanings:['individuo / unidad'], on:['コ'], kun:[],
    words:[{w:'個人',f:'こじん',m:'individuo / personal',l:'N3'},]},
  { rank:639, k:'倍', level:'N2', meanings:['múltiplo / doble'], on:['バイ'], kun:[],
    words:[{w:'二倍',f:'にばい',m:'el doble',l:'N3'},]},
  { rank:640, k:'停', level:'N2', meanings:['detener / parar'], on:['テイ'], kun:['と'],
    words:[{w:'バス停',f:'ばすてい',m:'parada de autobús',l:'N4'},{w:'停止',f:'ていし',m:'parada / detención',l:'N3'},{w:'停電',f:'ていでん',m:'apagón',l:'N3'}]},
  { rank:641, k:'傾', level:'N2', meanings:['inclinarse / tender a'], on:['ケイ'], kun:['かたむ'],
    words:[{w:'傾向',f:'けいこう',m:'tendencia',l:'N3'},]},
  { rank:642, k:'像', level:'N2', meanings:['imagen / estatua'], on:['ゾウ'], kun:[],
    words:[{w:'映像',f:'えいぞう',m:'imagen / video',l:'N4'},{w:'想像',f:'そうぞう',m:'imaginación',l:'N3'}]},
  { rank:643, k:'億', level:'N2', meanings:['cien millones'], on:['オク'], kun:[],
    words:[]},
  { rank:644, k:'兆', level:'N2', meanings:['billón / presagio'], on:['チョウ'], kun:['きざ'],
    words:[]},
  { rank:645, k:'児', level:'N2', meanings:['niño / infante'], on:['ジ'], kun:['こ'],
    words:[]},
  { rank:646, k:'党', level:'N2', meanings:['partido político'], on:['トウ'], kun:[],
    words:[]},
  { rank:647, k:'兵', level:'N2', meanings:['soldado / tropa'], on:['ヘイ'], kun:[],
    words:[]},
  { rank:648, k:'冊', level:'N2', meanings:['contador de libros'], on:['サツ'], kun:[],
    words:[{w:'一冊',f:'いっさつ',m:'un libro',l:'N4'},]},
  { rank:649, k:'再', level:'N2', meanings:['otra vez / re-'], on:['サイ'], kun:['ふたた'],
    words:[{w:'再び',f:'ふたたび',m:'de nuevo',l:'N3'},]},
  { rank:650, k:'凍', level:'N2', meanings:['congelar'], on:['トウ'], kun:['こお'],
    words:[]},
  { rank:651, k:'刊', level:'N2', meanings:['publicar / edición'], on:['カン'], kun:[],
    words:[{w:'週刊',f:'しゅうかん',m:'semanal',l:'N4'},]},
  { rank:652, k:'刷', level:'N2', meanings:['imprimir'], on:['サツ'], kun:['す'],
    words:[]},
  { rank:653, k:'券', level:'N2', meanings:['billete / bono'], on:['ケン'], kun:[],
    words:[]},
  { rank:654, k:'刺', level:'N2', meanings:['pinchar / tarjeta'], on:['シ'], kun:['さ'],
    words:[{w:'名刺',f:'めいし',m:'tarjeta de visita',l:'N4'},]},
  { rank:655, k:'則', level:'N2', meanings:['regla / norma'], on:['ソク'], kun:[],
    words:[{w:'規則',f:'きそく',m:'regla / norma',l:'N4'},{w:'原則',f:'げんそく',m:'principio / regla general',l:'N3'}]},
  { rank:656, k:'副', level:'N2', meanings:['vice- / secundario'], on:['フク'], kun:[],
    words:[]},
  { rank:657, k:'劇', level:'N2', meanings:['drama / teatro'], on:['ゲキ'], kun:[],
    words:[{w:'悲劇',f:'ひげき',m:'tragedia',l:'N3'},]},
  { rank:658, k:'効', level:'N2', meanings:['efecto / eficacia'], on:['コウ'], kun:['き'],
    words:[{w:'効果',f:'こうか',m:'efecto / resultado',l:'N3'},{w:'有効',f:'ゆうこう',m:'válido / efectivo',l:'N3'}]},
  { rank:659, k:'募', level:'N2', meanings:['reclutar / reunir'], on:['ボ'], kun:['つの'],
    words:[]},
  { rank:660, k:'勢', level:'N2', meanings:['fuerza / ímpetu'], on:['セイ'], kun:['いきお'],
    words:[]},
  { rank:661, k:'包', level:'N2', meanings:['envolver / empaquetar'], on:['ホウ'], kun:['つつ'],
    words:[{w:'小包',f:'こづつみ',m:'paquete postal',l:'N4'},]},
  { rank:662, k:'匹', level:'N2', meanings:['contador de animales pequeños'], on:['ヒキ'], kun:[],
    words:[{w:'一匹',f:'いっぴき',m:'un (animal pequeño)',l:'N4'},{w:'二匹',f:'にひき',m:'dos (animales)',l:'N4'}]},
  { rank:663, k:'区', level:'N2', meanings:['distrito / sección'], on:['ク'], kun:[],
    words:[{w:'地区',f:'ちく',m:'zona / distrito',l:'N3'},{w:'区別',f:'くべつ',m:'distinción / diferencia',l:'N3'}]},
  { rank:664, k:'卒', level:'N2', meanings:['graduarse / terminar'], on:['ソツ'], kun:[],
    words:[{w:'卒業',f:'そつぎょう',m:'graduación',l:'N4'},{w:'卒業式',f:'そつぎょうしき',m:'ceremonia de graduación',l:'N4'}]},
  { rank:665, k:'協', level:'N2', meanings:['cooperación'], on:['キョウ'], kun:[],
    words:[{w:'協力',f:'きょうりょく',m:'cooperación',l:'N4'},]},
  { rank:666, k:'占', level:'N2', meanings:['adivinar / ocupar'], on:['セン'], kun:['し'],
    words:[{w:'占い',f:'うらない',m:'adivinación / horóscopo',l:'N3'},]},
  { rank:667, k:'印', level:'N2', meanings:['sello / marca'], on:['イン'], kun:['しるし'],
    words:[]},
  { rank:668, k:'卵', level:'N2', meanings:['huevo'], on:['ラン'], kun:['たまご'],
    words:[{w:'卵',f:'たまご',m:'huevo',l:'N5'},{w:'卵焼き',f:'たまごやき',m:'tortilla japonesa',l:'N3'}]},
  { rank:669, k:'厚', level:'N2', meanings:['grueso / generoso'], on:['コウ'], kun:['あつ'],
    words:[{w:'厚い',f:'あつい',m:'grueso / espeso',l:'N4'},{w:'厚さ',f:'あつさ',m:'grosor',l:'N3'}]},
  { rank:670, k:'双', level:'N2', meanings:['par / ambos'], on:['ソウ'], kun:['ふた'],
    words:[{w:'双子',f:'ふたご',m:'gemelos',l:'N3'},]},
  { rank:671, k:'叫', level:'N2', meanings:['gritar'], on:['キョウ'], kun:['さけ'],
    words:[]},
  { rank:672, k:'召', level:'N2', meanings:['convocar / llamar'], on:['ショウ'], kun:['め'],
    words:[]},
  { rank:673, k:'史', level:'N2', meanings:['historia'], on:['シ'], kun:[],
    words:[{w:'歴史',f:'れきし',m:'historia',l:'N3'},]},
  { rank:674, k:'各', level:'N2', meanings:['cada / respectivo'], on:['カク'], kun:['おのおの'],
    words:[]},
  { rank:675, k:'含', level:'N2', meanings:['incluir / contener'], on:['ガン'], kun:['ふく'],
    words:[]},
  { rank:676, k:'周', level:'N2', meanings:['alrededor / perímetro'], on:['シュウ'], kun:['まわ'],
    words:[{w:'周り',f:'まわり',m:'alrededor',l:'N4'},]},
  { rank:677, k:'咲', level:'N2', meanings:['florecer'], on:[], kun:['さ'],
    words:[]},
  { rank:678, k:'喫', level:'N2', meanings:['beber / fumar'], on:['キツ'], kun:[],
    words:[{w:'喫茶店',f:'きっさてん',m:'cafetería',l:'N4'},]},
  { rank:679, k:'営', level:'N2', meanings:['gestionar / operar'], on:['エイ'], kun:['いとな'],
    words:[{w:'営業',f:'えいぎょう',m:'negocio / ventas',l:'N3'},{w:'経営',f:'けいえい',m:'gestión / administración',l:'N3'}]},
  { rank:680, k:'団', level:'N2', meanings:['grupo / organización'], on:['ダン'], kun:[],
    words:[{w:'団体',f:'だんたい',m:'grupo / organización',l:'N3'},]},
  { rank:681, k:'囲', level:'N2', meanings:['rodear / cercar'], on:['イ'], kun:['かこ'],
    words:[]},
  { rank:682, k:'固', level:'N2', meanings:['sólido / firme'], on:['コ'], kun:['かた'],
    words:[{w:'固い',f:'かたい',m:'duro / firme',l:'N3'},]},
  { rank:683, k:'圧', level:'N2', meanings:['presión'], on:['アツ'], kun:[],
    words:[]},
  { rank:684, k:'坂', level:'N2', meanings:['cuesta / pendiente'], on:['ハン'], kun:['さか'],
    words:[{w:'坂道',f:'さかみち',m:'camino en cuesta',l:'N3'},]},
  { rank:685, k:'均', level:'N2', meanings:['uniforme / equilibrio'], on:['キン'], kun:[],
    words:[{w:'平均',f:'へいきん',m:'promedio / media',l:'N3'},]},
  { rank:686, k:'型', level:'N2', meanings:['modelo / tipo'], on:['ケイ'], kun:['かた'],
    words:[{w:'型',f:'かた',m:'molde / modelo',l:'N3'},]},
  { rank:687, k:'埋', level:'N2', meanings:['enterrar / rellenar'], on:['マイ'], kun:['う'],
    words:[]},
  { rank:688, k:'城', level:'N2', meanings:['castillo'], on:['ジョウ'], kun:['しろ'],
    words:[{w:'城',f:'しろ',m:'castillo',l:'N3'},]},
  { rank:689, k:'域', level:'N2', meanings:['zona / región'], on:['イキ'], kun:[],
    words:[{w:'地域',f:'ちいき',m:'región / zona',l:'N3'},]},
  { rank:690, k:'塔', level:'N2', meanings:['torre / pagoda'], on:['トウ'], kun:[],
    words:[]},
  { rank:691, k:'塗', level:'N2', meanings:['pintar / aplicar'], on:['ト'], kun:['ぬ'],
    words:[]},
  { rank:692, k:'塩', level:'N2', meanings:['sal'], on:['エン'], kun:['しお'],
    words:[{w:'塩',f:'しお',m:'sal',l:'N5'},]},
  { rank:693, k:'境', level:'N2', meanings:['frontera / límite'], on:['キョウ'], kun:['さかい'],
    words:[{w:'環境',f:'かんきょう',m:'ambiente / entorno',l:'N3'},]},
  { rank:694, k:'央', level:'N2', meanings:['centro'], on:['オウ'], kun:[],
    words:[{w:'中央',f:'ちゅうおう',m:'centro / central',l:'N3'},]},
  { rank:695, k:'奥', level:'N2', meanings:['interior / profundidad'], on:['オウ'], kun:['おく'],
    words:[{w:'奥さん',f:'おくさん',m:'esposa (respetuoso)',l:'N4'},]},
  { rank:696, k:'姓', level:'N2', meanings:['apellido'], on:['セイ'], kun:['みょうじ'],
    words:[]},
  { rank:697, k:'委', level:'N2', meanings:['delegar / comité'], on:['イ'], kun:[],
    words:[{w:'委員',f:'いいん',m:'miembro de comité',l:'N3'},{w:'委員会',f:'いいんかい',m:'comité',l:'N3'}]},
  { rank:698, k:'季', level:'N2', meanings:['estación / período'], on:['キ'], kun:[],
    words:[{w:'季節',f:'きせつ',m:'estación del año',l:'N4'},{w:'四季',f:'しき',m:'las cuatro estaciones',l:'N4'}]},
  { rank:699, k:'孫', level:'N2', meanings:['nieto'], on:['ソン'], kun:['まご'],
    words:[{w:'孫',f:'まご',m:'nieto',l:'N3'},]},
  { rank:700, k:'宇', level:'N2', meanings:['universo / alero'], on:['ウ'], kun:[],
    words:[{w:'宇宙',f:'うちゅう',m:'universo / espacio',l:'N3'},{w:'宇宙人',f:'うちゅうじん',m:'extraterrestre',l:'N3'}]},
  { rank:701, k:'宝', level:'N2', meanings:['tesoro'], on:['ホウ'], kun:['たから'],
    words:[{w:'宝物',f:'たからもの',m:'tesoro',l:'N3'},]},
  { rank:702, k:'寺', level:'N2', meanings:['templo budista'], on:['ジ'], kun:['てら'],
    words:[{w:'お寺',f:'おてら',m:'templo budista',l:'N4'},]},
  { rank:703, k:'封', level:'N2', meanings:['sellar / sobre'], on:['フウ'], kun:['ふう'],
    words:[{w:'封筒',f:'ふうとう',m:'sobre (correo)',l:'N3'},]},
  { rank:704, k:'専', level:'N2', meanings:['especializado / exclusivo'], on:['セン'], kun:['もっぱ'],
    words:[{w:'専門',f:'せんもん',m:'especialidad',l:'N3'},]},
  { rank:705, k:'将', level:'N2', meanings:['general / futuro'], on:['ショウ'], kun:[],
    words:[{w:'将来',f:'しょうらい',m:'futuro',l:'N4'},]},
  { rank:706, k:'尊', level:'N2', meanings:['respetar / valioso'], on:['ソン'], kun:[],
    words:[]},
  { rank:707, k:'導', level:'N2', meanings:['guiar / liderar'], on:['ドウ'], kun:['みちび'],
    words:[]},
  { rank:708, k:'届', level:'N2', meanings:['llegar / entregar'], on:[], kun:['とど'],
    words:[]},
  { rank:709, k:'層', level:'N2', meanings:['capa / estrato'], on:['ソウ'], kun:[],
    words:[]},
  { rank:710, k:'岩', level:'N2', meanings:['roca'], on:['ガン'], kun:['いわ'],
    words:[{w:'岩',f:'いわ',m:'roca',l:'N4'},]},
  { rank:711, k:'岸', level:'N2', meanings:['orilla / costa'], on:['ガン'], kun:['きし'],
    words:[{w:'海岸',f:'かいがん',m:'costa / playa',l:'N4'},{w:'川岸',f:'かわぎし',m:'orilla del río',l:'N4'},{w:'岸',f:'きし',m:'orilla',l:'N3'}]},
  { rank:712, k:'島', level:'N2', meanings:['isla'], on:['トウ'], kun:['しま'],
    words:[{w:'島',f:'しま',m:'isla',l:'N4'},]},
  { rank:713, k:'州', level:'N2', meanings:['estado / provincia'], on:['シュウ'], kun:['す'],
    words:[{w:'九州',f:'きゅうしゅう',m:'Kyushu',l:'N4'},]},
  { rank:714, k:'巨', level:'N2', meanings:['enorme / gigante'], on:['キョ'], kun:[],
    words:[]},
  { rank:715, k:'巻', level:'N2', meanings:['enrollar / volumen'], on:['カン'], kun:['ま'],
    words:[]},
  { rank:716, k:'布', level:'N2', meanings:['tela / difundir'], on:['フ'], kun:['ぬの'],
    words:[{w:'財布',f:'さいふ',m:'cartera / billetera',l:'N5'},{w:'布団',f:'ふとん',m:'futón / edredón',l:'N4'},{w:'布',f:'ぬの',m:'tela / tejido',l:'N3'}]},
  { rank:717, k:'希', level:'N2', meanings:['raro / esperanza'], on:['キ'], kun:['まれ'],
    words:[{w:'希望',f:'きぼう',m:'esperanza / deseo',l:'N4'},]},
  { rank:718, k:'帯', level:'N2', meanings:['cinturón / zona'], on:['タイ'], kun:['お'],
    words:[{w:'帯',f:'おび',m:'cinturón (kimono)',l:'N3'},]},
  { rank:719, k:'帽', level:'N2', meanings:['sombrero / gorra'], on:['ボウ'], kun:[],
    words:[{w:'帽子',f:'ぼうし',m:'sombrero',l:'N5'},]},
  { rank:720, k:'幅', level:'N2', meanings:['anchura / margen'], on:['フク'], kun:['はば'],
    words:[{w:'幅',f:'はば',m:'anchura',l:'N3'},]},
  { rank:721, k:'干', level:'N2', meanings:['secar / intervenir'], on:['カン'], kun:['ほ'],
    words:[]},
  { rank:722, k:'幼', level:'N2', meanings:['infancia / joven'], on:['ヨウ'], kun:['おさな'],
    words:[{w:'幼稚園',f:'ようちえん',m:'jardín de infancia',l:'N4'},{w:'幼い',f:'おさない',m:'pequeño / infantil',l:'N3'}]},
  { rank:723, k:'庁', level:'N2', meanings:['agencia gubernamental'], on:['チョウ'], kun:[],
    words:[{w:'官庁',f:'かんちょう',m:'agencia del gobierno',l:'N3'},]},
  { rank:724, k:'床', level:'N2', meanings:['suelo / cama'], on:['ショウ'], kun:['ゆか'],
    words:[{w:'床',f:'ゆか',m:'suelo / piso',l:'N3'},{w:'床屋',f:'とこや',m:'barbería',l:'N3'}]},
  { rank:725, k:'底', level:'N2', meanings:['fondo / base'], on:['テイ'], kun:['そこ'],
    words:[{w:'底',f:'そこ',m:'fondo / parte inferior',l:'N3'},]},
  { rank:726, k:'府', level:'N2', meanings:['prefectura / sede'], on:['フ'], kun:[],
    words:[{w:'政府',f:'せいふ',m:'gobierno',l:'N3'},]},
  { rank:727, k:'庫', level:'N2', meanings:['almacén / depósito'], on:['コ'], kun:[],
    words:[]},
  { rank:728, k:'延', level:'N2', meanings:['extenderse / posponer'], on:['エン'], kun:['の'],
    words:[{w:'延期',f:'えんき',m:'aplazamiento',l:'N3'},]},
  { rank:729, k:'律', level:'N2', meanings:['ley / ritmo'], on:['リツ'], kun:[],
    words:[{w:'法律',f:'ほうりつ',m:'ley',l:'N3'},]},
  { rank:730, k:'復', level:'N2', meanings:['regresar / recuperarse'], on:['フク'], kun:[],
    words:[{w:'復習',f:'ふくしゅう',m:'repaso',l:'N4'},{w:'回復',f:'かいふく',m:'recuperación',l:'N3'}]},
  { rank:731, k:'快', level:'N2', meanings:['agradable / veloz'], on:['カイ'], kun:['こころよ'],
    words:[{w:'快適',f:'かいてき',m:'cómodo / agradable',l:'N3'},]},
  { rank:732, k:'恋', level:'N2', meanings:['amor romántico'], on:['レン'], kun:['こい'],
    words:[{w:'恋人',f:'こいびと',m:'pareja / novio/a',l:'N4'},{w:'恋愛',f:'れんあい',m:'amor romántico',l:'N3'},{w:'失恋',f:'しつれん',m:'desamor',l:'N3'}]},
  { rank:733, k:'患', level:'N2', meanings:['padecer (enfermedad)'], on:['カン'], kun:['わずら'],
    words:[{w:'患者',f:'かんじゃ',m:'paciente',l:'N3'},]},
  { rank:734, k:'悩', level:'N2', meanings:['preocuparse / angustia'], on:['ノウ'], kun:['なや'],
    words:[{w:'悩み',f:'なやみ',m:'preocupación / angustia',l:'N3'},]},
  { rank:735, k:'憎', level:'N2', meanings:['odiar / detestar'], on:['ゾウ'], kun:['にく'],
    words:[{w:'憎しみ',f:'にくしみ',m:'odio',l:'N3'},]},
  { rank:736, k:'戸', level:'N2', meanings:['puerta / hogar'], on:['コ'], kun:['と'],
    words:[{w:'戸',f:'と',m:'puerta / hoja de puerta',l:'N3'},{w:'戸棚',f:'とだな',m:'armario / alacena',l:'N3'}]},
  { rank:737, k:'承', level:'N2', meanings:['aceptar / recibir'], on:['ショウ'], kun:[],
    words:[{w:'承知',f:'しょうち',m:'entendido / conformidad',l:'N3'},]},
  { rank:738, k:'技', level:'N2', meanings:['habilidad / técnica'], on:['ギ'], kun:['わざ'],
    words:[{w:'技術',f:'ぎじゅつ',m:'tecnología / técnica',l:'N3'},]},
  { rank:739, k:'担', level:'N2', meanings:['cargar / encargarse'], on:['タン'], kun:['かつ'],
    words:[{w:'担当',f:'たんとう',m:'encargado / responsable',l:'N3'},{w:'負担',f:'ふたん',m:'carga / responsabilidad',l:'N3'}]},
  { rank:740, k:'拝', level:'N2', meanings:['venerar / (humilde)'], on:['ハイ'], kun:['おが'],
    words:[]},
  { rank:741, k:'拾', level:'N2', meanings:['recoger / diez'], on:['ジュウ'], kun:['ひろ'],
    words:[{w:'拾い物',f:'ひろいもの',m:'objeto encontrado',l:'N3'},]},
  { rank:742, k:'挟', level:'N2', meanings:['atrapar entre / intercalar'], on:['キョウ'], kun:['はさ'],
    words:[]},
  { rank:743, k:'捜', level:'N2', meanings:['buscar / investigar'], on:['ソウ'], kun:['さが'],
    words:[]},
  { rank:744, k:'捨', level:'N2', meanings:['tirar / abandonar'], on:['シャ'], kun:['す'],
    words:[]},
  { rank:745, k:'掃', level:'N2', meanings:['barrer / limpiar'], on:['ソウ'], kun:['は'],
    words:[{w:'掃除',f:'そうじ',m:'limpieza',l:'N5'},{w:'掃除機',f:'そうじき',m:'aspiradora',l:'N3'}]},
  { rank:746, k:'掘', level:'N2', meanings:['excavar / cavar'], on:['クツ'], kun:['ほ'],
    words:[]},
  { rank:747, k:'採', level:'N2', meanings:['recoger / adoptar'], on:['サイ'], kun:['と'],
    words:[]},
  { rank:748, k:'接', level:'N2', meanings:['conectar / contactar'], on:['セツ'], kun:['つ'],
    words:[{w:'直接',f:'ちょくせつ',m:'directo / directamente',l:'N4'},]},
  { rank:749, k:'換', level:'N2', meanings:['intercambiar / cambiar'], on:['カン'], kun:['か'],
    words:[{w:'交換',f:'こうかん',m:'intercambio',l:'N3'},{w:'換気',f:'かんき',m:'ventilación',l:'N3'}]},
  { rank:750, k:'損', level:'N2', meanings:['dañar / pérdida'], on:['ソン'], kun:['そこ'],
    words:[]},
  { rank:751, k:'改', level:'N2', meanings:['reformar / cambiar'], on:['カイ'], kun:['あらた'],
    words:[]},
  { rank:752, k:'敬', level:'N2', meanings:['respetar'], on:['ケイ'], kun:['うやま'],
    words:[{w:'敬語',f:'けいご',m:'lenguaje honorífico',l:'N3'},]},
  { rank:753, k:'旧', level:'N2', meanings:['antiguo / anterior'], on:['キュウ'], kun:['ふる'],
    words:[]},
  { rank:754, k:'昇', level:'N2', meanings:['ascender / subir'], on:['ショウ'], kun:['のぼ'],
    words:[{w:'上昇',f:'じょうしょう',m:'ascenso / subida',l:'N3'},]},
  { rank:755, k:'星', level:'N2', meanings:['estrella'], on:['セイ'], kun:['ほし'],
    words:[{w:'星',f:'ほし',m:'estrella',l:'N5'},{w:'星座',f:'せいざ',m:'constelación',l:'N3'}]},
  { rank:756, k:'普', level:'N2', meanings:['general / común'], on:['フ'], kun:[],
    words:[{w:'普通',f:'ふつう',m:'normal / ordinario',l:'N4'},{w:'普段',f:'ふだん',m:'habitualmente',l:'N3'}]},
  { rank:757, k:'暴', level:'N2', meanings:['violencia / revelar'], on:['ボウ'], kun:['あば'],
    words:[]},
  { rank:758, k:'曇', level:'N2', meanings:['nublado'], on:['ドン'], kun:['くも'],
    words:[{w:'曇り',f:'くもり',m:'nublado',l:'N5'},]},
  { rank:759, k:'替', level:'N2', meanings:['sustituir / cambiar'], on:['タイ'], kun:['か'],
    words:[{w:'着替え',f:'きがえ',m:'ropa de repuesto / cambiarse',l:'N4'},{w:'両替',f:'りょうがえ',m:'cambio de moneda',l:'N3'}]},
  { rank:760, k:'札', level:'N2', meanings:['billete / etiqueta'], on:['サツ'], kun:['ふだ'],
    words:[{w:'お札',f:'おさつ',m:'billete (dinero)',l:'N4'},]},
  { rank:761, k:'机', level:'N2', meanings:['escritorio'], on:['キ'], kun:['つくえ'],
    words:[{w:'机',f:'つくえ',m:'escritorio',l:'N5'},]},
  { rank:762, k:'材', level:'N2', meanings:['material / madera'], on:['ザイ'], kun:[],
    words:[{w:'材料',f:'ざいりょう',m:'material / ingrediente',l:'N4'},{w:'木材',f:'もくざい',m:'madera',l:'N4'}]},
  { rank:763, k:'村', level:'N2', meanings:['pueblo / aldea'], on:['ソン'], kun:['むら'],
    words:[{w:'村',f:'むら',m:'pueblo / aldea',l:'N4'},]},
  { rank:764, k:'板', level:'N2', meanings:['tablón / tabla'], on:['ハン'], kun:['いた'],
    words:[{w:'黒板',f:'こくばん',m:'pizarra',l:'N5'},{w:'板',f:'いた',m:'tabla / tablón',l:'N3'},{w:'看板',f:'かんばん',m:'letrero / cartel',l:'N3'}]},
  { rank:765, k:'林', level:'N2', meanings:['bosque'], on:['リン'], kun:['はやし'],
    words:[{w:'林',f:'はやし',m:'bosque pequeño',l:'N4'},]},
  { rank:766, k:'枚', level:'N2', meanings:['contador de hojas finas'], on:['マイ'], kun:[],
    words:[{w:'一枚',f:'いちまい',m:'una hoja / una pieza',l:'N5'},{w:'何枚',f:'なんまい',m:'cuántas hojas',l:'N4'}]},
  { rank:767, k:'枝', level:'N2', meanings:['rama'], on:['シ'], kun:['えだ'],
    words:[{w:'枝',f:'えだ',m:'rama',l:'N3'},]},
  { rank:768, k:'枯', level:'N2', meanings:['marchitarse / seco'], on:['コ'], kun:['か'],
    words:[]},
  { rank:769, k:'柔', level:'N2', meanings:['suave / flexible'], on:['ジュウ'], kun:['やわ'],
    words:[{w:'柔道',f:'じゅうどう',m:'judo',l:'N4'},{w:'柔らかい',f:'やわらかい',m:'suave / blando',l:'N3'}]},
  { rank:770, k:'柱', level:'N2', meanings:['pilar / columna'], on:['チュウ'], kun:['はしら'],
    words:[{w:'柱',f:'はしら',m:'pilar',l:'N3'},{w:'電柱',f:'でんちゅう',m:'poste eléctrico',l:'N3'}]},
  { rank:771, k:'査', level:'N2', meanings:['investigar / examinar'], on:['サ'], kun:[],
    words:[{w:'調査',f:'ちょうさ',m:'investigación',l:'N3'},]},
  { rank:772, k:'栄', level:'N2', meanings:['prosperar / gloria'], on:['エイ'], kun:['さか'],
    words:[{w:'栄養',f:'えいよう',m:'nutrición',l:'N3'},]},
  { rank:773, k:'根', level:'N2', meanings:['raíz'], on:['コン'], kun:['ね'],
    words:[{w:'根',f:'ね',m:'raíz',l:'N3'},]},
  { rank:774, k:'械', level:'N2', meanings:['maquinaria'], on:['カイ'], kun:[],
    words:[{w:'機械',f:'きかい',m:'máquina / maquinaria',l:'N3'},]},
  { rank:775, k:'棒', level:'N2', meanings:['bastón / palo'], on:['ボウ'], kun:[],
    words:[{w:'棒',f:'ぼう',m:'palo / bastón',l:'N3'},]},
  { rank:776, k:'森', level:'N2', meanings:['bosque denso'], on:['シン'], kun:['もり'],
    words:[{w:'森',f:'もり',m:'bosque',l:'N4'},]},
  { rank:777, k:'植', level:'N2', meanings:['plantar'], on:['ショク'], kun:['う'],
    words:[{w:'植物',f:'しょくぶつ',m:'planta',l:'N4'},]},
  { rank:778, k:'極', level:'N2', meanings:['extremo / polo'], on:['キョク'], kun:['きわ'],
    words:[{w:'南極',f:'なんきょく',m:'Antártida / polo sur',l:'N3'},{w:'積極的',f:'せっきょくてき',m:'activo / positivo',l:'N3'}]},
  { rank:779, k:'橋', level:'N2', meanings:['puente'], on:['キョウ'], kun:['はし'],
    words:[{w:'橋',f:'はし',m:'puente',l:'N4'},]},
  { rank:780, k:'欧', level:'N2', meanings:['Europa'], on:['オウ'], kun:[],
    words:[]},
  { rank:781, k:'武', level:'N2', meanings:['militar / marcial'], on:['ブ'], kun:[],
    words:[]},
  { rank:782, k:'歴', level:'N2', meanings:['historia / trayectoria'], on:['レキ'], kun:[],
    words:[{w:'歴史',f:'れきし',m:'historia',l:'N3'},]},
  { rank:783, k:'殿', level:'N2', meanings:['señor / palacio'], on:['デン'], kun:['との'],
    words:[]},
  { rank:784, k:'毒', level:'N2', meanings:['veneno'], on:['ドク'], kun:[],
    words:[{w:'毒',f:'どく',m:'veneno',l:'N3'},]},
  { rank:785, k:'比', level:'N2', meanings:['comparar / proporción'], on:['ヒ'], kun:['くら'],
    words:[]},
  { rank:786, k:'毛', level:'N2', meanings:['pelo / vello'], on:['モウ'], kun:['け'],
    words:[{w:'毛',f:'け',m:'pelo / vello',l:'N5'},{w:'毛布',f:'もうふ',m:'manta',l:'N3'}]},
  { rank:787, k:'氷', level:'N2', meanings:['hielo'], on:['ヒョウ'], kun:['こおり'],
    words:[{w:'氷',f:'こおり',m:'hielo',l:'N4'},]},
  { rank:788, k:'永', level:'N2', meanings:['eterno / permanente'], on:['エイ'], kun:['なが'],
    words:[{w:'永遠',f:'えいえん',m:'eterno',l:'N3'},]},
  { rank:789, k:'汗', level:'N2', meanings:['sudor'], on:['カン'], kun:['あせ'],
    words:[{w:'汗',f:'あせ',m:'sudor',l:'N3'},{w:'汗をかく',f:'あせをかく',m:'sudar',l:'N3'}]},
  { rank:790, k:'汚', level:'N2', meanings:['ensuciar / contaminar'], on:['オ'], kun:['よご'],
    words:[{w:'汚い',f:'きたない',m:'sucio',l:'N4'},]},
  { rank:791, k:'池', level:'N2', meanings:['estanque'], on:['チ'], kun:['いけ'],
    words:[{w:'池',f:'いけ',m:'estanque',l:'N5'},{w:'電池',f:'でんち',m:'batería / pila',l:'N4'}]},
  { rank:792, k:'沈', level:'N2', meanings:['hundir / sumergir'], on:['チン'], kun:['しず'],
    words:[]},
  { rank:793, k:'河', level:'N2', meanings:['río'], on:['カ'], kun:['かわ'],
    words:[{w:'河川',f:'かせん',m:'ríos',l:'N4'},]},
  { rank:794, k:'沸', level:'N2', meanings:['hervir'], on:['フツ'], kun:['わ'],
    words:[]},
  { rank:795, k:'油', level:'N2', meanings:['aceite / petróleo'], on:['ユ'], kun:['あぶら'],
    words:[{w:'油',f:'あぶら',m:'aceite / grasa',l:'N4'},]},
  { rank:796, k:'況', level:'N2', meanings:['situación / circunstancia'], on:['キョウ'], kun:[],
    words:[]},
  { rank:797, k:'泉', level:'N2', meanings:['manantial / fuente'], on:['セン'], kun:['いずみ'],
    words:[{w:'温泉',f:'おんせん',m:'aguas termales',l:'N4'},]},
  { rank:798, k:'泊', level:'N2', meanings:['alojarse / pernoctar'], on:['ハク'], kun:['と'],
    words:[{w:'一泊',f:'いっぱく',m:'una noche',l:'N3'},{w:'宿泊',f:'しゅくはく',m:'alojamiento',l:'N3'}]},
  { rank:799, k:'波', level:'N2', meanings:['ola / onda'], on:['ハ'], kun:['なみ'],
    words:[{w:'波',f:'なみ',m:'ola',l:'N3'},]},
  { rank:800, k:'泥', level:'N2', meanings:['barro / lodo'], on:['デイ'], kun:['どろ'],
    words:[{w:'泥',f:'どろ',m:'barro / lodo',l:'N3'},{w:'泥棒',f:'どろぼう',m:'ladrón',l:'N3'}]},
  { rank:801, k:'浅', level:'N2', meanings:['poco profundo / superficial'], on:['セン'], kun:['あさ'],
    words:[{w:'浅い',f:'あさい',m:'poco profundo',l:'N3'},]},
  { rank:802, k:'浴', level:'N2', meanings:['bañarse'], on:['ヨク'], kun:['あ'],
    words:[{w:'入浴',f:'にゅうよく',m:'baño / bañarse',l:'N3'},]},
  { rank:803, k:'涙', level:'N2', meanings:['lágrima'], on:['ルイ'], kun:['なみだ'],
    words:[{w:'涙',f:'なみだ',m:'lágrima',l:'N3'},]},
  { rank:804, k:'液', level:'N2', meanings:['líquido / fluido'], on:['エキ'], kun:[],
    words:[]},
  { rank:805, k:'涼', level:'N2', meanings:['fresco / refrescante'], on:['リョウ'], kun:['すず'],
    words:[{w:'涼しい',f:'すずしい',m:'fresco / agradable',l:'N4'},]},
  { rank:806, k:'混', level:'N2', meanings:['mezclar'], on:['コン'], kun:['ま'],
    words:[{w:'混雑',f:'こんざつ',m:'aglomeración / congestión',l:'N3'},]},
  { rank:807, k:'清', level:'N2', meanings:['limpio / puro'], on:['セイ'], kun:['きよ'],
    words:[{w:'清潔',f:'せいけつ',m:'limpieza / higiene',l:'N3'},]},
  { rank:808, k:'減', level:'N2', meanings:['disminuir / reducir'], on:['ゲン'], kun:['へ'],
    words:[]},
  { rank:809, k:'温', level:'N2', meanings:['temperatura / tibio'], on:['オン'], kun:['あたた'],
    words:[{w:'温度',f:'おんど',m:'temperatura',l:'N4'},{w:'温泉',f:'おんせん',m:'aguas termales',l:'N4'},{w:'気温',f:'きおん',m:'temperatura del aire',l:'N3'}]},
  { rank:810, k:'測', level:'N2', meanings:['medir'], on:['ソク'], kun:['はか'],
    words:[]},
  { rank:811, k:'湖', level:'N2', meanings:['lago'], on:['コ'], kun:['みずうみ'],
    words:[{w:'湖',f:'みずうみ',m:'lago',l:'N4'},]},
  { rank:812, k:'湯', level:'N2', meanings:['agua caliente'], on:['トウ'], kun:['ゆ'],
    words:[{w:'お湯',f:'おゆ',m:'agua caliente',l:'N5'},{w:'湯船',f:'ゆぶね',m:'bañera',l:'N3'}]},
  { rank:813, k:'湾', level:'N2', meanings:['bahía'], on:['ワン'], kun:[],
    words:[]},
  { rank:814, k:'湿', level:'N2', meanings:['húmedo'], on:['シツ'], kun:['しめ'],
    words:[]},
  { rank:815, k:'準', level:'N2', meanings:['estándar / nivel'], on:['ジュン'], kun:[],
    words:[{w:'準備',f:'じゅんび',m:'preparación',l:'N4'},]},
  { rank:816, k:'溶', level:'N2', meanings:['disolver / fundir'], on:['ヨウ'], kun:['と'],
    words:[]},
  { rank:817, k:'滴', level:'N2', meanings:['gota'], on:['テキ'], kun:['しずく'],
    words:[]},
  { rank:818, k:'漁', level:'N2', meanings:['pesca'], on:['ギョ'], kun:['りょう'],
    words:[]},
  { rank:819, k:'濃', level:'N2', meanings:['denso / concentrado'], on:['ノウ'], kun:['こ'],
    words:[{w:'濃い',f:'こい',m:'denso / espeso',l:'N3'},]},
  { rank:820, k:'濯', level:'N2', meanings:['lavar / enjuagar'], on:['タク'], kun:['すす'],
    words:[{w:'洗濯',f:'せんたく',m:'lavado / colada',l:'N4'},{w:'洗濯機',f:'せんたくき',m:'lavadora',l:'N4'},{w:'洗濯物',f:'せんたくもの',m:'ropa para lavar',l:'N3'}]},
  { rank:821, k:'灯', level:'N2', meanings:['lámpara / luz'], on:['トウ'], kun:['ひ'],
    words:[]},
  { rank:822, k:'灰', level:'N2', meanings:['ceniza'], on:['カイ'], kun:['はい'],
    words:[{w:'灰',f:'はい',m:'ceniza',l:'N3'},{w:'灰色',f:'はいいろ',m:'gris',l:'N3'}]},
  { rank:823, k:'炭', level:'N2', meanings:['carbón'], on:['タン'], kun:['すみ'],
    words:[]},
  { rank:824, k:'無', level:'N2', meanings:['nada / sin'], on:['ム'], kun:['な'],
    words:[{w:'無理',f:'むり',m:'imposible / excesivo',l:'N4'},{w:'無料',f:'むりょう',m:'gratis',l:'N4'},{w:'無駄',f:'むだ',m:'desperdicio / inútil',l:'N3'}]},
  { rank:825, k:'焼', level:'N2', meanings:['quemar / asar'], on:['ショウ'], kun:['や'],
    words:[{w:'焼き肉',f:'やきにく',m:'carne a la parrilla',l:'N4'},]},
  { rank:826, k:'照', level:'N2', meanings:['iluminar / comparar'], on:['ショウ'], kun:['て'],
    words:[]},
  { rank:827, k:'燃', level:'N2', meanings:['arder / quemar'], on:['ネン'], kun:['も'],
    words:[]},
  { rank:828, k:'燥', level:'N2', meanings:['seco / árido'], on:['ソウ'], kun:[],
    words:[]},
  { rank:829, k:'爆', level:'N2', meanings:['explotar'], on:['バク'], kun:[],
    words:[]},
  { rank:830, k:'片', level:'N2', meanings:['fragmento / un lado'], on:['ヘン'], kun:['かた'],
    words:[{w:'片方',f:'かたほう',m:'un lado / uno de los dos',l:'N3'},]},
  { rank:831, k:'版', level:'N2', meanings:['versión / edición'], on:['ハン'], kun:[],
    words:[]},
  { rank:832, k:'玉', level:'N2', meanings:['bola / joya'], on:['ギョク'], kun:['たま'],
    words:[{w:'玉',f:'たま',m:'bola / joya',l:'N4'},]},
  { rank:833, k:'珍', level:'N2', meanings:['raro / precioso'], on:['チン'], kun:['めずら'],
    words:[{w:'珍しい',f:'めずらしい',m:'raro / inusual',l:'N3'},]},
  { rank:834, k:'瓶', level:'N2', meanings:['botella / frasco'], on:['ビン'], kun:[],
    words:[{w:'瓶',f:'びん',m:'botella',l:'N3'},{w:'花瓶',f:'かびん',m:'jarrón / florero',l:'N3'}]},
  { rank:835, k:'甘', level:'N2', meanings:['dulce / indulgente'], on:['カン'], kun:['あま'],
    words:[{w:'甘い',f:'あまい',m:'dulce',l:'N4'},]},
  { rank:836, k:'畜', level:'N2', meanings:['ganado / bestia'], on:['チク'], kun:[],
    words:[]},
  { rank:837, k:'略', level:'N2', meanings:['abreviación / estrategia'], on:['リャク'], kun:[],
    words:[{w:'略',f:'りゃく',m:'abreviación',l:'N3'},{w:'戦略',f:'せんりゃく',m:'estrategia',l:'N3'}]},
  { rank:838, k:'畳', level:'N2', meanings:['tatami / doblar'], on:['ジョウ'], kun:['たた'],
    words:[{w:'畳',f:'たたみ',m:'tatami',l:'N3'},]},
  { rank:839, k:'療', level:'N2', meanings:['tratamiento médico'], on:['リョウ'], kun:[],
    words:[{w:'医療',f:'いりょう',m:'atención médica',l:'N4'},{w:'治療',f:'ちりょう',m:'tratamiento médico',l:'N3'}]},
  { rank:840, k:'皮', level:'N2', meanings:['piel / corteza'], on:['ヒ'], kun:['かわ'],
    words:[{w:'皮',f:'かわ',m:'piel / corteza',l:'N3'},]},
  { rank:841, k:'皿', level:'N2', meanings:['plato / bandeja'], on:[], kun:['さら'],
    words:[{w:'皿',f:'さら',m:'plato',l:'N4'},{w:'皿洗い',f:'さらあらい',m:'lavar platos',l:'N3'}]},
  { rank:842, k:'省', level:'N2', meanings:['ministerio / ahorrar'], on:['ショウ'], kun:['はぶ'],
    words:[{w:'反省',f:'はんせい',m:'reflexión / arrepentimiento',l:'N3'},]},
  { rank:843, k:'県', level:'N2', meanings:['prefectura'], on:['ケン'], kun:[],
    words:[{w:'県',f:'けん',m:'prefectura',l:'N4'},]},
  { rank:844, k:'短', level:'N2', meanings:['corto / breve'], on:['タン'], kun:['みじか'],
    words:[{w:'短い',f:'みじかい',m:'corto',l:'N5'},{w:'短所',f:'たんしょ',m:'defecto / punto débil',l:'N3'}]},
  { rank:845, k:'砂', level:'N2', meanings:['arena'], on:['サ'], kun:['すな'],
    words:[{w:'砂糖',f:'さとう',m:'azúcar',l:'N4'},{w:'砂',f:'すな',m:'arena',l:'N3'}]},
  { rank:846, k:'硬', level:'N2', meanings:['duro / rígido'], on:['コウ'], kun:['かた'],
    words:[{w:'硬い',f:'かたい',m:'duro / rígido',l:'N3'},]},
  { rank:847, k:'磨', level:'N2', meanings:['pulir / cepillar'], on:['マ'], kun:['みが'],
    words:[{w:'歯磨き',f:'はみがき',m:'cepillado dental',l:'N4'},]},
  { rank:848, k:'祈', level:'N2', meanings:['rezar / desear'], on:['キ'], kun:['いの'],
    words:[{w:'祈り',f:'いのり',m:'oración / deseo',l:'N3'},]},
  { rank:849, k:'祝', level:'N2', meanings:['celebrar / felicitar'], on:['シュク'], kun:['いわ'],
    words:[{w:'お祝い',f:'おいわい',m:'felicitación / celebración',l:'N4'},{w:'祝日',f:'しゅくじつ',m:'día festivo',l:'N4'}]},
  { rank:850, k:'祭', level:'N2', meanings:['festival / celebrar'], on:['サイ'], kun:['まつ'],
    words:[{w:'お祭り',f:'おまつり',m:'festival',l:'N4'},{w:'祭日',f:'さいじつ',m:'día festivo',l:'N3'}]},
  { rank:851, k:'禁', level:'N2', meanings:['prohibir'], on:['キン'], kun:[],
    words:[{w:'禁止',f:'きんし',m:'prohibición',l:'N4'},{w:'禁煙',f:'きんえん',m:'no fumar',l:'N4'}]},
  { rank:852, k:'秒', level:'N2', meanings:['segundo (tiempo)'], on:['ビョウ'], kun:[],
    words:[{w:'秒',f:'びょう',m:'segundo',l:'N4'},{w:'数秒',f:'すうびょう',m:'unos segundos',l:'N3'}]},
  { rank:853, k:'移', level:'N2', meanings:['trasladar / mudar'], on:['イ'], kun:['うつ'],
    words:[{w:'移動',f:'いどう',m:'movimiento / desplazamiento',l:'N3'},]},
  { rank:854, k:'税', level:'N2', meanings:['impuesto'], on:['ゼイ'], kun:[],
    words:[{w:'消費税',f:'しょうひぜい',m:'impuesto sobre el consumo',l:'N3'},{w:'税金',f:'ぜいきん',m:'impuesto',l:'N3'}]},
  { rank:855, k:'章', level:'N2', meanings:['capítulo / sección'], on:['ショウ'], kun:[],
    words:[{w:'文章',f:'ぶんしょう',m:'texto / redacción',l:'N3'},]},
  { rank:856, k:'童', level:'N2', meanings:['niño / infantil'], on:['ドウ'], kun:['わらべ'],
    words:[{w:'童話',f:'どうわ',m:'cuento infantil',l:'N4'},]},
  { rank:857, k:'競', level:'N2', meanings:['competir'], on:['キョウ'], kun:['きそ'],
    words:[{w:'競争',f:'きょうそう',m:'competencia',l:'N3'},]},
  { rank:858, k:'竹', level:'N2', meanings:['bambú'], on:['チク'], kun:['たけ'],
    words:[{w:'竹',f:'たけ',m:'bambú',l:'N4'},]},
  { rank:859, k:'符', level:'N2', meanings:['símbolo / billete'], on:['フ'], kun:[],
    words:[{w:'切符',f:'きっぷ',m:'billete (tren)',l:'N5'},]},
  { rank:860, k:'筆', level:'N2', meanings:['pincel / escritura'], on:['ヒツ'], kun:['ふで'],
    words:[{w:'鉛筆',f:'えんぴつ',m:'lápiz',l:'N5'},]},
  { rank:861, k:'筒', level:'N2', meanings:['tubo / cilindro'], on:['トウ'], kun:['つつ'],
    words:[{w:'封筒',f:'ふうとう',m:'sobre (correo)',l:'N3'},{w:'水筒',f:'すいとう',m:'cantimplora',l:'N3'}]},
  { rank:862, k:'算', level:'N2', meanings:['calcular / aritmética'], on:['サン'], kun:[],
    words:[{w:'算数',f:'さんすう',m:'aritmética',l:'N4'},{w:'計算',f:'けいさん',m:'cálculo',l:'N4'},{w:'予算',f:'よさん',m:'presupuesto',l:'N3'}]},
  { rank:863, k:'管', level:'N2', meanings:['tubo / gestionar'], on:['カン'], kun:['くだ'],
    words:[{w:'管理',f:'かんり',m:'gestión / administración',l:'N4'},]},
  { rank:864, k:'築', level:'N2', meanings:['construir / edificar'], on:['チク'], kun:['きず'],
    words:[{w:'建築',f:'けんちく',m:'arquitectura / construcción',l:'N3'},]},
  { rank:865, k:'簡', level:'N2', meanings:['simple / sencillo'], on:['カン'], kun:[],
    words:[{w:'簡単',f:'かんたん',m:'fácil / simple',l:'N5'},]},
  { rank:866, k:'籍', level:'N2', meanings:['registro / libro'], on:['セキ'], kun:[],
    words:[]},
  { rank:867, k:'粉', level:'N2', meanings:['polvo / harina'], on:['フン'], kun:['こな'],
    words:[{w:'粉',f:'こな',m:'polvo / harina',l:'N3'},{w:'花粉',f:'かふん',m:'polen',l:'N3'}]},
  { rank:868, k:'粒', level:'N2', meanings:['grano / partícula'], on:['リュウ'], kun:['つぶ'],
    words:[{w:'粒',f:'つぶ',m:'grano / partícula',l:'N3'},]},
  { rank:869, k:'糸', level:'N2', meanings:['hilo'], on:['シ'], kun:['いと'],
    words:[{w:'糸',f:'いと',m:'hilo',l:'N4'},{w:'毛糸',f:'けいと',m:'hilo de lana',l:'N3'}]},
  { rank:870, k:'紅', level:'N2', meanings:['rojo escarlata'], on:['コウ'], kun:['べに'],
    words:[{w:'紅茶',f:'こうちゃ',m:'té negro',l:'N4'},{w:'紅葉',f:'こうよう',m:'hojas otoñales',l:'N3'}]},
  { rank:871, k:'純', level:'N2', meanings:['puro / simple'], on:['ジュン'], kun:[],
    words:[{w:'単純',f:'たんじゅん',m:'simple',l:'N3'},]},
  { rank:872, k:'細', level:'N2', meanings:['fino / delgado / detalle'], on:['サイ'], kun:['こま'],
    words:[{w:'細かい',f:'こまかい',m:'fino / detallado',l:'N3'},]},
  { rank:873, k:'紹', level:'N2', meanings:['presentar'], on:['ショウ'], kun:[],
    words:[{w:'紹介',f:'しょうかい',m:'presentación / introducción',l:'N4'},{w:'自己紹介',f:'じこしょうかい',m:'autopresentación',l:'N3'}]},
  { rank:874, k:'絡', level:'N2', meanings:['conectar / enredar'], on:['ラク'], kun:['から'],
    words:[{w:'連絡',f:'れんらく',m:'contacto / comunicación',l:'N4'},]},
  { rank:875, k:'綿', level:'N2', meanings:['algodón'], on:['メン'], kun:['わた'],
    words:[{w:'綿',f:'わた',m:'algodón / relleno',l:'N3'},{w:'木綿',f:'もめん',m:'algodón',l:'N3'}]},
  { rank:876, k:'総', level:'N2', meanings:['total / general'], on:['ソウ'], kun:[],
    words:[]},
  { rank:877, k:'緑', level:'N2', meanings:['verde'], on:['リョク'], kun:['みどり'],
    words:[{w:'緑',f:'みどり',m:'verde',l:'N5'},{w:'緑茶',f:'りょくちゃ',m:'té verde',l:'N4'}]},
  { rank:878, k:'線', level:'N2', meanings:['línea / ruta'], on:['セン'], kun:[],
    words:[{w:'線',f:'せん',m:'línea',l:'N4'},{w:'路線',f:'ろせん',m:'ruta / línea de transporte',l:'N3'}]},
  { rank:879, k:'編', level:'N2', meanings:['tejer / editar'], on:['ヘン'], kun:['あ'],
    words:[]},
  { rank:880, k:'績', level:'N2', meanings:['logro / mérito'], on:['セキ'], kun:[],
    words:[{w:'成績',f:'せいせき',m:'resultados / calificaciones',l:'N3'},]},
  { rank:881, k:'缶', level:'N2', meanings:['lata'], on:['カン'], kun:[],
    words:[{w:'缶',f:'かん',m:'lata',l:'N3'},{w:'缶詰',f:'かんづめ',m:'conservas',l:'N3'}]},
  { rank:882, k:'署', level:'N2', meanings:['oficina / firmar'], on:['ショ'], kun:[],
    words:[]},
  { rank:883, k:'群', level:'N2', meanings:['grupo / manada'], on:['グン'], kun:['む'],
    words:[{w:'群れ',f:'むれ',m:'manada / grupo',l:'N3'},]},
  { rank:884, k:'羽', level:'N2', meanings:['pluma / ala'], on:['ウ'], kun:['はね'],
    words:[{w:'羽',f:'はね',m:'pluma / ala',l:'N4'},{w:'羽根',f:'はね',m:'pluma / paleta',l:'N3'}]},
  { rank:885, k:'翌', level:'N2', meanings:['al día siguiente'], on:['ヨク'], kun:[],
    words:[{w:'翌日',f:'よくじつ',m:'al día siguiente',l:'N3'},]},
  { rank:886, k:'耕', level:'N2', meanings:['cultivar / labrar'], on:['コウ'], kun:['たがや'],
    words:[]},
  { rank:887, k:'肌', level:'N2', meanings:['piel / tez'], on:[], kun:['はだ'],
    words:[{w:'肌',f:'はだ',m:'piel / tez',l:'N3'},{w:'肌着',f:'はだぎ',m:'ropa interior',l:'N3'}]},
  { rank:888, k:'肩', level:'N2', meanings:['hombro'], on:[], kun:['かた'],
    words:[{w:'肩',f:'かた',m:'hombro',l:'N4'},{w:'肩こり',f:'かたこり',m:'tensión en el hombro',l:'N3'}]},
  { rank:889, k:'肯', level:'N2', meanings:['asentir / afirmar'], on:['コウ'], kun:[],
    words:[]},
  { rank:890, k:'胃', level:'N2', meanings:['estómago'], on:['イ'], kun:[],
    words:[{w:'胃',f:'い',m:'estómago',l:'N4'},]},
  { rank:891, k:'胸', level:'N2', meanings:['pecho / corazón'], on:['キョウ'], kun:['むね'],
    words:[{w:'胸',f:'むね',m:'pecho',l:'N4'},]},
  { rank:892, k:'脂', level:'N2', meanings:['grasa / sebo'], on:['シ'], kun:['あぶら'],
    words:[]},
  { rank:893, k:'脳', level:'N2', meanings:['cerebro'], on:['ノウ'], kun:[],
    words:[{w:'脳',f:'のう',m:'cerebro',l:'N3'},]},
  { rank:894, k:'腕', level:'N2', meanings:['brazo'], on:['ワン'], kun:['うで'],
    words:[{w:'腕',f:'うで',m:'brazo',l:'N4'},{w:'腕時計',f:'うでどけい',m:'reloj de pulsera',l:'N4'}]},
  { rank:895, k:'腰', level:'N2', meanings:['cintura / caderas'], on:['ヨウ'], kun:['こし'],
    words:[{w:'腰',f:'こし',m:'cintura / caderas',l:'N4'},]},
  { rank:896, k:'膚', level:'N2', meanings:['piel / dermis'], on:['フ'], kun:['はだ'],
    words:[]},
  { rank:897, k:'臓', level:'N2', meanings:['órgano interno'], on:['ゾウ'], kun:[],
    words:[]},
  { rank:898, k:'臣', level:'N2', meanings:['vasallo / ministro'], on:['シン'], kun:[],
    words:[]},
  { rank:899, k:'舟', level:'N2', meanings:['barca / barco pequeño'], on:['シュウ'], kun:['ふね'],
    words:[{w:'舟',f:'ふね',m:'barca',l:'N3'},]},
  { rank:900, k:'航', level:'N2', meanings:['navegar'], on:['コウ'], kun:[],
    words:[{w:'航空',f:'こうくう',m:'aviación',l:'N4'},{w:'航海',f:'こうかい',m:'navegación',l:'N3'}]},
  { rank:901, k:'般', level:'N2', meanings:['general / clase'], on:['ハン'], kun:[],
    words:[{w:'一般',f:'いっぱん',m:'en general',l:'N3'},]},
  { rank:902, k:'芸', level:'N2', meanings:['arte / habilidad'], on:['ゲイ'], kun:[],
    words:[{w:'芸術',f:'げいじゅつ',m:'arte',l:'N3'},]},
  { rank:903, k:'荒', level:'N2', meanings:['salvaje / rugoso'], on:['コウ'], kun:['あら'],
    words:[{w:'荒い',f:'あらい',m:'brusco / rugoso',l:'N3'},]},
  { rank:904, k:'荷', level:'N2', meanings:['carga / equipaje'], on:['カ'], kun:['に'],
    words:[{w:'荷物',f:'にもつ',m:'equipaje / carga',l:'N4'},]},
  { rank:905, k:'菓', level:'N2', meanings:['dulce / confitería'], on:['カ'], kun:[],
    words:[{w:'菓子',f:'かし',m:'dulce / confite',l:'N4'},{w:'和菓子',f:'わがし',m:'dulce japonés',l:'N3'}]},
  { rank:906, k:'菜', level:'N2', meanings:['verdura'], on:['サイ'], kun:['な'],
    words:[{w:'野菜',f:'やさい',m:'verdura',l:'N5'},]},
  { rank:907, k:'著', level:'N2', meanings:['notable / autor'], on:['チョ'], kun:['いちじる'],
    words:[]},
  { rank:908, k:'蒸', level:'N2', meanings:['vapor / cocinar al vapor'], on:['ジョウ'], kun:['む'],
    words:[]},
  { rank:909, k:'蔵', level:'N2', meanings:['almacén / depósito'], on:['ゾウ'], kun:['くら'],
    words:[{w:'冷蔵庫',f:'れいぞうこ',m:'refrigerador',l:'N4'},]},
  { rank:910, k:'薄', level:'N2', meanings:['fino / tenue'], on:['ハク'], kun:['うす'],
    words:[{w:'薄い',f:'うすい',m:'delgado / fino',l:'N3'},]},
  { rank:911, k:'虫', level:'N2', meanings:['insecto / bicho'], on:['チュウ'], kun:['むし'],
    words:[{w:'虫',f:'むし',m:'insecto',l:'N5'},{w:'虫歯',f:'むしば',m:'caries',l:'N3'}]},
  { rank:912, k:'血', level:'N2', meanings:['sangre'], on:['ケツ'], kun:['ち'],
    words:[{w:'血',f:'ち',m:'sangre',l:'N4'},]},
  { rank:913, k:'衣', level:'N2', meanings:['ropa / vestido'], on:['イ'], kun:['ころも'],
    words:[]},
  { rank:914, k:'袋', level:'N2', meanings:['bolsa'], on:['タイ'], kun:['ふくろ'],
    words:[{w:'袋',f:'ふくろ',m:'bolsa',l:'N4'},{w:'手袋',f:'てぶくろ',m:'guantes',l:'N4'},{w:'ゴミ袋',f:'ごみぶくろ',m:'bolsa de basura',l:'N3'}]},
  { rank:915, k:'被', level:'N2', meanings:['sufrir / recibir'], on:['ヒ'], kun:['こうむ'],
    words:[{w:'被害',f:'ひがい',m:'daño / perjuicio',l:'N3'},]},
  { rank:916, k:'装', level:'N2', meanings:['vestir / equipar'], on:['ソウ'], kun:['よそお'],
    words:[{w:'服装',f:'ふくそう',m:'vestimenta',l:'N4'},{w:'装置',f:'そうち',m:'dispositivo / equipo',l:'N3'}]},
  { rank:917, k:'裏', level:'N2', meanings:['reverso / interior'], on:['リ'], kun:['うら'],
    words:[{w:'裏',f:'うら',m:'reverso / interior',l:'N3'},{w:'裏口',f:'うらぐち',m:'puerta trasera',l:'N3'}]},
  { rank:918, k:'補', level:'N2', meanings:['suplementar / compensar'], on:['ホ'], kun:['おぎな'],
    words:[{w:'候補',f:'こうほ',m:'candidato',l:'N3'},]},
  { rank:919, k:'複', level:'N2', meanings:['múltiple / duplicado'], on:['フク'], kun:[],
    words:[{w:'複雑',f:'ふくざつ',m:'complejo / complicado',l:'N3'},]},
  { rank:920, k:'角', level:'N2', meanings:['ángulo / esquina'], on:['カク'], kun:['かど'],
    words:[{w:'三角',f:'さんかく',m:'triángulo',l:'N5'},{w:'角',f:'かど',m:'esquina',l:'N4'}]},
  { rank:921, k:'触', level:'N2', meanings:['tocar'], on:['ショク'], kun:['さわ'],
    words:[]},
  { rank:922, k:'訓', level:'N2', meanings:['lectura kun / instrucción'], on:['クン'], kun:[],
    words:[{w:'訓練',f:'くんれん',m:'entrenamiento',l:'N4'},]},
  { rank:923, k:'設', level:'N2', meanings:['establecer / instalar'], on:['セツ'], kun:['もう'],
    words:[{w:'設備',f:'せつび',m:'instalaciones',l:'N3'},{w:'建設',f:'けんせつ',m:'construcción',l:'N3'}]},
  { rank:924, k:'詞', level:'N2', meanings:['palabra / letra'], on:['シ'], kun:[],
    words:[{w:'歌詞',f:'かし',m:'letra de canción',l:'N4'},]},
  { rank:925, k:'詰', level:'N2', meanings:['apretar / llenar'], on:['キツ'], kun:['つ'],
    words:[{w:'缶詰',f:'かんづめ',m:'conservas',l:'N3'},]},
  { rank:926, k:'誌', level:'N2', meanings:['revista / registro'], on:['シ'], kun:[],
    words:[{w:'雑誌',f:'ざっし',m:'revista',l:'N4'},]},
  { rank:927, k:'課', level:'N2', meanings:['sección / lección'], on:['カ'], kun:[],
    words:[{w:'課題',f:'かだい',m:'tarea / problema',l:'N3'},]},
  { rank:928, k:'諸', level:'N2', meanings:['varios / muchos'], on:['ショ'], kun:[],
    words:[]},
  { rank:929, k:'講', level:'N2', meanings:['conferencia / clase'], on:['コウ'], kun:[],
    words:[]},
  { rank:930, k:'谷', level:'N2', meanings:['valle'], on:['コク'], kun:['たに'],
    words:[{w:'谷',f:'たに',m:'valle',l:'N4'},]},
  { rank:931, k:'豊', level:'N2', meanings:['abundante / rico'], on:['ホウ'], kun:['ゆた'],
    words:[{w:'豊か',f:'ゆたか',m:'abundante / próspero',l:'N3'},{w:'豊富',f:'ほうふ',m:'abundante',l:'N3'}]},
  { rank:932, k:'象', level:'N2', meanings:['elefante / fenómeno'], on:['ショウ'], kun:['ぞう'],
    words:[{w:'象',f:'ぞう',m:'elefante',l:'N4'},]},
  { rank:933, k:'貝', level:'N2', meanings:['concha / marisco'], on:['カイ'], kun:['かい'],
    words:[{w:'貝',f:'かい',m:'concha',l:'N4'},]},
  { rank:934, k:'貨', level:'N2', meanings:['mercancía / moneda'], on:['カ'], kun:[],
    words:[]},
  { rank:935, k:'販', level:'N2', meanings:['vender'], on:['ハン'], kun:[],
    words:[{w:'販売',f:'はんばい',m:'venta',l:'N4'},{w:'自動販売機',f:'じどうはんばいき',m:'máquina expendedora',l:'N3'}]},
  { rank:936, k:'貯', level:'N2', meanings:['ahorrar / almacenar'], on:['チョ'], kun:['た'],
    words:[{w:'貯金',f:'ちょきん',m:'ahorro',l:'N4'},]},
  { rank:937, k:'貿', level:'N2', meanings:['comercio'], on:['ボウ'], kun:[],
    words:[{w:'貿易',f:'ぼうえき',m:'comercio exterior',l:'N3'},]},
  { rank:938, k:'賞', level:'N2', meanings:['premio / apreciar'], on:['ショウ'], kun:[],
    words:[{w:'賞',f:'しょう',m:'premio',l:'N3'},]},
  { rank:939, k:'賢', level:'N2', meanings:['inteligente / sabio'], on:['ケン'], kun:['かしこ'],
    words:[{w:'賢い',f:'かしこい',m:'inteligente / listo',l:'N3'},]},
  { rank:940, k:'贈', level:'N2', meanings:['regalar'], on:['ゾウ'], kun:['おく'],
    words:[{w:'贈り物',f:'おくりもの',m:'regalo',l:'N3'},]},
  { rank:941, k:'超', level:'N2', meanings:['superar / extra'], on:['チョウ'], kun:['こ'],
    words:[]},
  { rank:942, k:'跡', level:'N2', meanings:['rastro / vestigio'], on:['セキ'], kun:['あと'],
    words:[{w:'跡',f:'あと',m:'rastro / huella',l:'N3'},{w:'足跡',f:'あしあと',m:'huella / pisada',l:'N3'}]},
  { rank:943, k:'踊', level:'N2', meanings:['bailar'], on:['ヨウ'], kun:['おど'],
    words:[{w:'踊り',f:'おどり',m:'baile / danza',l:'N3'},]},
  { rank:944, k:'軍', level:'N2', meanings:['ejército / militar'], on:['グン'], kun:[],
    words:[]},
  { rank:945, k:'軒', level:'N2', meanings:['alero / contador de casas'], on:['ケン'], kun:['のき'],
    words:[{w:'一軒',f:'いっけん',m:'una casa',l:'N4'},]},
  { rank:946, k:'軟', level:'N2', meanings:['blando / suave'], on:['ナン'], kun:['やわ'],
    words:[{w:'軟らかい',f:'やわらかい',m:'blando / suave',l:'N3'},]},
  { rank:947, k:'輪', level:'N2', meanings:['rueda / círculo'], on:['リン'], kun:['わ'],
    words:[{w:'輪',f:'わ',m:'rueda / aro',l:'N3'},{w:'指輪',f:'ゆびわ',m:'anillo',l:'N3'}]},
  { rank:948, k:'輸', level:'N2', meanings:['transportar'], on:['ユ'], kun:[],
    words:[{w:'輸入',f:'ゆにゅう',m:'importación',l:'N4'},{w:'輸出',f:'ゆしゅつ',m:'exportación',l:'N3'}]},
  { rank:949, k:'辛', level:'N2', meanings:['picante / duro'], on:['シン'], kun:['から'],
    words:[{w:'辛い',f:'からい',m:'picante',l:'N4'}]},
  { rank:950, k:'農', level:'N2', meanings:['agricultura'], on:['ノウ'], kun:[],
    words:[{w:'農業',f:'のうぎょう',m:'agricultura',l:'N3'},{w:'農家',f:'のうか',m:'familia campesina / granja',l:'N3'}]},
  { rank:951, k:'辺', level:'N2', meanings:['alrededor / zona'], on:['ヘン'], kun:['あた'],
    words:[{w:'辺り',f:'あたり',m:'alrededor / zona',l:'N3'},{w:'海辺',f:'うみべ',m:'orilla del mar',l:'N3'}]},
  { rank:952, k:'述', level:'N2', meanings:['describir / exponer'], on:['ジュツ'], kun:['の'],
    words:[]},
  { rank:953, k:'逆', level:'N2', meanings:['inverso / opuesto'], on:['ギャク'], kun:['さか'],
    words:[{w:'逆',f:'さか',m:'inverso / opuesto',l:'N3'},{w:'逆に',f:'ぎゃくに',m:'al contrario',l:'N3'}]},
  { rank:954, k:'造', level:'N2', meanings:['fabricar / crear'], on:['ゾウ'], kun:['つく'],
    words:[]},
  { rank:955, k:'郊', level:'N2', meanings:['suburbio / afueras'], on:['コウ'], kun:[],
    words:[]},
  { rank:956, k:'郵', level:'N2', meanings:['correo postal'], on:['ユウ'], kun:[],
    words:[{w:'郵便局',f:'ゆうびんきょく',m:'oficina de correos',l:'N5'},{w:'郵便',f:'ゆうびん',m:'correo postal',l:'N4'},{w:'郵送',f:'ゆうそう',m:'envío postal',l:'N4'}]},
  { rank:957, k:'量', level:'N2', meanings:['cantidad / medir'], on:['リョウ'], kun:['はか'],
    words:[{w:'量',f:'りょう',m:'cantidad',l:'N3'},]},
  { rank:958, k:'針', level:'N2', meanings:['aguja / manecilla'], on:['シン'], kun:['はり'],
    words:[{w:'針',f:'はり',m:'aguja',l:'N3'},]},
  { rank:959, k:'鈍', level:'N2', meanings:['embotado / lento'], on:['ドン'], kun:['にぶ'],
    words:[]},
  { rank:960, k:'鉄', level:'N2', meanings:['hierro / férreo'], on:['テツ'], kun:[],
    words:[{w:'地下鉄',f:'ちかてつ',m:'metro',l:'N4'},{w:'鉄道',f:'てつどう',m:'ferrocarril',l:'N3'}]},
  { rank:961, k:'鉱', level:'N2', meanings:['mineral / mina'], on:['コウ'], kun:[],
    words:[]},
  { rank:962, k:'銅', level:'N2', meanings:['cobre'], on:['ドウ'], kun:[],
    words:[]},
  { rank:963, k:'鋭', level:'N2', meanings:['agudo / afilado'], on:['エイ'], kun:['するど'],
    words:[]},
  { rank:964, k:'録', level:'N2', meanings:['registrar / grabar'], on:['ロク'], kun:[],
    words:[{w:'記録',f:'きろく',m:'registro / récord',l:'N3'},{w:'登録',f:'とうろく',m:'registro / inscripción',l:'N3'}]},
  { rank:965, k:'門', level:'N2', meanings:['puerta / entrada'], on:['モン'], kun:['かど'],
    words:[{w:'門',f:'もん',m:'puerta',l:'N4'},{w:'専門',f:'せんもん',m:'especialidad',l:'N3'}]},
  { rank:966, k:'防', level:'N2', meanings:['defender / prevenir'], on:['ボウ'], kun:['ふせ'],
    words:[]},
  { rank:967, k:'陸', level:'N2', meanings:['tierra firme'], on:['リク'], kun:[],
    words:[{w:'陸',f:'りく',m:'tierra firme',l:'N3'},]},
  { rank:968, k:'隅', level:'N2', meanings:['rincón / esquina'], on:['グウ'], kun:['すみ'],
    words:[{w:'隅',f:'すみ',m:'rincón / esquina',l:'N3'},]},
  { rank:969, k:'階', level:'N2', meanings:['piso / escalera'], on:['カイ'], kun:[],
    words:[{w:'一階',f:'いっかい',m:'primer piso',l:'N5'},{w:'階段',f:'かいだん',m:'escalera',l:'N4'}]},
  { rank:970, k:'隻', level:'N2', meanings:['contador de embarcaciones'], on:['セキ'], kun:[],
    words:[]},
  { rank:971, k:'雇', level:'N2', meanings:['emplear / contratar'], on:['コ'], kun:['やと'],
    words:[]},
  { rank:972, k:'雲', level:'N2', meanings:['nube'], on:['ウン'], kun:['くも'],
    words:[{w:'雲',f:'くも',m:'nube',l:'N5'},]},
  { rank:973, k:'零', level:'N2', meanings:['cero / verter'], on:['レイ'], kun:['こぼ'],
    words:[]},
  { rank:974, k:'震', level:'N2', meanings:['temblar / terremoto'], on:['シン'], kun:['ふる'],
    words:[{w:'地震',f:'じしん',m:'terremoto',l:'N4'},]},
  { rank:975, k:'革', level:'N2', meanings:['cuero / reforma'], on:['カク'], kun:['かわ'],
    words:[]},
  { rank:976, k:'順', level:'N2', meanings:['orden / turno'], on:['ジュン'], kun:[],
    words:[{w:'順番',f:'じゅんばん',m:'turno / orden',l:'N3'},]},
  { rank:977, k:'預', level:'N2', meanings:['depositar / encomendar'], on:['ヨ'], kun:['あず'],
    words:[]},
  { rank:978, k:'領', level:'N2', meanings:['territorio / dominio'], on:['リョウ'], kun:[],
    words:[]},
  { rank:979, k:'額', level:'N2', meanings:['frente / importe'], on:['ガク'], kun:['ひたい'],
    words:[{w:'金額',f:'きんがく',m:'importe monetario',l:'N4'},]},
  { rank:980, k:'香', level:'N2', meanings:['fragancia / aroma'], on:['コウ'], kun:['かお'],
    words:[{w:'香り',f:'かおり',m:'fragancia',l:'N3'},]},
  { rank:981, k:'駐', level:'N2', meanings:['estacionarse'], on:['チュウ'], kun:[],
    words:[{w:'駐車場',f:'ちゅうしゃじょう',m:'aparcamiento',l:'N4'},{w:'駐車',f:'ちゅうしゃ',m:'estacionamiento',l:'N3'}]},
  { rank:982, k:'骨', level:'N2', meanings:['hueso'], on:['コツ'], kun:['ほね'],
    words:[{w:'骨',f:'ほね',m:'hueso',l:'N3'},]},
  { rank:983, k:'麦', level:'N2', meanings:['trigo / cebada'], on:['バク'], kun:['むぎ'],
    words:[{w:'麦',f:'むぎ',m:'trigo / cebada',l:'N4'},{w:'麦茶',f:'むぎちゃ',m:'té de cebada',l:'N3'},{w:'小麦',f:'こむぎ',m:'trigo',l:'N3'}]},
  { rank:984, k:'黄', level:'N2', meanings:['amarillo'], on:['オウ'], kun:['き'],
    words:[{w:'黄色',f:'きいろ',m:'amarillo',l:'N5'},]},
  { rank:985, k:'鼻', level:'N2', meanings:['nariz'], on:['ビ'], kun:['はな'],
    words:[{w:'鼻',f:'はな',m:'nariz',l:'N5'},{w:'鼻水',f:'はなみず',m:'mocos',l:'N3'},{w:'鼻声',f:'はなごえ',m:'voz gangosa / nasal',l:'N3'}]},
  { rank:986, k:'齢', level:'N2', meanings:['edad'], on:['レイ'], kun:[],
    words:[{w:'年齢',f:'ねんれい',m:'edad',l:'N4'},{w:'高齢',f:'こうれい',m:'edad avanzada',l:'N3'}]},
  { rank:1036, k:'勇', level:'N2', meanings:['valentía','coraje'], on:['ユウ'], kun:['いさ'],
    words:[{w:'勇気',f:'ゆうき',m:'valor / coraje',l:'N3'}]},

]
