import type { Kanji } from './types'

// N5: 103 kanji

export const kanjiN5: Kanji[] = [
  { k:'日', level:'N5', meanings:['sol','día'], on:['ニチ','ジツ'], kun:['ひ','か'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'今日',f:'きょう',m:'hoy',l:'N5'},{w:'毎日',f:'まいにち',m:'cada día',l:'N5'},{w:'日曜日',f:'にちようび',m:'domingo',l:'N5'},{w:'誕生日',f:'たんじょうび',m:'cumpleaños',l:'N4'},{w:'日記',f:'にっき',m:'diario personal',l:'N4'},{w:'休日',f:'きゅうじつ',m:'día festivo',l:'N4'},{w:'日程',f:'にってい',m:'agenda / itinerario',l:'N3'}]},
  { k:'一', level:'N5', meanings:['uno'], on:['イチ','イツ'], kun:['ひと'],
    words:[{w:'一人',f:'ひとり',m:'una persona',l:'N5'},{w:'一つ',f:'ひとつ',m:'una cosa',l:'N5'},{w:'一月',f:'いちがつ',m:'enero',l:'N5'},{w:'一番',f:'いちばん',m:'el más / número uno',l:'N5'},{w:'一度',f:'いちど',m:'una vez',l:'N5'},{w:'一緒に',f:'いっしょに',m:'juntos',l:'N5'},{w:'統一',f:'とういつ',m:'unificación',l:'N3'}]},
  { k:'国', level:'N5', meanings:['país','nación'], on:['コク'], kun:['くに'],
    words:[{w:'外国',f:'がいこく',m:'extranjero (país)',l:'N5'},{w:'国語',f:'こくご',m:'lengua nacional',l:'N5'},{w:'中国',f:'ちゅうごく',m:'China',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},{w:'全国',f:'ぜんこく',m:'todo el país',l:'N4'},{w:'国民',f:'こくみん',m:'ciudadano / pueblo',l:'N4'},{w:'国際',f:'こくさい',m:'internacional',l:'N4'}]},
  { k:'人', level:'N5', meanings:['persona'], on:['ジン','ニン'], kun:['ひと'],
    words:[{w:'人々',f:'ひとびと',m:'personas',l:'N5'},{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'外国人',f:'がいこくじん',m:'extranjero (persona)',l:'N5'},{w:'一人',f:'ひとり',m:'una persona / solo',l:'N5'},{w:'人口',f:'じんこう',m:'población',l:'N4'},{w:'人気',f:'にんき',m:'popularidad',l:'N4'},{w:'人物',f:'じんぶつ',m:'personaje / individuo',l:'N4'},{w:'人類',f:'じんるい',m:'humanidad',l:'N3'}]},
  { k:'年', level:'N5', meanings:['año'], on:['ネン'], kun:['とし'],
    words:[{w:'今年',f:'ことし',m:'este año',l:'N5'},{w:'来年',f:'らいねん',m:'el año que viene',l:'N5'},{w:'毎年',f:'まいとし',m:'cada año',l:'N5'},{w:'去年',f:'きょねん',m:'el año pasado',l:'N5'},{w:'新年',f:'しんねん',m:'año nuevo',l:'N5'},{w:'年齢',f:'ねんれい',m:'edad',l:'N4'},{w:'年間',f:'ねんかん',m:'período anual',l:'N4'}]},
  { k:'大', level:'N5', meanings:['grande'], on:['ダイ','タイ'], kun:['おお'],
    words:[{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'大切',f:'たいせつ',m:'importante',l:'N5'},{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'大きい',f:'おおきい',m:'grande',l:'N5'},{w:'大事',f:'だいじ',m:'importante / asunto grave',l:'N5'},{w:'大勢',f:'おおぜい',m:'mucha gente',l:'N4'},{w:'大体',f:'だいたい',m:'generalmente / más o menos',l:'N4'}]},
  { k:'十', level:'N5', meanings:['diez'], on:['ジュウ','ジッ'], kun:['とお','と'],
    words:[{w:'十日',f:'とおか',m:'diez días / día 10',l:'N5'},{w:'十分',f:'じゅうぶん',m:'suficiente',l:'N5'},{w:'二十歳',f:'はたち',m:'veinte años',l:'N5'},{w:'十字路',f:'じゅうじろ',m:'cruce / intersección',l:'N4'},{w:'数十',f:'すうじゅう',m:'varias decenas',l:'N4'}]},
  { k:'本', level:'N5', meanings:['libro','origen'], on:['ホン'], kun:['もと'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'本当',f:'ほんとう',m:'verdad / de verdad',l:'N5'},{w:'本屋',f:'ほんや',m:'librería',l:'N5'},{w:'絵本',f:'えほん',m:'libro ilustrado',l:'N5'},{w:'基本',f:'きほん',m:'fundamento',l:'N4'},{w:'本棚',f:'ほんだな',m:'estantería de libros',l:'N4'},{w:'見本',f:'みほん',m:'muestra / modelo',l:'N4'}]},
  { k:'中', level:'N5', meanings:['interior','durante'], on:['チュウ'], kun:['なか'],
    words:[{w:'中学校',f:'ちゅうがっこう',m:'instituto',l:'N5'},{w:'中国',f:'ちゅうごく',m:'China',l:'N5'},{w:'中心',f:'ちゅうしん',m:'centro',l:'N4'},{w:'途中',f:'とちゅう',m:'a mitad de camino',l:'N4'},{w:'中身',f:'なかみ',m:'contenido / interior',l:'N4'},{w:'集中',f:'しゅうちゅう',m:'concentración',l:'N4'},{w:'中級',f:'ちゅうきゅう',m:'nivel intermedio',l:'N3'}]},
  { k:'学', level:'N5', meanings:['estudio','aprendizaje'], on:['ガク'], kun:['まな.ぶ'],
    words:[{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'学生',f:'がくせい',m:'estudiante',l:'N5'},{w:'小学校',f:'しょうがっこう',m:'escuela primaria',l:'N5'},{w:'学習',f:'がくしゅう',m:'aprendizaje',l:'N4'},{w:'学力',f:'がくりょく',m:'capacidad académica',l:'N4'},{w:'語学',f:'ごがく',m:'estudio de idiomas',l:'N4'}]},
  { k:'生', level:'N5', meanings:['vida','nacer'], on:['セイ','ショウ'], kun:['い.きる','う.まれる','なま'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'学生',f:'がくせい',m:'estudiante',l:'N5'},{w:'生まれる',f:'うまれる',m:'nacer',l:'N5'},{w:'生活',f:'せいかつ',m:'vida cotidiana',l:'N4'},{w:'誕生日',f:'たんじょうび',m:'cumpleaños',l:'N4'},{w:'生徒',f:'せいと',m:'alumno (secundaria)',l:'N4'},{w:'人生',f:'じんせい',m:'vida (de una persona)',l:'N4'},{w:'生産',f:'せいさん',m:'producción',l:'N3'}]},
  { k:'二', level:'N5', meanings:['dos'], on:['ニ'], kun:['ふた'],
    words:[{w:'二人',f:'ふたり',m:'dos personas',l:'N5'},{w:'二つ',f:'ふたつ',m:'dos cosas',l:'N5'},{w:'二月',f:'にがつ',m:'febrero',l:'N5'},{w:'二十',f:'にじゅう',m:'veinte',l:'N5'}]},
  { k:'行', level:'N5', meanings:['ir'], on:['コウ','ギョウ'], kun:['い.く','おこな.う'],
    words:[{w:'行く',f:'いく',m:'ir',l:'N5'},{w:'旅行',f:'りょこう',m:'viaje',l:'N5'},{w:'銀行',f:'ぎんこう',m:'banco',l:'N5'},{w:'行動',f:'こうどう',m:'acción / conducta',l:'N4'},{w:'行事',f:'ぎょうじ',m:'evento / acto',l:'N4'},{w:'旅行者',f:'りょこうしゃ',m:'viajero',l:'N4'},{w:'行列',f:'ぎょうれつ',m:'fila / cola',l:'N3'}]},
  { k:'見', level:'N5', meanings:['ver','mirar'], on:['ケン'], kun:['み.る'],
    words:[{w:'見る',f:'みる',m:'ver / mirar',l:'N5'},{w:'見える',f:'みえる',m:'poder ver / ser visible',l:'N5'},{w:'花見',f:'はなみ',m:'contemplación de cerezos',l:'N5'},{w:'意見',f:'いけん',m:'opinión',l:'N4'},{w:'見学',f:'けんがく',m:'visita de estudio',l:'N4'},{w:'見物',f:'けんぶつ',m:'turismo / contemplación',l:'N4'},{w:'発見',f:'はっけん',m:'descubrimiento',l:'N3'}]},
  { k:'時', level:'N5', meanings:['tiempo','hora'], on:['ジ'], kun:['とき'],
    words:[{w:'時間',f:'じかん',m:'tiempo / hora',l:'N5'},{w:'何時',f:'なんじ',m:'qué hora',l:'N5'},{w:'時々',f:'ときどき',m:'a veces',l:'N5'},{w:'時代',f:'じだい',m:'era / época',l:'N4'},{w:'当時',f:'とうじ',m:'en aquel entonces',l:'N4'},{w:'時期',f:'じき',m:'período / momento',l:'N4'},{w:'一時',f:'いちじ',m:'temporalmente / de momento',l:'N3'}]},
  { k:'間', level:'N5', meanings:['intervalo','entre'], on:['カン','ケン'], kun:['あいだ','ま'],
    words:[{w:'時間',f:'じかん',m:'tiempo / hora',l:'N5'},{w:'人間',f:'にんげん',m:'ser humano',l:'N4'},{w:'間に合う',f:'まにあう',m:'llegar a tiempo',l:'N4'},{w:'期間',f:'きかん',m:'período',l:'N4'},{w:'時間割',f:'じかんわり',m:'horario escolar',l:'N4'},{w:'空間',f:'くうかん',m:'espacio',l:'N4'},{w:'民間',f:'みんかん',m:'sector privado / civil',l:'N3'}]},
  { k:'三', level:'N5', meanings:['tres'], on:['サン'], kun:['み','みっ'],
    words:[{w:'三日',f:'みっか',m:'tres días / día 3',l:'N5'},{w:'三つ',f:'みっつ',m:'tres cosas',l:'N5'},{w:'三月',f:'さんがつ',m:'marzo',l:'N5'},{w:'三角',f:'さんかく',m:'triángulo',l:'N5'}]},
  { k:'気', level:'N5', meanings:['espíritu','aire','ánimo'], on:['キ','ケ'], kun:[],
    words:[{w:'元気',f:'げんき',m:'saludable / animado',l:'N5'},{w:'天気',f:'てんき',m:'tiempo (meteorológico)',l:'N5'},{w:'気持ち',f:'きもち',m:'sentimiento',l:'N5'},{w:'電気',f:'でんき',m:'electricidad / luz',l:'N5'},{w:'空気',f:'くうき',m:'aire',l:'N5'},{w:'人気',f:'にんき',m:'popularidad',l:'N4'},{w:'気分',f:'きぶん',m:'estado de ánimo',l:'N4'},{w:'気候',f:'きこう',m:'clima',l:'N3'}]},
  { k:'今', level:'N5', meanings:['ahora'], on:['コン','キン'], kun:['いま'],
    words:[{w:'今日',f:'きょう',m:'hoy',l:'N5'},{w:'今年',f:'ことし',m:'este año',l:'N5'},{w:'今週',f:'こんしゅう',m:'esta semana',l:'N5'},{w:'今月',f:'こんげつ',m:'este mes',l:'N5'},{w:'今夜',f:'こんや',m:'esta noche',l:'N5'},{w:'今後',f:'こんご',m:'de ahora en adelante',l:'N4'},{w:'今すぐ',f:'いますぐ',m:'ahora mismo / enseguida',l:'N4'}]},
  { k:'前', level:'N5', meanings:['delante','antes'], on:['ゼン'], kun:['まえ'],
    words:[{w:'名前',f:'なまえ',m:'nombre',l:'N5'},{w:'午前',f:'ごぜん',m:'de la mañana (AM)',l:'N5'},{w:'駅前',f:'えきまえ',m:'frente a la estación',l:'N5'},{w:'前回',f:'ぜんかい',m:'la vez anterior',l:'N4'},{w:'以前',f:'いぜん',m:'antes / anteriormente',l:'N4'},{w:'前半',f:'ぜんはん',m:'primera mitad',l:'N4'},{w:'事前',f:'じぜん',m:'con antelación',l:'N3'}]},
  { k:'後', level:'N5', meanings:['después','detrás'], on:['ゴ','コウ'], kun:['あと','うし.ろ'],
    words:[{w:'午後',f:'ごご',m:'tarde (PM)',l:'N5'},{w:'後で',f:'あとで',m:'después',l:'N5'},{w:'最後',f:'さいご',m:'el último / al final',l:'N4'},{w:'後半',f:'こうはん',m:'segunda mitad',l:'N4'},{w:'後輩',f:'こうはい',m:'subalterno / junior',l:'N4'},{w:'今後',f:'こんご',m:'de ahora en adelante',l:'N4'},{w:'以後',f:'いご',m:'a partir de ahora',l:'N3'}]},
  { k:'分', level:'N5', meanings:['minuto','entender','parte'], on:['フン','ブン'], kun:['わか.る'],
    words:[{w:'分かる',f:'わかる',m:'entender',l:'N5'},{w:'半分',f:'はんぶん',m:'la mitad',l:'N5'},{w:'自分',f:'じぶん',m:'uno mismo',l:'N5'},{w:'十分',f:'じゅっぷん',m:'diez minutos',l:'N5'},{w:'気分',f:'きぶん',m:'estado de ánimo',l:'N4'},{w:'部分',f:'ぶぶん',m:'parte / sección',l:'N4'},{w:'区分',f:'くぶん',m:'clasificación / división',l:'N3'}]},
  { k:'語', level:'N5', meanings:['idioma','palabra'], on:['ゴ'], kun:['かた.る'],
    words:[{w:'日本語',f:'にほんご',m:'japonés',l:'N5'},{w:'英語',f:'えいご',m:'inglés',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},{w:'語学',f:'ごがく',m:'estudio de idiomas',l:'N4'},{w:'言語',f:'げんご',m:'lenguaje',l:'N4'},{w:'単語',f:'たんご',m:'vocabulario / palabra',l:'N4'},{w:'物語',f:'ものがたり',m:'cuento / relato',l:'N4'}]},
  { k:'食', level:'N5', meanings:['comer','comida'], on:['ショク'], kun:['た.べる','く.う'],
    words:[{w:'食べる',f:'たべる',m:'comer',l:'N5'},{w:'食事',f:'しょくじ',m:'comida / comida',l:'N5'},{w:'朝食',f:'ちょうしょく',m:'desayuno',l:'N4'},{w:'外食',f:'がいしょく',m:'comer fuera',l:'N4'},{w:'食料',f:'しょくりょう',m:'alimentos',l:'N4'},{w:'食欲',f:'しょくよく',m:'apetito',l:'N4'},{w:'食文化',f:'しょくぶんか',m:'cultura gastronómica',l:'N3'}]},
  { k:'名', level:'N5', meanings:['nombre','famoso'], on:['メイ','ミョウ'], kun:['な'],
    words:[{w:'名前',f:'なまえ',m:'nombre',l:'N5'},{w:'有名',f:'ゆうめい',m:'famoso',l:'N5'},{w:'名刺',f:'めいし',m:'tarjeta de visita',l:'N4'},{w:'名所',f:'めいしょ',m:'lugar famoso',l:'N4'},{w:'氏名',f:'しめい',m:'nombre completo',l:'N4'},{w:'名詞',f:'めいし',m:'sustantivo (gramática)',l:'N3'},{w:'名作',f:'めいさく',m:'obra maestra',l:'N3'}]},
  { k:'上', level:'N5', meanings:['arriba','encima'], on:['ジョウ','ショウ'], kun:['うえ','あ.がる','のぼ.る'],
    words:[{w:'上手',f:'じょうず',m:'hábil',l:'N5'},{w:'以上',f:'いじょう',m:'más de / al final',l:'N4'},{w:'上着',f:'うわぎ',m:'chaqueta',l:'N4'},{w:'屋上',f:'おくじょう',m:'azotea',l:'N4'},{w:'上司',f:'じょうし',m:'superior / jefe',l:'N4'},{w:'向上',f:'こうじょう',m:'mejora / progreso',l:'N3'},{w:'上昇',f:'じょうしょう',m:'ascenso / subida',l:'N3'}]},
  { k:'下', level:'N5', meanings:['abajo','debajo'], on:['カ','ゲ'], kun:['した','さ.がる','くだ.る'],
    words:[{w:'下手',f:'へた',m:'torpe',l:'N5'},{w:'地下',f:'ちか',m:'subterráneo',l:'N4'},{w:'以下',f:'いか',m:'menos de',l:'N4'},{w:'下着',f:'したぎ',m:'ropa interior',l:'N4'},{w:'下車',f:'げしゃ',m:'bajar del vehículo',l:'N4'},{w:'低下',f:'ていか',m:'descenso / deterioro',l:'N3'},{w:'下降',f:'かこう',m:'bajada / descenso',l:'N3'}]},
  { k:'来', level:'N5', meanings:['venir'], on:['ライ'], kun:['く.る','き','こ'],
    words:[{w:'来る',f:'くる',m:'venir',l:'N5'},{w:'来年',f:'らいねん',m:'el año que viene',l:'N5'},{w:'来週',f:'らいしゅう',m:'la semana próxima',l:'N5'},{w:'来月',f:'らいげつ',m:'el mes que viene',l:'N5'},{w:'未来',f:'みらい',m:'futuro',l:'N4'},{w:'来日',f:'らいにち',m:'llegada a Japón',l:'N4'},{w:'将来',f:'しょうらい',m:'futuro / porvenir',l:'N4'}]},
  { k:'先', level:'N5', meanings:['antes','adelante','punta'], on:['セン'], kun:['さき'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'先週',f:'せんしゅう',m:'la semana pasada',l:'N5'},{w:'先月',f:'せんげつ',m:'el mes pasado',l:'N5'},{w:'先輩',f:'せんぱい',m:'superior / veterano',l:'N4'},{w:'先日',f:'せんじつ',m:'el otro día',l:'N4'},{w:'優先',f:'ゆうせん',m:'prioridad',l:'N3'},{w:'先着',f:'せんちゃく',m:'primero en llegar',l:'N3'}]},
  { k:'月', level:'N5', meanings:['luna','mes'], on:['ゲツ','ガツ'], kun:['つき'],
    words:[{w:'月曜日',f:'げつようび',m:'lunes',l:'N5'},{w:'今月',f:'こんげつ',m:'este mes',l:'N5'},{w:'来月',f:'らいげつ',m:'el mes que viene',l:'N5'},{w:'一月',f:'いちがつ',m:'enero',l:'N5'},{w:'毎月',f:'まいつき',m:'cada mes',l:'N4'},{w:'月給',f:'げっきゅう',m:'salario mensual',l:'N4'},{w:'満月',f:'まんげつ',m:'luna llena',l:'N3'}]},
  { k:'週', level:'N5', meanings:['semana'], on:['シュウ'], kun:[],
    words:[{w:'今週',f:'こんしゅう',m:'esta semana',l:'N5'},{w:'先週',f:'せんしゅう',m:'la semana pasada',l:'N5'},{w:'来週',f:'らいしゅう',m:'la semana próxima',l:'N5'},{w:'毎週',f:'まいしゅう',m:'cada semana',l:'N5'},{w:'週末',f:'しゅうまつ',m:'fin de semana',l:'N4'},{w:'週刊',f:'しゅうかん',m:'semanal (publicación)',l:'N4'}]},
  { k:'何', level:'N5', meanings:['qué','cuánto'], on:['カ'], kun:['なに','なん'],
    words:[{w:'何か',f:'なにか',m:'algo',l:'N5'},{w:'何時',f:'なんじ',m:'qué hora',l:'N5'},{w:'何故',f:'なぜ',m:'por qué',l:'N4'},{w:'何度',f:'なんど',m:'cuántas veces',l:'N4'}]},
  { k:'電', level:'N5', meanings:['electricidad'], on:['デン'], kun:[],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'電気',f:'でんき',m:'electricidad / luz',l:'N5'},{w:'電子',f:'でんし',m:'electrónico',l:'N4'},{w:'電池',f:'でんち',m:'pila / batería',l:'N4'},{w:'電力',f:'でんりょく',m:'potencia eléctrica',l:'N4'},{w:'停電',f:'ていでん',m:'apagón',l:'N3'}]},
  { k:'車', level:'N5', meanings:['coche','vehículo'], on:['シャ'], kun:['くるま'],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},{w:'自動車',f:'じどうしゃ',m:'automóvil',l:'N4'},{w:'駐車場',f:'ちゅうしゃじょう',m:'aparcamiento',l:'N4'},{w:'乗用車',f:'じょうようしゃ',m:'coche de pasajeros',l:'N4'},{w:'救急車',f:'きゅうきゅうしゃ',m:'ambulancia',l:'N4'},{w:'車両',f:'しゃりょう',m:'vehículo / vagón',l:'N3'}]},
  { k:'話', level:'N5', meanings:['hablar','historia'], on:['ワ'], kun:['はな.す','はなし'],
    words:[{w:'話す',f:'はなす',m:'hablar',l:'N5'},{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'会話',f:'かいわ',m:'conversación',l:'N4'},{w:'話し合う',f:'はなしあう',m:'conversar / dialogar',l:'N4'},{w:'童話',f:'どうわ',m:'cuento infantil',l:'N4'},{w:'神話',f:'しんわ',m:'mitología',l:'N4'},{w:'話題',f:'わだい',m:'tema de conversación',l:'N4'}]},
  { k:'言', level:'N5', meanings:['decir','palabra'], on:['ゲン','ゴン'], kun:['い.う','こと'],
    words:[{w:'言う',f:'いう',m:'decir',l:'N5'},{w:'言葉',f:'ことば',m:'palabra / idioma',l:'N5'},{w:'言語',f:'げんご',m:'lenguaje',l:'N4'},{w:'一言',f:'ひとこと',m:'una palabra',l:'N4'},{w:'発言',f:'はつげん',m:'declaración / intervención',l:'N4'},{w:'伝言',f:'でんごん',m:'recado / mensaje',l:'N4'},{w:'名言',f:'めいげん',m:'frase célebre',l:'N3'}]},
  { k:'友', level:'N5', meanings:['amigo'], on:['ユウ'], kun:['とも'],
    words:[{w:'友達',f:'ともだち',m:'amigo',l:'N5'},{w:'友人',f:'ゆうじん',m:'amigo (formal)',l:'N4'},{w:'親友',f:'しんゆう',m:'amigo íntimo',l:'N4'},{w:'友好',f:'ゆうこう',m:'amistad / relaciones amistosas',l:'N4'},{w:'戦友',f:'せんゆう',m:'compañero de armas',l:'N3'}]},
  { k:'毎', level:'N5', meanings:['cada','todo'], on:['マイ'], kun:[],
    words:[{w:'毎日',f:'まいにち',m:'cada día',l:'N5'},{w:'毎週',f:'まいしゅう',m:'cada semana',l:'N5'},{w:'毎年',f:'まいとし',m:'cada año',l:'N5'},{w:'毎朝',f:'まいあさ',m:'cada mañana',l:'N5'}]},
  { k:'外', level:'N5', meanings:['exterior','fuera'], on:['ガイ','ゲ'], kun:['そと','ほか'],
    words:[{w:'外国',f:'がいこく',m:'extranjero (país)',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},{w:'外出',f:'がいしゅつ',m:'salida / salir',l:'N4'},{w:'海外',f:'かいがい',m:'ultramar / en el extranjero',l:'N4'},{w:'以外',f:'いがい',m:'excepto / aparte de',l:'N4'},{w:'外来',f:'がいらい',m:'consulta externa / de origen extranjero',l:'N3'},{w:'対外',f:'たいがい',m:'relaciones exteriores',l:'N3'}]},
  { k:'小', level:'N5', meanings:['pequeño'], on:['ショウ'], kun:['ちい.さい','こ'],
    words:[{w:'小学校',f:'しょうがっこう',m:'escuela primaria',l:'N5'},{w:'小さい',f:'ちいさい',m:'pequeño',l:'N5'},{w:'小学生',f:'しょうがくせい',m:'alumno de primaria',l:'N5'},{w:'小説',f:'しょうせつ',m:'novela',l:'N4'},{w:'小声',f:'こごえ',m:'voz baja',l:'N4'},{w:'小包',f:'こづつみ',m:'paquete postal',l:'N4'},{w:'縮小',f:'しゅくしょう',m:'reducción',l:'N3'}]},
  { k:'読', level:'N5', meanings:['leer'], on:['ドク','トク'], kun:['よ.む'],
    words:[{w:'読む',f:'よむ',m:'leer',l:'N5'},{w:'音読み',f:'おんよみ',m:'lectura on',l:'N5'},{w:'読書',f:'どくしょ',m:'lectura',l:'N4'},{w:'読者',f:'どくしゃ',m:'lector',l:'N4'},{w:'読み方',f:'よみかた',m:'manera de leer / pronunciación',l:'N4'},{w:'読解',f:'どっかい',m:'comprensión lectora',l:'N3'},{w:'購読',f:'こうどく',m:'suscripción',l:'N3'}]},
  { k:'書', level:'N5', meanings:['escribir'], on:['ショ'], kun:['か.く'],
    words:[{w:'書く',f:'かく',m:'escribir',l:'N5'},{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'辞書',f:'じしょ',m:'diccionario',l:'N5'},{w:'書店',f:'しょてん',m:'librería (formal)',l:'N5'},{w:'教科書',f:'きょうかしょ',m:'libro de texto',l:'N4'},{w:'書類',f:'しょるい',m:'documentos',l:'N4'},{w:'書道',f:'しょどう',m:'caligrafía japonesa',l:'N4'}]},
  { k:'出', level:'N5', meanings:['salir','sacar'], on:['シュツ','スイ'], kun:['で.る','だ.す'],
    words:[{w:'出る',f:'でる',m:'salir',l:'N5'},{w:'出口',f:'でぐち',m:'salida',l:'N5'},{w:'出発',f:'しゅっぱつ',m:'partida / salida',l:'N5'},{w:'提出',f:'ていしゅつ',m:'entrega / presentación',l:'N4'},{w:'外出',f:'がいしゅつ',m:'salir de casa',l:'N4'},{w:'出身',f:'しゅっしん',m:'lugar de origen',l:'N4'},{w:'輸出',f:'ゆしゅつ',m:'exportación',l:'N3'}]},
  { k:'入', level:'N5', meanings:['entrar','meter'], on:['ニュウ'], kun:['はい.る','い.れる'],
    words:[{w:'入る',f:'はいる',m:'entrar',l:'N5'},{w:'入口',f:'いりぐち',m:'entrada',l:'N5'},{w:'入学',f:'にゅうがく',m:'ingreso escolar',l:'N4'},{w:'輸入',f:'ゆにゅう',m:'importación',l:'N4'},{w:'入院',f:'にゅういん',m:'hospitalización',l:'N4'},{w:'収入',f:'しゅうにゅう',m:'ingresos / sueldo',l:'N4'},{w:'導入',f:'どうにゅう',m:'introducción / adopción',l:'N3'}]},
  { k:'会', level:'N5', meanings:['reunión','encontrar'], on:['カイ','エ'], kun:['あ.う'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},{w:'会う',f:'あう',m:'encontrarse / quedar',l:'N5'},{w:'会議',f:'かいぎ',m:'reunión',l:'N4'},{w:'社会',f:'しゃかい',m:'sociedad',l:'N4'},{w:'機会',f:'きかい',m:'oportunidad',l:'N4'},{w:'大会',f:'たいかい',m:'torneo / convención',l:'N4'},{w:'国会',f:'こっかい',m:'parlamento',l:'N3'}]},
  { k:'聞', level:'N5', meanings:['escuchar','preguntar'], on:['ブン','モン'], kun:['き.く'],
    words:[{w:'聞く',f:'きく',m:'escuchar / preguntar',l:'N5'},{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'},{w:'聞こえる',f:'きこえる',m:'poder escuchar / oírse',l:'N5'},{w:'伝聞',f:'でんぶん',m:'rumor / dicho de oídas',l:'N4'},{w:'見聞',f:'けんぶん',m:'conocimientos / experiencia',l:'N4'},{w:'聴聞',f:'ちょうもん',m:'audiencia / escucha formal',l:'N3'}]},
  { k:'買', level:'N5', meanings:['comprar'], on:['バイ'], kun:['か.う'],
    words:[{w:'買う',f:'かう',m:'comprar',l:'N5'},{w:'買い物',f:'かいもの',m:'compras',l:'N5'},{w:'売買',f:'ばいばい',m:'compraventa',l:'N4'},{w:'買い物袋',f:'かいものぶくろ',m:'bolsa de la compra',l:'N4'},{w:'購買',f:'こうばい',m:'adquisición / compra (formal)',l:'N3'}]},
  { k:'休', level:'N5', meanings:['descansar','vacaciones'], on:['キュウ'], kun:['やす.む'],
    words:[{w:'休む',f:'やすむ',m:'descansar',l:'N5'},{w:'夏休み',f:'なつやすみ',m:'vacaciones de verano',l:'N5'},{w:'休日',f:'きゅうじつ',m:'día festivo',l:'N4'},{w:'休憩',f:'きゅうけい',m:'descanso',l:'N4'}]},
  { k:'立', level:'N5', meanings:['ponerse de pie','levantarse'], on:['リツ','リュウ'], kun:['た.つ'],
    words:[{w:'立つ',f:'たつ',m:'ponerse de pie',l:'N5'},{w:'立場',f:'たちば',m:'posición / punto de vista',l:'N4'},{w:'役立つ',f:'やくだつ',m:'ser útil',l:'N4'},{w:'独立',f:'どくりつ',m:'independencia',l:'N4'},{w:'成立',f:'せいりつ',m:'establecimiento / formación',l:'N3'}]},
  { k:'校', level:'N5', meanings:['escuela'], on:['コウ'], kun:[],
    words:[{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},{w:'校長',f:'こうちょう',m:'director de escuela',l:'N4'},{w:'校庭',f:'こうてい',m:'patio del colegio',l:'N4'}]},
  { k:'社', level:'N5', meanings:['empresa','sociedad','santuario'], on:['シャ'], kun:['やしろ'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},{w:'社会',f:'しゃかい',m:'sociedad',l:'N4'},{w:'神社',f:'じんじゃ',m:'santuario shinto',l:'N4'},{w:'社長',f:'しゃちょう',m:'presidente de empresa',l:'N4'}]},
  { k:'山', level:'N5', meanings:['montaña'], on:['サン'], kun:['やま'],
    words:[{w:'富士山',f:'ふじさん',m:'monte Fuji',l:'N5'},{w:'火山',f:'かざん',m:'volcán',l:'N4'},{w:'山登り',f:'やまのぼり',m:'alpinismo / senderismo',l:'N4'},{w:'山道',f:'やまみち',m:'camino de montaña',l:'N4'},{w:'登山',f:'とざん',m:'montañismo',l:'N4'},{w:'山脈',f:'さんみゃく',m:'cordillera',l:'N3'}]},
  { k:'川', level:'N5', meanings:['río'], on:['セン'], kun:['かわ'],
    words:[{w:'小川',f:'おがわ',m:'arroyo',l:'N4'},{w:'河川',f:'かせん',m:'ríos (término colectivo)',l:'N4'},{w:'川辺',f:'かわべ',m:'orilla del río',l:'N4'},{w:'川岸',f:'かわぎし',m:'ribera',l:'N4'},{w:'川上',f:'かわかみ',m:'río arriba',l:'N3'},{w:'川下り',f:'かわくだり',m:'descenso en río',l:'N3'}]},
  { k:'口', level:'N5', meanings:['boca','entrada'], on:['コウ','ク'], kun:['くち'],
    words:[{w:'入口',f:'いりぐち',m:'entrada',l:'N5'},{w:'出口',f:'でぐち',m:'salida',l:'N5'},{w:'人口',f:'じんこう',m:'población',l:'N4'},{w:'口座',f:'こうざ',m:'cuenta bancaria',l:'N4'},{w:'窓口',f:'まどぐち',m:'ventanilla / mostrador',l:'N4'},{w:'口調',f:'くちょう',m:'tono de voz',l:'N4'},{w:'口実',f:'こうじつ',m:'pretexto / excusa',l:'N3'}]},
  { k:'手', level:'N5', meanings:['mano'], on:['シュ'], kun:['て'],
    words:[{w:'手紙',f:'てがみ',m:'carta',l:'N5'},{w:'上手',f:'じょうず',m:'hábil',l:'N5'},{w:'下手',f:'へた',m:'torpe',l:'N5'},{w:'手伝う',f:'てつだう',m:'ayudar',l:'N5'},{w:'握手',f:'あくしゅ',m:'apretón de manos',l:'N4'},{w:'手術',f:'しゅじゅつ',m:'operación quirúrgica',l:'N4'},{w:'選手',f:'せんしゅ',m:'atleta / jugador',l:'N3'}]},
  { k:'目', level:'N5', meanings:['ojo'], on:['モク','ボク'], kun:['め'],
    words:[{w:'目的',f:'もくてき',m:'propósito / objetivo',l:'N4'},{w:'目薬',f:'めぐすり',m:'colirio',l:'N4'},{w:'注目',f:'ちゅうもく',m:'atención / foco',l:'N4'},{w:'科目',f:'かもく',m:'asignatura',l:'N4'},{w:'項目',f:'こうもく',m:'ítem / punto',l:'N4'},{w:'一目',f:'ひとめ',m:'un vistazo',l:'N3'},{w:'目標',f:'もくひょう',m:'meta / objetivo',l:'N3'}]},
  { k:'耳', level:'N5', meanings:['oído'], on:['ジ'], kun:['みみ'],
    words:[{w:'耳',f:'みみ',m:'oído / oreja',l:'N5'},{w:'耳鳴り',f:'みみなり',m:'tinnitus / zumbido de oídos',l:'N4'},{w:'耳鼻科',f:'じびか',m:'otorrinolaringología',l:'N4'},{w:'耳元',f:'みみもと',m:'cerca del oído',l:'N4'},{w:'初耳',f:'はつみみ',m:'primera vez que se oye algo',l:'N3'}]},
  { k:'足', level:'N5', meanings:['pie','pierna','suficiente'], on:['ソク'], kun:['あし','た.りる'],
    words:[{w:'足りる',f:'たりる',m:'ser suficiente',l:'N5'},{w:'遠足',f:'えんそく',m:'excursión',l:'N4'},{w:'土足',f:'どそく',m:'entrar con zapatos',l:'N4'},{w:'足音',f:'あしおと',m:'sonido de pasos',l:'N3'}]},
  { k:'白', level:'N5', meanings:['blanco'], on:['ハク','ビャク'], kun:['しろ'],
    words:[{w:'白い',f:'しろい',m:'blanco',l:'N5'},{w:'白紙',f:'はくし',m:'papel en blanco',l:'N4'},{w:'白黒',f:'しろくろ',m:'blanco y negro',l:'N4'},{w:'告白',f:'こくはく',m:'confesión',l:'N3'}]},
  { k:'円', level:'N5', meanings:['yen','círculo'], on:['エン'], kun:['まる'],
    words:[{w:'百円',f:'ひゃくえん',m:'100 yenes',l:'N5'},{w:'千円',f:'せんえん',m:'1000 yenes',l:'N5'},{w:'円高',f:'えんだか',m:'yen fuerte',l:'N3'},{w:'円安',f:'えんやす',m:'yen débil',l:'N3'}]},
  { k:'金', level:'N5', meanings:['oro','dinero'], on:['キン','コン'], kun:['かね'],
    words:[{w:'金曜日',f:'きんようび',m:'viernes',l:'N5'},{w:'お金',f:'おかね',m:'dinero',l:'N5'},{w:'金色',f:'きんいろ',m:'color dorado',l:'N4'},{w:'金額',f:'きんがく',m:'cantidad de dinero',l:'N4'}]},
  { k:'駅', level:'N5', meanings:['estación'], on:['エキ'], kun:[],
    words:[{w:'駅',f:'えき',m:'estación',l:'N5'},{w:'駅前',f:'えきまえ',m:'frente a la estación',l:'N5'},{w:'駅員',f:'えきいん',m:'empleado de estación',l:'N4'},{w:'終点駅',f:'しゅうてんえき',m:'estación terminal',l:'N4'}]},
  { k:'道', level:'N5', meanings:['camino','vía'], on:['ドウ','トウ'], kun:['みち'],
    words:[{w:'道路',f:'どうろ',m:'carretera',l:'N4'},{w:'道具',f:'どうぐ',m:'herramienta',l:'N4'},{w:'北海道',f:'ほっかいどう',m:'Hokkaido',l:'N4'},{w:'柔道',f:'じゅうどう',m:'judo',l:'N4'},{w:'近道',f:'ちかみち',m:'atajo',l:'N4'},{w:'道徳',f:'どうとく',m:'moral / ética',l:'N3'},{w:'報道',f:'ほうどう',m:'noticias / información periodística',l:'N3'}]},
  { k:'東', level:'N5', meanings:['este'], on:['トウ'], kun:['ひがし'],
    words:[{w:'東京',f:'とうきょう',m:'Tokio',l:'N5'},{w:'東口',f:'ひがしぐち',m:'salida este',l:'N5'},{w:'東洋',f:'とうよう',m:'Oriente',l:'N4'},{w:'東西',f:'とうざい',m:'este y oeste',l:'N4'}]},
  { k:'西', level:'N5', meanings:['oeste'], on:['セイ','サイ'], kun:['にし'],
    words:[{w:'西口',f:'にしぐち',m:'salida oeste',l:'N5'},{w:'西洋',f:'せいよう',m:'Occidente',l:'N4'},{w:'関西',f:'かんさい',m:'región de Kansai',l:'N4'},{w:'東西',f:'とうざい',m:'este y oeste',l:'N4'}]},
  { k:'南', level:'N5', meanings:['sur'], on:['ナン'], kun:['みなみ'],
    words:[{w:'南口',f:'みなみぐち',m:'salida sur',l:'N5'},{w:'南国',f:'なんごく',m:'país sureño / trópico',l:'N4'},{w:'南半球',f:'みなみはんきゅう',m:'hemisferio sur',l:'N4'},{w:'東南',f:'とうなん',m:'sureste',l:'N4'},{w:'南極',f:'なんきょく',m:'Polo Sur / Antártida',l:'N3'}]},
  { k:'北', level:'N5', meanings:['norte'], on:['ホク'], kun:['きた'],
    words:[{w:'北口',f:'きたぐち',m:'salida norte',l:'N5'},{w:'北海道',f:'ほっかいどう',m:'Hokkaido',l:'N4'},{w:'北上',f:'ほくじょう',m:'avanzar hacia el norte',l:'N4'},{w:'東北',f:'とうほく',m:'noreste / región Tohoku',l:'N4'},{w:'北極',f:'ほっきょく',m:'Polo Norte / Ártico',l:'N3'}]},
  { k:'左', level:'N5', meanings:['izquierda'], on:['サ'], kun:['ひだり'],
    words:[{w:'左側',f:'ひだりがわ',m:'lado izquierdo',l:'N5'},{w:'左手',f:'ひだりて',m:'mano izquierda',l:'N5'},{w:'左右',f:'さゆう',m:'izquierda y derecha',l:'N4'},{w:'左折',f:'させつ',m:'girar a la izquierda',l:'N4'},{w:'左利き',f:'ひだりきき',m:'zurdo',l:'N4'}]},
  { k:'右', level:'N5', meanings:['derecha'], on:['ウ','ユウ'], kun:['みぎ'],
    words:[{w:'右側',f:'みぎがわ',m:'lado derecho',l:'N5'},{w:'右手',f:'みぎて',m:'mano derecha',l:'N5'},{w:'左右',f:'さゆう',m:'izquierda y derecha',l:'N4'},{w:'右折',f:'うせつ',m:'girar a la derecha',l:'N4'},{w:'右利き',f:'みぎきき',m:'diestro',l:'N4'}]},
  { k:'午', level:'N5', meanings:['mediodía'], on:['ゴ'], kun:[],
    words:[{w:'午前',f:'ごぜん',m:'de la mañana (AM)',l:'N5'},{w:'午後',f:'ごご',m:'de la tarde (PM)',l:'N5'},{w:'午前中',f:'ごぜんちゅう',m:'durante la mañana',l:'N5'},{w:'正午',f:'しょうご',m:'mediodía exacto',l:'N4'},{w:'午睡',f:'ごすい',m:'siesta',l:'N3'}]},
  { k:'半', level:'N5', meanings:['mitad','medio'], on:['ハン'], kun:['なかば'],
    words:[{w:'半分',f:'はんぶん',m:'la mitad',l:'N5'},{w:'一時半',f:'いちじはん',m:'la una y media',l:'N5'},{w:'半年',f:'はんとし',m:'medio año',l:'N4'},{w:'後半',f:'こうはん',m:'segunda mitad',l:'N4'}]},
  { k:'天', level:'N5', meanings:['cielo','paraíso'], on:['テン'], kun:['あめ','あま'],
    words:[{w:'天気',f:'てんき',m:'tiempo (meteorológico)',l:'N5'},{w:'天国',f:'てんごく',m:'paraíso / cielo',l:'N4'},{w:'天才',f:'てんさい',m:'genio',l:'N4'},{w:'天井',f:'てんじょう',m:'techo',l:'N4'},{w:'天然',f:'てんねん',m:'natural',l:'N4'},{w:'天皇',f:'てんのう',m:'Emperador (de Japón)',l:'N3'},{w:'天文',f:'てんもん',m:'astronomía',l:'N3'}]},
  { k:'水', level:'N5', meanings:['agua'], on:['スイ'], kun:['みず'],
    words:[{w:'水曜日',f:'すいようび',m:'miércoles',l:'N5'},{w:'お水',f:'おみず',m:'agua (cortés)',l:'N5'},{w:'水泳',f:'すいえい',m:'natación',l:'N4'},{w:'水道',f:'すいどう',m:'agua corriente / tubería',l:'N4'},{w:'洪水',f:'こうずい',m:'inundación',l:'N4'},{w:'水分',f:'すいぶん',m:'hidratación / contenido de agua',l:'N4'},{w:'水面',f:'すいめん',m:'superficie del agua',l:'N3'}]},
  { k:'火', level:'N5', meanings:['fuego'], on:['カ'], kun:['ひ'],
    words:[{w:'火曜日',f:'かようび',m:'martes',l:'N5'},{w:'花火',f:'はなび',m:'fuegos artificiales',l:'N4'},{w:'火事',f:'かじ',m:'incendio',l:'N4'},{w:'火山',f:'かざん',m:'volcán',l:'N4'},{w:'点火',f:'てんか',m:'encendido / ignición',l:'N4'},{w:'消火',f:'しょうか',m:'extinción de incendio',l:'N4'},{w:'火災',f:'かさい',m:'incendio (formal)',l:'N3'}]},
  { k:'木', level:'N5', meanings:['árbol','madera'], on:['モク','ボク'], kun:['き'],
    words:[{w:'木曜日',f:'もくようび',m:'jueves',l:'N5'},{w:'木材',f:'もくざい',m:'madera / material de madera',l:'N4'},{w:'木の葉',f:'このは',m:'hoja de árbol',l:'N4'},{w:'植木',f:'うえき',m:'árbol de jardín / planta de maceta',l:'N4'},{w:'木陰',f:'こかげ',m:'sombra de árbol',l:'N4'},{w:'木造',f:'もくぞう',m:'construcción de madera',l:'N3'},{w:'大木',f:'たいぼく',m:'árbol grande',l:'N3'}]},
  { k:'土', level:'N5', meanings:['tierra'], on:['ド','ト'], kun:['つち'],
    words:[{w:'土曜日',f:'どようび',m:'sábado',l:'N5'},{w:'土地',f:'とち',m:'terreno / tierra',l:'N4'},{w:'土台',f:'どだい',m:'base / fundamento',l:'N4'},{w:'土産',f:'みやげ',m:'souvenir / regalo típico',l:'N4'},{w:'郷土',f:'きょうど',m:'tierra natal / región',l:'N4'},{w:'土砂',f:'どしゃ',m:'tierra y arena',l:'N3'},{w:'粘土',f:'ねんど',m:'arcilla / plastilina',l:'N3'}]},
  { k:'花', level:'N5', meanings:['flor'], on:['カ'], kun:['はな'],
    words:[{w:'花',f:'はな',m:'flor',l:'N5'},{w:'花見',f:'はなみ',m:'contemplación de cerezos',l:'N5'},{w:'花火',f:'はなび',m:'fuegos artificiales',l:'N4'},{w:'花束',f:'はなたば',m:'ramo de flores',l:'N4'},{w:'生花',f:'いけばな',m:'arreglo floral japonés',l:'N4'},{w:'開花',f:'かいか',m:'florecimiento',l:'N3'},{w:'花粉',f:'かふん',m:'polen',l:'N3'}]},
  { k:'空', level:'N5', meanings:['cielo','vacío'], on:['クウ'], kun:['そら','あ.く','から'],
    words:[{w:'空港',f:'くうこう',m:'aeropuerto',l:'N5'},{w:'空気',f:'くうき',m:'aire',l:'N5'},{w:'青空',f:'あおぞら',m:'cielo azul',l:'N4'},{w:'空間',f:'くうかん',m:'espacio',l:'N4'},{w:'空白',f:'くうはく',m:'espacio en blanco / vacío',l:'N4'},{w:'航空',f:'こうくう',m:'aviación',l:'N4'},{w:'真空',f:'しんくう',m:'vacío (físico)',l:'N3'}]},
  { k:'雨', level:'N5', meanings:['lluvia'], on:['ウ'], kun:['あめ','あま'],
    words:[{w:'雨',f:'あめ',m:'lluvia',l:'N5'},{w:'大雨',f:'おおあめ',m:'lluvia fuerte',l:'N4'},{w:'梅雨',f:'つゆ',m:'temporada de lluvias',l:'N4'},{w:'雨天',f:'うてん',m:'día lluvioso',l:'N4'},{w:'小雨',f:'こさめ',m:'llovizna',l:'N4'},{w:'雨季',f:'うき',m:'estación lluviosa',l:'N3'}]},
  { k:'魚', level:'N5', meanings:['pez','pescado'], on:['ギョ'], kun:['さかな','うお'],
    words:[{w:'魚',f:'さかな',m:'pescado / pez',l:'N5'},{w:'金魚',f:'きんぎょ',m:'pez dorado',l:'N4'},{w:'魚市場',f:'さかなしじょう',m:'mercado de pescado',l:'N4'},{w:'魚介類',f:'ぎょかいるい',m:'mariscos y pescados',l:'N3'},{w:'熱帯魚',f:'ねったいぎょ',m:'pez tropical',l:'N3'}]},
  { k:'母', level:'N5', meanings:['madre'], on:['ボ'], kun:['はは'],
    words:[{w:'母',f:'はは',m:'madre',l:'N5'},{w:'お母さん',f:'おかあさん',m:'madre (respetuoso)',l:'N5'},{w:'母語',f:'ぼご',m:'lengua materna',l:'N4'},{w:'父母',f:'ふぼ',m:'padres',l:'N4'}]},
  { k:'父', level:'N5', meanings:['padre'], on:['フ'], kun:['ちち'],
    words:[{w:'父',f:'ちち',m:'padre',l:'N5'},{w:'お父さん',f:'おとうさん',m:'padre (respetuoso)',l:'N5'},{w:'父親',f:'ちちおや',m:'padre',l:'N4'},{w:'父母',f:'ふぼ',m:'padres',l:'N4'}]},
  { k:'女', level:'N5', meanings:['mujer','hembra'], on:['ジョ','ニョ'], kun:['おんな'],
    words:[{w:'女の人',f:'おんなのひと',m:'mujer',l:'N5'},{w:'女性',f:'じょせい',m:'mujer / femenino',l:'N4'},{w:'女優',f:'じょゆう',m:'actriz',l:'N4'},{w:'少女',f:'しょうじょ',m:'chica joven',l:'N4'}]},
  { k:'男', level:'N5', meanings:['hombre','varón'], on:['ダン','ナン'], kun:['おとこ'],
    words:[{w:'男の人',f:'おとこのひと',m:'hombre',l:'N5'},{w:'男性',f:'だんせい',m:'hombre / masculino',l:'N4'},{w:'男優',f:'だんゆう',m:'actor',l:'N4'},{w:'長男',f:'ちょうなん',m:'hijo mayor',l:'N4'}]},
  { k:'子', level:'N5', meanings:['niño','hijo'], on:['シ','ス'], kun:['こ'],
    words:[{w:'子供',f:'こども',m:'niño',l:'N5'},{w:'子育て',f:'こそだて',m:'crianza de hijos',l:'N4'},{w:'女子',f:'じょし',m:'chica',l:'N4'},{w:'男子',f:'だんし',m:'chico',l:'N4'}]},
  { k:'四', level:'N5', meanings:['cuatro'], on:['シ'], kun:['よ','よっ'],
    words:[{w:'四日',f:'よっか',m:'cuatro días / día 4',l:'N5'},{w:'四つ',f:'よっつ',m:'cuatro cosas',l:'N5'},{w:'四月',f:'しがつ',m:'abril',l:'N5'},{w:'四季',f:'しき',m:'cuatro estaciones',l:'N4'}]},
  { k:'五', level:'N5', meanings:['cinco'], on:['ゴ'], kun:['いつ'],
    words:[{w:'五日',f:'いつか',m:'cinco días / día 5',l:'N5'},{w:'五つ',f:'いつつ',m:'cinco cosas',l:'N5'},{w:'五月',f:'ごがつ',m:'mayo',l:'N5'},{w:'五分',f:'ごふん',m:'cinco minutos',l:'N5'},{w:'五感',f:'ごかん',m:'los cinco sentidos',l:'N3'}]},
  { k:'六', level:'N5', meanings:['seis'], on:['ロク'], kun:['む','むっ'],
    words:[{w:'六日',f:'むいか',m:'seis días / día 6',l:'N5'},{w:'六つ',f:'むっつ',m:'seis cosas',l:'N5'},{w:'六月',f:'ろくがつ',m:'junio',l:'N5'},{w:'六時',f:'ろくじ',m:'las seis',l:'N5'},{w:'六本木',f:'ろっぽんぎ',m:'Roppongi (barrio de Tokio)',l:'N4'}]},
  { k:'七', level:'N5', meanings:['siete'], on:['シチ'], kun:['なな'],
    words:[{w:'七日',f:'なのか',m:'siete días / día 7',l:'N5'},{w:'七つ',f:'ななつ',m:'siete cosas',l:'N5'},{w:'七月',f:'しちがつ',m:'julio',l:'N5'},{w:'七時',f:'しちじ',m:'las siete',l:'N5'},{w:'七夕',f:'たなばた',m:'festival Tanabata (7 de julio)',l:'N4'}]},
  { k:'八', level:'N5', meanings:['ocho'], on:['ハチ'], kun:['や','やっ'],
    words:[{w:'八日',f:'ようか',m:'ocho días / día 8',l:'N5'},{w:'八つ',f:'やっつ',m:'ocho cosas',l:'N5'},{w:'八月',f:'はちがつ',m:'agosto',l:'N5'},{w:'八時',f:'はちじ',m:'las ocho',l:'N5'},{w:'八百屋',f:'やおや',m:'verdulería',l:'N4'}]},
  { k:'九', level:'N5', meanings:['nueve'], on:['キュウ','ク'], kun:['ここの'],
    words:[{w:'九日',f:'ここのか',m:'nueve días / día 9',l:'N5'},{w:'九つ',f:'ここのつ',m:'nueve cosas',l:'N5'},{w:'九月',f:'くがつ',m:'septiembre',l:'N5'},{w:'九時',f:'くじ',m:'las nueve',l:'N5'},{w:'九州',f:'きゅうしゅう',m:'Kyushu (isla de Japón)',l:'N4'}]},
  { k:'百', level:'N5', meanings:['cien'], on:['ヒャク'], kun:[],
    words:[{w:'百円',f:'ひゃくえん',m:'100 yenes',l:'N5'},{w:'百万',f:'ひゃくまん',m:'un millón',l:'N5'},{w:'三百',f:'さんびゃく',m:'trescientos',l:'N5'},{w:'数百',f:'すうひゃく',m:'varios cientos',l:'N4'},{w:'百科事典',f:'ひゃっかじてん',m:'enciclopedia',l:'N3'}]},
  { k:'千', level:'N5', meanings:['mil'], on:['セン'], kun:['ち'],
    words:[{w:'千円',f:'せんえん',m:'1000 yenes',l:'N5'},{w:'三千',f:'さんぜん',m:'tres mil',l:'N5'},{w:'千葉',f:'ちば',m:'Chiba',l:'N5'},{w:'数千',f:'すうせん',m:'varios miles',l:'N4'},{w:'千代田',f:'ちよだ',m:'Chiyoda (barrio de Tokio)',l:'N4'}]},
  { k:'万', level:'N5', meanings:['diez mil'], on:['マン','バン'], kun:[],
    words:[{w:'一万円',f:'いちまんえん',m:'10.000 yenes',l:'N5'},{w:'百万',f:'ひゃくまん',m:'un millón',l:'N5'},{w:'万年筆',f:'まんねんひつ',m:'pluma estilográfica',l:'N4'},{w:'万が一',f:'まんがいち',m:'por si acaso',l:'N4'},{w:'万国',f:'ばんこく',m:'todas las naciones',l:'N3'}]},
  { k:'高', level:'N5', meanings:['alto','caro'], on:['コウ'], kun:['たか.い'],
    words:[{w:'高い',f:'たかい',m:'alto / caro',l:'N5'},{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},{w:'高校生',f:'こうこうせい',m:'estudiante de bachillerato',l:'N5'},{w:'最高',f:'さいこう',m:'el mejor / máximo',l:'N4'},{w:'高速',f:'こうそく',m:'alta velocidad',l:'N4'},{w:'高齢',f:'こうれい',m:'edad avanzada',l:'N3'},{w:'高度',f:'こうど',m:'altitud / alto nivel',l:'N3'}]},
  { k:'安', level:'N5', meanings:['barato','seguro'], on:['アン'], kun:['やす.い'],
    words:[{w:'安い',f:'やすい',m:'barato',l:'N5'},{w:'安全',f:'あんぜん',m:'seguridad',l:'N4'},{w:'安心',f:'あんしん',m:'tranquilidad',l:'N4'},{w:'不安',f:'ふあん',m:'inquietud',l:'N4'}]},
  { k:'新', level:'N5', meanings:['nuevo'], on:['シン'], kun:['あたら.しい','にい'],
    words:[{w:'新しい',f:'あたらしい',m:'nuevo',l:'N5'},{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'},{w:'新年',f:'しんねん',m:'año nuevo',l:'N5'},{w:'新幹線',f:'しんかんせん',m:'tren bala',l:'N4'},{w:'最新',f:'さいしん',m:'lo más reciente',l:'N4'},{w:'新鮮',f:'しんせん',m:'fresco / novedoso',l:'N4'},{w:'革新',f:'かくしん',m:'innovación',l:'N3'}]},
  { k:'古', level:'N5', meanings:['antiguo','viejo'], on:['コ'], kun:['ふる.い'],
    words:[{w:'古い',f:'ふるい',m:'viejo / antiguo',l:'N5'},{w:'中古',f:'ちゅうこ',m:'segunda mano',l:'N4'},{w:'古典',f:'こてん',m:'clásico',l:'N4'},{w:'古代',f:'こだい',m:'antigüedad',l:'N4'},{w:'古着',f:'ふるぎ',m:'ropa de segunda mano',l:'N4'},{w:'考古学',f:'こうこがく',m:'arqueología',l:'N3'}]},
  { k:'多', level:'N5', meanings:['mucho','abundante'], on:['タ'], kun:['おお.い'],
    words:[{w:'多い',f:'おおい',m:'mucho / muchos',l:'N5'},{w:'多分',f:'たぶん',m:'probablemente',l:'N5'},{w:'多数',f:'たすう',m:'mayoría',l:'N4'},{w:'多様',f:'たよう',m:'diverso',l:'N3'}]},
  { k:'少', level:'N5', meanings:['poco','joven'], on:['ショウ'], kun:['すく.ない','すこ.し'],
    words:[{w:'少ない',f:'すくない',m:'poco',l:'N5'},{w:'少し',f:'すこし',m:'un poco',l:'N5'},{w:'少女',f:'しょうじょ',m:'chica joven',l:'N4'},{w:'少年',f:'しょうねん',m:'chico joven',l:'N4'}]},
  { k:'長', level:'N5', meanings:['largo','jefe'], on:['チョウ'], kun:['なが.い'],
    words:[{w:'長い',f:'ながい',m:'largo',l:'N5'},{w:'社長',f:'しゃちょう',m:'presidente de empresa',l:'N4'},{w:'校長',f:'こうちょう',m:'director de escuela',l:'N4'},{w:'成長',f:'せいちょう',m:'crecimiento',l:'N4'}]},
  { k:'店', level:'N5', meanings:['tienda'], on:['テン'], kun:['みせ'],
    words:[{w:'お店',f:'おみせ',m:'tienda',l:'N5'},{w:'書店',f:'しょてん',m:'librería',l:'N5'},{w:'店員',f:'てんいん',m:'dependiente',l:'N4'},{w:'飲食店',f:'いんしょくてん',m:'restaurante',l:'N4'}]},
  { k:'飲', level:'N5', meanings:['beber'], on:['イン'], kun:['の.む'],
    words:[{w:'飲む',f:'のむ',m:'beber',l:'N5'},{w:'飲み物',f:'のみもの',m:'bebida',l:'N5'},{w:'飲食店',f:'いんしょくてん',m:'restaurante',l:'N4'},{w:'飲料水',f:'いんりょうすい',m:'agua potable',l:'N4'}]},

]
