import type { Kanji } from './types'

// N2: 203 kanji

export const kanjiN2: Kanji[] = [
  { rank:623, k:'並', level:'N2', meanings:['alinearse / estar en fila'], on:['ヘイ'], kun:['なら.ぶ'],
    words:[{w:'並行',f:'へいこう',m:'en paralelo / simultáneo',l:'N2'},{w:'並木',f:'なみき',m:'hilera de árboles',l:'N2'}]},
  { rank:626, k:'乱', level:'N2', meanings:['desorden / caos'], on:['ラン'], kun:['みだ.れる'],
    words:[{w:'混乱',f:'こんらん',m:'confusión / caos',l:'N2'},{w:'乱暴',f:'らんぼう',m:'violencia / brusquedad',l:'N2'}]},
  { rank:628, k:'乾', level:'N2', meanings:['secar / seco'], on:['カン'], kun:['かわ.く'],
    words:[{w:'乾杯',f:'かんぱい',m:'¡Salud! / brindis',l:'N4'},{w:'乾燥',f:'かんそう',m:'sequedad / desecación',l:'N2'},{w:'乾電池',f:'かんでんち',m:'pila seca',l:'N2'}]},
  { rank:629, k:'了', level:'N2', meanings:['terminar / completar'], on:['リョウ'], kun:[],
    words:[{w:'了解',f:'りょうかい',m:'entendido / comprensión',l:'N3'},{w:'終了',f:'しゅうりょう',m:'finalización',l:'N3'},{w:'完了',f:'かんりょう',m:'finalización / completado',l:'N2'},{w:'修了',f:'しゅうりょう',m:'finalización de un curso',l:'N1'}]},
  { rank:632, k:'令', level:'N2', meanings:['orden / mandato'], on:['レイ'], kun:[],
    words:[{w:'命令',f:'めいれい',m:'orden / mandato',l:'N3'},{w:'法令',f:'ほうれい',m:'ley / decreto',l:'N1'},{w:'指令',f:'しれい',m:'orden / directiva',l:'N1'}]},
  { rank:635, k:'伺', level:'N2', meanings:['visitar / preguntar (humilde)'], on:['シ'], kun:['うかが.う'],
    words:[]},
  { rank:637, k:'依', level:'N2', meanings:['depender / según'], on:['イ'], kun:['よ.る'],
    words:[{w:'依頼',f:'いらい',m:'solicitud / encargo',l:'N3'},{w:'依存',f:'いぞん',m:'dependencia',l:'N2'},{w:'依然',f:'いぜん',m:'todavía / como antes',l:'N1'}]},
  { rank:640, k:'停', level:'N2', meanings:['detener / parar'], on:['テイ'], kun:['と.まる'],
    words:[{w:'停止',f:'ていし',m:'parada / detención',l:'N3'},{w:'停電',f:'ていでん',m:'apagón',l:'N3'},{w:'停車',f:'ていしゃ',m:'parada de vehículo',l:'N2'},{w:'停留所',f:'ていりゅうじょ',m:'parada de autobús',l:'N2'}]},
  { rank:641, k:'傾', level:'N2', meanings:['inclinarse / tender a'], on:['ケイ'], kun:['かたむ.く'],
    words:[{w:'傾向',f:'けいこう',m:'tendencia',l:'N3'},{w:'傾斜',f:'けいしゃ',m:'inclinación / pendiente',l:'N1'}]},
  { rank:642, k:'像', level:'N2', meanings:['imagen / estatua'], on:['ゾウ'], kun:[],
    words:[{w:'映像',f:'えいぞう',m:'imagen / video',l:'N4'},{w:'想像',f:'そうぞう',m:'imaginación',l:'N3'},{w:'画像',f:'がぞう',m:'imagen / foto',l:'N2'},{w:'銅像',f:'どうぞう',m:'estatua de bronce',l:'N2'}]},
  { rank:646, k:'党', level:'N2', meanings:['partido político'], on:['トウ'], kun:[],
    words:[{w:'政党',f:'せいとう',m:'partido político',l:'N2'},{w:'与党',f:'よとう',m:'partido gobernante',l:'N1'}]},
  { rank:647, k:'兵', level:'N2', meanings:['soldado / tropa'], on:['ヘイ'], kun:[],
    words:[{w:'兵士',f:'へいし',m:'soldado',l:'N2'},{w:'兵器',f:'へいき',m:'armamento',l:'N1'}]},
  { rank:650, k:'凍', level:'N2', meanings:['congelar'], on:['トウ'], kun:['こお.る'],
    words:[{w:'冷凍',f:'れいとう',m:'congelación',l:'N2'},{w:'凍結',f:'とうけつ',m:'congelación / helada',l:'N1'}]},
  { rank:651, k:'刊', level:'N2', meanings:['publicar / edición'], on:['カン'], kun:[],
    words:[{w:'週刊',f:'しゅうかん',m:'semanal',l:'N4'},{w:'朝刊',f:'ちょうかん',m:'periódico matutino',l:'N2'},{w:'夕刊',f:'ゆうかん',m:'periódico vespertino',l:'N2'}]},
  { rank:652, k:'刷', level:'N2', meanings:['imprimir'], on:['サツ'], kun:['す.る'],
    words:[{w:'印刷',f:'いんさつ',m:'impresión',l:'N2'},{w:'刷新',f:'さっしん',m:'renovación',l:'N1'}]},
  { rank:653, k:'券', level:'N2', meanings:['billete / bono'], on:['ケン'], kun:[],
    words:[{w:'乗車券',f:'じょうしゃけん',m:'billete de transporte',l:'N2'},{w:'定期券',f:'ていきけん',m:'abono de transporte',l:'N2'}]},
  { rank:654, k:'刺', level:'N2', meanings:['pinchar / tarjeta'], on:['シ'], kun:['さ.す'],
    words:[{w:'名刺',f:'めいし',m:'tarjeta de visita',l:'N4'},{w:'刺激',f:'しげき',m:'estímulo',l:'N2'},{w:'刺身',f:'さしみ',m:'sashimi',l:'N2'}]},
  { rank:655, k:'則', level:'N2', meanings:['regla / norma'], on:['ソク'], kun:[],
    words:[{w:'規則',f:'きそく',m:'regla / norma',l:'N4'},{w:'原則',f:'げんそく',m:'principio / regla general',l:'N3'},{w:'法則',f:'ほうそく',m:'ley / principio',l:'N2'},{w:'反則',f:'はんそく',m:'falta / infracción',l:'N1'}]},
  { rank:657, k:'劇', level:'N2', meanings:['drama / teatro'], on:['ゲキ'], kun:[],
    words:[{w:'悲劇',f:'ひげき',m:'tragedia',l:'N3'},{w:'劇場',f:'げきじょう',m:'teatro',l:'N2'},{w:'演劇',f:'えんげき',m:'drama / teatro',l:'N1'}]},
  { rank:659, k:'募', level:'N2', meanings:['reclutar / reunir'], on:['ボ'], kun:['つの.む'],
    words:[{w:'募集',f:'ぼしゅう',m:'reclutamiento / convocatoria',l:'N2'},{w:'応募',f:'おうぼ',m:'solicitud / inscripción',l:'N2'}]},
  { rank:660, k:'勢', level:'N2', meanings:['fuerza / ímpetu'], on:['セイ'], kun:['いきお.い'],
    words:[{w:'姿勢',f:'しせい',m:'postura / actitud',l:'N2'},{w:'勢力',f:'せいりょく',m:'poder / influencia',l:'N1'}]},
  { rank:665, k:'協', level:'N2', meanings:['cooperación'], on:['キョウ'], kun:[],
    words:[{w:'協力',f:'きょうりょく',m:'cooperación',l:'N4'},{w:'協会',f:'きょうかい',m:'asociación',l:'N2'},{w:'協調',f:'きょうちょう',m:'cooperación / armonía',l:'N1'}]},
  { rank:666, k:'占', level:'N2', meanings:['adivinar / ocupar'], on:['セン'], kun:['し.める'],
    words:[{w:'占領',f:'せんりょう',m:'ocupación / dominio',l:'N2'},{w:'独占',f:'どくせん',m:'monopolio',l:'N1'},{w:'占拠',f:'せんきょ',m:'ocupación',l:'N1'}]},
  { rank:667, k:'印', level:'N2', meanings:['sello / marca'], on:['イン'], kun:['しるし'],
    words:[{w:'印象',f:'いんしょう',m:'impresión / sensación',l:'N2'},{w:'印刷',f:'いんさつ',m:'impresión',l:'N2'}]},
  { rank:675, k:'含', level:'N2', meanings:['incluir / contener'], on:['ガン'], kun:['ふく.む'],
    words:[]},
  { rank:676, k:'周', level:'N2', meanings:['alrededor / perímetro'], on:['シュウ'], kun:['まわ.り'],
    words:[{w:'周辺',f:'しゅうへん',m:'alrededores / periferia',l:'N2'},{w:'周囲',f:'しゅうい',m:'entorno / perímetro',l:'N2'},{w:'周期',f:'しゅうき',m:'ciclo / periodo',l:'N1'},{w:'一周',f:'いっしゅう',m:'una vuelta',l:'N2'}]},
  { rank:677, k:'咲', level:'N2', meanings:['florecer'], on:[], kun:['さ.く'],
    words:[]},
  { rank:678, k:'喫', level:'N2', meanings:['beber / fumar'], on:['キツ'], kun:[],
    words:[{w:'喫茶店',f:'きっさてん',m:'cafetería',l:'N4'},{w:'喫煙',f:'きつえん',m:'fumar',l:'N2'},{w:'満喫',f:'まんきつ',m:'disfrutar plenamente',l:'N1'}]},
  { rank:679, k:'営', level:'N2', meanings:['gestionar / operar'], on:['エイ'], kun:['いとな.む'],
    words:[{w:'営業',f:'えいぎょう',m:'negocio / ventas',l:'N3'},{w:'経営',f:'けいえい',m:'gestión / administración',l:'N3'},{w:'運営',f:'うんえい',m:'gestión / operación',l:'N2'},{w:'経営者',f:'けいえいしゃ',m:'empresario / gestor',l:'N2'}]},
  { rank:681, k:'囲', level:'N2', meanings:['rodear / cercar'], on:['イ'], kun:['かこ.む'],
    words:[{w:'範囲',f:'はんい',m:'rango / alcance',l:'N2'},{w:'周囲',f:'しゅうい',m:'alrededores',l:'N2'}]},
  { rank:682, k:'固', level:'N2', meanings:['sólido / firme'], on:['コ'], kun:['かた.い'],
    words:[{w:'固定',f:'こてい',m:'fijación / fijo',l:'N2'},{w:'固有',f:'こゆう',m:'inherente / propio',l:'N2'},{w:'固体',f:'こたい',m:'sólido',l:'N2'},{w:'頑固',f:'がんこ',m:'terco / obstinado',l:'N1'}]},
  { rank:683, k:'圧', level:'N2', meanings:['presión'], on:['アツ'], kun:[],
    words:[{w:'圧力',f:'あつりょく',m:'presión',l:'N2'},{w:'気圧',f:'きあつ',m:'presión atmosférica',l:'N2'}]},
  { rank:687, k:'埋', level:'N2', meanings:['enterrar / rellenar'], on:['マイ'], kun:['う.める'],
    words:[{w:'埋葬',f:'まいそう',m:'entierro / sepultura',l:'N1'}]},
  { rank:688, k:'城', level:'N2', meanings:['castillo'], on:['ジョウ'], kun:['しろ'],
    words:[{w:'城主',f:'じょうしゅ',m:'señor del castillo',l:'N1'},{w:'城下町',f:'じょうかまち',m:'ciudad castillo',l:'N1'},{w:'城壁',f:'じょうへき',m:'muralla del castillo',l:'N1'}]},
  { rank:689, k:'域', level:'N2', meanings:['zona / región'], on:['イキ'], kun:[],
    words:[{w:'地域',f:'ちいき',m:'región / zona',l:'N3'},{w:'区域',f:'くいき',m:'zona / sector',l:'N2'},{w:'領域',f:'りょういき',m:'dominio / área',l:'N1'}]},
  { rank:690, k:'塔', level:'N2', meanings:['torre / pagoda'], on:['トウ'], kun:[],
    words:[{w:'鉄塔',f:'てっとう',m:'torre de acero',l:'N1'},{w:'五重塔',f:'ごじゅうのとう',m:'pagoda de cinco pisos',l:'N1'}]},
  { rank:691, k:'塗', level:'N2', meanings:['pintar / aplicar'], on:['ト'], kun:['ぬ.る'],
    words:[{w:'塗装',f:'とそう',m:'pintura / recubrimiento',l:'N1'}]},
  { rank:693, k:'境', level:'N2', meanings:['frontera / límite'], on:['キョウ'], kun:['さかい'],
    words:[{w:'環境',f:'かんきょう',m:'ambiente / entorno',l:'N3'},{w:'境界',f:'きょうかい',m:'frontera / límite',l:'N1'},{w:'国境',f:'こっきょう',m:'frontera nacional',l:'N2'}]},
  { rank:695, k:'奥', level:'N2', meanings:['interior / profundidad'], on:['オウ'], kun:['おく'],
    words:[{w:'山奥',f:'やまおく',m:'interior de la montaña',l:'N2'},{w:'奥歯',f:'おくば',m:'muela',l:'N2'},{w:'奥地',f:'おくち',m:'interior / regiones remotas',l:'N1'}]},
  { rank:697, k:'委', level:'N2', meanings:['delegar / comité'], on:['イ'], kun:[],
    words:[{w:'委員',f:'いいん',m:'miembro de comité',l:'N3'},{w:'委員会',f:'いいんかい',m:'comité',l:'N3'},{w:'委託',f:'いたく',m:'encargo / consignación',l:'N1'},{w:'委任',f:'いにん',m:'delegación',l:'N1'}]},
  { rank:699, k:'孫', level:'N2', meanings:['nieto'], on:['ソン'], kun:['まご'],
    words:[{w:'子孫',f:'しそん',m:'descendiente / descendencia',l:'N2'},{w:'初孫',f:'はつまご',m:'primer nieto',l:'N1'}]},
  { rank:700, k:'宇', level:'N2', meanings:['universo / alero'], on:['ウ'], kun:[],
    words:[{w:'宇宙',f:'うちゅう',m:'universo / espacio',l:'N3'},{w:'宇宙人',f:'うちゅうじん',m:'extraterrestre',l:'N3'},{w:'宇宙船',f:'うちゅうせん',m:'nave espacial',l:'N2'}]},
  { rank:701, k:'宝', level:'N2', meanings:['tesoro'], on:['ホウ'], kun:['たから'],
    words:[{w:'宝物',f:'たからもの',m:'tesoro',l:'N3'},{w:'宝石',f:'ほうせき',m:'joya / gema',l:'N2'},{w:'国宝',f:'こくほう',m:'tesoro nacional',l:'N1'}]},
  { rank:703, k:'封', level:'N2', meanings:['sellar / sobre'], on:['フウ'], kun:['ふう'],
    words:[{w:'封筒',f:'ふうとう',m:'sobre (correo)',l:'N3'},{w:'開封',f:'かいふう',m:'abrir un sobre',l:'N2'},{w:'封鎖',f:'ふうさ',m:'bloqueo / cierre',l:'N1'}]},
  { rank:704, k:'専', level:'N2', meanings:['especializado / exclusivo'], on:['セン'], kun:['もっぱ.ら'],
    words:[{w:'専門',f:'せんもん',m:'especialidad',l:'N3'},{w:'専攻',f:'せんこう',m:'especialidad / carrera',l:'N2'},{w:'専用',f:'せんよう',m:'uso exclusivo',l:'N2'}]},
  { rank:705, k:'将', level:'N2', meanings:['general / futuro'], on:['ショウ'], kun:[],
    words:[{w:'将来',f:'しょうらい',m:'futuro',l:'N4'},{w:'将棋',f:'しょうぎ',m:'shogi (ajedrez japonés)',l:'N2'},{w:'将軍',f:'しょうぐん',m:'general / shogun',l:'N1'}]},
  { rank:706, k:'尊', level:'N2', meanings:['respetar / valioso'], on:['ソン'], kun:[],
    words:[{w:'尊敬',f:'そんけい',m:'respeto / admiración',l:'N2'},{w:'尊重',f:'そんちょう',m:'consideración / respeto',l:'N2'}]},
  { rank:707, k:'導', level:'N2', meanings:['guiar / liderar'], on:['ドウ'], kun:['みちび.く'],
    words:[{w:'指導',f:'しどう',m:'guía / instrucción',l:'N3'},{w:'導入',f:'どうにゅう',m:'introducción / implantación',l:'N1'}]},
  { rank:708, k:'届', level:'N2', meanings:['llegar / entregar'], on:[], kun:['とど.く'],
    words:[]},
  { rank:709, k:'層', level:'N2', meanings:['capa / estrato'], on:['ソウ'], kun:[],
    words:[{w:'高層',f:'こうそう',m:'de gran altura',l:'N2'},{w:'地層',f:'ちそう',m:'estrato geológico',l:'N1'}]},
  { rank:715, k:'巻', level:'N2', meanings:['enrollar / volumen'], on:['カン'], kun:['ま.く'],
    words:[{w:'圧巻',f:'あっかん',m:'lo más destacado',l:'N1'},{w:'巻末',f:'かんまつ',m:'final del libro',l:'N1'}]},
  { rank:716, k:'布', level:'N2', meanings:['tela / difundir'], on:['フ'], kun:['ぬの'],
    words:[{w:'財布',f:'さいふ',m:'cartera / billetera',l:'N5'},{w:'布団',f:'ふとん',m:'futón / edredón',l:'N4'},{w:'分布',f:'ぶんぷ',m:'distribución',l:'N2'},{w:'毛布',f:'もうふ',m:'manta',l:'N2'}]},
  { rank:719, k:'帽', level:'N2', meanings:['sombrero / gorra'], on:['ボウ'], kun:[],
    words:[{w:'帽子',f:'ぼうし',m:'sombrero',l:'N5'},{w:'脱帽',f:'だつぼう',m:'quitarse el sombrero / admiración',l:'N1'}]},
  { rank:720, k:'幅', level:'N2', meanings:['anchura / margen'], on:['フク'], kun:['はば'],
    words:[{w:'大幅',f:'おおはば',m:'a gran escala / sustancial',l:'N2'},{w:'道幅',f:'みちはば',m:'anchura del camino',l:'N2'}]},
  { rank:723, k:'庁', level:'N2', meanings:['agencia gubernamental'], on:['チョウ'], kun:[],
    words:[{w:'官庁',f:'かんちょう',m:'agencia del gobierno',l:'N3'},{w:'県庁',f:'けんちょう',m:'gobierno prefectural',l:'N2'}]},
  { rank:724, k:'床', level:'N2', meanings:['suelo / cama'], on:['ショウ'], kun:['ゆか','とこ'],
    words:[{w:'床屋',f:'とこや',m:'barbería',l:'N3'},{w:'起床',f:'きしょう',m:'levantarse de la cama',l:'N1'}]},
  { rank:728, k:'延', level:'N2', meanings:['extenderse / posponer'], on:['エン'], kun:['の.ばす'],
    words:[{w:'延期',f:'えんき',m:'aplazamiento',l:'N3'},{w:'延長',f:'えんちょう',m:'prolongación / prórroga',l:'N2'},{w:'遅延',f:'ちえん',m:'retraso',l:'N1'}]},
  { rank:729, k:'律', level:'N2', meanings:['ley / ritmo'], on:['リツ'], kun:[],
    words:[{w:'法律',f:'ほうりつ',m:'ley',l:'N3'},{w:'規律',f:'きりつ',m:'disciplina / orden',l:'N1'},{w:'一律',f:'いちりつ',m:'uniforme / por igual',l:'N1'}]},
  { rank:731, k:'快', level:'N2', meanings:['agradable / veloz'], on:['カイ'], kun:['こころよ.い'],
    words:[{w:'快適',f:'かいてき',m:'cómodo / agradable',l:'N3'},{w:'快速',f:'かいそく',m:'rápido (tren)',l:'N2'},{w:'快晴',f:'かいせい',m:'cielo despejado',l:'N1'}]},
  { rank:733, k:'患', level:'N2', meanings:['padecer (enfermedad)'], on:['カン'], kun:['わずら.う'],
    words:[{w:'患者',f:'かんじゃ',m:'paciente',l:'N3'},{w:'疾患',f:'しっかん',m:'enfermedad / dolencia',l:'N1'}]},
  { rank:735, k:'憎', level:'N2', meanings:['odiar / detestar'], on:['ゾウ'], kun:['にく.む'],
    words:[{w:'憎悪',f:'ぞうお',m:'odio / aborrecimiento',l:'N2'},{w:'愛憎',f:'あいぞう',m:'amor y odio',l:'N1'}]},
  { rank:737, k:'承', level:'N2', meanings:['aceptar / recibir'], on:['ショウ'], kun:[],
    words:[{w:'承知',f:'しょうち',m:'entendido / conformidad',l:'N3'},{w:'承認',f:'しょうにん',m:'aprobación / reconocimiento',l:'N1'},{w:'了承',f:'りょうしょう',m:'consentimiento',l:'N1'}]},
  { rank:740, k:'拝', level:'N2', meanings:['venerar / (humilde)'], on:['ハイ'], kun:['おが.む'],
    words:[{w:'拝見',f:'はいけん',m:'ver (humilde)',l:'N2'},{w:'参拝',f:'さんぱい',m:'visita a un templo',l:'N1'}]},
  { rank:742, k:'挟', level:'N2', meanings:['atrapar entre / intercalar'], on:['キョウ'], kun:['はさ.む'],
    words:[]},
  { rank:743, k:'捜', level:'N2', meanings:['buscar / investigar'], on:['ソウ'], kun:['さが.す'],
    words:[{w:'捜査',f:'そうさ',m:'investigación policial',l:'N1'},{w:'捜索',f:'そうさく',m:'búsqueda',l:'N1'}]},
  { rank:745, k:'掃', level:'N2', meanings:['barrer / limpiar'], on:['ソウ'], kun:['は.く'],
    words:[{w:'掃除',f:'そうじ',m:'limpieza',l:'N5'},{w:'掃除機',f:'そうじき',m:'aspiradora',l:'N3'},{w:'清掃',f:'せいそう',m:'limpieza',l:'N1'}]},
  { rank:746, k:'掘', level:'N2', meanings:['excavar / cavar'], on:['クツ'], kun:['ほ.る'],
    words:[{w:'発掘',f:'はっくつ',m:'excavación',l:'N1'},{w:'採掘',f:'さいくつ',m:'extracción / minería',l:'N1'}]},
  { rank:747, k:'採', level:'N2', meanings:['recoger / adoptar'], on:['サイ'], kun:['と.る'],
    words:[{w:'採用',f:'さいよう',m:'adopción / contratación',l:'N2'},{w:'採点',f:'さいてん',m:'calificación',l:'N2'}]},
  { rank:749, k:'換', level:'N2', meanings:['intercambiar / cambiar'], on:['カン'], kun:['か.える'],
    words:[{w:'交換',f:'こうかん',m:'intercambio',l:'N3'},{w:'換気',f:'かんき',m:'ventilación',l:'N3'}]},
  { rank:750, k:'損', level:'N2', meanings:['dañar / pérdida'], on:['ソン'], kun:['そこ.なう'],
    words:[{w:'損害',f:'そんがい',m:'daño / perjuicio',l:'N1'},{w:'損失',f:'そんしつ',m:'pérdida',l:'N1'}]},
  { rank:751, k:'改', level:'N2', meanings:['reformar / cambiar'], on:['カイ'], kun:['あらた.める'],
    words:[{w:'改札',f:'かいさつ',m:'control de billetes',l:'N2'},{w:'改善',f:'かいぜん',m:'mejora',l:'N2'}]},
  { rank:752, k:'敬', level:'N2', meanings:['respetar'], on:['ケイ'], kun:['うやま.う'],
    words:[{w:'敬語',f:'けいご',m:'lenguaje honorífico',l:'N3'},{w:'尊敬',f:'そんけい',m:'respeto / admiración',l:'N2'},{w:'敬意',f:'けいい',m:'respeto / deferencia',l:'N1'}]},
  { rank:754, k:'昇', level:'N2', meanings:['ascender / subir'], on:['ショウ'], kun:['のぼ.る'],
    words:[{w:'上昇',f:'じょうしょう',m:'ascenso / subida',l:'N3'},{w:'昇進',f:'しょうしん',m:'ascenso (laboral)',l:'N1'},{w:'昇給',f:'しょうきゅう',m:'aumento de sueldo',l:'N1'}]},
  { rank:756, k:'普', level:'N2', meanings:['general / común'], on:['フ'], kun:[],
    words:[{w:'普通',f:'ふつう',m:'normal / ordinario',l:'N4'},{w:'普段',f:'ふだん',m:'habitualmente',l:'N3'},{w:'普及',f:'ふきゅう',m:'difusión / popularización',l:'N1'}]},
  { rank:757, k:'暴', level:'N2', meanings:['violencia / revelar'], on:['ボウ'], kun:['あば.く'],
    words:[{w:'暴力',f:'ぼうりょく',m:'violencia',l:'N2'},{w:'暴動',f:'ぼうどう',m:'disturbio / motín',l:'N1'}]},
  { rank:759, k:'替', level:'N2', meanings:['sustituir / cambiar'], on:['タイ'], kun:['か.える'],
    words:[{w:'着替え',f:'きがえ',m:'ropa de repuesto / cambiarse',l:'N4'},{w:'両替',f:'りょうがえ',m:'cambio de moneda',l:'N3'},{w:'交替',f:'こうたい',m:'turno / relevo',l:'N2'},{w:'為替',f:'かわせ',m:'cambio de divisas',l:'N1'}]},
  { rank:760, k:'札', level:'N2', meanings:['billete / etiqueta'], on:['サツ'], kun:['ふだ'],
    words:[{w:'名札',f:'なふだ',m:'etiqueta con nombre',l:'N3'},{w:'改札',f:'かいさつ',m:'control de billetes',l:'N2'},{w:'表札',f:'ひょうさつ',m:'placa con el nombre',l:'N1'}]},
  { rank:767, k:'枝', level:'N2', meanings:['rama'], on:['シ'], kun:['えだ'],
    words:[{w:'枝豆',f:'えだまめ',m:'edamame / habas de soja',l:'N3'},{w:'小枝',f:'こえだ',m:'ramita',l:'N1'}]},
  { rank:768, k:'枯', level:'N2', meanings:['marchitarse / seco'], on:['コ'], kun:['か.れる'],
    words:[]},
  { rank:769, k:'柔', level:'N2', meanings:['suave / flexible'], on:['ジュウ'], kun:['やわ.らか'],
    words:[{w:'柔道',f:'じゅうどう',m:'judo',l:'N4'},{w:'柔軟',f:'じゅうなん',m:'flexible / blando',l:'N1'}]},
  { rank:772, k:'栄', level:'N2', meanings:['prosperar / gloria'], on:['エイ'], kun:['さか.える'],
    words:[{w:'栄養',f:'えいよう',m:'nutrición',l:'N3'},{w:'栄光',f:'えいこう',m:'gloria',l:'N1'},{w:'繁栄',f:'はんえい',m:'prosperidad',l:'N1'}]},
  { rank:776, k:'核', level:'N2', meanings:['núcleo / nuclear'], on:['カク'], kun:[],
    words:[{w:'核心',f:'かくしん',m:'núcleo / esencia',l:'N2'},{w:'核兵器',f:'かくへいき',m:'arma nuclear',l:'N2'},{w:'結核',f:'けっかく',m:'tuberculosis',l:'N1'}]},
  { rank:778, k:'極', level:'N2', meanings:['extremo / polo'], on:['キョク'], kun:['きわ.める'],
    words:[{w:'南極',f:'なんきょく',m:'Antártida / polo sur',l:'N3'},{w:'積極的',f:'せっきょくてき',m:'activo / positivo',l:'N3'},{w:'北極',f:'ほっきょく',m:'Polo Norte',l:'N2'},{w:'極端',f:'きょくたん',m:'extremo',l:'N1'}]},
  { rank:781, k:'武', level:'N2', meanings:['militar / marcial'], on:['ブ'], kun:[],
    words:[{w:'武器',f:'ぶき',m:'arma',l:'N2'},{w:'武士',f:'ぶし',m:'samurái / guerrero',l:'N2'}]},
  { rank:783, k:'殿', level:'N2', meanings:['señor / palacio'], on:['デン'], kun:['との'],
    words:[{w:'殿様',f:'とのさま',m:'señor feudal',l:'N2'},{w:'神殿',f:'しんでん',m:'templo / santuario',l:'N1'}]},
  { rank:784, k:'毒', level:'N2', meanings:['veneno'], on:['ドク'], kun:[],
    words:[{w:'中毒',f:'ちゅうどく',m:'intoxicación / adicción',l:'N2'},{w:'毒薬',f:'どくやく',m:'veneno / sustancia tóxica',l:'N2'},{w:'消毒',f:'しょうどく',m:'desinfección',l:'N2'},{w:'毒舌',f:'どくぜつ',m:'lengua viperina',l:'N1'}]},
  { rank:785, k:'比', level:'N2', meanings:['comparar / proporción'], on:['ヒ'], kun:['くら.べる'],
    words:[{w:'比較',f:'ひかく',m:'comparación',l:'N2'},{w:'比例',f:'ひれい',m:'proporción',l:'N1'}]},
  { rank:790, k:'汚', level:'N2', meanings:['ensuciar / contaminar'], on:['オ'], kun:['よご.れる'],
    words:[{w:'汚染',f:'おせん',m:'contaminación',l:'N2'},{w:'汚物',f:'おぶつ',m:'suciedad / basura',l:'N2'}]},
  { rank:792, k:'沈', level:'N2', meanings:['hundir / sumergir'], on:['チン'], kun:['しず.む'],
    words:[{w:'沈黙',f:'ちんもく',m:'silencio',l:'N1'},{w:'沈没',f:'ちんぼつ',m:'hundimiento',l:'N1'}]},
  { rank:794, k:'沸', level:'N2', meanings:['hervir'], on:['フツ'], kun:['わ.く'],
    words:[{w:'沸騰',f:'ふっとう',m:'ebullición',l:'N1'}]},
  { rank:796, k:'況', level:'N2', meanings:['situación / circunstancia'], on:['キョウ'], kun:[],
    words:[{w:'状況',f:'じょうきょう',m:'situación',l:'N2'},{w:'不況',f:'ふきょう',m:'recesión económica',l:'N1'}]},
  { rank:797, k:'泉', level:'N2', meanings:['manantial / fuente'], on:['セン'], kun:['いずみ'],
    words:[{w:'温泉',f:'おんせん',m:'aguas termales',l:'N3'},{w:'源泉',f:'げんせん',m:'fuente / manantial',l:'N1'}]},
  { rank:799, k:'波', level:'N2', meanings:['ola / onda'], on:['ハ'], kun:['なみ'],
    words:[{w:'津波',f:'つなみ',m:'tsunami',l:'N2'},{w:'音波',f:'おんぱ',m:'onda sonora',l:'N2'},{w:'電波',f:'でんぱ',m:'ondas de radio',l:'N2'},{w:'波長',f:'はちょう',m:'longitud de onda',l:'N1'}]},
  { rank:800, k:'泥', level:'N2', meanings:['barro / lodo'], on:['デイ'], kun:['どろ'],
    words:[{w:'泥棒',f:'どろぼう',m:'ladrón',l:'N3'},{w:'泥沼',f:'どろぬま',m:'ciénaga / atolladero',l:'N1'}]},
  { rank:805, k:'涼', level:'N2', meanings:['fresco / refrescante'], on:['リョウ'], kun:['すず.しい'],
    words:[{w:'清涼',f:'せいりょう',m:'refrescante',l:'N1'}]},
  { rank:806, k:'混', level:'N2', meanings:['mezclar'], on:['コン'], kun:['ま.ざる'],
    words:[{w:'混雑',f:'こんざつ',m:'aglomeración / congestión',l:'N3'},{w:'混合',f:'こんごう',m:'mezcla',l:'N1'},{w:'混乱',f:'こんらん',m:'confusión',l:'N2'}]},
  { rank:807, k:'清', level:'N2', meanings:['limpio / puro'], on:['セイ'], kun:['きよ.める'],
    words:[{w:'清潔',f:'せいけつ',m:'limpieza / higiene',l:'N3'},{w:'清掃',f:'せいそう',m:'limpieza',l:'N1'},{w:'清流',f:'せいりゅう',m:'corriente cristalina',l:'N1'}]},
  { rank:808, k:'減', level:'N2', meanings:['disminuir / reducir'], on:['ゲン'], kun:['へ.らす'],
    words:[{w:'減少',f:'げんしょう',m:'disminución',l:'N2'},{w:'削減',f:'さくげん',m:'recorte / reducción',l:'N1'}]},
  { rank:813, k:'湾', level:'N2', meanings:['bahía'], on:['ワン'], kun:[],
    words:[{w:'台湾',f:'たいわん',m:'Taiwán',l:'N2'},{w:'港湾',f:'こうわん',m:'puerto',l:'N1'}]},
  { rank:814, k:'湿', level:'N2', meanings:['húmedo'], on:['シツ'], kun:['しめ.る'],
    words:[{w:'湿気',f:'しっけ',m:'humedad',l:'N2'},{w:'湿度',f:'しつど',m:'grado de humedad',l:'N2'}]},
  { rank:816, k:'溶', level:'N2', meanings:['disolver / fundir'], on:['ヨウ'], kun:['と.ける'],
    words:[{w:'溶岩',f:'ようがん',m:'lava',l:'N1'}]},
  { rank:817, k:'滴', level:'N2', meanings:['gota'], on:['テキ'], kun:['しずく'],
    words:[{w:'水滴',f:'すいてき',m:'gota de agua',l:'N1'},{w:'点滴',f:'てんてき',m:'gotero / suero',l:'N1'}]},
  { rank:818, k:'漁', level:'N2', meanings:['pesca'], on:['ギョ'], kun:['りょう'],
    words:[{w:'漁業',f:'ぎょぎょう',m:'industria pesquera',l:'N2'},{w:'漁師',f:'りょうし',m:'pescador',l:'N2'}]},
  { rank:819, k:'濃', level:'N2', meanings:['denso / concentrado'], on:['ノウ'], kun:['こ.い'],
    words:[{w:'濃度',f:'のうど',m:'densidad / concentración',l:'N2'},{w:'濃縮',f:'のうしゅく',m:'concentrado / condensado',l:'N2'},{w:'濃厚',f:'のうこう',m:'denso / intenso',l:'N1'}]},
  { rank:821, k:'灯', level:'N2', meanings:['lámpara / luz'], on:['トウ'], kun:['とも.す'],
    words:[{w:'灯台',f:'とうだい',m:'faro',l:'N2'},{w:'街灯',f:'がいとう',m:'farola / alumbrado público',l:'N2'},{w:'電灯',f:'でんとう',m:'luz eléctrica',l:'N2'},{w:'点灯',f:'てんとう',m:'encender la luz',l:'N1'}]},
  { rank:822, k:'灰', level:'N2', meanings:['ceniza'], on:['カイ'], kun:['はい'],
    words:[{w:'灰色',f:'はいいろ',m:'gris',l:'N3'},{w:'灰皿',f:'はいざら',m:'cenicero',l:'N2'},{w:'石灰',f:'せっかい',m:'cal',l:'N1'}]},
  { rank:823, k:'炭', level:'N2', meanings:['carbón'], on:['タン'], kun:['すみ'],
    words:[{w:'石炭',f:'せきたん',m:'carbón mineral',l:'N2'},{w:'炭素',f:'たんそ',m:'carbono',l:'N1'}]},
  { rank:826, k:'照', level:'N2', meanings:['iluminar / comparar'], on:['ショウ'], kun:['て.らす'],
    words:[{w:'照明',f:'しょうめい',m:'iluminación',l:'N1'},{w:'参照',f:'さんしょう',m:'referencia / consulta',l:'N1'}]},
  { rank:828, k:'燥', level:'N2', meanings:['seco / árido'], on:['ソウ'], kun:[],
    words:[{w:'乾燥',f:'かんそう',m:'sequedad / desecación',l:'N2'}]},
  { rank:829, k:'爆', level:'N2', meanings:['explotar'], on:['バク'], kun:[],
    words:[{w:'爆発',f:'ばくはつ',m:'explosión',l:'N2'},{w:'爆弾',f:'ばくだん',m:'bomba',l:'N1'}]},
  { rank:830, k:'片', level:'N2', meanings:['fragmento / un lado'], on:['ヘン'], kun:['かた'],
    words:[{w:'片方',f:'かたほう',m:'un lado / uno de los dos',l:'N3'},{w:'片道',f:'かたみち',m:'ida (un sentido)',l:'N2'},{w:'破片',f:'はへん',m:'fragmento / esquirla',l:'N1'}]},
  { rank:831, k:'版', level:'N2', meanings:['versión / edición'], on:['ハン'], kun:[],
    words:[{w:'出版',f:'しゅっぱん',m:'publicación',l:'N2'},{w:'版画',f:'はんが',m:'grabado / estampa',l:'N1'}]},
  { rank:833, k:'珍', level:'N2', meanings:['raro / precioso'], on:['チン'], kun:['めずら.しい'],
    words:[{w:'珍品',f:'ちんぴん',m:'artículo raro / curiosidad',l:'N1'},{w:'珍事',f:'ちんじ',m:'suceso insólito',l:'N1'},{w:'珍味',f:'ちんみ',m:'manjar / exquisitez',l:'N1'}]},
  { rank:834, k:'瓶', level:'N2', meanings:['botella / frasco'], on:['ビン'], kun:[],
    words:[{w:'花瓶',f:'かびん',m:'jarrón / florero',l:'N3'},{w:'瓶詰',f:'びんづめ',m:'embotellado',l:'N1'}]},
  { rank:835, k:'甘', level:'N2', meanings:['dulce / indulgente'], on:['カン'], kun:['あま.い'],
    words:[{w:'甘口',f:'あまくち',m:'sabor suave / poco picante',l:'N2'},{w:'甘酒',f:'あまざけ',m:'amazake / bebida dulce de arroz',l:'N2'},{w:'甘党',f:'あまとう',m:'goloso / amante del dulce',l:'N1'}]},
  { rank:837, k:'略', level:'N2', meanings:['abreviación / estrategia'], on:['リャク'], kun:[],
    words:[{w:'戦略',f:'せんりゃく',m:'estrategia',l:'N3'},{w:'省略',f:'しょうりゃく',m:'abreviación / omisión',l:'N2'},{w:'略語',f:'りゃくご',m:'abreviatura',l:'N1'},{w:'侵略',f:'しんりゃく',m:'invasión',l:'N1'}]},
  { rank:838, k:'畳', level:'N2', meanings:['tatami / doblar'], on:['ジョウ'], kun:['たた.む'],
    words:[{w:'折り畳み',f:'おりたたみ',m:'plegable',l:'N2'},{w:'石畳',f:'いしだたみ',m:'pavimento de piedra',l:'N1'}]},
  { rank:839, k:'療', level:'N2', meanings:['tratamiento médico'], on:['リョウ'], kun:[],
    words:[{w:'医療',f:'いりょう',m:'atención médica',l:'N4'},{w:'治療',f:'ちりょう',m:'tratamiento médico',l:'N3'},{w:'診療',f:'しんりょう',m:'consulta médica',l:'N1'},{w:'療法',f:'りょうほう',m:'terapia / tratamiento',l:'N1'}]},
  { rank:840, k:'皮', level:'N2', meanings:['piel / corteza'], on:['ヒ'], kun:['かわ'],
    words:[{w:'皮膚',f:'ひふ',m:'piel / cutis',l:'N2'},{w:'皮革',f:'ひかく',m:'cuero / piel curtida',l:'N2'},{w:'皮肉',f:'ひにく',m:'ironía / sarcasmo',l:'N1'},{w:'毛皮',f:'けがわ',m:'piel / pelaje',l:'N1'}]},
  { rank:842, k:'省', level:'N2', meanings:['ministerio / ahorrar'], on:['ショウ'], kun:['はぶ.く'],
    words:[{w:'反省',f:'はんせい',m:'reflexión / arrepentimiento',l:'N3'},{w:'省略',f:'しょうりゃく',m:'omisión / abreviación',l:'N2'},{w:'帰省',f:'きせい',m:'volver al pueblo natal',l:'N1'}]},
  { rank:845, k:'砂', level:'N2', meanings:['arena'], on:['サ'], kun:['すな'],
    words:[{w:'砂糖',f:'さとう',m:'azúcar',l:'N4'},{w:'砂漠',f:'さばく',m:'desierto',l:'N2'},{w:'土砂',f:'どしゃ',m:'tierra y arena',l:'N1'}]},
  { rank:846, k:'硬', level:'N2', meanings:['duro / rígido'], on:['コウ'], kun:['かた.い'],
    words:[{w:'硬貨',f:'こうか',m:'moneda (metálica)',l:'N2'},{w:'強硬',f:'きょうこう',m:'firme / inflexible',l:'N2'},{w:'硬度',f:'こうど',m:'dureza',l:'N1'}]},
  { rank:847, k:'磨', level:'N2', meanings:['pulir / cepillar'], on:['マ'], kun:['みが.く'],
    words:[{w:'歯磨き',f:'はみがき',m:'cepillado dental',l:'N4'},{w:'研磨',f:'けんま',m:'pulido / abrasión',l:'N1'}]},
  { rank:848, k:'祈', level:'N2', meanings:['rezar / desear'], on:['キ'], kun:['いの.る'],
    words:[{w:'祈願',f:'きがん',m:'oración / súplica',l:'N2'},{w:'祈念',f:'きねん',m:'oración / deseo',l:'N1'}]},
  { rank:851, k:'禁', level:'N2', meanings:['prohibir'], on:['キン'], kun:[],
    words:[{w:'禁止',f:'きんし',m:'prohibición',l:'N4'},{w:'禁煙',f:'きんえん',m:'no fumar',l:'N4'},{w:'解禁',f:'かいきん',m:'levantar una prohibición',l:'N1'},{w:'厳禁',f:'げんきん',m:'estrictamente prohibido',l:'N1'}]},
  { rank:855, k:'章', level:'N2', meanings:['capítulo / sección'], on:['ショウ'], kun:[],
    words:[{w:'文章',f:'ぶんしょう',m:'texto / redacción',l:'N3'},{w:'勲章',f:'くんしょう',m:'medalla / condecoración',l:'N1'},{w:'序章',f:'じょしょう',m:'prólogo',l:'N1'}]},
  { rank:857, k:'競', level:'N2', meanings:['competir'], on:['キョウ'], kun:['きそ.う'],
    words:[{w:'競争',f:'きょうそう',m:'competencia',l:'N3'},{w:'競技',f:'きょうぎ',m:'competición deportiva',l:'N2'},{w:'競馬',f:'けいば',m:'carreras de caballos',l:'N2'}]},
  { rank:859, k:'符', level:'N2', meanings:['símbolo / billete'], on:['フ'], kun:[],
    words:[{w:'切符',f:'きっぷ',m:'billete (tren)',l:'N5'},{w:'符号',f:'ふごう',m:'símbolo / signo',l:'N1'},{w:'音符',f:'おんぷ',m:'nota musical',l:'N1'}]},
  { rank:861, k:'筒', level:'N2', meanings:['tubo / cilindro'], on:['トウ'], kun:['つつ'],
    words:[{w:'封筒',f:'ふうとう',m:'sobre (correo)',l:'N3'},{w:'水筒',f:'すいとう',m:'cantimplora',l:'N3'},{w:'円筒',f:'えんとう',m:'cilindro',l:'N1'}]},
  { rank:865, k:'簡', level:'N2', meanings:['simple / sencillo'], on:['カン'], kun:[],
    words:[{w:'簡単',f:'かんたん',m:'fácil / simple',l:'N5'},{w:'簡潔',f:'かんけつ',m:'conciso',l:'N1'},{w:'簡素',f:'かんそ',m:'simple / austero',l:'N1'}]},
  { rank:866, k:'籍', level:'N2', meanings:['registro / libro'], on:['セキ'], kun:[],
    words:[{w:'国籍',f:'こくせき',m:'nacionalidad',l:'N2'},{w:'書籍',f:'しょせき',m:'libros / publicaciones',l:'N1'}]},
  { rank:868, k:'粒', level:'N2', meanings:['grano / partícula'], on:['リュウ'], kun:['つぶ'],
    words:[{w:'粒子',f:'りゅうし',m:'partícula',l:'N2'},{w:'米粒',f:'こめつぶ',m:'grano de arroz',l:'N1'}]},
  { rank:870, k:'紅', level:'N2', meanings:['rojo escarlata'], on:['コウ'], kun:['べに'],
    words:[{w:'紅茶',f:'こうちゃ',m:'té negro',l:'N4'},{w:'紅葉',f:'こうよう',m:'hojas otoñales',l:'N3'},{w:'口紅',f:'くちべに',m:'pintalabios',l:'N2'},{w:'紅白',f:'こうはく',m:'rojo y blanco',l:'N1'}]},
  { rank:871, k:'純', level:'N2', meanings:['puro / simple'], on:['ジュン'], kun:[],
    words:[{w:'単純',f:'たんじゅん',m:'simple',l:'N3'},{w:'純粋',f:'じゅんすい',m:'puro / genuino',l:'N1'},{w:'不純',f:'ふじゅん',m:'impuro',l:'N1'}]},
  { rank:875, k:'綿', level:'N2', meanings:['algodón'], on:['メン'], kun:['わた'],
    words:[{w:'木綿',f:'もめん',m:'algodón',l:'N3'},{w:'綿花',f:'めんか',m:'algodón (planta)',l:'N1'}]},
  { rank:876, k:'総', level:'N2', meanings:['total / general'], on:['ソウ'], kun:[],
    words:[{w:'総合',f:'そうごう',m:'integral / general',l:'N2'},{w:'総理',f:'そうり',m:'primer ministro',l:'N1'}]},
  { rank:879, k:'編', level:'N2', meanings:['tejer / editar'], on:['ヘン'], kun:['あ.む'],
    words:[{w:'編集',f:'へんしゅう',m:'edición',l:'N1'},{w:'短編',f:'たんぺん',m:'relato corto',l:'N1'}]},
  { rank:882, k:'署', level:'N2', meanings:['oficina / firmar'], on:['ショ'], kun:[],
    words:[{w:'警察署',f:'けいさつしょ',m:'comisaría',l:'N2'},{w:'署名',f:'しょめい',m:'firma',l:'N1'}]},
  { rank:883, k:'群', level:'N2', meanings:['grupo / manada'], on:['グン'], kun:['む.れ'],
    words:[{w:'群衆',f:'ぐんしゅう',m:'multitud / muchedumbre',l:'N2'},{w:'群島',f:'ぐんとう',m:'archipiélago',l:'N2'},{w:'大群',f:'たいぐん',m:'gran multitud / manada',l:'N1'}]},
  { rank:887, k:'肌', level:'N2', meanings:['piel / tez'], on:[], kun:['はだ'],
    words:[{w:'肌着',f:'はだぎ',m:'ropa interior',l:'N3'},{w:'素肌',f:'すはだ',m:'piel al natural',l:'N2'},{w:'鳥肌',f:'とりはだ',m:'piel de gallina',l:'N1'}]},
  { rank:888, k:'肩', level:'N2', meanings:['hombro'], on:[], kun:['かた'],
    words:[{w:'肩書き',f:'かたがき',m:'título / cargo',l:'N2'},{w:'肩幅',f:'かたはば',m:'anchura de hombros',l:'N2'},{w:'肩車',f:'かたぐるま',m:'llevar a hombros',l:'N1'}]},
  { rank:890, k:'胃', level:'N2', meanings:['estómago'], on:['イ'], kun:[],
    words:[{w:'胃腸',f:'いちょう',m:'estómago e intestinos',l:'N2'},{w:'胃袋',f:'いぶくろ',m:'estómago (coloquial)',l:'N2'},{w:'胃薬',f:'いぐすり',m:'medicina estomacal',l:'N2'}]},
  { rank:891, k:'胸', level:'N2', meanings:['pecho / corazón'], on:['キョウ'], kun:['むね'],
    words:[{w:'胸囲',f:'きょうい',m:'perímetro del pecho',l:'N2'},{w:'胸騒ぎ',f:'むなさわぎ',m:'presentimiento / inquietud',l:'N2'},{w:'度胸',f:'どきょう',m:'valor / coraje',l:'N1'}]},
  { rank:892, k:'脂', level:'N2', meanings:['grasa / sebo'], on:['シ'], kun:['あぶら'],
    words:[{w:'脂肪',f:'しぼう',m:'grasa / lípido',l:'N1'},{w:'樹脂',f:'じゅし',m:'resina',l:'N1'}]},
  { rank:893, k:'脳', level:'N2', meanings:['cerebro'], on:['ノウ'], kun:[],
    words:[{w:'脳裏',f:'のうり',m:'en la mente',l:'N2'},{w:'大脳',f:'だいのう',m:'cerebro (parte grande)',l:'N2'},{w:'頭脳',f:'ずのう',m:'cerebro / intelecto',l:'N1'},{w:'首脳',f:'しゅのう',m:'líder / cúpula',l:'N1'}]},
  { rank:894, k:'腕', level:'N2', meanings:['brazo'], on:['ワン'], kun:['うで'],
    words:[{w:'腕時計',f:'うでどけい',m:'reloj de pulsera',l:'N4'},{w:'腕前',f:'うでまえ',m:'habilidad / destreza',l:'N2'},{w:'手腕',f:'しゅわん',m:'habilidad / destreza',l:'N1'},{w:'腕力',f:'わんりょく',m:'fuerza física',l:'N1'}]},
  { rank:895, k:'腰', level:'N2', meanings:['cintura / caderas'], on:['ヨウ'], kun:['こし'],
    words:[{w:'腰痛',f:'ようつう',m:'dolor de espalda / lumbalgia',l:'N2'},{w:'腰掛け',f:'こしかけ',m:'asiento / taburete',l:'N2'},{w:'足腰',f:'あしこし',m:'piernas y caderas',l:'N1'}]},
  { rank:897, k:'臓', level:'N2', meanings:['órgano interno'], on:['ゾウ'], kun:[],
    words:[{w:'心臓',f:'しんぞう',m:'corazón',l:'N2'},{w:'内臓',f:'ないぞう',m:'órganos internos',l:'N1'}]},
  { rank:900, k:'航', level:'N2', meanings:['navegar'], on:['コウ'], kun:[],
    words:[{w:'航空',f:'こうくう',m:'aviación',l:'N4'},{w:'航海',f:'こうかい',m:'navegación',l:'N3'},{w:'航路',f:'こうろ',m:'ruta / vía',l:'N1'},{w:'欠航',f:'けっこう',m:'cancelación de vuelo',l:'N1'}]},
  { rank:901, k:'般', level:'N2', meanings:['general / clase'], on:['ハン'], kun:[],
    words:[{w:'一般',f:'いっぱん',m:'en general',l:'N3'},{w:'全般',f:'ぜんぱん',m:'el conjunto / en general',l:'N1'}]},
  { rank:903, k:'荒', level:'N2', meanings:['salvaje / rugoso'], on:['コウ'], kun:['あら.い'],
    words:[{w:'荒野',f:'こうや',m:'desierto / yermo',l:'N2'},{w:'荒廃',f:'こうはい',m:'devastación / ruina',l:'N2'},{w:'荒波',f:'あらなみ',m:'olas embravecidas',l:'N1'}]},
  { rank:905, k:'菓', level:'N2', meanings:['dulce / confitería'], on:['カ'], kun:[],
    words:[{w:'菓子',f:'かし',m:'dulce / confite',l:'N4'},{w:'和菓子',f:'わがし',m:'dulce japonés',l:'N3'},{w:'洋菓子',f:'ようがし',m:'repostería occidental',l:'N1'},{w:'駄菓子',f:'だがし',m:'golosinas baratas',l:'N1'}]},
  { rank:907, k:'著', level:'N2', meanings:['notable / autor'], on:['チョ'], kun:['いちじる.しい'],
    words:[{w:'著者',f:'ちょしゃ',m:'autor',l:'N1'},{w:'著名',f:'ちょめい',m:'célebre / renombrado',l:'N1'}]},
  { rank:908, k:'蒸', level:'N2', meanings:['vapor / cocinar al vapor'], on:['ジョウ'], kun:['む.す'],
    words:[{w:'蒸気',f:'じょうき',m:'vapor',l:'N1'},{w:'蒸発',f:'じょうはつ',m:'evaporación',l:'N1'}]},
  { rank:909, k:'蔵', level:'N2', meanings:['almacén / depósito'], on:['ゾウ'], kun:['くら'],
    words:[{w:'冷蔵庫',f:'れいぞうこ',m:'refrigerador',l:'N4'},{w:'貯蔵',f:'ちょぞう',m:'almacenamiento',l:'N1'},{w:'冷蔵',f:'れいぞう',m:'refrigeración',l:'N2'}]},
  { rank:910, k:'薄', level:'N2', meanings:['fino / tenue'], on:['ハク'], kun:['うす.い'],
    words:[{w:'薄情',f:'はくじょう',m:'indiferente / desalmado',l:'N2'},{w:'薄力粉',f:'はくりきこ',m:'harina floja',l:'N2'},{w:'希薄',f:'きはく',m:'escaso / tenue',l:'N1'}]},
  { rank:915, k:'被', level:'N2', meanings:['sufrir / recibir'], on:['ヒ'], kun:['こうむ.る'],
    words:[{w:'被害',f:'ひがい',m:'daño / perjuicio',l:'N3'},{w:'被災',f:'ひさい',m:'ser damnificado',l:'N1'},{w:'被告',f:'ひこく',m:'acusado',l:'N1'}]},
  { rank:916, k:'装', level:'N2', meanings:['vestir / equipar'], on:['ソウ'], kun:['よそお.う'],
    words:[{w:'服装',f:'ふくそう',m:'vestimenta',l:'N4'},{w:'装置',f:'そうち',m:'dispositivo / equipo',l:'N3'},{w:'包装',f:'ほうそう',m:'embalaje',l:'N2'},{w:'装飾',f:'そうしょく',m:'decoración',l:'N1'}]},
  { rank:917, k:'裏', level:'N2', meanings:['reverso / interior'], on:['リ'], kun:['うら'],
    words:[{w:'裏口',f:'うらぐち',m:'puerta trasera',l:'N3'},{w:'裏切り',f:'うらぎり',m:'traición',l:'N3'},{w:'裏面',f:'りめん',m:'reverso / dorso',l:'N1'},{w:'裏庭',f:'うらにわ',m:'patio trasero',l:'N1'}]},
  { rank:921, k:'触', level:'N2', meanings:['tocar'], on:['ショク'], kun:['さわ.る'],
    words:[{w:'接触',f:'せっしょく',m:'contacto',l:'N1'},{w:'感触',f:'かんしょく',m:'tacto / sensación',l:'N1'}]},
  { rank:922, k:'訓', level:'N2', meanings:['lectura kun / instrucción'], on:['クン'], kun:[],
    words:[{w:'訓練',f:'くんれん',m:'entrenamiento',l:'N4'},{w:'教訓',f:'きょうくん',m:'lección / moraleja',l:'N1'},{w:'訓読み',f:'くんよみ',m:'lectura kun',l:'N2'}]},
  { rank:924, k:'詞', level:'N2', meanings:['palabra / letra'], on:['シ'], kun:[],
    words:[{w:'歌詞',f:'かし',m:'letra de canción',l:'N4'},{w:'動詞',f:'どうし',m:'verbo',l:'N2'},{w:'名詞',f:'めいし',m:'sustantivo',l:'N2'}]},
  { rank:925, k:'詰', level:'N2', meanings:['apretar / llenar'], on:['キツ'], kun:['つ.める'],
    words:[{w:'缶詰',f:'かんづめ',m:'conservas',l:'N3'},{w:'瓶詰',f:'びんづめ',m:'embotellado',l:'N1'}]},
  { rank:926, k:'誌', level:'N2', meanings:['revista / registro'], on:['シ'], kun:[],
    words:[{w:'雑誌',f:'ざっし',m:'revista',l:'N4'},{w:'日誌',f:'にっし',m:'diario / bitácora',l:'N1'},{w:'週刊誌',f:'しゅうかんし',m:'revista semanal',l:'N1'}]},
  { rank:927, k:'課', level:'N2', meanings:['sección / lección'], on:['カ'], kun:[],
    words:[{w:'課題',f:'かだい',m:'tarea / problema',l:'N3'},{w:'課長',f:'かちょう',m:'jefe de sección',l:'N2'},{w:'日課',f:'にっか',m:'rutina diaria',l:'N1'}]},
  { rank:928, k:'諸', level:'N2', meanings:['varios / muchos'], on:['ショ'], kun:[],
    words:[{w:'諸国',f:'しょこく',m:'varios países',l:'N1'},{w:'諸島',f:'しょとう',m:'archipiélago',l:'N1'}]},
  { rank:929, k:'講', level:'N2', meanings:['conferencia / clase'], on:['コウ'], kun:[],
    words:[{w:'講義',f:'こうぎ',m:'clase magistral',l:'N2'},{w:'講演',f:'こうえん',m:'conferencia / charla',l:'N1'}]},
  { rank:931, k:'豊', level:'N2', meanings:['abundante / rico'], on:['ホウ'], kun:['ゆた.か'],
    words:[{w:'豊富',f:'ほうふ',m:'abundante',l:'N3'},{w:'豊作',f:'ほうさく',m:'buena cosecha',l:'N2'},{w:'豊年',f:'ほうねん',m:'año de buena cosecha',l:'N1'}]},
  { rank:932, k:'象', level:'N2', meanings:['elefante / fenómeno'], on:['ショウ'], kun:['ぞう'],
    words:[{w:'象徴',f:'しょうちょう',m:'símbolo / emblema',l:'N2'},{w:'現象',f:'げんしょう',m:'fenómeno',l:'N2'},{w:'対象',f:'たいしょう',m:'objeto / objetivo',l:'N2'},{w:'気象',f:'きしょう',m:'meteorología',l:'N1'}]},
  { rank:934, k:'貨', level:'N2', meanings:['mercancía / moneda'], on:['カ'], kun:[],
    words:[{w:'貨物',f:'かもつ',m:'carga / mercancía',l:'N1'},{w:'通貨',f:'つうか',m:'divisa / moneda',l:'N1'}]},
  { rank:935, k:'販', level:'N2', meanings:['vender'], on:['ハン'], kun:[],
    words:[{w:'販売',f:'はんばい',m:'venta',l:'N4'},{w:'自動販売機',f:'じどうはんばいき',m:'máquina expendedora',l:'N3'},{w:'市販',f:'しはん',m:'venta al público',l:'N1'},{w:'通販',f:'つうはん',m:'venta por catálogo',l:'N1'}]},
  { rank:939, k:'賢', level:'N2', meanings:['inteligente / sabio'], on:['ケン'], kun:['かしこ.い'],
    words:[{w:'賢者',f:'けんじゃ',m:'sabio / persona sabia',l:'N1'},{w:'賢明',f:'けんめい',m:'prudente / inteligente',l:'N2'},{w:'賢人',f:'けんじん',m:'sabio',l:'N1'}]},
  { rank:940, k:'贈', level:'N2', meanings:['regalar'], on:['ゾウ'], kun:['おく.る'],
    words:[{w:'贈り物',f:'おくりもの',m:'regalo',l:'N3'},{w:'贈答',f:'ぞうとう',m:'intercambio de regalos',l:'N1'},{w:'寄贈',f:'きぞう',m:'donación',l:'N1'}]},
  { rank:941, k:'超', level:'N2', meanings:['superar / extra'], on:['チョウ'], kun:['こ.える'],
    words:[{w:'超過',f:'ちょうか',m:'exceso',l:'N1'},{w:'超能力',f:'ちょうのうりょく',m:'poderes psíquicos',l:'N1'}]},
  { rank:942, k:'跡', level:'N2', meanings:['rastro / vestigio'], on:['セキ'], kun:['あと'],
    words:[{w:'足跡',f:'あしあと',m:'huella / pisada',l:'N3'},{w:'遺跡',f:'いせき',m:'ruinas / sitio arqueológico',l:'N2'},{w:'奇跡',f:'きせき',m:'milagro',l:'N1'},{w:'追跡',f:'ついせき',m:'persecución / rastreo',l:'N1'}]},
  { rank:943, k:'踊', level:'N2', meanings:['bailar'], on:['ヨウ'], kun:['おど.る'],
    words:[{w:'盆踊り',f:'ぼんおどり',m:'danza del Bon',l:'N2'},{w:'舞踊',f:'ぶよう',m:'danza',l:'N1'}]},
  { rank:944, k:'軍', level:'N2', meanings:['ejército / militar'], on:['グン'], kun:[],
    words:[{w:'軍隊',f:'ぐんたい',m:'ejército',l:'N2'},{w:'海軍',f:'かいぐん',m:'armada / marina',l:'N1'}]},
  { rank:945, k:'軒', level:'N2', meanings:['alero / contador de casas'], on:['ケン'], kun:['のき'],
    words:[{w:'一軒',f:'いっけん',m:'una casa',l:'N4'},{w:'一軒家',f:'いっけんや',m:'casa independiente',l:'N1'}]},
  { rank:946, k:'軟', level:'N2', meanings:['blando / suave'], on:['ナン'], kun:['やわ.らか'],
    words:[{w:'軟化',f:'なんか',m:'ablandamiento / suavización',l:'N2'},{w:'軟水',f:'なんすい',m:'agua blanda',l:'N2'},{w:'軟弱',f:'なんじゃく',m:'débil / blando',l:'N1'},{w:'柔軟',f:'じゅうなん',m:'flexible',l:'N1'}]},
  { rank:947, k:'輪', level:'N2', meanings:['rueda / círculo'], on:['リン'], kun:['わ'],
    words:[{w:'指輪',f:'ゆびわ',m:'anillo',l:'N3'},{w:'車輪',f:'しゃりん',m:'rueda (de vehículo)',l:'N2'},{w:'五輪',f:'ごりん',m:'Juegos Olímpicos',l:'N1'},{w:'年輪',f:'ねんりん',m:'anillo de crecimiento',l:'N1'}]},
  { rank:948, k:'輸', level:'N2', meanings:['transportar'], on:['ユ'], kun:[],
    words:[{w:'輸入',f:'ゆにゅう',m:'importación',l:'N4'},{w:'輸出',f:'ゆしゅつ',m:'exportación',l:'N3'},{w:'輸送',f:'ゆそう',m:'transporte',l:'N1'},{w:'運輸',f:'うんゆ',m:'transporte (sector)',l:'N1'}]},
  { rank:949, k:'辛', level:'N2', meanings:['picante / duro'], on:['シン'], kun:['から.い'],
    words:[{w:'辛抱',f:'しんぼう',m:'paciencia / aguante',l:'N2'},{w:'辛口',f:'からくち',m:'sabor picante / seco',l:'N2'},{w:'香辛料',f:'こうしんりょう',m:'especias',l:'N1'}]},
  { rank:950, k:'農', level:'N2', meanings:['agricultura'], on:['ノウ'], kun:[],
    words:[{w:'農業',f:'のうぎょう',m:'agricultura',l:'N3'},{w:'農家',f:'のうか',m:'familia campesina / granja',l:'N3'},{w:'農村',f:'のうそん',m:'aldea rural',l:'N2'},{w:'農民',f:'のうみん',m:'campesino',l:'N1'}]},
  { rank:952, k:'述', level:'N2', meanings:['describir / exponer'], on:['ジュツ'], kun:['の.べる'],
    words:[{w:'記述',f:'きじゅつ',m:'descripción',l:'N1'},{w:'前述',f:'ぜんじゅつ',m:'lo antes mencionado',l:'N1'}]},
  { rank:955, k:'郊', level:'N2', meanings:['suburbio / afueras'], on:['コウ'], kun:[],
    words:[{w:'郊外',f:'こうがい',m:'afueras / suburbios',l:'N2'},{w:'近郊',f:'きんこう',m:'cercanías',l:'N1'}]},
  { rank:956, k:'郵', level:'N2', meanings:['correo postal'], on:['ユウ'], kun:[],
    words:[{w:'郵便局',f:'ゆうびんきょく',m:'oficina de correos',l:'N5'},{w:'郵便',f:'ゆうびん',m:'correo postal',l:'N4'},{w:'郵送',f:'ゆうそう',m:'envío postal',l:'N4'},{w:'郵政',f:'ゆうせい',m:'servicios postales',l:'N1'}]},
  { rank:958, k:'針', level:'N2', meanings:['aguja / manecilla'], on:['シン'], kun:['はり'],
    words:[{w:'方針',f:'ほうしん',m:'política / directriz',l:'N2'},{w:'針路',f:'しんろ',m:'rumbo / curso',l:'N2'},{w:'針金',f:'はりがね',m:'alambre',l:'N2'},{w:'秒針',f:'びょうしん',m:'segundero',l:'N1'}]},
  { rank:962, k:'銅', level:'N2', meanings:['cobre'], on:['ドウ'], kun:[],
    words:[{w:'銅像',f:'どうぞう',m:'estatua de bronce',l:'N2'},{w:'青銅',f:'せいどう',m:'bronce',l:'N1'}]},
  { rank:966, k:'防', level:'N2', meanings:['defender / prevenir'], on:['ボウ'], kun:['ふせ.ぐ'],
    words:[{w:'防止',f:'ぼうし',m:'prevención',l:'N2'},{w:'予防',f:'よぼう',m:'prevención (médica)',l:'N2'}]},
  { rank:968, k:'隅', level:'N2', meanings:['rincón / esquina'], on:['グウ'], kun:['すみ'],
    words:[{w:'片隅',f:'かたすみ',m:'rincón / esquina',l:'N2'},{w:'四隅',f:'よすみ',m:'las cuatro esquinas',l:'N1'}]},
  { rank:971, k:'雇', level:'N2', meanings:['emplear / contratar'], on:['コ'], kun:['やと.う'],
    words:[{w:'雇用',f:'こよう',m:'empleo / contratación',l:'N1'},{w:'解雇',f:'かいこ',m:'despido',l:'N1'}]},
  { rank:972, k:'雲', level:'N2', meanings:['nube'], on:['ウン'], kun:['くも'],
    words:[{w:'雨雲',f:'あまぐも',m:'nube de lluvia',l:'N3'},{w:'雲海',f:'うんかい',m:'mar de nubes',l:'N2'},{w:'暗雲',f:'あんうん',m:'nubarrón',l:'N1'}]},
  { rank:973, k:'零', level:'N2', meanings:['cero / verter'], on:['レイ'], kun:['こぼ.れる'],
    words:[{w:'零下',f:'れいか',m:'bajo cero',l:'N1'},{w:'零点',f:'れいてん',m:'cero puntos',l:'N1'}]},
  { rank:974, k:'震', level:'N2', meanings:['temblar / terremoto'], on:['シン'], kun:['ふる.える'],
    words:[{w:'地震',f:'じしん',m:'terremoto',l:'N4'},{w:'震度',f:'しんど',m:'intensidad sísmica',l:'N2'},{w:'余震',f:'よしん',m:'réplica sísmica',l:'N1'}]},
  { rank:975, k:'革', level:'N2', meanings:['cuero / reforma'], on:['カク'], kun:['かわ'],
    words:[{w:'改革',f:'かいかく',m:'reforma',l:'N2'},{w:'革命',f:'かくめい',m:'revolución',l:'N1'}]},
  { rank:977, k:'預', level:'N2', meanings:['depositar / encomendar'], on:['ヨ'], kun:['あず.ける'],
    words:[{w:'預金',f:'よきん',m:'depósito bancario',l:'N2'}]},
  { rank:978, k:'領', level:'N2', meanings:['territorio / dominio'], on:['リョウ'], kun:[],
    words:[{w:'大統領',f:'だいとうりょう',m:'presidente',l:'N2'},{w:'領土',f:'りょうど',m:'territorio',l:'N1'}]},
  { rank:979, k:'額', level:'N2', meanings:['frente / importe'], on:['ガク'], kun:['ひたい'],
    words:[{w:'金額',f:'きんがく',m:'importe monetario',l:'N4'},{w:'半額',f:'はんがく',m:'mitad de precio',l:'N2'},{w:'全額',f:'ぜんがく',m:'importe total',l:'N1'}]},
  { rank:980, k:'香', level:'N2', meanings:['fragancia / aroma'], on:['コウ'], kun:['かお.り'],
    words:[{w:'香水',f:'こうすい',m:'perfume',l:'N3'},{w:'線香',f:'せんこう',m:'incienso',l:'N3'},{w:'香料',f:'こうりょう',m:'fragancia / aromatizante',l:'N1'}]},
  { rank:981, k:'駐', level:'N2', meanings:['estacionarse'], on:['チュウ'], kun:[],
    words:[{w:'駐車場',f:'ちゅうしゃじょう',m:'aparcamiento',l:'N4'},{w:'駐車',f:'ちゅうしゃ',m:'estacionamiento',l:'N3'},{w:'駐在',f:'ちゅうざい',m:'residencia / destacamento',l:'N1'}]},
  { rank:982, k:'骨', level:'N2', meanings:['hueso'], on:['コツ'], kun:['ほね'],
    words:[{w:'骨折',f:'こっせつ',m:'fractura de hueso',l:'N2'},{w:'骨格',f:'こっかく',m:'esqueleto / estructura',l:'N2'},{w:'背骨',f:'せぼね',m:'columna vertebral',l:'N1'},{w:'鉄骨',f:'てっこつ',m:'estructura de acero',l:'N1'}]},
  { rank:986, k:'齢', level:'N2', meanings:['edad'], on:['レイ'], kun:[],
    words:[{w:'年齢',f:'ねんれい',m:'edad',l:'N4'},{w:'高齢',f:'こうれい',m:'edad avanzada',l:'N3'},{w:'老齢',f:'ろうれい',m:'vejez',l:'N1'}]},
  { rank:1036, k:'勇', level:'N2', meanings:['valentía','coraje'], on:['ユウ'], kun:['いさ.ましい'],
    words:[{w:'勇気',f:'ゆうき',m:'valor / coraje',l:'N3'},{w:'勇敢',f:'ゆうかん',m:'valiente',l:'N1'},{w:'勇者',f:'ゆうしゃ',m:'héroe / valiente',l:'N1'}]},
]
