import type { Kanji } from './types'

// N2: 364 kanji

export const kanjiN2: Kanji[] = [
  { k:'並', level:'N2', meanings:['alinearse / estar en fila'], on:['ヘイ'], kun:['なら'],
    words:[{w:'並ぶ',f:'ならぶ',m:'hacer cola / alinearse',l:'N3'},{w:'並べる',f:'ならべる',m:'poner en fila',l:'N3'},{w:'並行',f:'へいこう',m:'paralelo',l:'N2'}]},
  { k:'丸', level:'N2', meanings:['círculo / redondo'], on:['ガン'], kun:['まる'],
    words:[{w:'丸い',f:'まるい',m:'redondo',l:'N4'},{w:'丸める',f:'まるめる',m:'enrollar / redondear',l:'N2'},{w:'弾丸',f:'だんがん',m:'bala',l:'N2'}]},
  { k:'久', level:'N2', meanings:['largo tiempo / duradero'], on:['キュウ'], kun:['ひさ'],
    words:[{w:'久しぶり',f:'ひさしぶり',m:'hace mucho tiempo',l:'N4'},{w:'久しい',f:'ひさしい',m:'hace mucho',l:'N3'},{w:'永久',f:'えいきゅう',m:'eterno / permanente',l:'N2'}]},
  { k:'乱', level:'N2', meanings:['desorden / caos'], on:['ラン'], kun:['みだ'],
    words:[{w:'乱れる',f:'みだれる',m:'desordenarse',l:'N3'},{w:'混乱',f:'こんらん',m:'confusión / caos',l:'N2'},{w:'乱暴',f:'らんぼう',m:'violencia / brusquedad',l:'N2'}]},
  { k:'乳', level:'N2', meanings:['leche / pecho'], on:['ニュウ'], kun:['ちち'],
    words:[{w:'牛乳',f:'ぎゅうにゅう',m:'leche de vaca',l:'N5'},{w:'母乳',f:'ぼにゅう',m:'leche materna',l:'N2'},{w:'乳製品',f:'にゅうせいひん',m:'lácteos',l:'N2'}]},
  { k:'乾', level:'N2', meanings:['secar / seco'], on:['カン'], kun:['かわ'],
    words:[{w:'乾杯',f:'かんぱい',m:'¡Salud! / brindis',l:'N4'},{w:'乾く',f:'かわく',m:'secarse',l:'N3'},{w:'乾燥',f:'かんそう',m:'sequedad / secado',l:'N2'}]},
  { k:'了', level:'N2', meanings:['terminar / completar'], on:['リョウ'], kun:[],
    words:[{w:'了解',f:'りょうかい',m:'entendido / comprensión',l:'N3'},{w:'終了',f:'しゅうりょう',m:'finalización',l:'N3'},{w:'完了',f:'かんりょう',m:'completado',l:'N2'}]},
  { k:'介', level:'N2', meanings:['mediar / presentar'], on:['カイ'], kun:[],
    words:[{w:'紹介',f:'しょうかい',m:'presentación / introducción',l:'N4'},{w:'介護',f:'かいご',m:'cuidado de ancianos',l:'N2'},{w:'仲介',f:'ちゅうかい',m:'mediación',l:'N2'}]},
  { k:'仏', level:'N2', meanings:['Buda / Francia'], on:['ブツ'], kun:['ほとけ'],
    words:[{w:'仏教',f:'ぶっきょう',m:'budismo',l:'N3'},{w:'仏壇',f:'ぶつだん',m:'altar budista',l:'N2'},{w:'大仏',f:'だいぶつ',m:'gran Buda',l:'N2'}]},
  { k:'令', level:'N2', meanings:['orden / mandato'], on:['レイ'], kun:[],
    words:[{w:'命令',f:'めいれい',m:'orden / mandato',l:'N3'},{w:'法令',f:'ほうれい',m:'ley / decreto',l:'N2'},{w:'令和',f:'れいわ',m:'era Reiwa',l:'N1'}]},
  { k:'仲', level:'N2', meanings:['relación / mediación'], on:['チュウ'], kun:['なか'],
    words:[{w:'仲良し',f:'なかよし',m:'amigos íntimos',l:'N4'},{w:'仲間',f:'なかま',m:'compañero / camarada',l:'N3'},{w:'仲介',f:'ちゅうかい',m:'mediación',l:'N2'}]},
  { k:'伸', level:'N2', meanings:['estirar / extender'], on:['シン'], kun:['の'],
    words:[{w:'伸びる',f:'のびる',m:'crecer / estirarse',l:'N3'},{w:'伸ばす',f:'のばす',m:'extender / alargar',l:'N3'},{w:'背伸び',f:'せのび',m:'ponerse de puntillas',l:'N2'}]},
  { k:'伺', level:'N2', meanings:['visitar / preguntar (humilde)'], on:['シ'], kun:['うかが'],
    words:[{w:'伺う',f:'うかがう',m:'visitar / preguntar (humilde)',l:'N2'},{w:'伺い',f:'うかがい',m:'visita / consulta',l:'N2'},{w:'お伺い',f:'おうかがい',m:'visita respetuosa',l:'N2'}]},
  { k:'低', level:'N2', meanings:['bajo / inferior'], on:['テイ'], kun:['ひく'],
    words:[{w:'低い',f:'ひくい',m:'bajo',l:'N5'},{w:'最低',f:'さいてい',m:'mínimo / lo peor',l:'N3'},{w:'低下',f:'ていか',m:'disminución / descenso',l:'N3'}]},
  { k:'依', level:'N2', meanings:['depender / según'], on:['イ'], kun:['よ'],
    words:[{w:'依頼',f:'いらい',m:'solicitud / encargo',l:'N3'},{w:'依存',f:'いぞん',m:'dependencia',l:'N2'},{w:'依然',f:'いぜん',m:'aún / todavía',l:'N2'}]},
  { k:'個', level:'N2', meanings:['individuo / unidad'], on:['コ'], kun:[],
    words:[{w:'個人',f:'こじん',m:'individuo / personal',l:'N3'},{w:'個別',f:'こべつ',m:'individual / separado',l:'N2'},{w:'個性',f:'こせい',m:'personalidad / carácter',l:'N2'}]},
  { k:'倍', level:'N2', meanings:['múltiplo / doble'], on:['バイ'], kun:[],
    words:[{w:'二倍',f:'にばい',m:'el doble',l:'N3'},{w:'倍増',f:'ばいぞう',m:'duplicar / doblar',l:'N2'},{w:'何倍',f:'なんばい',m:'cuántas veces',l:'N2'}]},
  { k:'停', level:'N2', meanings:['detener / parar'], on:['テイ'], kun:['と'],
    words:[{w:'バス停',f:'ばすてい',m:'parada de autobús',l:'N4'},{w:'停止',f:'ていし',m:'parada / detención',l:'N3'},{w:'停電',f:'ていでん',m:'apagón',l:'N3'}]},
  { k:'傾', level:'N2', meanings:['inclinarse / tender a'], on:['ケイ'], kun:['かたむ'],
    words:[{w:'傾向',f:'けいこう',m:'tendencia',l:'N3'},{w:'傾く',f:'かたむく',m:'inclinarse',l:'N2'},{w:'傾ける',f:'かたむける',m:'inclinar',l:'N2'}]},
  { k:'像', level:'N2', meanings:['imagen / estatua'], on:['ゾウ'], kun:[],
    words:[{w:'映像',f:'えいぞう',m:'imagen / video',l:'N4'},{w:'想像',f:'そうぞう',m:'imaginación',l:'N3'},{w:'像',f:'ぞう',m:'estatua / figura',l:'N2'}]},
  { k:'億', level:'N2', meanings:['cien millones'], on:['オク'], kun:[],
    words:[{w:'一億',f:'いちおく',m:'cien millones',l:'N2'},{w:'数億',f:'すうおく',m:'varios cientos de millones',l:'N2'},{w:'億万長者',f:'おくまんちょうじゃ',m:'multimillonario',l:'N1'}]},
  { k:'兆', level:'N2', meanings:['billón / presagio'], on:['チョウ'], kun:['きざ'],
    words:[{w:'兆候',f:'ちょうこう',m:'señal / síntoma',l:'N2'},{w:'一兆',f:'いちちょう',m:'un billón',l:'N2'},{w:'吉兆',f:'きっちょう',m:'buen presagio',l:'N1'}]},
  { k:'児', level:'N2', meanings:['niño / infante'], on:['ジ'], kun:['こ'],
    words:[{w:'児童',f:'じどう',m:'niño / alumno',l:'N2'},{w:'幼児',f:'ようじ',m:'niño pequeño',l:'N2'},{w:'育児',f:'いくじ',m:'cuidado de niños',l:'N2'}]},
  { k:'党', level:'N2', meanings:['partido político'], on:['トウ'], kun:[],
    words:[{w:'政党',f:'せいとう',m:'partido político',l:'N2'},{w:'与党',f:'よとう',m:'partido gobernante',l:'N2'},{w:'野党',f:'やとう',m:'partido de oposición',l:'N2'}]},
  { k:'兵', level:'N2', meanings:['soldado / tropa'], on:['ヘイ'], kun:[],
    words:[{w:'兵士',f:'へいし',m:'soldado',l:'N2'},{w:'兵器',f:'へいき',m:'armamento',l:'N2'},{w:'兵庫',f:'ひょうご',m:'Hyogo (prefectura)',l:'N2'}]},
  { k:'冊', level:'N2', meanings:['contador de libros'], on:['サツ'], kun:[],
    words:[{w:'一冊',f:'いっさつ',m:'un libro',l:'N4'},{w:'別冊',f:'べっさつ',m:'volumen separado',l:'N2'},{w:'冊子',f:'さっし',m:'folleto / librito',l:'N2'}]},
  { k:'再', level:'N2', meanings:['otra vez / re-'], on:['サイ'], kun:['ふたた'],
    words:[{w:'再び',f:'ふたたび',m:'de nuevo',l:'N3'},{w:'再生',f:'さいせい',m:'reproducción / regeneración',l:'N2'},{w:'再確認',f:'さいかくにん',m:'reconfirmar',l:'N2'}]},
  { k:'凍', level:'N2', meanings:['congelar'], on:['トウ'], kun:['こお'],
    words:[{w:'凍る',f:'こおる',m:'congelarse',l:'N3'},{w:'冷凍',f:'れいとう',m:'congelación',l:'N2'},{w:'凍結',f:'とうけつ',m:'congelar / bloquear',l:'N2'}]},
  { k:'刊', level:'N2', meanings:['publicar / edición'], on:['カン'], kun:[],
    words:[{w:'週刊',f:'しゅうかん',m:'semanal',l:'N4'},{w:'月刊',f:'げっかん',m:'mensual',l:'N2'},{w:'発刊',f:'はっかん',m:'publicación / lanzamiento',l:'N2'}]},
  { k:'刷', level:'N2', meanings:['imprimir'], on:['サツ'], kun:['す'],
    words:[{w:'印刷',f:'いんさつ',m:'impresión',l:'N2'},{w:'刷る',f:'すう',m:'imprimir',l:'N2'},{w:'増刷',f:'ぞうさつ',m:'reimpresión',l:'N2'}]},
  { k:'券', level:'N2', meanings:['billete / bono'], on:['ケン'], kun:[],
    words:[{w:'乗車券',f:'じょうしゃけん',m:'billete de transporte',l:'N2'},{w:'食券',f:'しょっけん',m:'bono de comida',l:'N2'},{w:'入場券',f:'にゅうじょうけん',m:'entrada',l:'N2'}]},
  { k:'刺', level:'N2', meanings:['pinchar / tarjeta'], on:['シ'], kun:['さ'],
    words:[{w:'名刺',f:'めいし',m:'tarjeta de visita',l:'N4'},{w:'刺す',f:'さす',m:'pinchar / clavar',l:'N3'},{w:'刺激',f:'しげき',m:'estímulo',l:'N2'}]},
  { k:'則', level:'N2', meanings:['regla / norma'], on:['ソク'], kun:[],
    words:[{w:'規則',f:'きそく',m:'regla / norma',l:'N4'},{w:'原則',f:'げんそく',m:'principio / regla general',l:'N3'},{w:'法則',f:'ほうそく',m:'ley / principio',l:'N2'}]},
  { k:'副', level:'N2', meanings:['vice- / secundario'], on:['フク'], kun:[],
    words:[{w:'副作用',f:'ふくさよう',m:'efecto secundario',l:'N2'},{w:'副社長',f:'ふくしゃちょう',m:'vicepresidente',l:'N2'},{w:'副詞',f:'ふくし',m:'adverbio',l:'N2'}]},
  { k:'劇', level:'N2', meanings:['drama / teatro'], on:['ゲキ'], kun:[],
    words:[{w:'悲劇',f:'ひげき',m:'tragedia',l:'N3'},{w:'劇場',f:'げきじょう',m:'teatro',l:'N2'},{w:'演劇',f:'えんげき',m:'obra de teatro',l:'N2'}]},
  { k:'効', level:'N2', meanings:['efecto / eficacia'], on:['コウ'], kun:['き'],
    words:[{w:'効果',f:'こうか',m:'efecto / resultado',l:'N3'},{w:'有効',f:'ゆうこう',m:'válido / efectivo',l:'N3'},{w:'効率',f:'こうりつ',m:'eficiencia',l:'N2'}]},
  { k:'募', level:'N2', meanings:['reclutar / reunir'], on:['ボ'], kun:['つの'],
    words:[{w:'募集',f:'ぼしゅう',m:'reclutamiento / convocatoria',l:'N2'},{w:'応募',f:'おうぼ',m:'solicitud / candidatura',l:'N2'},{w:'募金',f:'ぼきん',m:'recaudación de fondos',l:'N2'}]},
  { k:'勢', level:'N2', meanings:['fuerza / ímpetu'], on:['セイ'], kun:['いきお'],
    words:[{w:'勢い',f:'いきおい',m:'ímpetu / fuerza',l:'N2'},{w:'姿勢',f:'しせい',m:'postura / actitud',l:'N2'},{w:'情勢',f:'じょうせい',m:'situación / estado',l:'N2'}]},
  { k:'包', level:'N2', meanings:['envolver / empaquetar'], on:['ホウ'], kun:['つつ'],
    words:[{w:'小包',f:'こづつみ',m:'paquete postal',l:'N4'},{w:'包む',f:'つつむ',m:'envolver',l:'N3'},{w:'包装',f:'ほうそう',m:'embalaje / envoltura',l:'N2'}]},
  { k:'匹', level:'N2', meanings:['contador de animales pequeños'], on:['ヒキ'], kun:[],
    words:[{w:'一匹',f:'いっぴき',m:'un (animal pequeño)',l:'N4'},{w:'二匹',f:'にひき',m:'dos (animales)',l:'N4'},{w:'匹敵',f:'ひってき',m:'rivalizar con',l:'N2'}]},
  { k:'区', level:'N2', meanings:['distrito / sección'], on:['ク'], kun:[],
    words:[{w:'地区',f:'ちく',m:'zona / distrito',l:'N3'},{w:'区別',f:'くべつ',m:'distinción / diferencia',l:'N3'},{w:'区役所',f:'くやくしょ',m:'oficina del distrito',l:'N2'}]},
  { k:'卒', level:'N2', meanings:['graduarse / terminar'], on:['ソツ'], kun:[],
    words:[{w:'卒業',f:'そつぎょう',m:'graduación',l:'N4'},{w:'卒業式',f:'そつぎょうしき',m:'ceremonia de graduación',l:'N4'},{w:'中卒',f:'ちゅうそつ',m:'graduado de secundaria',l:'N2'}]},
  { k:'協', level:'N2', meanings:['cooperación'], on:['キョウ'], kun:[],
    words:[{w:'協力',f:'きょうりょく',m:'cooperación',l:'N4'},{w:'協議',f:'きょうぎ',m:'deliberación / negociación',l:'N2'},{w:'協定',f:'きょうてい',m:'acuerdo / convenio',l:'N2'}]},
  { k:'占', level:'N2', meanings:['adivinar / ocupar'], on:['セン'], kun:['し'],
    words:[{w:'占める',f:'しめる',m:'ocupar / representar',l:'N3'},{w:'占い',f:'うらない',m:'adivinación / horóscopo',l:'N3'},{w:'独占',f:'どくせん',m:'monopolio',l:'N2'}]},
  { k:'印', level:'N2', meanings:['sello / marca'], on:['イン'], kun:['しるし'],
    words:[{w:'印鑑',f:'いんかん',m:'sello personal',l:'N2'},{w:'印象',f:'いんしょう',m:'impresión',l:'N2'},{w:'目印',f:'めじるし',m:'señal / marca',l:'N2'}]},
  { k:'卵', level:'N2', meanings:['huevo'], on:['ラン'], kun:['たまご'],
    words:[{w:'卵',f:'たまご',m:'huevo',l:'N5'},{w:'卵焼き',f:'たまごやき',m:'tortilla japonesa',l:'N3'},{w:'産卵',f:'さんらん',m:'puesta de huevos',l:'N2'}]},
  { k:'厚', level:'N2', meanings:['grueso / generoso'], on:['コウ'], kun:['あつ'],
    words:[{w:'厚い',f:'あつい',m:'grueso / espeso',l:'N4'},{w:'厚さ',f:'あつさ',m:'grosor',l:'N3'},{w:'厚意',f:'こうい',m:'amabilidad / generosidad',l:'N2'}]},
  { k:'双', level:'N2', meanings:['par / ambos'], on:['ソウ'], kun:['ふた'],
    words:[{w:'双子',f:'ふたご',m:'gemelos',l:'N3'},{w:'双方',f:'そうほう',m:'ambas partes',l:'N2'},{w:'双眼鏡',f:'そうがんきょう',m:'binoculares',l:'N2'}]},
  { k:'叫', level:'N2', meanings:['gritar'], on:['キョウ'], kun:['さけ'],
    words:[{w:'叫ぶ',f:'さけぶ',m:'gritar',l:'N3'},{w:'叫び声',f:'さけびごえ',m:'grito',l:'N2'},{w:'絶叫',f:'ぜっきょう',m:'grito extremo',l:'N2'}]},
  { k:'召', level:'N2', meanings:['convocar / llamar'], on:['ショウ'], kun:['め'],
    words:[{w:'召し上がる',f:'めしあがる',m:'comer/beber (honorífico)',l:'N2'},{w:'召集',f:'しょうしゅう',m:'convocatoria',l:'N2'},{w:'召喚',f:'しょうかん',m:'citación',l:'N2'}]},
  { k:'史', level:'N2', meanings:['historia'], on:['シ'], kun:[],
    words:[{w:'歴史',f:'れきし',m:'historia',l:'N3'},{w:'史上',f:'しじょう',m:'en la historia',l:'N2'},{w:'日本史',f:'にほんし',m:'historia de Japón',l:'N2'}]},
  { k:'各', level:'N2', meanings:['cada / respectivo'], on:['カク'], kun:['おのおの'],
    words:[{w:'各自',f:'かくじ',m:'cada uno / individualmente',l:'N2'},{w:'各地',f:'かくち',m:'cada lugar / diversas regiones',l:'N2'},{w:'各種',f:'かくしゅ',m:'varios tipos',l:'N2'}]},
  { k:'含', level:'N2', meanings:['incluir / contener'], on:['ガン'], kun:['ふく'],
    words:[{w:'含む',f:'ふくむ',m:'incluir / contener',l:'N3'},{w:'含める',f:'ふくめる',m:'incluir / añadir',l:'N3'},{w:'含有',f:'がんゆう',m:'contenido / inclusión',l:'N2'}]},
  { k:'周', level:'N2', meanings:['alrededor / perímetro'], on:['シュウ'], kun:['まわ'],
    words:[{w:'周り',f:'まわり',m:'alrededor',l:'N4'},{w:'周囲',f:'しゅうい',m:'entorno / perímetro',l:'N2'},{w:'周辺',f:'しゅうへん',m:'alrededores / periferia',l:'N2'}]},
  { k:'咲', level:'N2', meanings:['florecer'], on:[], kun:['さ'],
    words:[{w:'咲く',f:'さく',m:'florecer',l:'N4'},{w:'咲き誇る',f:'さきほこる',m:'florecer gloriosamente',l:'N2'},{w:'咲き始める',f:'さきはじめる',m:'empezar a florecer',l:'N2'}]},
  { k:'喫', level:'N2', meanings:['beber / fumar'], on:['キツ'], kun:[],
    words:[{w:'喫茶店',f:'きっさてん',m:'cafetería',l:'N4'},{w:'喫煙',f:'きつえん',m:'fumar',l:'N2'},{w:'喫緊',f:'きっきん',m:'urgente / apremiante',l:'N2'}]},
  { k:'営', level:'N2', meanings:['gestionar / operar'], on:['エイ'], kun:['いとな'],
    words:[{w:'営業',f:'えいぎょう',m:'negocio / ventas',l:'N3'},{w:'経営',f:'けいえい',m:'gestión / administración',l:'N3'},{w:'運営',f:'うんえい',m:'gestión / operación',l:'N2'}]},
  { k:'団', level:'N2', meanings:['grupo / organización'], on:['ダン'], kun:[],
    words:[{w:'団体',f:'だんたい',m:'grupo / organización',l:'N3'},{w:'集団',f:'しゅうだん',m:'grupo / colectivo',l:'N2'},{w:'楽団',f:'がくだん',m:'orquesta / banda',l:'N2'}]},
  { k:'囲', level:'N2', meanings:['rodear / cercar'], on:['イ'], kun:['かこ'],
    words:[{w:'囲む',f:'かこむ',m:'rodear',l:'N3'},{w:'周囲',f:'しゅうい',m:'entorno / perímetro',l:'N2'},{w:'範囲',f:'はんい',m:'alcance / rango',l:'N2'}]},
  { k:'固', level:'N2', meanings:['sólido / firme'], on:['コ'], kun:['かた'],
    words:[{w:'固い',f:'かたい',m:'duro / firme',l:'N3'},{w:'固定',f:'こてい',m:'fijo / permanente',l:'N2'},{w:'固有',f:'こゆう',m:'propio / inherente',l:'N2'}]},
  { k:'圧', level:'N2', meanings:['presión'], on:['アツ'], kun:[],
    words:[{w:'圧力',f:'あつりょく',m:'presión',l:'N2'},{w:'気圧',f:'きあつ',m:'presión atmosférica',l:'N2'},{w:'血圧',f:'けつあつ',m:'presión arterial',l:'N2'}]},
  { k:'坂', level:'N2', meanings:['cuesta / pendiente'], on:['ハン'], kun:['さか'],
    words:[{w:'坂道',f:'さかみち',m:'camino en cuesta',l:'N3'},{w:'急坂',f:'きゅうざか',m:'pendiente empinada',l:'N2'},{w:'下り坂',f:'くだりざか',m:'cuesta abajo',l:'N2'}]},
  { k:'均', level:'N2', meanings:['uniforme / equilibrio'], on:['キン'], kun:[],
    words:[{w:'平均',f:'へいきん',m:'promedio / media',l:'N3'},{w:'均等',f:'きんとう',m:'igual / uniforme',l:'N2'},{w:'均衡',f:'きんこう',m:'equilibrio',l:'N2'}]},
  { k:'型', level:'N2', meanings:['modelo / tipo'], on:['ケイ'], kun:['かた'],
    words:[{w:'型',f:'かた',m:'molde / modelo',l:'N3'},{w:'大型',f:'おおがた',m:'de gran tamaño',l:'N2'},{w:'新型',f:'しんがた',m:'nuevo modelo / nueva variante',l:'N2'}]},
  { k:'埋', level:'N2', meanings:['enterrar / rellenar'], on:['マイ'], kun:['う'],
    words:[{w:'埋める',f:'うめる',m:'enterrar / rellenar',l:'N3'},{w:'埋蔵',f:'まいぞう',m:'enterrado / reserva subterránea',l:'N2'},{w:'埋め立て',f:'うめたて',m:'relleno / terreno ganado al mar',l:'N2'}]},
  { k:'城', level:'N2', meanings:['castillo'], on:['ジョウ'], kun:['しろ'],
    words:[{w:'城',f:'しろ',m:'castillo',l:'N3'},{w:'大阪城',f:'おおさかじょう',m:'castillo de Osaka',l:'N2'},{w:'城下町',f:'じょうかまち',m:'ciudad castillo',l:'N2'}]},
  { k:'域', level:'N2', meanings:['zona / región'], on:['イキ'], kun:[],
    words:[{w:'地域',f:'ちいき',m:'región / zona',l:'N3'},{w:'区域',f:'くいき',m:'zona / área',l:'N2'},{w:'範域',f:'はんいき',m:'ámbito / alcance',l:'N2'}]},
  { k:'塔', level:'N2', meanings:['torre / pagoda'], on:['トウ'], kun:[],
    words:[{w:'五重塔',f:'ごじゅうのとう',m:'pagoda de cinco pisos',l:'N2'},{w:'塔',f:'とう',m:'torre / pagoda',l:'N2'},{w:'鐘塔',f:'しょうとう',m:'campanario',l:'N2'}]},
  { k:'塗', level:'N2', meanings:['pintar / aplicar'], on:['ト'], kun:['ぬ'],
    words:[{w:'塗る',f:'ぬる',m:'pintar / untar',l:'N3'},{w:'塗料',f:'とりょう',m:'pintura / barniz',l:'N2'},{w:'塗装',f:'とそう',m:'pintura / revestimiento',l:'N2'}]},
  { k:'塩', level:'N2', meanings:['sal'], on:['エン'], kun:['しお'],
    words:[{w:'塩',f:'しお',m:'sal',l:'N5'},{w:'塩分',f:'えんぶん',m:'contenido en sal',l:'N2'},{w:'食塩',f:'しょくえん',m:'sal de mesa',l:'N2'}]},
  { k:'境', level:'N2', meanings:['frontera / límite'], on:['キョウ'], kun:['さかい'],
    words:[{w:'環境',f:'かんきょう',m:'ambiente / entorno',l:'N3'},{w:'境界',f:'きょうかい',m:'frontera / límite',l:'N2'},{w:'国境',f:'こっきょう',m:'frontera nacional',l:'N2'}]},
  { k:'央', level:'N2', meanings:['centro'], on:['オウ'], kun:[],
    words:[{w:'中央',f:'ちゅうおう',m:'centro / central',l:'N3'},{w:'中央線',f:'ちゅうおうせん',m:'línea Chuo',l:'N2'},{w:'震央',f:'しんおう',m:'epicentro',l:'N2'}]},
  { k:'奥', level:'N2', meanings:['interior / profundidad'], on:['オウ'], kun:['おく'],
    words:[{w:'奥さん',f:'おくさん',m:'esposa (respetuoso)',l:'N4'},{w:'奥深い',f:'おくふかい',m:'profundo',l:'N2'},{w:'奥地',f:'おくち',m:'interior / zona remota',l:'N2'}]},
  { k:'姓', level:'N2', meanings:['apellido'], on:['セイ'], kun:['みょうじ'],
    words:[{w:'姓名',f:'せいめい',m:'nombre y apellido',l:'N2'},{w:'姓',f:'せい',m:'apellido',l:'N2'},{w:'改姓',f:'かいせい',m:'cambio de apellido',l:'N2'}]},
  { k:'委', level:'N2', meanings:['delegar / comité'], on:['イ'], kun:[],
    words:[{w:'委員',f:'いいん',m:'miembro de comité',l:'N3'},{w:'委員会',f:'いいんかい',m:'comité',l:'N3'},{w:'委任',f:'いにん',m:'delegación',l:'N2'}]},
  { k:'季', level:'N2', meanings:['estación / período'], on:['キ'], kun:[],
    words:[{w:'季節',f:'きせつ',m:'estación del año',l:'N4'},{w:'四季',f:'しき',m:'las cuatro estaciones',l:'N4'},{w:'冬季',f:'とうき',m:'temporada de invierno',l:'N2'}]},
  { k:'孫', level:'N2', meanings:['nieto'], on:['ソン'], kun:['まご'],
    words:[{w:'孫',f:'まご',m:'nieto',l:'N3'},{w:'子孫',f:'しそん',m:'descendiente',l:'N2'},{w:'外孫',f:'そとまご',m:'nieto por hija',l:'N2'}]},
  { k:'宇', level:'N2', meanings:['universo / alero'], on:['ウ'], kun:[],
    words:[{w:'宇宙',f:'うちゅう',m:'universo / espacio',l:'N3'},{w:'宇宙人',f:'うちゅうじん',m:'extraterrestre',l:'N3'},{w:'宇宙船',f:'うちゅうせん',m:'nave espacial',l:'N2'}]},
  { k:'宝', level:'N2', meanings:['tesoro'], on:['ホウ'], kun:['たから'],
    words:[{w:'宝物',f:'たからもの',m:'tesoro',l:'N3'},{w:'宝石',f:'ほうせき',m:'joya / piedra preciosa',l:'N2'},{w:'国宝',f:'こくほう',m:'tesoro nacional',l:'N2'}]},
  { k:'寺', level:'N2', meanings:['templo budista'], on:['ジ'], kun:['てら'],
    words:[{w:'お寺',f:'おてら',m:'templo budista',l:'N4'},{w:'寺院',f:'じいん',m:'templo',l:'N2'},{w:'古寺',f:'こじ',m:'templo antiguo',l:'N2'}]},
  { k:'封', level:'N2', meanings:['sellar / sobre'], on:['フウ'], kun:['ふう'],
    words:[{w:'封筒',f:'ふうとう',m:'sobre (correo)',l:'N3'},{w:'封する',f:'ふうする',m:'sellar',l:'N2'},{w:'封鎖',f:'ふうさ',m:'bloqueo / cierre',l:'N2'}]},
  { k:'専', level:'N2', meanings:['especializado / exclusivo'], on:['セン'], kun:['もっぱ'],
    words:[{w:'専門',f:'せんもん',m:'especialidad',l:'N3'},{w:'専用',f:'せんよう',m:'exclusivo / de uso propio',l:'N2'},{w:'専攻',f:'せんこう',m:'especialización',l:'N2'}]},
  { k:'将', level:'N2', meanings:['general / futuro'], on:['ショウ'], kun:[],
    words:[{w:'将来',f:'しょうらい',m:'futuro',l:'N4'},{w:'将軍',f:'しょうぐん',m:'general / shogun',l:'N2'},{w:'主将',f:'しゅしょう',m:'capitán',l:'N2'}]},
  { k:'尊', level:'N2', meanings:['respetar / valioso'], on:['ソン'], kun:['たっと'],
    words:[{w:'尊重',f:'そんちょう',m:'respeto / valoración',l:'N2'},{w:'自尊心',f:'じそんしん',m:'autoestima',l:'N2'},{w:'尊敬',f:'そんけい',m:'respeto',l:'N2'}]},
  { k:'導', level:'N2', meanings:['guiar / liderar'], on:['ドウ'], kun:['みちび'],
    words:[{w:'指導',f:'しどう',m:'dirección / guía',l:'N2'},{w:'導く',f:'みちびく',m:'guiar / liderar',l:'N2'},{w:'誘導',f:'ゆうどう',m:'inducción / guía',l:'N2'}]},
  { k:'届', level:'N2', meanings:['llegar / entregar'], on:[], kun:['とど'],
    words:[{w:'届く',f:'とどく',m:'llegar / alcanzar',l:'N3'},{w:'届ける',f:'とどける',m:'entregar / notificar',l:'N3'},{w:'届け出',f:'とどけで',m:'notificación oficial',l:'N2'}]},
  { k:'層', level:'N2', meanings:['capa / estrato'], on:['ソウ'], kun:[],
    words:[{w:'層',f:'そう',m:'capa / estrato',l:'N2'},{w:'地層',f:'ちそう',m:'estrato geológico',l:'N2'},{w:'上層部',f:'じょうそうぶ',m:'nivel superior / alta dirección',l:'N2'}]},
  { k:'岩', level:'N2', meanings:['roca'], on:['ガン'], kun:['いわ'],
    words:[{w:'岩',f:'いわ',m:'roca',l:'N4'},{w:'岩石',f:'がんせき',m:'roca / piedra',l:'N2'},{w:'溶岩',f:'ようがん',m:'lava',l:'N2'}]},
  { k:'岸', level:'N2', meanings:['orilla / costa'], on:['ガン'], kun:['きし'],
    words:[{w:'海岸',f:'かいがん',m:'costa / playa',l:'N4'},{w:'川岸',f:'かわぎし',m:'orilla del río',l:'N4'},{w:'岸',f:'きし',m:'orilla',l:'N3'}]},
  { k:'島', level:'N2', meanings:['isla'], on:['トウ'], kun:['しま'],
    words:[{w:'島',f:'しま',m:'isla',l:'N4'},{w:'半島',f:'はんとう',m:'península',l:'N2'},{w:'列島',f:'れっとう',m:'archipiélago',l:'N2'}]},
  { k:'州', level:'N2', meanings:['estado / provincia'], on:['シュウ'], kun:['す'],
    words:[{w:'九州',f:'きゅうしゅう',m:'Kyushu',l:'N4'},{w:'州',f:'しゅう',m:'estado / provincia',l:'N2'},{w:'中州',f:'なかす',m:'banco de arena en río',l:'N2'}]},
  { k:'巨', level:'N2', meanings:['enorme / gigante'], on:['キョ'], kun:[],
    words:[{w:'巨大',f:'きょだい',m:'enorme / gigantesco',l:'N2'},{w:'巨人',f:'きょじん',m:'gigante',l:'N2'},{w:'巨額',f:'きょがく',m:'enorme cantidad',l:'N2'}]},
  { k:'巻', level:'N2', meanings:['enrollar / volumen'], on:['カン'], kun:['ま'],
    words:[{w:'巻く',f:'まく',m:'enrollar / envolver',l:'N3'},{w:'巻物',f:'まきもの',m:'rollo / pergamino',l:'N2'},{w:'一巻',f:'いっかん',m:'primer volumen',l:'N2'}]},
  { k:'布', level:'N2', meanings:['tela / difundir'], on:['フ'], kun:['ぬの'],
    words:[{w:'財布',f:'さいふ',m:'cartera / billetera',l:'N5'},{w:'布団',f:'ふとん',m:'futón / edredón',l:'N4'},{w:'布',f:'ぬの',m:'tela / tejido',l:'N3'}]},
  { k:'希', level:'N2', meanings:['raro / esperanza'], on:['キ'], kun:['まれ'],
    words:[{w:'希望',f:'きぼう',m:'esperanza / deseo',l:'N4'},{w:'希少',f:'きしょう',m:'escaso / raro',l:'N2'},{w:'希薄',f:'きはく',m:'tenue / escaso',l:'N2'}]},
  { k:'帯', level:'N2', meanings:['cinturón / zona'], on:['タイ'], kun:['お'],
    words:[{w:'帯',f:'おび',m:'cinturón (kimono)',l:'N3'},{w:'熱帯',f:'ねったい',m:'zona tropical',l:'N2'},{w:'携帯',f:'けいたい',m:'teléfono móvil',l:'N2'}]},
  { k:'帽', level:'N2', meanings:['sombrero / gorra'], on:['ボウ'], kun:[],
    words:[{w:'帽子',f:'ぼうし',m:'sombrero',l:'N5'},{w:'野球帽',f:'やきゅうぼう',m:'gorra de béisbol',l:'N2'},{w:'麦わら帽',f:'むぎわらぼう',m:'sombrero de paja',l:'N2'}]},
  { k:'幅', level:'N2', meanings:['anchura / margen'], on:['フク'], kun:['はば'],
    words:[{w:'幅',f:'はば',m:'anchura',l:'N3'},{w:'幅広い',f:'はばひろい',m:'amplio / extenso',l:'N2'},{w:'価格幅',f:'かかくはば',m:'rango de precios',l:'N2'}]},
  { k:'干', level:'N2', meanings:['secar / intervenir'], on:['カン'], kun:['ほ'],
    words:[{w:'干す',f:'ほす',m:'secar / tender (ropa)',l:'N3'},{w:'干渉',f:'かんしょう',m:'interferencia',l:'N2'},{w:'干潮',f:'かんちょう',m:'marea baja',l:'N2'}]},
  { k:'幼', level:'N2', meanings:['infancia / joven'], on:['ヨウ'], kun:['おさな'],
    words:[{w:'幼稚園',f:'ようちえん',m:'jardín de infancia',l:'N4'},{w:'幼い',f:'おさない',m:'pequeño / infantil',l:'N3'},{w:'幼児',f:'ようじ',m:'niño pequeño',l:'N2'}]},
  { k:'庁', level:'N2', meanings:['agencia gubernamental'], on:['チョウ'], kun:[],
    words:[{w:'官庁',f:'かんちょう',m:'agencia del gobierno',l:'N3'},{w:'県庁',f:'けんちょう',m:'oficina prefectural',l:'N2'},{w:'市庁',f:'しちょう',m:'ayuntamiento',l:'N2'}]},
  { k:'床', level:'N2', meanings:['suelo / cama'], on:['ショウ'], kun:['ゆか'],
    words:[{w:'床',f:'ゆか',m:'suelo / piso',l:'N3'},{w:'床屋',f:'とこや',m:'barbería',l:'N3'},{w:'起床',f:'きしょう',m:'levantarse de la cama',l:'N2'}]},
  { k:'底', level:'N2', meanings:['fondo / base'], on:['テイ'], kun:['そこ'],
    words:[{w:'底',f:'そこ',m:'fondo / parte inferior',l:'N3'},{w:'底辺',f:'ていへん',m:'base / parte inferior',l:'N2'},{w:'徹底',f:'てってい',m:'exhaustivo / radical',l:'N2'}]},
  { k:'府', level:'N2', meanings:['prefectura / sede'], on:['フ'], kun:[],
    words:[{w:'政府',f:'せいふ',m:'gobierno',l:'N3'},{w:'大阪府',f:'おおさかふ',m:'prefectura de Osaka',l:'N2'},{w:'首府',f:'しゅふ',m:'capital',l:'N2'}]},
  { k:'庫', level:'N2', meanings:['almacén / depósito'], on:['コ'], kun:[],
    words:[{w:'書庫',f:'しょこ',m:'archivo / depósito de libros',l:'N2'},{w:'車庫',f:'しゃこ',m:'garaje',l:'N2'},{w:'文庫',f:'ぶんこ',m:'colección de libros / edición de bolsillo',l:'N2'}]},
  { k:'延', level:'N2', meanings:['extenderse / posponer'], on:['エン'], kun:['の'],
    words:[{w:'延期',f:'えんき',m:'aplazamiento',l:'N3'},{w:'延びる',f:'のびる',m:'extenderse / alargarse',l:'N3'},{w:'延長',f:'えんちょう',m:'prórroga / extensión',l:'N2'}]},
  { k:'律', level:'N2', meanings:['ley / ritmo'], on:['リツ'], kun:[],
    words:[{w:'法律',f:'ほうりつ',m:'ley',l:'N3'},{w:'規律',f:'きりつ',m:'disciplina / regla',l:'N2'},{w:'一律',f:'いちりつ',m:'uniforme / sin excepción',l:'N2'}]},
  { k:'復', level:'N2', meanings:['regresar / recuperarse'], on:['フク'], kun:[],
    words:[{w:'復習',f:'ふくしゅう',m:'repaso',l:'N4'},{w:'回復',f:'かいふく',m:'recuperación',l:'N3'},{w:'復帰',f:'ふっき',m:'regreso / reincorporación',l:'N2'}]},
  { k:'快', level:'N2', meanings:['agradable / veloz'], on:['カイ'], kun:['こころよ'],
    words:[{w:'快適',f:'かいてき',m:'cómodo / agradable',l:'N3'},{w:'快晴',f:'かいせい',m:'cielo despejado',l:'N2'},{w:'爽快',f:'そうかい',m:'refrescante',l:'N2'}]},
  { k:'恋', level:'N2', meanings:['amor romántico'], on:['レン'], kun:['こい'],
    words:[{w:'恋人',f:'こいびと',m:'pareja / novio/a',l:'N4'},{w:'恋愛',f:'れんあい',m:'amor romántico',l:'N3'},{w:'失恋',f:'しつれん',m:'desamor',l:'N3'}]},
  { k:'患', level:'N2', meanings:['padecer (enfermedad)'], on:['カン'], kun:['わずら'],
    words:[{w:'患者',f:'かんじゃ',m:'paciente',l:'N3'},{w:'患う',f:'わずらう',m:'sufrir de / padecer',l:'N2'},{w:'疾患',f:'しっかん',m:'enfermedad / afección',l:'N2'}]},
  { k:'悩', level:'N2', meanings:['preocuparse / angustia'], on:['ノウ'], kun:['なや'],
    words:[{w:'悩む',f:'なやむ',m:'preocuparse / angustiarse',l:'N3'},{w:'悩み',f:'なやみ',m:'preocupación / angustia',l:'N3'},{w:'苦悩',f:'くのう',m:'sufrimiento',l:'N2'}]},
  { k:'憎', level:'N2', meanings:['odiar / detestar'], on:['ゾウ'], kun:['にく'],
    words:[{w:'憎む',f:'にくむ',m:'odiar',l:'N3'},{w:'憎しみ',f:'にくしみ',m:'odio',l:'N3'},{w:'憎悪',f:'ぞうお',m:'odio / aversión',l:'N2'}]},
  { k:'戸', level:'N2', meanings:['puerta / hogar'], on:['コ'], kun:['と'],
    words:[{w:'戸',f:'と',m:'puerta / hoja de puerta',l:'N3'},{w:'戸棚',f:'とだな',m:'armario / alacena',l:'N3'},{w:'江戸',f:'えど',m:'Edo (antiguo Tokio)',l:'N2'}]},
  { k:'承', level:'N2', meanings:['aceptar / recibir'], on:['ショウ'], kun:['うけたまわ'],
    words:[{w:'承知',f:'しょうち',m:'entendido / conformidad',l:'N3'},{w:'承認',f:'しょうにん',m:'aprobación',l:'N2'},{w:'了承',f:'りょうしょう',m:'consentimiento',l:'N2'}]},
  { k:'技', level:'N2', meanings:['habilidad / técnica'], on:['ギ'], kun:['わざ'],
    words:[{w:'技術',f:'ぎじゅつ',m:'tecnología / técnica',l:'N3'},{w:'技能',f:'ぎのう',m:'habilidad',l:'N2'},{w:'競技',f:'きょうぎ',m:'competencia / evento deportivo',l:'N2'}]},
  { k:'担', level:'N2', meanings:['cargar / encargarse'], on:['タン'], kun:['かつ'],
    words:[{w:'担当',f:'たんとう',m:'encargado / responsable',l:'N3'},{w:'負担',f:'ふたん',m:'carga / responsabilidad',l:'N3'},{w:'担う',f:'になう',m:'encargarse / cargar',l:'N2'}]},
  { k:'拝', level:'N2', meanings:['venerar / (humilde)'], on:['ハイ'], kun:['おが'],
    words:[{w:'拝む',f:'おがむ',m:'orar / venerar',l:'N3'},{w:'礼拝',f:'れいはい',m:'culto / adoración',l:'N2'},{w:'拝見',f:'はいけん',m:'ver (humilde)',l:'N2'}]},
  { k:'拾', level:'N2', meanings:['recoger / diez'], on:['ジュウ'], kun:['ひろ'],
    words:[{w:'拾う',f:'ひろう',m:'recoger / encontrar',l:'N4'},{w:'拾い物',f:'ひろいもの',m:'objeto encontrado',l:'N3'},{w:'拾得',f:'しゅうとく',m:'recogida / hallazgo',l:'N2'}]},
  { k:'挟', level:'N2', meanings:['atrapar entre / intercalar'], on:['キョウ'], kun:['はさ'],
    words:[{w:'挟む',f:'はさむ',m:'intercalar / atrapar',l:'N3'},{w:'挟まる',f:'はさまる',m:'estar atrapado',l:'N2'},{w:'板挟み',f:'いたばさみ',m:'estar entre dos fuegos',l:'N2'}]},
  { k:'捜', level:'N2', meanings:['buscar / investigar'], on:['ソウ'], kun:['さが'],
    words:[{w:'捜す',f:'さがす',m:'buscar',l:'N3'},{w:'捜査',f:'そうさ',m:'investigación (policial)',l:'N2'},{w:'捜索',f:'そうさく',m:'búsqueda',l:'N2'}]},
  { k:'捨', level:'N2', meanings:['tirar / abandonar'], on:['シャ'], kun:['す'],
    words:[{w:'捨てる',f:'すてる',m:'tirar / desechar',l:'N4'},{w:'見捨てる',f:'みすてる',m:'abandonar',l:'N2'},{w:'投げ捨てる',f:'なげすてる',m:'tirar al suelo',l:'N2'}]},
  { k:'掃', level:'N2', meanings:['barrer / limpiar'], on:['ソウ'], kun:['は'],
    words:[{w:'掃除',f:'そうじ',m:'limpieza',l:'N5'},{w:'掃除機',f:'そうじき',m:'aspiradora',l:'N3'},{w:'一掃',f:'いっそう',m:'eliminar de una vez',l:'N2'}]},
  { k:'掘', level:'N2', meanings:['excavar / cavar'], on:['クツ'], kun:['ほ'],
    words:[{w:'掘る',f:'ほる',m:'cavar / excavar',l:'N3'},{w:'発掘',f:'はっくつ',m:'excavación',l:'N2'},{w:'採掘',f:'さいくつ',m:'extracción / minería',l:'N2'}]},
  { k:'採', level:'N2', meanings:['recoger / adoptar'], on:['サイ'], kun:['と'],
    words:[{w:'採用',f:'さいよう',m:'adopción / contratación',l:'N2'},{w:'採取',f:'さいしゅ',m:'recolección / muestreo',l:'N2'},{w:'採点',f:'さいてん',m:'calificación / puntuación',l:'N2'}]},
  { k:'接', level:'N2', meanings:['conectar / contactar'], on:['セツ'], kun:['つ'],
    words:[{w:'直接',f:'ちょくせつ',m:'directo / directamente',l:'N4'},{w:'接続',f:'せつぞく',m:'conexión',l:'N2'},{w:'接触',f:'せっしょく',m:'contacto',l:'N2'}]},
  { k:'換', level:'N2', meanings:['intercambiar / cambiar'], on:['カン'], kun:['か'],
    words:[{w:'交換',f:'こうかん',m:'intercambio',l:'N3'},{w:'換える',f:'かえる',m:'cambiar / intercambiar',l:'N3'},{w:'換気',f:'かんき',m:'ventilación',l:'N3'}]},
  { k:'損', level:'N2', meanings:['dañar / pérdida'], on:['ソン'], kun:['そこ'],
    words:[{w:'損する',f:'そんする',m:'perder / salir perjudicado',l:'N3'},{w:'損害',f:'そんがい',m:'daño / perjuicio',l:'N2'},{w:'破損',f:'はそん',m:'daño / rotura',l:'N2'}]},
  { k:'改', level:'N2', meanings:['reformar / cambiar'], on:['カイ'], kun:['あらた'],
    words:[{w:'改める',f:'あらためる',m:'reformar / reconsiderar',l:'N3'},{w:'改善',f:'かいぜん',m:'mejora',l:'N2'},{w:'改正',f:'かいせい',m:'revisión / enmienda',l:'N2'}]},
  { k:'敬', level:'N2', meanings:['respetar'], on:['ケイ'], kun:['うやま'],
    words:[{w:'敬語',f:'けいご',m:'lenguaje honorífico',l:'N3'},{w:'尊敬',f:'そんけい',m:'respeto',l:'N2'},{w:'敬意',f:'けいい',m:'respeto / deferencia',l:'N2'}]},
  { k:'旧', level:'N2', meanings:['antiguo / anterior'], on:['キュウ'], kun:['ふる'],
    words:[{w:'旧式',f:'きゅうしき',m:'anticuado',l:'N2'},{w:'旧友',f:'きゅうゆう',m:'viejo amigo',l:'N2'},{w:'旧来',f:'きゅうらい',m:'tradicional / antiguo',l:'N2'}]},
  { k:'昇', level:'N2', meanings:['ascender / subir'], on:['ショウ'], kun:['のぼ'],
    words:[{w:'昇る',f:'のぼる',m:'ascender / salir (sol)',l:'N3'},{w:'上昇',f:'じょうしょう',m:'ascenso / subida',l:'N3'},{w:'昇進',f:'しょうしん',m:'ascenso (laboral)',l:'N2'}]},
  { k:'星', level:'N2', meanings:['estrella'], on:['セイ'], kun:['ほし'],
    words:[{w:'星',f:'ほし',m:'estrella',l:'N5'},{w:'星座',f:'せいざ',m:'constelación',l:'N3'},{w:'惑星',f:'わくせい',m:'planeta',l:'N2'}]},
  { k:'普', level:'N2', meanings:['general / común'], on:['フ'], kun:[],
    words:[{w:'普通',f:'ふつう',m:'normal / ordinario',l:'N4'},{w:'普段',f:'ふだん',m:'habitualmente',l:'N3'},{w:'普及',f:'ふきゅう',m:'difusión / popularización',l:'N2'}]},
  { k:'暴', level:'N2', meanings:['violencia / revelar'], on:['ボウ'], kun:['あば'],
    words:[{w:'暴力',f:'ぼうりょく',m:'violencia',l:'N2'},{w:'暴れる',f:'あばれる',m:'alborotar / desbocarse',l:'N2'},{w:'暴露',f:'ばくろ',m:'revelación / exposición',l:'N2'}]},
  { k:'曇', level:'N2', meanings:['nublado'], on:['ドン'], kun:['くも'],
    words:[{w:'曇り',f:'くもり',m:'nublado',l:'N5'},{w:'曇る',f:'くもる',m:'nublarse',l:'N4'},{w:'薄曇り',f:'うすぐもり',m:'ligeramente nublado',l:'N2'}]},
  { k:'替', level:'N2', meanings:['sustituir / cambiar'], on:['タイ'], kun:['か'],
    words:[{w:'着替え',f:'きがえ',m:'ropa de repuesto / cambiarse',l:'N4'},{w:'替える',f:'かえる',m:'cambiar / sustituir',l:'N3'},{w:'両替',f:'りょうがえ',m:'cambio de moneda',l:'N3'}]},
  { k:'札', level:'N2', meanings:['billete / etiqueta'], on:['サツ'], kun:['ふだ'],
    words:[{w:'お札',f:'おさつ',m:'billete (dinero)',l:'N4'},{w:'札幌',f:'さっぽろ',m:'Sapporo',l:'N2'},{w:'名札',f:'なふだ',m:'etiqueta de nombre',l:'N2'}]},
  { k:'机', level:'N2', meanings:['escritorio'], on:['キ'], kun:['つくえ'],
    words:[{w:'机',f:'つくえ',m:'escritorio',l:'N5'},{w:'机上',f:'きじょう',m:'sobre el escritorio / teórico',l:'N2'},{w:'文机',f:'ふづくえ',m:'escritorio de estudio',l:'N2'}]},
  { k:'材', level:'N2', meanings:['material / madera'], on:['ザイ'], kun:[],
    words:[{w:'材料',f:'ざいりょう',m:'material / ingrediente',l:'N4'},{w:'木材',f:'もくざい',m:'madera',l:'N4'},{w:'人材',f:'じんざい',m:'recursos humanos / talento',l:'N2'}]},
  { k:'村', level:'N2', meanings:['pueblo / aldea'], on:['ソン'], kun:['むら'],
    words:[{w:'村',f:'むら',m:'pueblo / aldea',l:'N4'},{w:'村長',f:'そんちょう',m:'alcalde de pueblo',l:'N2'},{w:'農村',f:'のうそん',m:'aldea agrícola',l:'N2'}]},
  { k:'板', level:'N2', meanings:['tablón / tabla'], on:['ハン'], kun:['いた'],
    words:[{w:'黒板',f:'こくばん',m:'pizarra',l:'N5'},{w:'板',f:'いた',m:'tabla / tablón',l:'N3'},{w:'看板',f:'かんばん',m:'letrero / cartel',l:'N3'}]},
  { k:'林', level:'N2', meanings:['bosque'], on:['リン'], kun:['はやし'],
    words:[{w:'林',f:'はやし',m:'bosque pequeño',l:'N4'},{w:'森林',f:'しんりん',m:'bosque / selva',l:'N2'},{w:'林業',f:'りんぎょう',m:'silvicultura',l:'N2'}]},
  { k:'枚', level:'N2', meanings:['contador de hojas finas'], on:['マイ'], kun:[],
    words:[{w:'一枚',f:'いちまい',m:'una hoja / una pieza',l:'N5'},{w:'何枚',f:'なんまい',m:'cuántas hojas',l:'N4'},{w:'枚数',f:'まいすう',m:'número de hojas',l:'N2'}]},
  { k:'枝', level:'N2', meanings:['rama'], on:['シ'], kun:['えだ'],
    words:[{w:'枝',f:'えだ',m:'rama',l:'N3'},{w:'小枝',f:'こえだ',m:'ramita',l:'N2'},{w:'枝葉',f:'えだは',m:'ramas y hojas / detalles',l:'N2'}]},
  { k:'枯', level:'N2', meanings:['marchitarse / seco'], on:['コ'], kun:['か'],
    words:[{w:'枯れる',f:'かれる',m:'marchitarse / secarse',l:'N3'},{w:'枯れ木',f:'かれき',m:'árbol seco',l:'N2'},{w:'枯渇',f:'こかつ',m:'agotamiento / escasez',l:'N2'}]},
  { k:'柔', level:'N2', meanings:['suave / flexible'], on:['ジュウ'], kun:['やわ'],
    words:[{w:'柔道',f:'じゅうどう',m:'judo',l:'N4'},{w:'柔らかい',f:'やわらかい',m:'suave / blando',l:'N3'},{w:'柔軟',f:'じゅうなん',m:'flexible / suave',l:'N2'}]},
  { k:'柱', level:'N2', meanings:['pilar / columna'], on:['チュウ'], kun:['はしら'],
    words:[{w:'柱',f:'はしら',m:'pilar',l:'N3'},{w:'電柱',f:'でんちゅう',m:'poste eléctrico',l:'N3'},{w:'大黒柱',f:'だいこくばしら',m:'pilar principal / sustento',l:'N2'}]},
  { k:'査', level:'N2', meanings:['investigar / examinar'], on:['サ'], kun:[],
    words:[{w:'調査',f:'ちょうさ',m:'investigación',l:'N3'},{w:'審査',f:'しんさ',m:'examen / evaluación',l:'N2'},{w:'査定',f:'さてい',m:'evaluación / tasación',l:'N2'}]},
  { k:'栄', level:'N2', meanings:['prosperar / gloria'], on:['エイ'], kun:['さか'],
    words:[{w:'栄養',f:'えいよう',m:'nutrición',l:'N3'},{w:'繁栄',f:'はんえい',m:'prosperidad',l:'N2'},{w:'栄光',f:'えいこう',m:'gloria / esplendor',l:'N2'}]},
  { k:'根', level:'N2', meanings:['raíz'], on:['コン'], kun:['ね'],
    words:[{w:'根',f:'ね',m:'raíz',l:'N3'},{w:'根拠',f:'こんきょ',m:'base / fundamento',l:'N2'},{w:'根本',f:'こんぽん',m:'base / raíz',l:'N2'}]},
  { k:'械', level:'N2', meanings:['maquinaria'], on:['カイ'], kun:[],
    words:[{w:'機械',f:'きかい',m:'máquina / maquinaria',l:'N3'},{w:'器械',f:'きかい',m:'instrumento / aparato',l:'N2'},{w:'農機械',f:'のうきかい',m:'maquinaria agrícola',l:'N2'}]},
  { k:'棒', level:'N2', meanings:['bastón / palo'], on:['ボウ'], kun:[],
    words:[{w:'棒',f:'ぼう',m:'palo / bastón',l:'N3'},{w:'棒グラフ',f:'ぼうぐらふ',m:'gráfico de barras',l:'N2'},{w:'金棒',f:'かなぼう',m:'maza de hierro',l:'N2'}]},
  { k:'森', level:'N2', meanings:['bosque denso'], on:['シン'], kun:['もり'],
    words:[{w:'森',f:'もり',m:'bosque',l:'N4'},{w:'森林',f:'しんりん',m:'bosque / selva',l:'N2'},{w:'森閑',f:'しんかん',m:'silencio del bosque',l:'N2'}]},
  { k:'植', level:'N2', meanings:['plantar'], on:['ショク'], kun:['う'],
    words:[{w:'植物',f:'しょくぶつ',m:'planta',l:'N4'},{w:'植える',f:'うえる',m:'plantar',l:'N3'},{w:'植民地',f:'しょくみんち',m:'colonia',l:'N2'}]},
  { k:'極', level:'N2', meanings:['extremo / polo'], on:['キョク'], kun:['きわ'],
    words:[{w:'南極',f:'なんきょく',m:'Antártida / polo sur',l:'N3'},{w:'積極的',f:'せっきょくてき',m:'activo / positivo',l:'N3'},{w:'極端',f:'きょくたん',m:'extremo / radical',l:'N2'}]},
  { k:'橋', level:'N2', meanings:['puente'], on:['キョウ'], kun:['はし'],
    words:[{w:'橋',f:'はし',m:'puente',l:'N4'},{w:'歩道橋',f:'ほどうきょう',m:'pasarela peatonal',l:'N2'},{w:'橋渡し',f:'はしわたし',m:'mediar / hacer de puente',l:'N2'}]},
  { k:'欧', level:'N2', meanings:['Europa'], on:['オウ'], kun:[],
    words:[{w:'欧米',f:'おうべい',m:'Europa y América',l:'N2'},{w:'欧州',f:'おうしゅう',m:'Europa',l:'N2'},{w:'西欧',f:'せいおう',m:'Europa occidental',l:'N2'}]},
  { k:'武', level:'N2', meanings:['militar / marcial'], on:['ブ'], kun:[],
    words:[{w:'武道',f:'ぶどう',m:'artes marciales',l:'N2'},{w:'武器',f:'ぶき',m:'arma',l:'N2'},{w:'武士',f:'ぶし',m:'samurái',l:'N2'}]},
  { k:'歴', level:'N2', meanings:['historia / trayectoria'], on:['レキ'], kun:[],
    words:[{w:'歴史',f:'れきし',m:'historia',l:'N3'},{w:'経歴',f:'けいれき',m:'trayectoria / historial',l:'N2'},{w:'履歴書',f:'りれきしょ',m:'currículum',l:'N2'}]},
  { k:'殿', level:'N2', meanings:['señor / palacio'], on:['デン'], kun:['との'],
    words:[{w:'殿',f:'との',m:'señor / palacio',l:'N2'},{w:'宮殿',f:'きゅうでん',m:'palacio',l:'N2'},{w:'御殿',f:'ごてん',m:'palacio imperial',l:'N2'}]},
  { k:'毒', level:'N2', meanings:['veneno'], on:['ドク'], kun:[],
    words:[{w:'毒',f:'どく',m:'veneno',l:'N3'},{w:'中毒',f:'ちゅうどく',m:'intoxicación',l:'N2'},{w:'消毒',f:'しょうどく',m:'desinfección',l:'N2'}]},
  { k:'比', level:'N2', meanings:['comparar / proporción'], on:['ヒ'], kun:['くら'],
    words:[{w:'比べる',f:'くらべる',m:'comparar',l:'N3'},{w:'比較',f:'ひかく',m:'comparación',l:'N2'},{w:'比率',f:'ひりつ',m:'proporción / tasa',l:'N2'}]},
  { k:'毛', level:'N2', meanings:['pelo / vello'], on:['モウ'], kun:['け'],
    words:[{w:'毛',f:'け',m:'pelo / vello',l:'N5'},{w:'毛布',f:'もうふ',m:'manta',l:'N3'},{w:'羊毛',f:'ようもう',m:'lana',l:'N2'}]},
  { k:'氷', level:'N2', meanings:['hielo'], on:['ヒョウ'], kun:['こおり'],
    words:[{w:'氷',f:'こおり',m:'hielo',l:'N4'},{w:'氷山',f:'ひょうざん',m:'iceberg',l:'N2'},{w:'薄氷',f:'はくひょう',m:'hielo fino',l:'N2'}]},
  { k:'永', level:'N2', meanings:['eterno / permanente'], on:['エイ'], kun:['なが'],
    words:[{w:'永遠',f:'えいえん',m:'eterno',l:'N3'},{w:'永久',f:'えいきゅう',m:'permanente',l:'N2'},{w:'永続',f:'えいぞく',m:'continuación permanente',l:'N2'}]},
  { k:'汗', level:'N2', meanings:['sudor'], on:['カン'], kun:['あせ'],
    words:[{w:'汗',f:'あせ',m:'sudor',l:'N3'},{w:'汗をかく',f:'あせをかく',m:'sudar',l:'N3'},{w:'冷や汗',f:'ひやあせ',m:'sudor frío',l:'N2'}]},
  { k:'汚', level:'N2', meanings:['ensuciar / contaminar'], on:['オ'], kun:['よご'],
    words:[{w:'汚い',f:'きたない',m:'sucio',l:'N4'},{w:'汚れる',f:'よごれる',m:'ensuciarse',l:'N3'},{w:'汚染',f:'おせん',m:'contaminación',l:'N2'}]},
  { k:'池', level:'N2', meanings:['estanque'], on:['チ'], kun:['いけ'],
    words:[{w:'池',f:'いけ',m:'estanque',l:'N5'},{w:'電池',f:'でんち',m:'batería / pila',l:'N4'},{w:'池袋',f:'いけぶくろ',m:'Ikebukuro',l:'N2'}]},
  { k:'沈', level:'N2', meanings:['hundir / sumergir'], on:['チン'], kun:['しず'],
    words:[{w:'沈む',f:'しずむ',m:'hundirse',l:'N3'},{w:'沈黙',f:'ちんもく',m:'silencio',l:'N2'},{w:'沈着',f:'ちんちゃく',m:'calma / serenidad',l:'N2'}]},
  { k:'河', level:'N2', meanings:['río'], on:['カ'], kun:['かわ'],
    words:[{w:'河川',f:'かせん',m:'ríos',l:'N4'},{w:'銀河',f:'ぎんが',m:'galaxia',l:'N2'},{w:'運河',f:'うんが',m:'canal',l:'N2'}]},
  { k:'沸', level:'N2', meanings:['hervir'], on:['フツ'], kun:['わ'],
    words:[{w:'沸く',f:'わく',m:'hervir',l:'N3'},{w:'沸かす',f:'わかす',m:'hacer hervir',l:'N3'},{w:'沸点',f:'ふってん',m:'punto de ebullición',l:'N2'}]},
  { k:'油', level:'N2', meanings:['aceite / petróleo'], on:['ユ'], kun:['あぶら'],
    words:[{w:'油',f:'あぶら',m:'aceite / grasa',l:'N4'},{w:'石油',f:'せきゆ',m:'petróleo',l:'N2'},{w:'油断',f:'ゆだん',m:'descuido / distracción',l:'N2'}]},
  { k:'況', level:'N2', meanings:['situación / circunstancia'], on:['キョウ'], kun:[],
    words:[{w:'状況',f:'じょうきょう',m:'situación',l:'N2'},{w:'景況',f:'けいきょう',m:'condición económica',l:'N2'},{w:'好況',f:'こうきょう',m:'auge económico',l:'N2'}]},
  { k:'泉', level:'N2', meanings:['manantial / fuente'], on:['セン'], kun:['いずみ'],
    words:[{w:'温泉',f:'おんせん',m:'aguas termales',l:'N4'},{w:'泉',f:'いずみ',m:'manantial',l:'N2'},{w:'源泉',f:'げんせん',m:'fuente original',l:'N2'}]},
  { k:'泊', level:'N2', meanings:['alojarse / pernoctar'], on:['ハク'], kun:['と'],
    words:[{w:'泊まる',f:'とまる',m:'alojarse',l:'N4'},{w:'一泊',f:'いっぱく',m:'una noche',l:'N3'},{w:'宿泊',f:'しゅくはく',m:'alojamiento',l:'N3'}]},
  { k:'波', level:'N2', meanings:['ola / onda'], on:['ハ'], kun:['なみ'],
    words:[{w:'波',f:'なみ',m:'ola',l:'N3'},{w:'電波',f:'でんぱ',m:'onda de radio',l:'N2'},{w:'波紋',f:'はもん',m:'ondas concéntricas / repercusión',l:'N2'}]},
  { k:'泥', level:'N2', meanings:['barro / lodo'], on:['デイ'], kun:['どろ'],
    words:[{w:'泥',f:'どろ',m:'barro / lodo',l:'N3'},{w:'泥棒',f:'どろぼう',m:'ladrón',l:'N3'},{w:'泥沼',f:'どろぬま',m:'pantano / situación sin salida',l:'N2'}]},
  { k:'浅', level:'N2', meanings:['poco profundo / superficial'], on:['セン'], kun:['あさ'],
    words:[{w:'浅い',f:'あさい',m:'poco profundo',l:'N3'},{w:'浅瀬',f:'あさせ',m:'bajío / aguas poco profundas',l:'N2'},{w:'浅はか',f:'あさはか',m:'superficial / frivolo',l:'N2'}]},
  { k:'浴', level:'N2', meanings:['bañarse'], on:['ヨク'], kun:['あ'],
    words:[{w:'入浴',f:'にゅうよく',m:'baño / bañarse',l:'N3'},{w:'浴びる',f:'あびる',m:'ducharse / recibir',l:'N3'},{w:'浴室',f:'よくしつ',m:'cuarto de baño',l:'N2'}]},
  { k:'涙', level:'N2', meanings:['lágrima'], on:['ルイ'], kun:['なみだ'],
    words:[{w:'涙',f:'なみだ',m:'lágrima',l:'N3'},{w:'涙ぐむ',f:'なみだぐむ',m:'estar al borde del llanto',l:'N2'},{w:'感涙',f:'かんるい',m:'lágrimas de emoción',l:'N2'}]},
  { k:'液', level:'N2', meanings:['líquido / fluido'], on:['エキ'], kun:[],
    words:[{w:'液体',f:'えきたい',m:'líquido',l:'N2'},{w:'血液',f:'けつえき',m:'sangre',l:'N2'},{w:'溶液',f:'ようえき',m:'solución (química)',l:'N2'}]},
  { k:'涼', level:'N2', meanings:['fresco / refrescante'], on:['リョウ'], kun:['すず'],
    words:[{w:'涼しい',f:'すずしい',m:'fresco / agradable',l:'N4'},{w:'納涼',f:'のうりょう',m:'disfrutar del fresco',l:'N2'},{w:'涼む',f:'すずむ',m:'refrescarse',l:'N2'}]},
  { k:'混', level:'N2', meanings:['mezclar'], on:['コン'], kun:['ま'],
    words:[{w:'混雑',f:'こんざつ',m:'aglomeración / congestión',l:'N3'},{w:'混乱',f:'こんらん',m:'confusión / caos',l:'N2'},{w:'混合',f:'こんごう',m:'mezcla',l:'N2'}]},
  { k:'清', level:'N2', meanings:['limpio / puro'], on:['セイ'], kun:['きよ'],
    words:[{w:'清潔',f:'せいけつ',m:'limpieza / higiene',l:'N3'},{w:'清める',f:'きよめる',m:'purificar',l:'N2'},{w:'清水',f:'きよみず',m:'agua clara',l:'N2'}]},
  { k:'減', level:'N2', meanings:['disminuir / reducir'], on:['ゲン'], kun:['へ'],
    words:[{w:'減る',f:'へる',m:'disminuir',l:'N3'},{w:'削減',f:'さくげん',m:'reducción / recorte',l:'N2'},{w:'増減',f:'ぞうげん',m:'aumento y disminución',l:'N2'}]},
  { k:'温', level:'N2', meanings:['temperatura / tibio'], on:['オン'], kun:['あたた'],
    words:[{w:'温度',f:'おんど',m:'temperatura',l:'N4'},{w:'温泉',f:'おんせん',m:'aguas termales',l:'N4'},{w:'気温',f:'きおん',m:'temperatura del aire',l:'N3'}]},
  { k:'測', level:'N2', meanings:['medir'], on:['ソク'], kun:['はか'],
    words:[{w:'測る',f:'はかる',m:'medir',l:'N3'},{w:'観測',f:'かんそく',m:'observación',l:'N2'},{w:'測定',f:'そくてい',m:'medición',l:'N2'}]},
  { k:'湖', level:'N2', meanings:['lago'], on:['コ'], kun:['みずうみ'],
    words:[{w:'湖',f:'みずうみ',m:'lago',l:'N4'},{w:'湖畔',f:'こはん',m:'orilla del lago',l:'N2'},{w:'琵琶湖',f:'びわこ',m:'lago Biwa',l:'N2'}]},
  { k:'湯', level:'N2', meanings:['agua caliente'], on:['トウ'], kun:['ゆ'],
    words:[{w:'お湯',f:'おゆ',m:'agua caliente',l:'N5'},{w:'湯船',f:'ゆぶね',m:'bañera',l:'N3'},{w:'湯気',f:'ゆげ',m:'vapor de agua caliente',l:'N2'}]},
  { k:'湾', level:'N2', meanings:['bahía'], on:['ワン'], kun:[],
    words:[{w:'湾',f:'わん',m:'bahía',l:'N2'},{w:'東京湾',f:'とうきょうわん',m:'bahía de Tokio',l:'N2'},{w:'湾岸',f:'わんがん',m:'costa de la bahía',l:'N2'}]},
  { k:'湿', level:'N2', meanings:['húmedo'], on:['シツ'], kun:['しめ'],
    words:[{w:'湿気',f:'しっけ',m:'humedad',l:'N2'},{w:'湿る',f:'しめる',m:'humedecerse',l:'N2'},{w:'湿度',f:'しつど',m:'nivel de humedad',l:'N2'}]},
  { k:'準', level:'N2', meanings:['estándar / nivel'], on:['ジュン'], kun:[],
    words:[{w:'準備',f:'じゅんび',m:'preparación',l:'N4'},{w:'水準',f:'すいじゅん',m:'nivel / estándar',l:'N2'},{w:'標準',f:'ひょうじゅん',m:'estándar',l:'N2'}]},
  { k:'溶', level:'N2', meanings:['disolver / fundir'], on:['ヨウ'], kun:['と'],
    words:[{w:'溶ける',f:'とける',m:'disolverse / fundirse',l:'N3'},{w:'溶かす',f:'とかす',m:'disolver',l:'N3'},{w:'溶液',f:'ようえき',m:'solución',l:'N2'}]},
  { k:'滴', level:'N2', meanings:['gota'], on:['テキ'], kun:['しずく'],
    words:[{w:'一滴',f:'いってき',m:'una gota',l:'N2'},{w:'水滴',f:'すいてき',m:'gota de agua',l:'N2'},{w:'点滴',f:'てんてき',m:'intravenosa / gota a gota',l:'N2'}]},
  { k:'漁', level:'N2', meanings:['pesca'], on:['ギョ'], kun:['りょう'],
    words:[{w:'漁業',f:'ぎょぎょう',m:'industria pesquera',l:'N2'},{w:'漁師',f:'りょうし',m:'pescador',l:'N2'},{w:'漁港',f:'ぎょこう',m:'puerto pesquero',l:'N2'}]},
  { k:'濃', level:'N2', meanings:['denso / concentrado'], on:['ノウ'], kun:['こ'],
    words:[{w:'濃い',f:'こい',m:'denso / espeso',l:'N3'},{w:'濃度',f:'のうど',m:'concentración',l:'N2'},{w:'濃縮',f:'のうしゅく',m:'concentración / condensación',l:'N2'}]},
  { k:'濯', level:'N2', meanings:['lavar / enjuagar'], on:['タク'], kun:['すす'],
    words:[{w:'洗濯',f:'せんたく',m:'lavado / colada',l:'N4'},{w:'洗濯機',f:'せんたくき',m:'lavadora',l:'N4'},{w:'洗濯物',f:'せんたくもの',m:'ropa para lavar',l:'N3'}]},
  { k:'灯', level:'N2', meanings:['lámpara / luz'], on:['トウ'], kun:['ひ'],
    words:[{w:'街灯',f:'がいとう',m:'farola',l:'N2'},{w:'灯台',f:'とうだい',m:'faro',l:'N2'},{w:'照明灯',f:'しょうめいとう',m:'lámpara de iluminación',l:'N2'}]},
  { k:'灰', level:'N2', meanings:['ceniza'], on:['カイ'], kun:['はい'],
    words:[{w:'灰',f:'はい',m:'ceniza',l:'N3'},{w:'灰色',f:'はいいろ',m:'gris',l:'N3'},{w:'灰皿',f:'はいざら',m:'cenicero',l:'N2'}]},
  { k:'炭', level:'N2', meanings:['carbón'], on:['タン'], kun:['すみ'],
    words:[{w:'炭素',f:'たんそ',m:'carbono',l:'N2'},{w:'石炭',f:'せきたん',m:'carbón',l:'N2'},{w:'炭水化物',f:'たんすいかぶつ',m:'carbohidratos',l:'N2'}]},
  { k:'無', level:'N2', meanings:['nada / sin'], on:['ム'], kun:['な'],
    words:[{w:'無理',f:'むり',m:'imposible / excesivo',l:'N4'},{w:'無料',f:'むりょう',m:'gratis',l:'N4'},{w:'無駄',f:'むだ',m:'desperdicio / inútil',l:'N3'}]},
  { k:'焼', level:'N2', meanings:['quemar / asar'], on:['ショウ'], kun:['や'],
    words:[{w:'焼く',f:'やく',m:'quemar / asar',l:'N4'},{w:'焼き肉',f:'やきにく',m:'carne a la parrilla',l:'N4'},{w:'全焼',f:'ぜんしょう',m:'quemado completamente',l:'N2'}]},
  { k:'照', level:'N2', meanings:['iluminar / comparar'], on:['ショウ'], kun:['て'],
    words:[{w:'照らす',f:'てらす',m:'iluminar',l:'N3'},{w:'照れる',f:'てれる',m:'sentirse avergonzado',l:'N3'},{w:'照明',f:'しょうめい',m:'iluminación',l:'N2'}]},
  { k:'燃', level:'N2', meanings:['arder / quemar'], on:['ネン'], kun:['も'],
    words:[{w:'燃える',f:'もえる',m:'arder',l:'N3'},{w:'燃料',f:'ねんりょう',m:'combustible',l:'N2'},{w:'燃焼',f:'ねんしょう',m:'combustión',l:'N2'}]},
  { k:'燥', level:'N2', meanings:['seco / árido'], on:['ソウ'], kun:[],
    words:[{w:'乾燥',f:'かんそう',m:'sequedad / secado',l:'N2'},{w:'高燥',f:'こうそう',m:'árido / elevado y seco',l:'N2'},{w:'燥音',f:'そうおん',m:'ruido seco',l:'N2'}]},
  { k:'爆', level:'N2', meanings:['explotar'], on:['バク'], kun:[],
    words:[{w:'爆発',f:'ばくはつ',m:'explosión',l:'N2'},{w:'爆弾',f:'ばくだん',m:'bomba',l:'N2'},{w:'核爆弾',f:'かくばくだん',m:'bomba nuclear',l:'N2'}]},
  { k:'片', level:'N2', meanings:['fragmento / un lado'], on:['ヘン'], kun:['かた'],
    words:[{w:'片付ける',f:'かたづける',m:'ordenar / recoger',l:'N4'},{w:'片方',f:'かたほう',m:'un lado / uno de los dos',l:'N3'},{w:'断片',f:'だんぺん',m:'fragmento / trozo',l:'N2'}]},
  { k:'版', level:'N2', meanings:['versión / edición'], on:['ハン'], kun:[],
    words:[{w:'出版',f:'しゅっぱん',m:'publicación editorial',l:'N2'},{w:'版',f:'はん',m:'versión / edición',l:'N2'},{w:'初版',f:'しょはん',m:'primera edición',l:'N2'}]},
  { k:'玉', level:'N2', meanings:['bola / joya'], on:['ギョク'], kun:['たま'],
    words:[{w:'玉',f:'たま',m:'bola / joya',l:'N4'},{w:'宝玉',f:'ほうぎょく',m:'piedra preciosa',l:'N2'},{w:'目玉',f:'めだま',m:'globo ocular / producto estrella',l:'N2'}]},
  { k:'珍', level:'N2', meanings:['raro / precioso'], on:['チン'], kun:['めずら'],
    words:[{w:'珍しい',f:'めずらしい',m:'raro / inusual',l:'N3'},{w:'珍味',f:'ちんみ',m:'manjar / exquisitez',l:'N2'},{w:'珍事',f:'ちんじ',m:'suceso extraño',l:'N2'}]},
  { k:'瓶', level:'N2', meanings:['botella / frasco'], on:['ビン'], kun:[],
    words:[{w:'瓶',f:'びん',m:'botella',l:'N3'},{w:'花瓶',f:'かびん',m:'jarrón / florero',l:'N3'},{w:'瓶詰め',f:'びんづめ',m:'en botella',l:'N2'}]},
  { k:'甘', level:'N2', meanings:['dulce / indulgente'], on:['カン'], kun:['あま'],
    words:[{w:'甘い',f:'あまい',m:'dulce',l:'N4'},{w:'甘やかす',f:'あまやかす',m:'mimar / consentir',l:'N2'},{w:'甘味',f:'あまみ',m:'dulzor',l:'N2'}]},
  { k:'畜', level:'N2', meanings:['ganado / bestia'], on:['チク'], kun:[],
    words:[{w:'家畜',f:'かちく',m:'ganado / animales domésticos',l:'N2'},{w:'畜産',f:'ちくさん',m:'ganadería',l:'N2'},{w:'畜生',f:'ちくしょう',m:'maldición / bestia',l:'N2'}]},
  { k:'略', level:'N2', meanings:['abreviación / estrategia'], on:['リャク'], kun:[],
    words:[{w:'略',f:'りゃく',m:'abreviación',l:'N3'},{w:'戦略',f:'せんりゃく',m:'estrategia',l:'N3'},{w:'省略',f:'しょうりゃく',m:'omisión / abreviación',l:'N2'}]},
  { k:'畳', level:'N2', meanings:['tatami / doblar'], on:['ジョウ'], kun:['たた'],
    words:[{w:'畳',f:'たたみ',m:'tatami',l:'N3'},{w:'畳む',f:'たたむ',m:'doblar / plegar',l:'N3'},{w:'六畳',f:'ろくじょう',m:'habitación de 6 tatamis',l:'N2'}]},
  { k:'療', level:'N2', meanings:['tratamiento médico'], on:['リョウ'], kun:[],
    words:[{w:'医療',f:'いりょう',m:'atención médica',l:'N4'},{w:'治療',f:'ちりょう',m:'tratamiento médico',l:'N3'},{w:'療養',f:'りょうよう',m:'convalecencia',l:'N2'}]},
  { k:'皮', level:'N2', meanings:['piel / corteza'], on:['ヒ'], kun:['かわ'],
    words:[{w:'皮',f:'かわ',m:'piel / corteza',l:'N3'},{w:'皮膚',f:'ひふ',m:'piel / dermis',l:'N2'},{w:'果皮',f:'かひ',m:'cáscara de fruta',l:'N2'}]},
  { k:'皿', level:'N2', meanings:['plato / bandeja'], on:[], kun:['さら'],
    words:[{w:'皿',f:'さら',m:'plato',l:'N4'},{w:'皿洗い',f:'さらあらい',m:'lavar platos',l:'N3'},{w:'灰皿',f:'はいざら',m:'cenicero',l:'N2'}]},
  { k:'省', level:'N2', meanings:['ministerio / ahorrar'], on:['ショウ'], kun:['はぶ'],
    words:[{w:'反省',f:'はんせい',m:'reflexión / arrepentimiento',l:'N3'},{w:'省エネ',f:'しょうえね',m:'ahorro energético',l:'N2'},{w:'外務省',f:'がいむしょう',m:'Ministerio de Asuntos Exteriores',l:'N2'}]},
  { k:'県', level:'N2', meanings:['prefectura'], on:['ケン'], kun:[],
    words:[{w:'県',f:'けん',m:'prefectura',l:'N4'},{w:'県庁',f:'けんちょう',m:'oficina prefectural',l:'N2'},{w:'都道府県',f:'とどうふけん',m:'prefecturas de Japón',l:'N2'}]},
  { k:'短', level:'N2', meanings:['corto / breve'], on:['タン'], kun:['みじか'],
    words:[{w:'短い',f:'みじかい',m:'corto',l:'N5'},{w:'短所',f:'たんしょ',m:'defecto / punto débil',l:'N3'},{w:'短縮',f:'たんしゅく',m:'acortamiento / reducción',l:'N2'}]},
  { k:'砂', level:'N2', meanings:['arena'], on:['サ'], kun:['すな'],
    words:[{w:'砂糖',f:'さとう',m:'azúcar',l:'N4'},{w:'砂',f:'すな',m:'arena',l:'N3'},{w:'砂漠',f:'さばく',m:'desierto',l:'N2'}]},
  { k:'硬', level:'N2', meanings:['duro / rígido'], on:['コウ'], kun:['かた'],
    words:[{w:'硬い',f:'かたい',m:'duro / rígido',l:'N3'},{w:'硬貨',f:'こうか',m:'moneda metálica',l:'N2'},{w:'硬直',f:'こうちょく',m:'rigidez',l:'N2'}]},
  { k:'磨', level:'N2', meanings:['pulir / cepillar'], on:['マ'], kun:['みが'],
    words:[{w:'歯磨き',f:'はみがき',m:'cepillado dental',l:'N4'},{w:'磨く',f:'みがく',m:'pulir / cepillar',l:'N3'},{w:'研磨',f:'けんま',m:'pulido / esmerilado',l:'N2'}]},
  { k:'祈', level:'N2', meanings:['rezar / desear'], on:['キ'], kun:['いの'],
    words:[{w:'祈る',f:'いのる',m:'rezar / desear',l:'N4'},{w:'祈り',f:'いのり',m:'oración / deseo',l:'N3'},{w:'祈願',f:'きがん',m:'petición / oración',l:'N2'}]},
  { k:'祝', level:'N2', meanings:['celebrar / felicitar'], on:['シュク'], kun:['いわ'],
    words:[{w:'お祝い',f:'おいわい',m:'felicitación / celebración',l:'N4'},{w:'祝日',f:'しゅくじつ',m:'día festivo',l:'N4'},{w:'祝賀',f:'しゅくが',m:'celebración',l:'N2'}]},
  { k:'祭', level:'N2', meanings:['festival / celebrar'], on:['サイ'], kun:['まつ'],
    words:[{w:'お祭り',f:'おまつり',m:'festival',l:'N4'},{w:'祭日',f:'さいじつ',m:'día festivo',l:'N3'},{w:'文化祭',f:'ぶんかさい',m:'festival cultural',l:'N2'}]},
  { k:'禁', level:'N2', meanings:['prohibir'], on:['キン'], kun:[],
    words:[{w:'禁止',f:'きんし',m:'prohibición',l:'N4'},{w:'禁煙',f:'きんえん',m:'no fumar',l:'N4'},{w:'禁じる',f:'きんじる',m:'prohibir',l:'N2'}]},
  { k:'秒', level:'N2', meanings:['segundo (tiempo)'], on:['ビョウ'], kun:[],
    words:[{w:'秒',f:'びょう',m:'segundo',l:'N4'},{w:'数秒',f:'すうびょう',m:'unos segundos',l:'N3'},{w:'秒針',f:'びょうしん',m:'segundero',l:'N2'}]},
  { k:'移', level:'N2', meanings:['trasladar / mudar'], on:['イ'], kun:['うつ'],
    words:[{w:'移動',f:'いどう',m:'movimiento / desplazamiento',l:'N3'},{w:'移る',f:'うつる',m:'moverse / trasladarse',l:'N3'},{w:'移住',f:'いじゅう',m:'emigración / inmigración',l:'N2'}]},
  { k:'税', level:'N2', meanings:['impuesto'], on:['ゼイ'], kun:[],
    words:[{w:'消費税',f:'しょうひぜい',m:'impuesto sobre el consumo',l:'N3'},{w:'税金',f:'ぜいきん',m:'impuesto',l:'N3'},{w:'納税',f:'のうぜい',m:'pago de impuestos',l:'N2'}]},
  { k:'章', level:'N2', meanings:['capítulo / sección'], on:['ショウ'], kun:[],
    words:[{w:'文章',f:'ぶんしょう',m:'texto / redacción',l:'N3'},{w:'章',f:'しょう',m:'capítulo / sección',l:'N2'},{w:'勲章',f:'くんしょう',m:'condecoración / medalla',l:'N2'}]},
  { k:'童', level:'N2', meanings:['niño / infantil'], on:['ドウ'], kun:['わらべ'],
    words:[{w:'童話',f:'どうわ',m:'cuento infantil',l:'N4'},{w:'児童',f:'じどう',m:'niño / alumno',l:'N2'},{w:'童謡',f:'どうよう',m:'canción infantil',l:'N2'}]},
  { k:'競', level:'N2', meanings:['competir'], on:['キョウ'], kun:['きそ'],
    words:[{w:'競争',f:'きょうそう',m:'competencia',l:'N3'},{w:'競技',f:'きょうぎ',m:'evento deportivo',l:'N2'},{w:'競う',f:'きそう',m:'competir',l:'N2'}]},
  { k:'竹', level:'N2', meanings:['bambú'], on:['チク'], kun:['たけ'],
    words:[{w:'竹',f:'たけ',m:'bambú',l:'N4'},{w:'竹林',f:'ちくりん',m:'bosque de bambú',l:'N2'},{w:'竹馬',f:'たけうま',m:'zancos de bambú',l:'N2'}]},
  { k:'符', level:'N2', meanings:['símbolo / billete'], on:['フ'], kun:[],
    words:[{w:'切符',f:'きっぷ',m:'billete (tren)',l:'N5'},{w:'符号',f:'ふごう',m:'símbolo / signo',l:'N2'},{w:'お符',f:'おふだ',m:'amuleto',l:'N2'}]},
  { k:'筆', level:'N2', meanings:['pincel / escritura'], on:['ヒツ'], kun:['ふで'],
    words:[{w:'鉛筆',f:'えんぴつ',m:'lápiz',l:'N5'},{w:'筆者',f:'ひっしゃ',m:'autor / escritor',l:'N2'},{w:'毛筆',f:'もうひつ',m:'pincel',l:'N2'}]},
  { k:'筒', level:'N2', meanings:['tubo / cilindro'], on:['トウ'], kun:['つつ'],
    words:[{w:'封筒',f:'ふうとう',m:'sobre (correo)',l:'N3'},{w:'水筒',f:'すいとう',m:'cantimplora',l:'N3'},{w:'筒',f:'つつ',m:'tubo / cilindro',l:'N2'}]},
  { k:'算', level:'N2', meanings:['calcular / aritmética'], on:['サン'], kun:[],
    words:[{w:'算数',f:'さんすう',m:'aritmética',l:'N4'},{w:'計算',f:'けいさん',m:'cálculo',l:'N4'},{w:'予算',f:'よさん',m:'presupuesto',l:'N3'}]},
  { k:'管', level:'N2', meanings:['tubo / gestionar'], on:['カン'], kun:['くだ'],
    words:[{w:'管理',f:'かんり',m:'gestión / administración',l:'N4'},{w:'血管',f:'けっかん',m:'vaso sanguíneo',l:'N2'},{w:'気管',f:'きかん',m:'tráquea',l:'N2'}]},
  { k:'築', level:'N2', meanings:['construir / edificar'], on:['チク'], kun:['きず'],
    words:[{w:'建築',f:'けんちく',m:'arquitectura / construcción',l:'N3'},{w:'築く',f:'きずく',m:'construir / crear',l:'N2'},{w:'築城',f:'ちくじょう',m:'construcción de castillo',l:'N2'}]},
  { k:'簡', level:'N2', meanings:['simple / sencillo'], on:['カン'], kun:[],
    words:[{w:'簡単',f:'かんたん',m:'fácil / simple',l:'N5'},{w:'簡潔',f:'かんけつ',m:'conciso',l:'N2'},{w:'簡略',f:'かんりゃく',m:'simplificado',l:'N2'}]},
  { k:'籍', level:'N2', meanings:['registro / libro'], on:['セキ'], kun:[],
    words:[{w:'国籍',f:'こくせき',m:'nacionalidad',l:'N2'},{w:'書籍',f:'しょせき',m:'libro / publicación',l:'N2'},{w:'学籍',f:'がくせき',m:'registro escolar',l:'N2'}]},
  { k:'粉', level:'N2', meanings:['polvo / harina'], on:['フン'], kun:['こな'],
    words:[{w:'粉',f:'こな',m:'polvo / harina',l:'N3'},{w:'花粉',f:'かふん',m:'polen',l:'N3'},{w:'粉末',f:'ふんまつ',m:'polvo',l:'N2'}]},
  { k:'粒', level:'N2', meanings:['grano / partícula'], on:['リュウ'], kun:['つぶ'],
    words:[{w:'粒',f:'つぶ',m:'grano / partícula',l:'N3'},{w:'一粒',f:'ひとつぶ',m:'un grano',l:'N2'},{w:'粒子',f:'りゅうし',m:'partícula',l:'N2'}]},
  { k:'糸', level:'N2', meanings:['hilo'], on:['シ'], kun:['いと'],
    words:[{w:'糸',f:'いと',m:'hilo',l:'N4'},{w:'毛糸',f:'けいと',m:'hilo de lana',l:'N3'},{w:'糸口',f:'いとぐち',m:'comienzo / pista',l:'N2'}]},
  { k:'紅', level:'N2', meanings:['rojo escarlata'], on:['コウ'], kun:['べに'],
    words:[{w:'紅茶',f:'こうちゃ',m:'té negro',l:'N4'},{w:'紅葉',f:'こうよう',m:'hojas otoñales',l:'N3'},{w:'口紅',f:'くちべに',m:'pintalabios',l:'N2'}]},
  { k:'純', level:'N2', meanings:['puro / simple'], on:['ジュン'], kun:[],
    words:[{w:'単純',f:'たんじゅん',m:'simple',l:'N3'},{w:'純粋',f:'じゅんすい',m:'puro',l:'N2'},{w:'純利益',f:'じゅんりえき',m:'beneficio neto',l:'N2'}]},
  { k:'細', level:'N2', meanings:['fino / delgado / detalle'], on:['サイ'], kun:['こま'],
    words:[{w:'細かい',f:'こまかい',m:'fino / detallado',l:'N3'},{w:'細胞',f:'さいぼう',m:'célula',l:'N2'},{w:'詳細',f:'しょうさい',m:'detalles',l:'N2'}]},
  { k:'紹', level:'N2', meanings:['presentar'], on:['ショウ'], kun:[],
    words:[{w:'紹介',f:'しょうかい',m:'presentación / introducción',l:'N4'},{w:'自己紹介',f:'じこしょうかい',m:'autopresentación',l:'N3'},{w:'紹介状',f:'しょうかいじょう',m:'carta de presentación',l:'N2'}]},
  { k:'絡', level:'N2', meanings:['conectar / enredar'], on:['ラク'], kun:['から'],
    words:[{w:'連絡',f:'れんらく',m:'contacto / comunicación',l:'N4'},{w:'絡む',f:'からむ',m:'enredarse',l:'N3'},{w:'絡める',f:'からめる',m:'enredar / implicar',l:'N2'}]},
  { k:'綿', level:'N2', meanings:['algodón'], on:['メン'], kun:['わた'],
    words:[{w:'綿',f:'わた',m:'algodón / relleno',l:'N3'},{w:'木綿',f:'もめん',m:'algodón',l:'N3'},{w:'綿密',f:'めんみつ',m:'meticuloso / minucioso',l:'N2'}]},
  { k:'総', level:'N2', meanings:['total / general'], on:['ソウ'], kun:[],
    words:[{w:'総数',f:'そうすう',m:'número total',l:'N2'},{w:'総合',f:'そうごう',m:'síntesis / general',l:'N2'},{w:'総理',f:'そうり',m:'primer ministro',l:'N2'}]},
  { k:'緑', level:'N2', meanings:['verde'], on:['リョク'], kun:['みどり'],
    words:[{w:'緑',f:'みどり',m:'verde',l:'N5'},{w:'緑茶',f:'りょくちゃ',m:'té verde',l:'N4'},{w:'新緑',f:'しんりょく',m:'verde fresco (primavera)',l:'N2'}]},
  { k:'線', level:'N2', meanings:['línea / ruta'], on:['セン'], kun:[],
    words:[{w:'線',f:'せん',m:'línea',l:'N4'},{w:'路線',f:'ろせん',m:'ruta / línea de transporte',l:'N3'},{w:'直線',f:'ちょくせん',m:'línea recta',l:'N2'}]},
  { k:'編', level:'N2', meanings:['tejer / editar'], on:['ヘン'], kun:['あ'],
    words:[{w:'編む',f:'あむ',m:'tejer',l:'N3'},{w:'編集',f:'へんしゅう',m:'edición / redacción',l:'N2'},{w:'長編',f:'ちょうへん',m:'obra larga',l:'N2'}]},
  { k:'績', level:'N2', meanings:['logro / mérito'], on:['セキ'], kun:[],
    words:[{w:'成績',f:'せいせき',m:'resultados / calificaciones',l:'N3'},{w:'実績',f:'じっせき',m:'logro / resultado real',l:'N2'},{w:'業績',f:'ぎょうせき',m:'resultado / logro empresarial',l:'N2'}]},
  { k:'缶', level:'N2', meanings:['lata'], on:['カン'], kun:[],
    words:[{w:'缶',f:'かん',m:'lata',l:'N3'},{w:'缶詰',f:'かんづめ',m:'conservas',l:'N3'},{w:'缶切り',f:'かんきり',m:'abrelatas',l:'N2'}]},
  { k:'署', level:'N2', meanings:['oficina / firmar'], on:['ショ'], kun:[],
    words:[{w:'警察署',f:'けいさつしょ',m:'comisaría',l:'N2'},{w:'消防署',f:'しょうぼうしょ',m:'cuartel de bomberos',l:'N2'},{w:'署名',f:'しょめい',m:'firma',l:'N2'}]},
  { k:'群', level:'N2', meanings:['grupo / manada'], on:['グン'], kun:['む'],
    words:[{w:'群れ',f:'むれ',m:'manada / grupo',l:'N3'},{w:'群衆',f:'ぐんしゅう',m:'multitud',l:'N2'},{w:'群島',f:'ぐんとう',m:'archipiélago',l:'N2'}]},
  { k:'羽', level:'N2', meanings:['pluma / ala'], on:['ウ'], kun:['はね'],
    words:[{w:'羽',f:'はね',m:'pluma / ala',l:'N4'},{w:'羽根',f:'はね',m:'pluma / paleta',l:'N3'},{w:'羽毛',f:'うもう',m:'plumón',l:'N2'}]},
  { k:'翌', level:'N2', meanings:['al día siguiente'], on:['ヨク'], kun:[],
    words:[{w:'翌日',f:'よくじつ',m:'al día siguiente',l:'N3'},{w:'翌朝',f:'よくあさ',m:'a la mañana siguiente',l:'N2'},{w:'翌年',f:'よくねん',m:'al año siguiente',l:'N2'}]},
  { k:'耕', level:'N2', meanings:['cultivar / labrar'], on:['コウ'], kun:['たがや'],
    words:[{w:'耕す',f:'たがやす',m:'cultivar / labrar',l:'N2'},{w:'農耕',f:'のうこう',m:'agricultura',l:'N2'},{w:'耕地',f:'こうち',m:'tierra de cultivo',l:'N2'}]},
  { k:'肌', level:'N2', meanings:['piel / tez'], on:[], kun:['はだ'],
    words:[{w:'肌',f:'はだ',m:'piel / tez',l:'N3'},{w:'肌着',f:'はだぎ',m:'ropa interior',l:'N3'},{w:'肌触り',f:'はだざわり',m:'textura al tacto',l:'N2'}]},
  { k:'肩', level:'N2', meanings:['hombro'], on:[], kun:['かた'],
    words:[{w:'肩',f:'かた',m:'hombro',l:'N4'},{w:'肩こり',f:'かたこり',m:'tensión en el hombro',l:'N3'},{w:'肩書き',f:'かたがき',m:'título / cargo',l:'N2'}]},
  { k:'肯', level:'N2', meanings:['asentir / afirmar'], on:['コウ'], kun:[],
    words:[{w:'肯定',f:'こうてい',m:'afirmación',l:'N2'},{w:'肯く',f:'うなずく',m:'asentir',l:'N2'},{w:'否肯',f:'ひこう',m:'sí o no',l:'N2'}]},
  { k:'胃', level:'N2', meanings:['estómago'], on:['イ'], kun:[],
    words:[{w:'胃',f:'い',m:'estómago',l:'N4'},{w:'胃腸',f:'いちょう',m:'estómago e intestinos',l:'N2'},{w:'胃薬',f:'いぐすり',m:'medicina para el estómago',l:'N2'}]},
  { k:'胸', level:'N2', meanings:['pecho / corazón'], on:['キョウ'], kun:['むね'],
    words:[{w:'胸',f:'むね',m:'pecho',l:'N4'},{w:'胸焼け',f:'むねやけ',m:'acidez estomacal',l:'N2'},{w:'胸がいっぱい',f:'むねがいっぱい',m:'abrumado de emoción',l:'N2'}]},
  { k:'脂', level:'N2', meanings:['grasa / sebo'], on:['シ'], kun:['あぶら'],
    words:[{w:'脂肪',f:'しぼう',m:'grasa corporal',l:'N2'},{w:'脂っこい',f:'あぶらっこい',m:'grasoso',l:'N2'},{w:'皮脂',f:'ひし',m:'sebo / grasa de la piel',l:'N2'}]},
  { k:'脳', level:'N2', meanings:['cerebro'], on:['ノウ'], kun:[],
    words:[{w:'脳',f:'のう',m:'cerebro',l:'N3'},{w:'脳細胞',f:'のうさいぼう',m:'neurona',l:'N2'},{w:'洗脳',f:'せんのう',m:'lavado de cerebro',l:'N2'}]},
  { k:'腕', level:'N2', meanings:['brazo'], on:['ワン'], kun:['うで'],
    words:[{w:'腕',f:'うで',m:'brazo',l:'N4'},{w:'腕時計',f:'うでどけい',m:'reloj de pulsera',l:'N4'},{w:'腕前',f:'うでまえ',m:'habilidad / destreza',l:'N2'}]},
  { k:'腰', level:'N2', meanings:['cintura / caderas'], on:['ヨウ'], kun:['こし'],
    words:[{w:'腰',f:'こし',m:'cintura / caderas',l:'N4'},{w:'腰痛',f:'ようつう',m:'dolor de espalda',l:'N2'},{w:'腰を下ろす',f:'こしをおろす',m:'sentarse',l:'N2'}]},
  { k:'膚', level:'N2', meanings:['piel / dermis'], on:['フ'], kun:['はだ'],
    words:[{w:'皮膚',f:'ひふ',m:'piel / dermis',l:'N2'},{w:'皮膚科',f:'ひふか',m:'dermatología',l:'N2'},{w:'膚触り',f:'はだざわり',m:'textura',l:'N2'}]},
  { k:'臓', level:'N2', meanings:['órgano interno'], on:['ゾウ'], kun:[],
    words:[{w:'心臓',f:'しんぞう',m:'corazón',l:'N2'},{w:'肝臓',f:'かんぞう',m:'hígado',l:'N2'},{w:'臓器',f:'ぞうき',m:'órgano',l:'N2'}]},
  { k:'臣', level:'N2', meanings:['vasallo / ministro'], on:['シン'], kun:[],
    words:[{w:'臣民',f:'しんみん',m:'súbdito',l:'N2'},{w:'大臣',f:'だいじん',m:'ministro',l:'N2'},{w:'家臣',f:'かしん',m:'vasallo / súbdito',l:'N2'}]},
  { k:'舟', level:'N2', meanings:['barca / barco pequeño'], on:['シュウ'], kun:['ふね'],
    words:[{w:'舟',f:'ふね',m:'barca',l:'N3'},{w:'舟遊び',f:'ふなあそび',m:'paseo en barca',l:'N2'},{w:'舟歌',f:'ふなうた',m:'canción marinera',l:'N2'}]},
  { k:'航', level:'N2', meanings:['navegar'], on:['コウ'], kun:[],
    words:[{w:'航空',f:'こうくう',m:'aviación',l:'N4'},{w:'航海',f:'こうかい',m:'navegación',l:'N3'},{w:'運航',f:'うんこう',m:'operación de buque/avión',l:'N2'}]},
  { k:'般', level:'N2', meanings:['general / clase'], on:['ハン'], kun:[],
    words:[{w:'一般',f:'いっぱん',m:'en general',l:'N3'},{w:'全般',f:'ぜんぱん',m:'en general / toda',l:'N2'},{w:'般若',f:'はんにゃ',m:'prajna / máscara japonesa',l:'N2'}]},
  { k:'芸', level:'N2', meanings:['arte / habilidad'], on:['ゲイ'], kun:[],
    words:[{w:'芸術',f:'げいじゅつ',m:'arte',l:'N3'},{w:'芸能',f:'げいのう',m:'espectáculos / entretenimiento',l:'N2'},{w:'芸人',f:'げいにん',m:'artista / comediante',l:'N2'}]},
  { k:'荒', level:'N2', meanings:['salvaje / rugoso'], on:['コウ'], kun:['あら'],
    words:[{w:'荒れる',f:'あれる',m:'estar revuelto / deteriorarse',l:'N3'},{w:'荒い',f:'あらい',m:'brusco / rugoso',l:'N3'},{w:'荒廃',f:'こうはい',m:'devastación / deterioro',l:'N2'}]},
  { k:'荷', level:'N2', meanings:['carga / equipaje'], on:['カ'], kun:['に'],
    words:[{w:'荷物',f:'にもつ',m:'equipaje / carga',l:'N4'},{w:'出荷',f:'しゅっか',m:'envío / expedición',l:'N2'},{w:'入荷',f:'にゅうか',m:'llegada de mercancía',l:'N2'}]},
  { k:'菓', level:'N2', meanings:['dulce / confitería'], on:['カ'], kun:[],
    words:[{w:'菓子',f:'かし',m:'dulce / confite',l:'N4'},{w:'和菓子',f:'わがし',m:'dulce japonés',l:'N3'},{w:'洋菓子',f:'ようがし',m:'pastelería occidental',l:'N2'}]},
  { k:'菜', level:'N2', meanings:['verdura'], on:['サイ'], kun:['な'],
    words:[{w:'野菜',f:'やさい',m:'verdura',l:'N5'},{w:'菜の花',f:'なのはな',m:'flor de colza',l:'N2'},{w:'前菜',f:'ぜんさい',m:'entrante / aperitivo',l:'N2'}]},
  { k:'著', level:'N2', meanings:['notable / autor'], on:['チョ'], kun:['いちじる'],
    words:[{w:'著者',f:'ちょしゃ',m:'autor',l:'N2'},{w:'著作',f:'ちょさく',m:'obra literaria',l:'N2'},{w:'著しい',f:'いちじるしい',m:'notable / marcado',l:'N2'}]},
  { k:'蒸', level:'N2', meanings:['vapor / cocinar al vapor'], on:['ジョウ'], kun:['む'],
    words:[{w:'蒸す',f:'むす',m:'cocinar al vapor',l:'N3'},{w:'蒸気',f:'じょうき',m:'vapor',l:'N2'},{w:'蒸発',f:'じょうはつ',m:'evaporación',l:'N2'}]},
  { k:'蔵', level:'N2', meanings:['almacén / depósito'], on:['ゾウ'], kun:['くら'],
    words:[{w:'冷蔵庫',f:'れいぞうこ',m:'refrigerador',l:'N4'},{w:'土蔵',f:'どぞう',m:'almacén tradicional japonés',l:'N2'},{w:'蔵書',f:'ぞうしょ',m:'colección de libros',l:'N2'}]},
  { k:'薄', level:'N2', meanings:['fino / tenue'], on:['ハク'], kun:['うす'],
    words:[{w:'薄い',f:'うすい',m:'delgado / fino',l:'N3'},{w:'薄暗い',f:'うすぐらい',m:'tenuemente iluminado',l:'N2'},{w:'希薄',f:'きはく',m:'tenue / escaso',l:'N2'}]},
  { k:'虫', level:'N2', meanings:['insecto / bicho'], on:['チュウ'], kun:['むし'],
    words:[{w:'虫',f:'むし',m:'insecto',l:'N5'},{w:'虫歯',f:'むしば',m:'caries',l:'N3'},{w:'殺虫剤',f:'さっちゅうざい',m:'insecticida',l:'N2'}]},
  { k:'血', level:'N2', meanings:['sangre'], on:['ケツ'], kun:['ち'],
    words:[{w:'血',f:'ち',m:'sangre',l:'N4'},{w:'血液',f:'けつえき',m:'sangre',l:'N2'},{w:'輸血',f:'ゆけつ',m:'transfusión de sangre',l:'N2'}]},
  { k:'衣', level:'N2', meanings:['ropa / vestido'], on:['イ'], kun:['ころも'],
    words:[{w:'衣服',f:'いふく',m:'ropa',l:'N2'},{w:'衣類',f:'いるい',m:'prendas de vestir',l:'N2'},{w:'白衣',f:'はくい',m:'bata blanca',l:'N2'}]},
  { k:'袋', level:'N2', meanings:['bolsa'], on:['タイ'], kun:['ふくろ'],
    words:[{w:'袋',f:'ふくろ',m:'bolsa',l:'N4'},{w:'手袋',f:'てぶくろ',m:'guantes',l:'N4'},{w:'ゴミ袋',f:'ごみぶくろ',m:'bolsa de basura',l:'N3'}]},
  { k:'被', level:'N2', meanings:['sufrir / recibir'], on:['ヒ'], kun:['こうむ'],
    words:[{w:'被害',f:'ひがい',m:'daño / perjuicio',l:'N3'},{w:'被る',f:'こうむる',m:'sufrir / recibir',l:'N2'},{w:'被告',f:'ひこく',m:'acusado / demandado',l:'N2'}]},
  { k:'装', level:'N2', meanings:['vestir / equipar'], on:['ソウ'], kun:['よそお'],
    words:[{w:'服装',f:'ふくそう',m:'vestimenta',l:'N4'},{w:'装置',f:'そうち',m:'dispositivo / equipo',l:'N3'},{w:'武装',f:'ぶそう',m:'armado',l:'N2'}]},
  { k:'裏', level:'N2', meanings:['reverso / interior'], on:['リ'], kun:['うら'],
    words:[{w:'裏',f:'うら',m:'reverso / interior',l:'N3'},{w:'裏口',f:'うらぐち',m:'puerta trasera',l:'N3'},{w:'裏返す',f:'うらがえす',m:'dar la vuelta',l:'N2'}]},
  { k:'補', level:'N2', meanings:['suplementar / compensar'], on:['ホ'], kun:['おぎな'],
    words:[{w:'候補',f:'こうほ',m:'candidato',l:'N3'},{w:'補助',f:'ほじょ',m:'ayuda / subsidio',l:'N2'},{w:'補足',f:'ほそく',m:'suplemento / complemento',l:'N2'}]},
  { k:'複', level:'N2', meanings:['múltiple / duplicado'], on:['フク'], kun:[],
    words:[{w:'複雑',f:'ふくざつ',m:'complejo / complicado',l:'N3'},{w:'複数',f:'ふくすう',m:'plural / múltiple',l:'N2'},{w:'複製',f:'ふくせい',m:'réplica / copia',l:'N2'}]},
  { k:'角', level:'N2', meanings:['ángulo / esquina'], on:['カク'], kun:['かど'],
    words:[{w:'三角',f:'さんかく',m:'triángulo',l:'N5'},{w:'角',f:'かど',m:'esquina',l:'N4'},{w:'角度',f:'かくど',m:'ángulo',l:'N2'}]},
  { k:'触', level:'N2', meanings:['tocar'], on:['ショク'], kun:['さわ'],
    words:[{w:'触れる',f:'ふれる',m:'tocar / mencionar',l:'N3'},{w:'接触',f:'せっしょく',m:'contacto',l:'N2'},{w:'触感',f:'しょっかん',m:'sensación al tacto',l:'N2'}]},
  { k:'訓', level:'N2', meanings:['lectura kun / instrucción'], on:['クン'], kun:[],
    words:[{w:'訓練',f:'くんれん',m:'entrenamiento',l:'N4'},{w:'訓読み',f:'くんよみ',m:'lectura kun',l:'N2'},{w:'教訓',f:'きょうくん',m:'enseñanza / moraleja',l:'N2'}]},
  { k:'設', level:'N2', meanings:['establecer / instalar'], on:['セツ'], kun:['もう'],
    words:[{w:'設備',f:'せつび',m:'instalaciones',l:'N3'},{w:'建設',f:'けんせつ',m:'construcción',l:'N3'},{w:'設立',f:'せつりつ',m:'establecimiento / fundación',l:'N2'}]},
  { k:'詞', level:'N2', meanings:['palabra / letra'], on:['シ'], kun:[],
    words:[{w:'歌詞',f:'かし',m:'letra de canción',l:'N4'},{w:'品詞',f:'ひんし',m:'parte del discurso',l:'N2'},{w:'代名詞',f:'だいめいし',m:'pronombre',l:'N2'}]},
  { k:'詰', level:'N2', meanings:['apretar / llenar'], on:['キツ'], kun:['つ'],
    words:[{w:'詰める',f:'つめる',m:'meter / empacar',l:'N3'},{w:'缶詰',f:'かんづめ',m:'conservas',l:'N3'},{w:'行き詰まる',f:'ゆきづまる',m:'llegar a un callejón sin salida',l:'N2'}]},
  { k:'誌', level:'N2', meanings:['revista / registro'], on:['シ'], kun:[],
    words:[{w:'雑誌',f:'ざっし',m:'revista',l:'N4'},{w:'日誌',f:'にっし',m:'diario / registro',l:'N2'},{w:'機関誌',f:'きかんし',m:'publicación oficial',l:'N2'}]},
  { k:'課', level:'N2', meanings:['sección / lección'], on:['カ'], kun:[],
    words:[{w:'課題',f:'かだい',m:'tarea / problema',l:'N3'},{w:'課長',f:'かちょう',m:'jefe de sección',l:'N2'},{w:'税務課',f:'ぜいむか',m:'sección fiscal',l:'N2'}]},
  { k:'諸', level:'N2', meanings:['varios / muchos'], on:['ショ'], kun:[],
    words:[{w:'諸問題',f:'しょもんだい',m:'varios problemas',l:'N2'},{w:'諸国',f:'しょこく',m:'varios países',l:'N2'},{w:'諸外国',f:'しょがいこく',m:'países extranjeros',l:'N2'}]},
  { k:'講', level:'N2', meanings:['conferencia / clase'], on:['コウ'], kun:[],
    words:[{w:'講義',f:'こうぎ',m:'conferencia / clase',l:'N2'},{w:'講師',f:'こうし',m:'instructor / conferenciante',l:'N2'},{w:'講演',f:'こうえん',m:'conferencia pública',l:'N2'}]},
  { k:'谷', level:'N2', meanings:['valle'], on:['コク'], kun:['たに'],
    words:[{w:'谷',f:'たに',m:'valle',l:'N4'},{w:'谷底',f:'たにぞこ',m:'fondo del valle',l:'N2'},{w:'渋谷',f:'しぶや',m:'Shibuya',l:'N2'}]},
  { k:'豊', level:'N2', meanings:['abundante / rico'], on:['ホウ'], kun:['ゆた'],
    words:[{w:'豊か',f:'ゆたか',m:'abundante / próspero',l:'N3'},{w:'豊富',f:'ほうふ',m:'abundante',l:'N3'},{w:'豊作',f:'ほうさく',m:'buena cosecha',l:'N2'}]},
  { k:'象', level:'N2', meanings:['elefante / fenómeno'], on:['ショウ'], kun:['ぞう'],
    words:[{w:'象',f:'ぞう',m:'elefante',l:'N4'},{w:'現象',f:'げんしょう',m:'fenómeno',l:'N2'},{w:'象徴',f:'しょうちょう',m:'símbolo',l:'N2'}]},
  { k:'貝', level:'N2', meanings:['concha / marisco'], on:['カイ'], kun:['かい'],
    words:[{w:'貝',f:'かい',m:'concha',l:'N4'},{w:'貝殻',f:'かいがら',m:'concha marina',l:'N2'},{w:'貝類',f:'かいるい',m:'mariscos / moluscos',l:'N2'}]},
  { k:'貨', level:'N2', meanings:['mercancía / moneda'], on:['カ'], kun:[],
    words:[{w:'貨物',f:'かもつ',m:'carga / mercancía',l:'N2'},{w:'通貨',f:'つうか',m:'moneda / divisa',l:'N2'},{w:'外貨',f:'がいか',m:'moneda extranjera',l:'N2'}]},
  { k:'販', level:'N2', meanings:['vender'], on:['ハン'], kun:[],
    words:[{w:'販売',f:'はんばい',m:'venta',l:'N4'},{w:'自動販売機',f:'じどうはんばいき',m:'máquina expendedora',l:'N3'},{w:'販路',f:'はんろ',m:'canal de ventas',l:'N2'}]},
  { k:'貯', level:'N2', meanings:['ahorrar / almacenar'], on:['チョ'], kun:['た'],
    words:[{w:'貯金',f:'ちょきん',m:'ahorro',l:'N4'},{w:'貯蔵',f:'ちょぞう',m:'almacenamiento',l:'N2'},{w:'貯水',f:'ちょすい',m:'almacenamiento de agua',l:'N2'}]},
  { k:'貿', level:'N2', meanings:['comercio'], on:['ボウ'], kun:[],
    words:[{w:'貿易',f:'ぼうえき',m:'comercio exterior',l:'N3'},{w:'貿易赤字',f:'ぼうえきあかじ',m:'déficit comercial',l:'N2'},{w:'自由貿易',f:'じゆうぼうえき',m:'libre comercio',l:'N2'}]},
  { k:'賞', level:'N2', meanings:['premio / apreciar'], on:['ショウ'], kun:[],
    words:[{w:'賞',f:'しょう',m:'premio',l:'N3'},{w:'入賞',f:'にゅうしょう',m:'ganar un premio',l:'N2'},{w:'受賞',f:'じゅしょう',m:'recibir un premio',l:'N2'}]},
  { k:'賢', level:'N2', meanings:['inteligente / sabio'], on:['ケン'], kun:['かしこ'],
    words:[{w:'賢い',f:'かしこい',m:'inteligente / listo',l:'N3'},{w:'賢明',f:'けんめい',m:'sensato / inteligente',l:'N2'},{w:'賢者',f:'けんじゃ',m:'sabio',l:'N2'}]},
  { k:'贈', level:'N2', meanings:['regalar'], on:['ゾウ'], kun:['おく'],
    words:[{w:'贈る',f:'おくる',m:'regalar',l:'N3'},{w:'贈り物',f:'おくりもの',m:'regalo',l:'N3'},{w:'贈答品',f:'ぞうとうひん',m:'regalo formal',l:'N2'}]},
  { k:'超', level:'N2', meanings:['superar / extra'], on:['チョウ'], kun:['こ'],
    words:[{w:'超える',f:'こえる',m:'superar / cruzar',l:'N3'},{w:'超過',f:'ちょうか',m:'exceso',l:'N2'},{w:'超高速',f:'ちょうこうそく',m:'ultrarrápido',l:'N2'}]},
  { k:'跡', level:'N2', meanings:['rastro / vestigio'], on:['セキ'], kun:['あと'],
    words:[{w:'跡',f:'あと',m:'rastro / huella',l:'N3'},{w:'足跡',f:'あしあと',m:'huella / pisada',l:'N3'},{w:'遺跡',f:'いせき',m:'ruinas / vestigios',l:'N2'}]},
  { k:'踊', level:'N2', meanings:['bailar'], on:['ヨウ'], kun:['おど'],
    words:[{w:'踊る',f:'おどる',m:'bailar',l:'N4'},{w:'踊り',f:'おどり',m:'baile / danza',l:'N3'},{w:'盆踊り',f:'ぼんおどり',m:'danza bon',l:'N2'}]},
  { k:'軍', level:'N2', meanings:['ejército / militar'], on:['グン'], kun:[],
    words:[{w:'軍',f:'ぐん',m:'ejército',l:'N2'},{w:'軍隊',f:'ぐんたい',m:'ejército / tropa',l:'N2'},{w:'海軍',f:'かいぐん',m:'marina / armada',l:'N2'}]},
  { k:'軒', level:'N2', meanings:['alero / contador de casas'], on:['ケン'], kun:['のき'],
    words:[{w:'一軒',f:'いっけん',m:'una casa',l:'N4'},{w:'軒並み',f:'のきなみ',m:'en fila / sin excepción',l:'N2'},{w:'軒下',f:'のきした',m:'bajo el alero',l:'N2'}]},
  { k:'軟', level:'N2', meanings:['blando / suave'], on:['ナン'], kun:['やわ'],
    words:[{w:'軟らかい',f:'やわらかい',m:'blando / suave',l:'N3'},{w:'軟化',f:'なんか',m:'ablandamiento',l:'N2'},{w:'柔軟',f:'じゅうなん',m:'flexible',l:'N2'}]},
  { k:'輪', level:'N2', meanings:['rueda / círculo'], on:['リン'], kun:['わ'],
    words:[{w:'輪',f:'わ',m:'rueda / aro',l:'N3'},{w:'指輪',f:'ゆびわ',m:'anillo',l:'N3'},{w:'車輪',f:'しゃりん',m:'rueda de coche',l:'N2'}]},
  { k:'輸', level:'N2', meanings:['transportar'], on:['ユ'], kun:[],
    words:[{w:'輸入',f:'ゆにゅう',m:'importación',l:'N4'},{w:'輸出',f:'ゆしゅつ',m:'exportación',l:'N3'},{w:'運輸',f:'うんゆ',m:'transporte',l:'N2'}]},
  { k:'辛', level:'N2', meanings:['picante / duro'], on:['シン'], kun:['から'],
    words:[{w:'辛い',f:'からい',m:'picante',l:'N4'},{w:'辛抱',f:'しんぼう',m:'paciencia / aguante',l:'N2'}]},
  { k:'農', level:'N2', meanings:['agricultura'], on:['ノウ'], kun:[],
    words:[{w:'農業',f:'のうぎょう',m:'agricultura',l:'N3'},{w:'農家',f:'のうか',m:'familia campesina / granja',l:'N3'},{w:'農産物',f:'のうさんぶつ',m:'producto agrícola',l:'N2'}]},
  { k:'辺', level:'N2', meanings:['alrededor / zona'], on:['ヘン'], kun:['あた'],
    words:[{w:'辺り',f:'あたり',m:'alrededor / zona',l:'N3'},{w:'海辺',f:'うみべ',m:'orilla del mar',l:'N3'},{w:'周辺',f:'しゅうへん',m:'alrededores',l:'N2'}]},
  { k:'述', level:'N2', meanings:['describir / exponer'], on:['ジュツ'], kun:['の'],
    words:[{w:'述べる',f:'のべる',m:'exponer / describir',l:'N3'},{w:'記述',f:'きじゅつ',m:'descripción / registro',l:'N2'},{w:'口述',f:'こうじゅつ',m:'dictado / declaración oral',l:'N2'}]},
  { k:'逆', level:'N2', meanings:['inverso / opuesto'], on:['ギャク'], kun:['さか'],
    words:[{w:'逆',f:'さか',m:'inverso / opuesto',l:'N3'},{w:'逆に',f:'ぎゃくに',m:'al contrario',l:'N3'},{w:'逆転',f:'ぎゃくてん',m:'inversión / vuelta de tortilla',l:'N2'}]},
  { k:'造', level:'N2', meanings:['fabricar / crear'], on:['ゾウ'], kun:['つく'],
    words:[{w:'造る',f:'つくる',m:'fabricar / crear',l:'N3'},{w:'製造',f:'せいぞう',m:'fabricación',l:'N2'},{w:'改造',f:'かいぞう',m:'reforma / modificación',l:'N2'}]},
  { k:'郊', level:'N2', meanings:['suburbio / afueras'], on:['コウ'], kun:[],
    words:[{w:'郊外',f:'こうがい',m:'suburbios / afueras',l:'N2'},{w:'近郊',f:'きんこう',m:'área suburbana cercana',l:'N2'},{w:'郊外店',f:'こうがいてん',m:'tienda en las afueras',l:'N2'}]},
  { k:'郵', level:'N2', meanings:['correo postal'], on:['ユウ'], kun:[],
    words:[{w:'郵便局',f:'ゆうびんきょく',m:'oficina de correos',l:'N5'},{w:'郵便',f:'ゆうびん',m:'correo postal',l:'N4'},{w:'郵送',f:'ゆうそう',m:'envío postal',l:'N4'}]},
  { k:'量', level:'N2', meanings:['cantidad / medir'], on:['リョウ'], kun:['はか'],
    words:[{w:'量',f:'りょう',m:'cantidad',l:'N3'},{w:'重量',f:'じゅうりょう',m:'peso',l:'N2'},{w:'大量',f:'たいりょう',m:'gran cantidad',l:'N2'}]},
  { k:'針', level:'N2', meanings:['aguja / manecilla'], on:['シン'], kun:['はり'],
    words:[{w:'針',f:'はり',m:'aguja',l:'N3'},{w:'方針',f:'ほうしん',m:'política / directriz',l:'N2'},{w:'秒針',f:'びょうしん',m:'segundero',l:'N2'}]},
  { k:'鈍', level:'N2', meanings:['embotado / lento'], on:['ドン'], kun:['にぶ'],
    words:[{w:'鈍い',f:'にぶい',m:'embotado / lento',l:'N2'},{w:'鈍感',f:'どんかん',m:'insensible',l:'N2'},{w:'鈍化',f:'どんか',m:'ralentización',l:'N2'}]},
  { k:'鉄', level:'N2', meanings:['hierro / férreo'], on:['テツ'], kun:[],
    words:[{w:'地下鉄',f:'ちかてつ',m:'metro',l:'N4'},{w:'鉄道',f:'てつどう',m:'ferrocarril',l:'N3'},{w:'鉄砲',f:'てっぽう',m:'fusil / escopeta',l:'N2'}]},
  { k:'鉱', level:'N2', meanings:['mineral / mina'], on:['コウ'], kun:[],
    words:[{w:'鉱山',f:'こうざん',m:'mina',l:'N2'},{w:'鉱物',f:'こうぶつ',m:'mineral',l:'N2'},{w:'採鉱',f:'さいこう',m:'minería',l:'N2'}]},
  { k:'銅', level:'N2', meanings:['cobre'], on:['ドウ'], kun:[],
    words:[{w:'銅',f:'どう',m:'cobre',l:'N2'},{w:'銅メダル',f:'どうめだる',m:'medalla de bronce',l:'N2'},{w:'銅像',f:'どうぞう',m:'estatua de bronce',l:'N2'}]},
  { k:'鋭', level:'N2', meanings:['agudo / afilado'], on:['エイ'], kun:['するど'],
    words:[{w:'鋭い',f:'するどい',m:'agudo / afilado',l:'N2'},{w:'鋭利',f:'えいり',m:'agudo / perspicaz',l:'N2'},{w:'鋭角',f:'えいかく',m:'ángulo agudo',l:'N2'}]},
  { k:'録', level:'N2', meanings:['registrar / grabar'], on:['ロク'], kun:[],
    words:[{w:'記録',f:'きろく',m:'registro / récord',l:'N3'},{w:'登録',f:'とうろく',m:'registro / inscripción',l:'N3'},{w:'録音',f:'ろくおん',m:'grabación de sonido',l:'N2'}]},
  { k:'門', level:'N2', meanings:['puerta / entrada'], on:['モン'], kun:['かど'],
    words:[{w:'門',f:'もん',m:'puerta',l:'N4'},{w:'専門',f:'せんもん',m:'especialidad',l:'N3'},{w:'正門',f:'せいもん',m:'puerta principal',l:'N2'}]},
  { k:'防', level:'N2', meanings:['defender / prevenir'], on:['ボウ'], kun:['ふせ'],
    words:[{w:'防ぐ',f:'ふせぐ',m:'defender / prevenir',l:'N3'},{w:'予防',f:'よぼう',m:'prevención',l:'N2'},{w:'消防',f:'しょうぼう',m:'bomberos',l:'N2'}]},
  { k:'陸', level:'N2', meanings:['tierra firme'], on:['リク'], kun:[],
    words:[{w:'陸',f:'りく',m:'tierra firme',l:'N3'},{w:'陸地',f:'りくち',m:'tierra / continente',l:'N2'},{w:'陸上',f:'りくじょう',m:'terrestre / atletismo',l:'N2'}]},
  { k:'隅', level:'N2', meanings:['rincón / esquina'], on:['グウ'], kun:['すみ'],
    words:[{w:'隅',f:'すみ',m:'rincón / esquina',l:'N3'},{w:'隅々',f:'すみずみ',m:'todos los rincones',l:'N2'},{w:'片隅',f:'かたすみ',m:'un rincón',l:'N2'}]},
  { k:'階', level:'N2', meanings:['piso / escalera'], on:['カイ'], kun:[],
    words:[{w:'一階',f:'いっかい',m:'primer piso',l:'N5'},{w:'階段',f:'かいだん',m:'escalera',l:'N4'},{w:'階級',f:'かいきゅう',m:'rango / nivel',l:'N2'}]},
  { k:'隻', level:'N2', meanings:['contador de embarcaciones'], on:['セキ'], kun:[],
    words:[{w:'一隻',f:'いっせき',m:'una embarcación',l:'N2'},{w:'二隻',f:'にせき',m:'dos embarcaciones',l:'N2'},{w:'隻手',f:'せきしゅ',m:'una mano',l:'N2'}]},
  { k:'雇', level:'N2', meanings:['emplear / contratar'], on:['コ'], kun:['やと'],
    words:[{w:'雇用',f:'こよう',m:'empleo',l:'N2'},{w:'雇う',f:'やとう',m:'contratar',l:'N2'},{w:'解雇',f:'かいこ',m:'despido',l:'N2'}]},
  { k:'雲', level:'N2', meanings:['nube'], on:['ウン'], kun:['くも'],
    words:[{w:'雲',f:'くも',m:'nube',l:'N5'},{w:'雲行き',f:'くもゆき',m:'aspecto de las nubes / tendencia',l:'N2'},{w:'積乱雲',f:'せきらんうん',m:'cumulonimbo',l:'N2'}]},
  { k:'零', level:'N2', meanings:['cero / verter'], on:['レイ'], kun:['こぼ'],
    words:[{w:'零',f:'れい',m:'cero',l:'N2'},{w:'零下',f:'れいか',m:'bajo cero',l:'N2'},{w:'零細',f:'れいさい',m:'muy pequeño / ínfimo',l:'N2'}]},
  { k:'震', level:'N2', meanings:['temblar / terremoto'], on:['シン'], kun:['ふる'],
    words:[{w:'地震',f:'じしん',m:'terremoto',l:'N4'},{w:'震える',f:'ふるえる',m:'temblar',l:'N3'},{w:'震度',f:'しんど',m:'escala sísmica',l:'N2'}]},
  { k:'革', level:'N2', meanings:['cuero / reforma'], on:['カク'], kun:['かわ'],
    words:[{w:'革命',f:'かくめい',m:'revolución',l:'N2'},{w:'皮革',f:'ひかく',m:'cuero / piel',l:'N2'},{w:'改革',f:'かいかく',m:'reforma',l:'N2'}]},
  { k:'順', level:'N2', meanings:['orden / turno'], on:['ジュン'], kun:[],
    words:[{w:'順番',f:'じゅんばん',m:'turno / orden',l:'N3'},{w:'順序',f:'じゅんじょ',m:'orden / secuencia',l:'N2'},{w:'手順',f:'てじゅん',m:'procedimiento / paso',l:'N2'}]},
  { k:'預', level:'N2', meanings:['depositar / encomendar'], on:['ヨ'], kun:['あず'],
    words:[{w:'預ける',f:'あずける',m:'depositar / dejar a cargo',l:'N3'},{w:'預金',f:'よきん',m:'depósito bancario',l:'N2'},{w:'貯預金',f:'ちょよきん',m:'ahorros y depósitos',l:'N2'}]},
  { k:'領', level:'N2', meanings:['territorio / dominio'], on:['リョウ'], kun:[],
    words:[{w:'領土',f:'りょうど',m:'territorio',l:'N2'},{w:'大統領',f:'だいとうりょう',m:'presidente de la república',l:'N2'},{w:'領域',f:'りょういき',m:'campo / área',l:'N2'}]},
  { k:'額', level:'N2', meanings:['frente / importe'], on:['ガク'], kun:['ひたい'],
    words:[{w:'金額',f:'きんがく',m:'importe monetario',l:'N4'},{w:'額',f:'がく',m:'importe / cantidad',l:'N2'},{w:'額縁',f:'がくぶち',m:'marco de cuadro',l:'N2'}]},
  { k:'香', level:'N2', meanings:['fragancia / aroma'], on:['コウ'], kun:['かお'],
    words:[{w:'香り',f:'かおり',m:'fragancia',l:'N3'},{w:'香辛料',f:'こうしんりょう',m:'especias',l:'N2'},{w:'香港',f:'ほんこん',m:'Hong Kong',l:'N2'}]},
  { k:'駐', level:'N2', meanings:['estacionarse'], on:['チュウ'], kun:[],
    words:[{w:'駐車場',f:'ちゅうしゃじょう',m:'aparcamiento',l:'N4'},{w:'駐車',f:'ちゅうしゃ',m:'estacionamiento',l:'N3'},{w:'駐在',f:'ちゅうざい',m:'residencia / destacamento',l:'N2'}]},
  { k:'骨', level:'N2', meanings:['hueso'], on:['コツ'], kun:['ほね'],
    words:[{w:'骨',f:'ほね',m:'hueso',l:'N3'},{w:'骨折',f:'こっせつ',m:'fractura ósea',l:'N2'},{w:'骨格',f:'こっかく',m:'esqueleto / estructura',l:'N2'}]},
  { k:'麦', level:'N2', meanings:['trigo / cebada'], on:['バク'], kun:['むぎ'],
    words:[{w:'麦',f:'むぎ',m:'trigo / cebada',l:'N4'},{w:'麦茶',f:'むぎちゃ',m:'té de cebada',l:'N3'},{w:'小麦',f:'こむぎ',m:'trigo',l:'N3'}]},
  { k:'黄', level:'N2', meanings:['amarillo'], on:['オウ'], kun:['き'],
    words:[{w:'黄色',f:'きいろ',m:'amarillo',l:'N5'},{w:'黄金',f:'こがね',m:'oro',l:'N2'},{w:'黄身',f:'きみ',m:'yema de huevo',l:'N2'}]},
  { k:'鼻', level:'N2', meanings:['nariz'], on:['ビ'], kun:['はな'],
    words:[{w:'鼻',f:'はな',m:'nariz',l:'N5'},{w:'鼻水',f:'はなみず',m:'mocos',l:'N3'},{w:'鼻声',f:'はなごえ',m:'voz gangosa / nasal',l:'N3'}]},
  { k:'齢', level:'N2', meanings:['edad'], on:['レイ'], kun:[],
    words:[{w:'年齢',f:'ねんれい',m:'edad',l:'N4'},{w:'高齢',f:'こうれい',m:'edad avanzada',l:'N3'},{w:'老齢',f:'ろうれい',m:'vejez',l:'N2'}]},

]
