import type { Kanji } from './types'

// N5: 103 kanji

export const kanjiN5: Kanji[] = [
  { rank:1, k:'日', level:'N5', meanings:['sol','día'], on:['ニチ','ジツ'], kun:['ひ','か'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'今日',f:'きょう',m:'hoy',l:'N5'},{w:'毎日',f:'まいにち',m:'cada día',l:'N5'},{w:'日曜日',f:'にちようび',m:'domingo',l:'N5'},]},
  { rank:2, k:'一', level:'N5', meanings:['uno'], on:['イチ','イツ'], kun:['ひと'],
    words:[{w:'一人',f:'ひとり',m:'una persona',l:'N5'},{w:'一つ',f:'ひとつ',m:'una cosa',l:'N5'},{w:'一月',f:'いちがつ',m:'enero',l:'N5'},{w:'一番',f:'いちばん',m:'el más / número uno',l:'N5'},{w:'一度',f:'いちど',m:'una vez',l:'N5'},{w:'一緒に',f:'いっしょに',m:'juntos',l:'N5'},]},
  { rank:3, k:'国', level:'N5', meanings:['país','nación'], on:['コク'], kun:['くに'],
    words:[{w:'外国',f:'がいこく',m:'extranjero (país)',l:'N5'},{w:'国語',f:'こくご',m:'lengua nacional',l:'N5'},{w:'中国',f:'ちゅうごく',m:'China',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},]},
  { rank:4, k:'会', level:'N5', meanings:['reunión','encontrar'], on:['カイ','エ'], kun:['あ.う'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},{w:'会話',f:'かいわ',m:'conversación',l:'N4'},]},
  { rank:5, k:'人', level:'N5', meanings:['persona'], on:['ジン','ニン'], kun:['ひと'],
    words:[{w:'人々',f:'ひとびと',m:'personas',l:'N5'},{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'外国人',f:'がいこくじん',m:'extranjero (persona)',l:'N5'},{w:'一人',f:'ひとり',m:'una persona / solo',l:'N5'},]},
  { rank:6, k:'年', level:'N5', meanings:['año'], on:['ネン'], kun:['とし'],
    words:[{w:'今年',f:'ことし',m:'este año',l:'N5'},{w:'来年',f:'らいねん',m:'el año que viene',l:'N5'},{w:'毎年',f:'まいとし',m:'cada año',l:'N5'},{w:'去年',f:'きょねん',m:'el año pasado',l:'N5'},{w:'新年',f:'しんねん',m:'año nuevo',l:'N5'},]},
  { rank:7, k:'大', level:'N5', meanings:['grande'], on:['ダイ','タイ'], kun:['おお'],
    words:[{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'大切',f:'たいせつ',m:'importante',l:'N5'},{w:'大人',f:'おとな',m:'adulto',l:'N5'},{w:'大きい',f:'おおきい',m:'grande',l:'N5'},{w:'大事',f:'だいじ',m:'importante / asunto grave',l:'N5'},]},
  { rank:8, k:'十', level:'N5', meanings:['diez'], on:['ジュウ','ジッ'], kun:['とお','と'],
    words:[{w:'十日',f:'とおか',m:'diez días / día 10',l:'N5'},{w:'十分',f:'じゅうぶん',m:'suficiente',l:'N5'},{w:'二十歳',f:'はたち',m:'veinte años',l:'N5'},]},
  { rank:9, k:'二', level:'N5', meanings:['dos'], on:['ニ'], kun:['ふた'],
    words:[{w:'二人',f:'ふたり',m:'dos personas',l:'N5'},{w:'二つ',f:'ふたつ',m:'dos cosas',l:'N5'},{w:'二月',f:'にがつ',m:'febrero',l:'N5'},{w:'二十',f:'にじゅう',m:'veinte',l:'N5'}]},
  { rank:10, k:'本', level:'N5', meanings:['libro','origen'], on:['ホン'], kun:['もと'],
    words:[{w:'日本',f:'にほん',m:'Japón',l:'N5'},{w:'本当',f:'ほんとう',m:'verdad / de verdad',l:'N5'},{w:'本屋',f:'ほんや',m:'librería',l:'N5'},{w:'絵本',f:'えほん',m:'libro ilustrado',l:'N5'},]},
  { rank:11, k:'中', level:'N5', meanings:['dentro','interior','durante'], on:['チュウ'], kun:['なか'],
    words:[{w:'中学校',f:'ちゅうがっこう',m:'instituto',l:'N5'},{w:'中国',f:'ちゅうごく',m:'China',l:'N5'},]},
  { rank:12, k:'長', level:'N5', meanings:['largo','jefe'], on:['チョウ'], kun:['なが.い'],
    words:[{w:'長い',f:'ながい',m:'largo',l:'N5'},]},
  { rank:13, k:'出', level:'N5', meanings:['salir','sacar'], on:['シュツ','スイ'], kun:['で.る','だ.す'],
    words:[{w:'出口',f:'でぐち',m:'salida',l:'N5'},{w:'出発',f:'しゅっぱつ',m:'partida / salida',l:'N5'},]},
  { rank:14, k:'三', level:'N5', meanings:['tres'], on:['サン'], kun:['み','みっ'],
    words:[{w:'三日',f:'みっか',m:'tres días / día 3',l:'N5'},{w:'三つ',f:'みっつ',m:'tres cosas',l:'N5'},{w:'三月',f:'さんがつ',m:'marzo',l:'N5'},{w:'三角',f:'さんかく',m:'triángulo',l:'N5'}]},
  { rank:16, k:'時', level:'N5', meanings:['tiempo','hora'], on:['ジ'], kun:['とき'],
    words:[{w:'時間',f:'じかん',m:'tiempo / hora',l:'N5'},{w:'何時',f:'なんじ',m:'qué hora',l:'N5'},{w:'時々',f:'ときどき',m:'a veces',l:'N5'},]},
  { rank:20, k:'行', level:'N5', meanings:['ir'], on:['コウ','ギョウ'], kun:['い.く','おこな.う'],
    words:[{w:'旅行',f:'りょこう',m:'viaje',l:'N5'},{w:'銀行',f:'ぎんこう',m:'banco',l:'N5'},]},
  { rank:21, k:'社', level:'N5', meanings:['empresa','sociedad','santuario'], on:['シャ'], kun:['やしろ'],
    words:[{w:'会社',f:'かいしゃ',m:'empresa',l:'N5'},]},
  { rank:22, k:'見', level:'N5', meanings:['ver','mirar', 'mostrar'], on:['ケン'], kun:['み.る','み.える','み.せる'],
    words:[{w:'花見',f:'はなみ',m:'contemplación de cerezos',l:'N5'},]},
  { rank:23, k:'月', level:'N5', meanings:['luna','mes'], on:['ゲツ','ガツ'], kun:['つき'],
    words:[{w:'月曜日',f:'げつようび',m:'lunes',l:'N5'},{w:'今月',f:'こんげつ',m:'este mes',l:'N5'},{w:'来月',f:'らいげつ',m:'el mes que viene',l:'N5'},{w:'一月',f:'いちがつ',m:'enero',l:'N5'},]},
  { rank:24, k:'分', level:'N5', meanings:['minuto','entender','parte'], on:['フン','ブン'], kun:['わか.る'],
    words:[{w:'半分',f:'はんぶん',m:'la mitad',l:'N5'},{w:'自分',f:'じぶん',m:'uno mismo',l:'N5'},{w:'十分',f:'じゅっぷん',m:'diez minutos',l:'N5'},]},
  { rank:26, k:'後', level:'N5', meanings:['después','detrás'], on:['ゴ','コウ'], kun:['あと','うし.ろ'],
    words:[{w:'午後',f:'ごご',m:'tarde (PM)',l:'N5'},{w:'後で',f:'あとで',m:'después',l:'N5'},]},
  { rank:27, k:'前', level:'N5', meanings:['delante','antes'], on:['ゼン'], kun:['まえ'],
    words:[{w:'名前',f:'なまえ',m:'nombre',l:'N5'},{w:'午前',f:'ごぜん',m:'de la mañana (AM)',l:'N5'},{w:'駅前',f:'えきまえ',m:'frente a la estación',l:'N5'},]},
  { rank:29, k:'生', level:'N5', meanings:['vida','nacer'], on:['セイ','ショウ'], kun:['い.きる','う.まれる','なま'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'学生',f:'がくせい',m:'estudiante',l:'N5'},{w:'人生',f:'じんせい',m:'vida (humana)',l:'N4'},]},
  { rank:31, k:'五', level:'N5', meanings:['cinco'], on:['ゴ'], kun:['いつ'],
    words:[{w:'五日',f:'いつか',m:'cinco días / día 5',l:'N5'},{w:'五つ',f:'いつつ',m:'cinco cosas',l:'N5'},{w:'五月',f:'ごがつ',m:'mayo',l:'N5'},{w:'五分',f:'ごふん',m:'cinco minutos',l:'N5'},]},
  { rank:33, k:'間', level:'N5', meanings:['intervalo','entre'], on:['カン','ケン'], kun:['あいだ','ま'],
    words:[{w:'時間',f:'じかん',m:'tiempo / hora',l:'N5'},]},
  { rank:35, k:'上', level:'N5', meanings:['arriba','encima'], on:['ジョウ','ショウ'], kun:['うえ','あ.がる','のぼ.る'],
    words:[{w:'上手',f:'じょうず',m:'hábil',l:'N5'},]},
  { rank:37, k:'東', level:'N5', meanings:['este'], on:['トウ'], kun:['ひがし'],
    words:[{w:'東京',f:'とうきょう',m:'Tokio',l:'N5'},{w:'東口',f:'ひがしぐち',m:'salida este',l:'N5'},]},
  { rank:47, k:'四', level:'N5', meanings:['cuatro'], on:['シ'], kun:['よ','よっ'],
    words:[{w:'四日',f:'よっか',m:'cuatro días / día 4',l:'N5'},{w:'四つ',f:'よっつ',m:'cuatro cosas',l:'N5'},{w:'四月',f:'しがつ',m:'abril',l:'N5'},]},
  { rank:49, k:'今', level:'N5', meanings:['ahora'], on:['コン','キン'], kun:['いま'],
    words:[{w:'今日',f:'きょう',m:'hoy',l:'N5'},{w:'今年',f:'ことし',m:'este año',l:'N5'},{w:'今週',f:'こんしゅう',m:'esta semana',l:'N5'},{w:'今月',f:'こんげつ',m:'este mes',l:'N5'},{w:'今夜',f:'こんや',m:'esta noche',l:'N5'},]},
  { rank:51, k:'新', level:'N5', meanings:['nuevo'], on:['シン'], kun:['あたら.しい','にい'],
    words:[{w:'新しい',f:'あたらしい',m:'nuevo',l:'N5'},{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'},{w:'新年',f:'しんねん',m:'año nuevo',l:'N5'},]},
  { rank:53, k:'金', level:'N5', meanings:['oro','dinero'], on:['キン','コン'], kun:['かね'],
    words:[{w:'金曜日',f:'きんようび',m:'viernes',l:'N5'},{w:'お金',f:'おかね',m:'dinero',l:'N5'},]},
  { rank:55, k:'九', level:'N5', meanings:['nueve'], on:['キュウ','ク'], kun:['ここの'],
    words:[{w:'九日',f:'ここのか',m:'nueve días / día 9',l:'N5'},{w:'九つ',f:'ここのつ',m:'nueve cosas',l:'N5'},{w:'九月',f:'くがつ',m:'septiembre',l:'N5'},{w:'九時',f:'くじ',m:'las nueve',l:'N5'},]},
  { rank:56, k:'入', level:'N5', meanings:['entrar','meter'], on:['ニュウ'], kun:['はい.る','い.れる'],
    words:[{w:'入口',f:'いりぐち',m:'entrada',l:'N5'},{w:'入学',f:'にゅうがく',m:'ingreso a la escuela',l:'N4'},]},
  { rank:58, k:'立', level:'N5', meanings:['ponerse de pie','levantarse'], on:['リツ','リュウ'], kun:['た.つ'],
    words:[{w:'国立',f:'こくりつ',m:'nacional / estatal',l:'N4'},{w:'私立',f:'しりつ',m:'privado',l:'N4'},]},
  { rank:60, k:'手', level:'N5', meanings:['mano'], on:['シュ'], kun:['て'],
    words:[{w:'手紙',f:'てがみ',m:'carta',l:'N5'},{w:'上手',f:'じょうず',m:'hábil',l:'N5'},{w:'下手',f:'へた',m:'torpe',l:'N5'},]},
  { rank:63, k:'学', level:'N5', meanings:['estudio','aprendizaje'], on:['ガク'], kun:['まな.ぶ'],
    words:[{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'大学',f:'だいがく',m:'universidad',l:'N5'},{w:'学生',f:'がくせい',m:'estudiante',l:'N5'},{w:'小学校',f:'しょうがっこう',m:'escuela primaria',l:'N5'},]},
  { rank:65, k:'高', level:'N5', meanings:['alto','caro'], on:['コウ'], kun:['たか.い'],
    words:[{w:'高い',f:'たかい',m:'alto / caro',l:'N5'},{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},{w:'高校生',f:'こうこうせい',m:'estudiante de bachillerato',l:'N5'},]},
  { rank:69, k:'円', level:'N5', meanings:['yen','círculo'], on:['エン'], kun:['まる'],
    words:[{w:'百円',f:'ひゃくえん',m:'100 yenes',l:'N5'},{w:'千円',f:'せんえん',m:'1000 yenes',l:'N5'},]},
  { rank:72, k:'子', level:'N5', meanings:['niño','hijo'], on:['シ','ス'], kun:['こ'],
    words:[{w:'子供',f:'こども',m:'niño',l:'N5'},]},
  { rank:76, k:'目', level:'N5', meanings:['ojo'], on:['モク','ボク'], kun:['め'],
    words:[]},
  { rank:81, k:'外', level:'N5', meanings:['exterior','fuera'], on:['ガイ','ゲ'], kun:['そと','ほか'],
    words:[{w:'外国',f:'がいこく',m:'extranjero (país)',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},]},
  { rank:83, k:'言', level:'N5', meanings:['decir','palabra'], on:['ゲン','ゴン'], kun:['い.う','こと'],
    words:[{w:'言葉',f:'ことば',m:'palabra / idioma',l:'N5'},]},
  { rank:92, k:'八', level:'N5', meanings:['ocho'], on:['ハチ'], kun:['や','やっ'],
    words:[{w:'八日',f:'ようか',m:'ocho días / día 8',l:'N5'},{w:'八つ',f:'やっつ',m:'ocho cosas',l:'N5'},{w:'八月',f:'はちがつ',m:'agosto',l:'N5'},{w:'八時',f:'はちじ',m:'las ocho',l:'N5'},]},
  { rank:93, k:'六', level:'N5', meanings:['seis'], on:['ロク'], kun:['む','むっ'],
    words:[{w:'六日',f:'むいか',m:'seis días / día 6',l:'N5'},{w:'六つ',f:'むっつ',m:'seis cosas',l:'N5'},{w:'六月',f:'ろくがつ',m:'junio',l:'N5'},{w:'六時',f:'ろくじ',m:'las seis',l:'N5'},]},
  { rank:97, k:'下', level:'N5', meanings:['abajo','debajo'], on:['カ','ゲ'], kun:['した','さ.がる','くだ.る'],
    words:[{w:'下手',f:'へた',m:'torpe',l:'N5'},]},
  { rank:102, k:'来', level:'N5', meanings:['venir'], on:['ライ'], kun:['く.る','き','こ'],
    words:[{w:'来年',f:'らいねん',m:'el año que viene',l:'N5'},{w:'来週',f:'らいしゅう',m:'la semana próxima',l:'N5'},{w:'来月',f:'らいげつ',m:'el mes que viene',l:'N5'},]},
  { rank:113, k:'気', level:'N5', meanings:['espíritu','aire','ánimo'], on:['キ','ケ'], kun:[],
    words:[{w:'元気',f:'げんき',m:'saludable / animado',l:'N5'},{w:'天気',f:'てんき',m:'tiempo (meteorológico)',l:'N5'},{w:'気持ち',f:'きもち',m:'sentimiento',l:'N5'},{w:'電気',f:'でんき',m:'electricidad / luz',l:'N5'},{w:'空気',f:'くうき',m:'aire',l:'N5'},]},
  { rank:114, k:'小', level:'N5', meanings:['pequeño'], on:['ショウ'], kun:['ちい.さい','こ'],
    words:[{w:'小学校',f:'しょうがっこう',m:'escuela primaria',l:'N5'},{w:'小さい',f:'ちいさい',m:'pequeño',l:'N5'},{w:'小学生',f:'しょうがくせい',m:'alumno de primaria',l:'N5'},]},
  { rank:115, k:'七', level:'N5', meanings:['siete'], on:['シチ'], kun:['なな'],
    words:[{w:'七日',f:'なのか',m:'siete días / día 7',l:'N5'},{w:'七つ',f:'ななつ',m:'siete cosas',l:'N5'},{w:'七月',f:'しちがつ',m:'julio',l:'N5'},{w:'七時',f:'しちじ',m:'las siete',l:'N5'},]},
  { rank:131, k:'山', level:'N5', meanings:['montaña'], on:['サン'], kun:['やま'],
    words:[{w:'富士山',f:'ふじさん',m:'monte Fuji',l:'N5'},]},
  { rank:134, k:'話', level:'N5', meanings:['hablar','historia'], on:['ワ'], kun:['はな.す','はなし'],
    words:[{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'会話',f:'かいわ',m:'conversación',l:'N4'},]},
  { rank:139, k:'多', level:'N5', meanings:['mucho','abundante'], on:['タ'], kun:['おお.い'],
    words:[{w:'多い',f:'おおい',m:'mucho / muchos',l:'N5'},{w:'多分',f:'たぶん',m:'probablemente',l:'N5'},]},
  { rank:144, k:'安', level:'N5', meanings:['barato','seguro'], on:['アン'], kun:['やす.い'],
    words:[{w:'安い',f:'やすい',m:'barato',l:'N5'},]},
  { rank:151, k:'女', level:'N5', meanings:['mujer','hembra'], on:['ジョ','ニョ'], kun:['おんな'],
    words:[{w:'女の人',f:'おんなのひと',m:'mujer',l:'N5'},]},
  { rank:153, k:'北', level:'N5', meanings:['norte'], on:['ホク'], kun:['きた'],
    words:[{w:'北口',f:'きたぐち',m:'salida norte',l:'N5'},]},
  { rank:154, k:'午', level:'N5', meanings:['mediodía'], on:['ゴ'], kun:[],
    words:[{w:'午前',f:'ごぜん',m:'de la mañana (AM)',l:'N5'},{w:'午後',f:'ごご',m:'de la tarde (PM)',l:'N5'},{w:'午前中',f:'ごぜんちゅう',m:'durante la mañana',l:'N5'},]},
  { rank:163, k:'百', level:'N5', meanings:['cien'], on:['ヒャク'], kun:[],
    words:[{w:'百円',f:'ひゃくえん',m:'100 yenes',l:'N5'},{w:'百万',f:'ひゃくまん',m:'un millón',l:'N5'},{w:'三百',f:'さんびゃく',m:'trescientos',l:'N5'},]},
  { rank:169, k:'書', level:'N5', meanings:['escribir'], on:['ショ'], kun:['か.く'],
    words:[{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'辞書',f:'じしょ',m:'diccionario',l:'N5'},{w:'書店',f:'しょてん',m:'librería (formal)',l:'N5'},]},
  { rank:173, k:'先', level:'N5', meanings:['antes','adelante','punta'], on:['セン'], kun:['さき'],
    words:[{w:'先生',f:'せんせい',m:'profesor',l:'N5'},{w:'先週',f:'せんしゅう',m:'la semana pasada',l:'N5'},{w:'先月',f:'せんげつ',m:'el mes pasado',l:'N5'},]},
  { rank:177, k:'名', level:'N5', meanings:['nombre','famoso'], on:['メイ','ミョウ'], kun:['な'],
    words:[{w:'名前',f:'なまえ',m:'nombre',l:'N5'},{w:'有名',f:'ゆうめい',m:'famoso',l:'N5'},]},
  { rank:181, k:'川', level:'N5', meanings:['río'], on:['セン'], kun:['かわ'],
    words:[]},
  { rank:195, k:'千', level:'N5', meanings:['mil'], on:['セン'], kun:['ち'],
    words:[{w:'千円',f:'せんえん',m:'1000 yenes',l:'N5'},{w:'三千',f:'さんぜん',m:'tres mil',l:'N5'},{w:'千葉',f:'ちば',m:'Chiba',l:'N5'},]},
  { rank:207, k:'道', level:'N5', meanings:['camino','vía'], on:['ドウ','トウ'], kun:['みち'],
    words:[]},
  { rank:223, k:'水', level:'N5', meanings:['agua'], on:['スイ'], kun:['みず'],
    words:[{w:'水曜日',f:'すいようび',m:'miércoles',l:'N5'},{w:'お水',f:'おみず',m:'agua (cortés)',l:'N5'},]},
  { rank:224, k:'半', level:'N5', meanings:['mitad','medio'], on:['ハン'], kun:['なかば'],
    words:[{w:'半分',f:'はんぶん',m:'la mitad',l:'N5'},{w:'一時半',f:'いちじはん',m:'la una y media',l:'N5'},]},
  { rank:240, k:'男', level:'N5', meanings:['hombre','varón'], on:['ダン','ナン'], kun:['おとこ'],
    words:[{w:'男の人',f:'おとこのひと',m:'hombre',l:'N5'},]},
  { rank:259, k:'西', level:'N5', meanings:['oeste'], on:['セイ','サイ'], kun:['にし'],
    words:[{w:'西口',f:'にしぐち',m:'salida oeste',l:'N5'},]},
  { rank:268, k:'電', level:'N5', meanings:['electricidad'], on:['デン'], kun:[],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'電話',f:'でんわ',m:'teléfono',l:'N5'},{w:'電気',f:'でんき',m:'electricidad / luz',l:'N5'},]},
  { rank:284, k:'口', level:'N5', meanings:['boca','entrada'], on:['コウ','ク'], kun:['くち'],
    words:[{w:'入口',f:'いりぐち',m:'entrada',l:'N5'},{w:'出口',f:'でぐち',m:'salida',l:'N5'},]},
  { rank:287, k:'少', level:'N5', meanings:['poco','joven'], on:['ショウ'], kun:['すく.ない','すこ.し'],
    words:[{w:'少ない',f:'すくない',m:'poco',l:'N5'},{w:'少し',f:'すこし',m:'un poco',l:'N5'},]},
  { rank:294, k:'校', level:'N5', meanings:['escuela'], on:['コウ'], kun:[],
    words:[{w:'学校',f:'がっこう',m:'escuela',l:'N5'},{w:'高校',f:'こうこう',m:'bachillerato',l:'N5'},]},
  { rank:301, k:'語', level:'N5', meanings:['idioma','palabra'], on:['ゴ'], kun:['かた.る'],
    words:[{w:'日本語',f:'にほんご',m:'japonés',l:'N5'},{w:'英語',f:'えいご',m:'inglés',l:'N5'},{w:'外国語',f:'がいこくご',m:'idioma extranjero',l:'N5'},]},
  { rank:304, k:'空', level:'N5', meanings:['cielo','vacío'], on:['クウ'], kun:['そら','あ.く','から'],
    words:[{w:'空港',f:'くうこう',m:'aeropuerto',l:'N5'},{w:'空気',f:'くうき',m:'aire',l:'N5'},]},
  { rank:307, k:'土', level:'N5', meanings:['tierra'], on:['ド','ト'], kun:['つち'],
    words:[{w:'土曜日',f:'どようび',m:'sábado',l:'N5'},]},
  { rank:317, k:'木', level:'N5', meanings:['árbol','madera'], on:['モク','ボク'], kun:['き'],
    words:[{w:'木曜日',f:'もくようび',m:'jueves',l:'N5'},]},
  { rank:319, k:'聞', level:'N5', meanings:['escuchar','preguntar'], on:['ブン','モン'], kun:['き.く'],
    words:[{w:'新聞',f:'しんぶん',m:'periódico',l:'N5'},]},
  { rank:328, k:'食', level:'N5', meanings:['comer','comida'], on:['ショク'], kun:['た.べる','く.う'],
    words:[{w:'食事',f:'しょくじ',m:'comida / comer',l:'N5'},]},
  { rank:333, k:'車', level:'N5', meanings:['coche','vehículo'], on:['シャ'], kun:['くるま'],
    words:[{w:'電車',f:'でんしゃ',m:'tren eléctrico',l:'N5'},{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},]},
  { rank:340, k:'何', level:'N5', meanings:['qué','cuánto'], on:['カ'], kun:['なに','なん'],
    words:[{w:'何か',f:'なにか',m:'algo',l:'N5'},{w:'何時',f:'なんじ',m:'qué hora',l:'N5'},]},
  { rank:341, k:'南', level:'N5', meanings:['sur'], on:['ナン'], kun:['みなみ'],
    words:[{w:'南口',f:'みなみぐち',m:'salida sur',l:'N5'},]},
  { rank:343, k:'足', level:'N5', meanings:['pie','pierna','suficiente'], on:['ソク'], kun:['あし','た.りる'],
    words:[{w:'遠足',f:'えんそく',m:'excursión',l:'N4'},{w:'不足',f:'ふそく',m:'insuficiencia',l:'N4'},]},
  { rank:375, k:'万', level:'N5', meanings:['diez mil'], on:['マン','バン'], kun:[],
    words:[{w:'一万円',f:'いちまんえん',m:'10.000 yenes',l:'N5'},{w:'百万',f:'ひゃくまん',m:'un millón',l:'N5'},]},
  { rank:378, k:'店', level:'N5', meanings:['tienda'], on:['テン'], kun:['みせ'],
    words:[{w:'お店',f:'おみせ',m:'tienda',l:'N5'},{w:'書店',f:'しょてん',m:'librería',l:'N5'},]},
  { rank:436, k:'毎', level:'N5', meanings:['cada','todo'], on:['マイ'], kun:[],
    words:[{w:'毎日',f:'まいにち',m:'cada día',l:'N5'},{w:'毎週',f:'まいしゅう',m:'cada semana',l:'N5'},{w:'毎年',f:'まいとし',m:'cada año',l:'N5'},{w:'毎朝',f:'まいあさ',m:'cada mañana',l:'N5'}]},
  { rank:483, k:'白', level:'N5', meanings:['blanco'], on:['ハク','ビャク'], kun:['しろ'],
    words:[{w:'白い',f:'しろい',m:'blanco',l:'N5'},]},
  { rank:509, k:'古', level:'N5', meanings:['antiguo','viejo'], on:['コ'], kun:['ふる.い'],
    words:[{w:'古い',f:'ふるい',m:'viejo / antiguo',l:'N5'},]},
  { rank:512, k:'天', level:'N5', meanings:['cielo','paraíso'], on:['テン'], kun:['あめ','あま'],
    words:[{w:'天気',f:'てんき',m:'tiempo (meteorológico)',l:'N5'},]},
  { rank:520, k:'買', level:'N5', meanings:['comprar'], on:['バイ'], kun:['か.う'],
    words:[{w:'買い物',f:'かいもの',m:'compras',l:'N5'},]},
  { rank:540, k:'週', level:'N5', meanings:['semana'], on:['シュウ'], kun:[],
    words:[{w:'今週',f:'こんしゅう',m:'esta semana',l:'N5'},{w:'先週',f:'せんしゅう',m:'la semana pasada',l:'N5'},{w:'来週',f:'らいしゅう',m:'la semana próxima',l:'N5'},{w:'毎週',f:'まいしゅう',m:'cada semana',l:'N5'},]},
  { rank:570, k:'母', level:'N5', meanings:['madre'], on:['ボ'], kun:['はは'],
    words:[{w:'母',f:'はは',m:'madre',l:'N5'},{w:'お母さん',f:'おかあさん',m:'madre (respetuoso)',l:'N5'},]},
  { rank:574, k:'火', level:'N5', meanings:['fuego'], on:['カ'], kun:['ひ'],
    words:[{w:'火曜日',f:'かようび',m:'martes',l:'N5'},]},
  { rank:578, k:'花', level:'N5', meanings:['flor'], on:['カ'], kun:['はな'],
    words:[{w:'花',f:'はな',m:'flor',l:'N5'},{w:'花見',f:'はなみ',m:'contemplación de cerezos',l:'N5'},]},
  { rank:602, k:'右', level:'N5', meanings:['derecha'], on:['ウ','ユウ'], kun:['みぎ'],
    words:[{w:'右側',f:'みぎがわ',m:'lado derecho',l:'N5'},{w:'右手',f:'みぎて',m:'mano derecha',l:'N5'},]},
  { rank:618, k:'読', level:'N5', meanings:['leer'], on:['ドク','トク'], kun:['よ.む'],
    words:[{w:'音読み',f:'おんよみ',m:'lectura on',l:'N5'},]},
  { rank:622, k:'友', level:'N5', meanings:['amigo'], on:['ユウ'], kun:['とも'],
    words:[{w:'友達',f:'ともだち',m:'amigo',l:'N5'},]},
  { rank:630, k:'左', level:'N5', meanings:['izquierda'], on:['サ'], kun:['ひだり'],
    words:[{w:'左側',f:'ひだりがわ',m:'lado izquierdo',l:'N5'},{w:'左手',f:'ひだりて',m:'mano izquierda',l:'N5'},]},
  { rank:642, k:'休', level:'N5', meanings:['descansar','vacaciones'], on:['キュウ'], kun:['やす.む'],
    words:[{w:'夏休み',f:'なつやすみ',m:'vacaciones de verano',l:'N5'},]},
  { rank:646, k:'父', level:'N5', meanings:['padre'], on:['フ'], kun:['ちち'],
    words:[{w:'父',f:'ちち',m:'padre',l:'N5'},{w:'お父さん',f:'おとうさん',m:'padre (respetuoso)',l:'N5'},]},
  { rank:724, k:'駅', level:'N5', meanings:['estación'], on:['エキ'], kun:[],
    words:[{w:'駅',f:'えき',m:'estación',l:'N5'},{w:'駅前',f:'えきまえ',m:'frente a la estación',l:'N5'},]},
  { rank:950, k:'雨', level:'N5', meanings:['lluvia'], on:['ウ'], kun:['あめ','あま'],
    words:[{w:'雨',f:'あめ',m:'lluvia',l:'N5'},]},
  { rank:969, k:'飲', level:'N5', meanings:['beber'], on:['イン'], kun:['の.む'],
    words:[{w:'飲み物',f:'のみもの',m:'bebida',l:'N5'},]},
  { rank:1208, k:'魚', level:'N5', meanings:['pez','pescado'], on:['ギョ'], kun:['さかな','うお'],
    words:[{w:'魚',f:'さかな',m:'pescado / pez',l:'N5'},]},
  { rank:1328, k:'耳', level:'N5', meanings:['oído / oreja'], on:['ジ'], kun:['みみ'],
    words:[{w:'耳',f:'みみ',m:'oído / oreja',l:'N5'},]}
]
