import type { Kanji } from './types'

// N1: 49 kanji

export const kanjiN1: Kanji[] = [
  { rank:987, k:'巡', level:'N1', meanings:['recorrer / patrullar'], on:['ジュン'], kun:['めぐ'],
    words:[]},
  { rank:988, k:'義', level:'N1', meanings:['justicia / significado'], on:['ギ'], kun:[],
    words:[{w:'義務',f:'ぎむ',m:'obligación / deber',l:'N3'}]},
  { rank:989, k:'幹', level:'N1', meanings:['tronco / núcleo'], on:['カン'], kun:['みき'],
    words:[{w:'新幹線',f:'しんかんせん',m:'shinkansen',l:'N4'}]},
  { rank:990, k:'誠', level:'N1', meanings:['sinceridad / fidelidad'], on:['セイ'], kun:['まこと'],
    words:[]},
  { rank:991, k:'沿', level:'N1', meanings:['a lo largo de'], on:['エン'], kun:['そ'],
    words:[]},
  { rank:992, k:'隆', level:'N1', meanings:['prosperidad / elevado'], on:['リュウ'], kun:[],
    words:[]},
  { rank:993, k:'憲', level:'N1', meanings:['constitución / ley'], on:['ケン'], kun:[],
    words:[]},
  { rank:994, k:'縮', level:'N1', meanings:['encoger / reducir'], on:['シュク'], kun:['ちぢ'],
    words:[{w:'縮む',f:'ちぢむ',m:'encogerse',l:'N3'}]},
  { rank:995, k:'批', level:'N1', meanings:['criticar'], on:['ヒ'], kun:[],
    words:[{w:'批判',f:'ひはん',m:'crítica',l:'N3'}]},
  { rank:996, k:'距', level:'N1', meanings:['distancia'], on:['キョ'], kun:[],
    words:[]},
  { rank:997, k:'耐', level:'N1', meanings:['soportar / resistir'], on:['タイ'], kun:['た'],
    words:[{w:'耐える',f:'たえる',m:'soportar / aguantar',l:'N3'}]},
  { rank:998, k:'維', level:'N1', meanings:['mantener / fibra'], on:['イ'], kun:[],
    words:[{w:'維持',f:'いじ',m:'mantenimiento',l:'N4'}]},
  { rank:999, k:'促', level:'N1', meanings:['impulsar / instar'], on:['ソク'], kun:['うなが'],
    words:[]},
  { rank:1000, k:'殊', level:'N1', meanings:['especial / particularmente'], on:['シュ'], kun:['こと'],
    words:[]},
  { rank:1001, k:'既', level:'N1', meanings:['ya / anterior'], on:['キ'], kun:['すで'],
    words:[]},
  { rank:1002, k:'微', level:'N1', meanings:['sutil / leve'], on:['ビ'], kun:['かす'],
    words:[]},
  { rank:1003, k:'徹', level:'N1', meanings:['penetrar / exhaustivo'], on:['テツ'], kun:[],
    words:[]},
  { rank:1004, k:'矛', level:'N1', meanings:['lanza / contradicción'], on:['ム'], kun:['ほこ'],
    words:[]},
  { rank:1005, k:'慎', level:'N1', meanings:['prudente / cuidadoso'], on:['シン'], kun:['つつし'],
    words:[]},
  { rank:1006, k:'紛', level:'N1', meanings:['confusión / conflicto'], on:['フン'], kun:['まぎ'],
    words:[]},
  { rank:1007, k:'繁', level:'N1', meanings:['abundante / frecuente'], on:['ハン'], kun:['しげ'],
    words:[]},
  { rank:1008, k:'濁', level:'N1', meanings:['turbio / sucio'], on:['ダク'], kun:['にご'],
    words:[]},
  { rank:1009, k:'貢', level:'N1', meanings:['contribuir / tributo'], on:['コウ'], kun:['みつ'],
    words:[]},
  { rank:1010, k:'析', level:'N1', meanings:['analizar / dividir'], on:['セキ'], kun:[],
    words:[]},
  { rank:1011, k:'奮', level:'N1', meanings:['esforzarse / animarse'], on:['フン'], kun:['ふる'],
    words:[]},
  { rank:1012, k:'廃', level:'N1', meanings:['abandonar / abolir'], on:['ハイ'], kun:['すた'],
    words:[]},
  { rank:1013, k:'拒', level:'N1', meanings:['rechazar / negar'], on:['キョ'], kun:['こば'],
    words:[{w:'拒否',f:'きょひ',m:'rechazo / veto',l:'N3'}]},
  { rank:1014, k:'抽', level:'N1', meanings:['extraer / abstracto'], on:['チュウ'], kun:[],
    words:[]},
  { rank:1015, k:'搬', level:'N1', meanings:['transportar'], on:['ハン'], kun:[],
    words:[]},
  { rank:1016, k:'掲', level:'N1', meanings:['publicar / exhibir'], on:['ケイ'], kun:['かか'],
    words:[]},
  { rank:1017, k:'脅', level:'N1', meanings:['amenazar'], on:['キョウ'], kun:['おど'],
    words:[]},
  { rank:1018, k:'潔', level:'N1', meanings:['limpio / puro / honrado'], on:['ケツ'], kun:['いさぎよ'],
    words:[{w:'清潔',f:'せいけつ',m:'limpieza / higiene',l:'N3'}]},
  { rank:1019, k:'慮', level:'N1', meanings:['consideración / precaución'], on:['リョ'], kun:[],
    words:[{w:'遠慮',f:'えんりょ',m:'reserva / discreción',l:'N3'}]},
  { rank:1020, k:'催', level:'N1', meanings:['organizar / sentir impulso'], on:['サイ'], kun:['もよお'],
    words:[]},
  { rank:1021, k:'敵', level:'N1', meanings:['enemigo / rival'], on:['テキ'], kun:['かたき'],
    words:[]},
  { rank:1022, k:'慕', level:'N1', meanings:['anhelar / adorar'], on:['ボ'], kun:['した'],
    words:[]},
  { rank:1023, k:'隔', level:'N1', meanings:['separar / distancia'], on:['カク'], kun:['へだ'],
    words:[]},
  { rank:1024, k:'謙', level:'N1', meanings:['modestia / humildad'], on:['ケン'], kun:[],
    words:[]},
  { rank:1025, k:'秀', level:'N1', meanings:['excelente / destacado'], on:['シュウ'], kun:['ひい'],
    words:[]},
  { rank:1026, k:'懸', level:'N1', meanings:['colgar / apostar'], on:['ケン'], kun:['か'],
    words:[{w:'一生懸命',f:'いっしょうけんめい',m:'con todo empeño',l:'N3'}]},
  { rank:1027, k:'紡', level:'N1', meanings:['hilar / girar'], on:['ボウ'], kun:['つむ'],
    words:[]},
  { rank:1028, k:'虐', level:'N1', meanings:['crueldad / opresión'], on:['ギャク'], kun:['しいた'],
    words:[]},
  { rank:1029, k:'陵', level:'N1', meanings:['tumba imperial / colina'], on:['リョウ'], kun:['みささぎ'],
    words:[]},
  { rank:1030, k:'駆', level:'N1', meanings:['correr / impulsar'], on:['ク'], kun:['か'],
    words:[]},
  { rank:1031, k:'璧', level:'N1', meanings:['jade / perfección'], on:['ヘキ'], kun:[],
    words:[{w:'完璧',f:'かんぺき',m:'perfecto / impecable',l:'N3'}]},
  { rank:1032, k:'鑑', level:'N1', meanings:['espejo / modelo / apreciar'], on:['カン'], kun:['かがみ'],
    words:[]},

  { rank:1033, k:'魂', level:'N1', meanings:['alma','espíritu'], on:['コン'], kun:['たましい'],
    words:[]},
  { rank:1034, k:'誇', level:'N1', meanings:['orgullo','enorgullecerse'], on:['コ'], kun:['ほこ'],
    words:[]},
  { rank:1035, k:'憂', level:'N1', meanings:['pena','melancolía'], on:['ユウ'], kun:['うれ'],
    words:[]},
]
