import type { Kanji } from './types'

// N3: 355 kanji

export const kanjiN3: Kanji[] = [
  { rank:268, k:'達', level:'N3', meanings:['alcanzar','plural (personas)'], on:['タツ'], kun:['た'],
    words:[{w:'友達',f:'ともだち',m:'amigo',l:'N5'},{w:'達成',f:'たっせい',m:'logro',l:'N3'},{w:'上達',f:'じょうたつ',m:'progreso',l:'N3'}]},
  { rank:269, k:'配', level:'N3', meanings:['distribuir','preocupar'], on:['ハイ'], kun:['くば.る'],
    words:[{w:'心配',f:'しんぱい',m:'preocupación',l:'N4'},{w:'配達',f:'はいたつ',m:'entrega',l:'N3'},{w:'分配',f:'ぶんぱい',m:'distribución',l:'N3'}]},
  { rank:270, k:'様', level:'N3', meanings:['manera','señor/señora'], on:['ヨウ'], kun:['さま'],
    words:[{w:'様子',f:'ようす',m:'estado / apariencia',l:'N4'},{w:'同様',f:'どうよう',m:'de la misma manera',l:'N3'},{w:'お客様',f:'おきゃくさま',m:'cliente / huésped',l:'N3'}]},
  { rank:271, k:'表', level:'N3', meanings:['tabla','expresar','exterior'], on:['ヒョウ'], kun:['おもて','あらわ.す'],
    words:[{w:'発表',f:'はっぴょう',m:'presentación / anuncio',l:'N4'},{w:'表現',f:'ひょうげん',m:'expresión',l:'N3'},{w:'表面',f:'ひょうめん',m:'superficie',l:'N3'}]},
  { rank:272, k:'記', level:'N3', meanings:['registrar','anotar'], on:['キ'], kun:['しる.す'],
    words:[{w:'日記',f:'にっき',m:'diario',l:'N4'},{w:'記念',f:'きねん',m:'conmemoración',l:'N3'},{w:'記者',f:'きしゃ',m:'periodista',l:'N3'}]},
  { rank:273, k:'産', level:'N3', meanings:['producir','nacer'], on:['サン'], kun:['う.む'],
    words:[{w:'生産',f:'せいさん',m:'producción',l:'N3'},{w:'産業',f:'さんぎょう',m:'industria',l:'N3'},{w:'出産',f:'しゅっさん',m:'parto',l:'N3'}]},
  { rank:274, k:'全', level:'N3', meanings:['todo','completo'], on:['ゼン'], kun:['すべ.て','まった.く'],
    words:[{w:'全部',f:'ぜんぶ',m:'todo',l:'N4'},{w:'全員',f:'ぜんいん',m:'todos los miembros',l:'N3'},{w:'完全',f:'かんぜん',m:'perfecto / completo',l:'N3'}]},
  { rank:275, k:'的', level:'N3', meanings:['objetivo','(sufijo adjetival)'], on:['テキ'], kun:['まと'],
    words:[{w:'目的',f:'もくてき',m:'propósito',l:'N4'},{w:'具体的',f:'ぐたいてき',m:'concreto',l:'N3'},{w:'的確',f:'てきかく',m:'exacto / preciso',l:'N3'}]},
  { rank:276, k:'次', level:'N3', meanings:['siguiente','próximo'], on:['ジ','シ'], kun:['つぎ'],
    words:[{w:'次',f:'つぎ',m:'siguiente',l:'N4'},{w:'次第',f:'しだい',m:'según / dependiendo de',l:'N3'},{w:'順次',f:'じゅんじ',m:'sucesivamente',l:'N3'}]},
  { rank:277, k:'最', level:'N3', meanings:['más','el más'], on:['サイ'], kun:['もっと.も'],
    words:[{w:'最初',f:'さいしょ',m:'el primero',l:'N4'},{w:'最近',f:'さいきん',m:'recientemente',l:'N4'},{w:'最終',f:'さいしゅう',m:'último / final',l:'N4'}]},
  { rank:278, k:'続', level:'N3', meanings:['continuar'], on:['ゾク'], kun:['つづ.く','つづ.ける'],
    words:[{w:'続く',f:'つづく',m:'continuar',l:'N4'},{w:'継続',f:'けいぞく',m:'continuación',l:'N3'},{w:'手続き',f:'てつづき',m:'procedimiento',l:'N3'}]},
  { rank:279, k:'変', level:'N3', meanings:['cambiar','extraño'], on:['ヘン'], kun:['か.わる','かわ.る'],
    words:[{w:'大変',f:'たいへん',m:'difícil / muy',l:'N5'},{w:'変わる',f:'かわる',m:'cambiar',l:'N4'},{w:'変化',f:'へんか',m:'cambio',l:'N3'}]},
  { rank:280, k:'関', level:'N3', meanings:['relacionar','barrera'], on:['カン'], kun:['せき','かか.わる'],
    words:[{w:'関係',f:'かんけい',m:'relación',l:'N4'},{w:'玄関',f:'げんかん',m:'entrada de casa',l:'N4'},{w:'関心',f:'かんしん',m:'interés',l:'N4'}]},
  { rank:281, k:'現', level:'N3', meanings:['presente','aparecer'], on:['ゲン'], kun:['あらわ.れる'],
    words:[{w:'現在',f:'げんざい',m:'actualmente',l:'N4'},{w:'現実',f:'げんじつ',m:'realidad',l:'N3'},{w:'表現',f:'ひょうげん',m:'expresión',l:'N3'}]},
  { rank:282, k:'進', level:'N3', meanings:['avanzar','progresar'], on:['シン'], kun:['すす.む'],
    words:[{w:'進む',f:'すすむ',m:'avanzar',l:'N4'},{w:'進歩',f:'しんぽ',m:'progreso',l:'N4'},{w:'前進',f:'ぜんしん',m:'avance',l:'N3'}]},
  { rank:283, k:'得', level:'N3', meanings:['obtener','ganar'], on:['トク'], kun:['え.る','う.る'],
    words:[{w:'得る',f:'える',m:'obtener',l:'N4'},{w:'納得',f:'なっとく',m:'comprensión / convicción',l:'N3'},{w:'習得',f:'しゅうとく',m:'adquisición',l:'N3'}]},
  { rank:284, k:'失', level:'N3', meanings:['perder','fallar'], on:['シツ'], kun:['うしな.う'],
    words:[{w:'失礼',f:'しつれい',m:'descortesía',l:'N4'},{w:'失敗',f:'しっぱい',m:'fracaso',l:'N4'},{w:'消失',f:'しょうしつ',m:'desaparición',l:'N3'}]},
  { rank:285, k:'望', level:'N3', meanings:['desear','esperanza'], on:['ボウ','モウ'], kun:['のぞ.む'],
    words:[{w:'希望',f:'きぼう',m:'esperanza',l:'N4'},{w:'望む',f:'のぞむ',m:'desear',l:'N3'},{w:'展望',f:'てんぼう',m:'perspectiva',l:'N3'}]},
  { rank:286, k:'決', level:'N3', meanings:['decidir'], on:['ケツ'], kun:['き.める','き.まる'],
    words:[{w:'決める',f:'きめる',m:'decidir',l:'N4'},{w:'決定',f:'けってい',m:'decisión',l:'N3'},{w:'解決',f:'かいけつ',m:'solución',l:'N3'}]},
  { rank:287, k:'合', level:'N3', meanings:['combinar','concordar'], on:['ゴウ','ガッ'], kun:['あ.う'],
    words:[{w:'場合',f:'ばあい',m:'caso / situación',l:'N4'},{w:'合格',f:'ごうかく',m:'aprobado',l:'N3'},{w:'都合',f:'つごう',m:'conveniencia',l:'N3'}]},
  { rank:288, k:'調', level:'N3', meanings:['investigar','ajustar'], on:['チョウ'], kun:['しら.べる','ととの.える'],
    words:[{w:'調べる',f:'しらべる',m:'investigar',l:'N4'},{w:'調子',f:'ちょうし',m:'condición / ritmo',l:'N4'},{w:'調査',f:'ちょうさ',m:'investigación',l:'N3'}]},
  { rank:289, k:'確', level:'N3', meanings:['confirmar','seguro'], on:['カク'], kun:['たし.かめる'],
    words:[{w:'確かめる',f:'たしかめる',m:'confirmar',l:'N4'},{w:'正確',f:'せいかく',m:'exacto / preciso',l:'N4'},{w:'確認',f:'かくにん',m:'confirmación',l:'N3'}]},
  { rank:290, k:'能', level:'N3', meanings:['habilidad','capaz'], on:['ノウ'], kun:[],
    words:[{w:'可能',f:'かのう',m:'posible',l:'N3'},{w:'能力',f:'のうりょく',m:'capacidad',l:'N3'},{w:'機能',f:'きのう',m:'función',l:'N3'}]},
  { rank:291, k:'活', level:'N3', meanings:['vivir','activo'], on:['カツ'], kun:['い.きる'],
    words:[{w:'生活',f:'せいかつ',m:'vida cotidiana',l:'N4'},{w:'活動',f:'かつどう',m:'actividad',l:'N4'},{w:'活用',f:'かつよう',m:'uso activo',l:'N3'}]},
  { rank:292, k:'機', level:'N3', meanings:['máquina','oportunidad'], on:['キ'], kun:['はた'],
    words:[{w:'飛行機',f:'ひこうき',m:'avión',l:'N5'},{w:'機会',f:'きかい',m:'oportunidad',l:'N4'},{w:'機能',f:'きのう',m:'función',l:'N3'}]},
  { rank:293, k:'術', level:'N3', meanings:['arte','técnica'], on:['ジュツ'], kun:[],
    words:[{w:'手術',f:'しゅじゅつ',m:'cirugía',l:'N4'},{w:'芸術',f:'げいじゅつ',m:'arte',l:'N3'},{w:'技術',f:'ぎじゅつ',m:'tecnología / técnica',l:'N3'}]},
  { rank:294, k:'際', level:'N3', meanings:['cuando','ocasión'], on:['サイ'], kun:['きわ'],
    words:[{w:'国際',f:'こくさい',m:'internacional',l:'N4'},{w:'実際',f:'じっさい',m:'en realidad',l:'N3'},{w:'交際',f:'こうさい',m:'relación / trato',l:'N3'}]},
  { rank:295, k:'困', level:'N3', meanings:['estar en apuros'], on:['コン'], kun:['こま.る'],
    words:[{w:'困る',f:'こまる',m:'estar en apuros',l:'N4'},{w:'困難',f:'こんなん',m:'dificultad',l:'N3'},{w:'貧困',f:'ひんこん',m:'pobreza',l:'N3'}]},
  { rank:296, k:'整', level:'N3', meanings:['ordenar','arreglar'], on:['セイ'], kun:['ととの.える'],
    words:[{w:'整理',f:'せいり',m:'organización',l:'N3'},{w:'調整',f:'ちょうせい',m:'ajuste',l:'N3'},{w:'整備',f:'せいび',m:'mantenimiento',l:'N3'}]},
  { rank:297, k:'政', level:'N3', meanings:['gobierno','política'], on:['セイ','ショウ'], kun:['まつりごと'],
    words:[{w:'政治',f:'せいじ',m:'política',l:'N3'},{w:'政府',f:'せいふ',m:'gobierno',l:'N3'},{w:'行政',f:'ぎょうせい',m:'administración pública',l:'N3'}]},
  { rank:298, k:'議', level:'N3', meanings:['debatir','asamblea'], on:['ギ'], kun:[],
    words:[{w:'会議',f:'かいぎ',m:'reunión / conferencia',l:'N4'},{w:'議論',f:'ぎろん',m:'debate',l:'N3'},{w:'議員',f:'ぎいん',m:'parlamentario',l:'N3'}]},
  { rank:299, k:'民', level:'N3', meanings:['pueblo','ciudadano'], on:['ミン'], kun:['たみ'],
    words:[{w:'国民',f:'こくみん',m:'ciudadano',l:'N4'},{w:'民族',f:'みんぞく',m:'etnia',l:'N3'},{w:'市民',f:'しみん',m:'ciudadano (ciudad)',l:'N3'}]},
  { rank:300, k:'連', level:'N3', meanings:['unir','conectar','llevar'], on:['レン'], kun:['つら.なる','つ.れる'],
    words:[{w:'連絡',f:'れんらく',m:'contacto / comunicación',l:'N4'},{w:'連続',f:'れんぞく',m:'continuación / serie',l:'N3'},{w:'連れ',f:'つれ',m:'acompañante',l:'N3'}]},
  { rank:301, k:'対', level:'N3', meanings:['opuesto','contra'], on:['タイ','ツイ'], kun:[],
    words:[{w:'対話',f:'たいわ',m:'diálogo',l:'N3'},{w:'反対',f:'はんたい',m:'oposición',l:'N3'},{w:'対応',f:'たいおう',m:'respuesta / reacción',l:'N3'}]},
  { rank:302, k:'部', level:'N3', meanings:['sección','departamento','parte'], on:['ブ'], kun:[],
    words:[{w:'全部',f:'ぜんぶ',m:'todo',l:'N4'},{w:'部分',f:'ぶぶん',m:'parte',l:'N4'},{w:'部長',f:'ぶちょう',m:'jefe de departamento',l:'N3'}]},
  { rank:303, k:'市', level:'N3', meanings:['ciudad','mercado'], on:['シ'], kun:['いち'],
    words:[{w:'市民',f:'しみん',m:'ciudadano',l:'N3'},{w:'市場',f:'いちば',m:'mercado',l:'N3'},{w:'都市',f:'とし',m:'ciudad',l:'N3'}]},
  { rank:304, k:'内', level:'N3', meanings:['interior','dentro'], on:['ナイ','ダイ'], kun:['うち'],
    words:[{w:'案内',f:'あんない',m:'guía / información',l:'N4'},{w:'内容',f:'ないよう',m:'contenido',l:'N3'},{w:'国内',f:'こくない',m:'interior del país',l:'N3'}]},
  { rank:305, k:'相', level:'N3', meanings:['mutuo','ministro','aspecto'], on:['ソウ','ショウ'], kun:['あい'],
    words:[{w:'相談',f:'そうだん',m:'consulta / consejo',l:'N4'},{w:'相互',f:'そうご',m:'mutuo / recíproco',l:'N3'},{w:'相手',f:'あいて',m:'interlocutor / contrario',l:'N3'}]},
  { rank:306, k:'定', level:'N3', meanings:['determinar','fijar','establecer'], on:['テイ','ジョウ'], kun:['さだ.める'],
    words:[{w:'予定',f:'よてい',m:'plan / horario',l:'N4'},{w:'決定',f:'けってい',m:'decisión',l:'N3'},{w:'定期',f:'ていき',m:'periódico / abono',l:'N3'}]},
  { rank:307, k:'回', level:'N3', meanings:['vuelta','vez','girar'], on:['カイ','エ'], kun:['まわ.る'],
    words:[{w:'今回',f:'こんかい',m:'esta vez',l:'N4'},{w:'回答',f:'かいとう',m:'respuesta',l:'N4'},{w:'毎回',f:'まいかい',m:'cada vez',l:'N3'}]},
  { rank:308, k:'選', level:'N3', meanings:['elegir','seleccionar'], on:['セン'], kun:['えら.ぶ'],
    words:[{w:'選ぶ',f:'えらぶ',m:'elegir',l:'N4'},{w:'選手',f:'せんしゅ',m:'atleta / jugador',l:'N3'},{w:'選択',f:'せんたく',m:'selección',l:'N3'}]},
  { rank:309, k:'実', level:'N3', meanings:['realidad','fruto','verdad'], on:['ジツ'], kun:['み','みの.る'],
    words:[{w:'実は',f:'じつは',m:'en realidad',l:'N4'},{w:'実際',f:'じっさい',m:'en la práctica',l:'N3'},{w:'現実',f:'げんじつ',m:'realidad',l:'N3'}]},
  { rank:310, k:'戦', level:'N3', meanings:['guerra','batalla','luchar'], on:['セン'], kun:['いくさ','たたか.う'],
    words:[{w:'戦争',f:'せんそう',m:'guerra',l:'N3'},{w:'挑戦',f:'ちょうせん',m:'desafío',l:'N3'}]},
  { rank:311, k:'経', level:'N3', meanings:['pasar','transcurrir','longitud'], on:['ケイ','キョウ'], kun:['へ.る','た.つ'],
    words:[{w:'経験',f:'けいけん',m:'experiencia',l:'N4'},{w:'経済',f:'けいざい',m:'economía',l:'N3'},{w:'経営',f:'けいえい',m:'gestión / administración',l:'N3'}]},
  { rank:312, k:'化', level:'N3', meanings:['transformar','cambiar','química'], on:['カ','ケ'], kun:['ば','ふ'],
    words:[{w:'文化',f:'ぶんか',m:'cultura',l:'N4'},{w:'変化',f:'へんか',m:'cambio',l:'N3'},{w:'化学',f:'かがく',m:'química',l:'N3'}]},
  { rank:313, k:'当', level:'N3', meanings:['acertar','aplicar','este'], on:['トウ'], kun:['あ.たる'],
    words:[{w:'本当',f:'ほんとう',m:'verdad',l:'N5'},{w:'当然',f:'とうぜん',m:'por supuesto / natural',l:'N3'},{w:'担当',f:'たんとう',m:'encargado',l:'N3'}]},
  { rank:314, k:'約', level:'N3', meanings:['promesa','aproximadamente'], on:['ヤク'], kun:['つづ'],
    words:[{w:'約束',f:'やくそく',m:'promesa',l:'N4'},{w:'約',f:'やく',m:'aproximadamente',l:'N3'},{w:'条約',f:'じょうやく',m:'tratado',l:'N3'}]},
  { rank:315, k:'首', level:'N3', meanings:['cuello','cabeza','primero'], on:['シュ'], kun:['くび'],
    words:[{w:'首相',f:'しゅしょう',m:'primer ministro',l:'N3'},{w:'首都',f:'しゅと',m:'capital',l:'N3'},{w:'手首',f:'てくび',m:'muñeca',l:'N3'}]},
  { rank:316, k:'法', level:'N3', meanings:['ley','método','regla'], on:['ホウ','ホッ','ハッ'], kun:['のり'],
    words:[{w:'方法',f:'ほうほう',m:'método',l:'N4'},{w:'文法',f:'ぶんぽう',m:'gramática',l:'N4'},{w:'法律',f:'ほうりつ',m:'ley',l:'N3'}]},
  { rank:317, k:'性', level:'N3', meanings:['sexo','género','naturaleza'], on:['セイ','ショウ'], kun:[],
    words:[{w:'男性',f:'だんせい',m:'hombre / masculino',l:'N4'},{w:'性格',f:'せいかく',m:'personalidad / carácter',l:'N3'},{w:'可能性',f:'かのうせい',m:'posibilidad',l:'N3'}]},
  { rank:318, k:'要', level:'N3', meanings:['necesario','esencia','punto principal'], on:['ヨウ'], kun:['い','かなめ'],
    words:[{w:'必要',f:'ひつよう',m:'necesario',l:'N4'},{w:'重要',f:'じゅうよう',m:'importante',l:'N4'},{w:'要求',f:'ようきゅう',m:'demanda / petición',l:'N3'}]},
  { rank:319, k:'制', level:'N3', meanings:['sistema','controlar','regla'], on:['セイ'], kun:[],
    words:[{w:'制度',f:'せいど',m:'sistema',l:'N3'},{w:'制限',f:'せいげん',m:'limitación',l:'N3'},{w:'規制',f:'きせい',m:'regulación',l:'N3'}]},
  { rank:320, k:'治', level:'N3', meanings:['gobernar','curar','sanar'], on:['ジ','チ'], kun:['おさ.める','なお.る'],
    words:[{w:'治る',f:'なおる',m:'curarse / sanarse',l:'N4'},{w:'政治',f:'せいじ',m:'política',l:'N3'},{w:'治療',f:'ちりょう',m:'tratamiento médico',l:'N3'}]},
  { rank:321, k:'務', level:'N3', meanings:['tarea','deber','servir'], on:['ム'], kun:['つと.める'],
    words:[{w:'義務',f:'ぎむ',m:'obligación',l:'N3'},{w:'任務',f:'にんむ',m:'misión / deber',l:'N3'},{w:'勤務',f:'きんむ',m:'servicio / trabajo',l:'N3'}]},
  { rank:322, k:'成', level:'N3', meanings:['convertirse','lograr','alcanzar'], on:['セイ','ジョウ'], kun:['な.る'],
    words:[{w:'成長',f:'せいちょう',m:'crecimiento',l:'N4'},{w:'成功',f:'せいこう',m:'éxito',l:'N3'},{w:'達成',f:'たっせい',m:'logro',l:'N3'}]},
  { rank:323, k:'期', level:'N3', meanings:['período','temporada','plazo'], on:['キ','ゴ'], kun:[],
    words:[{w:'時期',f:'じき',m:'momento / período',l:'N4'},{w:'期間',f:'きかん',m:'período de tiempo',l:'N4'},{w:'期待',f:'きたい',m:'expectativa',l:'N4'}]},
  { rank:324, k:'取', level:'N3', meanings:['tomar','coger','obtener'], on:['シュ'], kun:['と.る'],
    words:[{w:'受け取る',f:'うけとる',m:'recibir',l:'N4'},{w:'取り組む',f:'とりくむ',m:'abordar / enfrentarse',l:'N3'},{w:'取引',f:'とりひき',m:'transacción',l:'N3'}]},
  { rank:325, k:'都', level:'N3', meanings:['metrópoli','capital','ciudad'], on:['ト','ツ'], kun:['みやこ'],
    words:[{w:'都市',f:'とし',m:'ciudad',l:'N3'},{w:'首都',f:'しゅと',m:'capital',l:'N3'},{w:'都合',f:'つごう',m:'conveniencia',l:'N3'}]},
  { rank:326, k:'和', level:'N3', meanings:['armonía','paz','estilo japonés'], on:['ワ','オ'], kun:['やわ.らぐ','なご.む'],
    words:[{w:'和食',f:'わしょく',m:'comida japonesa',l:'N4'},{w:'平和',f:'へいわ',m:'paz',l:'N3'},{w:'調和',f:'ちょうわ',m:'armonía',l:'N3'}]},
  { rank:327, k:'平', level:'N3', meanings:['plano','tranquilo','igual'], on:['ヘイ','ビョウ'], kun:['たい','ひら'],
    words:[{w:'平日',f:'へいじつ',m:'día laborable',l:'N4'},{w:'平和',f:'へいわ',m:'paz',l:'N3'},{w:'平均',f:'へいきん',m:'promedio',l:'N3'}]},
  { rank:328, k:'加', level:'N3', meanings:['añadir','sumar','incorporarse'], on:['カ'], kun:['くわ.える'],
    words:[{w:'参加',f:'さんか',m:'participación',l:'N4'},{w:'追加',f:'ついか',m:'adición',l:'N3'},{w:'加速',f:'かそく',m:'aceleración',l:'N3'}]},
  { rank:329, k:'受', level:'N3', meanings:['recibir','aceptar','sufrir'], on:['ジュ'], kun:['う.ける'],
    words:[{w:'受ける',f:'うける',m:'recibir',l:'N4'},{w:'受験',f:'じゅけん',m:'presentarse a examen',l:'N4'},{w:'受付',f:'うけつけ',m:'recepción',l:'N3'}]},
  { rank:330, k:'数', level:'N3', meanings:['número','contar'], on:['スウ','ス'], kun:['かず','かぞ.える'],
    words:[{w:'数学',f:'すうがく',m:'matemáticas',l:'N4'},{w:'数字',f:'すうじ',m:'dígito / cifra',l:'N4'},{w:'数える',f:'かぞえる',m:'contar',l:'N3'}]},
  { rank:331, k:'初', level:'N3', meanings:['primero','principio','primera vez'], on:['ショ'], kun:['はつ','はじ.めて','うい'],
    words:[{w:'初めて',f:'はじめて',m:'por primera vez',l:'N5'},{w:'最初',f:'さいしょ',m:'el primero / al principio',l:'N4'},{w:'初心者',f:'しょしんしゃ',m:'principiante',l:'N3'}]},
  { rank:332, k:'指', level:'N3', meanings:['dedo','señalar','indicar'], on:['シ'], kun:['ゆび','さ.す'],
    words:[{w:'指す',f:'さす',m:'señalar / indicar',l:'N3'},{w:'指示',f:'しじ',m:'instrucción',l:'N3'},{w:'指輪',f:'ゆびわ',m:'anillo',l:'N3'}]},
  { rank:333, k:'権', level:'N3', meanings:['derecho','autoridad','poder'], on:['ゴン','ケン'], kun:[],
    words:[{w:'人権',f:'じんけん',m:'derechos humanos',l:'N3'},{w:'権利',f:'けんり',m:'derecho',l:'N3'}]},
  { rank:334, k:'支', level:'N3', meanings:['apoyar','rama','sustentar'], on:['シ'], kun:['ささ.える'],
    words:[{w:'支える',f:'ささえる',m:'apoyar / sostener',l:'N3'},{w:'支持',f:'しじ',m:'apoyo',l:'N3'},{w:'支払い',f:'しはらい',m:'pago',l:'N3'}]},
  { rank:335, k:'点', level:'N3', meanings:['punto','marca','nota'], on:['テン'], kun:['つ','た'],
    words:[{w:'点数',f:'てんすう',m:'puntuación',l:'N3'},{w:'観点',f:'かんてん',m:'punto de vista',l:'N3'},{w:'欠点',f:'けってん',m:'defecto / punto débil',l:'N3'}]},
  { rank:336, k:'報', level:'N3', meanings:['informar','noticia','recompensar'], on:['ホウ'], kun:['むく.いる'],
    words:[{w:'情報',f:'じょうほう',m:'información',l:'N3'},{w:'報告',f:'ほうこく',m:'informe',l:'N3'},{w:'報道',f:'ほうどう',m:'noticias / cobertura',l:'N3'}]},
  { rank:337, k:'済', level:'N3', meanings:['concluir','saldar','economía'], on:['サイ'], kun:['す.む'],
    words:[{w:'済む',f:'すむ',m:'terminarse / resolverse',l:'N4'},{w:'経済',f:'けいざい',m:'economía',l:'N3'},{w:'返済',f:'へんさい',m:'reembolso',l:'N3'}]},
  { rank:338, k:'原', level:'N3', meanings:['campo','origen','llanura'], on:['ゲン'], kun:['はら'],
    words:[{w:'原因',f:'げんいん',m:'causa',l:'N3'},{w:'原則',f:'げんそく',m:'principio',l:'N3'},{w:'原料',f:'げんりょう',m:'materia prima',l:'N3'}]},
  { rank:339, k:'共', level:'N3', meanings:['juntos','en común'], on:['キョウ'], kun:['とも'],
    words:[{w:'共通',f:'きょうつう',m:'común / compartido',l:'N3'},{w:'共に',f:'ともに',m:'junto con',l:'N3'},{w:'共感',f:'きょうかん',m:'empatía',l:'N3'}]},
  { rank:340, k:'解', level:'N3', meanings:['resolver','entender','desatar'], on:['カイ','ゲ'], kun:['と.く'],
    words:[{w:'理解',f:'りかい',m:'comprensión',l:'N4'},{w:'解決',f:'かいけつ',m:'solución',l:'N3'},{w:'解説',f:'かいせつ',m:'explicación / comentario',l:'N3'}]},
  { rank:341, k:'交', level:'N3', meanings:['cruzar','intercambiar','mezclarse'], on:['コウ'], kun:['まじ.わる','か.わす'],
    words:[{w:'交通',f:'こうつう',m:'tráfico',l:'N4'},{w:'交換',f:'こうかん',m:'intercambio',l:'N3'},{w:'外交',f:'がいこう',m:'diplomacia',l:'N3'}]},
  { rank:342, k:'資', level:'N3', meanings:['activos','recursos','capital'], on:['シ'], kun:[],
    words:[{w:'資料',f:'しりょう',m:'material / recurso',l:'N3'},{w:'資源',f:'しげん',m:'recurso natural',l:'N3'},{w:'資格',f:'しかく',m:'calificación / credencial',l:'N3'}]},
  { rank:343, k:'予', level:'N3', meanings:['por anticipado','de antemano'], on:['ヨ','シャ'], kun:['あらかじ.め'],
    words:[{w:'予定',f:'よてい',m:'plan / horario',l:'N4'},{w:'予約',f:'よやく',m:'reserva',l:'N4'},{w:'予算',f:'よさん',m:'presupuesto',l:'N3'}]},
  { rank:344, k:'向', level:'N3', meanings:['orientarse hacia','dirección'], on:['コウ'], kun:['む.く','むか.う','むこ.う'],
    words:[{w:'向かう',f:'むかう',m:'dirigirse hacia',l:'N4'},{w:'方向',f:'ほうこう',m:'dirección',l:'N4'},{w:'傾向',f:'けいこう',m:'tendencia',l:'N3'}]},
  { rank:345, k:'勝', level:'N3', meanings:['victoria','ganar','superar'], on:['ショウ'], kun:['か.つ','まさ.る'],
    words:[{w:'勝つ',f:'かつ',m:'ganar',l:'N4'},{w:'優勝',f:'ゆうしょう',m:'campeonato',l:'N3'},{w:'勝負',f:'しょうぶ',m:'combate / competición',l:'N3'}]},
  { rank:346, k:'面', level:'N3', meanings:['cara','superficie','aspecto'], on:['メン'], kun:['おも','おもて','つら'],
    words:[{w:'面白い',f:'おもしろい',m:'interesante / divertido',l:'N5'},{w:'場面',f:'ばめん',m:'escena',l:'N3'},{w:'正面',f:'しょうめん',m:'frente / fachada',l:'N3'}]},
  { rank:347, k:'告', level:'N3', meanings:['anunciar','notificar','informar'], on:['コク'], kun:['つ.げる'],
    words:[{w:'広告',f:'こうこく',m:'publicidad',l:'N4'},{w:'報告',f:'ほうこく',m:'informe',l:'N3'},{w:'告白',f:'こくはく',m:'confesión',l:'N3'}]},
  { rank:348, k:'反', level:'N3', meanings:['oponer','anti-','rebelarse'], on:['ホン','ハン','タン'], kun:['そ.る'],
    words:[{w:'反対',f:'はんたい',m:'oposición',l:'N3'},{w:'反省',f:'はんせい',m:'reflexión / arrepentimiento',l:'N3'},{w:'反応',f:'はんのう',m:'reacción',l:'N3'}]},
  { rank:349, k:'判', level:'N3', meanings:['juzgar','sello','tamaño'], on:['ハン','バン'], kun:[],
    words:[{w:'判断',f:'はんだん',m:'juicio / decisión',l:'N3'},{w:'裁判',f:'さいばん',m:'juicio / tribunal',l:'N3'},{w:'批判',f:'ひはん',m:'crítica',l:'N3'}]},
  { rank:350, k:'認', level:'N3', meanings:['reconocer','admitir','aprobar'], on:['ニン'], kun:['みと.める'],
    words:[{w:'認める',f:'みとめる',m:'reconocer / admitir',l:'N4'},{w:'確認',f:'かくにん',m:'confirmación',l:'N3'},{w:'認識',f:'にんしき',m:'reconocimiento',l:'N3'}]},
  { rank:351, k:'参', level:'N3', meanings:['visitar (templo)','participar'], on:['サン'], kun:['まい.る'],
    words:[{w:'参加',f:'さんか',m:'participación',l:'N4'},{w:'参考',f:'さんこう',m:'referencia',l:'N4'},{w:'参拝',f:'さんぱい',m:'visita a un santuario',l:'N3'}]},
  { rank:352, k:'利', level:'N3', meanings:['provecho','ventaja','beneficio'], on:['リ'], kun:['き.く'],
    words:[{w:'便利',f:'べんり',m:'conveniente',l:'N5'},{w:'利用',f:'りよう',m:'uso / utilización',l:'N3'},{w:'権利',f:'けんり',m:'derecho',l:'N3'}]},
  { rank:353, k:'組', level:'N3', meanings:['grupo','equipo','ensamblar'], on:['ソ'], kun:['く.む','くみ'],
    words:[{w:'番組',f:'ばんぐみ',m:'programa (TV/radio)',l:'N3'},{w:'組織',f:'そしき',m:'organización',l:'N3'},{w:'組み合わせ',f:'くみあわせ',m:'combinación',l:'N3'}]},
  { rank:354, k:'信', level:'N3', meanings:['creer','confiar','fe'], on:['シン'], kun:[],
    words:[{w:'信じる',f:'しんじる',m:'creer',l:'N4'},{w:'自信',f:'じしん',m:'confianza en uno mismo',l:'N3'},{w:'信頼',f:'しんらい',m:'confianza',l:'N3'}]},
  { rank:355, k:'在', level:'N3', meanings:['existir','estar presente'], on:['ザイ'], kun:['あ.る'],
    words:[{w:'現在',f:'げんざい',m:'actualmente',l:'N4'},{w:'存在',f:'そんざい',m:'existencia',l:'N3'},{w:'不在',f:'ふざい',m:'ausencia',l:'N3'}]},
  { rank:356, k:'件', level:'N3', meanings:['asunto','caso','incidente'], on:['ケン'], kun:['くだん'],
    words:[{w:'事件',f:'じけん',m:'incidente',l:'N4'},{w:'条件',f:'じょうけん',m:'condición',l:'N3'},{w:'要件',f:'ようけん',m:'requisito',l:'N3'}]},
  { rank:357, k:'側', level:'N3', meanings:['lado','flanco'], on:['ソク'], kun:['がわ','そば'],
    words:[{w:'右側',f:'みぎがわ',m:'lado derecho',l:'N5'},{w:'内側',f:'うちがわ',m:'interior',l:'N3'},{w:'外側',f:'そとがわ',m:'exterior',l:'N3'}]},
  { rank:358, k:'任', level:'N3', meanings:['encomendar','responsabilidad','deber'], on:['ニン'], kun:['まか.せる'],
    words:[{w:'任せる',f:'まかせる',m:'dejar a cargo',l:'N4'},{w:'責任',f:'せきにん',m:'responsabilidad',l:'N3'},{w:'担任',f:'たんにん',m:'tutor de clase',l:'N3'}]},
  { rank:359, k:'引', level:'N3', meanings:['tirar','jalar','atraer'], on:['イン'], kun:['ひ.く'],
    words:[{w:'引く',f:'ひく',m:'tirar / restar',l:'N5'},{w:'引っ越し',f:'ひっこし',m:'mudanza',l:'N4'},{w:'引用',f:'いんよう',m:'cita / citar',l:'N3'}]},
  { rank:360, k:'求', level:'N3', meanings:['pedir','solicitar','buscar'], on:['キュウ'], kun:['もと.める'],
    words:[{w:'求める',f:'もとめる',m:'buscar / pedir',l:'N4'},{w:'要求',f:'ようきゅう',m:'demanda / petición',l:'N3'},{w:'求人',f:'きゅうじん',m:'oferta de empleo',l:'N3'}]},
  { rank:361, k:'所', level:'N3', meanings:['lugar','punto','sitio'], on:['ショ'], kun:['ところ'],
    words:[{w:'場所',f:'ばしょ',m:'lugar',l:'N5'},{w:'住所',f:'じゅうしょ',m:'dirección (postal)',l:'N4'},{w:'研究所',f:'けんきゅうじょ',m:'instituto de investigación',l:'N3'}]},
  { rank:362, k:'昨', level:'N3', meanings:['ayer','anterior','pasado'], on:['サク'], kun:[],
    words:[{w:'昨日',f:'きのう',m:'ayer',l:'N5'},{w:'昨年',f:'さくねん',m:'el año pasado',l:'N4'},{w:'昨夜',f:'さくや',m:'anoche',l:'N3'}]},
  { rank:363, k:'論', level:'N3', meanings:['argumento','teoría','debate'], on:['ロン'], kun:['あげつら.う'],
    words:[{w:'議論',f:'ぎろん',m:'debate / discusión',l:'N3'},{w:'理論',f:'りろん',m:'teoría',l:'N3'},{w:'結論',f:'けつろん',m:'conclusión',l:'N3'}]},
  { rank:364, k:'官', level:'N3', meanings:['burocracia','funcionario'], on:['カン'], kun:[],
    words:[{w:'官庁',f:'かんちょう',m:'ministerio / agencia',l:'N3'},{w:'長官',f:'ちょうかん',m:'director general',l:'N3'}]},
  { rank:365, k:'増', level:'N3', meanings:['aumentar','incrementar'], on:['ゾウ'], kun:['ま.す','ふ.える'],
    words:[{w:'増える',f:'ふえる',m:'aumentar',l:'N4'},{w:'増加',f:'ぞうか',m:'incremento',l:'N3'},{w:'急増',f:'きゅうぞう',m:'aumento repentino',l:'N3'}]},
  { rank:366, k:'係', level:'N3', meanings:['encargado','relacionado','vinculado'], on:['ケイ'], kun:['かか','かかり'],
    words:[{w:'関係',f:'かんけい',m:'relación',l:'N4'},{w:'係員',f:'かかりいん',m:'persona encargada',l:'N3'}]},
  { rank:367, k:'情', level:'N3', meanings:['emoción','sentimiento','compasión'], on:['ジョウ','セイ'], kun:['なさ.け'],
    words:[{w:'感情',f:'かんじょう',m:'emoción',l:'N3'},{w:'事情',f:'じじょう',m:'circunstancias',l:'N3'},{w:'情報',f:'じょうほう',m:'información',l:'N3'}]},
  { rank:368, k:'投', level:'N3', meanings:['lanzar','arrojar','invertir'], on:['トウ'], kun:['な.げる'],
    words:[{w:'投げる',f:'なげる',m:'lanzar',l:'N4'},{w:'投票',f:'とうひょう',m:'voto',l:'N3'},{w:'投資',f:'とうし',m:'inversión',l:'N3'}]},
  { rank:369, k:'示', level:'N3', meanings:['mostrar','indicar','exhibir'], on:['ジ','シ'], kun:['しめ.す'],
    words:[{w:'示す',f:'しめす',m:'mostrar / indicar',l:'N3'},{w:'指示',f:'しじ',m:'instrucción',l:'N3'},{w:'展示',f:'てんじ',m:'exposición / exhibición',l:'N3'}]},
  { rank:370, k:'打', level:'N3', meanings:['golpear','batear','teclear'], on:['ダ'], kun:['う.つ'],
    words:[{w:'打つ',f:'うつ',m:'golpear / batear',l:'N4'},{w:'打ち合わせ',f:'うちあわせ',m:'reunión / coordinación',l:'N3'}]},
  { rank:371, k:'直', level:'N3', meanings:['recto','directo','corregir'], on:['チョク','ジキ'], kun:['ただ.ちに','なお.す'],
    words:[{w:'直接',f:'ちょくせつ',m:'directo / directamente',l:'N4'},{w:'直す',f:'なおす',m:'reparar / corregir',l:'N4'},{w:'直前',f:'ちょくぜん',m:'justo antes',l:'N3'}]},
  { rank:372, k:'両', level:'N3', meanings:['ambos','los dos'], on:['リョウ'], kun:[],
    words:[{w:'両方',f:'りょうほう',m:'ambos',l:'N4'},{w:'両親',f:'りょうしん',m:'ambos padres',l:'N4'},{w:'両立',f:'りょうりつ',m:'compatibilidad',l:'N3'}]},
  { rank:373, k:'式', level:'N3', meanings:['ceremonia','estilo','fórmula'], on:['シキ'], kun:[],
    words:[{w:'式',f:'しき',m:'ceremonia',l:'N4'},{w:'卒業式',f:'そつぎょうしき',m:'ceremonia de graduación',l:'N4'},{w:'方式',f:'ほうしき',m:'método / sistema',l:'N3'}]},
  { rank:374, k:'果', level:'N3', meanings:['fruto','resultado','lograr'], on:['カ'], kun:['は.たす'],
    words:[{w:'果物',f:'くだもの',m:'fruta',l:'N5'},{w:'結果',f:'けっか',m:'resultado',l:'N3'},{w:'効果',f:'こうか',m:'efecto',l:'N3'}]},
  { rank:375, k:'容', level:'N3', meanings:['contener','apariencia','permitir'], on:['ヨウ'], kun:[],
    words:[{w:'美容院',f:'びよういん',m:'peluquería',l:'N4'},{w:'内容',f:'ないよう',m:'contenido',l:'N3'},{w:'容易',f:'ようい',m:'fácil / sencillo',l:'N3'}]},
  { rank:376, k:'必', level:'N3', meanings:['inevitable','sin falta','ciertamente'], on:['ヒツ'], kun:['かなら.ず'],
    words:[{w:'必要',f:'ひつよう',m:'necesario',l:'N4'},{w:'必ず',f:'かならず',m:'sin falta / con certeza',l:'N4'},{w:'必死',f:'ひっし',m:'desesperado',l:'N3'}]},
  { rank:377, k:'演', level:'N3', meanings:['actuar','representar','realizar'], on:['エン'], kun:[],
    words:[{w:'演じる',f:'えんじる',m:'actuar / representar',l:'N3'},{w:'演技',f:'えんぎ',m:'actuación',l:'N3'},{w:'演奏',f:'えんそう',m:'interpretación musical',l:'N3'}]},
  { rank:378, k:'歳', level:'N3', meanings:['años de edad'], on:['サイ','セイ'], kun:[],
    words:[{w:'二十歳',f:'はたち',m:'veinte años',l:'N5'},{w:'歳',f:'さい',m:'años de edad',l:'N5'}]},
  { rank:379, k:'争', level:'N3', meanings:['contender','disputar','competir'], on:['ソウ'], kun:['あらそ.う'],
    words:[{w:'争う',f:'あらそう',m:'competir / disputar',l:'N3'},{w:'戦争',f:'せんそう',m:'guerra',l:'N3'},{w:'競争',f:'きょうそう',m:'competencia',l:'N3'}]},
  { rank:380, k:'談', level:'N3', meanings:['conversación','hablar','charla'], on:['ダン'], kun:[],
    words:[{w:'相談',f:'そうだん',m:'consulta / consejo',l:'N4'},{w:'冗談',f:'じょうだん',m:'broma',l:'N4'},{w:'会談',f:'かいだん',m:'conversación formal',l:'N3'}]},
  { rank:381, k:'位', level:'N3', meanings:['rango','grado','aproximadamente'], on:['イ'], kun:['くらい','ぐらい'],
    words:[{w:'位置',f:'いち',m:'posición',l:'N3'},{w:'地位',f:'ちい',m:'posición / rango',l:'N3'},{w:'単位',f:'たんい',m:'unidad',l:'N3'}]},
  { rank:382, k:'置', level:'N3', meanings:['colocar','poner','depositar'], on:['チ'], kun:['お.く'],
    words:[{w:'置く',f:'おく',m:'colocar / poner',l:'N5'},{w:'位置',f:'いち',m:'posición',l:'N3'},{w:'装置',f:'そうち',m:'dispositivo / aparato',l:'N3'}]},
  { rank:383, k:'流', level:'N3', meanings:['corriente','fluir','estilo'], on:['リュウ','ル'], kun:['なが.れる'],
    words:[{w:'流れる',f:'ながれる',m:'fluir / correr',l:'N4'},{w:'交流',f:'こうりゅう',m:'intercambio / interacción',l:'N3'},{w:'流行',f:'りゅうこう',m:'moda / tendencia',l:'N3'}]},
  { rank:384, k:'格', level:'N3', meanings:['rango','estatus','norma'], on:['カク','コウ','キャク'], kun:[],
    words:[{w:'資格',f:'しかく',m:'calificación / credencial',l:'N3'},{w:'性格',f:'せいかく',m:'personalidad',l:'N3'},{w:'合格',f:'ごうかく',m:'aprobado',l:'N3'}]},
  { rank:385, k:'疑', level:'N3', meanings:['dudar','sospechar','desconfiar'], on:['ギ'], kun:['うたが.う'],
    words:[{w:'疑問',f:'ぎもん',m:'duda / interrogante',l:'N3'},{w:'疑う',f:'うたがう',m:'dudar / sospechar',l:'N3'},{w:'容疑者',f:'ようぎしゃ',m:'sospechoso',l:'N3'}]},
  { rank:386, k:'過', level:'N3', meanings:['exceder','pasar','sobrepasar'], on:['カ'], kun:['す.ぎる','あやま.つ'],
    words:[{w:'過去',f:'かこ',m:'pasado',l:'N4'},{w:'過ぎる',f:'すぎる',m:'pasar / exceder',l:'N4'},{w:'過程',f:'かてい',m:'proceso',l:'N3'}]},
  { rank:387, k:'局', level:'N3', meanings:['oficina','departamento','emisora'], on:['キョク'], kun:[],
    words:[{w:'郵便局',f:'ゆうびんきょく',m:'oficina de correos',l:'N5'},{w:'放送局',f:'ほうそうきょく',m:'emisora de radio/TV',l:'N3'},{w:'局面',f:'きょくめん',m:'situación / fase',l:'N3'}]},
  { rank:388, k:'放', level:'N3', meanings:['soltar','liberar','emitir'], on:['ホウ'], kun:['はな.す'],
    words:[{w:'放送',f:'ほうそう',m:'emisión / transmisión',l:'N4'},{w:'解放',f:'かいほう',m:'liberación',l:'N3'},{w:'放す',f:'はなす',m:'soltar / liberar',l:'N3'}]},
  { rank:389, k:'常', level:'N3', meanings:['normal','habitual','siempre'], on:['ジョウ'], kun:['つね','とこ'],
    words:[{w:'日常',f:'にちじょう',m:'cotidiano',l:'N3'},{w:'非常',f:'ひじょう',m:'emergencia / extremo',l:'N3'},{w:'常識',f:'じょうしき',m:'sentido común',l:'N3'}]},
  { rank:390, k:'状', level:'N3', meanings:['estado','condición','forma'], on:['ジョウ'], kun:[],
    words:[{w:'状態',f:'じょうたい',m:'estado / condición',l:'N3'},{w:'現状',f:'げんじょう',m:'situación actual',l:'N3'},{w:'症状',f:'しょうじょう',m:'síntoma',l:'N3'}]},
  { rank:391, k:'球', level:'N3', meanings:['esfera','pelota'], on:['キュウ'], kun:['たま'],
    words:[{w:'野球',f:'やきゅう',m:'béisbol',l:'N4'},{w:'地球',f:'ちきゅう',m:'Tierra',l:'N4'},{w:'電球',f:'でんきゅう',m:'bombilla',l:'N3'}]},
  { rank:392, k:'職', level:'N3', meanings:['ocupación','empleo','trabajo'], on:['ショク'], kun:[],
    words:[{w:'職業',f:'しょくぎょう',m:'profesión',l:'N4'},{w:'職場',f:'しょくば',m:'lugar de trabajo',l:'N3'},{w:'就職',f:'しゅうしょく',m:'conseguir empleo',l:'N3'}]},
  { rank:393, k:'与', level:'N3', meanings:['dar','proporcionar'], on:['ヨ','シャ'], kun:['あた.える'],
    words:[{w:'与える',f:'あたえる',m:'dar / proporcionar',l:'N3'},{w:'給与',f:'きゅうよ',m:'salario',l:'N3'},{w:'関与',f:'かんよ',m:'participación',l:'N3'}]},
  { rank:394, k:'供', level:'N3', meanings:['ofrecer','acompañar','niño'], on:['キョウ','ク'], kun:['そな.える','とも'],
    words:[{w:'子供',f:'こども',m:'niño',l:'N5'},{w:'提供',f:'ていきょう',m:'provisión / aportación',l:'N3'},{w:'供給',f:'きょうきゅう',m:'suministro',l:'N3'}]},
  { rank:395, k:'役', level:'N3', meanings:['papel','función','servicio'], on:['ヤク','エキ'], kun:[],
    words:[{w:'役に立つ',f:'やくにたつ',m:'ser útil',l:'N4'},{w:'役所',f:'やくしょ',m:'oficina pública',l:'N4'},{w:'役割',f:'やくわり',m:'papel / función',l:'N3'}]},
  { rank:396, k:'構', level:'N3', meanings:['construir','estructura','no importar'], on:['コウ'], kun:['かま.う'],
    words:[{w:'結構',f:'けっこう',m:'bastante / está bien',l:'N4'},{w:'構造',f:'こうぞう',m:'estructura',l:'N3'},{w:'機構',f:'きこう',m:'mecanismo / organismo',l:'N3'}]},
  { rank:397, k:'割', level:'N3', meanings:['dividir','porcentaje','romper'], on:['カツ'], kun:['わ.る','わり','さ.く'],
    words:[{w:'割合',f:'わりあい',m:'proporción / porcentaje',l:'N3'},{w:'割引',f:'わりびき',m:'descuento',l:'N3'},{w:'役割',f:'やくわり',m:'papel / función',l:'N3'}]},
  { rank:398, k:'身', level:'N3', meanings:['cuerpo','persona','uno mismo'], on:['シン'], kun:['み'],
    words:[{w:'出身',f:'しゅっしん',m:'origen / procedencia',l:'N4'},{w:'身体',f:'しんたい',m:'cuerpo',l:'N3'},{w:'自身',f:'じしん',m:'uno mismo',l:'N3'}]},
  { rank:399, k:'費', level:'N3', meanings:['gasto','coste','consumir'], on:['ヒ'], kun:['つい.やす'],
    words:[{w:'費用',f:'ひよう',m:'gasto / coste',l:'N4'},{w:'消費',f:'しょうひ',m:'consumo',l:'N3'},{w:'生活費',f:'せいかつひ',m:'gastos de vida',l:'N3'}]},
  { rank:400, k:'付', level:'N3', meanings:['adjuntar','añadir','pegar'], on:['フ'], kun:['つ.く','つ.ける'],
    words:[{w:'付く',f:'つく',m:'adherirse / encenderse',l:'N4'},{w:'気付く',f:'きづく',m:'darse cuenta',l:'N4'},{w:'付近',f:'ふきん',m:'cercanías',l:'N3'}]},
  { rank:401, k:'由', level:'N3', meanings:['origen','causa','razón'], on:['ユ','ユウ','ユイ'], kun:['よし'],
    words:[{w:'自由',f:'じゆう',m:'libertad',l:'N4'},{w:'理由',f:'りゆう',m:'razón / motivo',l:'N4'},{w:'由来',f:'ゆらい',m:'origen / procedencia',l:'N3'}]},
  { rank:402, k:'説', level:'N3', meanings:['teoría','explicar','persuadir'], on:['セツ','ゼイ'], kun:['と.く'],
    words:[{w:'説明',f:'せつめい',m:'explicación',l:'N4'},{w:'小説',f:'しょうせつ',m:'novela',l:'N4'},{w:'説得',f:'せっとく',m:'persuasión',l:'N3'}]},
  { rank:403, k:'難', level:'N3', meanings:['difícil','problema','desastre'], on:['ナン'], kun:['かた.い','むずか.しい'],
    words:[{w:'難しい',f:'むずかしい',m:'difícil',l:'N5'},{w:'困難',f:'こんなん',m:'dificultad',l:'N3'},{w:'避難',f:'ひなん',m:'evacuación',l:'N3'}]},
  { rank:404, k:'優', level:'N3', meanings:['superior','excelente','gentil'], on:['ユウ','ウ'], kun:['やさ.しい','すぐ.れる'],
    words:[{w:'優しい',f:'やさしい',m:'amable / gentil',l:'N5'},{w:'優れる',f:'すぐれる',m:'destacar / ser excelente',l:'N3'},{w:'優先',f:'ゆうせん',m:'prioridad',l:'N3'}]},
  { rank:405, k:'夫', level:'N3', meanings:['marido','esposo'], on:['フ','フウ'], kun:['おっと'],
    words:[{w:'夫',f:'おっと',m:'marido',l:'N4'},{w:'夫婦',f:'ふうふ',m:'matrimonio / pareja',l:'N3'},{w:'夫人',f:'ふじん',m:'señora / esposa',l:'N3'}]},
  { rank:406, k:'収', level:'N3', meanings:['recaudar','recoger','ingreso'], on:['シュウ'], kun:['おさ.める'],
    words:[{w:'収入',f:'しゅうにゅう',m:'ingresos',l:'N4'},{w:'回収',f:'かいしゅう',m:'recogida / recuperación',l:'N3'},{w:'収集',f:'しゅうしゅう',m:'colección',l:'N3'}]},
  { rank:407, k:'断', level:'N3', meanings:['rechazar','cortar','decidir'], on:['ダン'], kun:['た.つ','ことわ.る'],
    words:[{w:'断る',f:'ことわる',m:'rechazar / declinar',l:'N4'},{w:'判断',f:'はんだん',m:'juicio / decisión',l:'N3'},{w:'断言',f:'だんげん',m:'declaración categórica',l:'N3'}]},
  { rank:408, k:'石', level:'N3', meanings:['piedra','roca'], on:['セキ','シャク','コク'], kun:['いし'],
    words:[{w:'石',f:'いし',m:'piedra',l:'N5'},{w:'磁石',f:'じしゃく',m:'imán',l:'N3'},{w:'化石',f:'かせき',m:'fósil',l:'N3'}]},
  { rank:409, k:'違', level:'N3', meanings:['diferir','equivocarse','incorrecto'], on:['イ'], kun:['ちが.う'],
    words:[{w:'違う',f:'ちがう',m:'diferir / estar equivocado',l:'N5'},{w:'違い',f:'ちがい',m:'diferencia',l:'N4'},{w:'違反',f:'いはん',m:'infracción',l:'N3'}]},
  { rank:410, k:'消', level:'N3', meanings:['extinguir','borrar','desaparecer'], on:['ショウ'], kun:['き.える','け.す'],
    words:[{w:'消える',f:'きえる',m:'desaparecer / apagarse',l:'N4'},{w:'消費',f:'しょうひ',m:'consumo',l:'N3'},{w:'取り消す',f:'とりけす',m:'cancelar',l:'N3'}]},
  { rank:411, k:'神', level:'N3', meanings:['dios','deidad','espíritu'], on:['シン','ジン'], kun:['かみ','こう','かん'],
    words:[{w:'神社',f:'じんじゃ',m:'santuario sintoísta',l:'N4'},{w:'精神',f:'せいしん',m:'espíritu / mente',l:'N3'},{w:'神秘',f:'しんぴ',m:'misterio',l:'N3'}]},
  { rank:412, k:'番', level:'N3', meanings:['turno','número de serie','guardia'], on:['バン'], kun:['つが'],
    words:[{w:'番号',f:'ばんごう',m:'número',l:'N5'},{w:'交番',f:'こうばん',m:'comisaría de barrio',l:'N4'},{w:'番組',f:'ばんぐみ',m:'programa (TV/radio)',l:'N3'}]},
  { rank:413, k:'規', level:'N3', meanings:['regla','regulación','estándar'], on:['キ'], kun:[],
    words:[{w:'規則',f:'きそく',m:'regla / norma',l:'N4'},{w:'規制',f:'きせい',m:'regulación',l:'N3'},{w:'規模',f:'きぼ',m:'escala / magnitud',l:'N3'}]},
  { rank:414, k:'備', level:'N3', meanings:['preparar','equipar','prever'], on:['ビ'], kun:['そな.える'],
    words:[{w:'準備',f:'じゅんび',m:'preparación',l:'N4'},{w:'設備',f:'せつび',m:'instalaciones',l:'N3'},{w:'装備',f:'そうび',m:'equipo / armamento',l:'N3'}]},
  { rank:415, k:'宅', level:'N3', meanings:['hogar','residencia','domicilio'], on:['タク'], kun:[],
    words:[{w:'帰宅',f:'きたく',m:'regreso a casa',l:'N4'},{w:'自宅',f:'じたく',m:'casa propia / domicilio',l:'N3'},{w:'宅配',f:'たくはい',m:'entrega a domicilio',l:'N3'}]},
  { rank:416, k:'害', level:'N3', meanings:['daño','perjuicio','lesión'], on:['ガイ'], kun:[],
    words:[{w:'被害',f:'ひがい',m:'daño sufrido',l:'N3'},{w:'公害',f:'こうがい',m:'contaminación',l:'N3'},{w:'障害',f:'しょうがい',m:'discapacidad / obstáculo',l:'N3'}]},
  { rank:417, k:'警', level:'N3', meanings:['advertir','policía'], on:['ケイ'], kun:[],
    words:[{w:'警察',f:'けいさつ',m:'policía',l:'N4'},{w:'警告',f:'けいこく',m:'advertencia',l:'N3'},{w:'警備',f:'けいび',m:'seguridad / vigilancia',l:'N3'}]},
  { rank:418, k:'育', level:'N3', meanings:['criar','educar','crecer'], on:['イク'], kun:['そだ.てる','はぐく.む'],
    words:[{w:'教育',f:'きょういく',m:'educación',l:'N4'},{w:'育てる',f:'そだてる',m:'criar / educar',l:'N4'},{w:'保育',f:'ほいく',m:'cuidado de niños',l:'N3'}]},
  { rank:419, k:'席', level:'N3', meanings:['asiento','lugar','puesto'], on:['セキ'], kun:[],
    words:[{w:'出席',f:'しゅっせき',m:'asistencia / presencia',l:'N3'},{w:'欠席',f:'けっせき',m:'ausencia',l:'N3'},{w:'座席',f:'ざせき',m:'asiento',l:'N3'}]},
  { rank:420, k:'訪', level:'N3', meanings:['visitar','llamar','ir a ver'], on:['ホウ'], kun:['おとず.れる','たず.ねる'],
    words:[{w:'訪問',f:'ほうもん',m:'visita',l:'N4'},{w:'訪れる',f:'おとずれる',m:'visitar / llegar',l:'N3'},{w:'来訪',f:'らいほう',m:'visita (alguien viene)',l:'N3'}]},
  { rank:421, k:'残', level:'N3', meanings:['quedar','sobrar','resto'], on:['ザン'], kun:['のこ.る'],
    words:[{w:'残る',f:'のこる',m:'quedar / sobrar',l:'N4'},{w:'残念',f:'ざんねん',m:'lástima / decepción',l:'N4'},{w:'残業',f:'ざんぎょう',m:'horas extra',l:'N3'}]},
  { rank:422, k:'想', level:'N3', meanings:['idea','pensamiento','imaginar'], on:['ソウ','ソ'], kun:[],
    words:[{w:'感想',f:'かんそう',m:'impresión / opinión',l:'N4'},{w:'想像',f:'そうぞう',m:'imaginación',l:'N3'},{w:'理想',f:'りそう',m:'ideal',l:'N3'}]},
  { rank:423, k:'助', level:'N3', meanings:['ayudar','rescatar','asistir'], on:['ジョ'], kun:['たす.ける','すけ'],
    words:[{w:'助ける',f:'たすける',m:'ayudar / salvar',l:'N4'},{w:'助言',f:'じょげん',m:'consejo / asesoramiento',l:'N3'},{w:'救助',f:'きゅうじょ',m:'rescate',l:'N3'}]},
  { rank:424, k:'労', level:'N3', meanings:['trabajo','esfuerzo','fatiga'], on:['ロウ'], kun:['いたわ.る','ねぎら.う'],
    words:[{w:'苦労',f:'くろう',m:'esfuerzo / sufrimiento',l:'N4'},{w:'労働',f:'ろうどう',m:'trabajo / labor',l:'N4'},{w:'過労',f:'かろう',m:'exceso de trabajo',l:'N3'}]},
  { rank:425, k:'例', level:'N3', meanings:['ejemplo','instancia'], on:['レイ'], kun:['たと.える'],
    words:[{w:'例えば',f:'たとえば',m:'por ejemplo',l:'N4'},{w:'例外',f:'れいがい',m:'excepción',l:'N3'},{w:'事例',f:'じれい',m:'caso / ejemplo',l:'N3'}]},
  { rank:426, k:'然', level:'N3', meanings:['naturaleza','así','por supuesto'], on:['ゼン','ネン'], kun:[],
    words:[{w:'自然',f:'しぜん',m:'naturaleza',l:'N4'},{w:'当然',f:'とうぜん',m:'por supuesto',l:'N3'},{w:'突然',f:'とつぜん',m:'de repente',l:'N3'}]},
  { rank:427, k:'限', level:'N3', meanings:['límite','restricción'], on:['ゲン'], kun:['かぎ.る'],
    words:[{w:'限る',f:'かぎる',m:'limitar / restringir',l:'N3'},{w:'制限',f:'せいげん',m:'limitación',l:'N3'},{w:'期限',f:'きげん',m:'plazo / fecha límite',l:'N3'}]},
  { rank:428, k:'追', level:'N3', meanings:['perseguir','seguir'], on:['ツイ'], kun:['お.う'],
    words:[{w:'追う',f:'おう',m:'perseguir / seguir',l:'N3'},{w:'追加',f:'ついか',m:'adición',l:'N3'},{w:'追跡',f:'ついせき',m:'seguimiento / rastreo',l:'N3'}]},
  { rank:429, k:'商', level:'N3', meanings:['comercio','negocio','mercader'], on:['ショウ'], kun:['あきな.う'],
    words:[{w:'商品',f:'しょうひん',m:'mercancía',l:'N3'},{w:'商業',f:'しょうぎょう',m:'comercio',l:'N3'},{w:'商店',f:'しょうてん',m:'tienda / comercio',l:'N3'}]},
  { rank:430, k:'葉', level:'N3', meanings:['hoja','foliage'], on:['ヨウ'], kun:['は'],
    words:[{w:'言葉',f:'ことば',m:'palabra / lenguaje',l:'N5'},{w:'葉',f:'は',m:'hoja',l:'N4'},{w:'紅葉',f:'こうよう',m:'follaje otoñal / momiji',l:'N3'}]},
  { rank:431, k:'伝', level:'N3', meanings:['transmitir','comunicar','propagar'], on:['デン'], kun:['つた.える'],
    words:[{w:'伝える',f:'つたえる',m:'transmitir / comunicar',l:'N4'},{w:'伝統',f:'でんとう',m:'tradición',l:'N3'},{w:'宣伝',f:'せんでん',m:'publicidad / propaganda',l:'N3'}]},
  { rank:432, k:'形', level:'N3', meanings:['forma','figura','apariencia'], on:['ケイ','ギョウ'], kun:['かた','かたち'],
    words:[{w:'形',f:'かたち',m:'forma / figura',l:'N4'},{w:'人形',f:'にんぎょう',m:'muñeca / marioneta',l:'N4'},{w:'形式',f:'けいしき',m:'formato / formalidad',l:'N3'}]},
  { rank:433, k:'景', level:'N3', meanings:['paisaje','vista','escena'], on:['ケイ','ケ'], kun:[],
    words:[{w:'景色',f:'けしき',m:'paisaje / vista',l:'N4'},{w:'風景',f:'ふうけい',m:'paisaje / escenario',l:'N4'},{w:'背景',f:'はいけい',m:'fondo / contexto',l:'N3'}]},
  { rank:434, k:'落', level:'N3', meanings:['caer','bajar','perder'], on:['ラク'], kun:['お.とす','お.ちる'],
    words:[{w:'落とす',f:'おとす',m:'dejar caer',l:'N4'},{w:'落ちる',f:'おちる',m:'caer',l:'N4'},{w:'落ち着く',f:'おちつく',m:'calmarse / establecerse',l:'N4'}]},
  { rank:435, k:'好', level:'N3', meanings:['gustar','afición','favorable'], on:['コウ'], kun:['この.む','す.き'],
    words:[{w:'好き',f:'すき',m:'gustar',l:'N5'},{w:'友好',f:'ゆうこう',m:'amistad',l:'N4'},{w:'好奇心',f:'こうきしん',m:'curiosidad',l:'N3'}]},
  { rank:436, k:'退', level:'N3', meanings:['retirarse','retroceder'], on:['タイ'], kun:['しりぞ.く','ひ.く','の.く'],
    words:[{w:'退院',f:'たいいん',m:'alta médica',l:'N3'},{w:'引退',f:'いんたい',m:'retiro',l:'N3'},{w:'退職',f:'たいしょく',m:'jubilación / renuncia',l:'N3'}]},
  { rank:437, k:'負', level:'N3', meanings:['perder','derrota','carga'], on:['フ'], kun:['ま.ける','お.う'],
    words:[{w:'負ける',f:'まける',m:'perder',l:'N4'},{w:'負担',f:'ふたん',m:'carga / responsabilidad',l:'N3'},{w:'勝負',f:'しょうぶ',m:'combate / competición',l:'N3'}]},
  { rank:438, k:'渡', level:'N3', meanings:['cruzar','entregar','pasar'], on:['ト'], kun:['わた.る','わた.す'],
    words:[{w:'渡る',f:'わたる',m:'cruzar / pasar',l:'N4'},{w:'渡す',f:'わたす',m:'entregar / pasar',l:'N4'},{w:'引き渡し',f:'ひきわたし',m:'entrega / extradición',l:'N3'}]},
  { rank:439, k:'差', level:'N3', meanings:['diferencia','distinción','discriminación'], on:['サ'], kun:['さ'],
    words:[{w:'差別',f:'さべつ',m:'discriminación',l:'N3'},{w:'時差',f:'じさ',m:'diferencia horaria',l:'N3'},{w:'格差',f:'かくさ',m:'brecha / disparidad',l:'N3'}]},
  { rank:440, k:'末', level:'N3', meanings:['final','extremo','punta'], on:['マツ','バツ'], kun:['すえ'],
    words:[{w:'週末',f:'しゅうまつ',m:'fin de semana',l:'N4'},{w:'年末',f:'ねんまつ',m:'fin de año',l:'N3'},{w:'始末',f:'しまつ',m:'resultado / manejo',l:'N3'}]},
  { rank:441, k:'守', level:'N3', meanings:['guardar','proteger','cumplir'], on:['シュ','ス'], kun:['まも.る','もり'],
    words:[{w:'守る',f:'まもる',m:'proteger / cumplir',l:'N4'},{w:'留守',f:'るす',m:'ausencia del hogar',l:'N4'},{w:'守備',f:'しゅび',m:'defensa',l:'N3'}]},
  { rank:442, k:'若', level:'N3', meanings:['joven','juvenil'], on:['ジャク','ニャク'], kun:['わか.い','も'],
    words:[{w:'若い',f:'わかい',m:'joven',l:'N4'},{w:'若者',f:'わかもの',m:'joven / juventud',l:'N4'},{w:'若手',f:'わかて',m:'persona joven (en trabajo)',l:'N3'}]},
  { rank:443, k:'種', level:'N3', meanings:['tipo','especie','semilla'], on:['シュ'], kun:['たね'],
    words:[{w:'種類',f:'しゅるい',m:'tipo / clase',l:'N3'},{w:'品種',f:'ひんしゅ',m:'variedad',l:'N3'},{w:'種目',f:'しゅもく',m:'categoría / evento',l:'N3'}]},
  { rank:444, k:'美', level:'N3', meanings:['belleza','hermoso'], on:['ビ','ミ'], kun:['うつく.しい'],
    words:[{w:'美しい',f:'うつくしい',m:'hermoso / bello',l:'N4'},{w:'美術',f:'びじゅつ',m:'arte / bellas artes',l:'N4'},{w:'美容',f:'びよう',m:'belleza',l:'N3'}]},
  { rank:445, k:'命', level:'N3', meanings:['vida','destino','orden'], on:['メイ','ミョウ'], kun:['いのち'],
    words:[{w:'命',f:'いのち',m:'vida',l:'N4'},{w:'運命',f:'うんめい',m:'destino',l:'N3'},{w:'命令',f:'めいれい',m:'orden / mandato',l:'N3'}]},
  { rank:446, k:'福', level:'N3', meanings:['fortuna','felicidad','bendición'], on:['フク'], kun:[],
    words:[{w:'幸福',f:'こうふく',m:'felicidad',l:'N3'},{w:'福祉',f:'ふくし',m:'bienestar',l:'N3'},{w:'福岡',f:'ふくおか',m:'Fukuoka (ciudad)',l:'N3'}]},
  { rank:447, k:'非', level:'N3', meanings:['no-','no es','incorrecto'], on:['ヒ'], kun:[],
    words:[{w:'非常に',f:'ひじょうに',m:'extremadamente',l:'N3'},{w:'非常口',f:'ひじょうぐち',m:'salida de emergencia',l:'N3'},{w:'非公開',f:'ひこうかい',m:'privado / no público',l:'N3'}]},
  { rank:448, k:'観', level:'N3', meanings:['observar','perspectiva','visión'], on:['カン'], kun:[],
    words:[{w:'観光',f:'かんこう',m:'turismo',l:'N4'},{w:'観客',f:'かんきゃく',m:'audiencia / espectadores',l:'N3'},{w:'観察',f:'かんさつ',m:'observación',l:'N3'}]},
  { rank:449, k:'察', level:'N3', meanings:['investigar','intuir','deducir'], on:['サツ'], kun:[],
    words:[{w:'警察',f:'けいさつ',m:'policía',l:'N4'},{w:'観察',f:'かんさつ',m:'observación',l:'N3'},{w:'視察',f:'しさつ',m:'inspección',l:'N3'}]},
  { rank:450, k:'段', level:'N3', meanings:['escalón','grado','etapa'], on:['ダン'], kun:[],
    words:[{w:'階段',f:'かいだん',m:'escaleras',l:'N4'},{w:'段階',f:'だんかい',m:'etapa / fase',l:'N3'},{w:'手段',f:'しゅだん',m:'medio / método',l:'N3'}]},
  { rank:451, k:'横', level:'N3', meanings:['horizontal','lado','lateral'], on:['オウ'], kun:['よこ'],
    words:[{w:'横',f:'よこ',m:'lado / horizontal',l:'N4'},{w:'横断歩道',f:'おうだんほどう',m:'paso de peatones',l:'N3'},{w:'横浜',f:'よこはま',m:'Yokohama',l:'N3'}]},
  { rank:452, k:'深', level:'N3', meanings:['profundo','hondo'], on:['シン'], kun:['ふか.い'],
    words:[{w:'深い',f:'ふかい',m:'profundo / hondo',l:'N4'},{w:'深夜',f:'しんや',m:'medianoche / madrugada',l:'N3'},{w:'深刻',f:'しんこく',m:'grave / serio',l:'N3'}]},
  { rank:453, k:'申', level:'N3', meanings:['decir (humilde)','noveno signo zodiacal'], on:['シン'], kun:['もう.す'],
    words:[{w:'申し込む',f:'もうしこむ',m:'solicitar / inscribirse',l:'N3'},{w:'申し訳',f:'もうしわけ',m:'disculpa',l:'N3'},{w:'申し上げる',f:'もうしあげる',m:'decir (humilde)',l:'N3'}]},
  { rank:454, k:'財', level:'N3', meanings:['propiedad','riqueza','activos'], on:['ザイ','サイ'], kun:[],
    words:[{w:'財布',f:'さいふ',m:'billetera / monedero',l:'N5'},{w:'財産',f:'ざいさん',m:'propiedad / patrimonio',l:'N3'},{w:'財政',f:'ざいせい',m:'finanzas públicas',l:'N3'}]},
  { rank:455, k:'港', level:'N3', meanings:['puerto','harbor'], on:['コウ'], kun:['みなと'],
    words:[{w:'空港',f:'くうこう',m:'aeropuerto',l:'N5'},{w:'港',f:'みなと',m:'puerto',l:'N4'},{w:'出港',f:'しゅっこう',m:'partida del puerto',l:'N3'}]},
  { rank:456, k:'識', level:'N3', meanings:['saber','discernir','conocimiento'], on:['シキ'], kun:[],
    words:[{w:'知識',f:'ちしき',m:'conocimiento',l:'N4'},{w:'意識',f:'いしき',m:'conciencia',l:'N3'},{w:'常識',f:'じょうしき',m:'sentido común',l:'N3'}]},
  { rank:457, k:'呼', level:'N3', meanings:['llamar','nombrar','invitar'], on:['コ'], kun:['よ.ぶ'],
    words:[{w:'呼ぶ',f:'よぶ',m:'llamar / invitar',l:'N4'},{w:'呼吸',f:'こきゅう',m:'respiración',l:'N3'},{w:'呼びかける',f:'よびかける',m:'hacer un llamamiento',l:'N3'}]},
  { rank:458, k:'良', level:'N3', meanings:['bueno','fino'], on:['リョウ'], kun:['よ','い'],
    words:[{w:'良い',f:'よい',m:'bueno / bien',l:'N5'},{w:'改良',f:'かいりょう',m:'mejora',l:'N3'},{w:'優良',f:'ゆうりょう',m:'excelente',l:'N3'}]},
  { rank:459, k:'阪', level:'N3', meanings:['pendiente (Osaka)'], on:['ハン'], kun:['さか'],
    words:[{w:'大阪',f:'おおさか',m:'Osaka',l:'N3'},{w:'阪神',f:'はんしん',m:'región Osaka-Kobe',l:'N3'}]},
  { rank:460, k:'候', level:'N3', meanings:['condición','estado','(sufijo epistolar)'], on:['コウ'], kun:['そうろう'],
    words:[{w:'気候',f:'きこう',m:'clima',l:'N3'},{w:'候補',f:'こうほ',m:'candidato',l:'N3'},{w:'天候',f:'てんこう',m:'condición meteorológica',l:'N3'}]},
  { rank:461, k:'程', level:'N3', meanings:['grado','extensión','medida'], on:['テイ'], kun:['ほど'],
    words:[{w:'程度',f:'ていど',m:'grado / nivel',l:'N4'},{w:'過程',f:'かてい',m:'proceso',l:'N3'},{w:'日程',f:'にってい',m:'programa / itinerario',l:'N3'}]},
  { rank:462, k:'満', level:'N3', meanings:['lleno','satisfecho','completo'], on:['マン'], kun:['み.ちる'],
    words:[{w:'不満',f:'ふまん',m:'insatisfacción',l:'N4'},{w:'満足',f:'まんぞく',m:'satisfacción',l:'N3'},{w:'満員',f:'まんいん',m:'lleno / aforo completo',l:'N3'}]},
  { rank:463, k:'敗', level:'N3', meanings:['derrota','perder'], on:['ハイ'], kun:['やぶ.れる'],
    words:[{w:'失敗',f:'しっぱい',m:'fracaso',l:'N4'},{w:'敗北',f:'はいぼく',m:'derrota',l:'N3'}]},
  { rank:464, k:'値', level:'N3', meanings:['precio','valor','costo'], on:['チ'], kun:['ね','あたい'],
    words:[{w:'値段',f:'ねだん',m:'precio',l:'N4'},{w:'価値',f:'かち',m:'valor',l:'N3'},{w:'値引き',f:'ねびき',m:'descuento',l:'N3'}]},
  { rank:465, k:'突', level:'N3', meanings:['empujar','sobresalir','de repente'], on:['トツ','カ'], kun:['つ.く'],
    words:[{w:'突然',f:'とつぜん',m:'de repente',l:'N3'},{w:'衝突',f:'しょうとつ',m:'choque / colisión',l:'N3'}]},
  { rank:466, k:'路', level:'N3', meanings:['camino','ruta','vía'], on:['ロ'], kun:['じ'],
    words:[{w:'道路',f:'どうろ',m:'carretera',l:'N4'},{w:'線路',f:'せんろ',m:'vía del tren',l:'N3'},{w:'路線',f:'ろせん',m:'línea (transporte)',l:'N3'}]},
  { rank:467, k:'科', level:'N3', meanings:['departamento','asignatura','ciencia'], on:['カ'], kun:[],
    words:[{w:'科学',f:'かがく',m:'ciencia',l:'N4'},{w:'外科',f:'げか',m:'cirugía',l:'N3'},{w:'内科',f:'ないか',m:'medicina interna',l:'N3'}]},
  { rank:468, k:'積', level:'N3', meanings:['acumular','amontonar','carga'], on:['セキ'], kun:['つ.む','つ.もる'],
    words:[{w:'積む',f:'つむ',m:'apilar / acumular',l:'N4'},{w:'面積',f:'めんせき',m:'área / superficie',l:'N3'},{w:'積極的',f:'せっきょくてき',m:'activo / proactivo',l:'N3'}]},
  { rank:469, k:'他', level:'N3', meanings:['otro','diferente','además'], on:['タ'], kun:['ほか'],
    words:[{w:'他の',f:'ほかの',m:'otro / demás',l:'N4'},{w:'その他',f:'そのほか',m:'etc. / entre otros',l:'N4'},{w:'他人',f:'たにん',m:'otra persona / extraño',l:'N3'}]},
  { rank:470, k:'処', level:'N3', meanings:['tratar','lidiar','lugar'], on:['ショ'], kun:[],
    words:[{w:'処理',f:'しょり',m:'procesamiento / gestión',l:'N3'},{w:'処分',f:'しょぶん',m:'disposición / sanción',l:'N3'},{w:'対処',f:'たいしょ',m:'manejo / respuesta',l:'N3'}]},
  { rank:471, k:'太', level:'N3', meanings:['gordo','grueso'], on:['タイ','タ'], kun:['ふと.い','ふと.る'],
    words:[{w:'太い',f:'ふとい',m:'gordo / grueso',l:'N4'},{w:'太る',f:'ふとる',m:'engordar',l:'N4'},{w:'太陽',f:'たいよう',m:'sol',l:'N4'}]},
  { rank:472, k:'客', level:'N3', meanings:['cliente','visitante','invitado'], on:['キャク','カク'], kun:[],
    words:[{w:'お客さん',f:'おきゃくさん',m:'cliente / invitado',l:'N5'},{w:'観客',f:'かんきゃく',m:'audiencia / espectadores',l:'N3'},{w:'旅客',f:'りょかく',m:'pasajero',l:'N3'}]},
  { rank:473, k:'否', level:'N3', meanings:['negar','no','rechazar'], on:['ヒ'], kun:['いな','いや'],
    words:[{w:'否定',f:'ひてい',m:'negación',l:'N3'},{w:'拒否',f:'きょひ',m:'rechazo / denegación',l:'N3'}]},
  { rank:474, k:'師', level:'N3', meanings:['maestro','experto','tropas'], on:['シ'], kun:[],
    words:[{w:'教師',f:'きょうし',m:'profesor / maestro',l:'N4'},{w:'医師',f:'いし',m:'médico',l:'N3'},{w:'師匠',f:'ししょう',m:'maestro / instructor',l:'N3'}]},
  { rank:475, k:'登', level:'N3', meanings:['subir','ascender'], on:['トウ','ト'], kun:['のぼ.る'],
    words:[{w:'登る',f:'のぼる',m:'subir / escalar',l:'N4'},{w:'登山',f:'とざん',m:'montañismo',l:'N4'},{w:'登録',f:'とうろく',m:'registro',l:'N3'}]},
  { rank:476, k:'易', level:'N3', meanings:['fácil','sencillo','comercio'], on:['エキ','イ'], kun:['やさ.しい'],
    words:[{w:'容易',f:'ようい',m:'fácil / sencillo',l:'N3'},{w:'貿易',f:'ぼうえき',m:'comercio exterior',l:'N3'}]},
  { rank:477, k:'速', level:'N3', meanings:['rápido','veloz'], on:['ソク'], kun:['はや.い'],
    words:[{w:'速い',f:'はやい',m:'rápido',l:'N5'},{w:'高速',f:'こうそく',m:'alta velocidad / autopista',l:'N4'},{w:'速度',f:'そくど',m:'velocidad',l:'N3'}]},
  { rank:478, k:'存', level:'N3', meanings:['existir','mantener'], on:['ソン','ゾン'], kun:[],
    words:[{w:'存在',f:'そんざい',m:'existencia',l:'N3'},{w:'保存',f:'ほぞん',m:'conservación / almacenamiento',l:'N3'}]},
  { rank:479, k:'殺', level:'N3', meanings:['matar','asesinar'], on:['サツ','セツ','サイ'], kun:['ころ.す'],
    words:[{w:'殺す',f:'ころす',m:'matar',l:'N3'},{w:'殺人',f:'さつじん',m:'asesinato',l:'N3'}]},
  { rank:480, k:'号', level:'N3', meanings:['número','nombre especial','señal'], on:['ゴウ'], kun:[],
    words:[{w:'番号',f:'ばんごう',m:'número',l:'N5'},{w:'信号',f:'しんごう',m:'semáforo / señal',l:'N4'},{w:'記号',f:'きごう',m:'símbolo',l:'N3'}]},
  { rank:481, k:'単', level:'N3', meanings:['simple','único','soltero'], on:['タン'], kun:['ひとえ'],
    words:[{w:'簡単',f:'かんたん',m:'fácil / sencillo',l:'N5'},{w:'単語',f:'たんご',m:'vocabulario / palabra',l:'N4'},{w:'単純',f:'たんじゅん',m:'simple / sencillo',l:'N3'}]},
  { rank:482, k:'座', level:'N3', meanings:['sentar','asiento'], on:['ザ'], kun:['すわ.る'],
    words:[{w:'座る',f:'すわる',m:'sentarse',l:'N5'},{w:'座席',f:'ざせき',m:'asiento',l:'N3'},{w:'銀座',f:'ぎんざ',m:'Ginza (barrio de Tokio)',l:'N3'}]},
  { rank:483, k:'破', level:'N3', meanings:['romper','destruir','rasgar'], on:['ハ'], kun:['やぶ.る','やぶ.れる'],
    words:[{w:'破る',f:'やぶる',m:'romper / rasgar',l:'N4'},{w:'破壊',f:'はかい',m:'destrucción',l:'N3'},{w:'破産',f:'はさん',m:'quiebra',l:'N3'}]},
  { rank:484, k:'除', level:'N3', meanings:['excluir','eliminar','salvo'], on:['ジョ','ジ'], kun:['のぞ.く'],
    words:[{w:'除く',f:'のぞく',m:'excluir / salvo',l:'N3'},{w:'削除',f:'さくじょ',m:'eliminación / borrado',l:'N3'},{w:'解除',f:'かいじょ',m:'levantamiento / cancelación',l:'N3'}]},
  { rank:485, k:'完', level:'N3', meanings:['completo','terminado','perfecto'], on:['カン'], kun:[],
    words:[{w:'完成',f:'かんせい',m:'finalización',l:'N3'},{w:'完全',f:'かんぜん',m:'perfecto / completo',l:'N3'},{w:'完璧',f:'かんぺき',m:'perfecto',l:'N3'}]},
  { rank:486, k:'降', level:'N3', meanings:['descender','caer','rendirse'], on:['コウ','ゴ'], kun:['ふ.る','お.りる'],
    words:[{w:'降りる',f:'おりる',m:'bajar / descender',l:'N5'},{w:'降る',f:'ふる',m:'caer (lluvia/nieve)',l:'N5'},{w:'以降',f:'いこう',m:'desde entonces / a partir de',l:'N3'}]},
  { rank:487, k:'責', level:'N3', meanings:['responsabilidad','culpa','reprochar'], on:['セキ'], kun:['せ.める'],
    words:[{w:'責任',f:'せきにん',m:'responsabilidad',l:'N3'},{w:'責める',f:'せめる',m:'culpar / reprochar',l:'N3'}]},
  { rank:488, k:'捕', level:'N3', meanings:['capturar','atrapar'], on:['ホ'], kun:['とら.える','つか.まえる'],
    words:[{w:'捕まる',f:'つかまる',m:'ser atrapado',l:'N3'},{w:'逮捕',f:'たいほ',m:'arresto',l:'N3'},{w:'捕まえる',f:'つかまえる',m:'atrapar / capturar',l:'N3'}]},
  { rank:489, k:'危', level:'N3', meanings:['peligroso','arriesgado'], on:['キ'], kun:['あぶ.ない'],
    words:[{w:'危ない',f:'あぶない',m:'peligroso',l:'N4'},{w:'危険',f:'きけん',m:'peligro',l:'N3'},{w:'危機',f:'きき',m:'crisis',l:'N3'}]},
  { rank:490, k:'給', level:'N3', meanings:['suministrar','salario','proveer'], on:['キュウ'], kun:['たま'],
    words:[{w:'給料',f:'きゅうりょう',m:'salario',l:'N4'},{w:'給付',f:'きゅうふ',m:'prestación / subsidio',l:'N3'},{w:'給食',f:'きゅうしょく',m:'comida escolar',l:'N3'}]},
  { rank:491, k:'苦', level:'N3', meanings:['sufrimiento','amargo','dificultad'], on:['ク'], kun:['にが.い','くる.しい'],
    words:[{w:'苦しい',f:'くるしい',m:'doloroso / difícil',l:'N4'},{w:'苦労',f:'くろう',m:'esfuerzo / sufrimiento',l:'N4'},{w:'苦手',f:'にがて',m:'punto débil / no ser bueno en',l:'N4'}]},
  { rank:492, k:'迎', level:'N3', meanings:['dar la bienvenida','recibir'], on:['ゲイ'], kun:['むか.える'],
    words:[{w:'迎える',f:'むかえる',m:'recibir / dar la bienvenida',l:'N4'},{w:'歓迎',f:'かんげい',m:'bienvenida',l:'N3'}]},
  { rank:493, k:'園', level:'N3', meanings:['parque','jardín'], on:['エン'], kun:['その'],
    words:[{w:'公園',f:'こうえん',m:'parque público',l:'N5'},{w:'幼稚園',f:'ようちえん',m:'jardín de infancia',l:'N4'},{w:'動物園',f:'どうぶつえん',m:'zoológico',l:'N4'}]},
  { rank:494, k:'具', level:'N3', meanings:['herramienta','implemento','ingrediente'], on:['グ'], kun:[],
    words:[{w:'道具',f:'どうぐ',m:'herramienta',l:'N4'},{w:'具体的',f:'ぐたいてき',m:'concreto / específico',l:'N3'},{w:'文具',f:'ぶんぐ',m:'papelería',l:'N3'}]},
  { rank:495, k:'辞', level:'N3', meanings:['renunciar','dimitir','palabras'], on:['ジ'], kun:['や.める'],
    words:[{w:'辞書',f:'じしょ',m:'diccionario',l:'N5'},{w:'辞める',f:'やめる',m:'renunciar / dejar',l:'N4'},{w:'辞典',f:'じてん',m:'diccionario',l:'N4'}]},
  { rank:496, k:'因', level:'N3', meanings:['causa','factor','debido a'], on:['イン'], kun:['よ','ちな'],
    words:[{w:'原因',f:'げんいん',m:'causa',l:'N3'},{w:'要因',f:'よういん',m:'factor',l:'N3'}]},
  { rank:497, k:'馬', level:'N3', meanings:['caballo'], on:['バ'], kun:['うま','ま'],
    words:[{w:'馬',f:'うま',m:'caballo',l:'N5'},{w:'競馬',f:'けいば',m:'carreras de caballos',l:'N3'}]},
  { rank:498, k:'愛', level:'N3', meanings:['amor','afecto'], on:['アイ'], kun:['いと','まな','かな','め'],
    words:[{w:'愛する',f:'あいする',m:'amar',l:'N3'},{w:'愛情',f:'あいじょう',m:'afecto / cariño',l:'N3'},{w:'恋愛',f:'れんあい',m:'amor romántico',l:'N3'}]},
  { rank:499, k:'富', level:'N3', meanings:['riqueza','abundancia'], on:['フ','フウ'], kun:['と','とみ'],
    words:[{w:'富士山',f:'ふじさん',m:'monte Fuji',l:'N5'},{w:'豊富',f:'ほうふ',m:'abundante',l:'N3'}]},
  { rank:500, k:'彼', level:'N3', meanings:['él','ella','aquél'], on:['ヒ'], kun:['かれ','かの'],
    words:[{w:'彼女',f:'かのじょ',m:'ella / novia',l:'N5'},{w:'彼',f:'かれ',m:'él',l:'N4'},{w:'彼ら',f:'かれら',m:'ellos',l:'N3'}]},
  { rank:501, k:'未', level:'N3', meanings:['todavía no','aún no','prefijo negativo'], on:['ミ','ビ'], kun:['まだ','いまだ'],
    words:[{w:'未来',f:'みらい',m:'futuro',l:'N4'},{w:'未定',f:'みてい',m:'aún por determinar',l:'N3'},{w:'未満',f:'みまん',m:'menos de',l:'N3'}]},
  { rank:502, k:'舞', level:'N3', meanings:['danzar','bailar','circular'], on:['ブ'], kun:['ま','まい'],
    words:[{w:'舞台',f:'ぶたい',m:'escenario',l:'N4'},{w:'舞う',f:'まう',m:'danzar / girar',l:'N3'}]},
  { rank:503, k:'亡', level:'N3', meanings:['fallecido','morir','perdido'], on:['ボウ','モウ'], kun:['な'],
    words:[{w:'亡くなる',f:'なくなる',m:'fallecer',l:'N4'},{w:'死亡',f:'しぼう',m:'fallecimiento',l:'N3'},{w:'亡命',f:'ぼうめい',m:'exilio / huida',l:'N3'}]},
  { rank:504, k:'冷', level:'N3', meanings:['frío','enfriar','refrigerar'], on:['レイ'], kun:['つめ','ひ','さ'],
    words:[{w:'冷たい',f:'つめたい',m:'frío (al tacto)',l:'N5'},{w:'冷蔵庫',f:'れいぞうこ',m:'refrigerador',l:'N4'},{w:'冷静',f:'れいせい',m:'calmado / sereno',l:'N3'}]},
  { rank:505, k:'適', level:'N3', meanings:['adecuado','apropiado'], on:['テキ'], kun:[],
    words:[{w:'適当',f:'てきとう',m:'apropiado / razonable',l:'N3'},{w:'快適',f:'かいてき',m:'cómodo / agradable',l:'N3'}]},
  { rank:506, k:'婦', level:'N3', meanings:['mujer casada','señora'], on:['フ'], kun:['よめ'],
    words:[{w:'主婦',f:'しゅふ',m:'ama de casa',l:'N4'},{w:'夫婦',f:'ふうふ',m:'matrimonio / pareja',l:'N3'},{w:'婦人',f:'ふじん',m:'señora',l:'N3'}]},
  { rank:507, k:'寄', level:'N3', meanings:['acercarse','contribuir','donación'], on:['キ'], kun:['よ.る'],
    words:[{w:'寄る',f:'よる',m:'acercarse / pasar por',l:'N4'},{w:'寄付',f:'きふ',m:'donación',l:'N3'}]},
  { rank:508, k:'込', level:'N3', meanings:['estar lleno','meter','incluir'], on:[], kun:['こ'],
    words:[{w:'込む',f:'こむ',m:'estar lleno / atiborrado',l:'N4'},{w:'申し込む',f:'もうしこむ',m:'solicitar / inscribirse',l:'N3'}]},
  { rank:509, k:'類', level:'N3', meanings:['tipo','clase','género'], on:['ルイ'], kun:['たぐ.い'],
    words:[{w:'種類',f:'しゅるい',m:'tipo / clase',l:'N3'},{w:'分類',f:'ぶんるい',m:'clasificación',l:'N3'},{w:'人類',f:'じんるい',m:'humanidad',l:'N3'}]},
  { rank:510, k:'余', level:'N3', meanings:['sobrante','exceso','más de'], on:['ヨ'], kun:['あま.る'],
    words:[{w:'余る',f:'あまる',m:'sobrar',l:'N4'},{w:'余裕',f:'よゆう',m:'margen / holgura',l:'N3'},{w:'余分',f:'よぶん',m:'excedente / sobrante',l:'N3'}]},
  { rank:511, k:'王', level:'N3', meanings:['rey','monarca'], on:['オウ'], kun:[],
    words:[{w:'王様',f:'おうさま',m:'rey',l:'N4'},{w:'王国',f:'おうこく',m:'reino',l:'N3'},{w:'女王',f:'じょおう',m:'reina',l:'N3'}]},
  { rank:512, k:'返', level:'N3', meanings:['devolver','responder'], on:['ヘン'], kun:['かえ.す','かえ.る'],
    words:[{w:'返事',f:'へんじ',m:'respuesta',l:'N5'},{w:'返す',f:'かえす',m:'devolver',l:'N4'},{w:'返却',f:'へんきゃく',m:'devolución',l:'N3'}]},
  { rank:513, k:'妻', level:'N3', meanings:['esposa','mujer'], on:['サイ'], kun:['つま'],
    words:[{w:'妻',f:'つま',m:'esposa',l:'N4'},{w:'夫妻',f:'ふさい',m:'matrimonio / esposos',l:'N3'}]},
  { rank:514, k:'背', level:'N3', meanings:['espalda','estatura','dar la espalda'], on:['ハイ'], kun:['そむ.く','せい','せ'],
    words:[{w:'背中',f:'せなか',m:'espalda',l:'N4'},{w:'背景',f:'はいけい',m:'fondo / contexto',l:'N3'},{w:'背負う',f:'せおう',m:'cargar a la espalda',l:'N3'}]},
  { rank:515, k:'熱', level:'N3', meanings:['calor','fiebre','ardor'], on:['ネツ'], kun:['あつ.い'],
    words:[{w:'熱い',f:'あつい',m:'caliente (al tacto)',l:'N5'},{w:'熱心',f:'ねっしん',m:'entusiasta / diligente',l:'N4'},{w:'情熱',f:'じょうねつ',m:'pasión',l:'N3'}]},
  { rank:516, k:'宿', level:'N3', meanings:['alojamiento','posada','tarea'], on:['シュク'], kun:['やど'],
    words:[{w:'宿題',f:'しゅくだい',m:'tarea / deberes',l:'N5'},{w:'宿泊',f:'しゅくはく',m:'alojamiento / estancia',l:'N3'}]},
  { rank:517, k:'険', level:'N3', meanings:['peligroso','escarpado'], on:['ケン'], kun:['けわ.しい'],
    words:[{w:'保険',f:'ほけん',m:'seguro',l:'N4'},{w:'険しい',f:'けわしい',m:'escarpado / riguroso',l:'N3'},{w:'危険',f:'きけん',m:'peligro',l:'N3'}]},
  { rank:518, k:'頼', level:'N3', meanings:['pedir','confiar','depender'], on:['ライ'], kun:['たの.む','たよ.る'],
    words:[{w:'頼む',f:'たのむ',m:'pedir / rogar',l:'N4'},{w:'信頼',f:'しんらい',m:'confianza',l:'N3'},{w:'依頼',f:'いらい',m:'solicitud / encargo',l:'N3'}]},
  { rank:519, k:'覚', level:'N3', meanings:['memorizar','recordar','despertar'], on:['カク'], kun:['おぼ.える','さ.める'],
    words:[{w:'覚える',f:'おぼえる',m:'memorizar / recordar',l:'N4'},{w:'覚める',f:'さめる',m:'despertar',l:'N3'},{w:'自覚',f:'じかく',m:'conciencia propia',l:'N3'}]},
  { rank:520, k:'船', level:'N3', meanings:['barco','nave'], on:['セン'], kun:['ふね','ふな'],
    words:[{w:'船',f:'ふね',m:'barco',l:'N4'},{w:'客船',f:'きゃくせん',m:'barco de pasajeros',l:'N3'},{w:'造船',f:'ぞうせん',m:'construcción naval',l:'N3'}]},
  { rank:521, k:'途', level:'N3', meanings:['camino','ruta','a mitad'], on:['ト'], kun:['みち'],
    words:[{w:'途中',f:'とちゅう',m:'a mitad / en el camino',l:'N4'},{w:'用途',f:'ようと',m:'uso / aplicación',l:'N3'}]},
  { rank:522, k:'許', level:'N3', meanings:['permitir','aprobar','perdonar'], on:['キョ'], kun:['ゆる.す'],
    words:[{w:'許す',f:'ゆるす',m:'perdonar / permitir',l:'N4'},{w:'免許',f:'めんきょ',m:'licencia / carnet',l:'N4'},{w:'許可',f:'きょか',m:'permiso',l:'N3'}]},
  { rank:523, k:'抜', level:'N3', meanings:['sacar','extraer','quitar'], on:['バツ'], kun:['ぬ.く'],
    words:[{w:'抜く',f:'ぬく',m:'sacar / extraer',l:'N3'},{w:'引き抜く',f:'ひきぬく',m:'arrancar / headhunting',l:'N3'}]},
  { rank:524, k:'便', level:'N3', meanings:['conveniente','servicio','correo'], on:['ベン','ビン'], kun:['たよ'],
    words:[{w:'便利',f:'べんり',m:'conveniente',l:'N5'},{w:'郵便',f:'ゆうびん',m:'correo postal',l:'N4'},{w:'不便',f:'ふべん',m:'inconveniente',l:'N4'}]},
  { rank:525, k:'留', level:'N3', meanings:['detenerse','retener','estudiar en el extranjero'], on:['リュウ','ル'], kun:['と.まる','とど.める'],
    words:[{w:'留学',f:'りゅうがく',m:'estudiar en el extranjero',l:'N4'},{w:'留守',f:'るす',m:'ausencia del hogar',l:'N4'}]},
  { rank:526, k:'罪', level:'N3', meanings:['crimen','culpa','pecado'], on:['ザイ'], kun:['つみ'],
    words:[{w:'犯罪',f:'はんざい',m:'crimen',l:'N3'},{w:'謝罪',f:'しゃざい',m:'disculpa',l:'N3'},{w:'無罪',f:'むざい',m:'inocencia',l:'N3'}]},
  { rank:527, k:'努', level:'N3', meanings:['esforzarse','hacer el máximo'], on:['ド'], kun:['つと.める'],
    words:[{w:'努力',f:'どりょく',m:'esfuerzo',l:'N4'},{w:'努める',f:'つとめる',m:'esforzarse',l:'N3'}]},
  { rank:528, k:'精', level:'N3', meanings:['refinado','espíritu','fuerza vital'], on:['セイ','ショウ'], kun:['しら'],
    words:[{w:'精神',f:'せいしん',m:'espíritu / mente',l:'N3'},{w:'精力',f:'せいりょく',m:'energía / vitalidad',l:'N3'}]},
  { rank:529, k:'散', level:'N3', meanings:['dispersar','esparcir','pasear'], on:['サン'], kun:['ち.る'],
    words:[{w:'散歩',f:'さんぽ',m:'paseo',l:'N5'},{w:'解散',f:'かいさん',m:'disolución',l:'N3'}]},
  { rank:530, k:'静', level:'N3', meanings:['quieto','tranquilo','silencioso'], on:['セイ','ジョウ'], kun:['しず.まる'],
    words:[{w:'静か',f:'しずか',m:'tranquilo / silencioso',l:'N5'},{w:'冷静',f:'れいせい',m:'calmado',l:'N3'}]},
  { rank:531, k:'婚', level:'N3', meanings:['matrimonio','casarse'], on:['コン'], kun:[],
    words:[{w:'結婚',f:'けっこん',m:'matrimonio / boda',l:'N4'},{w:'離婚',f:'りこん',m:'divorcio',l:'N3'},{w:'婚約',f:'こんやく',m:'compromiso / noviazgo',l:'N3'}]},
  { rank:532, k:'喜', level:'N3', meanings:['regocijarse','alegría'], on:['キ'], kun:['よろこ.ぶ'],
    words:[{w:'喜ぶ',f:'よろこぶ',m:'alegrarse / regocijarse',l:'N4'},{w:'喜び',f:'よろこび',m:'alegría / felicidad',l:'N3'}]},
  { rank:533, k:'浮', level:'N3', meanings:['flotar','surgir','alegrarse'], on:['フ'], kun:['う.かぶ'],
    words:[{w:'浮かぶ',f:'うかぶ',m:'flotar / venir a la mente',l:'N3'},{w:'浮気',f:'うわき',m:'infidelidad',l:'N3'}]},
  { rank:534, k:'絶', level:'N3', meanings:['cortar','extinguir','absolutamente'], on:['ゼツ'], kun:['た.える','た.つ'],
    words:[{w:'絶対',f:'ぜったい',m:'absoluto / definitivamente',l:'N4'},{w:'絶える',f:'たえる',m:'extinguirse / cesar',l:'N3'},{w:'絶望',f:'ぜつぼう',m:'desesperanza',l:'N3'}]},
  { rank:535, k:'幸', level:'N3', meanings:['felicidad','fortuna','suerte'], on:['コウ'], kun:['しあわ','さち','さいわ'],
    words:[{w:'幸せ',f:'しあわせ',m:'felicidad',l:'N4'},{w:'幸福',f:'こうふく',m:'felicidad',l:'N3'}]},
  { rank:536, k:'押', level:'N3', meanings:['empujar','presionar'], on:['オウ'], kun:['お.す'],
    words:[{w:'押す',f:'おす',m:'empujar / presionar',l:'N4'},{w:'押さえる',f:'おさえる',m:'sujetar / controlar',l:'N3'}]},
  { rank:537, k:'倒', level:'N3', meanings:['caer','tumbar','derrotar'], on:['トウ'], kun:['たお.れる','たお.す'],
    words:[{w:'倒れる',f:'たおれる',m:'caerse / colapsar',l:'N4'},{w:'圧倒',f:'あっとう',m:'abrumar / aplastar',l:'N3'}]},
  { rank:538, k:'等', level:'N3', meanings:['igualdad','etc.','etcétera'], on:['トウ'], kun:['ひと','など'],
    words:[{w:'など',f:'など',m:'etc.',l:'N5'},{w:'平等',f:'びょうどう',m:'igualdad',l:'N3'}]},
  { rank:539, k:'老', level:'N3', meanings:['envejecer','anciano'], on:['ロウ'], kun:['お','ふ'],
    words:[{w:'老人',f:'ろうじん',m:'anciano',l:'N3'},{w:'老化',f:'ろうか',m:'envejecimiento',l:'N3'},{w:'老後',f:'ろうご',m:'vejez',l:'N3'}]},
  { rank:540, k:'曲', level:'N3', meanings:['curvar','melodía','canción'], on:['キョク'], kun:['ま.がる','ま.げる'],
    words:[{w:'曲',f:'きょく',m:'canción / melodía',l:'N4'},{w:'曲がる',f:'まがる',m:'torcer / girar',l:'N4'},{w:'作曲',f:'さっきょく',m:'composición musical',l:'N3'}]},
  { rank:541, k:'払', level:'N3', meanings:['pagar','limpiar','dispersar'], on:['フツ'], kun:['はら.う'],
    words:[{w:'払う',f:'はらう',m:'pagar',l:'N4'},{w:'支払い',f:'しはらい',m:'pago',l:'N3'}]},
  { rank:542, k:'庭', level:'N3', meanings:['jardín','patio'], on:['テイ'], kun:['にわ'],
    words:[{w:'庭',f:'にわ',m:'jardín / patio',l:'N4'},{w:'家庭',f:'かてい',m:'hogar / familia',l:'N4'}]},
  { rank:543, k:'徒', level:'N3', meanings:['seguidor','a pie','en vano'], on:['ト'], kun:[],
    words:[{w:'生徒',f:'せいと',m:'alumno',l:'N4'},{w:'徒歩',f:'とほ',m:'a pie',l:'N3'}]},
  { rank:544, k:'勤', level:'N3', meanings:['trabajar','servir'], on:['キン','ゴン'], kun:['つと.める'],
    words:[{w:'勤める',f:'つとめる',m:'trabajar (para una empresa)',l:'N4'},{w:'通勤',f:'つうきん',m:'desplazamiento al trabajo',l:'N4'}]},
  { rank:545, k:'居', level:'N3', meanings:['residir','estar presente'], on:['キョ','コ'], kun:['い.る'],
    words:[{w:'居る',f:'いる',m:'estar / existir',l:'N5'},{w:'居間',f:'いま',m:'sala de estar',l:'N4'},{w:'居住',f:'きょじゅう',m:'residencia',l:'N3'}]},
  { rank:546, k:'雑', level:'N3', meanings:['diverso','misceláneo','descuidado'], on:['ザツ','ゾウ'], kun:['まじ.る'],
    words:[{w:'雑誌',f:'ざっし',m:'revista',l:'N4'},{w:'複雑',f:'ふくざつ',m:'complicado',l:'N3'}]},
  { rank:547, k:'招', level:'N3', meanings:['invitar','convocar','hacer señas'], on:['ショウ'], kun:['まね.く'],
    words:[{w:'招待',f:'しょうたい',m:'invitación',l:'N4'},{w:'招く',f:'まねく',m:'invitar / hacer señas',l:'N3'}]},
  { rank:548, k:'欠', level:'N3', meanings:['faltar','defecto','ausente'], on:['ケツ'], kun:['か.ける'],
    words:[{w:'欠席',f:'けっせき',m:'ausencia',l:'N3'},{w:'欠点',f:'けってん',m:'defecto',l:'N3'},{w:'不可欠',f:'ふかけつ',m:'indispensable',l:'N3'}]},
  { rank:549, k:'更', level:'N3', meanings:['renovar','reemplazar','además'], on:['コウ'], kun:['ふ','さら'],
    words:[{w:'更に',f:'さらに',m:'además / más aún',l:'N3'},{w:'変更',f:'へんこう',m:'cambio / modificación',l:'N3'}]},
  { rank:550, k:'刻', level:'N3', meanings:['tallar','grabar','momento'], on:['コク'], kun:['きざ'],
    words:[{w:'時刻',f:'じこく',m:'hora / momento',l:'N3'},{w:'深刻',f:'しんこく',m:'grave / serio',l:'N3'}]},
  { rank:551, k:'賛', level:'N3', meanings:['aprobar','estar de acuerdo'], on:['サン'], kun:[],
    words:[{w:'賛成',f:'さんせい',m:'acuerdo / aprobación',l:'N3'},{w:'賛同',f:'さんどう',m:'apoyo / aprobación',l:'N3'}]},
  { rank:552, k:'抱', level:'N3', meanings:['abrazar','contener'], on:['ホウ'], kun:['だ.く','かか.える'],
    words:[{w:'抱く',f:'だく',m:'abrazar',l:'N3'},{w:'抱える',f:'かかえる',m:'cargar / tener (un problema)',l:'N3'}]},
  { rank:553, k:'犯', level:'N3', meanings:['crimen','cometer delito'], on:['ハン'], kun:['おか.す'],
    words:[{w:'犯罪',f:'はんざい',m:'crimen',l:'N3'},{w:'犯人',f:'はんにん',m:'criminal / culpable',l:'N3'}]},
  { rank:554, k:'恐', level:'N3', meanings:['temer','miedo','horror'], on:['キョウ'], kun:['おそ.れる'],
    words:[{w:'恐ろしい',f:'おそろしい',m:'aterrador / horrible',l:'N3'},{w:'恐怖',f:'きょうふ',m:'terror / miedo',l:'N3'}]},
  { rank:555, k:'息', level:'N3', meanings:['respiración','hijo','interés'], on:['ムス','ソク'], kun:['いき'],
    words:[{w:'息子',f:'むすこ',m:'hijo',l:'N5'},{w:'息',f:'いき',m:'respiración',l:'N4'},{w:'休息',f:'きゅうそく',m:'descanso',l:'N3'}]},
  { rank:556, k:'戻', level:'N3', meanings:['volver','regresar'], on:['レイ'], kun:['もど.る','もど.す'],
    words:[{w:'戻る',f:'もどる',m:'volver / regresar',l:'N4'},{w:'戻す',f:'もどす',m:'devolver',l:'N4'}]},
  { rank:557, k:'願', level:'N3', meanings:['deseo','petición','súplica'], on:['ガン'], kun:['ねが.う'],
    words:[{w:'お願い',f:'おねがい',m:'por favor / petición',l:'N5'},{w:'願う',f:'ねがう',m:'desear / pedir',l:'N4'}]},
  { rank:558, k:'越', level:'N3', meanings:['superar','cruzar','traspasar'], on:['エツ'], kun:['こ.える'],
    words:[{w:'引っ越し',f:'ひっこし',m:'mudanza',l:'N4'},{w:'越える',f:'こえる',m:'superar / cruzar',l:'N3'}]},
  { rank:559, k:'欲', level:'N3', meanings:['deseo','codicia','anhelar'], on:['ヨク'], kun:['ほ.しい'],
    words:[{w:'欲しい',f:'ほしい',m:'querer / desear',l:'N5'},{w:'食欲',f:'しょくよく',m:'apetito',l:'N4'},{w:'欲望',f:'よくぼう',m:'deseo / codicia',l:'N3'}]},
  { rank:560, k:'痛', level:'N3', meanings:['dolor','doler','agudo'], on:['ツウ'], kun:['いた.い','いた.む'],
    words:[{w:'痛い',f:'いたい',m:'doloroso',l:'N4'},{w:'頭痛',f:'ずつう',m:'dolor de cabeza',l:'N4'},{w:'腹痛',f:'ふくつう',m:'dolor de estómago',l:'N3'}]},
  { rank:561, k:'笑', level:'N3', meanings:['reír','sonreír'], on:['ショウ'], kun:['わら.う','え.む'],
    words:[{w:'笑う',f:'わらう',m:'reír',l:'N4'},{w:'笑顔',f:'えがお',m:'sonrisa',l:'N4'},{w:'微笑む',f:'ほほえむ',m:'sonreír suavemente',l:'N3'}]},
  { rank:562, k:'互', level:'N3', meanings:['mutuamente','recíprocamente'], on:['ゴ'], kun:['たが','かたみ'],
    words:[{w:'互いに',f:'たがいに',m:'mutuamente',l:'N3'},{w:'相互',f:'そうご',m:'mutuo / recíproco',l:'N3'}]},
  { rank:563, k:'束', level:'N3', meanings:['ramo','atado','manojo'], on:['ソク'], kun:['たば','つか'],
    words:[{w:'花束',f:'はなたば',m:'ramo de flores',l:'N4'},{w:'約束',f:'やくそく',m:'promesa',l:'N4'}]},
  { rank:564, k:'似', level:'N3', meanings:['parecerse','similar'], on:['ジ'], kun:['に'],
    words:[{w:'似る',f:'にる',m:'parecerse',l:'N4'},{w:'似合う',f:'にあう',m:'quedar bien / sentar bien',l:'N3'}]},
  { rank:565, k:'列', level:'N3', meanings:['fila','hilera','columna'], on:['レツ','レ'], kun:[],
    words:[{w:'列車',f:'れっしゃ',m:'tren',l:'N4'},{w:'行列',f:'ぎょうれつ',m:'fila / cola',l:'N3'}]},
  { rank:566, k:'探', level:'N3', meanings:['buscar','explorar','investigar'], on:['タン'], kun:['さぐ.る','さが.す'],
    words:[{w:'探す',f:'さがす',m:'buscar',l:'N4'},{w:'探偵',f:'たんてい',m:'detective',l:'N3'},{w:'探検',f:'たんけん',m:'exploración',l:'N3'}]},
  { rank:567, k:'逃', level:'N3', meanings:['escapar','huir','evadir'], on:['トウ'], kun:['のが.れる','に.げる'],
    words:[{w:'逃げる',f:'にげる',m:'escapar / huir',l:'N4'},{w:'見逃す',f:'みのがす',m:'pasar por alto',l:'N3'}]},
  { rank:568, k:'遊', level:'N3', meanings:['jugar','divertirse','viajar'], on:['ユウ','ユ'], kun:['あそ.ぶ'],
    words:[{w:'遊ぶ',f:'あそぶ',m:'jugar',l:'N5'},{w:'遊園地',f:'ゆうえんち',m:'parque de atracciones',l:'N4'}]},
  { rank:569, k:'迷', level:'N3', meanings:['perderse','confundirse'], on:['メイ'], kun:['まよ.う'],
    words:[{w:'迷う',f:'まよう',m:'perderse / dudar',l:'N4'},{w:'迷惑',f:'めいわく',m:'molestia / inconveniencia',l:'N4'},{w:'迷子',f:'まいご',m:'niño perdido',l:'N3'}]},
  { rank:570, k:'夢', level:'N3', meanings:['sueño','ensoñación'], on:['ム'], kun:['ゆめ'],
    words:[{w:'夢',f:'ゆめ',m:'sueño',l:'N4'},{w:'夢中',f:'むちゅう',m:'absorto / obsesionado',l:'N3'},{w:'悪夢',f:'あくむ',m:'pesadilla',l:'N3'}]},
  { rank:571, k:'君', level:'N3', meanings:['tú','señor','sufijo masculino'], on:['クン'], kun:['きみ'],
    words:[{w:'君',f:'きみ',m:'tú (informal)',l:'N4'},{w:'君主',f:'くんしゅ',m:'monarca',l:'N3'}]},
  { rank:572, k:'閉', level:'N3', meanings:['cerrar','clausurar'], on:['ヘイ'], kun:['し.める','と.じる'],
    words:[{w:'閉める',f:'しめる',m:'cerrar',l:'N5'},{w:'閉店',f:'へいてん',m:'cierre de tienda',l:'N3'}]},
  { rank:573, k:'緒', level:'N3', meanings:['comienzo','cuerda','principio'], on:['ショ','チョ'], kun:['お'],
    words:[{w:'一緒に',f:'いっしょに',m:'juntos',l:'N5'},{w:'情緒',f:'じょうちょ',m:'emoción / atmósfera',l:'N3'}]},
  { rank:574, k:'折', level:'N3', meanings:['doblar','romper','oportunidad'], on:['セツ','シャク'], kun:['お.る','おり'],
    words:[{w:'折る',f:'おる',m:'doblar / romper',l:'N4'},{w:'折り紙',f:'おりがみ',m:'origami',l:'N4'},{w:'時折',f:'ときおり',m:'de vez en cuando',l:'N3'}]},
  { rank:575, k:'草', level:'N3', meanings:['hierba','maleza'], on:['ソウ'], kun:['くさ'],
    words:[{w:'草',f:'くさ',m:'hierba / planta',l:'N4'},{w:'雑草',f:'ざっそう',m:'maleza',l:'N3'}]},
  { rank:576, k:'暮', level:'N3', meanings:['oscurecer','vivir','sustento'], on:['ボ'], kun:['く.らす','く.れる'],
    words:[{w:'暮らす',f:'くらす',m:'vivir / pasar la vida',l:'N4'},{w:'夕暮れ',f:'ゆうぐれ',m:'anochecer',l:'N4'}]},
  { rank:577, k:'酒', level:'N3', meanings:['alcohol','sake'], on:['シュ'], kun:['さけ','さか'],
    words:[{w:'お酒',f:'おさけ',m:'alcohol / sake',l:'N4'},{w:'日本酒',f:'にほんしゅ',m:'sake japonés',l:'N3'}]},
  { rank:578, k:'悲', level:'N3', meanings:['triste','llorar','lamentar'], on:['ヒ'], kun:['かな.しい'],
    words:[{w:'悲しい',f:'かなしい',m:'triste',l:'N4'},{w:'悲劇',f:'ひげき',m:'tragedia',l:'N3'}]},
  { rank:579, k:'晴', level:'N3', meanings:['despejado','buen tiempo'], on:['セイ'], kun:['は.れる'],
    words:[{w:'晴れ',f:'はれ',m:'despejado / soleado',l:'N5'},{w:'晴れる',f:'はれる',m:'aclarar (tiempo)',l:'N4'}]},
  { rank:580, k:'掛', level:'N3', meanings:['colgar','multiplicar','cubrir'], on:['ケイ'], kun:['か.ける','かかり'],
    words:[{w:'掛ける',f:'かける',m:'colgar / cubrir',l:'N4'},{w:'声を掛ける',f:'こえをかける',m:'dirigirse a alguien',l:'N3'}]},
  { rank:581, k:'到', level:'N3', meanings:['llegar','alcanzar'], on:['トウ'], kun:['いた.る'],
    words:[{w:'到着',f:'とうちゃく',m:'llegada',l:'N4'},{w:'到達',f:'とうたつ',m:'alcanzar',l:'N3'}]},
  { rank:582, k:'盗', level:'N3', meanings:['robar','hurtar'], on:['トウ'], kun:['ぬす.む'],
    words:[{w:'盗む',f:'ぬすむ',m:'robar / hurtar',l:'N3'},{w:'盗難',f:'とうなん',m:'robo',l:'N3'}]},
  { rank:583, k:'吸', level:'N3', meanings:['inhalar','absorber','chupar'], on:['キュウ'], kun:['す.う'],
    words:[{w:'吸う',f:'すう',m:'inhalar / fumar',l:'N4'},{w:'呼吸',f:'こきゅう',m:'respiración',l:'N3'},{w:'吸収',f:'きゅうしゅう',m:'absorción',l:'N3'}]},
  { rank:584, k:'陽', level:'N3', meanings:['sol','positivo','cálido'], on:['ヨウ'], kun:['ひ'],
    words:[{w:'太陽',f:'たいよう',m:'sol',l:'N4'},{w:'陽気',f:'ようき',m:'alegre / animado',l:'N3'}]},
  { rank:585, k:'御', level:'N3', meanings:['honorable','honorífico'], on:['ギョ','ゴ'], kun:['おん','お'],
    words:[{w:'御飯',f:'ごはん',m:'arroz / comida',l:'N5'},{w:'御免',f:'ごめん',m:'perdón / lo siento',l:'N5'}]},
  { rank:586, k:'歯', level:'N3', meanings:['diente'], on:['シ'], kun:['は'],
    words:[{w:'歯',f:'は',m:'diente',l:'N4'},{w:'歯医者',f:'はいしゃ',m:'dentista',l:'N4'},{w:'虫歯',f:'むしば',m:'caries',l:'N3'}]},
  { rank:587, k:'忘', level:'N3', meanings:['olvidar'], on:['ボウ'], kun:['わす.れる'],
    words:[{w:'忘れる',f:'わすれる',m:'olvidar',l:'N5'},{w:'忘れ物',f:'わすれもの',m:'objeto olvidado',l:'N4'}]},
  { rank:588, k:'吹', level:'N3', meanings:['soplar','tocar (instrumento)'], on:['スイ'], kun:['ふ.く'],
    words:[{w:'吹く',f:'ふく',m:'soplar',l:'N4'},{w:'吹雪',f:'ふぶき',m:'tormenta de nieve',l:'N3'}]},
  { rank:589, k:'娘', level:'N3', meanings:['hija','chica'], on:['ジョウ'], kun:['むすめ','こ'],
    words:[{w:'娘',f:'むすめ',m:'hija',l:'N4'},{w:'娘さん',f:'むすめさん',m:'su hija (respetuoso)',l:'N4'}]},
  { rank:590, k:'誤', level:'N3', meanings:['error','equivocarse'], on:['ゴ'], kun:['あやま.る'],
    words:[{w:'誤解',f:'ごかい',m:'malentendido',l:'N3'},{w:'誤字',f:'ごじ',m:'errata / error tipográfico',l:'N3'}]},
  { rank:591, k:'洗', level:'N3', meanings:['lavar','limpiar'], on:['セン'], kun:['あら.う'],
    words:[{w:'洗う',f:'あらう',m:'lavar',l:'N5'},{w:'洗濯',f:'せんたく',m:'lavandería / lavado de ropa',l:'N4'},{w:'洗剤',f:'せんざい',m:'detergente',l:'N3'}]},
  { rank:592, k:'慣', level:'N3', meanings:['acostumbrarse','hábito'], on:['カン'], kun:['な.れる'],
    words:[{w:'慣れる',f:'なれる',m:'acostumbrarse',l:'N4'},{w:'習慣',f:'しゅうかん',m:'costumbre / hábito',l:'N4'}]},
  { rank:593, k:'礼', level:'N3', meanings:['etiqueta','gratitud','reverencia'], on:['レイ','ライ'], kun:[],
    words:[{w:'お礼',f:'おれい',m:'agradecimiento',l:'N4'},{w:'失礼',f:'しつれい',m:'descortesía',l:'N4'},{w:'礼儀',f:'れいぎ',m:'etiqueta / modales',l:'N3'}]},
  { rank:594, k:'窓', level:'N3', meanings:['ventana'], on:['ソウ'], kun:['まど'],
    words:[{w:'窓',f:'まど',m:'ventana',l:'N4'},{w:'窓口',f:'まどぐち',m:'ventanilla / taquilla',l:'N4'}]},
  { rank:595, k:'昔', level:'N3', meanings:['antaño','hace mucho','pasado'], on:['セキ','シャク'], kun:['むかし'],
    words:[{w:'昔',f:'むかし',m:'hace mucho / en el pasado',l:'N4'},{w:'昔話',f:'むかしばなし',m:'cuento antiguo',l:'N3'}]},
  { rank:596, k:'貧', level:'N3', meanings:['pobreza','pobre'], on:['ヒン','ビン'], kun:['まず.しい'],
    words:[{w:'貧しい',f:'まずしい',m:'pobre',l:'N3'},{w:'貧乏',f:'びんぼう',m:'pobreza / miseria',l:'N3'}]},
  { rank:597, k:'怒', level:'N3', meanings:['enojarse','airado'], on:['ド'], kun:['おこ.る','いか.る'],
    words:[{w:'怒る',f:'おこる',m:'enojarse',l:'N4'},{w:'怒り',f:'いかり',m:'ira / enojo',l:'N3'}]},
  { rank:598, k:'祖', level:'N3', meanings:['antepasado','ancestro'], on:['ソ'], kun:[],
    words:[{w:'祖父',f:'そふ',m:'abuelo (formal)',l:'N5'},{w:'祖母',f:'そぼ',m:'abuela (formal)',l:'N5'},{w:'祖先',f:'そせん',m:'antepasado',l:'N3'}]},
  { rank:599, k:'杯', level:'N3', meanings:['copa','vaso','contadora de tazas'], on:['ハイ'], kun:['さかずき'],
    words:[{w:'一杯',f:'いっぱい',m:'una taza / lleno',l:'N5'},{w:'乾杯',f:'かんぱい',m:'brindis / ¡salud!',l:'N4'}]},
  { rank:600, k:'疲', level:'N3', meanings:['cansado','fatiga'], on:['ヒ'], kun:['つか.れる'],
    words:[{w:'疲れる',f:'つかれる',m:'cansarse',l:'N4'},{w:'疲労',f:'ひろう',m:'fatiga',l:'N3'}]},
  { rank:601, k:'皆', level:'N3', meanings:['todos','todo el mundo'], on:['カイ'], kun:['みな','みんな'],
    words:[{w:'皆さん',f:'みなさん',m:'todos ustedes',l:'N5'},{w:'皆',f:'みんな',m:'todos',l:'N5'}]},
  { rank:602, k:'鳴', level:'N3', meanings:['sonar','cantar (pájaros)','llamar (animales)'], on:['メイ'], kun:['な.る','な.く'],
    words:[{w:'鳴る',f:'なる',m:'sonar',l:'N4'},{w:'鳴く',f:'なく',m:'cantar (pájaro) / llamar',l:'N4'}]},
  { rank:603, k:'腹', level:'N3', meanings:['vientre','estómago','ira'], on:['フク'], kun:['はら'],
    words:[{w:'お腹',f:'おなか',m:'barriga / estómago',l:'N5'},{w:'腹痛',f:'ふくつう',m:'dolor de estómago',l:'N3'}]},
  { rank:604, k:'煙', level:'N3', meanings:['humo'], on:['エン'], kun:['けむ','けむり'],
    words:[{w:'禁煙',f:'きんえん',m:'no fumar',l:'N4'},{w:'煙',f:'けむり',m:'humo',l:'N3'}]},
  { rank:605, k:'眠', level:'N3', meanings:['dormir','sueño'], on:['ミン'], kun:['ねむ.る','ねむ.い'],
    words:[{w:'眠る',f:'ねむる',m:'dormir',l:'N4'},{w:'眠い',f:'ねむい',m:'tener sueño',l:'N4'},{w:'不眠',f:'ふみん',m:'insomnio',l:'N3'}]},
  { rank:606, k:'怖', level:'N3', meanings:['asustado','aterrador'], on:['フ'], kun:['こわ.い'],
    words:[{w:'怖い',f:'こわい',m:'asustador / aterrador',l:'N4'},{w:'怖がる',f:'こわがる',m:'tener miedo',l:'N3'}]},
  { rank:607, k:'頂', level:'N3', meanings:['cima','cumbre','recibir (humilde)'], on:['チョウ'], kun:['いただ.く'],
    words:[{w:'いただく',f:'いただく',m:'recibir (humilde) / comer',l:'N4'},{w:'頂上',f:'ちょうじょう',m:'cima / cumbre',l:'N3'}]},
  { rank:608, k:'箱', level:'N3', meanings:['caja','estuche'], on:['ソウ'], kun:['はこ'],
    words:[{w:'箱',f:'はこ',m:'caja',l:'N4'},{w:'郵便箱',f:'ゆうびんばこ',m:'buzón',l:'N3'}]},
  { rank:609, k:'晩', level:'N3', meanings:['noche','tarde'], on:['バン'], kun:[],
    words:[{w:'今晩',f:'こんばん',m:'esta noche',l:'N5'},{w:'晩ご飯',f:'ばんごはん',m:'cena',l:'N5'},{w:'毎晩',f:'まいばん',m:'cada noche',l:'N4'}]},
  { rank:610, k:'寒', level:'N3', meanings:['frío (clima)'], on:['カン'], kun:['さむ.い'],
    words:[{w:'寒い',f:'さむい',m:'frío',l:'N5'},{w:'極寒',f:'ごっかん',m:'frío extremo',l:'N3'}]},
  { rank:611, k:'髪', level:'N3', meanings:['cabello','pelo'], on:['ハツ'], kun:['かみ'],
    words:[{w:'髪',f:'かみ',m:'cabello',l:'N4'},{w:'金髪',f:'きんぱつ',m:'cabello rubio',l:'N3'}]},
  { rank:612, k:'忙', level:'N3', meanings:['ocupado','ajetreado'], on:['ボウ','モウ'], kun:['いそが.しい'],
    words:[{w:'忙しい',f:'いそがしい',m:'ocupado',l:'N5'},{w:'多忙',f:'たぼう',m:'muy ocupado',l:'N3'}]},
  { rank:613, k:'才', level:'N3', meanings:['talento','años de edad'], on:['サイ'], kun:[],
    words:[{w:'天才',f:'てんさい',m:'genio',l:'N4'},{w:'才能',f:'さいのう',m:'talento',l:'N3'}]},
  { rank:614, k:'靴', level:'N3', meanings:['zapato','calzado'], on:['カ'], kun:['くつ'],
    words:[{w:'靴',f:'くつ',m:'zapato',l:'N4'},{w:'靴下',f:'くつした',m:'calcetín',l:'N4'}]},
  { rank:615, k:'恥', level:'N3', meanings:['vergüenza','avergonzarse'], on:['チ'], kun:['は','はじ'],
    words:[{w:'恥ずかしい',f:'はずかしい',m:'vergonzoso',l:'N4'},{w:'恥',f:'はじ',m:'vergüenza',l:'N3'}]},
  { rank:616, k:'偶', level:'N3', meanings:['por casualidad','número par'], on:['グウ'], kun:['たま'],
    words:[{w:'偶然',f:'ぐうぜん',m:'por casualidad',l:'N3'},{w:'偶数',f:'ぐうすう',m:'número par',l:'N3'}]},
  { rank:617, k:'偉', level:'N3', meanings:['admirable','grandioso'], on:['イ'], kun:['えら.い'],
    words:[{w:'偉い',f:'えらい',m:'admirable / grandioso',l:'N4'},{w:'偉大',f:'いだい',m:'grandioso / extraordinario',l:'N3'}]},
  { rank:618, k:'猫', level:'N3', meanings:['gato'], on:['ビョウ'], kun:['ねこ'],
    words:[{w:'猫',f:'ねこ',m:'gato',l:'N5'},{w:'子猫',f:'こねこ',m:'gatito',l:'N3'},{w:'野良猫',f:'のらねこ',m:'gato callejero',l:'N3'}]},
  { rank:619, k:'幾', level:'N3', meanings:['¿cuántos?','varios'], on:['キ'], kun:['いく'],
    words:[{w:'幾つ',f:'いくつ',m:'¿cuántos? / varios',l:'N5'},{w:'幾ら',f:'いくら',m:'¿cuánto?',l:'N5'}]},
  { rank:620, k:'誰', level:'N3', meanings:['¿quién?'], on:['スイ'], kun:['だれ'],
    words:[{w:'誰',f:'だれ',m:'¿quién?',l:'N5'},{w:'誰でも',f:'だれでも',m:'cualquiera',l:'N4'},{w:'誰も',f:'だれも',m:'nadie / todos',l:'N4'}]},
  { rank:621, k:'可', level:'N3', meanings:['posible','permitido'], on:['カ'], kun:[],
    words:[{w:'可能',f:'かのう',m:'posible',l:'N3'},{w:'不可能',f:'ふかのう',m:'imposible',l:'N3'},{w:'許可',f:'きょか',m:'permiso',l:'N3'}]},
  { rank:622, k:'念', level:'N3', meanings:['pensamiento','preocupación','deseo'], on:['ネン'], kun:[],
    words:[{w:'残念',f:'ざんねん',m:'lástima / qué pena',l:'N4'},{w:'念のため',f:'ねんのため',m:'por si acaso',l:'N3'},{w:'記念',f:'きねん',m:'conmemoración',l:'N3'}]},

]
