import type { Kanji } from './types'

// N1: 44 kanji

export const kanjiN1: Kanji[] = [
  { rank:670, k:'双', level:'N1', meanings:['par / ambos'], on:['ソウ'], kun:['ふた'],
    words:[{w:'双子',f:'ふたご',m:'gemelos',l:'N3'},{w:'双方',f:'そうほう',m:'ambas partes',l:'N2'}]},
  { rank:896, k:'膚', level:'N1', meanings:['piel / dermis'], on:['フ'], kun:['はだ'],
    words:[{w:'皮膚',f:'ひふ',m:'piel / cutis',l:'N2'}]},
  { rank:898, k:'臣', level:'N1', meanings:['vasallo / ministro'], on:['シン','ジン'], kun:[],
    words:[{w:'大臣',f:'だいじん',m:'ministro del gobierno',l:'N2'},{w:'家臣',f:'かしん',m:'vasallo',l:'N1'}]},
  { rank:959, k:'鈍', level:'N1', meanings:['embotado / lento'], on:['ドン'], kun:['にぶ.い'],
    words:[{w:'鈍感',f:'どんかん',m:'insensible / torpe',l:'N2'},{w:'鈍角',f:'どんかく',m:'ángulo obtuso',l:'N1'}]},
  { rank:988, k:'義', level:'N1', meanings:['justicia / significado'], on:['ギ'], kun:[],
    words:[{w:'義務',f:'ぎむ',m:'obligación / deber',l:'N3'},{w:'正義',f:'せいぎ',m:'justicia',l:'N2'},{w:'義理',f:'ぎり',m:'obligación social',l:'N1'}]},
  { rank:989, k:'幹', level:'N1', meanings:['tronco / núcleo'], on:['カン'], kun:['みき'],
    words:[{w:'新幹線',f:'しんかんせん',m:'shinkansen',l:'N4'},{w:'幹部',f:'かんぶ',m:'ejecutivo / cúpula',l:'N1'}]},
  { rank:990, k:'誠', level:'N1', meanings:['sinceridad / fidelidad'], on:['セイ'], kun:['まこと'],
    words:[{w:'誠実',f:'せいじつ',m:'sinceridad / honestidad',l:'N2'},{w:'誠意',f:'せいい',m:'sinceridad',l:'N1'}]},
  { rank:993, k:'憲', level:'N1', meanings:['constitución / ley'], on:['ケン'], kun:[],
    words:[{w:'憲法',f:'けんぽう',m:'constitución',l:'N2'}]},
  { rank:994, k:'縮', level:'N1', meanings:['encoger / reducir'], on:['シュク'], kun:['ちぢ.む'],
    words:[{w:'短縮',f:'たんしゅく',m:'acortamiento / reducción',l:'N2'},{w:'縮小',f:'しゅくしょう',m:'reducción / disminución',l:'N2'}]},
  { rank:995, k:'批', level:'N1', meanings:['criticar'], on:['ヒ'], kun:[],
    words:[{w:'批判',f:'ひはん',m:'crítica',l:'N3'},{w:'批評',f:'ひひょう',m:'crítica',l:'N1'}]},
  { rank:996, k:'距', level:'N1', meanings:['distancia'], on:['キョ'], kun:[],
    words:[{w:'距離',f:'きょり',m:'distancia',l:'N3'}]},
  { rank:997, k:'耐', level:'N1', meanings:['soportar / resistir'], on:['タイ'], kun:['た.える'],
    words:[{w:'耐久',f:'たいきゅう',m:'durabilidad / resistencia',l:'N2'},{w:'耐震',f:'たいしん',m:'resistencia sísmica',l:'N2'}]},
  { rank:998, k:'維', level:'N1', meanings:['mantener / fibra'], on:['イ'], kun:[],
    words:[{w:'維持',f:'いじ',m:'mantenimiento',l:'N4'},{w:'繊維',f:'せんい',m:'fibra',l:'N1'},{w:'維新',f:'いしん',m:'restauración / reforma',l:'N1'}]},
  { rank:999, k:'促', level:'N1', meanings:['impulsar / instar'], on:['ソク'], kun:['うなが.す'],
    words:[{w:'促進',f:'そくしん',m:'fomento / promoción',l:'N2'},{w:'催促',f:'さいそく',m:'urgir / apremiar',l:'N1'}]},
  { rank:1000, k:'殊', level:'N1', meanings:['especial / particularmente'], on:['シュ'], kun:['こと'],
    words:[{w:'特殊',f:'とくしゅ',m:'especial / particular',l:'N2'}]},
  { rank:1001, k:'既', level:'N1', meanings:['ya / anterior'], on:['キ'], kun:['すで.に'],
    words:[{w:'既製',f:'きせい',m:'de confección / listo para usar',l:'N2'},{w:'既存',f:'きそん',m:'existente',l:'N1'},{w:'既婚',f:'きこん',m:'casado',l:'N1'}]},
  { rank:1002, k:'微', level:'N1', meanings:['sutil / leve'], on:['ビ'], kun:['かす.か'],
    words:[{w:'微妙',f:'びみょう',m:'sutil / delicado',l:'N2'},{w:'微量',f:'びりょう',m:'cantidad mínima',l:'N1'},{w:'顕微鏡',f:'けんびきょう',m:'microscopio',l:'N1'}]},
  { rank:1003, k:'徹', level:'N1', meanings:['penetrar / exhaustivo'], on:['テツ'], kun:[],
    words:[{w:'徹底',f:'てってい',m:'minuciosidad / a fondo',l:'N2'},{w:'徹夜',f:'てつや',m:'trasnochar / pasar la noche en vela',l:'N3'}]},
  { rank:1004, k:'矛', level:'N1', meanings:['lanza / contradicción'], on:['ム'], kun:['ほこ'],
    words:[{w:'矛盾',f:'むじゅん',m:'contradicción',l:'N2'}]},
  { rank:1005, k:'慎', level:'N1', meanings:['prudente / cuidadoso'], on:['シン'], kun:['つつし.む'],
    words:[{w:'慎重',f:'しんちょう',m:'prudente / cauteloso',l:'N2'}]},
  { rank:1010, k:'析', level:'N1', meanings:['analizar / dividir'], on:['セキ'], kun:[],
    words:[{w:'分析',f:'ぶんせき',m:'análisis',l:'N2'}]},
  { rank:1011, k:'奮', level:'N1', meanings:['esforzarse / animarse'], on:['フン'], kun:['ふる.う'],
    words:[{w:'興奮',f:'こうふん',m:'excitación / emoción',l:'N2'},{w:'奮闘',f:'ふんとう',m:'lucha denodada',l:'N1'}]},
  { rank:1012, k:'廃', level:'N1', meanings:['abandonar / abolir'], on:['ハイ'], kun:['すた.れる'],
    words:[{w:'廃止',f:'はいし',m:'abolición / supresión',l:'N2'},{w:'廃棄',f:'はいき',m:'desecho / eliminación',l:'N1'}]},
  { rank:1013, k:'拒', level:'N1', meanings:['rechazar / negar'], on:['キョ'], kun:['こば.む'],
    words:[{w:'拒否',f:'きょひ',m:'rechazo / veto',l:'N3'},{w:'拒絶',f:'きょぜつ',m:'rechazo',l:'N1'}]},
  { rank:1016, k:'掲', level:'N1', meanings:['publicar / exhibir'], on:['ケイ'], kun:['かか.げる'],
    words:[{w:'掲示',f:'けいじ',m:'aviso / notificación',l:'N2'},{w:'掲載',f:'けいさい',m:'publicación',l:'N1'},{w:'掲示板',f:'けいじばん',m:'tablón de anuncios',l:'N1'}]},
  { rank:1018, k:'潔', level:'N1', meanings:['limpio / puro / honrado'], on:['ケツ'], kun:['いさぎよ.い'],
    words:[{w:'清潔',f:'せいけつ',m:'limpieza / higiene',l:'N3'},{w:'潔白',f:'けっぱく',m:'inocencia',l:'N1'}]},
  { rank:1019, k:'慮', level:'N1', meanings:['consideración / precaución'], on:['リョ'], kun:[],
    words:[{w:'遠慮',f:'えんりょ',m:'reserva / discreción',l:'N3'},{w:'考慮',f:'こうりょ',m:'consideración',l:'N1'},{w:'配慮',f:'はいりょ',m:'consideración / atención',l:'N1'}]},
  { rank:1020, k:'催', level:'N1', meanings:['organizar / sentir impulso'], on:['サイ'], kun:['もよお.す'],
    words:[{w:'開催',f:'かいさい',m:'celebración / realización',l:'N2'},{w:'主催',f:'しゅさい',m:'organización / patrocinio',l:'N1'}]},
  { rank:1021, k:'敵', level:'N1', meanings:['enemigo / rival'], on:['テキ'], kun:['かたき'],
    words:[{w:'敵対',f:'てきたい',m:'hostilidad / oposición',l:'N2'},{w:'強敵',f:'きょうてき',m:'rival fuerte',l:'N1'},{w:'無敵',f:'むてき',m:'invencible',l:'N1'}]},
  { rank:1023, k:'隔', level:'N1', meanings:['separar / distancia'], on:['カク'], kun:['へだ.てる'],
    words:[{w:'間隔',f:'かんかく',m:'intervalo / espacio',l:'N2'},{w:'隔離',f:'かくり',m:'aislamiento',l:'N1'}]},
  { rank:1025, k:'秀', level:'N1', meanings:['excelente / destacado'], on:['シュウ'], kun:['ひい.でる'],
    words:[{w:'優秀',f:'ゆうしゅう',m:'excelente / destacado',l:'N2'},{w:'秀才',f:'しゅうさい',m:'prodigio / talento',l:'N1'}]},
  { rank:1026, k:'懸', level:'N1', meanings:['colgar / apostar'], on:['ケン','ケ'], kun:['か.ける'],
    words:[{w:'一生懸命',f:'いっしょうけんめい',m:'con todo empeño',l:'N3'},{w:'懸念',f:'けねん',m:'preocupación',l:'N1'},{w:'懸賞',f:'けんしょう',m:'premio / concurso',l:'N1'}]},
  { rank:1031, k:'璧', level:'N1', meanings:['jade / perfección'], on:['ヘキ'], kun:[],
    words:[{w:'完璧',f:'かんぺき',m:'perfecto / impecable',l:'N3'}]},
  { rank:1032, k:'鑑', level:'N1', meanings:['espejo / modelo / apreciar'], on:['カン'], kun:['かがみ'],
    words:[{w:'鑑賞',f:'かんしょう',m:'apreciación (artística)',l:'N2'},{w:'鑑定',f:'かんてい',m:'peritaje / tasación',l:'N1'},{w:'図鑑',f:'ずかん',m:'enciclopedia ilustrada',l:'N1'}]},
  { rank:1033, k:'頑', level:'N1', meanings:['terco / obstinado'], on:['ガン'], kun:[],
    words:[{w:'頑張る',f:'がんばる',m:'esforzarse / dar lo mejor',l:'N4'},{w:'頑固',f:'がんこ',m:'terco / obstinado',l:'N1'},{w:'頑丈',f:'がんじょう',m:'robusto / resistente',l:'N1'}]},
  { rank:1034, k:'邪', level:'N1', meanings:['malvado / perverso'], on:['ジャ'], kun:[],
    words:[{w:'風邪',f:'かぜ',m:'resfriado',l:'N5'},{w:'邪魔',f:'じゃま',m:'estorbo / molestia',l:'N3'}]},
  { rank:1035, k:'我', level:'N1', meanings:['yo / uno mismo'], on:['ガ'], kun:['われ','わ'],
    words:[{w:'我慢',f:'がまん',m:'aguantar / paciencia',l:'N3'},{w:'怪我',f:'けが',m:'herida / lesión',l:'N4'}]},
  { rank:1036, k:'慢', level:'N1', meanings:['arrogancia / pereza'], on:['マン'], kun:[],
    words:[{w:'我慢',f:'がまん',m:'aguantar / paciencia',l:'N3'},{w:'自慢',f:'じまん',m:'presumir / alarde',l:'N3'}]},
  { rank:1037, k:'駄', level:'N1', meanings:['inútil / sin valor'], on:['ダ'], kun:[],
    words:[{w:'無駄',f:'むだ',m:'inútil / desperdicio',l:'N3'},{w:'駄目',f:'だめ',m:'no servir / prohibido',l:'N4'}]},
  { rank:1038, k:'憶', level:'N1', meanings:['recordar / pensar'], on:['オク'], kun:[],
    words:[{w:'記憶',f:'きおく',m:'memoria / recuerdo',l:'N3'},{w:'憶測',f:'おくそく',m:'conjetura / especulación',l:'N1'}]},
  { rank:1039, k:'瞬', level:'N1', meanings:['instante / parpadeo'], on:['シュン'], kun:['またた.く'],
    words:[{w:'瞬間',f:'しゅんかん',m:'instante / momento',l:'N3'},{w:'一瞬',f:'いっしゅん',m:'un instante',l:'N2'}]},
  { rank:1040, k:'趣', level:'N1', meanings:['gusto / encanto'], on:['シュ'], kun:['おもむき'],
    words:[{w:'趣味',f:'しゅみ',m:'afición / hobby',l:'N4'},{w:'趣旨',f:'しゅし',m:'propósito / intención',l:'N1'}]},
  { rank:1041, k:'怪', level:'N1', meanings:['misterioso / sospechoso'], on:['カイ'], kun:['あや.しい'],
    words:[{w:'怪我',f:'けが',m:'herida / lesión',l:'N4'},{w:'怪物',f:'かいぶつ',m:'monstruo',l:'N3'}]},
  { rank:1042, k:'恐', level:'N1', meanings:['miedo / temor'], on:['キョウ'], kun:['おそ.れる','おそ.ろしい'],
    words:[{w:'恐怖',f:'きょうふ',m:'miedo / terror',l:'N3'},{w:'恐竜',f:'きょうりゅう',m:'dinosaurio',l:'N2'}]},
]
