import type { Kanji } from './types'

// N4: 164 kanji

export const kanjiN4: Kanji[] = [
  { rank:15, k:'同', level:'N4', meanings:['igual','mismo'], on:['ドウ'], kun:['おな.じ'],
    words:[{w:'同じ',f:'おなじ',m:'igual / mismo',l:'N5'},{w:'同時',f:'どうじ',m:'al mismo tiempo',l:'N4'},]},
  { rank:18, k:'事', level:'N4', meanings:['asunto','cosa','hecho'], on:['ジ'], kun:['こと'],
    words:[{w:'仕事',f:'しごと',m:'trabajo',l:'N5'},{w:'大事',f:'だいじ',m:'importante',l:'N5'},{w:'事件',f:'じけん',m:'incidente / caso',l:'N4'},{w:'事故',f:'じこ',m:'accidente',l:'N4'}]},
  { rank:19, k:'自', level:'N4', meanings:['uno mismo'], on:['ジ','シ'], kun:['みずか.ら'],
    words:[{w:'自分',f:'じぶん',m:'uno mismo',l:'N5'},{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},{w:'自然',f:'しぜん',m:'naturaleza',l:'N4'},{w:'自由',f:'じゆう',m:'libertad',l:'N4'}]},
  { rank:32, k:'発', level:'N4', meanings:['partir','emitir','publicar'], on:['ハツ','ホツ'], kun:[],
    words:[{w:'出発',f:'しゅっぱつ',m:'partida / salida',l:'N5'},{w:'発表',f:'はっぴょう',m:'presentación / anuncio',l:'N4'},{w:'発音',f:'はつおん',m:'pronunciación',l:'N4'},]},
  { rank:38, k:'者', level:'N4', meanings:['persona','individuo'], on:['シャ'], kun:['もの'],
    words:[{w:'医者',f:'いしゃ',m:'médico',l:'N5'},{w:'若者',f:'わかもの',m:'joven',l:'N4'},{w:'読者',f:'どくしゃ',m:'lector',l:'N4'},]},
  { rank:40, k:'地', level:'N4', meanings:['tierra','terreno'], on:['チ','ジ'], kun:[],
    words:[{w:'地図',f:'ちず',m:'mapa',l:'N5'},{w:'地下',f:'ちか',m:'subterráneo',l:'N4'},{w:'土地',f:'とち',m:'terreno',l:'N4'}]},
  { rank:43, k:'業', level:'N4', meanings:['negocio','trabajo','industria'], on:['ギョウ','ゴウ'], kun:['わざ'],
    words:[{w:'授業',f:'じゅぎょう',m:'clase / lección',l:'N5'},{w:'卒業',f:'そつぎょう',m:'graduación',l:'N4'},{w:'職業',f:'しょくぎょう',m:'profesión',l:'N4'},]},
  { rank:46, k:'方', level:'N4', meanings:['dirección','persona','método'], on:['ホウ'], kun:['かた'],
    words:[{w:'使い方',f:'つかいかた',m:'manera de usar',l:'N5'},{w:'方法',f:'ほうほう',m:'método',l:'N4'},{w:'方向',f:'ほうこう',m:'dirección',l:'N4'},{w:'地方',f:'ちほう',m:'región',l:'N4'}]},
  { rank:52, k:'場', level:'N4', meanings:['lugar','sitio'], on:['ジョウ'], kun:['ば'],
    words:[{w:'場所',f:'ばしょ',m:'lugar',l:'N5'},{w:'工場',f:'こうじょう',m:'fábrica',l:'N4'},{w:'広場',f:'ひろば',m:'plaza',l:'N4'},{w:'駐車場',f:'ちゅうしゃじょう',m:'aparcamiento',l:'N4'}]},
  { rank:54, k:'員', level:'N4', meanings:['miembro','empleado'], on:['イン'], kun:[],
    words:[{w:'店員',f:'てんいん',m:'dependiente',l:'N4'},{w:'会員',f:'かいいん',m:'miembro',l:'N4'},{w:'社員',f:'しゃいん',m:'empleado',l:'N4'},]},
  { rank:59, k:'開', level:'N4', meanings:['abrir','inaugurar'], on:['カイ'], kun:['ひら.く','あ.ける'],
    words:[{w:'開始',f:'かいし',m:'comienzo',l:'N4'},{w:'開店',f:'かいてん',m:'apertura de tienda',l:'N3'},]},
  { rank:61, k:'米', level:'N4', meanings:['arroz','EE.UU.'], on:['マイ','ベイ'], kun:['こめ'],
    words:[{w:'お米',f:'おこめ',m:'arroz',l:'N5'},{w:'米国',f:'べいこく',m:'Estados Unidos',l:'N4'},]},
  { rank:62, k:'力', level:'N4', meanings:['fuerza','poder'], on:['リョク','リキ'], kun:['ちから'],
    words:[{w:'力',f:'ちから',m:'fuerza',l:'N5'},{w:'努力',f:'どりょく',m:'esfuerzo',l:'N4'},{w:'協力',f:'きょうりょく',m:'cooperación',l:'N4'},]},
  { rank:64, k:'問', level:'N4', meanings:['pregunta','problema'], on:['モン'], kun:['と.う'],
    words:[{w:'質問',f:'しつもん',m:'pregunta',l:'N5'},{w:'問題',f:'もんだい',m:'problema / pregunta',l:'N5'},{w:'訪問',f:'ほうもん',m:'visita',l:'N4'},]},
  { rank:66, k:'代', level:'N4', meanings:['generación','época','tarifa'], on:['ダイ','タイ'], kun:['かわ.る','よ'],
    words:[{w:'時代',f:'じだい',m:'época / era',l:'N4'},{w:'代わり',f:'かわり',m:'sustituto',l:'N4'},{w:'電話代',f:'でんわだい',m:'tarifa telefónica',l:'N4'},]},
  { rank:67, k:'明', level:'N4', meanings:['brillante','claro','mañana'], on:['メイ','ミョウ'], kun:['あか.るい','あき.らか'],
    words:[{w:'明日',f:'あした',m:'mañana',l:'N5'},{w:'明るい',f:'あかるい',m:'brillante / alegre',l:'N5'},{w:'説明',f:'せつめい',m:'explicación',l:'N4'},]},
  { rank:73, k:'動', level:'N4', meanings:['mover','moverse'], on:['ドウ'], kun:['うご.く'],
    words:[{w:'動物',f:'どうぶつ',m:'animal',l:'N5'},{w:'運動',f:'うんどう',m:'ejercicio / movimiento',l:'N4'},{w:'活動',f:'かつどう',m:'actividad',l:'N4'},{w:'自動',f:'じどう',m:'automático',l:'N4'},{w:'感動',f:'かんどう',m:'emoción / conmoción',l:'N4'}]},
  { rank:74, k:'京', level:'N4', meanings:['capital'], on:['キョウ','ケイ'], kun:[],
    words:[{w:'東京',f:'とうきょう',m:'Tokio',l:'N5'},{w:'京都',f:'きょうと',m:'Kioto',l:'N5'},]},
  { rank:80, k:'通', level:'N4', meanings:['pasar','circular','comunicar'], on:['ツウ'], kun:['とお.る','かよ.う'],
    words:[{w:'交通',f:'こうつう',m:'tráfico',l:'N4'},{w:'通勤',f:'つうきん',m:'desplazamiento al trabajo',l:'N4'},{w:'普通',f:'ふつう',m:'normal / corriente',l:'N4'}]},
  { rank:86, k:'理', level:'N4', meanings:['razón','principio'], on:['リ'], kun:[],
    words:[{w:'料理',f:'りょうり',m:'cocina / plato',l:'N5'},{w:'理由',f:'りゆう',m:'razón / motivo',l:'N4'},{w:'理解',f:'りかい',m:'comprensión',l:'N4'},{w:'管理',f:'かんり',m:'gestión / administración',l:'N4'},]},
  { rank:88, k:'体', level:'N4', meanings:['cuerpo'], on:['タイ','テイ'], kun:['からだ'],
    words:[{w:'体',f:'からだ',m:'cuerpo',l:'N5'},{w:'体育',f:'たいいく',m:'educación física',l:'N4'},{w:'体験',f:'たいけん',m:'experiencia',l:'N4'},{w:'全体',f:'ぜんたい',m:'totalidad / conjunto',l:'N4'},]},
  { rank:90, k:'田', level:'N4', meanings:['arrozal','campo'], on:['デン'], kun:['た'],
    words:[{w:'田んぼ',f:'たんぼ',m:'campo de arroz',l:'N5'},{w:'田舎',f:'いなか',m:'campo / zona rural',l:'N4'}]},
  { rank:95, k:'主', level:'N4', meanings:['dueño','principal','señor'], on:['シュ'], kun:['ぬし','おも'],
    words:[{w:'主人',f:'しゅじん',m:'marido / dueño',l:'N5'},{w:'主語',f:'しゅご',m:'sujeto (gramática)',l:'N4'},{w:'主に',f:'おもに',m:'principalmente',l:'N4'}]},
  { rank:96, k:'題', level:'N4', meanings:['tema','título','problema'], on:['ダイ'], kun:[],
    words:[{w:'問題',f:'もんだい',m:'problema',l:'N5'},{w:'宿題',f:'しゅくだい',m:'tarea / deberes',l:'N5'},{w:'題名',f:'だいめい',m:'título',l:'N4'},{w:'話題',f:'わだい',m:'tema de conversación',l:'N4'}]},
  { rank:99, k:'意', level:'N4', meanings:['idea','mente','intención'], on:['イ'], kun:[],
    words:[{w:'意味',f:'いみ',m:'significado',l:'N5'},{w:'注意',f:'ちゅうい',m:'atención / cuidado',l:'N4'},{w:'意見',f:'いけん',m:'opinión',l:'N4'},{w:'用意',f:'ようい',m:'preparación',l:'N4'}]},
  { rank:101, k:'不', level:'N4', meanings:['no-','in-','negación'], on:['フ','ブ'], kun:[],
    words:[{w:'不便',f:'ふべん',m:'inconveniente',l:'N4'},{w:'不安',f:'ふあん',m:'ansiedad / inquietud',l:'N4'},{w:'不満',f:'ふまん',m:'insatisfacción',l:'N4'},{w:'不思議',f:'ふしぎ',m:'misterioso',l:'N4'}]},
  { rank:103, k:'作', level:'N4', meanings:['hacer','crear','fabricar'], on:['サク','サ'], kun:['つく.る'],
    words:[{w:'作品',f:'さくひん',m:'obra',l:'N4'},{w:'作文',f:'さくぶん',m:'composición escrita',l:'N4'},{w:'工作',f:'こうさく',m:'manualidades',l:'N4'}]},
  { rank:107, k:'用', level:'N4', meanings:['uso','negocio','emplear'], on:['ヨウ'], kun:['もち.いる'],
    words:[{w:'使用',f:'しよう',m:'uso / utilización',l:'N4'},{w:'用意',f:'ようい',m:'preparación',l:'N4'},{w:'費用',f:'ひよう',m:'gasto / coste',l:'N4'},{w:'用事',f:'ようじ',m:'asunto / recado',l:'N4'}]},
  { rank:110, k:'度', level:'N4', meanings:['grado','vez','frecuencia'], on:['ド','ト'], kun:['たび'],
    words:[{w:'今度',f:'こんど',m:'esta vez / próxima vez',l:'N5'},{w:'温度',f:'おんど',m:'temperatura',l:'N4'},{w:'程度',f:'ていど',m:'grado / nivel',l:'N4'},{w:'毎度',f:'まいど',m:'cada vez',l:'N4'}]},
  { rank:112, k:'強', level:'N4', meanings:['fuerte'], on:['キョウ','ゴウ'], kun:['つよ.い'],
    words:[{w:'強い',f:'つよい',m:'fuerte',l:'N5'},{w:'勉強',f:'べんきょう',m:'estudio',l:'N5'},]},
  { rank:118, k:'公', level:'N4', meanings:['público','oficial'], on:['コウ','ク'], kun:[],
    words:[{w:'公園',f:'こうえん',m:'parque público',l:'N5'},{w:'公務員',f:'こうむいん',m:'funcionario público',l:'N4'},]},
  { rank:119, k:'持', level:'N4', meanings:['sostener','tener'], on:['ジ'], kun:['も.つ'],
    words:[{w:'気持ち',f:'きもち',m:'sentimiento',l:'N5'},{w:'持参',f:'じさん',m:'traer consigo',l:'N4'},{w:'気持ちいい',f:'きもちいい',m:'agradable / que sienta bien',l:'N4'}]},
  { rank:120, k:'野', level:'N4', meanings:['campo','llanura'], on:['ヤ'], kun:['の'],
    words:[{w:'野菜',f:'やさい',m:'verdura',l:'N5'},{w:'野球',f:'やきゅう',m:'béisbol',l:'N4'},{w:'野外',f:'やがい',m:'al aire libre',l:'N4'},]},
  { rank:126, k:'以', level:'N4', meanings:['por medio de','a partir de'], on:['イ'], kun:[],
    words:[{w:'以上',f:'いじょう',m:'más de / en adelante',l:'N4'},{w:'以下',f:'いか',m:'menos de / a continuación',l:'N4'},{w:'以前',f:'いぜん',m:'antes / anteriormente',l:'N4'},{w:'以外',f:'いがい',m:'excepto / aparte de',l:'N4'}]},
  { rank:132, k:'思', level:'N4', meanings:['pensar','sentir'], on:['シ'], kun:['おも.う'],
    words:[{w:'思い出',f:'おもいで',m:'recuerdo',l:'N4'},{w:'不思議',f:'ふしぎ',m:'misterioso / extraño',l:'N4'},]},
  { rank:133, k:'家', level:'N4', meanings:['casa','hogar','familia'], on:['カ','ケ'], kun:['いえ','や'],
    words:[{w:'家族',f:'かぞく',m:'familia',l:'N5'},{w:'家庭',f:'かてい',m:'hogar',l:'N4'},{w:'家具',f:'かぐ',m:'muebles',l:'N4'},{w:'家賃',f:'やちん',m:'alquiler',l:'N4'}]},
  { rank:135, k:'世', level:'N4', meanings:['generación','mundo','era'], on:['セイ','セ'], kun:['よ'],
    words:[{w:'世界',f:'せかい',m:'mundo',l:'N5'},{w:'世話',f:'せわ',m:'cuidado / ayuda',l:'N4'},{w:'世代',f:'せだい',m:'generación',l:'N4'},]},
  { rank:143, k:'正', level:'N4', meanings:['correcto','justo','recto'], on:['セイ','ショウ'], kun:['ただ.しい','まさ'],
    words:[{w:'正しい',f:'ただしい',m:'correcto',l:'N5'},{w:'正月',f:'しょうがつ',m:'año nuevo',l:'N5'},{w:'正直',f:'しょうじき',m:'honesto',l:'N4'},{w:'正確',f:'せいかく',m:'exacto / preciso',l:'N4'}]},
  { rank:150, k:'院', level:'N4', meanings:['institución','templo','hospital'], on:['イン'], kun:[],
    words:[{w:'病院',f:'びょういん',m:'hospital',l:'N5'},{w:'美容院',f:'びよういん',m:'peluquería',l:'N4'},{w:'大学院',f:'だいがくいん',m:'posgrado',l:'N4'},{w:'入院',f:'にゅういん',m:'hospitalización',l:'N4'}]},
  { rank:157, k:'心', level:'N4', meanings:['corazón','mente'], on:['シン'], kun:['こころ'],
    words:[{w:'安心',f:'あんしん',m:'tranquilidad',l:'N4'},{w:'心配',f:'しんぱい',m:'preocupación',l:'N4'},{w:'中心',f:'ちゅうしん',m:'centro',l:'N4'},{w:'関心',f:'かんしん',m:'interés / inquietud',l:'N4'},{w:'熱心',f:'ねっしん',m:'entusiasta / dedicado',l:'N4'}]},
  { rank:158, k:'界', level:'N4', meanings:['mundo','frontera','ámbito'], on:['カイ'], kun:[],
    words:[{w:'世界',f:'せかい',m:'mundo',l:'N5'},]},
  { rank:166, k:'教', level:'N4', meanings:['enseñar'], on:['キョウ'], kun:['おし.える'],
    words:[{w:'教室',f:'きょうしつ',m:'aula',l:'N5'},{w:'教育',f:'きょういく',m:'educación',l:'N4'},{w:'教科書',f:'きょうかしょ',m:'libro de texto',l:'N4'},]},
  { rank:190, k:'文', level:'N4', meanings:['texto','escritura'], on:['ブン','モン'], kun:['ふみ'],
    words:[{w:'文化',f:'ぶんか',m:'cultura',l:'N4'},{w:'作文',f:'さくぶん',m:'redacción',l:'N4'},{w:'文法',f:'ぶんぽう',m:'gramática',l:'N4'}]},
  { rank:192, k:'元', level:'N4', meanings:['origen','comienzo','antes'], on:['ゲン','ガン'], kun:['もと'],
    words:[{w:'元気',f:'げんき',m:'energía / salud',l:'N5'},{w:'元々',f:'もともと',m:'originalmente',l:'N4'},{w:'元日',f:'がんじつ',m:'día de año nuevo',l:'N4'},{w:'地元',f:'じもと',m:'local / de la zona',l:'N4'}]},
  { rank:193, k:'重', level:'N4', meanings:['pesado','importante'], on:['ジュウ','チョウ'], kun:['おも.い','かさ.なる'],
    words:[{w:'重い',f:'おもい',m:'pesado',l:'N5'},{w:'重要',f:'じゅうよう',m:'importante',l:'N4'},]},
  { rank:194, k:'近', level:'N4', meanings:['cerca'], on:['キン'], kun:['ちか.い'],
    words:[{w:'近い',f:'ちかい',m:'cercano',l:'N5'},{w:'近所',f:'きんじょ',m:'vecindario',l:'N4'},{w:'最近',f:'さいきん',m:'recientemente',l:'N4'}]},
  { rank:196, k:'考', level:'N4', meanings:['considerar','pensar'], on:['コウ'], kun:['かんが.える'],
    words:[{w:'参考',f:'さんこう',m:'referencia',l:'N4'},]},
  { rank:199, k:'画', level:'N4', meanings:['imagen','trazar','planificar'], on:['ガ','カク'], kun:['かく','えが.く'],
    words:[{w:'映画',f:'えいが',m:'película',l:'N5'},{w:'計画',f:'けいかく',m:'plan',l:'N4'},{w:'画家',f:'がか',m:'pintor / artista',l:'N4'},{w:'漫画',f:'まんが',m:'manga / cómic',l:'N4'}]},
  { rank:200, k:'海', level:'N4', meanings:['mar'], on:['カイ'], kun:['うみ'],
    words:[{w:'海外',f:'かいがい',m:'extranjero / ultramar',l:'N4'},{w:'日本海',f:'にほんかい',m:'Mar de Japón',l:'N4'},{w:'海岸',f:'かいがん',m:'costa / playa',l:'N4'},{w:'海水',f:'かいすい',m:'agua de mar',l:'N4'},]},
  { rank:202, k:'売', level:'N4', meanings:['vender'], on:['バイ'], kun:['う.る'],
    words:[{w:'売り場',f:'うりば',m:'mostrador de ventas',l:'N4'},{w:'売買',f:'ばいばい',m:'compraventa',l:'N4'},{w:'販売',f:'はんばい',m:'venta',l:'N4'},]},
  { rank:205, k:'知', level:'N4', meanings:['saber','conocer'], on:['チ'], kun:['し.る'],
    words:[{w:'知識',f:'ちしき',m:'conocimiento',l:'N4'},{w:'知人',f:'ちじん',m:'conocido',l:'N4'},{w:'通知',f:'つうち',m:'notificación / aviso',l:'N4'},]},
  { rank:210, k:'集', level:'N4', meanings:['reunir','congregar'], on:['シュウ'], kun:['あつ.める'],
    words:[{w:'集合',f:'しゅうごう',m:'reunión / punto de encuentro',l:'N4'},{w:'集中',f:'しゅうちゅう',m:'concentración',l:'N4'}]},
  { rank:214, k:'別', level:'N4', meanings:['separar','diferente','otro'], on:['ベツ'], kun:['わか.れる'],
    words:[{w:'特別',f:'とくべつ',m:'especial',l:'N4'},{w:'別に',f:'べつに',m:'especialmente / en particular',l:'N4'},{w:'別々',f:'べつべつ',m:'por separado',l:'N4'},]},
  { rank:215, k:'物', level:'N4', meanings:['cosa','objeto','asunto'], on:['ブツ','モツ'], kun:['もの'],
    words:[{w:'食べ物',f:'たべもの',m:'comida',l:'N5'},{w:'飲み物',f:'のみもの',m:'bebida',l:'N5'},{w:'荷物',f:'にもつ',m:'equipaje',l:'N4'},{w:'物語',f:'ものがたり',m:'historia / cuento',l:'N4'}]},
  { rank:219, k:'使', level:'N4', meanings:['usar'], on:['シ'], kun:['つか.う'],
    words:[{w:'使い方',f:'つかいかた',m:'forma de usar',l:'N5'},{w:'使用',f:'しよう',m:'uso / utilización',l:'N4'}]},
  { rank:225, k:'品', level:'N4', meanings:['artículo','producto','calidad'], on:['ヒン','ホン'], kun:['しな'],
    words:[{w:'品物',f:'しなもの',m:'artículo / mercancía',l:'N4'},{w:'作品',f:'さくひん',m:'obra',l:'N4'},{w:'食品',f:'しょくひん',m:'alimento / producto alimenticio',l:'N4'},]},
  { rank:228, k:'計', level:'N4', meanings:['medir','calcular','plan'], on:['ケイ'], kun:['はか.る'],
    words:[{w:'時計',f:'とけい',m:'reloj',l:'N5'},{w:'計画',f:'けいかく',m:'plan',l:'N4'},{w:'合計',f:'ごうけい',m:'total',l:'N4'},{w:'計算',f:'けいさん',m:'cálculo',l:'N4'}]},
  { rank:229, k:'死', level:'N4', meanings:['morir','muerte'], on:['シ'], kun:['し.ぬ'],
    words:[{w:'必死',f:'ひっし',m:'desesperado',l:'N3'},]},
  { rank:233, k:'感', level:'N4', meanings:['sentir','emoción'], on:['カン'], kun:[],
    words:[{w:'感動',f:'かんどう',m:'emoción profunda',l:'N4'},{w:'感想',f:'かんそう',m:'impresión / opinión',l:'N4'},]},
  { rank:234, k:'特', level:'N4', meanings:['especial','particular'], on:['トク'], kun:[],
    words:[{w:'特別',f:'とくべつ',m:'especial',l:'N4'},{w:'特に',f:'とくに',m:'especialmente',l:'N4'},{w:'特急',f:'とっきゅう',m:'tren expreso',l:'N4'},]},
  { rank:242, k:'私', level:'N4', meanings:['yo','privado'], on:['シ'], kun:['わたし','わたくし'],
    words:[{w:'私',f:'わたし',m:'yo',l:'N5'},{w:'私立',f:'しりつ',m:'privado',l:'N4'},]},
  { rank:244, k:'始', level:'N4', meanings:['comenzar'], on:['シ'], kun:['はじ.める','はじ.まる'],
    words:[{w:'開始',f:'かいし',m:'inicio',l:'N4'},{w:'始発',f:'しはつ',m:'primer tren / primera salida',l:'N4'},{w:'年始',f:'ねんし',m:'comienzo del año',l:'N4'}]},
  { rank:248, k:'朝', level:'N4', meanings:['mañana'], on:['チョウ'], kun:['あさ'],
    words:[{w:'朝',f:'あさ',m:'mañana',l:'N5'},{w:'毎朝',f:'まいあさ',m:'cada mañana',l:'N5'},{w:'今朝',f:'けさ',m:'esta mañana',l:'N5'},{w:'朝食',f:'ちょうしょく',m:'desayuno',l:'N4'},]},
  { rank:255, k:'運', level:'N4', meanings:['transportar','suerte','destino'], on:['ウン'], kun:['はこ.ぶ'],
    words:[{w:'運転',f:'うんてん',m:'conducción',l:'N5'},{w:'運動',f:'うんどう',m:'ejercicio / movimiento',l:'N4'},{w:'幸運',f:'こううん',m:'buena suerte',l:'N4'}]},
  { rank:256, k:'終', level:'N4', meanings:['terminar','fin'], on:['シュウ'], kun:['お.わる'],
    words:[{w:'終電',f:'しゅうでん',m:'último tren',l:'N4'},{w:'最終',f:'さいしゅう',m:'último / final',l:'N4'},{w:'終点',f:'しゅうてん',m:'terminal / última parada',l:'N4'},]},
  { rank:262, k:'台', level:'N4', meanings:['plataforma','pedestal','contador de vehículos'], on:['ダイ','タイ'], kun:['うてな'],
    words:[{w:'台所',f:'だいどころ',m:'cocina',l:'N5'},{w:'台風',f:'たいふう',m:'tifón',l:'N4'},{w:'舞台',f:'ぶたい',m:'escenario',l:'N4'}]},
  { rank:263, k:'広', level:'N4', meanings:['amplio'], on:['コウ'], kun:['ひろ.い'],
    words:[{w:'広い',f:'ひろい',m:'amplio',l:'N5'},{w:'広告',f:'こうこく',m:'publicidad',l:'N4'},{w:'広場',f:'ひろば',m:'plaza',l:'N4'}]},
  { rank:270, k:'住', level:'N4', meanings:['residir','vivir en'], on:['ジュウ'], kun:['す.む'],
    words:[{w:'住所',f:'じゅうしょ',m:'dirección',l:'N4'},{w:'住民',f:'じゅうみん',m:'residente',l:'N4'},{w:'住宅',f:'じゅうたく',m:'vivienda',l:'N4'},]},
  { rank:279, k:'真', level:'N4', meanings:['verdad','realidad','auténtico'], on:['シン'], kun:['ま','まこと'],
    words:[{w:'写真',f:'しゃしん',m:'fotografía',l:'N5'},{w:'真剣',f:'しんけん',m:'serio / en serio',l:'N4'},{w:'真っ直ぐ',f:'まっすぐ',m:'recto / directo',l:'N4'},]},
  { rank:282, k:'有', level:'N4', meanings:['tener','existir','poseer'], on:['ユウ','ウ'], kun:['あ.る'],
    words:[{w:'有名',f:'ゆうめい',m:'famoso',l:'N5'},{w:'有料',f:'ゆうりょう',m:'de pago',l:'N4'},]},
  { rank:292, k:'町', level:'N4', meanings:['ciudad','barrio','manzana'], on:['チョウ'], kun:['まち'],
    words:[{w:'町',f:'まち',m:'ciudad / barrio',l:'N5'},{w:'下町',f:'したまち',m:'barrio antiguo',l:'N4'}]},
  { rank:295, k:'料', level:'N4', meanings:['tarifa','ingrediente'], on:['リョウ'], kun:[],
    words:[{w:'料理',f:'りょうり',m:'cocina / plato',l:'N5'},{w:'料金',f:'りょうきん',m:'tarifa / precio',l:'N4'},{w:'材料',f:'ざいりょう',m:'ingredientes / materiales',l:'N4'},{w:'無料',f:'むりょう',m:'gratis',l:'N4'},{w:'有料',f:'ゆうりょう',m:'de pago',l:'N4'}]},
  { rank:299, k:'工', level:'N4', meanings:['artesanía','construcción','trabajo'], on:['コウ','ク'], kun:[],
    words:[{w:'工場',f:'こうじょう',m:'fábrica',l:'N4'},{w:'工事',f:'こうじ',m:'obra / construcción',l:'N4'},]},
  { rank:300, k:'建', level:'N4', meanings:['construir','edificar'], on:['ケン','コン'], kun:['た.てる'],
    words:[{w:'建物',f:'たてもの',m:'edificio',l:'N5'},{w:'建設',f:'けんせつ',m:'construcción',l:'N3'},]},
  { rank:309, k:'急', level:'N4', meanings:['urgente','rápido'], on:['キュウ'], kun:['いそ.ぐ'],
    words:[{w:'急行',f:'きゅうこう',m:'tren expreso',l:'N4'},{w:'急用',f:'きゅうよう',m:'asunto urgente',l:'N3'},]},
  { rank:310, k:'止', level:'N4', meanings:['parar','detener'], on:['シ'], kun:['と.まる','や.める'],
    words:[{w:'禁止',f:'きんし',m:'prohibición',l:'N4'},{w:'中止',f:'ちゅうし',m:'cancelación',l:'N4'},]},
  { rank:311, k:'送', level:'N4', meanings:['enviar','mandar'], on:['ソウ'], kun:['おく.る'],
    words:[{w:'放送',f:'ほうそう',m:'emisión / transmisión',l:'N4'},{w:'送料',f:'そうりょう',m:'gastos de envío',l:'N4'},{w:'郵送',f:'ゆうそう',m:'envío postal',l:'N4'}]},
  { rank:324, k:'切', level:'N4', meanings:['cortar','importante'], on:['セツ','サイ'], kun:['き.る'],
    words:[{w:'大切',f:'たいせつ',m:'importante',l:'N5'},{w:'切符',f:'きっぷ',m:'billete',l:'N5'}]},
  { rank:327, k:'転', level:'N4', meanings:['rodar','girar','cambiar'], on:['テン'], kun:['ころ.ぶ','うつ.る'],
    words:[{w:'自転車',f:'じてんしゃ',m:'bicicleta',l:'N5'},{w:'運転',f:'うんてん',m:'conducción',l:'N5'},{w:'転校',f:'てんこう',m:'cambio de escuela',l:'N4'}]},
  { rank:336, k:'研', level:'N4', meanings:['pulir','estudiar'], on:['ケン'], kun:['と.ぐ'],
    words:[{w:'研究',f:'けんきゅう',m:'investigación',l:'N4'},]},
  { rank:368, k:'究', level:'N4', meanings:['investigar','estudiar a fondo'], on:['キュウ'], kun:['きわ.める'],
    words:[{w:'研究',f:'けんきゅう',m:'investigación',l:'N4'},]},
  { rank:373, k:'楽', level:'N4', meanings:['música','placer','fácil'], on:['ガク','ラク'], kun:['たの.しい'],
    words:[{w:'音楽',f:'おんがく',m:'música',l:'N5'},{w:'楽しい',f:'たのしい',m:'divertido / placentero',l:'N5'},{w:'気楽',f:'きらく',m:'relajado / despreocupado',l:'N4'},{w:'楽器',f:'がっき',m:'instrumento musical',l:'N4'}]},
  { rank:374, k:'起', level:'N4', meanings:['levantarse','ocurrir'], on:['キ'], kun:['お.きる','お.こる'],
    words:[{w:'早起き',f:'はやおき',m:'madrugar',l:'N4'},]},
  { rank:376, k:'着', level:'N4', meanings:['llegar','ponerse ropa'], on:['チャク','ジャク'], kun:['き.る','つ.く'],
    words:[{w:'到着',f:'とうちゃく',m:'llegada',l:'N4'},{w:'着替え',f:'きがえ',m:'cambiarse de ropa',l:'N4'}]},
  { rank:377, k:'乗', level:'N4', meanings:['montar','subir a'], on:['ジョウ'], kun:['の.る'],
    words:[{w:'乗り換え',f:'のりかえ',m:'transbordo',l:'N4'},{w:'乗客',f:'じょうきゃく',m:'pasajero',l:'N4'},{w:'乗車',f:'じょうしゃ',m:'subir al vehículo',l:'N4'},]},
  { rank:384, k:'病', level:'N4', meanings:['enfermedad'], on:['ビョウ','ヘイ'], kun:['や.む'],
    words:[{w:'病院',f:'びょういん',m:'hospital',l:'N5'},{w:'病気',f:'びょうき',m:'enfermedad',l:'N5'},{w:'病室',f:'びょうしつ',m:'habitación de hospital',l:'N4'}]},
  { rank:388, k:'声', level:'N4', meanings:['voz'], on:['セイ','ショウ'], kun:['こえ'],
    words:[{w:'声',f:'こえ',m:'voz',l:'N5'},{w:'大声',f:'おおごえ',m:'voz alta',l:'N4'},]},
  { rank:389, k:'質', level:'N4', meanings:['calidad','sustancia','pregunta'], on:['シツ','シチ'], kun:['たち'],
    words:[{w:'質問',f:'しつもん',m:'pregunta',l:'N5'},]},
  { rank:391, k:'待', level:'N4', meanings:['esperar'], on:['タイ'], kun:['ま.つ'],
    words:[{w:'待つ',f:'まつ',m:'esperar',l:'N5'},{w:'期待',f:'きたい',m:'expectativa',l:'N4'},{w:'招待',f:'しょうたい',m:'invitación',l:'N4'}]},
  { rank:392, k:'試', level:'N4', meanings:['probar','experimentar'], on:['シ'], kun:['こころ.みる','ため.す'],
    words:[{w:'試験',f:'しけん',m:'examen',l:'N5'},{w:'試合',f:'しあい',m:'partido / encuentro',l:'N4'},{w:'入試',f:'にゅうし',m:'examen de ingreso',l:'N4'}]},
  { rank:393, k:'族', level:'N4', meanings:['tribu','familia','grupo'], on:['ゾク'], kun:[],
    words:[{w:'家族',f:'かぞく',m:'familia',l:'N5'},{w:'水族館',f:'すいぞくかん',m:'acuario',l:'N4'},]},
  { rank:395, k:'銀', level:'N4', meanings:['plata','banco'], on:['ギン'], kun:[],
    words:[{w:'銀行',f:'ぎんこう',m:'banco',l:'N5'},{w:'銀色',f:'ぎんいろ',m:'color plata',l:'N4'}]},
  { rank:402, k:'早', level:'N4', meanings:['temprano','rápido'], on:['ソウ','サッ'], kun:['はや.い'],
    words:[{w:'早い',f:'はやい',m:'temprano / rápido',l:'N5'},{w:'早速',f:'さっそく',m:'de inmediato',l:'N4'},]},
  { rank:404, k:'映', level:'N4', meanings:['proyectar','reflejar'], on:['エイ'], kun:['うつ.る'],
    words:[{w:'映画',f:'えいが',m:'película',l:'N5'},{w:'映画館',f:'えいがかん',m:'cine',l:'N5'},]},
  { rank:406, k:'親', level:'N4', meanings:['padre/madre','pariente','íntimo'], on:['シン'], kun:['おや','した.しい'],
    words:[{w:'親',f:'おや',m:'padre o madre',l:'N5'},{w:'親切',f:'しんせつ',m:'amabilidad',l:'N5'},{w:'両親',f:'りょうしん',m:'ambos padres',l:'N4'},{w:'親友',f:'しんゆう',m:'amigo íntimo',l:'N4'}]},
  { rank:410, k:'験', level:'N4', meanings:['examen','experiencia','efecto'], on:['ケン'], kun:[],
    words:[{w:'試験',f:'しけん',m:'examen',l:'N5'},{w:'経験',f:'けいけん',m:'experiencia',l:'N4'},{w:'受験',f:'じゅけん',m:'presentarse a un examen',l:'N4'},]},
  { rank:417, k:'働', level:'N4', meanings:['trabajar'], on:['ドウ'], kun:['はたら.く'],
    words:[{w:'労働',f:'ろうどう',m:'trabajo / labor',l:'N4'},]},
  { rank:430, k:'英', level:'N4', meanings:['inglés','Gran Bretaña','brillante'], on:['エイ'], kun:[],
    words:[{w:'英語',f:'えいご',m:'inglés',l:'N5'},{w:'英国',f:'えいこく',m:'Reino Unido',l:'N4'},{w:'英会話',f:'えいかいわ',m:'conversación en inglés',l:'N4'},]},
  { rank:433, k:'頭', level:'N4', meanings:['cabeza'], on:['トウ','ズ'], kun:['あたま','かしら'],
    words:[{w:'頭',f:'あたま',m:'cabeza',l:'N5'},{w:'頭痛',f:'ずつう',m:'dolor de cabeza',l:'N4'},]},
  { rank:437, k:'医', level:'N4', meanings:['medicina','médico'], on:['イ'], kun:[],
    words:[{w:'医者',f:'いしゃ',m:'médico',l:'N5'},{w:'医学',f:'いがく',m:'medicina (ciencia)',l:'N4'},{w:'医療',f:'いりょう',m:'atención médica',l:'N4'},{w:'医院',f:'いいん',m:'clínica',l:'N4'},]},
  { rank:439, k:'仕', level:'N4', meanings:['servir','hacer'], on:['シ'], kun:[],
    words:[{w:'仕事',f:'しごと',m:'trabajo',l:'N5'},{w:'仕方',f:'しかた',m:'manera / forma',l:'N4'},]},
  { rank:440, k:'去', level:'N4', meanings:['irse','pasado'], on:['キョ','コ'], kun:['さ.る'],
    words:[{w:'去年',f:'きょねん',m:'el año pasado',l:'N5'},{w:'過去',f:'かこ',m:'pasado',l:'N4'},]},
  { rank:442, k:'味', level:'N4', meanings:['sabor','gusto','interés'], on:['ミ'], kun:['あじ'],
    words:[{w:'味',f:'あじ',m:'sabor',l:'N5'},{w:'意味',f:'いみ',m:'significado',l:'N5'},{w:'趣味',f:'しゅみ',m:'afición / pasatiempo',l:'N5'}]},
  { rank:453, k:'写', level:'N4', meanings:['copiar','fotografiar'], on:['シャ'], kun:['うつ.す'],
    words:[{w:'写真',f:'しゃしん',m:'fotografía',l:'N5'},{w:'写真館',f:'しゃしんかん',m:'estudio fotográfico',l:'N4'},{w:'複写',f:'ふくしゃ',m:'copia',l:'N4'},]},
  { rank:485, k:'字', level:'N4', meanings:['carácter','letra'], on:['ジ'], kun:['あざ'],
    words:[{w:'漢字',f:'かんじ',m:'kanji',l:'N5'},{w:'文字',f:'もじ',m:'carácter / letra',l:'N4'},{w:'数字',f:'すうじ',m:'número',l:'N4'}]},
  { rank:486, k:'答', level:'N4', meanings:['respuesta','contestar'], on:['トウ'], kun:['こた.える'],
    words:[{w:'答え',f:'こたえ',m:'respuesta',l:'N5'},{w:'回答',f:'かいとう',m:'respuesta / contestación',l:'N4'},{w:'解答',f:'かいとう',m:'solución',l:'N4'}]},
  { rank:487, k:'夜', level:'N4', meanings:['noche'], on:['ヤ'], kun:['よる','よ'],
    words:[{w:'夜',f:'よる',m:'noche',l:'N5'},{w:'今夜',f:'こんや',m:'esta noche',l:'N5'},{w:'夜中',f:'よなか',m:'medianoche',l:'N4'},{w:'夜景',f:'やけい',m:'vista nocturna',l:'N4'},]},
  { rank:491, k:'音', level:'N4', meanings:['sonido'], on:['オン','イン'], kun:['おと','ね'],
    words:[{w:'音楽',f:'おんがく',m:'música',l:'N5'},{w:'音読み',f:'おんよみ',m:'lectura on del kanji',l:'N5'},{w:'発音',f:'はつおん',m:'pronunciación',l:'N4'},{w:'音声',f:'おんせい',m:'voz / sonido',l:'N4'},]},
  { rank:497, k:'注', level:'N4', meanings:['verter','anotar','prestar atención'], on:['チュウ'], kun:['そそ.ぐ','さ.す'],
    words:[{w:'注文',f:'ちゅうもん',m:'pedido',l:'N5'},{w:'注意',f:'ちゅうい',m:'atención / cuidado',l:'N4'},{w:'注射',f:'ちゅうしゃ',m:'inyección',l:'N4'},{w:'注目',f:'ちゅうもく',m:'atención / foco',l:'N4'}]},
  { rank:504, k:'帰', level:'N4', meanings:['regresar'], on:['キ'], kun:['かえ.る'],
    words:[{w:'帰国',f:'きこく',m:'regreso al país',l:'N4'},{w:'日帰り',f:'ひがえり',m:'excursión de un día',l:'N4'}]},
  { rank:519, k:'歌', level:'N4', meanings:['cantar','canción'], on:['カ'], kun:['うた.う','うた'],
    words:[{w:'歌手',f:'かしゅ',m:'cantante',l:'N4'}]},
  { rank:527, k:'光', level:'N4', meanings:['luz','brillar'], on:['コウ'], kun:['ひかり'],
    words:[{w:'光',f:'ひかり',m:'luz',l:'N5'},{w:'観光',f:'かんこう',m:'turismo',l:'N4'},]},
  { rank:530, k:'悪', level:'N4', meanings:['malo','malvado'], on:['アク','オ'], kun:['わる.い'],
    words:[{w:'悪い',f:'わるい',m:'malo',l:'N5'},{w:'最悪',f:'さいあく',m:'pésimo',l:'N4'},{w:'悪口',f:'わるくち',m:'hablar mal de alguien',l:'N4'},]},
  { rank:539, k:'図', level:'N4', meanings:['mapa','diagrama'], on:['ズ','ト'], kun:['はか.る'],
    words:[{w:'地図',f:'ちず',m:'mapa',l:'N5'},{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'図形',f:'ずけい',m:'figura geométrica',l:'N4'}]},
  { rank:550, k:'室', level:'N4', meanings:['habitación','sala'], on:['シツ'], kun:['むろ'],
    words:[{w:'教室',f:'きょうしつ',m:'aula',l:'N5'},{w:'洋室',f:'ようしつ',m:'habitación al estilo occidental',l:'N4'},{w:'和室',f:'わしつ',m:'habitación al estilo japonés',l:'N4'},{w:'個室',f:'こしつ',m:'habitación individual / privada',l:'N4'}]},
  { rank:554, k:'歩', level:'N4', meanings:['caminar','paso'], on:['ホ','ブ'], kun:['ある.く','あゆ.む'],
    words:[{w:'散歩',f:'さんぽ',m:'paseo',l:'N5'},{w:'進歩',f:'しんぽ',m:'progreso',l:'N4'},{w:'一歩',f:'いっぽ',m:'un paso',l:'N4'}]},
  { rank:558, k:'風', level:'N4', meanings:['viento'], on:['フウ','フ'], kun:['かぜ'],
    words:[{w:'風',f:'かぜ',m:'viento',l:'N5'},{w:'台風',f:'たいふう',m:'tifón',l:'N4'},{w:'風景',f:'ふうけい',m:'paisaje',l:'N4'}]},
  { rank:559, k:'紙', level:'N4', meanings:['papel'], on:['シ'], kun:['かみ'],
    words:[{w:'手紙',f:'てがみ',m:'carta',l:'N5'},{w:'新聞紙',f:'しんぶんし',m:'papel de periódico',l:'N4'},{w:'折り紙',f:'おりがみ',m:'origami',l:'N4'}]},
  { rank:573, k:'黒', level:'N4', meanings:['negro'], on:['コク'], kun:['くろ'],
    words:[{w:'黒い',f:'くろい',m:'negro',l:'N5'},{w:'黒板',f:'こくばん',m:'pizarra',l:'N5'},]},
  { rank:579, k:'春', level:'N4', meanings:['primavera'], on:['シュン'], kun:['はる'],
    words:[{w:'春',f:'はる',m:'primavera',l:'N5'},{w:'春休み',f:'はるやすみ',m:'vacaciones de primavera',l:'N4'}]},
  { rank:580, k:'飛', level:'N4', meanings:['volar'], on:['ヒ'], kun:['と.ぶ'],
    words:[{w:'飛行機',f:'ひこうき',m:'avión',l:'N5'},]},
  { rank:584, k:'赤', level:'N4', meanings:['rojo'], on:['セキ','シャク'], kun:['あか'],
    words:[{w:'赤い',f:'あかい',m:'rojo',l:'N5'},{w:'赤ちゃん',f:'あかちゃん',m:'bebé',l:'N5'},{w:'赤信号',f:'あかしんごう',m:'semáforo en rojo',l:'N4'},]},
  { rank:589, k:'青', level:'N4', meanings:['azul','verde'], on:['セイ','ショウ'], kun:['あお'],
    words:[{w:'青い',f:'あおい',m:'azul / verde',l:'N5'},{w:'青空',f:'あおぞら',m:'cielo azul',l:'N4'},{w:'青信号',f:'あおしんごう',m:'semáforo en verde',l:'N4'},]},
  { rank:613, k:'館', level:'N4', meanings:['edificio','sala'], on:['カン'], kun:['やかた'],
    words:[{w:'図書館',f:'としょかん',m:'biblioteca',l:'N5'},{w:'映画館',f:'えいがかん',m:'cine',l:'N5'},{w:'水族館',f:'すいぞくかん',m:'acuario',l:'N4'},{w:'旅館',f:'りょかん',m:'posada japonesa',l:'N4'}]},
  { rank:616, k:'屋', level:'N4', meanings:['tienda','casa','techo'], on:['オク'], kun:['や'],
    words:[{w:'本屋',f:'ほんや',m:'librería',l:'N5'},{w:'部屋',f:'へや',m:'habitación',l:'N5'},{w:'八百屋',f:'やおや',m:'frutería / verdulería',l:'N4'},{w:'肉屋',f:'にくや',m:'carnicería',l:'N4'}]},
  { rank:621, k:'色', level:'N4', meanings:['color'], on:['ショク','シキ'], kun:['いろ'],
    words:[{w:'色',f:'いろ',m:'color',l:'N5'},{w:'茶色',f:'ちゃいろ',m:'marrón',l:'N5'},{w:'景色',f:'けしき',m:'paisaje',l:'N4'},{w:'色々',f:'いろいろ',m:'varios / diverso',l:'N4'},]},
  { rank:626, k:'走', level:'N4', meanings:['correr'], on:['ソウ'], kun:['はし.る'],
    words:[{w:'競走',f:'きょうそう',m:'carrera',l:'N4'},{w:'走者',f:'そうしゃ',m:'corredor',l:'N4'},]},
  { rank:635, k:'秋', level:'N4', meanings:['otoño'], on:['シュウ'], kun:['あき'],
    words:[{w:'秋',f:'あき',m:'otoño',l:'N5'},]},
  { rank:659, k:'夏', level:'N4', meanings:['verano'], on:['カ','ゲ'], kun:['なつ'],
    words:[{w:'夏',f:'なつ',m:'verano',l:'N5'},{w:'夏休み',f:'なつやすみ',m:'vacaciones de verano',l:'N5'},]},
  { rank:676, k:'顔', level:'N4', meanings:['cara','rostro'], on:['ガン'], kun:['かお'],
    words:[{w:'顔',f:'かお',m:'cara',l:'N5'},{w:'笑顔',f:'えがお',m:'sonrisa',l:'N4'},{w:'顔色',f:'かおいろ',m:'color de la cara / expresión',l:'N4'},]},
  { rank:702, k:'薬', level:'N4', meanings:['medicina','fármaco'], on:['ヤク'], kun:['くすり'],
    words:[{w:'薬',f:'くすり',m:'medicina',l:'N5'},{w:'薬局',f:'やっきょく',m:'farmacia',l:'N4'},{w:'目薬',f:'めぐすり',m:'colirio',l:'N4'},]},
  { rank:706, k:'習', level:'N4', meanings:['aprender','practicar'], on:['シュウ'], kun:['なら.う'],
    words:[{w:'練習',f:'れんしゅう',m:'práctica',l:'N5'},{w:'学習',f:'がくしゅう',m:'aprendizaje',l:'N4'},{w:'習慣',f:'しゅうかん',m:'costumbre / hábito',l:'N4'},]},
  { rank:763, k:'洋', level:'N4', meanings:['océano','occidental'], on:['ヨウ'], kun:[],
    words:[{w:'洋服',f:'ようふく',m:'ropa occidental',l:'N5'},{w:'西洋',f:'せいよう',m:'occidente',l:'N4'},{w:'東洋',f:'とうよう',m:'oriente',l:'N4'},{w:'洋食',f:'ようしょく',m:'comida occidental',l:'N4'}]},
  { rank:783, k:'旅', level:'N4', meanings:['viaje','viajar'], on:['リョ'], kun:['たび'],
    words:[{w:'旅行',f:'りょこう',m:'viaje',l:'N5'},{w:'旅館',f:'りょかん',m:'posada japonesa',l:'N4'},{w:'旅人',f:'たびびと',m:'viajero',l:'N4'},{w:'旅費',f:'りょひ',m:'gastos de viaje',l:'N4'}]},
  { rank:788, k:'練', level:'N4', meanings:['practicar','entrenar'], on:['レン'], kun:['ね.る'],
    words:[{w:'練習',f:'れんしゅう',m:'práctica',l:'N5'},{w:'訓練',f:'くんれん',m:'entrenamiento',l:'N4'},]},
  { rank:790, k:'軽', level:'N4', meanings:['ligero','leve'], on:['ケイ'], kun:['かる.い'],
    words:[{w:'軽い',f:'かるい',m:'ligero',l:'N5'},{w:'気軽',f:'きがる',m:'despreocupado',l:'N4'},]},
  { rank:833, k:'遅', level:'N4', meanings:['tarde','lento'], on:['チ'], kun:['おそ.い','おく.れる'],
    words:[{w:'遅い',f:'おそい',m:'tarde / lento',l:'N5'},{w:'遅刻',f:'ちこく',m:'llegar tarde',l:'N4'},]},
  { rank:873, k:'服', level:'N4', meanings:['ropa','prenda'], on:['フク'], kun:[],
    words:[{w:'洋服',f:'ようふく',m:'ropa occidental',l:'N5'},{w:'制服',f:'せいふく',m:'uniforme',l:'N4'},{w:'和服',f:'わふく',m:'ropa japonesa',l:'N4'}]},
  { rank:887, k:'遠', level:'N4', meanings:['lejos'], on:['エン','オン'], kun:['とお.い'],
    words:[{w:'遠い',f:'とおい',m:'lejano',l:'N5'},{w:'遠足',f:'えんそく',m:'excursión',l:'N4'},]},
  { rank:895, k:'絵', level:'N4', meanings:['pintura','cuadro'], on:['カイ','エ'], kun:[],
    words:[{w:'絵',f:'え',m:'pintura / dibujo',l:'N5'},{w:'絵本',f:'えほん',m:'libro ilustrado',l:'N5'},]},
  { rank:924, k:'夕', level:'N4', meanings:['tarde','atardecer'], on:['セキ'], kun:['ゆう'],
    words:[{w:'夕方',f:'ゆうがた',m:'tarde / atardecer',l:'N5'},{w:'夕食',f:'ゆうしょく',m:'cena',l:'N5'},{w:'夕日',f:'ゆうひ',m:'sol del atardecer',l:'N4'},{w:'夕暮れ',f:'ゆうぐれ',m:'anochecer',l:'N4'}]},
  { rank:932, k:'借', level:'N4', meanings:['pedir prestado','alquilar'], on:['シャク'], kun:['か.りる'],
    words:[{w:'借金',f:'しゃっきん',m:'deuda',l:'N4'},{w:'借家',f:'しゃくや',m:'casa de alquiler',l:'N4'},]},
  { rank:940, k:'曜', level:'N4', meanings:['día de la semana'], on:['ヨウ'], kun:[],
    words:[{w:'月曜日',f:'げつようび',m:'lunes',l:'N5'},{w:'火曜日',f:'かようび',m:'martes',l:'N5'},{w:'水曜日',f:'すいようび',m:'miércoles',l:'N5'},{w:'何曜日',f:'なんようび',m:'¿qué día de la semana?',l:'N5'}]},
  { rank:958, k:'弱', level:'N4', meanings:['débil'], on:['ジャク'], kun:['よわ.い'],
    words:[{w:'弱い',f:'よわい',m:'débil',l:'N5'},{w:'弱点',f:'じゃくてん',m:'punto débil',l:'N4'},]},
  { rank:986, k:'肉', level:'N4', meanings:['carne'], on:['ニク'], kun:[],
    words:[{w:'牛肉',f:'ぎゅうにく',m:'carne de vaca',l:'N5'},]},
  { rank:995, k:'貸', level:'N4', meanings:['prestar','alquilar (a otro)'], on:['タイ'], kun:['か.す'],
    words:[{w:'貸し出し',f:'かしだし',m:'préstamo',l:'N4'},{w:'貸家',f:'かしや',m:'casa en alquiler',l:'N4'}]},
  { rank:1010, k:'堂', level:'N4', meanings:['sala pública','comedor','templo'], on:['ドウ'], kun:[],
    words:[{w:'食堂',f:'しょくどう',m:'comedor / cantina',l:'N5'},{w:'講堂',f:'こうどう',m:'auditorio',l:'N4'},]},
  { rank:1034, k:'寝', level:'N4', meanings:['dormir'], on:['シン'], kun:['ね.る'],
    words:[{w:'寝室',f:'しんしつ',m:'dormitorio',l:'N4'},{w:'昼寝',f:'ひるね',m:'siesta',l:'N4'}]},
  { rank:1040, k:'暗', level:'N4', meanings:['oscuro'], on:['アン'], kun:['くら.い'],
    words:[{w:'暗い',f:'くらい',m:'oscuro',l:'N5'},{w:'暗記',f:'あんき',m:'memorización',l:'N4'},]},
  { rank:1043, k:'鳥', level:'N4', meanings:['pájaro','ave'], on:['チョウ'], kun:['とり'],
    words:[{w:'鳥',f:'とり',m:'pájaro',l:'N5'},{w:'小鳥',f:'ことり',m:'pajarito',l:'N4'},{w:'渡り鳥',f:'わたりどり',m:'ave migratoria',l:'N4'},{w:'鳥居',f:'とりい',m:'torii (puerta de santuario)',l:'N4'}]},
  { rank:1046, k:'飯', level:'N4', meanings:['arroz cocido','comida'], on:['ハン'], kun:['めし'],
    words:[{w:'ご飯',f:'ごはん',m:'arroz / comida',l:'N5'},{w:'朝ご飯',f:'あさごはん',m:'desayuno',l:'N5'},{w:'夕飯',f:'ゆうはん',m:'cena',l:'N4'}]},
  { rank:1066, k:'勉', level:'N4', meanings:['estudiar','esforzarse'], on:['ベン'], kun:[],
    words:[{w:'勉強',f:'べんきょう',m:'estudio',l:'N5'},]},
  { rank:1090, k:'冬', level:'N4', meanings:['invierno'], on:['トウ'], kun:['ふゆ'],
    words:[{w:'冬',f:'ふゆ',m:'invierno',l:'N5'},{w:'冬休み',f:'ふゆやすみ',m:'vacaciones de invierno',l:'N5'},]},
  { rank:1115, k:'昼', level:'N4', meanings:['mediodía'], on:['チュウ'], kun:['ひる'],
    words:[{w:'昼',f:'ひる',m:'mediodía',l:'N5'},{w:'昼食',f:'ちゅうしょく',m:'almuerzo',l:'N4'},{w:'昼間',f:'ひるま',m:'durante el día',l:'N4'},{w:'昼休み',f:'ひるやすみ',m:'descanso del mediodía',l:'N4'},]},
  { rank:1116, k:'茶', level:'N4', meanings:['té'], on:['チャ','サ'], kun:[],
    words:[{w:'お茶',f:'おちゃ',m:'té',l:'N5'},{w:'茶色',f:'ちゃいろ',m:'color marrón',l:'N5'},{w:'紅茶',f:'こうちゃ',m:'té negro',l:'N4'},{w:'茶道',f:'さどう',m:'ceremonia del té',l:'N4'}]},
  { rank:1131, k:'雪', level:'N4', meanings:['nieve'], on:['セツ'], kun:['ゆき'],
    words:[{w:'雪',f:'ゆき',m:'nieve',l:'N5'},{w:'大雪',f:'おおゆき',m:'nevada intensa',l:'N4'},]},
  { rank:1161, k:'弟', level:'N4', meanings:['hermano menor'], on:['テイ','ダイ'], kun:['おとうと'],
    words:[{w:'弟',f:'おとうと',m:'hermano menor',l:'N5'},{w:'弟子',f:'でし',m:'discípulo / aprendiz',l:'N4'},{w:'兄弟',f:'きょうだい',m:'hermanos',l:'N4'}]},
  { rank:1202, k:'牛', level:'N4', meanings:['vaca','buey'], on:['ギュウ'], kun:['うし'],
    words:[{w:'牛乳',f:'ぎゅうにゅう',m:'leche',l:'N5'},{w:'牛肉',f:'ぎゅうにく',m:'carne de vaca',l:'N5'},{w:'牛丼',f:'ぎゅうどん',m:'cuenco de arroz con carne',l:'N4'}]},
  { rank:1219, k:'兄', level:'N4', meanings:['hermano mayor'], on:['ケイ','キョウ'], kun:['あに'],
    words:[{w:'お兄さん',f:'おにいさん',m:'hermano mayor (respetuoso)',l:'N5'},{w:'兄',f:'あに',m:'hermano mayor (humilde)',l:'N5'},{w:'兄弟',f:'きょうだい',m:'hermanos',l:'N4'}]},
  { rank:1223, k:'泳', level:'N4', meanings:['nadar'], on:['エイ'], kun:['およ.ぐ'],
    words:[{w:'水泳',f:'すいえい',m:'natación',l:'N4'},]},
  { rank:1326, k:'犬', level:'N4', meanings:['perro'], on:['ケン'], kun:['いぬ'],
    words:[{w:'犬',f:'いぬ',m:'perro',l:'N5'},{w:'小犬',f:'こいぬ',m:'perrito / cachorro',l:'N4'},]},
  { rank:1446, k:'妹', level:'N4', meanings:['hermana menor'], on:['マイ'], kun:['いもうと'],
    words:[{w:'妹',f:'いもうと',m:'hermana menor',l:'N5'},{w:'姉妹',f:'しまい',m:'hermanas',l:'N4'}]},
  { rank:1473, k:'姉', level:'N4', meanings:['hermana mayor'], on:['シ'], kun:['あね'],
    words:[{w:'お姉さん',f:'おねえさん',m:'hermana mayor (respetuoso)',l:'N5'},{w:'姉',f:'あね',m:'hermana mayor (humilde)',l:'N5'},{w:'姉妹',f:'しまい',m:'hermanas',l:'N4'}]},
  { rank:1487, k:'漢', level:'N4', meanings:['China','carácter chino','hombre'], on:['カン'], kun:[],
    words:[{w:'漢字',f:'かんじ',m:'kanji / carácter chino',l:'N5'},{w:'漢語',f:'かんご',m:'palabra de origen chino',l:'N4'},{w:'漢文',f:'かんぶん',m:'texto clásico chino',l:'N4'}]}
]
